MLIR: lib/Dialect/AffineOps/AffineOps.cpp File Reference
AffineOps.cpp File Reference
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/Transforms/SideEffectsInterface.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/Support/Debug.h"
#include "mlir/Dialect/AffineOps/AffineOps.cpp.inc"
Macros
#define DEBUG_TYPE "affine-analysis"
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool isFunctionRegion (Region *region)
A utility function to check if a given region is attached to a function.
template<typename AnyMemRefDefOp >
static bool isMemRefSizeValidSymbol (AnyMemRefDefOp memrefDefOp, unsigned index)
Returns true if the 'index' dimension of the memref defined by memrefDefOp is a statically shaped one or defined using a valid symbol.
static bool isDimOpValidSymbol (DimOp dimOp)
Returns true if the result of the dim op is a valid symbol.
static bool isValidAffineIndexOperand (Value value)
template<typename OpTy >
static LogicalResult verifyDimAndSymbolIdentifiers (OpTy &op, Operation::operand_range operands, unsigned numDims)
Utility function to verify that a set of operands are valid dimension and symbol identifiers.
static llvm::SetVector< unsigned > indicesFromAffineApplyOp (ArrayRef< Value > operands)
static AffineMap promoteComposedSymbolsAsDims (AffineMap map, ArrayRef< Value > symbols)
static void composeAffineMapAndOperands (AffineMap *map, SmallVectorImpl< Value > *operands)
Implements map and operands composition and simplification to support makeComposedAffineApply.
template<class MapOrSet >
static void canonicalizePromotedSymbols (MapOrSet *mapOrSet, SmallVectorImpl< Value > *operands)
template<class MapOrSet >
static void canonicalizeMapOrSetAndOperands (MapOrSet *mapOrSet, SmallVectorImpl< Value > *operands)
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
static LogicalResult verify (AffineForOp op)
static ParseResult parseBound (bool isLower, OperationState &result, OpAsmParser &p)
Parse a for operation loop bounds.
static ParseResult parseAffineForOp (OpAsmParser &parser, OperationState &result)
static void printBound (AffineMapAttr boundMap, Operation::operand_range boundOperands, const char *prefix, OpAsmPrinter &p)
static void print (OpAsmPrinter &p, AffineForOp op)
static LogicalResult foldLoopBounds (AffineForOp forOp)
Fold the constant bounds of a loop.
static LogicalResult canonicalizeLoopBounds (AffineForOp forOp)
Canonicalize the bounds of the given loop.
static LogicalResult verify (AffineIfOp op)
static ParseResult parseAffineIfOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffineIfOp op)
static ParseResult parseAffineMinOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffineMinOp op)
static LogicalResult verify (AffineMinOp op)
static ParseResult parseAffinePrefetchOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AffinePrefetchOp op)
static LogicalResult verify (AffinePrefetchOp op)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-analysis"
Definition at line 25 of file AffineOps.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2116 of file AffineOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
canonicalizeLoopBounds()
static LogicalResult canonicalizeLoopBounds (AffineForOp forOp) static
Canonicalize the bounds of the given loop.
Definition at line 1400 of file AffineOps.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), mlir::canonicalizeMapAndOperands(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end(), mlir::PatternRewriter::eraseOp(), mlir::failure(), foldLoopBounds(), mlir::AffineMapAttr::get(), mlir::AffineMap::getConstantMap(), getLowerBoundOperands(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::Value::getParentRegion(), getUpperBoundOperands(), mlir::has_single_element(), mlir::OwningRewritePatternList::insert(), mlir::functional::map(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), mlir::succeeded(), and mlir::success().
canonicalizeMapOrSetAndOperands()
template<class MapOrSet > static void canonicalizeMapOrSetAndOperands (MapOrSet * mapOrSet, SmallVectorImpl< Value > * operands) static
Definition at line 654 of file AffineOps.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::IntegerAttr::getValue(), mlir::m_Constant(), and mlir::matchPattern().
canonicalizePromotedSymbols()
template<class MapOrSet > static void canonicalizePromotedSymbols (MapOrSet * mapOrSet, SmallVectorImpl< Value > * operands) static
Definition at line 611 of file AffineOps.cpp.
References mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::AffineApplyNormalizer::getNumDims(), and mlir::isValidSymbol().
composeAffineMapAndOperands()
static void composeAffineMapAndOperands (AffineMap * map, SmallVectorImpl< Value > * operands) static
Implements map and operands composition and simplification to support makeComposedAffineApply.
This can be called to achieve the same effects on map and operands without creating an AffineApplyOp that needs to be immediately deleted.
Definition at line 578 of file AffineOps.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::AffineApplyNormalizer::getAffineMap(), and mlir::AffineApplyNormalizer::getOperands().
Referenced by mlir::canonicalizeSetAndOperands(), mlir::fullyComposeAffineMapAndOperands(), and mlir::makeComposedAffineApply().
foldLoopBounds()
static LogicalResult foldLoopBounds (AffineForOp forOp) static
Fold the constant bounds of a loop.
Definition at line 1354 of file AffineOps.cpp.
References mlir::AffineMap::constantFold(), mlir::failed(), mlir::failure(), mlir::AffineMap::getNumResults(), mlir::m_Constant(), mlir::matchPattern(), mlir::succeeded(), and mlir::success().
Referenced by canonicalizeLoopBounds().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
It folds the source of any memref_cast into the root operation directly.
Definition at line 820 of file AffineOps.cpp.
References mlir::Operation::getOpOperands(), and mlir::success().
Referenced by mlir::AffineDmaStartOp::fold(), mlir::AffineDmaWaitOp::fold(), mlir::AffineLoadOp::fold(), mlir::AffineStoreOp::fold(), and verify().
indicesFromAffineApplyOp()
static llvm::SetVector<unsigned> indicesFromAffineApplyOp (ArrayRef< Value > operands) static
Definition at line 366 of file AffineOps.cpp.
References mlir::detail::enumerate().
Referenced by promoteComposedSymbolsAsDims().
isDimOpValidSymbol()
static bool isDimOpValidSymbol (DimOp dimOp) static
Returns true if the result of the dim op is a valid symbol.
Definition at line 157 of file AffineOps.cpp.
References mlir::isTopLevelValue().
Referenced by mlir::isValidSymbol().
isFunctionRegion()
static bool isFunctionRegion (Region * region) static
A utility function to check if a given region is attached to a function.
Definition at line 102 of file AffineOps.cpp.
References mlir::Region::getParentOp().
Referenced by mlir::isTopLevelValue(), mlir::isValidDim(), and mlir::isValidSymbol().
isMemRefSizeValidSymbol()
template<typename AnyMemRefDefOp > static bool isMemRefSizeValidSymbol (AnyMemRefDefOp memrefDefOp, unsigned index) static
Returns true if the 'index' dimension of the memref defined by memrefDefOp is a statically shaped one or defined using a valid symbol.
Definition at line 144 of file AffineOps.cpp.
References mlir::ShapedType::isDynamic(), and mlir::isValidSymbol().
isValidAffineIndexOperand()
static bool isValidAffineIndexOperand (Value value) static
Definition at line 202 of file AffineOps.cpp.
References mlir::isValidDim(), and mlir::isValidSymbol().
Referenced by mlir::AffineDmaStartOp::verify(), mlir::AffineDmaWaitOp::verify(), mlir::AffineLoadOp::verify(), mlir::AffineStoreOp::verify(), and verify().
parseAffineForOp()
static ParseResult parseAffineForOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1244 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::IntegerAttr::getValue(), mlir::OperationState::location, mlir::OpAsmParser::parseAttribute(), parseBound(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgument(), mlir::OperationState::setOperandListToResizable(), and mlir::success().
parseAffineIfOp()
static ParseResult parseAffineIfOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1624 of file AffineOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getNameLoc(), mlir::AffineApplyNormalizer::getNumDims(), mlir::AffineApplyNormalizer::getNumSymbols(), mlir::IntegerSetAttr::getValue(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::parseDimAndSymbolList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, and mlir::success().
parseAffineMinOp()
static ParseResult parseAffineMinOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1944 of file AffineOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::OptionalSquare, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseAffinePrefetchOp()
static ParseResult parseAffinePrefetchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2013 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseGreater(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseBound()
static ParseResult parseBound (bool isLower, OperationState & result, OpAsmParser & p) static
Parse a for operation loop bounds.
Definition at line 1153 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::AffineMapAttr::get(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::OpAsmParser::getNameLoc(), mlir::functional::map(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::parseDimAndSymbolList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
Referenced by parseAffineForOp().
print() [1/4]
static void print (OpAsmPrinter & p, AffineForOp op) static
Definition at line 1334 of file AffineOps.cpp.
References printBound(), and mlir::OpAsmPrinter::printOperand().
Referenced by mlir::Diagnostic::append(), mlir::Type::classof(), mlir::tblgen::DagLeaf::DagLeaf(), mlir::Identifier::dump(), mlir::ModuleOp::dump(), mlir::AffineMap::dump(), mlir::AffineExpr::dump(), mlir::IntegerSet::dump(), mlir::Attribute::dump(), mlir::SDBM::dump(), mlir::Type::dump(), mlir::Value::dump(), mlir::Operation::dump(), mlir::OperationName::dump(), mlir::Block::dump(), mlir::Operation::emitError(), mlir::CallGraph::end(), mlir::tblgen::Operator::getDialect(), mlir::Attribute::getKind(), mlir::Value::getKind(), mlir::AffineApplyOp::getMapOperands(), mlir::DmaWaitOp::getNumElements(), mlir::DmaStartOp::getOperationName(), mlir::AffineDmaStartOp::getOperationName(), mlir::AffineLoadOp::getOperationName(), mlir::AffineStoreOp::getOperationName(), mlir::AffineDmaWaitOp::getTagMapAttrName(), isMemRefDereferencingOp(), mlir::OperationName::OperationName(), mlir::tblgen::DagNode::operator bool(), mlir::AffineExpr::operator!(), mlir::SDBMExpr::operator!(), mlir::AffineMap::operator!=(), mlir::IntegerSet::operator==(), mlir::ModuleOp::print(), mlir::Operation::print(), mlir::Block::print(), printDenseFloatElement(), printTimeEntry(), mlir::FlatAffineConstraints::setIdValues(), mlir::Diagnostic::str(), and mlir::OpState::verify().
print() [2/4]
static void print (OpAsmPrinter & p, AffineIfOp op) static
Definition at line 1672 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::canonicalizeSetAndOperands(), mlir::failure(), mlir::IntegerSetAttr::get(), mlir::AffineApplyNormalizer::getOperands(), mlir::OperationState::location, mlir::printDimAndSymbolList(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), and mlir::success().
print() [3/4]
static void print (OpAsmPrinter & p, AffineMinOp op) static
Definition at line 1963 of file AffineOps.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), and mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front().
print() [4/4]
static void print (OpAsmPrinter & p, AffinePrefetchOp op) static
Definition at line 2062 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printBound()
static void printBound (AffineMapAttr boundMap, Operation::operand_range boundOperands, const char * prefix, OpAsmPrinter & p) static
Definition at line 1293 of file AffineOps.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), mlir::AffineExpr::dyn_cast(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), mlir::AffineMapAttr::getValue(), mlir::functional::map(), mlir::printDimAndSymbolList(), and mlir::OpAsmPrinter::printOperand().
Referenced by print().
promoteComposedSymbolsAsDims()
static AffineMap promoteComposedSymbolsAsDims (AffineMap map, ArrayRef< Value > symbols) static
Definition at line 387 of file AffineOps.cpp.
References mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), indicesFromAffineApplyOp(), mlir::isValidSymbol(), mlir::functional::map(), and mlir::AffineMap::replaceDimsAndSymbols().
Referenced by mlir::AffineApplyNormalizer::AffineApplyNormalizer().
verify() [1/4]
static LogicalResult verify (AffineForOp op) static
Lower bound.
Upper bound.
Definition at line 1123 of file AffineOps.cpp.
References mlir::failed(), mlir::failure(), mlir::AffineMap::getNumInputs(), mlir::success(), and verifyDimAndSymbolIdentifiers().
verify() [2/4]
static LogicalResult verify (AffineIfOp op) static
Definition at line 1593 of file AffineOps.cpp.
References mlir::failed(), mlir::failure(), mlir::IntegerSet::getNumDims(), mlir::IntegerSet::getNumInputs(), mlir::success(), and verifyDimAndSymbolIdentifiers().
verify() [3/4]
static LogicalResult verify (AffineMinOp op) static
Definition at line 1975 of file AffineOps.cpp.
References mlir::failed(), mlir::IntegerAttr::getInt(), mlir::functional::map(), and mlir::success().
verify() [4/4]
static LogicalResult verify (AffinePrefetchOp op) static
Definition at line 2079 of file AffineOps.cpp.
References foldMemRefCast(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::OwningRewritePatternList::insert(), isValidAffineIndexOperand(), and mlir::success().
verifyDimAndSymbolIdentifiers()
template<typename OpTy > static LogicalResult verifyDimAndSymbolIdentifiers (OpTy & op, Operation::operand_range operands, unsigned numDims) static
Utility function to verify that a set of operands are valid dimension and symbol identifiers.
The operands should be laid out such that the dimension operands are before the symbol operands. This function returns failure if there was an invalid operand. An operation is provided to emit any necessary errors.
Definition at line 213 of file AffineOps.cpp.
References mlir::isValidDim(), mlir::isValidSymbol(), and mlir::success().
Referenced by verify().