MLIR: lib/Transforms/AffineLoopInvariantCodeMotion.cpp File Reference
AffineLoopInvariantCodeMotion.cpp File Reference
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "licm"
Functions
static bool checkInvarianceOfNestedIfOps (Operation *op, Value indVar, SmallPtrSetImpl< Operation *> &definedOps, SmallPtrSetImpl< Operation *> &opsToHoist)
static bool isOpLoopInvariant (Operation &op, Value indVar, SmallPtrSetImpl< Operation *> &definedOps, SmallPtrSetImpl< Operation *> &opsToHoist)
static bool areAllOpsInTheBlockListInvariant (Region &blockList, Value indVar, SmallPtrSetImpl< Operation *> &definedOps, SmallPtrSetImpl< Operation *> &opsToHoist)
static bool isMemRefDereferencingOp (Operation &op)
Variables
static PassRegistration< LoopInvariantCodeMotion > pass ("affine-loop-invariant-code-motion", "Hoist loop invariant instructions outside of the loop")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "licm"
Definition at line 34 of file AffineLoopInvariantCodeMotion.cpp.
Function Documentation
areAllOpsInTheBlockListInvariant()
bool areAllOpsInTheBlockListInvariant (Region & blockList, Value indVar, SmallPtrSetImpl< Operation *> & definedOps, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 156 of file AffineLoopInvariantCodeMotion.cpp.
References isOpLoopInvariant().
Referenced by checkInvarianceOfNestedIfOps().
checkInvarianceOfNestedIfOps()
bool checkInvarianceOfNestedIfOps (Operation * op, Value indVar, SmallPtrSetImpl< Operation *> & definedOps, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 172 of file AffineLoopInvariantCodeMotion.cpp.
References areAllOpsInTheBlockListInvariant(), isOpLoopInvariant(), and mlir::Operation::moveBefore().
Referenced by isOpLoopInvariant().
isMemRefDereferencingOp()
static bool isMemRefDereferencingOp (Operation & op) static
Definition at line 64 of file AffineLoopInvariantCodeMotion.cpp.
Referenced by isOpLoopInvariant().
isOpLoopInvariant()
bool isOpLoopInvariant (Operation & op, Value indVar, SmallPtrSetImpl< Operation *> & definedOps, SmallPtrSetImpl< Operation *> & opsToHoist) static
Definition at line 73 of file AffineLoopInvariantCodeMotion.cpp.
References checkInvarianceOfNestedIfOps(), mlir::Value::getDefiningOp(), mlir::getForInductionVarOwner(), mlir::getLoopIVs(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Value::getUsers(), isMemRefDereferencingOp(), and mlir::Value::print().
Referenced by areAllOpsInTheBlockListInvariant(), and checkInvarianceOfNestedIfOps().
Variable Documentation
pass
PassRegistration<LoopInvariantCodeMotion> pass("affine-loop-invariant-code-motion", "Hoist loop invariant instructions outside of the loop") static
Referenced by mlir::createAffineLoopInvariantCodeMotionPass().