MLIR: lib/IR/AffineExpr.cpp File Reference
AffineExpr.cpp File Reference
#include "mlir/IR/AffineExpr.h"
#include "AffineExprDetail.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/ADT/STLExtras.h"
Functions
static AffineExpr getAffineDimOrSymbol (AffineExprKind kind, unsigned position, MLIRContext *context)
static AffineExpr simplifyAdd (AffineExpr lhs, AffineExpr rhs)
Simplify add expression. Return nullptr if it can't be simplified.
static AffineExpr simplifyMul (AffineExpr lhs, AffineExpr rhs)
Simplify a multiply expression. Return nullptr if it can't be simplified.
static AffineExpr simplifyFloorDiv (AffineExpr lhs, AffineExpr rhs)
static AffineExpr simplifyCeilDiv (AffineExpr lhs, AffineExpr rhs)
static AffineExpr simplifyMod (AffineExpr lhs, AffineExpr rhs)
static bool getFlattenedAffineExprs (ArrayRef< AffineExpr > exprs, unsigned numDims, unsigned numSymbols, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs)
Function Documentation
getAffineDimOrSymbol()
static AffineExpr getAffineDimOrSymbol (AffineExprKind kind, unsigned position, MLIRContext * context) static
Definition at line 241 of file AffineExpr.cpp.
References mlir::StorageUniquer::get(), and mlir::MLIRContext::getAffineUniquer().
Referenced by mlir::getAffineDimExpr(), and mlir::getAffineSymbolExpr().
getFlattenedAffineExprs()
static bool getFlattenedAffineExprs (ArrayRef< AffineExpr > exprs, unsigned numDims, unsigned numSymbols, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs) static
Definition at line 861 of file AffineExpr.cpp.
References mlir::AffineExpr::isPureAffine(), mlir::SimpleAffineExprFlattener::operandExprStack, and mlir::AffineExprVisitor< SubClass, RetTy >::walkPostOrder().
Referenced by mlir::getFlattenedAffineExprs().
simplifyAdd()
static AffineExpr simplifyAdd (AffineExpr lhs, AffineExpr rhs) static
Simplify add expression. Return nullptr if it can't be simplified.
Definition at line 288 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::dyn_cast(), mlir::FloorDiv, mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineBinaryOpExpr::getRHS(), mlir::AffineConstantExpr::getValue(), mlir::AffineExpr::isa(), and mlir::AffineExpr::isSymbolicOrConstant().
Referenced by mlir::AffineExpr::operator+().
simplifyCeilDiv()
static AffineExpr simplifyCeilDiv (AffineExpr lhs, AffineExpr rhs) static
Definition at line 490 of file AffineExpr.cpp.
References mlir::AffineExpr::ceilDiv(), mlir::AffineExpr::dyn_cast(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineConstantExpr::getValue(), and mlir::Mul.
Referenced by mlir::AffineExpr::ceilDiv().
simplifyFloorDiv()
static AffineExpr simplifyFloorDiv (AffineExpr lhs, AffineExpr rhs) static
Definition at line 434 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::dyn_cast(), mlir::AffineExpr::floorDiv(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getLargestKnownDivisor(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineConstantExpr::getValue(), and mlir::Mul.
Referenced by mlir::AffineExpr::floorDiv().
simplifyMod()
static AffineExpr simplifyMod (AffineExpr lhs, AffineExpr rhs) static
Definition at line 533 of file AffineExpr.cpp.
References mlir::Add, mlir::AffineExpr::dyn_cast(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getLargestKnownDivisor(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineConstantExpr::getValue(), and mlir::mod().
Referenced by mlir::AffineExpr::operator%().
simplifyMul()
static AffineExpr simplifyMul (AffineExpr lhs, AffineExpr rhs) static
Simplify a multiply expression. Return nullptr if it can't be simplified.
Definition at line 364 of file AffineExpr.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::getAffineConstantExpr(), mlir::AffineExpr::getContext(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineConstantExpr::getValue(), mlir::AffineExpr::isa(), mlir::AffineExpr::isSymbolicOrConstant(), and mlir::Mul.
Referenced by mlir::AffineExpr::operator*().