MLIR: lib/Analysis/AffineAnalysis.cpp File Reference
AffineAnalysis.cpp File Reference
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "affine-analysis"
Functions
static LogicalResult getInstIndexSet (Operation *op, FlatAffineConstraints *indexSet)
static void buildDimAndSymbolPositionMaps (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, ValuePositionMap *valuePosMap, FlatAffineConstraints *dependenceConstraints)
static void initDependenceConstraints (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, const ValuePositionMap &valuePosMap, FlatAffineConstraints *dependenceConstraints)
static void addDomainConstraints (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, const ValuePositionMap &valuePosMap, FlatAffineConstraints *dependenceDomain)
static LogicalResult addMemRefAccessConstraints (const AffineValueMap &srcAccessMap, const AffineValueMap &dstAccessMap, const ValuePositionMap &valuePosMap, FlatAffineConstraints *dependenceDomain)
static unsigned getNumCommonLoops (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, SmallVectorImpl< AffineForOp > *commonLoops=nullptr)
static Block * getCommonBlock (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess, const FlatAffineConstraints &srcDomain, unsigned numCommonLoops)
static bool srcAppearsBeforeDstInAncestralBlock (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess, const FlatAffineConstraints &srcDomain, unsigned numCommonLoops)
static void addOrderingConstraints (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, unsigned loopDepth, FlatAffineConstraints *dependenceDomain)
static void computeDirectionVector (const FlatAffineConstraints &srcDomain, const FlatAffineConstraints &dstDomain, unsigned loopDepth, FlatAffineConstraints *dependenceDomain, SmallVector< DependenceComponent, 2 > *dependenceComponents)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-analysis"
Definition at line 30 of file AffineAnalysis.cpp.
Function Documentation
addDomainConstraints()
static void addDomainConstraints (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, const ValuePositionMap & valuePosMap, FlatAffineConstraints * dependenceDomain) static
Definition at line 306 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::atEq(), mlir::FlatAffineConstraints::atIneq(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), and mlir::functional::map().
Referenced by mlir::checkMemrefAccessDependence().
addMemRefAccessConstraints()
static LogicalResult addMemRefAccessConstraints (const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, const ValuePositionMap & valuePosMap, FlatAffineConstraints * dependenceDomain) static
Definition at line 383 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::addLocalId(), mlir::FlatAffineConstraints::atIneq(), mlir::failed(), mlir::failure(), mlir::AffineValueMap::getAffineMap(), mlir::getFlattenedAffineExprs(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::AffineMap::getNumDims(), mlir::FlatAffineConstraints::getNumEqualities(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::AffineMap::getNumResults(), mlir::FlatAffineConstraints::getNumSymbolIds(), mlir::AffineMap::getNumSymbols(), mlir::AffineValueMap::getOperands(), mlir::isForInductionVar(), mlir::isValidSymbol(), mlir::FlatAffineConstraints::setIdToConstant(), and mlir::success().
Referenced by mlir::checkMemrefAccessDependence().
addOrderingConstraints()
static void addOrderingConstraints (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, unsigned loopDepth, FlatAffineConstraints * dependenceDomain) static
Definition at line 584 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::getNumCols(), getNumCommonLoops(), and mlir::FlatAffineConstraints::getNumDimIds().
Referenced by mlir::checkMemrefAccessDependence().
buildDimAndSymbolPositionMaps()
static void buildDimAndSymbolPositionMaps (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, ValuePositionMap * valuePosMap, FlatAffineConstraints * dependenceConstraints) static
Definition at line 210 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::getIdValues(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::AffineValueMap::getOperands(), mlir::isForInductionVar(), and mlir::isValidSymbol().
Referenced by mlir::checkMemrefAccessDependence().
computeDirectionVector()
static void computeDirectionVector (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, unsigned loopDepth, FlatAffineConstraints * dependenceDomain, SmallVector< DependenceComponent, 2 > * dependenceComponents) static
Definition at line 610 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addDimId(), mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::getConstantLowerBound(), mlir::FlatAffineConstraints::getConstantUpperBound(), mlir::FlatAffineConstraints::getNumCols(), getNumCommonLoops(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumIds(), and mlir::FlatAffineConstraints::projectOut().
Referenced by mlir::checkMemrefAccessDependence().
getCommonBlock()
static Block* getCommonBlock (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess, const FlatAffineConstraints & srcDomain, unsigned numCommonLoops) static
Definition at line 537 of file AffineAnalysis.cpp.
References mlir::Operation::getBlock(), mlir::getForInductionVarOwner(), mlir::FlatAffineConstraints::getIdValue(), mlir::Block::getParentOp(), and mlir::MemRefAccess::opInst.
Referenced by srcAppearsBeforeDstInAncestralBlock().
getInstIndexSet()
static LogicalResult getInstIndexSet (Operation * op, FlatAffineConstraints * indexSet) static
Definition at line 111 of file AffineAnalysis.cpp.
References mlir::getIndexSet(), and mlir::getLoopIVs().
Referenced by mlir::checkMemrefAccessDependence().
getNumCommonLoops()
static unsigned getNumCommonLoops (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, SmallVectorImpl< AffineForOp > * commonLoops = nullptr) static
Definition at line 515 of file AffineAnalysis.cpp.
References mlir::getForInductionVarOwner(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getNumDimIds(), and mlir::isForInductionVar().
Referenced by addOrderingConstraints(), mlir::checkMemrefAccessDependence(), and computeDirectionVector().
initDependenceConstraints()
static void initDependenceConstraints (const FlatAffineConstraints & srcDomain, const FlatAffineConstraints & dstDomain, const AffineValueMap & srcAccessMap, const AffineValueMap & dstAccessMap, const ValuePositionMap & valuePosMap, FlatAffineConstraints * dependenceConstraints) static
Definition at line 245 of file AffineAnalysis.cpp.
References mlir::AffineValueMap::getAffineMap(), mlir::FlatAffineConstraints::getIds(), mlir::FlatAffineConstraints::getIdValues(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumInequalities(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::AffineMap::getNumResults(), mlir::AffineValueMap::getOperands(), mlir::isForInductionVar(), mlir::isValidSymbol(), mlir::FlatAffineConstraints::reset(), mlir::FlatAffineConstraints::setIdValue(), and mlir::FlatAffineConstraints::setIdValues().
Referenced by mlir::checkMemrefAccessDependence().
srcAppearsBeforeDstInAncestralBlock()
static bool srcAppearsBeforeDstInAncestralBlock (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess, const FlatAffineConstraints & srcDomain, unsigned numCommonLoops) static
Definition at line 560 of file AffineAnalysis.cpp.
References getCommonBlock(), and mlir::MemRefAccess::opInst.
Referenced by mlir::checkMemrefAccessDependence().