MLIR: lib/Conversion/AffineToStandard/AffineToStandard.cpp File Reference
AffineToStandard.cpp File Reference
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/Functional.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
Functions
static Optional< SmallVector< Value, 8 > > expandAffineMap (OpBuilder &builder, Location loc, AffineMap affineMap, ValueRange operands)
Create a sequence of operations that implement the affineMap applied to the given operands (as it it were an AffineApplyOp).
static Value buildMinMaxReductionSeq (Location loc, CmpIPredicate predicate, ValueRange values, OpBuilder &builder)
Given a range of values, emit the code that reduces them with "min" or "max" depending on the provided comparison predicate.
static Value lowerAffineMapMin (OpBuilder &builder, Location loc, AffineMap map, ValueRange operands)
Emit instructions that correspond to computing the minimum value amoung the values of a (potentially) multi-output affine map applied to operands.
Variables
static PassRegistration< LowerAffinePass > pass ("lower-affine", "Lower If, For, AffineApply operations to primitive equivalents")
Function Documentation
buildMinMaxReductionSeq()
static Value buildMinMaxReductionSeq (Location loc, CmpIPredicate predicate, ValueRange values, OpBuilder & builder) static
Given a range of values, emit the code that reduces them with "min" or "max" depending on the provided comparison predicate.
The predicate defines which comparison to perform, "lt" for "min", "gt" for "max" and is used for the cmpi operation followed by the select operation:
cond = cmpi "predicate" v0, v1 result = select cond, v0, v1
Multiple values are scanned in a linear sequence. This creates a data dependences that wouldn't exist in a tree reduction, but is easier to recognize as a reduction by the subsequent passes.
Definition at line 247 of file AffineToStandard.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), mlir::OpBuilder::create(), and mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end().
Referenced by mlir::lowerAffineLowerBound(), and lowerAffineMapMin().
expandAffineMap()
static Optional<SmallVector<Value, 8> > expandAffineMap (OpBuilder & builder, Location loc, AffineMap affineMap, ValueRange operands) static
Create a sequence of operations that implement the affineMap applied to the given operands (as it it were an AffineApplyOp).
Definition at line 219 of file AffineToStandard.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front(), mlir::expandAffineExpr(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getResults(), mlir::functional::map(), mlir::StandardTypes::None, and mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front().
Referenced by mlir::lowerAffineLowerBound(), lowerAffineMapMin(), and mlir::lowerAffineUpperBound().
lowerAffineMapMin()
static Value lowerAffineMapMin (OpBuilder & builder, Location loc, AffineMap map, ValueRange operands) static
Emit instructions that correspond to computing the minimum value amoung the values of a (potentially) multi-output affine map applied to operands.
Definition at line 275 of file AffineToStandard.cpp.
References buildMinMaxReductionSeq(), and expandAffineMap().
Referenced by mlir::lowerAffineUpperBound().
Variable Documentation
pass
PassRegistration<LowerAffinePass> pass("lower-affine", "Lower If, For, AffineApply operations to primitive equivalents") static
Referenced by mlir::createLowerAffinePass().