MLIR: lib/Analysis/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Analysis/Utils.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "analysis-utils"
Functions
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType)
static void findInstPosition (Operation *op, Block *limitBlock, SmallVectorImpl< unsigned > *positions)
static Operation * getInstAtPosition (ArrayRef< unsigned > positions, unsigned level, Block *block)
static LogicalResult addMissingLoopIVBounds (SmallPtrSet< Value, 8 > &ivs, FlatAffineConstraints *cst)
static unsigned getInnermostCommonLoopDepth (ArrayRef< Operation *> ops, SmallVectorImpl< AffineForOp > &surroundingLoops)
static Optional< int64_t > getMemoryFootprintBytes (Block &block, Block::iterator start, Block::iterator end, int memorySpace)
Variables
const char *const kSliceFusionBarrierAttrName = "slice_fusion_barrier"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "analysis-utils"
Definition at line 23 of file Utils.cpp.
Function Documentation
addMissingLoopIVBounds()
static LogicalResult addMissingLoopIVBounds (SmallPtrSet< Value, 8 > & ivs, FlatAffineConstraints * cst) static
Definition at line 474 of file Utils.cpp.
References mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::failed(), mlir::failure(), mlir::getForInductionVarOwner(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::isForInductionVar(), and mlir::success().
Referenced by mlir::computeSliceUnion().
findInstPosition()
static void findInstPosition (Operation * op, Block * limitBlock, SmallVectorImpl< unsigned > * positions) static
Definition at line 432 of file Utils.cpp.
References mlir::Block::begin(), mlir::Operation::getBlock(), and mlir::Block::getParentOp().
Referenced by mlir::insertBackwardComputationSlice().
getInnermostCommonLoopDepth()
static unsigned getInnermostCommonLoopDepth (ArrayRef< Operation *> ops, SmallVectorImpl< AffineForOp > & surroundingLoops) static
Definition at line 491 of file Utils.cpp.
References mlir::getLoopIVs().
Referenced by mlir::computeSliceUnion().
getInstAtPosition()
static Operation* getInstAtPosition (ArrayRef< unsigned > positions, unsigned level, Block * block) static
Definition at line 449 of file Utils.cpp.
Referenced by mlir::insertBackwardComputationSlice().
getMemoryFootprintBytes()
static Optional<int64_t> getMemoryFootprintBytes (Block & block, Block::iterator start, Block::iterator end, int memorySpace) static
Definition at line 909 of file Utils.cpp.
References mlir::WalkResult::advance(), mlir::Block::begin(), mlir::Operation::emitError(), mlir::Operation::emitWarning(), mlir::failed(), mlir::Operation::getLoc(), mlir::getNestingDepth(), mlir::StandardTypes::None, and mlir::Block::walk().
Referenced by mlir::getMemoryFootprintBytes().
getMemRefEltSizeInBytes()
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType) static
Definition at line 312 of file Utils.cpp.
Referenced by mlir::getMemRefSizeInBytes(), and mlir::MemRefRegion::getRegionSize().
Variable Documentation
kSliceFusionBarrierAttrName
const char* const kSliceFusionBarrierAttrName = "slice_fusion_barrier"
Definition at line 675 of file Utils.cpp.
Referenced by mlir::getComputationSliceState().