MLIR: lib/IR/AsmPrinter.cpp File Reference
AsmPrinter.cpp File Reference
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/AsmState.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/SaveAndRestore.h"
#include "mlir/IR/OpAsmInterface.cpp.inc"
Classes
class mlir::detail::AsmStateImpl
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::detail
Utilities for detecting if a given trait holds for some set of arguments 'Args'.
Functions
static llvm::cl::opt< unsigned > elideElementsAttrIfLarger ("mlir-elide-elementsattrs-if-larger", llvm::cl::desc("Elide ElementsAttrs with \..\that have " "more elements than the given upper limit"))
The OpAsmOpInterface, see OpAsmInterface.td for more details.
static llvm::cl::opt< bool > printDebugInfoOpt ("mlir-print-debuginfo", llvm::cl::desc("Print debug info in MLIR output"), llvm::cl::init(false))
static llvm::cl::opt< bool > printPrettyDebugInfoOpt ("mlir-pretty-debuginfo", llvm::cl::desc("Print pretty debug info in MLIR output"), llvm::cl::init(false))
static llvm::cl::opt< bool > printGenericOpFormOpt ("mlir-print-op-generic", llvm::cl::desc("Print the generic op form"), llvm::cl::init(false), llvm::cl::Hidden)
static llvm::cl::opt< bool > printLocalScopeOpt ("mlir-print-local-scope", llvm::cl::desc("Print assuming in local scope by default"), llvm::cl::init(false), llvm::cl::Hidden)
static bool canRegisterAlias (StringRef name, llvm::StringSet<> &usedAliases)
static void printFloatValue (const APFloat &apValue, raw_ostream &os)
Print a floating point value in a way that the parser will be able to round-trip losslessly.
static bool isDialectSymbolSimpleEnoughForPrettyForm (StringRef symName)
Returns if the given dialect symbol data is simple enough to print in the pretty form, i.e.
static void printDialectSymbol (raw_ostream &os, StringRef symPrefix, StringRef dialectName, StringRef symString)
Print the given dialect symbol to the stream.
static bool isBareIdentifier (StringRef name)
Returns if the given string can be represented as a bare identifier.
static void printSymbolReference (StringRef symbolRef, raw_ostream &os)
Print the given string as a symbol reference.
static void printElidedElementsAttr (raw_ostream &os)
static void printDenseIntElement (DenseElementsAttr attr, raw_ostream &os, unsigned index)
Print the integer element of the given DenseElementsAttr at 'index'.
static void printDenseFloatElement (DenseElementsAttr attr, raw_ostream &os, unsigned index)
Print the float element of the given DenseElementsAttr at 'index'.
Function Documentation
canRegisterAlias()
static bool canRegisterAlias (StringRef name, llvm::StringSet<> & usedAliases) static
Definition at line 223 of file AsmPrinter.cpp.
References mlir::StandardAttributes::AffineMap, mlir::Value::cast(), mlir::Value::dyn_cast(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::Region::empty(), mlir::Region::front(), mlir::AffineMapAttr::get(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Value::getDefiningOp(), mlir::Operation::getDialect(), mlir::DialectInterfaceCollection< InterfaceType >::getInterfaceFor(), mlir::Attribute::getKind(), mlir::Block::getNumArguments(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::BlockArgument::getOwner(), mlir::OpResult::getOwner(), mlir::Block::getParentOp(), mlir::Region::getParentOp(), mlir::Operation::getRegions(), mlir::Operation::getResult(), mlir::OpResult::getResultNumber(), mlir::Operation::getResultTypes(), mlir::StandardAttributes::IntegerSet, mlir::Block::isEntryBlock(), mlir::Operation::isKnownIsolatedFromAbove(), mlir::functional::map(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), and mlir::Operation::walk().
elideElementsAttrIfLarger()
static llvm::cl::opt<unsigned> elideElementsAttrIfLarger ("mlir-elide-elementsattrs-if-larger" , llvm::cl::desc("Elide ElementsAttrs with \.\hat have " "more elements than the given upper limit")) static
The OpAsmOpInterface, see OpAsmInterface.td for more details.
Referenced by mlir::OpAsmPrinter::~OpAsmPrinter().
isBareIdentifier()
static bool isBareIdentifier (StringRef name) static
Returns if the given string can be represented as a bare identifier.
Definition at line 1098 of file AsmPrinter.cpp.
Referenced by printSymbolReference().
isDialectSymbolSimpleEnoughForPrettyForm()
static bool isDialectSymbolSimpleEnoughForPrettyForm (StringRef symName) static
Returns if the given dialect symbol data is simple enough to print in the pretty form, i.e.
without the enclosing "".
Definition at line 1009 of file AsmPrinter.cpp.
Referenced by printDialectSymbol().
printDebugInfoOpt()
static llvm::cl::opt<bool> printDebugInfoOpt ("mlir-print-debuginfo" , llvm::cl::desc("Print debug info in MLIR output") , llvm::cl::init(false)) static
Referenced by mlir::OpAsmPrinter::~OpAsmPrinter().
printDenseFloatElement()
static void printDenseFloatElement (DenseElementsAttr attr, raw_ostream & os, unsigned index) static
Print the float element of the given DenseElementsAttr at 'index'.
Definition at line 1317 of file AsmPrinter.cpp.
References mlir::Add, mlir::Block::args_empty(), mlir::StandardTypes::BF16, mlir::AffineExpr::cast(), mlir::Type::cast(), mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::AffineExpr::dyn_cast(), mlir::Region::empty(), mlir::StandardTypes::F16, mlir::StandardTypes::F32, mlir::StandardTypes::F64, mlir::DenseElementsAttr::float_value_begin(), mlir::FloorDiv, mlir::Region::front(), mlir::Operation::getAbstractOperation(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::Region::getBlocks(), mlir::Attribute::getDialect(), mlir::Type::getDialect(), mlir::AffineExpr::getKind(), mlir::Type::getKind(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::AffineMap::getNumDims(), mlir::Operation::getNumOperands(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Operation::getNumSuccessorOperands(), mlir::Operation::getNumSuccessors(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getOperands(), mlir::Op< ConcreteType, Traits >::getOperation(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::Block::getPredecessors(), mlir::Operation::getRegions(), mlir::Operation::getResult(), mlir::AffineMap::getResults(), mlir::FunctionType::getResults(), mlir::Block::getSinglePredecessor(), mlir::detail::AsmStateImpl::getSSANameState(), mlir::OperationName::getStringRef(), mlir::Operation::getSuccessor(), mlir::Operation::getSuccessorOperands(), mlir::Value::getType(), mlir::AffineMapAttr::getValue(), mlir::IntegerType::getWidth(), mlir::Block::hasNoPredecessors(), mlir::StandardTypes::Index, mlir::StandardTypes::Integer, mlir::interleaveComma(), mlir::Type::isa(), mlir::DenseElementsAttr::isSplat(), mlir::functional::map(), mlir::Mod, mlir::Mul, mlir::StandardAttributes::Opaque, print(), printDenseIntElement(), printDialectSymbol(), printFloatValue(), printGenericOp(), printSymbolReference(), mlir::StandardTypes::RankedTensor, mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), mlir::SymbolId, mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front(), mlir::StandardTypes::UnrankedTensor, and mlir::StandardTypes::Vector.
printDenseIntElement()
static void printDenseIntElement (DenseElementsAttr attr, raw_ostream & os, unsigned index) static
Print the integer element of the given DenseElementsAttr at 'index'.
Definition at line 1307 of file AsmPrinter.cpp.
References mlir::DenseElementsAttr::int_value_begin(), and mlir::Value::print().
Referenced by printDenseFloatElement().
printDialectSymbol()
static void printDialectSymbol (raw_ostream & os, StringRef symPrefix, StringRef dialectName, StringRef symString) static
Print the given dialect symbol to the stream.
Definition at line 1082 of file AsmPrinter.cpp.
References isDialectSymbolSimpleEnoughForPrettyForm().
Referenced by printDenseFloatElement(), and printElidedElementsAttr().
printElidedElementsAttr()
static void printElidedElementsAttr (raw_ostream & os) static
Definition at line 1140 of file AsmPrinter.cpp.
References mlir::StandardAttributes::AffineMap, mlir::StandardAttributes::Array, mlir::StandardAttributes::Bool, mlir::Attribute::cast(), mlir::StandardAttributes::DenseElements, mlir::StandardAttributes::Dictionary, mlir::StandardAttributes::Float, mlir::Attribute::getKind(), mlir::Attribute::getType(), mlir::ArrayAttr::getValue(), mlir::DictionaryAttr::getValue(), mlir::IntegerAttr::getValue(), mlir::StringAttr::getValue(), mlir::StandardAttributes::Integer, mlir::interleaveComma(), mlir::Attribute::isa(), mlir::StandardAttributes::Opaque, printDialectSymbol(), printFloatValue(), mlir::StandardAttributes::String, and mlir::StandardAttributes::Unit.
printFloatValue()
static void printFloatValue (const APFloat & apValue, raw_ostream & os) static
Print a floating point value in a way that the parser will be able to round-trip losslessly.
Definition at line 958 of file AsmPrinter.cpp.
Referenced by printDenseFloatElement(), and printElidedElementsAttr().
printGenericOpFormOpt()
static llvm::cl::opt<bool> printGenericOpFormOpt ("mlir-print-op-generic" , llvm::cl::desc("Print the generic op form") , llvm::cl::init(false) , llvm::cl::Hidden) static
Referenced by mlir::OpAsmPrinter::~OpAsmPrinter().
printLocalScopeOpt()
static llvm::cl::opt<bool> printLocalScopeOpt ("mlir-print-local-scope" , llvm::cl::desc("Print assuming in local scope by default") , llvm::cl::init(false) , llvm::cl::Hidden) static
Referenced by mlir::OpAsmPrinter::~OpAsmPrinter().
printPrettyDebugInfoOpt()
static llvm::cl::opt<bool> printPrettyDebugInfoOpt ("mlir-pretty-debuginfo" , llvm::cl::desc("Print pretty debug info in MLIR output") , llvm::cl::init(false)) static
Referenced by mlir::OpAsmPrinter::~OpAsmPrinter().
printSymbolReference()
static void printSymbolReference (StringRef symbolRef, raw_ostream & os) static
Print the given string as a symbol reference.
A symbol reference is represented as a string prefixed with '@'. The reference is surrounded with ""'s and escaped if it has any special or non-printable characters in it.
Definition at line 1116 of file AsmPrinter.cpp.
References isBareIdentifier().
Referenced by printDenseFloatElement().