MLIR: lib/IR/Attributes.cpp File Reference
Attributes.cpp File Reference
#include "mlir/IR/Attributes.h"
#include "AttributeDetail.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Types.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/Twine.h"
Functions
static int compareNamedAttributes (const NamedAttribute *lhs, const NamedAttribute *rhs)
Perform a three-way comparison between the names of the specified NamedAttributes.
static LogicalResult verifyFloatTypeInvariants (Optional< Location > loc, Type type)
Verify construction invariants.
static LogicalResult verifyIntegerTypeInvariants (Optional< Location > loc, Type type)
LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *ctx, Type type, int64_t value)
static size_t getDenseElementBitwidth (Type eltType)
static size_t getDenseElementStorageWidth (size_t origWidth)
Get the bitwidth of a dense element type within the buffer.
static void setBit (char *rawData, size_t bitPos, bool value)
Set a bit to a specific value.
static bool getBit (const char *rawData, size_t bitPos)
Return the value of the specified bit.
static void writeBits (char *rawData, size_t bitPos, APInt value)
Writes value to the bit position bitPos in array rawData.
static APInt readBits (const char *rawData, size_t bitPos, size_t bitWidth)
Reads the next bitWidth bits from the bit position bitPos in array rawData.
template<typename Values >
static bool hasSameElementsOrSplat (ShapedType type, const Values &values)
Returns if 'values' corresponds to a splat, i.e.
static bool isValidIntOrFloat (ShapedType type, int64_t dataEltSize, bool isInt)
Check the information for a c++ data type, check if this type is valid for the current attribute.
template<typename Fn , typename Attr >
static ShapedType mappingHelper (Fn mapping, Attr &attr, ShapedType inType, Type newElementType, llvm::SmallVectorImpl< char > &data)
Function Documentation
compareNamedAttributes()
static int compareNamedAttributes (const NamedAttribute * lhs, const NamedAttribute * rhs) static
Perform a three-way comparison between the names of the specified NamedAttributes.
Definition at line 83 of file Attributes.cpp.
Referenced by mlir::DictionaryAttr::get().
getBit()
static bool getBit (const char * rawData, size_t bitPos) static
Return the value of the specified bit.
Definition at line 492 of file Attributes.cpp.
Referenced by mlir::DenseElementsAttr::BoolElementIterator::operator*(), and readBits().
getDenseElementBitwidth()
static size_t getDenseElementBitwidth (Type eltType) static
Definition at line 471 of file Attributes.cpp.
References mlir::Type::getIntOrFloatBitWidth(), and mlir::Type::isBF16().
Referenced by mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getRaw(), isValidIntOrFloat(), mappingHelper(), and mlir::DenseElementsAttr::BoolElementIterator::operator*().
getDenseElementStorageWidth()
static size_t getDenseElementStorageWidth (size_t origWidth) static
Get the bitwidth of a dense element type within the buffer.
DenseElementsAttr requires bitwidths greater than 1 to be aligned by 8.
Definition at line 479 of file Attributes.cpp.
Referenced by mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getRaw(), mappingHelper(), and mlir::DenseElementsAttr::IntElementIterator::operator*().
hasSameElementsOrSplat()
template<typename Values > static bool hasSameElementsOrSplat (ShapedType type, const Values & values) static
Returns if 'values' corresponds to a splat, i.e.
one element, or has the same element count as 'type'.
Definition at line 530 of file Attributes.cpp.
References mlir::ShapedType::getNumElements().
Referenced by mlir::DenseElementsAttr::get(), and mlir::DenseElementsAttr::getRaw().
isValidIntOrFloat()
static bool isValidIntOrFloat (ShapedType type, int64_t dataEltSize, bool isInt) static
Check the information for a c++ data type, check if this type is valid for the current attribute.
This method is used to verify specific type invariants that the templatized 'getValues' method cannot.
Definition at line 703 of file Attributes.cpp.
References getDenseElementBitwidth(), mlir::ShapedType::getElementType(), and mlir::Type::isa().
Referenced by mlir::DenseElementsAttr::getRawIntOrFloat(), mlir::DenseElementsAttr::getValues(), mlir::DenseElementsAttr::isValidIntOrFloat(), and mlir::DenseElementsAttr::raw_int_end().
mappingHelper()
template<typename Fn , typename Attr > static ShapedType mappingHelper (Fn mapping, Attr & attr, ShapedType inType, Type newElementType, llvm::SmallVectorImpl< char > & data) static
Definition at line 836 of file Attributes.cpp.
References mlir::VectorType::get(), mlir::RankedTensorType::get(), getDenseElementBitwidth(), getDenseElementStorageWidth(), mlir::ShapedType::getNumElements(), mlir::ShapedType::getShape(), mlir::Type::isa(), and writeBits().
Referenced by mlir::DenseFPElementsAttr::mapValues(), and mlir::DenseIntElementsAttr::mapValues().
readBits()
static APInt readBits (const char * rawData, size_t bitPos, size_t bitWidth) static
Reads the next bitWidth bits from the bit position bitPos in array rawData.
Definition at line 513 of file Attributes.cpp.
References getBit().
Referenced by mlir::DenseElementsAttr::IntElementIterator::operator*().
setBit()
static void setBit (char * rawData, size_t bitPos, bool value) static
Set a bit to a specific value.
Definition at line 484 of file Attributes.cpp.
Referenced by mlir::DenseElementsAttr::get(), and writeBits().
verifyConstructionInvariants()
LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext * ctx, Type type, int64_t value)
Definition at line 291 of file Attributes.cpp.
References verifyIntegerTypeInvariants().
Referenced by mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::get(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::getChecked(), mlir::quant::AnyQuantizedType::kindof(), mlir::FloatAttr::kindof(), and mlir::IntegerAttr::kindof().
verifyFloatTypeInvariants()
static LogicalResult verifyFloatTypeInvariants (Optional< Location > loc, Type type) static
Verify construction invariants.
Definition at line 208 of file Attributes.cpp.
References mlir::emitOptionalError(), mlir::Type::isa(), and mlir::success().
Referenced by mlir::FloatAttr::verifyConstructionInvariants().
verifyIntegerTypeInvariants()
static LogicalResult verifyIntegerTypeInvariants (Optional< Location > loc, Type type) static
Definition at line 284 of file Attributes.cpp.
References mlir::emitOptionalError(), mlir::Type::isa(), and mlir::success().
Referenced by verifyConstructionInvariants(), and mlir::IntegerAttr::verifyConstructionInvariants().
writeBits()
static void writeBits (char * rawData, size_t bitPos, APInt value) static
Writes value to the bit position bitPos in array rawData.
Definition at line 497 of file Attributes.cpp.
References setBit().
Referenced by mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getRaw(), and mappingHelper().