MLIR: mlir::edsc::BlockHandle Class Reference
mlir::edsc::BlockHandle Class Reference
A BlockHandle represents a (potentially "delayed") Block abstraction.
#include "mlir/EDSC/Builders.h"
Public Member Functions
BlockHandle ()
A BlockHandle constructed without an mlir::Block* represents a "delayed" Block.
BlockHandle (mlir::Block *block)
A BlockHandle constructed with an mlir::Block* represents an "eager" Block.
BlockHandle (const BlockHandle &)=default
BlockHandle is a value type, use the default copy constructor and assignment operator.
BlockHandle & operator= (const BlockHandle &)=default
operator bool ()
operator mlir::Block * ()
mlir::Block * getBlock ()
Static Public Member Functions
static BlockHandle create (ArrayRef< Type > argTypes)
Delegates block creation to MLIR and wrap the resulting mlir::Block.
static BlockHandle createInRegion (Region &region, ArrayRef< Type > argTypes)
Delegates block creation to MLIR and wrap the resulting mlir::Block.
Additional Inherited Members
Protected Member Functions inherited from mlir::edsc::CapturableHandle
CapturableHandle ()=default
Detailed Description
A BlockHandle represents a (potentially "delayed") Block abstraction.
This extra abstraction is necessary because an mlir::Block is not an mlir::Value. A BlockHandle should be captured by pointer but otherwise passed by Value everywhere.
Definition at line 442 of file Builders.h.
Constructor & Destructor Documentation
BlockHandle() [1/3]
mlir::edsc::BlockHandle::BlockHandle () inline
A BlockHandle constructed without an mlir::Block* represents a "delayed" Block.
A delayed Block represents the declaration (in the PL sense) of a placeholder for an mlir::Block* that will be constructed and captured at some later point in the program.
Definition at line 448 of file Builders.h.
BlockHandle() [2/3]
mlir::edsc::BlockHandle::BlockHandle (mlir::Block * block) inline
A BlockHandle constructed with an mlir::Block* represents an "eager" Block.
An eager Block represents both the declaration and the definition (in the PL sense) of a placeholder for an mlir::Block* that has already been constructed in the past and that is captured "now" in the program.
Definition at line 454 of file Builders.h.
BlockHandle() [3/3]
mlir::edsc::BlockHandle::BlockHandle (const BlockHandle &) default
BlockHandle is a value type, use the default copy constructor and assignment operator.
Member Function Documentation
create()
BlockHandle mlir::edsc::BlockHandle::create (ArrayRef< Type > argTypes) static
Delegates block creation to MLIR and wrap the resulting mlir::Block.
Definition at line 121 of file Builders.cpp.
References mlir::Block::addArgument(), mlir::OpBuilder::createBlock(), and mlir::edsc::ScopedContext::getBuilder().
Referenced by mlir::edsc::BlockBuilder::BlockBuilder().
createInRegion()
BlockHandle mlir::edsc::BlockHandle::createInRegion (Region & region, ArrayRef< Type > argTypes) static
Delegates block creation to MLIR and wrap the resulting mlir::Block.
Definition at line 136 of file Builders.cpp.
References mlir::Block::addArgument(), mlir::Region::back(), mlir::Block::begin(), mlir::edsc::ScopedContext::getBuilder(), and mlir::Region::push_back().
Referenced by mlir::edsc::BlockBuilder::BlockBuilder().
getBlock()
mlir::Block* mlir::edsc::BlockHandle::getBlock () inline
Definition at line 469 of file Builders.h.
References mlir::matcher::Op().
Referenced by mlir::edsc::BlockBuilder::BlockBuilder(), mlir::edsc::intrinsics::br(), and mlir::edsc::intrinsics::cond_br().
operator bool()
mlir::edsc::BlockHandle::operator bool () inline
Definition at line 467 of file Builders.h.
operator mlir::Block *()
mlir::edsc::BlockHandle::operator mlir::Block * () inline
Definition at line 468 of file Builders.h.
operator=()
BlockHandle& mlir::edsc::BlockHandle::operator= (const BlockHandle &) default
The documentation for this class was generated from the following files:
include/mlir/EDSC/Builders.h
lib/EDSC/Builders.cpp