MLIR: mlir::DmaStartOp Class Reference
mlir::DmaStartOp Class Reference
#include "mlir/Dialect/StandardOps/Ops.h"
Public Member Functions
Value getSrcMemRef ()
unsigned getSrcMemRefRank ()
operand_range getSrcIndices ()
Value getDstMemRef ()
unsigned getDstMemRefRank ()
unsigned getSrcMemorySpace ()
unsigned getDstMemorySpace ()
operand_range getDstIndices ()
Value getNumElements ()
Value getTagMemRef ()
unsigned getTagMemRefRank ()
operand_range getTagIndices ()
bool isDestMemorySpaceFaster ()
Returns true if this is a DMA from a faster memory space to a slower one.
bool isSrcMemorySpaceFaster ()
Returns true if this is a DMA from a slower memory space to a faster one.
unsigned getFasterMemPos ()
Given a DMA start operation, returns the operand position of either the source or destination memref depending on the one that is at the higher level of the memory hierarchy.
void print (OpAsmPrinter &p)
LogicalResult verify ()
LogicalResult fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > &results)
bool isStrided ()
Value getStride ()
Value getNumElementsPerStride ()
Public Member Functions inherited from mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
Operation * getOperation ()
Return the operation that this refers to.
DmaStartOp clone ()
Create a deep copy of this operation.
DmaStartOp cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Dialect * getDialect ()
Return the dialect that this refers to.
Region * getParentRegion ()
Return the parent Region of this operation.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow implicit conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * getOperation ()
Return the operation that this refers to.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
template<typename OpTy >
OpTy getParentOfType ()
Return the closest surrounding parent operation that is of type 'OpTy'.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState, OpPrintingFlags flags=llvm::None)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
void setLoc (Location loc)
ArrayRef< NamedAttribute > getAttrs ()
Return all of the attributes on this operation.
dialect_attr_range getDialectAttrs ()
Return a range corresponding to the dialect attributes for this operation.
dialect_attr_iterator dialect_attr_begin ()
dialect_attr_iterator dialect_attr_end ()
Attribute getAttr (StringRef name)
Return an attribute with the specified name.
template<typename AttrClass >
AttrClass getAttrOfType (StringRef name)
If the operation has an attribute of the specified type, return it.
void setAttr (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setAttr (StringRef name, Attribute value)
void setAttrs (ArrayRef< NamedAttribute > attributes)
Set the attributes held by this operation.
void setAttrs (NamedAttributeList newAttrs)
template<typename DialectAttrs >
void setDialectAttrs (DialectAttrs &&attrs)
Set the dialect attributes for this operation, and preserve all dependent.
NamedAttributeList::RemoveResult removeAttr (Identifier name)
Remove the attribute with the specified name if it exists.
NamedAttributeList::RemoveResult removeAttr (StringRef name)
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk the operation in postorder, calling the callback for each nested operation(including this one).
Public Member Functions inherited from mlir::OpTrait::detail::MultiOperandTraitBase< DmaStartOp, VariadicOperands >
unsigned getNumOperands ()
Return the number of operands.
Value getOperand (unsigned i)
Return the operand at index 'i'.
void setOperand (unsigned i, Value value)
Set the operand at index 'i' to 'value'.
operand_iterator operand_begin ()
Operand iterator access.
operand_iterator operand_end ()
operand_range getOperands ()
operand_type_iterator operand_type_begin ()
Operand type access.
operand_type_iterator operand_type_end ()
operand_type_range getOperandTypes ()
Public Member Functions inherited from mlir::FoldingHook< DmaStartOp, llvm::is_one_of< OpTrait::OneResult< DmaStartOp >, OpTrait::VariadicOperands< DmaStartOp >... >::value >
LogicalResult fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This hook implements a generalized folder for this operation.
Static Public Member Functions
static void build (Builder *builder, OperationState &result, Value srcMemRef, ValueRange srcIndices, Value destMemRef, ValueRange destIndices, Value numElements, Value tagMemRef, ValueRange tagIndices, Value stride=nullptr, Value elementsPerStride=nullptr)
static StringRef getOperationName ()
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Static Public Member Functions inherited from mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
static ParseResult parseAssembly (OpAsmParser &parser, OperationState &result)
This is the hook used by the AsmParser to parse the custom form of this op from an .mlir file.
static void printAssembly (Operation *op, OpAsmPrinter &p)
This is the hook used by the AsmPrinter to emit this to the .mlir file.
static LogicalResult verifyInvariants (Operation *op)
This is the hook that checks whether or not this operation is well formed according to the invariants of its opcode.
static AbstractOperation::OperationProperties getOperationProperties ()
static ConcreteOpType getFromOpaquePointer (const void *pointer)
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (OwningRewritePatternList &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Static Public Member Functions inherited from mlir::FoldingHook< DmaStartOp, llvm::is_one_of< OpTrait::OneResult< DmaStartOp >, OpTrait::VariadicOperands< DmaStartOp >... >::value >
static LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This is an implementation detail of the constant folder hook for AbstractOperation.
Additional Inherited Members
Public Types inherited from mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
using ConcreteOpType = DmaStartOp
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
Public Types inherited from mlir::OpState
using dialect_attr_iterator = Operation::dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
using dialect_attr_range = Operation::dialect_attr_range
Public Types inherited from mlir::OpTrait::detail::MultiOperandTraitBase< DmaStartOp, VariadicOperands >
using operand_iterator = Operation::operand_iterator
using operand_range = Operation::operand_range
using operand_type_iterator = Operation::operand_type_iterator
using operand_type_range = Operation::operand_type_range
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
void print (OpAsmPrinter &p)
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< DmaStartOp, VariadicOperands >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Unless overridden, the custom assembly form of an op is always rejected.
Static Protected Member Functions inherited from mlir::OpTrait::TraitBase< DmaStartOp, VariadicOperands >
static LogicalResult verifyTrait (Operation *op)
Provide default implementations of trait hooks.
static AbstractOperation::OperationProperties getTraitProperties ()
Detailed Description
Definition at line 171 of file Ops.h.
Member Function Documentation
build()
void DmaStartOp::build (Builder * builder, OperationState & result, Value srcMemRef, ValueRange srcIndices, Value destMemRef, ValueRange destIndices, Value numElements, Value tagMemRef, ValueRange tagIndices, Value stride = nullptr, Value elementsPerStride = nullptr) static
Definition at line 1353 of file Ops.cpp.
References mlir::OperationState::addOperands().
fold()
LogicalResult DmaStartOp::fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > & results)
dma_start(memrefcast) -> dma_start
Definition at line 1486 of file Ops.cpp.
References foldMemRefCast().
getDstIndices()
operand_range mlir::DmaStartOp::getDstIndices () inline
Definition at line 208 of file Ops.h.
getDstMemorySpace()
unsigned mlir::DmaStartOp::getDstMemorySpace () inline
Definition at line 203 of file Ops.h.
getDstMemRef()
Value mlir::DmaStartOp::getDstMemRef () inline
Definition at line 195 of file Ops.h.
Referenced by mlir::lowerAffineUpperBound().
getDstMemRefRank()
unsigned mlir::DmaStartOp::getDstMemRefRank () inline
Definition at line 197 of file Ops.h.
getFasterMemPos()
unsigned mlir::DmaStartOp::getFasterMemPos () inline
Given a DMA start operation, returns the operand position of either the source or destination memref depending on the one that is at the higher level of the memory hierarchy.
Asserts failure if neither is true.
Definition at line 251 of file Ops.h.
getNumElements()
Value mlir::DmaStartOp::getNumElements () inline
Definition at line 215 of file Ops.h.
Referenced by mlir::lowerAffineUpperBound().
getNumElementsPerStride()
Value mlir::DmaStartOp::getNumElementsPerStride () inline
Definition at line 275 of file Ops.h.
References mlir::isStrided().
Referenced by mlir::lowerAffineUpperBound().
getOperationName()
static StringRef mlir::DmaStartOp::getOperationName () inline static
Definition at line 256 of file Ops.h.
References print(), and mlir::verify().
getSrcIndices()
operand_range mlir::DmaStartOp::getSrcIndices () inline
Definition at line 189 of file Ops.h.
getSrcMemorySpace()
unsigned mlir::DmaStartOp::getSrcMemorySpace () inline
Definition at line 200 of file Ops.h.
getSrcMemRef()
Value mlir::DmaStartOp::getSrcMemRef () inline
Definition at line 183 of file Ops.h.
Referenced by mlir::lowerAffineUpperBound().
getSrcMemRefRank()
unsigned mlir::DmaStartOp::getSrcMemRefRank () inline
Definition at line 185 of file Ops.h.
getStride()
Value mlir::DmaStartOp::getStride () inline
Definition at line 269 of file Ops.h.
References mlir::isStrided().
Referenced by mlir::lowerAffineUpperBound().
getTagIndices()
operand_range mlir::DmaStartOp::getTagIndices () inline
Definition at line 229 of file Ops.h.
getTagMemRef()
Value mlir::DmaStartOp::getTagMemRef () inline
Definition at line 220 of file Ops.h.
Referenced by mlir::lowerAffineUpperBound().
getTagMemRefRank()
unsigned mlir::DmaStartOp::getTagMemRefRank () inline
Definition at line 224 of file Ops.h.
isDestMemorySpaceFaster()
bool mlir::DmaStartOp::isDestMemorySpaceFaster () inline
Returns true if this is a DMA from a faster memory space to a slower one.
Definition at line 238 of file Ops.h.
isSrcMemorySpaceFaster()
bool mlir::DmaStartOp::isSrcMemorySpaceFaster () inline
Returns true if this is a DMA from a slower memory space to a faster one.
Definition at line 243 of file Ops.h.
isStrided()
bool mlir::DmaStartOp::isStrided () inline
Definition at line 264 of file Ops.h.
parse()
ParseResult DmaStartOp::parse (OpAsmParser & parser, OperationState & result) static
Definition at line 1388 of file Ops.cpp.
References mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OpAsmParser::getNameLoc(), mlir::isStrided(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseTrailingOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::success().
print()
void DmaStartOp::print (OpAsmPrinter & p)
Definition at line 1368 of file Ops.cpp.
References mlir::isStrided(), and mlir::OpAsmPrinter::printOptionalAttrDict().
verify()
LogicalResult DmaStartOp::verify ()
Definition at line 1472 of file Ops.cpp.
References mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/StandardOps/Ops.h
lib/Dialect/StandardOps/Ops.cpp