MLIR: mlir::quantizer::AttributeTensorStatistics Class Reference
mlir::quantizer::AttributeTensorStatistics Class Reference
Wraps an MLIR Attribute and returns statistics about it.
#include "mlir/Quantizer/Support/Statistics.h"
Public Member Functions
AttributeTensorStatistics (Attribute attr)
bool get (TensorAxisStatistics &stats) const override
Gets statistics across the whole tensor.
Public Member Functions inherited from mlir::quantizer::AbstractTensorStatistics
virtual ~AbstractTensorStatistics ()=default
virtual bool supportsPerAxis () const
Whether this instance supports querying per axis statistics.
virtual unsigned getAxisCount () const
Count of axes supported in a per-axis query.
virtual bool getForAxis (unsigned axis, TensorAxisStatistics &stats) const
Gets statistics for a specific axis (0..getAxisCount() - 1).
Detailed Description
Wraps an MLIR Attribute and returns statistics about it.
It is expected that the attribute be one of: FloatAttr (scalar) DenseFPElementsAttr OpaqueElementsAttr (with Float based type) SparseElementAttr (with Float based type)
Definition at line 67 of file Statistics.h.
Constructor & Destructor Documentation
AttributeTensorStatistics()
mlir::quantizer::AttributeTensorStatistics::AttributeTensorStatistics (Attribute attr) inline
Definition at line 69 of file Statistics.h.
References mlir::quantizer::operator<<().
Member Function Documentation
get()
bool AttributeTensorStatistics::get (TensorAxisStatistics & stats) const override virtual
Gets statistics across the whole tensor.
Returns true if statistics are valid and were populated.
Reimplemented from mlir::quantizer::AbstractTensorStatistics.
Definition at line 78 of file Statistics.cpp.
References mlir::Attribute::dyn_cast(), and getElementsStatistics().
The documentation for this class was generated from the following files:
include/mlir/Quantizer/Support/Statistics.h
lib/Quantizer/Support/Statistics.cpp