MLIR: mlir::AffineDmaWaitOp Class Reference
mlir::AffineDmaWaitOp Class Reference
AffineDmaWaitOp blocks until the completion of a DMA operation associated with the tag element 'tag[index]'.
#include "mlir/Dialect/AffineOps/AffineOps.h"
Public Member Functions
Value getTagMemRef ()
MemRefType getTagMemRefType ()
AffineMap getTagMap ()
Returns the affine map used to access the tag memref.
AffineMapAttr getTagMapAttr ()
operand_range getTagIndices ()
unsigned getTagMemRefRank ()
NamedAttribute getAffineMapAttrForMemRef (Value memref)
Returns the AffineMapAttr associated with 'memref'.
Value getNumElements ()
Returns the number of elements transferred in the associated DMA op.
void print (OpAsmPrinter &p)
LogicalResult verify ()
LogicalResult fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > &results)
Public Member Functions inherited from mlir::Op< AffineDmaWaitOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
Operation * getOperation ()
Return the operation that this refers to.
AffineDmaWaitOp clone ()
Create a deep copy of this operation.
AffineDmaWaitOp cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Dialect * getDialect ()
Return the dialect that this refers to.
Region * getParentRegion ()
Return the parent Region of this operation.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow implicit conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * getOperation ()
Return the operation that this refers to.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
template<typename OpTy >
OpTy getParentOfType ()
Return the closest surrounding parent operation that is of type 'OpTy'.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState, OpPrintingFlags flags=llvm::None)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
void setLoc (Location loc)
ArrayRef< NamedAttribute > getAttrs ()
Return all of the attributes on this operation.
dialect_attr_range getDialectAttrs ()
Return a range corresponding to the dialect attributes for this operation.
dialect_attr_iterator dialect_attr_begin ()
dialect_attr_iterator dialect_attr_end ()
Attribute getAttr (StringRef name)
Return an attribute with the specified name.
template<typename AttrClass >
AttrClass getAttrOfType (StringRef name)
If the operation has an attribute of the specified type, return it.
void setAttr (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setAttr (StringRef name, Attribute value)
void setAttrs (ArrayRef< NamedAttribute > attributes)
Set the attributes held by this operation.
void setAttrs (NamedAttributeList newAttrs)
template<typename DialectAttrs >
void setDialectAttrs (DialectAttrs &&attrs)
Set the dialect attributes for this operation, and preserve all dependent.
NamedAttributeList::RemoveResult removeAttr (Identifier name)
Remove the attribute with the specified name if it exists.
NamedAttributeList::RemoveResult removeAttr (StringRef name)
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk the operation in postorder, calling the callback for each nested operation(including this one).
Public Member Functions inherited from mlir::OpTrait::detail::MultiOperandTraitBase< AffineDmaWaitOp, VariadicOperands >
unsigned getNumOperands ()
Return the number of operands.
Value getOperand (unsigned i)
Return the operand at index 'i'.
void setOperand (unsigned i, Value value)
Set the operand at index 'i' to 'value'.
operand_iterator operand_begin ()
Operand iterator access.
operand_iterator operand_end ()
operand_range getOperands ()
operand_type_iterator operand_type_begin ()
Operand type access.
operand_type_iterator operand_type_end ()
operand_type_range getOperandTypes ()
Public Member Functions inherited from mlir::FoldingHook< AffineDmaWaitOp, llvm::is_one_of< OpTrait::OneResult< AffineDmaWaitOp >, OpTrait::VariadicOperands< AffineDmaWaitOp >... >::value >
LogicalResult fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This hook implements a generalized folder for this operation.
Static Public Member Functions
static void build (Builder *builder, OperationState &result, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements)
static StringRef getOperationName ()
static StringRef getTagMapAttrName ()
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Static Public Member Functions inherited from mlir::Op< AffineDmaWaitOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
static ParseResult parseAssembly (OpAsmParser &parser, OperationState &result)
This is the hook used by the AsmParser to parse the custom form of this op from an .mlir file.
static void printAssembly (Operation *op, OpAsmPrinter &p)
This is the hook used by the AsmPrinter to emit this to the .mlir file.
static LogicalResult verifyInvariants (Operation *op)
This is the hook that checks whether or not this operation is well formed according to the invariants of its opcode.
static AbstractOperation::OperationProperties getOperationProperties ()
static ConcreteOpType getFromOpaquePointer (const void *pointer)
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (OwningRewritePatternList &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Static Public Member Functions inherited from mlir::FoldingHook< AffineDmaWaitOp, llvm::is_one_of< OpTrait::OneResult< AffineDmaWaitOp >, OpTrait::VariadicOperands< AffineDmaWaitOp >... >::value >
static LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This is an implementation detail of the constant folder hook for AbstractOperation.
Additional Inherited Members
Public Types inherited from mlir::Op< AffineDmaWaitOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >
using ConcreteOpType = AffineDmaWaitOp
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
Public Types inherited from mlir::OpState
using dialect_attr_iterator = Operation::dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
using dialect_attr_range = Operation::dialect_attr_range
Public Types inherited from mlir::OpTrait::detail::MultiOperandTraitBase< AffineDmaWaitOp, VariadicOperands >
using operand_iterator = Operation::operand_iterator
using operand_range = Operation::operand_range
using operand_type_iterator = Operation::operand_type_iterator
using operand_type_range = Operation::operand_type_range
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
void print (OpAsmPrinter &p)
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< AffineDmaWaitOp, VariadicOperands >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Unless overridden, the custom assembly form of an op is always rejected.
Static Protected Member Functions inherited from mlir::OpTrait::TraitBase< AffineDmaWaitOp, VariadicOperands >
static LogicalResult verifyTrait (Operation *op)
Provide default implementations of trait hooks.
static AbstractOperation::OperationProperties getTraitProperties ()
Detailed Description
AffineDmaWaitOp blocks until the completion of a DMA operation associated with the tag element 'tag[index]'.
tag is a memref, and index has to be an index with the same restrictions as any load/store index. In particular, index for each memref dimension must be an affine expression of loop induction variables and symbols. num_elements is the number of elements associated with the DMA operation. For example:
Definition at line 325 of file AffineOps.h.
Member Function Documentation
build()
void AffineDmaWaitOp::build (Builder * builder, OperationState & result, Value tagMemRef, AffineMap tagMap, ValueRange tagIndices, Value numElements) static
Definition at line 1006 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), and mlir::AffineMapAttr::get().
fold()
LogicalResult AffineDmaWaitOp::fold (ArrayRef< Attribute > cstOperands, SmallVectorImpl< OpFoldResult > & results)
dma_wait(memrefcast) -> dma_wait
Definition at line 1071 of file AffineOps.cpp.
References mlir::Block::addArgument(), mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty(), foldMemRefCast(), mlir::IndexType::get(), mlir::AffineMapAttr::get(), mlir::AffineMap::getConstantMap(), mlir::Builder::getContext(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::AffineMap::getNumInputs(), mlir::OperationState::location, mlir::Region::push_back(), mlir::OperationState::setOperandListToResizable(), and mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
getAffineMapAttrForMemRef()
NamedAttribute mlir::AffineDmaWaitOp::getAffineMapAttrForMemRef (Value memref) inline
Returns the AffineMapAttr associated with 'memref'.
Definition at line 359 of file AffineOps.h.
References mlir::Identifier::get(), and mlir::Dialect::getContext().
getNumElements()
Value mlir::AffineDmaWaitOp::getNumElements () inline
Returns the number of elements transferred in the associated DMA op.
Definition at line 366 of file AffineOps.h.
getOperationName()
static StringRef mlir::AffineDmaWaitOp::getOperationName () inline static
Definition at line 333 of file AffineOps.h.
getTagIndices()
operand_range mlir::AffineDmaWaitOp::getTagIndices () inline
Definition at line 348 of file AffineOps.h.
Referenced by checkTagMatch(), and mlir::lowerAffineUpperBound().
getTagMap()
AffineMap mlir::AffineDmaWaitOp::getTagMap () inline
Returns the affine map used to access the tag memref.
Definition at line 342 of file AffineOps.h.
Referenced by mlir::lowerAffineUpperBound().
getTagMapAttr()
AffineMapAttr mlir::AffineDmaWaitOp::getTagMapAttr () inline
Definition at line 343 of file AffineOps.h.
getTagMapAttrName()
static StringRef mlir::AffineDmaWaitOp::getTagMapAttrName () inline static
Definition at line 368 of file AffineOps.h.
References print(), and mlir::verify().
getTagMemRef()
Value mlir::AffineDmaWaitOp::getTagMemRef () inline
Definition at line 336 of file AffineOps.h.
Referenced by checkTagMatch().
getTagMemRefRank()
unsigned mlir::AffineDmaWaitOp::getTagMemRefRank () inline
Definition at line 354 of file AffineOps.h.
getTagMemRefType()
MemRefType mlir::AffineDmaWaitOp::getTagMemRefType () inline
Definition at line 337 of file AffineOps.h.
parse()
ParseResult AffineDmaWaitOp::parse (OpAsmParser & parser, OperationState & result) static
Definition at line 1029 of file AffineOps.cpp.
References mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OpAsmParser::getNameLoc(), mlir::AffineMap::getNumInputs(), mlir::AffineMapAttr::getValue(), mlir::Type::isa(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
print()
void AffineDmaWaitOp::print (OpAsmPrinter & p)
Definition at line 1015 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), and mlir::OpAsmPrinter::printOperand().
verify()
LogicalResult AffineDmaWaitOp::verify ()
Definition at line 1059 of file AffineOps.cpp.
References isValidAffineIndexOperand(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/AffineOps/AffineOps.h
lib/Dialect/AffineOps/AffineOps.cpp