MLIR: mlir::BoolAttr Class Reference
mlir::BoolAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = bool
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
bool getValue () const
Static Public Member Functions
static BoolAttr get (bool value, MLIRContext *context)
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 244 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::BoolAttr::ValueType = bool
Definition at line 248 of file Attributes.h.
Member Function Documentation
get()
BoolAttr BoolAttr::get (bool value, MLIRContext * context) static
Definition at line 551 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::falseAttr, mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::trueAttr.
Referenced by mlir::Builder::getBoolAttr(), mlir::SparseElementsAttr::getValue(), makeBoolAttr(), and mlir::DenseElementsAttr::AttributeElementIterator::operator*().
getValue()
bool BoolAttr::getValue () const
Definition at line 75 of file Attributes.cpp.
Referenced by getLastStructuredControlFlowOpMergeBlock().
kindof()
static bool mlir::BoolAttr::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 255 of file Attributes.h.
References mlir::StandardAttributes::Bool.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp
lib/IR/MLIRContext.cpp