MLIR: mlir::quantizer::CAGNode Class Reference
mlir::quantizer::CAGNode Class Reference
A node in the Constraint Analysis Graph.
#include "mlir/Quantizer/Support/ConstraintAnalysisGraph.h"
Public Types
enum Kind {
Kind::Anchor, Kind::OperandAnchor, Kind::ResultAnchor, Kind::LastAnchor = ResultAnchor,
Kind::Constraint, Kind::SolveUniformConstraint, Kind::UniformPropagateExplicitScale, Kind::LastConstraint = UniformPropagateExplicitScale
}
using node_vector = SmallVector< CAGNode *, 1 >
using iterator = node_vector::iterator
using const_iterator = node_vector::const_iterator
Public Member Functions
virtual ~CAGNode ()=default
Kind getKind () const
int getNodeId () const
Unique id of the node within the slice.
bool isDirty () const
Whether the node is dirty, requiring one or more calls to propagate().
void markDirty ()
void clearDirty ()
const_iterator begin () const
Iterator over this node's children (outgoing) nodes.
const_iterator end () const
iterator begin ()
iterator end ()
const_iterator incoming_begin () const
Iterator over this parents (incoming) nodes.
const_iterator incoming_end () const
iterator incoming_begin ()
iterator incoming_end ()
virtual void propagate (SolverContext &solverContext, const TargetConfiguration &config)
virtual void printLabel (raw_ostream &os) const
Prints the node label, suitable for one-line display.
template<typename T >
void findChildrenOfKind (SmallVectorImpl< T *> &found)
void replaceIncoming (CAGNode *otherNode)
Replaces this node by rerouting any parent nodes to have otherNode as a child.
void addOutgoing (CAGNode *toNode)
Adds an outgoing connection to this node (and corresponding back incoming connection).
bool isOrphan () const
Whether this node is an orphan (has no incoming or outgoing connections).
Protected Member Functions
CAGNode (Kind kind)
Friends
class CAGSlice
Detailed Description
A node in the Constraint Analysis Graph.
Nodes are either anchors (representing results and operands) or constraints. Anchor nodes are connected to other anchor nodes via constraints. Nodes exist within graph slices, which are typically analyses attached to the function or module. Slices can contain other slices, which mirrors the nesting of analyses.
Nodes have directed relationships which propagate successor-ward when dirty. Relationships can be bi-directional, in which case, the constraint's propagation mechanism must ensure convergence.
Definition at line 45 of file ConstraintAnalysisGraph.h.
Member Typedef Documentation
const_iterator
using mlir::quantizer::CAGNode::const_iterator = node_vector::const_iterator
Definition at line 64 of file ConstraintAnalysisGraph.h.
iterator
using mlir::quantizer::CAGNode::iterator = node_vector::iterator
Definition at line 63 of file ConstraintAnalysisGraph.h.
node_vector
using mlir::quantizer::CAGNode::node_vector = SmallVector<CAGNode *, 1>
Definition at line 62 of file ConstraintAnalysisGraph.h.
Member Enumeration Documentation
Kind
enum mlir::quantizer::CAGNode::Kind strong
Enumerator
Anchor
Anchors.
OperandAnchor
ResultAnchor
LastAnchor
Constraint
Constraints.
SolveUniformConstraint
UniformPropagateExplicitScale
LastConstraint
Definition at line 47 of file ConstraintAnalysisGraph.h.
Constructor & Destructor Documentation
~CAGNode()
virtual mlir::quantizer::CAGNode::~CAGNode () virtual default
CAGNode()
mlir::quantizer::CAGNode::CAGNode (Kind kind) inline protected
Definition at line 117 of file ConstraintAnalysisGraph.h.
Member Function Documentation
addOutgoing()
void CAGNode::addOutgoing (CAGNode * toNode)
Adds an outgoing connection to this node (and corresponding back incoming connection).
Definition at line 32 of file ConstraintAnalysisGraph.cpp.
Referenced by mlir::quantizer::CAGSlice::addUnidirectionalConstraint(), and findChildrenOfKind().
begin() [1/2]
const_iterator mlir::quantizer::CAGNode::begin () const inline
Iterator over this node's children (outgoing) nodes.
Definition at line 79 of file ConstraintAnalysisGraph.h.
Referenced by llvm::GraphTraits< const mlir::quantizer::CAGNode * >::child_begin().
begin() [2/2]
iterator mlir::quantizer::CAGNode::begin () inline
Definition at line 81 of file ConstraintAnalysisGraph.h.
clearDirty()
void mlir::quantizer::CAGNode::clearDirty () inline
Definition at line 76 of file ConstraintAnalysisGraph.h.
end() [1/2]
const_iterator mlir::quantizer::CAGNode::end () const inline
Definition at line 80 of file ConstraintAnalysisGraph.h.
Referenced by llvm::GraphTraits< const mlir::quantizer::CAGNode * >::child_end().
end() [2/2]
iterator mlir::quantizer::CAGNode::end () inline
Definition at line 82 of file ConstraintAnalysisGraph.h.
findChildrenOfKind()
template<typename T > void mlir::quantizer::CAGNode::findChildrenOfKind (SmallVectorImpl< T *> & found) inline
Definition at line 96 of file ConstraintAnalysisGraph.h.
References addOutgoing(), and replaceIncoming().
getKind()
Kind mlir::quantizer::CAGNode::getKind () const inline
Definition at line 68 of file ConstraintAnalysisGraph.h.
Referenced by mlir::quantizer::CAGAnchorNode::classof(), mlir::quantizer::CAGOperandAnchor::classof(), mlir::quantizer::CAGResultAnchor::classof(), mlir::quantizer::CAGConstraintNode::classof(), llvm::DOTGraphTraits< const CAGSlice * >::getNodeAttributes(), and solveUniformType().
getNodeId()
int mlir::quantizer::CAGNode::getNodeId () const inline
Unique id of the node within the slice.
Definition at line 71 of file ConstraintAnalysisGraph.h.
incoming_begin() [1/2]
const_iterator mlir::quantizer::CAGNode::incoming_begin () const inline
Iterator over this parents (incoming) nodes.
Definition at line 85 of file ConstraintAnalysisGraph.h.
incoming_begin() [2/2]
iterator mlir::quantizer::CAGNode::incoming_begin () inline
Definition at line 87 of file ConstraintAnalysisGraph.h.
incoming_end() [1/2]
const_iterator mlir::quantizer::CAGNode::incoming_end () const inline
Definition at line 86 of file ConstraintAnalysisGraph.h.
incoming_end() [2/2]
iterator mlir::quantizer::CAGNode::incoming_end () inline
Definition at line 88 of file ConstraintAnalysisGraph.h.
isDirty()
bool mlir::quantizer::CAGNode::isDirty () const inline
Whether the node is dirty, requiring one or more calls to propagate().
Definition at line 74 of file ConstraintAnalysisGraph.h.
Referenced by mlir::quantizer::CAGSlice::propagate().
isOrphan()
bool mlir::quantizer::CAGNode::isOrphan () const inline
Whether this node is an orphan (has no incoming or outgoing connections).
Definition at line 114 of file ConstraintAnalysisGraph.h.
Referenced by llvm::DOTGraphTraits< const CAGSlice * >::isNodeHidden().
markDirty()
void mlir::quantizer::CAGNode::markDirty () inline
Definition at line 75 of file ConstraintAnalysisGraph.h.
Referenced by mlir::quantizer::CAGAnchorNode::propagate().
printLabel()
void CAGNode::printLabel (raw_ostream & os) const virtual
Prints the node label, suitable for one-line display.
Reimplemented in mlir::quantizer::CAGResultAnchor, mlir::quantizer::CAGOperandAnchor, and mlir::quantizer::CAGAnchorNode.
Definition at line 151 of file ConstraintAnalysisGraph.cpp.
Referenced by mlir::quantizer::CAGAnchorNode::classof(), llvm::DOTGraphTraits< const CAGSlice * >::getNodeLabel(), mlir::quantizer::CAGOperandAnchor::getValue(), mlir::quantizer::CAGResultAnchor::getValue(), mlir::quantizer::operator<<(), and propagate().
propagate()
virtual void mlir::quantizer::CAGNode::propagate (SolverContext & solverContext, const TargetConfiguration & config) inline virtual
Reimplemented in mlir::quantizer::CAGAnchorNode.
Definition at line 90 of file ConstraintAnalysisGraph.h.
References printLabel().
Referenced by mlir::quantizer::CAGSlice::addClusteredConstraint(), and mlir::quantizer::CAGAnchorNode::classof().
replaceIncoming()
void CAGNode::replaceIncoming (CAGNode * otherNode)
Replaces this node by rerouting any parent nodes to have otherNode as a child.
Definition at line 18 of file ConstraintAnalysisGraph.cpp.
Referenced by findChildrenOfKind().
Friends And Related Function Documentation
CAGSlice
friend class CAGSlice friend
Definition at line 126 of file ConstraintAnalysisGraph.h.
The documentation for this class was generated from the following files:
include/mlir/Quantizer/Support/ConstraintAnalysisGraph.h
lib/Quantizer/Support/ConstraintAnalysisGraph.cpp