MLIR: mlir::TypeConverter Class Reference
mlir::TypeConverter Class Reference
Base class for type conversion interface.
#include "mlir/Transforms/DialectConversion.h"
Classes
class SignatureConversion
This class provides all of the information necessary to convert a type signature.
Public Member Functions
virtual ~TypeConverter ()=default
virtual LogicalResult convertType (Type t, SmallVectorImpl< Type > &results)
This hook allows for converting a type.
virtual Type convertType (Type t)
This hook simplifies defining 1-1 type conversions.
LogicalResult convertTypes (ArrayRef< Type > types, SmallVectorImpl< Type > &results)
Convert the given set of types, filling 'results' as necessary.
bool isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
bool isSignatureLegal (FunctionType funcType)
Return true if the inputs and outputs of the given function type are legal.
virtual LogicalResult convertSignatureArg (unsigned inputNo, Type type, SignatureConversion &result)
This hook allows for converting a specific argument of a signature.
Optional< SignatureConversion > convertBlockSignature (Block *block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
virtual Operation * materializeConversion (PatternRewriter &rewriter, Type resultType, ArrayRef< Value > inputs, Location loc)
This hook allows for materializing a conversion from a set of types into one result type by generating a cast operation of some kind.
Detailed Description
Base class for type conversion interface.
Specific converters must derive this class and implement the pure virtual functions.
Definition at line 39 of file DialectConversion.h.
Constructor & Destructor Documentation
~TypeConverter()
virtual mlir::TypeConverter::~TypeConverter () virtual default
Member Function Documentation
convertBlockSignature()
auto TypeConverter::convertBlockSignature (Block * block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
This function should return a valid conversion for the signature on success, None otherwise.
Definition at line 1662 of file DialectConversion.cpp.
References mlir::failed(), mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::BlockArgument::getType(), and mlir::StandardTypes::None.
Referenced by convertType().
convertSignatureArg()
LogicalResult TypeConverter::convertSignatureArg (unsigned inputNo, Type type, SignatureConversion & result) virtual
This hook allows for converting a specific argument of a signature.
It takes as inputs the original argument input number, type. On success, this function should populate 'result' with any new mappings.
Definition at line 1599 of file DialectConversion.cpp.
References mlir::TypeConverter::SignatureConversion::addInputs(), mlir::ConversionPatternRewriter::applySignatureConversion(), convertSignatureArg(), convertTypes(), mlir::failed(), mlir::failure(), mlir::FunctionType::get(), mlir::OpState::getContext(), mlir::FunctionType::getInput(), mlir::FunctionType::getNumInputs(), mlir::FunctionType::getResults(), mlir::FuncOp::getType(), mlir::FuncOp::setType(), mlir::success(), and mlir::PatternRewriter::updateRootInPlace().
Referenced by convertSignatureArg(), and convertType().
convertType() [1/2]
LogicalResult TypeConverter::convertType (Type t, SmallVectorImpl< Type > & results) virtual
This hook allows for converting a type.
This hooks allows for converting a type.
This function should return failure if no valid conversion exists, success otherwise. If the new set of types is empty, the type is removed and any usages of the existing value are expected to be removed during conversion.
Definition at line 1562 of file DialectConversion.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::TypeConverter::SignatureConversion::getInputMapping().
convertType() [2/2]
virtual Type mlir::TypeConverter::convertType (Type t) inline virtual
This hook simplifies defining 1-1 type conversions.
This function returns the type to convert to on success, and a null type on failure.
Reimplemented in mlir::LLVMTypeConverter, mlir::SPIRVTypeConverter, and mlir::LinalgTypeConverter.
Definition at line 102 of file DialectConversion.h.
References convertBlockSignature(), convertSignatureArg(), convertTypes(), mlir::TypeConverter::SignatureConversion::InputMapping::inputNo, isLegal(), and isSignatureLegal().
convertTypes()
LogicalResult TypeConverter::convertTypes (ArrayRef< Type > types, SmallVectorImpl< Type > & results)
Convert the given set of types, filling 'results' as necessary.
This returns failure if the conversion of any of the types fails, success otherwise.
Definition at line 1574 of file DialectConversion.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
Referenced by convertSignatureArg(), and convertType().
isLegal()
bool TypeConverter::isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
the type converts to itself.
Definition at line 1584 of file DialectConversion.cpp.
References mlir::succeeded().
Referenced by mlir::ConversionTarget::addIllegalDialect(), and convertType().
isSignatureLegal()
bool TypeConverter::isSignatureLegal (FunctionType funcType)
Return true if the inputs and outputs of the given function type are legal.
Definition at line 1592 of file DialectConversion.cpp.
References mlir::FunctionType::getInputs(), and mlir::FunctionType::getResults().
Referenced by convertType(), mlir::populateLinalgToLLVMConversionPatterns(), and mlir::populateVectorToLLVMConversionPatterns().
materializeConversion()
virtual Operation* mlir::TypeConverter::materializeConversion (PatternRewriter & rewriter, Type resultType, ArrayRef< Value > inputs, Location loc) inline virtual
This hook allows for materializing a conversion from a set of types into one result type by generating a cast operation of some kind.
The generated operation should produce one result, of 'resultType', with the provided 'inputs' as operands. This hook must be overridden when a type conversion results in more than one type, or if a type conversion may persist after the conversion has finished.
Definition at line 135 of file DialectConversion.h.
The documentation for this class was generated from the following files:
include/mlir/Transforms/DialectConversion.h
lib/Transforms/DialectConversion.cpp