MLIR: mlir::PostDominanceInfo Class Reference
mlir::PostDominanceInfo Class Reference
A class for computing basic postdominance information.
#include "mlir/Analysis/Dominance.h"
Public Member Functions
bool properlyPostDominates (Operation *a, Operation *b)
Return true if operation A properly postdominates operation B.
bool postDominates (Operation *a, Operation *b)
Return true if operation A postdominates operation B.
bool properlyPostDominates (Block *a, Block *b)
Return true if the specified block A properly postdominates block B.
bool postDominates (Block *a, Block *b)
Return true if the specified block A postdominates block B.
Public Member Functions inherited from mlir::detail::DominanceInfoBase< true >
DominanceInfoBase (Operation *op)
DominanceInfoBase (DominanceInfoBase &&)=default
DominanceInfoBase (const DominanceInfoBase &)=delete
DominanceInfoBase & operator= (DominanceInfoBase &&)=default
DominanceInfoBase & operator= (const DominanceInfoBase &)=delete
void recalculate (Operation *op)
Recalculate the dominance info.
DominanceInfoNode * getRootNode (Region *region)
Get the root dominance node of the given region.
Additional Inherited Members
Protected Types inherited from mlir::detail::DominanceInfoBase< true >
using super = DominanceInfoBase< IsPostDom >
Protected Member Functions inherited from mlir::detail::DominanceInfoBase< true >
bool properlyDominates (Block *a, Block *b)
Return true if the specified block A properly dominates block B.
Protected Attributes inherited from mlir::detail::DominanceInfoBase< true >
DenseMap< Region *, std::unique_ptr< base > > dominanceInfos
A mapping of regions to their base dominator tree.
Detailed Description
A class for computing basic postdominance information.
Definition at line 93 of file Dominance.h.
Member Function Documentation
postDominates() [1/2]
bool mlir::PostDominanceInfo::postDominates (Operation * a, Operation * b) inline
Return true if operation A postdominates operation B.
Definition at line 101 of file Dominance.h.
postDominates() [2/2]
bool mlir::PostDominanceInfo::postDominates (Block * a, Block * b) inline
Return true if the specified block A postdominates block B.
Definition at line 111 of file Dominance.h.
properlyPostDominates() [1/2]
bool PostDominanceInfo::properlyPostDominates (Operation * a, Operation * b)
Return true if operation A properly postdominates operation B.
Returns true if statement 'a' properly postdominates statement b.
Definition at line 151 of file Dominance.cpp.
References mlir::Block::findAncestorOpInBlock(), mlir::Operation::getBlock(), and mlir::Operation::isBeforeInBlock().
properlyPostDominates() [2/2]
bool mlir::PostDominanceInfo::properlyPostDominates (Block * a, Block * b) inline
Return true if the specified block A properly postdominates block B.
Definition at line 106 of file Dominance.h.
The documentation for this class was generated from the following files:
include/mlir/Analysis/Dominance.h
lib/Analysis/Dominance.cpp