MLIR: mlir::OwningRewritePatternList Class Reference
mlir::OwningRewritePatternList Class Reference
#include "mlir/IR/PatternMatch.h"
Public Member Functions
PatternListT::iterator begin ()
PatternListT::iterator end ()
PatternListT::const_iterator begin () const
PatternListT::const_iterator end () const
void clear ()
template<typename... Ts, typename ConstructorArg , typename... ConstructorArgs, typename = std::enable_if_t<sizeof...(Ts) != 0>>
void insert (ConstructorArg &&arg, ConstructorArgs &&... args)
Add an instance of each of the pattern types 'Ts' to the pattern list with the given arguments.
Detailed Description
Definition at line 399 of file PatternMatch.h.
Member Function Documentation
begin() [1/2]
PatternListT::iterator mlir::OwningRewritePatternList::begin () inline
Definition at line 403 of file PatternMatch.h.
begin() [2/2]
PatternListT::const_iterator mlir::OwningRewritePatternList::begin () const inline
Definition at line 405 of file PatternMatch.h.
clear()
void mlir::OwningRewritePatternList::clear () inline
Definition at line 407 of file PatternMatch.h.
end() [1/2]
PatternListT::iterator mlir::OwningRewritePatternList::end () inline
Definition at line 404 of file PatternMatch.h.
end() [2/2]
PatternListT::const_iterator mlir::OwningRewritePatternList::end () const inline
Definition at line 406 of file PatternMatch.h.
insert()
template<typename... Ts, typename ConstructorArg , typename... ConstructorArgs, typename = std::enable_if_t<sizeof...(Ts) != 0>> void mlir::OwningRewritePatternList::insert (ConstructorArg && arg, ConstructorArgs &&... args) inline
Add an instance of each of the pattern types 'Ts' to the pattern list with the given arguments.
Note: ConstructorArg is necessary here to separate the two variadic lists.
Definition at line 419 of file PatternMatch.h.
Referenced by canonicalizeLoopBounds(), mlir::LinalgTypeConverter::convertType(), mlir::fxpmath::createLowerUniformRealMathPass(), emitLoopRanges(), mlir::AffineApplyOp::getCanonicalizationPatterns(), mlir::AffineLoadOp::getCanonicalizationPatterns(), mlir::AffineStoreOp::getCanonicalizationPatterns(), lowerEntryPointABIAttr(), mlir::operator<<(), parseLaunchOp(), mlir::populateAffineToStdConversionPatterns(), mlir::populateBuiltinFuncToSPIRVPatterns(), mlir::populateFuncOpTypeConversionPattern(), mlir::populateGpuRewritePatterns(), mlir::populateGpuToNVVMConversionPatterns(), mlir::populateGPUToSPIRVPatterns(), mlir::populateLinalgToLLVMConversionPatterns(), mlir::populateLoopToStdConversionPatterns(), populateSPIRVLayoutInfoPatterns(), mlir::populateStandardToSPIRVPatterns(), mlir::populateStdLegalizationPatternsForSPIRVLowering(), mlir::populateStdToLLVMMemoryConversionPatters(), mlir::populateStdToLLVMNonMemoryConversionPatterns(), mlir::vector::populateVectorSlicesLoweringPatterns(), mlir::populateVectorToAffineLoopsConversionPatterns(), mlir::populateVectorToLLVMConversionPatterns(), mlir::vector::populateVectorToVectorCanonicalizationPatterns(), mlir::vector::populateVectorToVectorTransformationPatterns(), print(), tryRewriteAffineMulEwSigned(), and verify().
The documentation for this class was generated from the following file:
include/mlir/IR/PatternMatch.h