MLIR: mlir::edsc::TemplatedIndexedValue< Load, Store > Class Template Reference
mlir::edsc::TemplatedIndexedValue< Load, Store > Class Template Reference
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
#include "mlir/EDSC/Helpers.h"
Public Member Functions
TemplatedIndexedValue (Type t)
TemplatedIndexedValue (Value v)
TemplatedIndexedValue (ValueHandle v)
TemplatedIndexedValue (const TemplatedIndexedValue &rhs)=default
TemplatedIndexedValue operator() ()
TemplatedIndexedValue operator() (ValueHandle index)
Returns a new TemplatedIndexedValue.
template<typename... Args>
TemplatedIndexedValue operator() (ValueHandle index, Args... indices)
TemplatedIndexedValue operator() (ArrayRef< ValueHandle > indices)
TemplatedIndexedValue operator() (ArrayRef< IndexHandle > indices)
OperationHandle operator= (const TemplatedIndexedValue &rhs)
Emits a store.
OperationHandle operator= (ValueHandle rhs)
operator ValueHandle () const
Emits a load when converting to a ValueHandle.
Value operator* (void) const
Emits a load when converting to a Value.
ValueHandle getBase () const
ValueHandle operator+ (ValueHandle e)
Operator overloadings.
ValueHandle operator- (ValueHandle e)
ValueHandle operator* (ValueHandle e)
ValueHandle operator/ (ValueHandle e)
OperationHandle operator+= (ValueHandle e)
OperationHandle operator-= (ValueHandle e)
OperationHandle operator*= (ValueHandle e)
OperationHandle operator/= (ValueHandle e)
ValueHandle operator+ (TemplatedIndexedValue e)
ValueHandle operator- (TemplatedIndexedValue e)
ValueHandle operator* (TemplatedIndexedValue e)
ValueHandle operator/ (TemplatedIndexedValue e)
OperationHandle operator+= (TemplatedIndexedValue e)
OperationHandle operator-= (TemplatedIndexedValue e)
OperationHandle operator*= (TemplatedIndexedValue e)
OperationHandle operator/= (TemplatedIndexedValue e)
Detailed Description
template<typename Load, typename Store>
class mlir::edsc::TemplatedIndexedValue< Load, Store >
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
This helper class is an abstraction purely for sugaring purposes and allows writing compact expressions such as:
// `IndexedValue` provided by default in the mlir::edsc namespace.
using IndexedValue =
  TemplatedIndexedValue<intrinsics::load, intrinsics::store>;
IndexedValue A(...), B(...), C(...);
For(ivs, zeros, shapeA, ones, {
  C(ivs) = A(ivs) + B(ivs)
});
Assigning to an IndexedValue emits an actual Store operation, while converting an IndexedValue to a ValueHandle emits an actual Load operation.
Definition at line 24 of file Helpers.h.
Constructor & Destructor Documentation
TemplatedIndexedValue() [1/4]
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::TemplatedIndexedValue (Type t) inline explicit
Definition at line 113 of file Helpers.h.
TemplatedIndexedValue() [2/4]
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::TemplatedIndexedValue (Value v) inline explicit
Definition at line 114 of file Helpers.h.
TemplatedIndexedValue() [3/4]
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::TemplatedIndexedValue (ValueHandle v) inline explicit
Definition at line 116 of file Helpers.h.
TemplatedIndexedValue() [4/4]
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::TemplatedIndexedValue (const TemplatedIndexedValue< Load, Store > & rhs) default
Member Function Documentation
getBase()
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::getBase () const inline
Definition at line 160 of file Helpers.h.
References mlir::operator*(), mlir::operator+(), mlir::operator-(), and mlir::edsc::op::operator/().
operator ValueHandle()
template<typename Load , typename Store > mlir::edsc::TemplatedIndexedValue< Load, Store >::operator ValueHandle () const inline
Emits a load when converting to a ValueHandle.
Definition at line 151 of file Helpers.h.
operator()() [1/5]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() () inline
Definition at line 120 of file Helpers.h.
operator()() [2/5]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (ValueHandle index) inline
Returns a new TemplatedIndexedValue.
Definition at line 122 of file Helpers.h.
operator()() [3/5]
template<typename Load , typename Store > template<typename... Args> TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (ValueHandle index, Args... indices) inline
Definition at line 128 of file Helpers.h.
operator()() [4/5]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (ArrayRef< ValueHandle > indices) inline
Definition at line 131 of file Helpers.h.
operator()() [5/5]
template<typename Load , typename Store > TemplatedIndexedValue mlir::edsc::TemplatedIndexedValue< Load, Store >::operator() (ArrayRef< IndexHandle > indices) inline
Definition at line 134 of file Helpers.h.
operator*() [1/3]
template<typename Load , typename Store > Value mlir::edsc::TemplatedIndexedValue< Load, Store >::operator* (void) const inline
Emits a load when converting to a Value.
Definition at line 156 of file Helpers.h.
operator*() [2/3]
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator* (ValueHandle e)
Definition at line 224 of file Helpers.h.
operator*() [3/3]
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator* (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 177 of file Helpers.h.
operator*=() [1/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator*= (ValueHandle e)
Definition at line 245 of file Helpers.h.
operator*=() [2/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator*= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 189 of file Helpers.h.
operator+() [1/2]
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+ (ValueHandle e)
Operator overloadings.
Definition at line 214 of file Helpers.h.
operator+() [2/2]
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+ (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 171 of file Helpers.h.
operator+=() [1/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+= (ValueHandle e)
Definition at line 235 of file Helpers.h.
operator+=() [2/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator+= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 183 of file Helpers.h.
operator-() [1/2]
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator- (ValueHandle e)
Definition at line 219 of file Helpers.h.
operator-() [2/2]
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator- (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 174 of file Helpers.h.
operator-=() [1/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator-= (ValueHandle e)
Definition at line 240 of file Helpers.h.
operator-=() [2/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator-= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 186 of file Helpers.h.
operator/() [1/2]
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/ (ValueHandle e)
Definition at line 229 of file Helpers.h.
operator/() [2/2]
template<typename Load , typename Store > ValueHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/ (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 180 of file Helpers.h.
operator/=() [1/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/= (ValueHandle e)
Definition at line 250 of file Helpers.h.
operator/=() [2/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator/= (TemplatedIndexedValue< Load, Store > e) inline
Definition at line 192 of file Helpers.h.
operator=() [1/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator= (const TemplatedIndexedValue< Load, Store > & rhs) inline
Emits a store.
Definition at line 141 of file Helpers.h.
operator=() [2/2]
template<typename Load , typename Store > OperationHandle mlir::edsc::TemplatedIndexedValue< Load, Store >::operator= (ValueHandle rhs) inline
Definition at line 146 of file Helpers.h.
The documentation for this class was generated from the following file:
include/mlir/EDSC/Helpers.h