MLIR: mlir::OpOperand Class Reference
mlir::OpOperand Class Reference
A reference to a value, suitable for use as an operand of an operation.
#include "mlir/IR/UseDefLists.h"
Public Member Functions
Value get () const
Return the current value being used by this operand.
void set (Value value)
Set the operand to the given value.
unsigned getOperandNumber ()
Return which operand this is in the operand list of the User.
Public Member Functions inherited from mlir::IROperand< OpOperand, detail::OpaqueValue >
IROperand (Operation *owner)
IROperand (Operation *owner, ValueType value)
IROperand (IROperand &&other)
We support a move constructor so IROperand's can be in vectors, but this shouldn't be used by general clients.
ValueType get () const
Return the current value being used by this operand.
void set (ValueType newValue)
Set the current value being used by this operand.
Operation * getOwner ()
Return the owner of this operand.
Operation * getOwner () const
void drop ()
Remove this use of the operand.
~IROperand ()
OpOperand * getNextOperandUsingThisValue ()
Return the next operand on the use-list of the value we are referring to.
IROperand & operator= (IROperand &&other)
Static Public Member Functions
static IRObjectWithUseList< OpOperand > * getUseList (Value value)
Provide the use list that is attached to the given value.
Additional Inherited Members
Public Types inherited from mlir::IROperand< OpOperand, detail::OpaqueValue >
using ValueType = detail::OpaqueValue
Detailed Description
A reference to a value, suitable for use as an operand of an operation.
Definition at line 330 of file UseDefLists.h.
Member Function Documentation
get()
Value OpOperand::get () const
Return the current value being used by this operand.
Definition at line 207 of file Value.cpp.
References mlir::IROperand< DerivedT, IRValueTy >::get().
Referenced by mlir::Operation::getOperand(), and mlir::getUsedValuesDefinedAbove().
getOperandNumber()
unsigned OpOperand::getOperandNumber ()
Return which operand this is in the operand list of the User.
Return which operand this is in the operand list.
Definition at line 217 of file Value.cpp.
Referenced by isUseSpeciallyKnownDead().
getUseList()
IRObjectWithUseList< OpOperand > * OpOperand::getUseList (Value value) static
Provide the use list that is attached to the given value.
Definition at line 202 of file Value.cpp.
References mlir::Value::getUseList().
set()
void OpOperand::set (Value value)
Set the operand to the given value.
Definition at line 212 of file Value.cpp.
References mlir::IROperand< DerivedT, IRValueTy >::set().
Referenced by mlir::Operation::setOperand().
The documentation for this class was generated from the following files:
include/mlir/IR/UseDefLists.h
lib/IR/Value.cpp