MLIR: mlir::TypeAttr Class Reference
mlir::TypeAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = Type
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
Type getValue () const
Static Public Member Functions
static TypeAttr get (Type value)
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 520 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::TypeAttr::ValueType = Type
Definition at line 524 of file Attributes.h.
Member Function Documentation
get()
TypeAttr TypeAttr::get (Type value) static
Definition at line 349 of file Attributes.cpp.
References mlir::Type::getContext(), and mlir::StandardAttributes::Type.
Referenced by mlir::FuncOp::build(), extractSymbolReference(), getLinkageAttrName(), isFnEntryBlock(), mlir::impl::parseFunctionLikeOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseLLVMFuncOp(), parseShuffleVectorOp(), printGPUFuncOp(), mlir::FuncOp::setType(), and verify().
getValue()
Type TypeAttr::getValue () const
Definition at line 353 of file Attributes.cpp.
kindof()
static bool mlir::TypeAttr::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 531 of file Attributes.h.
References mlir::StandardAttributes::Type.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp