MLIR: mlir::IntegerSetAttr Class Reference
mlir::IntegerSetAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = IntegerSet
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
IntegerSet getValue () const
Static Public Member Functions
static IntegerSetAttr get (IntegerSet value)
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 368 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::IntegerSetAttr::ValueType = IntegerSet
Definition at line 373 of file Attributes.h.
Member Function Documentation
get()
IntegerSetAttr IntegerSetAttr::get (IntegerSet value) static
Definition at line 288 of file Attributes.cpp.
References mlir::IntegerSet::getConstraint(), mlir::AffineExpr::getContext(), and mlir::StandardAttributes::IntegerSet.
Referenced by extractSymbolReference(), and print().
getValue()
IntegerSet IntegerSetAttr::getValue () const
Definition at line 293 of file Attributes.cpp.
Referenced by parseAffineIfOp().
kindof()
static bool mlir::IntegerSetAttr::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 380 of file Attributes.h.
References mlir::StandardAttributes::IntegerSet.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp