MLIR: mlir::FloatType Class Reference
mlir::FloatType Class Reference
#include "mlir/IR/StandardTypes.h"
Public Member Functions
unsigned getWidth ()
Return the bitwidth of this float type.
const llvm::fltSemantics & getFloatSemantics ()
Return the floating semantics of this float type.
Static Public Member Functions
static FloatType get (StandardTypes::Kind kind, MLIRContext *context)
static FloatType getBF16 (MLIRContext *ctx)
static FloatType getF16 (MLIRContext *ctx)
static FloatType getF32 (MLIRContext *ctx)
static FloatType getF64 (MLIRContext *ctx)
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 113 of file StandardTypes.h.
Member Function Documentation
get()
FloatType FloatType::get (StandardTypes::Kind kind, MLIRContext * context) static
Definition at line 469 of file MLIRContext.cpp.
References mlir::StandardTypes::BF16, mlir::MLIRContextImpl::bf16Ty, mlir::StandardTypes::F16, mlir::MLIRContextImpl::f16Ty, mlir::StandardTypes::F32, mlir::MLIRContextImpl::f32Ty, mlir::StandardTypes::F64, mlir::MLIRContextImpl::f64Ty, and mlir::MLIRContext::getImpl().
getBF16()
static FloatType mlir::FloatType::getBF16 (MLIRContext * ctx) inline static
Definition at line 120 of file StandardTypes.h.
References mlir::StandardTypes::BF16.
Referenced by mlir::Builder::getBF16Type().
getF16()
static FloatType mlir::FloatType::getF16 (MLIRContext * ctx) inline static
Definition at line 123 of file StandardTypes.h.
References mlir::StandardTypes::F16.
Referenced by mlir::Builder::getF16Type().
getF32()
static FloatType mlir::FloatType::getF32 (MLIRContext * ctx) inline static
Definition at line 126 of file StandardTypes.h.
References mlir::StandardTypes::F32.
Referenced by diag(), mlir::Builder::getF32Type(), and makeFloatAttr().
getF64()
static FloatType mlir::FloatType::getF64 (MLIRContext * ctx) inline static
Definition at line 129 of file StandardTypes.h.
References mlir::StandardTypes::F64.
Referenced by diag(), and mlir::Builder::getF64Type().
getFloatSemantics()
const llvm::fltSemantics & FloatType::getFloatSemantics ()
Return the floating semantics of this float type.
Returns the floating semantics for the given type.
Definition at line 86 of file StandardTypes.cpp.
Referenced by buildHexadecimalFloatLiteral(), mlir::fxpmath::detail::convertFloatToType(), mlir::detail::FloatAttributeStorage::getKey(), and mlir::FloatAttr::verifyConstructionInvariants().
getWidth()
unsigned FloatType::getWidth ()
Return the bitwidth of this float type.
Definition at line 71 of file StandardTypes.cpp.
References mlir::StandardTypes::BF16, mlir::StandardTypes::F16, mlir::StandardTypes::F32, and mlir::StandardTypes::F64.
Referenced by buildHexadecimalFloatLiteral().
kindof()
static bool mlir::FloatType::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 134 of file StandardTypes.h.
References mlir::StandardTypes::FIRST_FLOATING_POINT_TYPE, and mlir::StandardTypes::LAST_FLOATING_POINT_TYPE.
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/MLIRContext.cpp
lib/IR/StandardTypes.cpp