MLIR: mlir::ValueRange Class Reference
mlir::ValueRange Class Reference final
This class provides an abstraction over the different types of ranges over Values.
#include "mlir/IR/OperationSupport.h"
Public Types
using type_iterator = ValueTypeIterator< iterator >
Returns the types of the values within this range.
Public Types inherited from mlir::detail::indexed_accessor_range_base< ValueRange, detail::ValueRangeOwner, Value, Value, Value >
using RangeBaseT = indexed_accessor_range_base< ValueRange, detail::ValueRangeOwner, Value, Value, Value >
Public Member Functions
template<typename Arg , typename = typename std::enable_if_t< std::is_constructible<ArrayRef<Value>, Arg>::value && !std::is_convertible<Arg, Value>::value>>
ValueRange (Arg &&arg)
ValueRange (const Value &value)
ValueRange (const std::initializer_list< Value > &values)
ValueRange (iterator_range< OperandRange::iterator > values)
ValueRange (iterator_range< ResultRange::iterator > values)
ValueRange (ArrayRef< Value > values=llvm::None)
ValueRange (OperandRange values)
ValueRange (ResultRange values)
iterator_range< type_iterator > getTypes () const
Public Member Functions inherited from mlir::detail::indexed_accessor_range_base< ValueRange, detail::ValueRangeOwner, Value, Value, Value >
indexed_accessor_range_base (iterator begin, iterator end)
indexed_accessor_range_base (const iterator_range< iterator > &range)
indexed_accessor_range_base (detail::ValueRangeOwner base, ptrdiff_t count)
iterator begin () const
iterator end () const
Value operator[] (unsigned index) const
size_t size () const
Return the size of this range.
bool empty () const
Return if the range is empty.
ValueRange slice (size_t n, size_t m) const
Drop the first N elements, and keep M elements.
ValueRange drop_front (size_t n=1) const
Drop the first n elements.
ValueRange drop_back (size_t n=1) const
Drop the last n elements.
ValueRange take_front (size_t n=1) const
Take the first n elements.
operator SmallVector< SVT, N > () const
Allow conversion to SmallVector if necessary.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::indexed_accessor_range_base< ValueRange, detail::ValueRangeOwner, Value, Value, Value >
indexed_accessor_range_base (const indexed_accessor_range_base &)=default
indexed_accessor_range_base (indexed_accessor_range_base &&)=default
indexed_accessor_range_base & operator= (const indexed_accessor_range_base &)=default
Protected Attributes inherited from mlir::detail::indexed_accessor_range_base< ValueRange, detail::ValueRangeOwner, Value, Value, Value >
detail::ValueRangeOwner base
The base that owns the provided range of values.
ptrdiff_t count
The size from the owning range.
Detailed Description
This class provides an abstraction over the different types of ranges over Values.
In many cases, this prevents the need to explicitly materialize a SmallVector/std::vector. This class should be used in places that are not suitable for a more derived type (e.g. ArrayRef) or a template range parameter.
Definition at line 641 of file OperationSupport.h.
Member Typedef Documentation
type_iterator
using mlir::ValueRange::type_iterator = ValueTypeIterator<iterator>
Returns the types of the values within this range.
Definition at line 664 of file OperationSupport.h.
Constructor & Destructor Documentation
ValueRange() [1/8]
template<typename Arg , typename = typename std::enable_if_t< std::is_constructible<ArrayRef<Value>, Arg>::value && !std::is_convertible<Arg, Value>::value>> mlir::ValueRange::ValueRange (Arg && arg) inline
Definition at line 651 of file OperationSupport.h.
ValueRange() [2/8]
mlir::ValueRange::ValueRange (const Value & value) inline
Definition at line 652 of file OperationSupport.h.
ValueRange() [3/8]
mlir::ValueRange::ValueRange (const std::initializer_list< Value > & values) inline
Definition at line 653 of file OperationSupport.h.
ValueRange() [4/8]
mlir::ValueRange::ValueRange (iterator_range< OperandRange::iterator > values) inline
Definition at line 655 of file OperationSupport.h.
ValueRange() [5/8]
mlir::ValueRange::ValueRange (iterator_range< ResultRange::iterator > values) inline
Definition at line 657 of file OperationSupport.h.
References mlir::StandardTypes::None.
ValueRange() [6/8]
ValueRange::ValueRange (ArrayRef< Value > values = llvm::None)
Definition at line 167 of file OperationSupport.cpp.
ValueRange() [7/8]
ValueRange::ValueRange (OperandRange values)
Definition at line 169 of file OperationSupport.cpp.
ValueRange() [8/8]
ValueRange::ValueRange (ResultRange values)
Definition at line 171 of file OperationSupport.cpp.
References mlir::indexed_accessor_range< DerivedT, BaseT, T, PointerT, ReferenceT >::getBase(), mlir::Operation::getResult(), mlir::indexed_accessor_range< DerivedT, BaseT, T, PointerT, ReferenceT >::getStartIndex(), mlir::detail::ValueRangeOwner::ptr, and mlir::detail::ValueRangeOwner::startIndex.
Member Function Documentation
getTypes()
iterator_range<type_iterator> mlir::ValueRange::getTypes () const inline
Definition at line 665 of file OperationSupport.h.
Referenced by parseShuffleOp().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/OperationSupport.cpp