MLIR: mlir::OpaqueElementsAttr Class Reference
mlir::OpaqueElementsAttr Class Reference
An opaque attribute that represents a reference to a vector or tensor constant with opaque content.
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = StringRef
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
StringRef getValue () const
Attribute getValue (ArrayRef< uint64_t > index) const
Return the value at the given index.
bool decode (ElementsAttr &result)
Decodes the attribute value using dialect-specific decoding hook.
Dialect * getDialect () const
Returns dialect associated with this opaque constant.
Static Public Member Functions
static OpaqueElementsAttr get (Dialect *dialect, ShapedType type, StringRef bytes)
static bool kindof (unsigned kind)
Method for support type inquiry through isa, cast and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
An opaque attribute that represents a reference to a vector or tensor constant with opaque content.
This representation is for tensor constants which the compiler may not need to interpret. This attribute is always associated with a particular dialect, which provides a method to convert tensor representation to a non-opaque format.
Definition at line 1060 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::OpaqueElementsAttr::ValueType = StringRef
Definition at line 1065 of file Attributes.h.
Member Function Documentation
decode()
bool OpaqueElementsAttr::decode (ElementsAttr & result)
Decodes the attribute value using dialect-specific decoding hook.
Returns false if decoding is successful. If not, returns true and leaves 'result' argument unspecified.
Definition at line 934 of file Attributes.cpp.
References mlir::AttributeStorage::getDialect().
get()
OpaqueElementsAttr OpaqueElementsAttr::get (Dialect * dialect, ShapedType type, StringRef bytes) static
Definition at line 913 of file Attributes.cpp.
References mlir::Type::getContext(), mlir::ShapedType::getElementType(), mlir::TensorType::isValidElementType(), and mlir::StandardAttributes::OpaqueElements.
Referenced by buildHexadecimalFloatLiteral().
getDialect()
Dialect * OpaqueElementsAttr::getDialect () const
Returns dialect associated with this opaque constant.
Definition at line 932 of file Attributes.cpp.
getValue() [1/2]
StringRef OpaqueElementsAttr::getValue () const
Definition at line 921 of file Attributes.cpp.
getValue() [2/2]
Attribute OpaqueElementsAttr::getValue (ArrayRef< uint64_t > index) const
Return the value at the given index.
The 'index' is expected to refer to a valid element.
If index does not refer to a valid element, then a null attribute is returned.
Definition at line 925 of file Attributes.cpp.
References mlir::Dialect::extractElementHook, and mlir::AttributeStorage::getDialect().
kindof()
static bool mlir::OpaqueElementsAttr::kindof (unsigned kind) inline static
Method for support type inquiry through isa, cast and dyn_cast.
Definition at line 1085 of file Attributes.h.
References mlir::StandardAttributes::OpaqueElements.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp