MLIR: mlir::FloatAttr Class Reference
mlir::FloatAttr Class Reference
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = APFloat
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
APFloat getValue () const
double getValueAsDouble () const
This function is used to convert the value to a double, even if it loses precision.
Static Public Member Functions
static FloatAttr get (Type type, double value)
Return a float attribute for the specified value in the specified type.
static FloatAttr getChecked (Type type, double value, Location loc)
static FloatAttr get (Type type, const APFloat &value)
Return a float attribute for the specified value in the specified type.
static FloatAttr getChecked (Type type, const APFloat &value, Location loc)
static double getValueAsDouble (APFloat val)
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
static LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *ctx, Type type, double value)
Verify the construction invariants for a double value.
static LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *ctx, Type type, const APFloat &value)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 303 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::FloatAttr::ValueType = APFloat
Definition at line 307 of file Attributes.h.
Member Function Documentation
get() [1/2]
FloatAttr FloatAttr::get (Type type, double value) static
Return a float attribute for the specified value in the specified type.
These methods should only be used for simple constant values, e.g 1.0/2.0, that are known-valid both as host double and the 'type' format.
Definition at line 175 of file Attributes.cpp.
References mlir::StandardAttributes::Float, and mlir::Type::getContext().
Referenced by mlir::fxpmath::detail::broadcastScalarConstFloatValue(), buildHexadecimalFloatLiteral(), extractSymbolReference(), mlir::Builder::getF16FloatAttr(), mlir::Builder::getF32FloatAttr(), mlir::Builder::getF64FloatAttr(), mlir::Builder::getFloatAttr(), mlir::SparseElementsAttr::getValue(), makeFloatAttr(), and mlir::DenseElementsAttr::AttributeElementIterator::operator*().
get() [2/2]
FloatAttr FloatAttr::get (Type type, const APFloat & value) static
Return a float attribute for the specified value in the specified type.
Definition at line 184 of file Attributes.cpp.
References mlir::StandardAttributes::Float, and mlir::Type::getContext().
getChecked() [1/2]
FloatAttr FloatAttr::getChecked (Type type, double value, Location loc) static
Definition at line 179 of file Attributes.cpp.
References mlir::StandardAttributes::Float, and mlir::Type::getContext().
getChecked() [2/2]
FloatAttr FloatAttr::getChecked (Type type, const APFloat & value, Location loc) static
Definition at line 188 of file Attributes.cpp.
References mlir::StandardAttributes::Float, and mlir::Type::getContext().
getValue()
APFloat FloatAttr::getValue () const
Definition at line 193 of file Attributes.cpp.
Referenced by applyCmpPredicate(), convertPrimitiveValueAttr(), and getLastStructuredControlFlowOpMergeBlock().
getValueAsDouble() [1/2]
double FloatAttr::getValueAsDouble () const
This function is used to convert the value to a double, even if it loses precision.
Definition at line 195 of file Attributes.cpp.
getValueAsDouble() [2/2]
double FloatAttr::getValueAsDouble (APFloat val) static
Definition at line 198 of file Attributes.cpp.
kindof()
static bool mlir::FloatAttr::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 327 of file Attributes.h.
References mlir::StandardAttributes::Float.
verifyConstructionInvariants() [1/2]
LogicalResult FloatAttr::verifyConstructionInvariants (Optional< Location > loc, MLIRContext * ctx, Type type, double value) static
Verify the construction invariants for a double value.
Definition at line 215 of file Attributes.cpp.
References verifyFloatTypeInvariants().
verifyConstructionInvariants() [2/2]
LogicalResult FloatAttr::verifyConstructionInvariants (Optional< Location > loc, MLIRContext * ctx, Type type, const APFloat & value) static
Definition at line 221 of file Attributes.cpp.
References mlir::Type::cast(), mlir::emitOptionalError(), mlir::failed(), mlir::failure(), mlir::FloatType::getFloatSemantics(), mlir::success(), and verifyFloatTypeInvariants().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp