MLIR: mlir::gpu::GPUDialect Class Reference
mlir::gpu::GPUDialect Class Reference
The dialect containing GPU kernel launching operations and related facilities.
#include "mlir/Dialect/GPU/GPUDialect.h"
Public Member Functions
GPUDialect (MLIRContext *context)
Create the dialect in the given context.
LogicalResult verifyOperationAttribute (Operation *op, NamedAttribute attr) override
Verify an attribute from this dialect on the given operation.
Public Member Functions inherited from mlir::Dialect
virtual ~Dialect ()
MLIRContext * getContext () const
StringRef getNamespace () const
bool allowsUnknownOperations () const
Returns true if this dialect allows for unregistered operations, i.e.
bool allowsUnknownTypes () const
Return true if this dialect allows for unregistered types, i.e., types prefixed with the dialect namespace but not registered with addType.
virtual Operation * materializeConstant (OpBuilder &builder, Attribute value, Type type, Location loc)
Registered hook to materialize a single constant operation from a given attribute value with the desired resultant type.
virtual Attribute parseAttribute (DialectAsmParser &parser, Type type) const
Parse an attribute registered to this dialect.
virtual void printAttribute (Attribute, DialectAsmPrinter &) const
Print an attribute registered to this dialect.
virtual Type parseType (DialectAsmParser &parser) const
Parse a type registered to this dialect.
virtual void printType (Type, DialectAsmPrinter &) const
Print a type registered to this dialect.
virtual LogicalResult verifyRegionArgAttribute (Operation *, unsigned regionIndex, unsigned argIndex, NamedAttribute)
Verify an attribute from this dialect on the argument at 'argIndex' for the region at 'regionIndex' on the given operation.
virtual LogicalResult verifyRegionResultAttribute (Operation *, unsigned regionIndex, unsigned resultIndex, NamedAttribute)
Verify an attribute from this dialect on the result at 'resultIndex' for the region at 'regionIndex' on the given operation.
const DialectInterface * getRegisteredInterface (ClassID *interfaceID)
Lookup an interface for the given ID if one is registered, otherwise nullptr.
template<typename InterfaceT >
const InterfaceT * getRegisteredInterface ()
Static Public Member Functions
static StringRef getDialectNamespace ()
Get dialect namespace.
static StringRef getContainerModuleAttrName ()
Get the name of the attribute used to annotate the modules that contain kernel modules.
static StringRef getDialectName ()
Get the canonical string name of the dialect.
static StringRef getKernelFuncAttrName ()
Get the name of the attribute used to annotate external kernel functions.
static StringRef getKernelModuleAttrName ()
Get the name of the attribute used to annotate kernel modules.
static bool isKernel (Operation *op)
Returns whether the given function is a kernel function, i.e., has the 'gpu.kernel' attribute.
static unsigned getNumWorkgroupDimensions ()
Returns the number of workgroup (thread, block) dimensions supported in the GPU dialect.
static unsigned getWorkgroupAddressSpace ()
Returns the numeric value used to identify the workgroup memory address space.
static unsigned getPrivateAddressSpace ()
Returns the numeric value used to identify the private memory address space.
Static Public Member Functions inherited from mlir::Dialect
static bool isValidNamespace (StringRef str)
Utility function that returns if the given string is a valid dialect namespace.
Additional Inherited Members
Public Attributes inherited from mlir::Dialect
DialectConstantFoldHook constantFoldHook
Registered fallback constant fold hook for the dialect.
DialectConstantDecodeHook decodeHook
Registered hook to decode opaque constants associated with this dialect.
DialectExtractElementHook extractElementHook
Registered hook to extract an element from an opaque constant associated with this dialect.
Protected Member Functions inherited from mlir::Dialect
Dialect (StringRef name, MLIRContext *context)
The constructor takes a unique namespace for this dialect as well as the context to bind to.
template<typename... Args>
void addOperations ()
This method is used by derived classes to add their operations to the set.
void addOperation (AbstractOperation opInfo)
template<typename... Args>
void addTypes ()
This method is used by derived classes to add their types to the set.
template<typename... Args>
void addAttributes ()
This method is used by derived classes to add their attributes to the set.
void allowUnknownOperations (bool allow=true)
Enable support for unregistered operations.
void allowUnknownTypes (bool allow=true)
Enable support for unregistered types.
void addInterface (std::unique_ptr< DialectInterface > interface)
Register a dialect interface with this dialect instance.
template<typename T , typename T2 , typename... Tys>
void addInterfaces ()
Register a set of dialect interfaces with this dialect instance.
template<typename T >
void addInterfaces ()
Detailed Description
The dialect containing GPU kernel launching operations and related facilities.
Definition at line 30 of file GPUDialect.h.
Constructor & Destructor Documentation
GPUDialect()
GPUDialect::GPUDialect (MLIRContext * context) explicit
Create the dialect in the given context.
Definition at line 38 of file GPUDialect.cpp.
References mlir::Dialect::addOperations().
Member Function Documentation
getContainerModuleAttrName()
static StringRef mlir::gpu::GPUDialect::getContainerModuleAttrName () inline static
Get the name of the attribute used to annotate the modules that contain kernel modules.
Definition at line 39 of file GPUDialect.h.
References getDialectName().
Referenced by convertToLaunchFuncOp(), verify(), and verifyOperationAttribute().
getDialectName()
StringRef GPUDialect::getDialectName () static
Get the canonical string name of the dialect.
Definition at line 31 of file GPUDialect.cpp.
Referenced by getContainerModuleAttrName().
getDialectNamespace()
static StringRef mlir::gpu::GPUDialect::getDialectNamespace () inline static
Get dialect namespace.
Definition at line 35 of file GPUDialect.h.
getKernelFuncAttrName()
static StringRef mlir::gpu::GPUDialect::getKernelFuncAttrName () inline static
Get the name of the attribute used to annotate external kernel functions.
Definition at line 47 of file GPUDialect.h.
Referenced by isKernel(), lowerAsEntryFunction(), outlineKernelFunc(), parseGPUFuncOp(), printGPUFuncOp(), mlir::translateModuleToROCDLIR(), and verifyOperationAttribute().
getKernelModuleAttrName()
static StringRef mlir::gpu::GPUDialect::getKernelModuleAttrName () inline static
Get the name of the attribute used to annotate kernel modules.
Definition at line 50 of file GPUDialect.h.
References isKernel().
Referenced by parseLaunchOp().
getNumWorkgroupDimensions()
static unsigned mlir::gpu::GPUDialect::getNumWorkgroupDimensions () inline static
Returns the number of workgroup (thread, block) dimensions supported in the GPU dialect.
Definition at line 59 of file GPUDialect.h.
Referenced by insertCopyLoops().
getPrivateAddressSpace()
static unsigned mlir::gpu::GPUDialect::getPrivateAddressSpace () inline static
Returns the numeric value used to identify the private memory address space.
Definition at line 67 of file GPUDialect.h.
References verifyOperationAttribute().
Referenced by verifyAttributions().
getWorkgroupAddressSpace()
static unsigned mlir::gpu::GPUDialect::getWorkgroupAddressSpace () inline static
Returns the numeric value used to identify the workgroup memory address space.
Definition at line 63 of file GPUDialect.h.
Referenced by verify(), and verifyAttributions().
isKernel()
bool GPUDialect::isKernel (Operation * op) static
Returns whether the given function is a kernel function, i.e., has the 'gpu.kernel' attribute.
Definition at line 33 of file GPUDialect.cpp.
References mlir::Operation::getAttrOfType(), and getKernelFuncAttrName().
Referenced by getKernelModuleAttrName(), lowerAsEntryFunction(), printGPUFuncOp(), and mlir::translateModuleToNVVMIR().
verifyOperationAttribute()
LogicalResult GPUDialect::verifyOperationAttribute (Operation * , NamedAttribute) override virtual
Verify an attribute from this dialect on the given operation.
Returns failure if the verification failed, success otherwise.
Reimplemented from mlir::Dialect.
Definition at line 46 of file GPUDialect.cpp.
References mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::failure(), mlir::Operation::getAttrOfType(), getContainerModuleAttrName(), getKernelFuncAttrName(), mlir::ModuleOp::getOperationName(), and mlir::success().
Referenced by getPrivateAddressSpace().
The documentation for this class was generated from the following files:
include/mlir/Dialect/GPU/GPUDialect.h
lib/Dialect/GPU/IR/GPUDialect.cpp