MLIR: mlir::tblgen::OpTrait Class Reference
mlir::tblgen::OpTrait Class Reference
#include "mlir/TableGen/OpTrait.h"
Public Types
enum Kind { Kind::Native, Kind::Pred, Kind::Internal, Kind::Interface }
Public Member Functions
OpTrait (Kind kind, const llvm::Record *def)
Kind getKind () const
Static Public Member Functions
static OpTrait create (const llvm::Init *init)
Protected Attributes
const llvm::Record * def
Kind kind
Detailed Description
Definition at line 31 of file OpTrait.h.
Member Enumeration Documentation
Kind
enum mlir::tblgen::OpTrait::Kind strong
Enumerator
Native
Pred
Internal
Interface
Definition at line 34 of file OpTrait.h.
Constructor & Destructor Documentation
OpTrait()
mlir::tblgen::OpTrait::OpTrait (Kind kind, const llvm::Record * def) explicit
Member Function Documentation
create()
static OpTrait mlir::tblgen::OpTrait::create (const llvm::Init * init) static
Referenced by mlir::tblgen::Operator::getArg().
getKind()
Kind mlir::tblgen::OpTrait::getKind () const inline
Definition at line 50 of file OpTrait.h.
Referenced by mlir::tblgen::NativeOpTrait::classof(), mlir::tblgen::PredOpTrait::classof(), mlir::tblgen::InternalOpTrait::classof(), and mlir::tblgen::InterfaceOpTrait::classof().
Member Data Documentation
def
const llvm::Record* mlir::tblgen::OpTrait::def protected
Definition at line 54 of file OpTrait.h.
kind
Kind mlir::tblgen::OpTrait::kind protected
Definition at line 55 of file OpTrait.h.
The documentation for this class was generated from the following file:
include/mlir/TableGen/OpTrait.h