MLIR: mlir::SDBMConstantExpr Class Reference
mlir::SDBMConstantExpr Class Reference
SDBM constant expression, wraps a 64-bit integer.
#include "mlir/Dialect/SDBM/SDBMExpr.h"
Public Types
using ImplType = detail::SDBMConstantExprStorage
Public Types inherited from mlir::SDBMExpr
using ImplType = detail::SDBMExprStorage
Public Member Functions
int64_t getValue () const
Public Member Functions inherited from mlir::SDBMExpr
SDBMExpr ()
SDBMExpr (ImplType *expr)
SDBMExpr (const SDBMExpr &)=default
SDBM expressions are thin wrappers around a unique'ed immutable pointer, which makes them trivially assignable and trivially copyable.
SDBMExpr & operator= (const SDBMExpr &)=default
bool operator== (const SDBMExpr &other) const
SDBM expressions can be compared straight-forwardly.
bool operator!= (const SDBMExpr &other) const
operator bool () const
SDBM expressions are convertible to bool: null expressions are converted to false, non-null expressions are converted to true.
bool operator! () const
SDBMExpr operator- ()
Negate the given SDBM expression.
void print (raw_ostream &os) const
Prints the SDBM expression.
void dump () const
template<typename U >
bool isa () const
LLVM-style casts.
template<typename U >
U dyn_cast () const
template<typename U >
U cast () const
::llvm::hash_code hash_value () const
Support for LLVM hashing.
SDBMExprKind getKind () const
Returns the kind of the SDBM expression.
MLIRContext * getContext () const
Returns the MLIR context in which this expression lives.
SDBMDialect * getDialect () const
Returns the SDBM dialect instance.
AffineExpr getAsAffineExpr () const
Convert the SDBM expression into an Affine expression.
Static Public Member Functions
static SDBMConstantExpr get (SDBMDialect *dialect, int64_t value)
Obtain or create a constant expression unique'ed in the given dialect (which belongs to a context).
static bool isClassFor (const SDBMExpr &expr)
Static Public Member Functions inherited from mlir::SDBMExpr
static Optional< SDBMExpr > tryConvertAffineExpr (AffineExpr affine)
Try constructing an SDBM expression from the given affine expression.
Additional Inherited Members
Protected Attributes inherited from mlir::SDBMExpr
ImplType * impl
Detailed Description
SDBM constant expression, wraps a 64-bit integer.
Definition at line 155 of file SDBMExpr.h.
Member Typedef Documentation
ImplType
using mlir::SDBMConstantExpr::ImplType = detail::SDBMConstantExprStorage
Definition at line 157 of file SDBMExpr.h.
Member Function Documentation
get()
SDBMConstantExpr SDBMConstantExpr::get (SDBMDialect * dialect, int64_t value) static
Obtain or create a constant expression unique'ed in the given dialect (which belongs to a context).
Definition at line 634 of file SDBMExpr.cpp.
References mlir::Constant, mlir::StorageUniquer::get(), and mlir::SDBMDialect::getUniquer().
Referenced by addConstant(), addConstantAndSink(), buildDiffExpr(), mlir::SDBMExpr::dump(), mlir::SDBM::get(), mlir::SDBMSumExpr::get(), mlir::SDBM::getSDBMExpressions(), mlir::ops_assertions::operator+(), mlir::ops_assertions::operator-(), mlir::ops_assertions::stripe(), and mlir::SDBMExpr::tryConvertAffineExpr().
getValue()
int64_t SDBMConstantExpr::getValue () const
Definition at line 646 of file SDBMExpr.cpp.
References mlir::SDBMExpr::impl.
Referenced by collectSDBMBuildInfo(), mlir::SDBMExpr::dump(), mlir::SDBMSumExpr::get(), mlir::SDBMStripeExpr::get(), mlir::SDBMExpr::getAsAffineExpr(), mlir::ops_assertions::operator+(), mlir::ops_assertions::operator-(), and mlir::SDBMExpr::print().
isClassFor()
static bool mlir::SDBMConstantExpr::isClassFor (const SDBMExpr & expr) inline static
Definition at line 165 of file SDBMExpr.h.
References mlir::Constant, and mlir::SDBMExpr::getKind().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SDBM/SDBMExpr.h
lib/Dialect/SDBM/SDBMExpr.cpp