MLIR: mlir::PatternRewriter Class Reference
mlir::PatternRewriter Class Reference abstract
This class coordinates the application of a pattern to the current function, providing a way to create operations and keep track of what gets deleted.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
template<typename OpTy , typename... Args>
OpTy create (Location location, Args... args)
Create operation of specific op type at the current insertion point without verifying to see if it is valid.
template<typename OpTy , typename... Args>
OpTy createChecked (Location location, Args... args)
Creates an operation of specific op type at the current insertion point.
virtual Operation * insert (Operation *op)=0
This is implemented to insert the specified operation and serves as a notification hook for rewriters that want to know about new operations.
virtual void inlineRegionBefore (Region &region, Region &parent, Region::iterator before)
Move the blocks that belong to "region" before the given position in another region "parent".
void inlineRegionBefore (Region &region, Block *before)
virtual void cloneRegionBefore (Region &region, Region &parent, Region::iterator before, BlockAndValueMapping &mapping)
Clone the blocks that belong to "region" before the given position in another region "parent".
void cloneRegionBefore (Region &region, Region &parent, Region::iterator before)
void cloneRegionBefore (Region &region, Block *before)
virtual void replaceOp (Operation *op, ValueRange newValues)
This method performs the final replacement for a pattern, where the results of the operation are updated to use the specified list of SSA values.
template<typename OpTy , typename... Args>
void replaceOpWithNewOp (Operation *op, Args &&... args)
Replaces the result op with a new op that is created without verification.
virtual void eraseOp (Operation *op)
This method erases an operation that is known to have no uses.
virtual void mergeBlocks (Block *source, Block *dest, ValueRange argValues=llvm::None)
Merge the operations of block 'source' into the end of block 'dest'.
virtual Block * splitBlock (Block *block, Block::iterator before)
Split the operations starting at "before" (inclusive) out of the given block into a new block, and return it.
virtual void startRootUpdate (Operation *op)
This method is used to notify the rewriter that an in-place operation modification is about to happen.
virtual void finalizeRootUpdate (Operation *op)
This method is used to signal the end of a root update on the given operation.
virtual void cancelRootUpdate (Operation *op)
This method cancels a pending root update.
template<typename CallableT >
void updateRootInPlace (Operation *root, CallableT &&callable)
This method is a utility wrapper around a root update of an operation.
Public Member Functions inherited from mlir::OpBuilder
OpBuilder (MLIRContext *ctx)
Create a builder with the given context.
OpBuilder (Region *region)
Create a builder and set the insertion point to the start of the region.
OpBuilder (Region &region)
virtual ~OpBuilder ()
OpBuilder (Operation *op)
Create a builder and set insertion point to the given operation, which will cause subsequent insertions to go right before it.
OpBuilder (Block *block)
OpBuilder (Block *block, Block::iterator insertPoint)
void clearInsertionPoint ()
Reset the insertion point to no location.
InsertPoint saveInsertionPoint () const
Return a saved insertion point.
void restoreInsertionPoint (InsertPoint ip)
Restore the insert point to a previously saved point.
void setInsertionPoint (Block *block, Block::iterator insertPoint)
Set the insertion point to the specified location.
void setInsertionPoint (Operation *op)
Sets the insertion point to the specified operation, which will cause subsequent insertions to go right before it.
void setInsertionPointAfter (Operation *op)
Sets the insertion point to the node after the specified operation, which will cause subsequent insertions to go right after it.
void setInsertionPointToStart (Block *block)
Sets the insertion point to the start of the specified block.
void setInsertionPointToEnd (Block *block)
Sets the insertion point to the end of the specified block.
Block * getInsertionBlock () const
Return the block the current insertion point belongs to.
Block::iterator getInsertionPoint () const
Returns the current insertion point of the builder.
Block * createBlock (Region *parent, Region::iterator insertPt={})
Add new block and set the insertion point to the end of it.
Block * createBlock (Block *insertBefore)
Add new block and set the insertion point to the end of it.
Block * getBlock () const
Returns the current block of the builder.
Operation * createOperation (const OperationState &state)
Creates an operation given the fields represented as an OperationState.
template<typename OpTy , typename... Args>
OpTy create (Location location, Args &&... args)
Create an operation of specific op type at the current insertion point.
template<typename OpTy , typename... Args>
void createOrFold (SmallVectorImpl< Value > &results, Location location, Args &&... args)
Create an operation of specific op type at the current insertion point, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::OneResult >), Value >::type createOrFold (Location location, Args &&... args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::ZeroResult >), OpTy >::type createOrFold (Location location, Args &&... args)
Overload to create or fold a zero result operation.
LogicalResult tryFold (Operation *op, SmallVectorImpl< Value > &results)
Attempts to fold the given operation and places new results within 'results'.
Operation * clone (Operation &op, BlockAndValueMapping &mapper)
Creates a deep copy of the specified operation, remapping any operands that use values outside of the operation using the map that is provided (leaving them alone if no entry is present).
Operation * clone (Operation &op)
Operation * cloneWithoutRegions (Operation &op, BlockAndValueMapping &mapper)
Creates a deep copy of this operation but keep the operation regions empty.
Operation * cloneWithoutRegions (Operation &op)
template<typename OpT >
OpT cloneWithoutRegions (OpT op)
Public Member Functions inherited from mlir::Builder
Builder (MLIRContext *context)
Builder (ModuleOp module)
MLIRContext * getContext () const
Identifier getIdentifier (StringRef str)
Location getUnknownLoc ()
Location getFileLineColLoc (Identifier filename, unsigned line, unsigned column)
Location getFusedLoc (ArrayRef< Location > locs, Attribute metadata=Attribute())
FloatType getBF16Type ()
FloatType getF16Type ()
FloatType getF32Type ()
FloatType getF64Type ()
IndexType getIndexType ()
IntegerType getI1Type ()
IntegerType getIntegerType (unsigned width)
FunctionType getFunctionType (ArrayRef< Type > inputs, ArrayRef< Type > results)
TupleType getTupleType (ArrayRef< Type > elementTypes)
NoneType getNoneType ()
template<typename Ty , typename... Args>
Ty getType (Args... args)
Get or construct an instance of the type 'ty' with provided arguments.
NamedAttribute getNamedAttr (StringRef name, Attribute val)
UnitAttr getUnitAttr ()
BoolAttr getBoolAttr (bool value)
DictionaryAttr getDictionaryAttr (ArrayRef< NamedAttribute > value)
IntegerAttr getIntegerAttr (Type type, int64_t value)
IntegerAttr getIntegerAttr (Type type, const APInt &value)
FloatAttr getFloatAttr (Type type, double value)
FloatAttr getFloatAttr (Type type, const APFloat &value)
StringAttr getStringAttr (StringRef bytes)
ArrayAttr getArrayAttr (ArrayRef< Attribute > value)
FlatSymbolRefAttr getSymbolRefAttr (Operation *value)
FlatSymbolRefAttr getSymbolRefAttr (StringRef value)
SymbolRefAttr getSymbolRefAttr (StringRef value, ArrayRef< FlatSymbolRefAttr > nestedReferences)
Attribute getZeroAttr (Type type)
FloatAttr getF16FloatAttr (float value)
FloatAttr getF32FloatAttr (float value)
FloatAttr getF64FloatAttr (double value)
IntegerAttr getI8IntegerAttr (int8_t value)
IntegerAttr getI16IntegerAttr (int16_t value)
IntegerAttr getI32IntegerAttr (int32_t value)
IntegerAttr getI64IntegerAttr (int64_t value)
DenseIntElementsAttr getI32VectorAttr (ArrayRef< int32_t > values)
ArrayAttr getAffineMapArrayAttr (ArrayRef< AffineMap > values)
ArrayAttr getI32ArrayAttr (ArrayRef< int32_t > values)
ArrayAttr getI64ArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getIndexArrayAttr (ArrayRef< int64_t > values)
ArrayAttr getF32ArrayAttr (ArrayRef< float > values)
ArrayAttr getF64ArrayAttr (ArrayRef< double > values)
ArrayAttr getStrArrayAttr (ArrayRef< StringRef > values)
AffineExpr getAffineDimExpr (unsigned position)
AffineExpr getAffineSymbolExpr (unsigned position)
AffineExpr getAffineConstantExpr (int64_t constant)
AffineMap getEmptyAffineMap ()
Returns a zero result affine map with no dimensions or symbols: () -> ().
AffineMap getConstantAffineMap (int64_t val)
Returns a single constant result affine map with 0 dimensions and 0 symbols.
AffineMap getDimIdentityMap ()
AffineMap getMultiDimIdentityMap (unsigned rank)
AffineMap getSymbolIdentityMap ()
AffineMap getSingleDimShiftAffineMap (int64_t shift)
Returns a map that shifts its (single) input dimension by 'shift'.
AffineMap getShiftedAffineMap (AffineMap map, int64_t shift)
Returns an affine map that is a translation (shift) of all result expressions in 'map' by 'shift'.
Protected Member Functions
PatternRewriter (MLIRContext *ctx)
virtual ~PatternRewriter ()
virtual void notifyRootReplaced (Operation *op)
Notify the pattern rewriter that the specified operation is about to be replaced with another set of operations.
virtual void notifyOperationRemoved (Operation *op)
This is called on an operation that a pattern match is removing, right before the operation is deleted.
Additional Inherited Members
Protected Attributes inherited from mlir::Builder
MLIRContext * context
Detailed Description
This class coordinates the application of a pattern to the current function, providing a way to create operations and keep track of what gets deleted.
These class serves two purposes: 1) it is the interface that patterns interact with to make mutations to the IR they are being applied to. 2) It is a base class that clients of the PatternMatcher use when they want to apply patterns and observe their effects (e.g. to keep worklists or other data structures up to date).
Definition at line 260 of file PatternMatch.h.
Constructor & Destructor Documentation
PatternRewriter()
mlir::PatternRewriter::PatternRewriter (MLIRContext * ctx) inline explicit protected
Definition at line 373 of file PatternMatch.h.
~PatternRewriter()
PatternRewriter::~PatternRewriter () protected virtual
Definition at line 70 of file PatternMatch.cpp.
Member Function Documentation
cancelRootUpdate()
virtual void mlir::PatternRewriter::cancelRootUpdate (Operation * op) inline virtual
This method cancels a pending root update.
This can only be called on operations that were provided to a call to startRootUpdate.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 360 of file PatternMatch.h.
Referenced by parseLaunchOp().
cloneRegionBefore() [1/3]
void PatternRewriter::cloneRegionBefore (Region & region, Region & parent, Region::iterator before, BlockAndValueMapping & mapping) virtual
Clone the blocks that belong to "region" before the given position in another region "parent".
The two regions must be different. The caller is responsible for creating or updating the operation transferring flow of control to the region and passing it the correct block arguments.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 153 of file PatternMatch.cpp.
References mlir::Region::cloneInto().
Referenced by mlir::ConversionPatternRewriter::cloneRegionBefore().
cloneRegionBefore() [2/3]
void PatternRewriter::cloneRegionBefore (Region & region, Region & parent, Region::iterator before)
Definition at line 158 of file PatternMatch.cpp.
cloneRegionBefore() [3/3]
void PatternRewriter::cloneRegionBefore (Region & region, Block * before)
Definition at line 163 of file PatternMatch.cpp.
References mlir::Block::getParent().
create()
template<typename OpTy , typename... Args> OpTy mlir::PatternRewriter::create (Location location, Args... args) inline
Create operation of specific op type at the current insertion point without verifying to see if it is valid.
Definition at line 265 of file PatternMatch.h.
Referenced by mlir::LinalgTypeConverter::convertType(), emitUniformPerLayerDequantize(), extractOne(), generateTransferOpSlices(), getI64SubArray(), getLibraryCallSymbolRef(), getLocalInvocationDimSize(), getOrCreateUnrolledVectorSlice(), initUnrolledVectorState(), insertOne(), mlir::lowerAffineUpperBound(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), mlir::operator<<(), resolveSourceIndices(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), tryRewriteAffineAddEwIsomorphicSigned(), tryRewriteAffineMulEwSigned(), unrollSingleResultStructuredOp(), and verify().
createChecked()
template<typename OpTy , typename... Args> OpTy mlir::PatternRewriter::createChecked (Location location, Args... args) inline
Creates an operation of specific op type at the current insertion point.
If the result is an invalid op (the verifier hook fails), emit an error and return null.
Definition at line 278 of file PatternMatch.h.
References mlir::Operation::erase().
eraseOp()
void PatternRewriter::eraseOp (Operation * op) virtual
This method erases an operation that is known to have no uses.
The uses of the given operation must be known to be dead.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 91 of file PatternMatch.cpp.
References mlir::Operation::erase(), and mlir::IRMultiObjectWithUseList< OperandType >::use_empty().
Referenced by mlir::ConstantIndexOp::build(), canonicalizeLoopBounds(), clip(), emitLoopRanges(), generateTransferOpSlices(), mlir::lowerAffineUpperBound(), mlir::linalg::tileAndFuseLinalgOpAndSetMarker(), and verify().
finalizeRootUpdate()
virtual void mlir::PatternRewriter::finalizeRootUpdate (Operation * op) inline virtual
This method is used to signal the end of a root update on the given operation.
This can only be called on operations that were provided to a call to startRootUpdate.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 356 of file PatternMatch.h.
Referenced by parseLaunchOp().
inlineRegionBefore() [1/2]
void PatternRewriter::inlineRegionBefore (Region & region, Region & parent, Region::iterator before) virtual
Move the blocks that belong to "region" before the given position in another region "parent".
Move the blocks that belong to "region" before the given position in another region.
The two regions must be different. The caller is responsible for creating or updating the operation transferring flow of control to the region and passing it the correct block arguments.
The two regions must be different. The caller is in charge to update create the operation transferring the control flow to the region and pass it the correct block arguments.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 141 of file PatternMatch.cpp.
References mlir::Region::getBlocks().
Referenced by mlir::ConversionPatternRewriter::inlineRegionBefore(), and mlir::lowerAffineUpperBound().
inlineRegionBefore() [2/2]
void PatternRewriter::inlineRegionBefore (Region & region, Block * before)
Definition at line 145 of file PatternMatch.cpp.
References mlir::Block::getParent().
insert()
virtual Operation* mlir::PatternRewriter::insert (Operation * op) pure virtual
This is implemented to insert the specified operation and serves as a notification hook for rewriters that want to know about new operations.
Reimplemented from mlir::OpBuilder.
Implemented in mlir::ConversionPatternRewriter.
mergeBlocks()
void PatternRewriter::mergeBlocks (Block * source, Block * dest, ValueRange argValues = llvm::None) virtual
Merge the operations of block 'source' into the end of block 'dest'.
'source's predecessors must either be empty or only contain 'dest`. 'argValues' is used to replace the block arguments of 'source' after merging.
'source's predecessors must be empty or only contain 'dest`. 'argValues' is used to replace the block arguments of 'source' after merging.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 101 of file PatternMatch.cpp.
References mlir::IRObjectWithUseList< OperandType >::dropAllUses(), mlir::Block::end(), mlir::Block::erase(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Block::getOperations(), mlir::Block::getPredecessors(), and mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
Referenced by verify().
notifyOperationRemoved()
virtual void mlir::PatternRewriter::notifyOperationRemoved (Operation * op) inline protected virtual
This is called on an operation that a pattern match is removing, right before the operation is deleted.
At this point, the operation has zero uses.
Definition at line 387 of file PatternMatch.h.
notifyRootReplaced()
virtual void mlir::PatternRewriter::notifyRootReplaced (Operation * op) inline protected virtual
Notify the pattern rewriter that the specified operation is about to be replaced with another set of operations.
This is called before the uses of the operation have been changed.
Definition at line 382 of file PatternMatch.h.
replaceOp()
void PatternRewriter::replaceOp (Operation * op, ValueRange newValues) virtual
This method performs the final replacement for a pattern, where the results of the operation are updated to use the specified list of SSA values.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 77 of file PatternMatch.cpp.
References mlir::Operation::erase(), mlir::Operation::getNumResults(), mlir::Operation::replaceAllUsesWith(), and mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
Referenced by clip(), emitDequantize(), emitLoopRanges(), generateTransferOpSlices(), getI64SubArray(), mlir::lowerAffineUpperBound(), and verify().
replaceOpWithNewOp()
template<typename OpTy , typename... Args> void mlir::PatternRewriter::replaceOpWithNewOp (Operation * op, Args &&... args) inline
Replaces the result op with a new op that is created without verification.
The result values of the two ops must be the same types.
Definition at line 327 of file PatternMatch.h.
References mlir::Operation::getLoc(), and mlir::StandardTypes::None.
Referenced by applyCmpPredicate(), mlir::canonicalizeSetAndOperands(), convertLinalgType(), mlir::LinalgTypeConverter::convertType(), emitLoopRanges(), generateTransferOpSlices(), getI64SubArray(), mlir::lowerAffineUpperBound(), lowerAsEntryFunction(), mlir::operator<<(), resolveSourceIndices(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), tryRewriteAffineAddEwIsomorphicSigned(), tryRewriteAffineMulEwSigned(), and verify().
splitBlock()
Block * PatternRewriter::splitBlock (Block * block, Block::iterator before) virtual
Split the operations starting at "before" (inclusive) out of the given block into a new block, and return it.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 122 of file PatternMatch.cpp.
References mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResults(), and mlir::Block::splitBlock().
Referenced by mlir::ConversionPatternRewriter::splitBlock().
startRootUpdate()
virtual void mlir::PatternRewriter::startRootUpdate (Operation * op) inline virtual
This method is used to notify the rewriter that an in-place operation modification is about to happen.
A call to this function must be followed by a call to either finalizeRootUpdate or cancelRootUpdate. This is a minor efficiency win (it avoids creating a new operation and removing the old one) but also often allows simpler code in the client.
Reimplemented in mlir::ConversionPatternRewriter.
Definition at line 351 of file PatternMatch.h.
Referenced by parseLaunchOp().
updateRootInPlace()
template<typename CallableT > void mlir::PatternRewriter::updateRootInPlace (Operation * root, CallableT && callable) inline
This method is a utility wrapper around a root update of an operation.
It wraps calls to startRootUpdate and finalizeRootUpdate around the given callable.
Definition at line 366 of file PatternMatch.h.
Referenced by mlir::TypeConverter::convertSignatureArg(), mlir::SPIRVTypeConverter::convertType(), and lowerEntryPointABIAttr().
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp