MLIR: mlir::CallGraph Class Reference
mlir::CallGraph Class Reference
#include "mlir/Analysis/CallGraph.h"
Public Types
using iterator = NodeIterator
An iterator over the nodes of the graph.
Public Member Functions
CallGraph (Operation *op)
CallGraphNode * getOrAddNode (Region *region, CallGraphNode *parentNode)
Get or add a call graph node for the given region.
CallGraphNode * lookupNode (Region *region) const
Lookup a call graph node for the given region, or nullptr if none is registered.
CallGraphNode * getExternalNode () const
Return the callgraph node representing the indirect-external callee.
CallGraphNode * resolveCallable (CallInterfaceCallable callable, Operation *from=nullptr) const
Resolve the callable for given callee to a node in the callgraph, or the external node if a valid node was not resolved.
iterator begin () const
iterator end () const
void dump () const
Dump the graph in a human readable format.
void print (raw_ostream &os) const
Detailed Description
Definition at line 152 of file CallGraph.h.
Member Typedef Documentation
iterator
using mlir::CallGraph::iterator = NodeIterator
An iterator over the nodes of the graph.
Definition at line 198 of file CallGraph.h.
Constructor & Destructor Documentation
CallGraph()
CallGraph::CallGraph (Operation * op)
Definition at line 103 of file CallGraph.cpp.
References computeCallGraph().
Member Function Documentation
begin()
iterator mlir::CallGraph::begin () const inline
Definition at line 199 of file CallGraph.h.
Referenced by llvm::GraphTraits< const mlir::CallGraph * >::nodes_begin().
dump()
void CallGraph::dump () const
Dump the graph in a human readable format.
Definition at line 170 of file CallGraph.cpp.
References print().
end()
iterator mlir::CallGraph::end () const inline
Definition at line 200 of file CallGraph.h.
References print().
Referenced by llvm::GraphTraits< const mlir::CallGraph * >::nodes_end().
getExternalNode()
CallGraphNode* mlir::CallGraph::getExternalNode () const inline
Return the callgraph node representing the indirect-external callee.
Definition at line 186 of file CallGraph.h.
Referenced by llvm::GraphTraits< const mlir::CallGraph * >::getEntryNode(), and resolveCallable().
getOrAddNode()
CallGraphNode * CallGraph::getOrAddNode (Region * region, CallGraphNode * parentNode)
Get or add a call graph node for the given region.
parentNode corresponds to the direct node in the callgraph that contains the parent operation of region, or nullptr if there is no parent node.
Definition at line 112 of file CallGraph.cpp.
References mlir::CallGraphNode::addAbstractEdge(), mlir::CallGraphNode::addChildEdge(), and mlir::Region::getParentOp().
Referenced by computeCallGraph().
lookupNode()
CallGraphNode * CallGraph::lookupNode (Region * region) const
Lookup a call graph node for the given region, or nullptr if none is registered.
Definition at line 137 of file CallGraph.cpp.
Referenced by collectCallOps(), and resolveCallable().
print()
void CallGraph::print (raw_ostream & os) const
Definition at line 171 of file CallGraph.cpp.
References mlir::CallGraphNode::getCallableRegion(), mlir::Operation::getName(), mlir::Region::getParentOp(), mlir::Operation::getParentOp(), and mlir::CallGraphNode::isExternal().
Referenced by dump().
resolveCallable()
CallGraphNode * CallGraph::resolveCallable (CallInterfaceCallable callable, Operation * from = nullptr) const
Resolve the callable for given callee to a node in the callgraph, or the external node if a valid node was not resolved.
'from' provides an anchor for symbol table lookups, and is only required if the callable is a symbol reference.
Definition at line 144 of file CallGraph.cpp.
References getExternalNode(), mlir::Operation::getNumRegions(), mlir::SymbolTable::lookupNearestSymbolFrom(), and lookupNode().
Referenced by collectCallOps(), and computeCallGraph().
The documentation for this class was generated from the following files:
include/mlir/Analysis/CallGraph.h
lib/Analysis/CallGraph.cpp