MLIR: mlir::ResultRange Class Reference
mlir::ResultRange Class Reference final
This class implements the result iterators for the Operation class.
#include "mlir/IR/OperationSupport.h"
Public Types
using type_iterator = ArrayRef< Type >::iterator
Returns the types of the values within this range.
Public Types inherited from mlir::detail::indexed_accessor_range_base< ResultRange, std::pair< Operation *, ptrdiff_t >, OpResult, OpResult, OpResult >
using RangeBaseT = indexed_accessor_range_base< ResultRange, std::pair< Operation *, ptrdiff_t >, OpResult, OpResult, OpResult >
Public Member Functions
ResultRange (Operation *op)
ArrayRef< Type > getTypes () const
Public Member Functions inherited from mlir::indexed_accessor_range< ResultRange, Operation *, OpResult, OpResult, OpResult >
indexed_accessor_range (Operation * base, ptrdiff_t startIndex, ptrdiff_t count)
const Operation * & getBase () const
Returns the current base of the range.
ptrdiff_t getStartIndex () const
Returns the current start index of the range.
Public Member Functions inherited from mlir::detail::indexed_accessor_range_base< ResultRange, std::pair< Operation *, ptrdiff_t >, OpResult, OpResult, OpResult >
indexed_accessor_range_base (iterator begin, iterator end)
indexed_accessor_range_base (const iterator_range< iterator > &range)
indexed_accessor_range_base (std::pair< Operation *, ptrdiff_t > base, ptrdiff_t count)
iterator begin () const
iterator end () const
OpResult operator[] (unsigned index) const
size_t size () const
Return the size of this range.
bool empty () const
Return if the range is empty.
ResultRange slice (size_t n, size_t m) const
Drop the first N elements, and keep M elements.
ResultRange drop_front (size_t n=1) const
Drop the first n elements.
ResultRange drop_back (size_t n=1) const
Drop the last n elements.
ResultRange take_front (size_t n=1) const
Take the first n elements.
operator SmallVector< SVT, N > () const
Allow conversion to SmallVector if necessary.
Additional Inherited Members
Static Public Member Functions inherited from mlir::indexed_accessor_range< ResultRange, Operation *, OpResult, OpResult, OpResult >
static std::pair< Operation *, ptrdiff_t > offset_base (const std::pair< Operation *, ptrdiff_t > &base, ptrdiff_t index)
See detail::indexed_accessor_range_base for details.
static OpResult dereference_iterator (const std::pair< Operation *, ptrdiff_t > &base, ptrdiff_t index)
See detail::indexed_accessor_range_base for details.
Protected Member Functions inherited from mlir::detail::indexed_accessor_range_base< ResultRange, std::pair< Operation *, ptrdiff_t >, OpResult, OpResult, OpResult >
indexed_accessor_range_base (const indexed_accessor_range_base &)=default
indexed_accessor_range_base (indexed_accessor_range_base &&)=default
indexed_accessor_range_base & operator= (const indexed_accessor_range_base &)=default
Protected Attributes inherited from mlir::detail::indexed_accessor_range_base< ResultRange, std::pair< Operation *, ptrdiff_t >, OpResult, OpResult, OpResult >
std::pair< Operation *, ptrdiff_t > base
The base that owns the provided range of values.
ptrdiff_t count
The size from the owning range.
Detailed Description
This class implements the result iterators for the Operation class.
Definition at line 589 of file OperationSupport.h.
Member Typedef Documentation
type_iterator
using mlir::ResultRange::type_iterator = ArrayRef<Type>::iterator
Returns the types of the values within this range.
Definition at line 598 of file OperationSupport.h.
Constructor & Destructor Documentation
ResultRange()
ResultRange::ResultRange (Operation * op)
Definition at line 152 of file OperationSupport.cpp.
Member Function Documentation
getTypes()
ArrayRef< Type > ResultRange::getTypes () const
Definition at line 155 of file OperationSupport.cpp.
References mlir::indexed_accessor_range< ResultRange, Operation *, OpResult, OpResult, OpResult >::getBase(), mlir::Operation::getResult(), and mlir::Operation::getResultTypes().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/OperationSupport.cpp