MLIR: mlir::AttributeStorage Class Reference
mlir::AttributeStorage Class Reference
Base storage class appearing in an attribute.
#include "mlir/IR/AttributeSupport.h"
Public Member Functions
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Protected Member Functions
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Base storage class appearing in an attribute.
Derived storage classes should only be constructed within the context of the AttributeUniquer.
Definition at line 34 of file AttributeSupport.h.
Constructor & Destructor Documentation
AttributeStorage() [1/2]
AttributeStorage::AttributeStorage (Type type) protected
Construct a new attribute storage instance with the given type.
Note: All attributes require a valid type. If no type is provided here, the type of the attribute will automatically default to NoneType upon initialization in the uniquer.
Definition at line 27 of file Attributes.cpp.
AttributeStorage() [2/2]
AttributeStorage::AttributeStorage () protected
Definition at line 29 of file Attributes.cpp.
Member Function Documentation
getDialect()
Dialect& mlir::AttributeStorage::getDialect () const inline
Get the dialect of this attribute.
Definition at line 43 of file AttributeSupport.h.
Referenced by mlir::OpaqueElementsAttr::decode(), and mlir::OpaqueElementsAttr::getValue().
getType()
Type AttributeStorage::getType () const
Get the type of this attribute.
Definition at line 31 of file Attributes.cpp.
References mlir::Type::getFromOpaquePointer().
Referenced by mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getBoolValues(), mlir::Attribute::getContext(), mlir::ElementsAttr::getFlattenedIndex(), mlir::DenseElementsAttr::getFloatValues(), mlir::DenseElementsAttr::getIntValues(), mlir::ElementsAttr::getNumElements(), mlir::detail::IntegerAttributeStorage::getValue(), mlir::SparseElementsAttr::getValue(), mlir::DenseElementsAttr::int_value_begin(), mlir::DenseElementsAttr::int_value_end(), mlir::ElementsAttr::isValidIndex(), mlir::DenseElementsAttr::isValidIntOrFloat(), mlir::DenseFPElementsAttr::mapValues(), mlir::DenseIntElementsAttr::mapValues(), mlir::detail::FloatAttributeStorage::operator==(), mlir::detail::IntegerAttributeStorage::operator==(), mlir::detail::OpaqueAttributeStorage::operator==(), mlir::detail::StringAttributeStorage::operator==(), mlir::detail::DenseElementsAttributeStorage::operator==(), mlir::detail::OpaqueElementsAttributeStorage::operator==(), mlir::detail::SparseElementsAttributeStorage::operator==(), and mlir::DenseElementsAttr::reshape().
initializeDialect()
void mlir::AttributeStorage::initializeDialect (Dialect & newDialect) inline protected
Definition at line 61 of file AttributeSupport.h.
setType()
void AttributeStorage::setType (Type type) protected
Set the type of this attribute.
Definition at line 34 of file Attributes.cpp.
References mlir::Type::getAsOpaquePointer().
The documentation for this class was generated from the following files:
include/mlir/IR/AttributeSupport.h
lib/IR/Attributes.cpp