MLIR: mlir::AsmState Class Reference
mlir::AsmState Class Reference
This class provides management for the lifetime of the state used when printing the IR.
#include "mlir/IR/AsmState.h"
Public Member Functions
AsmState (Operation *op)
Initialize the asm state at the level of the given operation.
~AsmState ()
detail::AsmStateImpl & getImpl ()
Return an instance of the internal implementation.
Detailed Description
This class provides management for the lifetime of the state used when printing the IR.
It allows for alleviating the cost of recomputing the internal state of the asm printer.
The IR should not be mutated in-between invocations using this state, and the IR being printed must not be an parent of the IR originally used to initialize this state. This means that if a child operation is provided, a parent operation cannot reuse this state.
Definition at line 33 of file AsmState.h.
Constructor & Destructor Documentation
AsmState()
AsmState::AsmState (Operation * op)
Initialize the asm state at the level of the given operation.
Definition at line 801 of file AsmPrinter.cpp.
~AsmState()
AsmState::~AsmState ()
Definition at line 802 of file AsmPrinter.cpp.
References mlir::StandardAttributes::CallSiteLocation, mlir::Attribute::cast(), mlir::StandardAttributes::FileLineColLocation, mlir::StandardAttributes::FusedLocation, mlir::CallSiteLoc::getCaller(), mlir::OpaqueLoc::getFallbackLocation(), mlir::FileLineColLoc::getFilename(), mlir::Attribute::getKind(), mlir::FileLineColLoc::getLine(), mlir::NameLoc::getName(), mlir::interleave(), mlir::interleaveComma(), mlir::functional::map(), mlir::StandardAttributes::NameLocation, mlir::StandardTypes::None, mlir::StandardAttributes::OpaqueLocation, and mlir::StandardAttributes::UnknownLocation.
Member Function Documentation
getImpl()
detail::AsmStateImpl& mlir::AsmState::getImpl () inline
Return an instance of the internal implementation.
Returns nullptr if the state has not been initialized.
Definition at line 41 of file AsmState.h.
Referenced by mlir::ModuleOp::print(), mlir::Operation::print(), mlir::Block::print(), mlir::Value::printAsOperand(), and mlir::Block::printAsOperand().
The documentation for this class was generated from the following files:
include/mlir/IR/AsmState.h
lib/IR/AsmPrinter.cpp