MLIR: mlir::SuccessorRange Class Reference
mlir::SuccessorRange Class Reference final
This class implements the successor iterators for Block.
#include "mlir/IR/BlockSupport.h"
Public Member Functions
SuccessorRange (Block *block)
SuccessorRange (Operation *term)
Public Member Functions inherited from mlir::detail::indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block *>
indexed_accessor_range_base (iterator begin, iterator end)
indexed_accessor_range_base (const iterator_range< iterator > &range)
indexed_accessor_range_base (BlockOperand * base, ptrdiff_t count)
iterator begin () const
iterator end () const
Block * operator[] (unsigned index) const
size_t size () const
Return the size of this range.
bool empty () const
Return if the range is empty.
SuccessorRange slice (size_t n, size_t m) const
Drop the first N elements, and keep M elements.
SuccessorRange drop_front (size_t n=1) const
Drop the first n elements.
SuccessorRange drop_back (size_t n=1) const
Drop the last n elements.
SuccessorRange take_front (size_t n=1) const
Take the first n elements.
operator SmallVector< SVT, N > () const
Allow conversion to SmallVector if necessary.
Additional Inherited Members
Public Types inherited from mlir::detail::indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block *>
using RangeBaseT = indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block * >
Protected Member Functions inherited from mlir::detail::indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block *>
indexed_accessor_range_base (const indexed_accessor_range_base &)=default
indexed_accessor_range_base (indexed_accessor_range_base &&)=default
indexed_accessor_range_base & operator= (const indexed_accessor_range_base &)=default
Protected Attributes inherited from mlir::detail::indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block *>
BlockOperand * base
The base that owns the provided range of values.
ptrdiff_t count
The size from the owning range.
Detailed Description
This class implements the successor iterators for Block.
Definition at line 56 of file BlockSupport.h.
Constructor & Destructor Documentation
SuccessorRange() [1/2]
SuccessorRange::SuccessorRange (Block * block)
Definition at line 286 of file Block.cpp.
References mlir::detail::indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block *>::base, mlir::detail::indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block *>::count, and mlir::Block::getTerminator().
SuccessorRange() [2/2]
SuccessorRange::SuccessorRange (Operation * term)
Definition at line 292 of file Block.cpp.
References mlir::detail::indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block *>::base, mlir::detail::indexed_accessor_range_base< SuccessorRange, BlockOperand *, Block *, Block *, Block *>::count, mlir::Operation::getBlockOperands(), and mlir::Operation::getNumSuccessors().
The documentation for this class was generated from the following files:
include/mlir/IR/BlockSupport.h
lib/IR/Block.cpp