MLIR: mlir::linalg::LinalgDialect Class Reference
mlir::linalg::LinalgDialect Class Reference
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
Public Member Functions
LinalgDialect (MLIRContext *context)
Type parseType (DialectAsmParser &parser) const override
Parse a type registered to this dialect.
void printType (Type type, DialectAsmPrinter &os) const override
Print a type registered to this dialect.
Public Member Functions inherited from mlir::Dialect
virtual ~Dialect ()
MLIRContext * getContext () const
StringRef getNamespace () const
bool allowsUnknownOperations () const
Returns true if this dialect allows for unregistered operations, i.e.
bool allowsUnknownTypes () const
Return true if this dialect allows for unregistered types, i.e., types prefixed with the dialect namespace but not registered with addType.
virtual Operation * materializeConstant (OpBuilder &builder, Attribute value, Type type, Location loc)
Registered hook to materialize a single constant operation from a given attribute value with the desired resultant type.
virtual Attribute parseAttribute (DialectAsmParser &parser, Type type) const
Parse an attribute registered to this dialect.
virtual void printAttribute (Attribute, DialectAsmPrinter &) const
Print an attribute registered to this dialect.
virtual LogicalResult verifyRegionArgAttribute (Operation *, unsigned regionIndex, unsigned argIndex, NamedAttribute)
Verify an attribute from this dialect on the argument at 'argIndex' for the region at 'regionIndex' on the given operation.
virtual LogicalResult verifyRegionResultAttribute (Operation *, unsigned regionIndex, unsigned resultIndex, NamedAttribute)
Verify an attribute from this dialect on the result at 'resultIndex' for the region at 'regionIndex' on the given operation.
virtual LogicalResult verifyOperationAttribute (Operation *, NamedAttribute)
Verify an attribute from this dialect on the given operation.
const DialectInterface * getRegisteredInterface (ClassID *interfaceID)
Lookup an interface for the given ID if one is registered, otherwise nullptr.
template<typename InterfaceT >
const InterfaceT * getRegisteredInterface ()
Static Public Member Functions
static StringRef getDialectNamespace ()
Static Public Member Functions inherited from mlir::Dialect
static bool isValidNamespace (StringRef str)
Utility function that returns if the given string is a valid dialect namespace.
Additional Inherited Members
Public Attributes inherited from mlir::Dialect
DialectConstantFoldHook constantFoldHook
Registered fallback constant fold hook for the dialect.
DialectConstantDecodeHook decodeHook
Registered hook to decode opaque constants associated with this dialect.
DialectExtractElementHook extractElementHook
Registered hook to extract an element from an opaque constant associated with this dialect.
Protected Member Functions inherited from mlir::Dialect
Dialect (StringRef name, MLIRContext *context)
The constructor takes a unique namespace for this dialect as well as the context to bind to.
template<typename... Args>
void addOperations ()
This method is used by derived classes to add their operations to the set.
void addOperation (AbstractOperation opInfo)
template<typename... Args>
void addTypes ()
This method is used by derived classes to add their types to the set.
template<typename... Args>
void addAttributes ()
This method is used by derived classes to add their attributes to the set.
void allowUnknownOperations (bool allow=true)
Enable support for unregistered operations.
void allowUnknownTypes (bool allow=true)
Enable support for unregistered types.
void addInterface (std::unique_ptr< DialectInterface > interface)
Register a dialect interface with this dialect instance.
template<typename T , typename T2 , typename... Tys>
void addInterfaces ()
Register a set of dialect interfaces with this dialect instance.
template<typename T >
void addInterfaces ()
Detailed Description
Definition at line 24 of file LinalgTypes.h.
Constructor & Destructor Documentation
LinalgDialect()
mlir::linalg::LinalgDialect::LinalgDialect (MLIRContext * context) explicit
Definition at line 27 of file LinalgTypes.cpp.
References mlir::Dialect::addOperations().
Member Function Documentation
getDialectNamespace()
static StringRef mlir::linalg::LinalgDialect::getDialectNamespace () inline static
Definition at line 27 of file LinalgTypes.h.
References parseType(), and printType().
parseType()
Type mlir::linalg::LinalgDialect::parseType (DialectAsmParser & parser) const override virtual
Parse a type registered to this dialect.
Reimplemented from mlir::Dialect.
Definition at line 39 of file LinalgTypes.cpp.
References mlir::DialectAsmParser::emitError(), mlir::linalg::RangeType::get(), mlir::Dialect::getContext(), mlir::DialectAsmParser::getNameLoc(), mlir::DialectAsmParser::parseKeyword(), and mlir::StandardAttributes::Type.
Referenced by getDialectNamespace().
printType()
void mlir::linalg::LinalgDialect::printType (Type type, DialectAsmPrinter & os) const override virtual
Print a type registered to this dialect.
Reimplemented from mlir::Dialect.
Definition at line 57 of file LinalgTypes.cpp.
References mlir::Type::cast(), mlir::Type::getKind(), print(), and mlir::linalg::Range.
Referenced by getDialectNamespace().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/IR/LinalgTypes.h
lib/Dialect/Linalg/IR/LinalgTypes.cpp