MLIR: mlir::ModuleOp Class Reference
mlir::ModuleOp Class Reference
ModuleOp represents a module, or an operation containing one region with a single block containing opaque operations.
#include "mlir/IR/Module.h"
Public Types
using iterator = Block::iterator
Iteration over the operations in the module.
Public Types inherited from mlir::Op< ModuleOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::SymbolTable, OpTrait::SingleBlockImplicitTerminator< ModuleTerminatorOp >::Impl >
using ConcreteOpType = ModuleOp
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
Public Types inherited from mlir::OpState
using dialect_attr_iterator = Operation::dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
using dialect_attr_range = Operation::dialect_attr_range
Public Member Functions
void print (OpAsmPrinter &p)
LogicalResult verify ()
Region & getBodyRegion ()
Return body of this module.
Block * getBody ()
Optional< StringRef > getName ()
Return the name of this module if present.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the this module in the custom top-level form.
void print (raw_ostream &os, AsmState &state, OpPrintingFlags flags=llvm::None)
void dump ()
iterator begin ()
iterator end ()
Operation & front ()
template<typename T >
iterator_range< Block::op_iterator< T > > getOps ()
This returns a range of operations of the given type 'T' held within the module.
void push_back (Operation *op)
Insert the operation into the back of the body, before the terminator.
void insert (Operation *insertPt, Operation *op)
Insert the operation at the given insertion point.
void insert (Block::iterator insertPt, Operation *op)
Public Member Functions inherited from mlir::Op< ModuleOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::SymbolTable, OpTrait::SingleBlockImplicitTerminator< ModuleTerminatorOp >::Impl >
Operation * getOperation ()
Return the operation that this refers to.
ModuleOp clone ()
Create a deep copy of this operation.
ModuleOp cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Dialect * getDialect ()
Return the dialect that this refers to.
Region * getParentRegion ()
Return the parent Region of this operation.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow implicit conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * getOperation ()
Return the operation that this refers to.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
template<typename OpTy >
OpTy getParentOfType ()
Return the closest surrounding parent operation that is of type 'OpTy'.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState, OpPrintingFlags flags=llvm::None)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
void setLoc (Location loc)
ArrayRef< NamedAttribute > getAttrs ()
Return all of the attributes on this operation.
dialect_attr_range getDialectAttrs ()
Return a range corresponding to the dialect attributes for this operation.
dialect_attr_iterator dialect_attr_begin ()
dialect_attr_iterator dialect_attr_end ()
Attribute getAttr (StringRef name)
Return an attribute with the specified name.
template<typename AttrClass >
AttrClass getAttrOfType (StringRef name)
If the operation has an attribute of the specified type, return it.
void setAttr (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setAttr (StringRef name, Attribute value)
void setAttrs (ArrayRef< NamedAttribute > attributes)
Set the attributes held by this operation.
void setAttrs (NamedAttributeList newAttrs)
template<typename DialectAttrs >
void setDialectAttrs (DialectAttrs &&attrs)
Set the dialect attributes for this operation, and preserve all dependent.
NamedAttributeList::RemoveResult removeAttr (Identifier name)
Remove the attribute with the specified name if it exists.
NamedAttributeList::RemoveResult removeAttr (StringRef name)
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk the operation in postorder, calling the callback for each nested operation(including this one).
Public Member Functions inherited from mlir::FoldingHook< ModuleOp, llvm::is_one_of< OpTrait::OneResult< ModuleOp >, OpTrait::ZeroOperands< ModuleOp >... >::value >
LogicalResult fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This hook implements a generalized folder for this operation.
Static Public Member Functions
static StringRef getOperationName ()
static void build (Builder *builder, OperationState &result, Optional< StringRef > name=llvm::None)
static ModuleOp create (Location loc, Optional< StringRef > name=llvm::None)
Construct a module from the given location with an optional name.
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Operation hooks.
Static Public Member Functions inherited from mlir::Op< ModuleOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::SymbolTable, OpTrait::SingleBlockImplicitTerminator< ModuleTerminatorOp >::Impl >
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
static ParseResult parseAssembly (OpAsmParser &parser, OperationState &result)
This is the hook used by the AsmParser to parse the custom form of this op from an .mlir file.
static void printAssembly (Operation *op, OpAsmPrinter &p)
This is the hook used by the AsmPrinter to emit this to the .mlir file.
static LogicalResult verifyInvariants (Operation *op)
This is the hook that checks whether or not this operation is well formed according to the invariants of its opcode.
static AbstractOperation::OperationProperties getOperationProperties ()
static ConcreteOpType getFromOpaquePointer (const void *pointer)
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (OwningRewritePatternList &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Static Public Member Functions inherited from mlir::OpTrait::ZeroOperands< ModuleOp >
static LogicalResult verifyTrait (Operation *op)
Static Public Member Functions inherited from mlir::FoldingHook< ModuleOp, llvm::is_one_of< OpTrait::OneResult< ModuleOp >, OpTrait::ZeroOperands< ModuleOp >... >::value >
static LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This is an implementation detail of the constant folder hook for AbstractOperation.
Additional Inherited Members
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
void print (OpAsmPrinter &p)
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ModuleOp, ZeroOperands >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Unless overridden, the custom assembly form of an op is always rejected.
Static Protected Member Functions inherited from mlir::OpTrait::TraitBase< ModuleOp, ZeroOperands >
static LogicalResult verifyTrait (Operation *op)
Provide default implementations of trait hooks.
static AbstractOperation::OperationProperties getTraitProperties ()
Detailed Description
ModuleOp represents a module, or an operation containing one region with a single block containing opaque operations.
The region of a module is not allowed to implicitly capture global values, and all external references must use symbolic references via attributes(e.g. via a string name).
Definition at line 29 of file Module.h.
Member Typedef Documentation
iterator
using mlir::ModuleOp::iterator = Block::iterator
Iteration over the operations in the module.
Definition at line 69 of file Module.h.
Member Function Documentation
begin()
iterator mlir::ModuleOp::begin () inline
Definition at line 71 of file Module.h.
References mlir::Block::begin(), and getBody().
Referenced by front().
build()
void ModuleOp::build (Builder * builder, OperationState & result, Optional< StringRef > name = llvm::None) static
Definition at line 2223 of file SPIRVOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::Builder::getI32IntegerAttr(), and mlir::OperationState::location.
Referenced by create(), and getOperationName().
create()
ModuleOp ModuleOp::create (Location loc, Optional< StringRef > name = llvm::None) static
Construct a module from the given location with an optional name.
Construct a module from the given context.
Definition at line 28 of file Module.cpp.
References build(), mlir::Operation::create(), and mlir::Attribute::getContext().
Referenced by deserializeModule(), getOperationName(), mlir::parseSourceFile(), roundTripModule(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), and mlir::translateLLVMIRToModule().
dump()
void ModuleOp::dump ()
Definition at line 2288 of file AsmPrinter.cpp.
References print().
Referenced by getOperationName().
end()
iterator mlir::ModuleOp::end () inline
Definition at line 72 of file Module.h.
References mlir::Block::end(), and getBody().
front()
Operation& mlir::ModuleOp::front () inline
Definition at line 73 of file Module.h.
References begin().
getBody()
Block * ModuleOp::getBody ()
Definition at line 102 of file Module.cpp.
References mlir::Region::front(), and getBodyRegion().
Referenced by begin(), deserializeModule(), diag(), end(), getOperationName(), getOps(), insert(), push_back(), and roundTripModule().
getBodyRegion()
Region & ModuleOp::getBodyRegion ()
Return body of this module.
Definition at line 101 of file Module.cpp.
References mlir::Op< ModuleOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::SymbolTable, OpTrait::SingleBlockImplicitTerminator< ModuleTerminatorOp >::Impl >::getOperation(), and mlir::Operation::getRegion().
Referenced by getBody(), getOperationName(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
getName()
Optional< StringRef > ModuleOp::getName ()
Return the name of this module if present.
Definition at line 104 of file Module.cpp.
References mlir::SymbolTable::getSymbolAttrName(), and mlir::StandardTypes::None.
Referenced by getOperationName(), and print().
getOperationName()
static StringRef mlir::ModuleOp::getOperationName () inline static
Definition at line 38 of file Module.h.
References build(), create(), dump(), getBody(), getBodyRegion(), getName(), mlir::StandardTypes::None, parse(), print(), and verify().
Referenced by mlir::gpu::GPUDialect::verifyOperationAttribute().
getOps()
template<typename T > iterator_range<Block::op_iterator<T> > mlir::ModuleOp::getOps () inline
This returns a range of operations of the given type 'T' held within the module.
Definition at line 77 of file Module.h.
References getBody(), and mlir::Block::getOps().
Referenced by mlir::LLVM::ensureDistinctSuccessors().
insert() [1/2]
void mlir::ModuleOp::insert (Operation * insertPt, Operation * op) inline
Insert the operation at the given insertion point.
Note: The operation is never inserted after the terminator, even if the insertion point is end().
Definition at line 88 of file Module.h.
Referenced by push_back().
insert() [2/2]
void mlir::ModuleOp::insert (Block::iterator insertPt, Operation * op) inline
Definition at line 91 of file Module.h.
References getBody().
parse()
ParseResult ModuleOp::parse (OpAsmParser & parser, OperationState & result) static
Operation hooks.
Definition at line 35 of file Module.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::SymbolTable::getSymbolAttrName(), mlir::OperationState::location, mlir::StandardTypes::None, mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseOptionalSymbolName(), mlir::OpAsmParser::parseRegion(), and mlir::success().
Referenced by getOperationName().
print() [1/3]
void ModuleOp::print (OpAsmPrinter & p)
Definition at line 55 of file Module.cpp.
References mlir::OpState::getAttrs(), getName(), mlir::Op< ModuleOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::SymbolTable, OpTrait::SingleBlockImplicitTerminator< ModuleTerminatorOp >::Impl >::getOperation(), mlir::SymbolTable::getSymbolAttrName(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), and mlir::OpAsmPrinter::printSymbolName().
Referenced by getOperationName(), performActions(), printIR(), printMLIROutput(), roundTripModule(), and runWithCrashRecovery().
print() [2/3]
void ModuleOp::print (raw_ostream & os, OpPrintingFlags flags = llvm::None)
Print the this module in the custom top-level form.
Definition at line 2276 of file AsmPrinter.cpp.
References mlir::AsmState::getImpl(), mlir::detail::AsmStateImpl::initializeAliases(), print(), and mlir::OpPrintingFlags::shouldUseLocalScope().
print() [3/3]
void ModuleOp::print (raw_ostream & os, AsmState & state, OpPrintingFlags flags = llvm::None)
Definition at line 2284 of file AsmPrinter.cpp.
References mlir::AsmState::getImpl(), and print().
push_back()
void mlir::ModuleOp::push_back (Operation * op) inline
Insert the operation into the back of the body, before the terminator.
Definition at line 82 of file Module.h.
References getBody(), and insert().
verify()
LogicalResult ModuleOp::verify ()
Definition at line 72 of file Module.cpp.
References mlir::OpState::emitOpError(), mlir::Operation::getAttrList(), mlir::NamedAttributeList::getAttrs(), mlir::Op< ModuleOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::SymbolTable, OpTrait::SingleBlockImplicitTerminator< ModuleTerminatorOp >::Impl >::getOperation(), mlir::Operation::getRegion(), mlir::SymbolTable::getSymbolAttrName(), mlir::SymbolTable::getVisibilityAttrName(), mlir::has_single_element(), and mlir::success().
Referenced by getOperationName().
The documentation for this class was generated from the following files:
include/mlir/IR/Module.h
lib/Dialect/SPIRV/SPIRVOps.cpp
lib/IR/AsmPrinter.cpp
lib/IR/Module.cpp