MLIR: mlir::detail::OperandStorage Class Reference
mlir::detail::OperandStorage Class Reference final
This class handles the management of operation operands.
#include "mlir/IR/OperationSupport.h"
Public Member Functions
OperandStorage (unsigned numOperands, bool resizable)
~OperandStorage ()
void setOperands (Operation *owner, ValueRange operands)
Replace the operands contained in the storage with the ones provided in 'operands'.
void eraseOperand (unsigned index)
Erase an operand held by the storage.
MutableArrayRef< OpOperand > getOperands ()
Get the operation operands held by the storage.
unsigned size () const
Return the number of operands held in the storage.
bool isResizable () const
Returns if this storage is resizable.
Static Public Member Functions
static size_t additionalAllocSize (unsigned numOperands, bool resizable)
Returns the additional size necessary for allocating this object.
Detailed Description
This class handles the management of operation operands.
Operands are stored similarly to the elements of a SmallVector except for two key differences. The first is the inline storage, which is a trailing objects array. The second is that being able to dynamically resize the operand list is optional.
Definition at line 376 of file OperationSupport.h.
Constructor & Destructor Documentation
OperandStorage()
mlir::detail::OperandStorage::OperandStorage (unsigned numOperands, bool resizable) inline
Definition at line 380 of file OperationSupport.h.
~OperandStorage()
mlir::detail::OperandStorage::~OperandStorage () inline
Definition at line 389 of file OperationSupport.h.
Member Function Documentation
additionalAllocSize()
static size_t mlir::detail::OperandStorage::additionalAllocSize (unsigned numOperands, bool resizable) inline static
Returns the additional size necessary for allocating this object.
Definition at line 415 of file OperationSupport.h.
Referenced by mlir::Operation::create().
eraseOperand()
void detail::OperandStorage::eraseOperand (unsigned index)
Erase an operand held by the storage.
Definition at line 107 of file OperationSupport.cpp.
References mlir::detail::ResizableStorage::capacity, mlir::OperationState::operands, and mlir::detail::ResizableStorage::setDynamicStorage().
Referenced by mlir::Operation::eraseOperand().
getOperands()
MutableArrayRef<OpOperand> mlir::detail::OperandStorage::getOperands () inline
Get the operation operands held by the storage.
Definition at line 407 of file OperationSupport.h.
Referenced by mlir::Operation::getOpOperands().
isResizable()
bool mlir::detail::OperandStorage::isResizable () const inline
Returns if this storage is resizable.
Definition at line 421 of file OperationSupport.h.
Referenced by mlir::Operation::hasResizableOperandsList().
setOperands()
void detail::OperandStorage::setOperands (Operation * owner, ValueRange operands)
Replace the operands contained in the storage with the ones provided in 'operands'.
Definition at line 71 of file OperationSupport.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
size()
unsigned mlir::detail::OperandStorage::size () const inline
Return the number of operands held in the storage.
Definition at line 412 of file OperationSupport.h.
Referenced by mlir::Operation::getNumOperands().
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/OperationSupport.cpp