MLIR: mlir::LLVM::LLVMType Class Reference
mlir::LLVM::LLVMType Class Reference
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
Public Types
enum Kind { LLVM_TYPE = FIRST_LLVM_TYPE }
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
LLVMDialect & getDialect ()
llvm::Type * getUnderlyingType () const
bool isHalfTy ()
Utilities to identify types.
bool isFloatTy ()
bool isDoubleTy ()
bool isIntegerTy ()
bool isIntegerTy (unsigned bitwidth)
LLVMType getArrayElementType ()
Array type utilities.
unsigned getArrayNumElements ()
bool isArrayTy ()
LLVMType getVectorElementType ()
Vector type utilities.
bool isVectorTy ()
LLVMType getFunctionParamType (unsigned argIdx)
Function type utilities.
unsigned getFunctionNumParams ()
LLVMType getFunctionResultType ()
bool isFunctionTy ()
LLVMType getPointerTo (unsigned addrSpace=0)
Pointer type utilities.
LLVMType getPointerElementTy ()
bool isPointerTy ()
LLVMType getStructElementType (unsigned i)
Struct type utilities.
unsigned getStructNumElements ()
bool isStructTy ()
Static Public Member Functions
static bool kindof (unsigned kind)
static LLVMType getDoubleTy (LLVMDialect *dialect)
Utilities used to generate floating point types.
static LLVMType getFloatTy (LLVMDialect *dialect)
static LLVMType getHalfTy (LLVMDialect *dialect)
static LLVMType getFP128Ty (LLVMDialect *dialect)
static LLVMType getX86_FP80Ty (LLVMDialect *dialect)
static LLVMType getIntNTy (LLVMDialect *dialect, unsigned numBits)
Utilities used to generate integer types.
static LLVMType getInt1Ty (LLVMDialect *dialect)
static LLVMType getInt8Ty (LLVMDialect *dialect)
static LLVMType getInt8PtrTy (LLVMDialect *dialect)
static LLVMType getInt16Ty (LLVMDialect *dialect)
static LLVMType getInt32Ty (LLVMDialect *dialect)
static LLVMType getInt64Ty (LLVMDialect *dialect)
static LLVMType getArrayTy (LLVMType elementType, uint64_t numElements)
Utilities used to generate other miscellaneous types.
static LLVMType getFunctionTy (LLVMType result, ArrayRef< LLVMType > params, bool isVarArg)
static LLVMType getFunctionTy (LLVMType result, bool isVarArg)
static LLVMType getStructTy (LLVMDialect *dialect, ArrayRef< LLVMType > elements, bool isPacked=false)
static LLVMType getStructTy (LLVMDialect *dialect, bool isPacked=false)
template<typename... Args>
static std::enable_if< llvm::are_base_of< LLVMType, Args... >::value, LLVMType >::type getStructTy (LLVMType elt1, Args... elts)
static LLVMType getVectorTy (LLVMType elementType, unsigned numElements)
static LLVMType getVoidTy (LLVMDialect *dialect)
static LLVMType createStructTy (LLVMDialect *dialect, ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked=false)
static LLVMType createStructTy (LLVMDialect *dialect, Optional< StringRef > name)
static LLVMType createStructTy (ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked=false)
template<typename... Args>
static std::enable_if_t< llvm::are_base_of< LLVMType, Args... >::value, LLVMType > createStructTy (StringRef name, LLVMType elt1, Args... elts)
static LLVMType setStructTyBody (LLVMType structType, ArrayRef< LLVMType > elements, bool isPacked=false)
template<typename... Args>
static std::enable_if_t< llvm::are_base_of< LLVMType, Args... >::value, LLVMType > setStructTyBody (LLVMType structType, LLVMType elt1, Args... elts)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Definition at line 44 of file LLVMDialect.h.
Member Enumeration Documentation
Kind
enum mlir::LLVM::LLVMType::Kind
Enumerator
LLVM_TYPE
Definition at line 47 of file LLVMDialect.h.
Member Function Documentation
createStructTy() [1/4]
LLVMType LLVMType::createStructTy (LLVMDialect * dialect, ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked = false) static
Definition at line 1806 of file LLVMDialect.cpp.
References mlir::LLVM::LLVMDialect::getLLVMContext(), and toUnderlyingTypes().
createStructTy() [2/4]
static LLVMType mlir::LLVM::LLVMType::createStructTy (LLVMDialect * dialect, Optional< StringRef > name) inline static
Definition at line 148 of file LLVMDialect.h.
References mlir::StandardTypes::None.
createStructTy() [3/4]
static LLVMType mlir::LLVM::LLVMType::createStructTy (ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked = false) inline static
Definition at line 153 of file LLVMDialect.h.
createStructTy() [4/4]
template<typename... Args> static std::enable_if_t<llvm::are_base_of<LLVMType, Args...>::value, LLVMType> mlir::LLVM::LLVMType::createStructTy (StringRef name, LLVMType elt1, Args... elts) inline static
Definition at line 165 of file LLVMDialect.h.
References getDialect().
getArrayElementType()
LLVMType LLVMType::getArrayElementType ()
Array type utilities.
Definition at line 1677 of file LLVMDialect.cpp.
References mlir::Dialect::getContext().
Referenced by diag(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), and verify().
getArrayNumElements()
unsigned LLVMType::getArrayNumElements ()
Definition at line 1680 of file LLVMDialect.cpp.
Referenced by diag(), and verify().
getArrayTy()
LLVMType LLVMType::getArrayTy (LLVMType elementType, uint64_t numElements) static
Utilities used to generate other miscellaneous types.
Definition at line 1769 of file LLVMDialect.cpp.
References getDialect(), and getUnderlyingType().
Referenced by mlir::LLVM::createGlobalString(), diag(), and parseGlobalOp().
getDialect()
LLVMDialect & LLVMType::getDialect ()
Definition at line 1668 of file LLVMDialect.cpp.
References mlir::Type::getDialect().
Referenced by createStructTy(), getArrayTy(), getFunctionTy(), getStructTy(), getVectorTy(), and setStructTyBody().
getDoubleTy()
LLVMType LLVMType::getDoubleTy (LLVMDialect * dialect) static
Utilities used to generate floating point types.
Definition at line 1727 of file LLVMDialect.cpp.
Referenced by diag(), getI64SubArray(), and mlir::LLVMTypeConverter::getLLVMContext().
getFloatTy()
LLVMType LLVMType::getFloatTy (LLVMDialect * dialect) static
Definition at line 1730 of file LLVMDialect.cpp.
Referenced by diag(), getI64SubArray(), mlir::LLVMTypeConverter::getLLVMContext(), and verify().
getFP128Ty()
LLVMType LLVMType::getFP128Ty (LLVMDialect * dialect) static
Definition at line 1736 of file LLVMDialect.cpp.
Referenced by diag().
getFunctionNumParams()
unsigned LLVMType::getFunctionNumParams ()
Definition at line 1695 of file LLVMDialect.cpp.
Referenced by parseShuffleVectorOp(), and printLLVMFuncOp().
getFunctionParamType()
LLVMType LLVMType::getFunctionParamType (unsigned argIdx)
Function type utilities.
Definition at line 1692 of file LLVMDialect.cpp.
References mlir::Dialect::getContext().
Referenced by getICmpPredicate(), parseShuffleVectorOp(), and printLLVMFuncOp().
getFunctionResultType()
LLVMType LLVMType::getFunctionResultType ()
Definition at line 1698 of file LLVMDialect.cpp.
References mlir::Dialect::getContext().
Referenced by printLLVMFuncOp().
getFunctionTy() [1/2]
LLVMType LLVMType::getFunctionTy (LLVMType result, ArrayRef< LLVMType > params, bool isVarArg) static
Definition at line 1775 of file LLVMDialect.cpp.
References getDialect(), and getUnderlyingType().
Referenced by buildLLVMFunctionType(), mlir::LLVMTypeConverter::convertFunctionSignature(), diag(), getI64SubArray(), parseCallOp(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
getFunctionTy() [2/2]
static LLVMType mlir::LLVM::LLVMType::getFunctionTy (LLVMType result, bool isVarArg) inline static
Definition at line 124 of file LLVMDialect.h.
References mlir::StandardTypes::None.
getHalfTy()
LLVMType LLVMType::getHalfTy (LLVMDialect * dialect) static
Definition at line 1733 of file LLVMDialect.cpp.
Referenced by mlir::LLVMTypeConverter::getLLVMContext(), and verify().
getInt16Ty()
static LLVMType mlir::LLVM::LLVMType::getInt16Ty (LLVMDialect * dialect) inline static
Definition at line 110 of file LLVMDialect.h.
getInt1Ty()
static LLVMType mlir::LLVM::LLVMType::getInt1Ty (LLVMDialect * dialect) inline static
Definition at line 101 of file LLVMDialect.h.
Referenced by parseAtomicCmpXchgOp(), parseCmpOp(), parseCondBrOp(), and parseNVVMVoteBallotOp().
getInt32Ty()
static LLVMType mlir::LLVM::LLVMType::getInt32Ty (LLVMDialect * dialect) inline static
Definition at line 113 of file LLVMDialect.h.
Referenced by mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), parseNVVMShflSyncBflyOp(), and parseNVVMVoteBallotOp().
getInt64Ty()
static LLVMType mlir::LLVM::LLVMType::getInt64Ty (LLVMDialect * dialect) inline static
Definition at line 116 of file LLVMDialect.h.
Referenced by mlir::LLVM::createGlobalString(), getI64SubArray(), and mlir::LLVMTypeConverter::promoteOneMemRefDescriptor().
getInt8PtrTy()
static LLVMType mlir::LLVM::LLVMType::getInt8PtrTy (LLVMDialect * dialect) inline static
Definition at line 107 of file LLVMDialect.h.
References getPointerTo().
Referenced by mlir::LLVM::createGlobalString(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
getInt8Ty()
static LLVMType mlir::LLVM::LLVMType::getInt8Ty (LLVMDialect * dialect) inline static
Definition at line 104 of file LLVMDialect.h.
Referenced by mlir::LLVM::createGlobalString(), and parseGlobalOp().
getIntNTy()
LLVMType LLVMType::getIntNTy (LLVMDialect * dialect, unsigned numBits) static
Utilities used to generate integer types.
Definition at line 1744 of file LLVMDialect.cpp.
References mlir::LLVM::LLVMDialect::getLLVMContext().
Referenced by diag(), mlir::LLVMTypeConverter::getLLVMContext(), mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
getPointerElementTy()
LLVMType LLVMType::getPointerElementTy ()
Definition at line 1712 of file LLVMDialect.cpp.
References mlir::Dialect::getContext().
getPointerTo()
LLVMType LLVMType::getPointerTo (unsigned addrSpace = 0)
Pointer type utilities.
Definition at line 1706 of file LLVMDialect.cpp.
Referenced by mlir::LLVMTypeConverter::convertFunctionSignature(), diag(), getInt8PtrTy(), parseAtomicCmpXchgOp(), and parseAtomicRMWOp().
getStructElementType()
LLVMType LLVMType::getStructElementType (unsigned i)
Struct type utilities.
Definition at line 1718 of file LLVMDialect.cpp.
References mlir::Dialect::getContext().
Referenced by parseNVVMShflSyncBflyOp().
getStructNumElements()
unsigned LLVMType::getStructNumElements ()
Definition at line 1721 of file LLVMDialect.cpp.
getStructTy() [1/3]
LLVMType LLVMType::getStructTy (LLVMDialect * dialect, ArrayRef< LLVMType > elements, bool isPacked = false) static
Definition at line 1787 of file LLVMDialect.cpp.
References mlir::LLVM::LLVMDialect::getLLVMContext().
Referenced by diag(), mlir::LLVMTypeConverter::packFunctionResults(), parseAtomicCmpXchgOp(), and verify().
getStructTy() [2/3]
static LLVMType mlir::LLVM::LLVMType::getStructTy (LLVMDialect * dialect, bool isPacked = false) inline static
Definition at line 129 of file LLVMDialect.h.
References mlir::StandardTypes::None.
getStructTy() [3/3]
template<typename... Args> static std::enable_if<llvm::are_base_of<LLVMType, Args...>::value, LLVMType>::type mlir::LLVM::LLVMType::getStructTy (LLVMType elt1, Args... elts) inline static
Definition at line 135 of file LLVMDialect.h.
References getDialect().
getUnderlyingType()
llvm::Type * LLVMType::getUnderlyingType () const
Definition at line 1672 of file LLVMDialect.cpp.
Referenced by diag(), getArrayTy(), getFunctionTy(), getI64SubArray(), getVectorTy(), parseShuffleVectorOp(), printLLVMFuncOp(), mlir::LLVM::LLVMDialect::printType(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), setStructTyBody(), and verify().
getVectorElementType()
LLVMType LLVMType::getVectorElementType ()
Vector type utilities.
Definition at line 1686 of file LLVMDialect.cpp.
References mlir::Dialect::getContext().
Referenced by diag(), and parseCallOp().
getVectorTy()
LLVMType LLVMType::getVectorTy (LLVMType elementType, unsigned numElements) static
Definition at line 1828 of file LLVMDialect.cpp.
References getDialect(), and getUnderlyingType().
Referenced by diag(), parseCmpOp(), parseShuffleVectorOp(), and verify().
getVoidTy()
LLVMType LLVMType::getVoidTy (LLVMDialect * dialect) static
Definition at line 1834 of file LLVMDialect.cpp.
Referenced by buildLLVMFunctionType(), mlir::LLVMTypeConverter::convertFunctionSignature(), diag(), getI64SubArray(), parseCallOp(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
getX86_FP80Ty()
LLVMType LLVMType::getX86_FP80Ty (LLVMDialect * dialect) static
Definition at line 1739 of file LLVMDialect.cpp.
Referenced by diag().
isArrayTy()
bool LLVMType::isArrayTy ()
Definition at line 1683 of file LLVMDialect.cpp.
Referenced by diag().
isDoubleTy()
bool mlir::LLVM::LLVMType::isDoubleTy () inline
Definition at line 61 of file LLVMDialect.h.
Referenced by diag(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), and verify().
isFloatTy()
bool mlir::LLVM::LLVMType::isFloatTy () inline
Definition at line 60 of file LLVMDialect.h.
Referenced by diag(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), and verify().
isFunctionTy()
bool LLVMType::isFunctionTy ()
Definition at line 1703 of file LLVMDialect.cpp.
isHalfTy()
bool mlir::LLVM::LLVMType::isHalfTy () inline
Utilities to identify types.
Definition at line 59 of file LLVMDialect.h.
Referenced by verify().
isIntegerTy() [1/2]
bool mlir::LLVM::LLVMType::isIntegerTy () inline
Definition at line 62 of file LLVMDialect.h.
Referenced by diag(), and verify().
isIntegerTy() [2/2]
bool mlir::LLVM::LLVMType::isIntegerTy (unsigned bitwidth) inline
Definition at line 63 of file LLVMDialect.h.
isPointerTy()
bool LLVMType::isPointerTy ()
Definition at line 1715 of file LLVMDialect.cpp.
Referenced by verify().
isStructTy()
bool LLVMType::isStructTy ()
Definition at line 1724 of file LLVMDialect.cpp.
isVectorTy()
bool LLVMType::isVectorTy ()
Definition at line 1689 of file LLVMDialect.cpp.
Referenced by diag().
kindof()
static bool mlir::LLVM::LLVMType::kindof (unsigned kind) inline static
Definition at line 53 of file LLVMDialect.h.
References mlir::StandardAttributes::Type.
setStructTyBody() [1/2]
LLVMType LLVMType::setStructTyBody (LLVMType structType, ArrayRef< LLVMType > elements, bool isPacked = false) static
Definition at line 1818 of file LLVMDialect.cpp.
References getDialect(), getUnderlyingType(), and toUnderlyingTypes().
setStructTyBody() [2/2]
template<typename... Args> static std::enable_if_t<llvm::are_base_of<LLVMType, Args...>::value, LLVMType> mlir::LLVM::LLVMType::setStructTyBody (LLVMType structType, LLVMType elt1, Args... elts) inline static
Definition at line 178 of file LLVMDialect.h.
References mlir::StandardAttributes::Type.
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMDialect.h
lib/Dialect/LLVMIR/IR/LLVMDialect.cpp