MLIR: mlir::quantizer::CAGSlice Class Reference
mlir::quantizer::CAGSlice Class Reference
A slice of a CAG (which may be the whole graph).
#include "mlir/Quantizer/Support/ConstraintAnalysisGraph.h"
Public Types
using node_vector = std::vector< CAGNode * >
using iterator = node_vector::iterator
using const_iterator = node_vector::const_iterator
Public Member Functions
CAGSlice (SolverContext &context)
~CAGSlice ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
CAGOperandAnchor * getOperandAnchor (Operation *op, unsigned operandIdx)
Gets an operand anchor node.
CAGResultAnchor * getResultAnchor (Operation *op, unsigned resultIdx)
Gets a result anchor node.
template<typename T , typename... Args>
T * addUniqueConstraint (ArrayRef< CAGAnchorNode *> anchors, Args... args)
Adds a relation constraint with incoming 'from' anchors and outgoing 'to' anchors.
template<typename T , typename... Args>
T * addUnidirectionalConstraint (CAGAnchorNode *fromAnchor, ArrayRef< CAGAnchorNode *> toAnchors, Args... args)
Adds a unidirectional constraint from a node to an array of target nodes.
template<typename T >
T * addClusteredConstraint (ArrayRef< CAGAnchorNode *> anchors)
void enumerateImpliedConnections (std::function< void(CAGAnchorNode *from, CAGAnchorNode *to)> callback)
Enumerates all implied connections in the slice.
unsigned propagate (const TargetConfiguration &config)
Performs one round of propagation, returning the number of nodes propagates.
Detailed Description
A slice of a CAG (which may be the whole graph).
Definition at line 245 of file ConstraintAnalysisGraph.h.
Member Typedef Documentation
const_iterator
using mlir::quantizer::CAGSlice::const_iterator = node_vector::const_iterator
Definition at line 252 of file ConstraintAnalysisGraph.h.
iterator
using mlir::quantizer::CAGSlice::iterator = node_vector::iterator
Definition at line 251 of file ConstraintAnalysisGraph.h.
node_vector
using mlir::quantizer::CAGSlice::node_vector = std::vector<CAGNode *>
Definition at line 250 of file ConstraintAnalysisGraph.h.
Constructor & Destructor Documentation
CAGSlice()
CAGSlice::CAGSlice (SolverContext & context)
Definition at line 47 of file ConstraintAnalysisGraph.cpp.
~CAGSlice()
CAGSlice::~CAGSlice ()
Definition at line 48 of file ConstraintAnalysisGraph.cpp.
Member Function Documentation
addClusteredConstraint()
template<typename T > T* mlir::quantizer::CAGSlice::addClusteredConstraint (ArrayRef< CAGAnchorNode *> anchors) inline
Definition at line 293 of file ConstraintAnalysisGraph.h.
References mlir::quantizer::CAGNode::propagate().
addUnidirectionalConstraint()
template<typename T , typename... Args> T* mlir::quantizer::CAGSlice::addUnidirectionalConstraint (CAGAnchorNode * fromAnchor, ArrayRef< CAGAnchorNode *> toAnchors, Args... args) inline
Adds a unidirectional constraint from a node to an array of target nodes.
Definition at line 279 of file ConstraintAnalysisGraph.h.
References mlir::quantizer::CAGNode::addOutgoing().
addUniqueConstraint()
template<typename T , typename... Args> T* mlir::quantizer::CAGSlice::addUniqueConstraint (ArrayRef< CAGAnchorNode *> anchors, Args... args) inline
Adds a relation constraint with incoming 'from' anchors and outgoing 'to' anchors.
Definition at line 268 of file ConstraintAnalysisGraph.h.
begin() [1/2]
iterator mlir::quantizer::CAGSlice::begin () inline
Definition at line 254 of file ConstraintAnalysisGraph.h.
Referenced by llvm::GraphTraits< const mlir::quantizer::CAGSlice * >::nodes_begin().
begin() [2/2]
const_iterator mlir::quantizer::CAGSlice::begin () const inline
Definition at line 256 of file ConstraintAnalysisGraph.h.
end() [1/2]
iterator mlir::quantizer::CAGSlice::end () inline
Definition at line 255 of file ConstraintAnalysisGraph.h.
Referenced by llvm::GraphTraits< const mlir::quantizer::CAGSlice * >::nodes_end().
end() [2/2]
const_iterator mlir::quantizer::CAGSlice::end () const inline
Definition at line 257 of file ConstraintAnalysisGraph.h.
enumerateImpliedConnections()
void CAGSlice::enumerateImpliedConnections (std::function< void(CAGAnchorNode *from, CAGAnchorNode *to)> callback)
Enumerates all implied connections in the slice.
An implied connection is any two nodes that physically refer to the same value in the IR, such as result->operand. Typically this will be modeled with some kind of strong or weak identity constraint such that types propagate. This is usually called when the slice has been fully constructed in order to add final constraints. It is legal for the callback to modify the graph by adding constraints.
Definition at line 89 of file ConstraintAnalysisGraph.cpp.
References mlir::Value::getUses(), and mlir::quantizer::CAGResultAnchor::getValue().
getOperandAnchor()
CAGOperandAnchor * CAGSlice::getOperandAnchor (Operation * op, unsigned operandIdx)
Gets an operand anchor node.
Definition at line 50 of file ConstraintAnalysisGraph.cpp.
getResultAnchor()
CAGResultAnchor * CAGSlice::getResultAnchor (Operation * op, unsigned resultIdx)
Gets a result anchor node.
Definition at line 70 of file ConstraintAnalysisGraph.cpp.
propagate()
unsigned CAGSlice::propagate (const TargetConfiguration & config)
Performs one round of propagation, returning the number of nodes propagates.
If returns > 0, then additional propagate() rounds are required.
Definition at line 113 of file ConstraintAnalysisGraph.cpp.
References mlir::quantizer::CAGNode::isDirty().
Referenced by validateTypeConversion().
The documentation for this class was generated from the following files:
include/mlir/Quantizer/Support/ConstraintAnalysisGraph.h
lib/Quantizer/Support/ConstraintAnalysisGraph.cpp