MLIR: mlir::SymbolRefAttr Class Reference
mlir::SymbolRefAttr Class Reference
A symbol reference attribute represents a symbolic reference to another operation.
#include "mlir/IR/Attributes.h"
Public Member Functions
StringRef getRootReference () const
Returns the name of the top level symbol reference, i.e.
StringRef getLeafReference () const
Returns the name of the fully resolved symbol, i.e.
ArrayRef< FlatSymbolRefAttr > getNestedReferences () const
Returns the set of nested references representing the path to the symbol nested under the root reference.
Static Public Member Functions
static FlatSymbolRefAttr get (StringRef value, MLIRContext *ctx)
Construct a symbol reference for the given value name.
static SymbolRefAttr get (StringRef value, ArrayRef< FlatSymbolRefAttr > references, MLIRContext *ctx)
Construct a symbol reference for the given value name, and a set of nested references that are further resolve to a nested symbol.
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
A symbol reference attribute represents a symbolic reference to another operation.
Definition at line 464 of file Attributes.h.
Member Function Documentation
get() [1/2]
FlatSymbolRefAttr SymbolRefAttr::get (StringRef value, MLIRContext * ctx) static
Construct a symbol reference for the given value name.
Definition at line 241 of file Attributes.cpp.
References mlir::StandardTypes::None, and mlir::StandardAttributes::SymbolRef.
Referenced by mlir::FlatSymbolRefAttr::classof(), collectSymbolScopes(), collectValidReferencesFor(), extractSymbolReference(), generateNewRefAttr(), mlir::FlatSymbolRefAttr::get(), getInterfaceVariables(), mlir::Builder::getSymbolRefAttr(), and replaceAllSymbolUsesImpl().
get() [2/2]
SymbolRefAttr SymbolRefAttr::get (StringRef value, ArrayRef< FlatSymbolRefAttr > references, MLIRContext * ctx) static
Construct a symbol reference for the given value name, and a set of nested references that are further resolve to a nested symbol.
Definition at line 246 of file Attributes.cpp.
References mlir::StandardAttributes::SymbolRef.
getLeafReference()
StringRef SymbolRefAttr::getLeafReference () const
Returns the name of the fully resolved symbol, i.e.
the leaf of the reference path.
Definition at line 254 of file Attributes.cpp.
Referenced by mlir::SymbolTable::lookupSymbolIn().
getNestedReferences()
ArrayRef< FlatSymbolRefAttr > SymbolRefAttr::getNestedReferences () const
Returns the set of nested references representing the path to the symbol nested under the root reference.
Definition at line 259 of file Attributes.cpp.
Referenced by mlir::FlatSymbolRefAttr::classof(), generateNewRefAttr(), isReferencePrefixOf(), mlir::SymbolTable::lookupSymbolIn(), and replaceAllSymbolUsesImpl().
getRootReference()
StringRef SymbolRefAttr::getRootReference () const
Returns the name of the top level symbol reference, i.e.
the root of the reference path.
Definition at line 252 of file Attributes.cpp.
Referenced by generateNewRefAttr(), isReferencePrefixOf(), mlir::SymbolTable::lookupSymbolIn(), and replaceAllSymbolUsesImpl().
kindof()
static bool mlir::SymbolRefAttr::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 492 of file Attributes.h.
References mlir::StandardAttributes::SymbolRef.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp