MLIR: mlir::DenseElementsAttr::BoolElementIterator Class Reference
mlir::DenseElementsAttr::BoolElementIterator Class Reference
A utility iterator that allows walking over the internal bool values.
#include "mlir/IR/Attributes.h"
Public Member Functions
bool operator* () const
Accesses the bool value at this iterator position.
Public Member Functions inherited from mlir::indexed_accessor_iterator< BoolElementIterator, DenseIterPtrAndSplat, bool, bool, bool >
ptrdiff_t operator- (const indexed_accessor_iterator &rhs) const
bool operator== (const indexed_accessor_iterator &rhs) const
bool operator< (const indexed_accessor_iterator &rhs) const
BoolElementIterator & operator+= (ptrdiff_t offset)
BoolElementIterator & operator-= (ptrdiff_t offset)
ptrdiff_t getIndex () const
Returns the current index of the iterator.
const DenseIterPtrAndSplat & getBase () const
Returns the current base of the iterator.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::DenseElementIndexedIteratorImpl< BoolElementIterator, bool, bool, bool >
DenseElementIndexedIteratorImpl (const char *data, bool isSplat, size_t dataIndex)
ptrdiff_t getDataIndex () const
Return the current index for this iterator, adjusted for the case of a splat.
const char * getData () const
Return the data base pointer.
Protected Member Functions inherited from mlir::indexed_accessor_iterator< BoolElementIterator, DenseIterPtrAndSplat, bool, bool, bool >
indexed_accessor_iterator (DenseIterPtrAndSplat base, ptrdiff_t index)
Protected Attributes inherited from mlir::indexed_accessor_iterator< BoolElementIterator, DenseIterPtrAndSplat, bool, bool, bool >
DenseIterPtrAndSplat base
ptrdiff_t index
Detailed Description
A utility iterator that allows walking over the internal bool values.
Definition at line 766 of file Attributes.h.
Member Function Documentation
operator*()
bool DenseElementsAttr::BoolElementIterator::operator* (void) const
Accesses the bool value at this iterator position.
Definition at line 544 of file Attributes.cpp.
References getBit(), getDenseElementBitwidth(), mlir::DenseElementsAttr::getRawData(), and mlir::DenseElementsAttr::isSplat().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp