MLIR: mlir::AffineExpr Class Reference
mlir::AffineExpr Class Reference
Base type for affine expression.
#include "mlir/IR/AffineExpr.h"
Public Types
using ImplType = detail::AffineExprStorage
Public Member Functions
constexpr AffineExpr ()
AffineExpr (const ImplType *expr)
bool operator== (AffineExpr other) const
bool operator!= (AffineExpr other) const
bool operator== (int64_t v) const
bool operator!= (int64_t v) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
MLIRContext * getContext () const
AffineExprKind getKind () const
Return the classification for this type.
void print (raw_ostream &os) const
void dump () const
bool isSymbolicOrConstant () const
Returns true if this expression is made out of only symbols and constants, i.e., it does not involve dimensional identifiers.
bool isPureAffine () const
Returns true if this is a pure affine expression, i.e., multiplication, floordiv, ceildiv, and mod is only allowed w.r.t constants.
int64_t getLargestKnownDivisor () const
Returns the greatest known integral divisor of this affine expression.
bool isMultipleOf (int64_t factor) const
Return true if the affine expression is a multiple of 'factor'.
bool isFunctionOfDim (unsigned position) const
Return true if the affine expression involves AffineDimExpr position.
void walk (std::function< void(AffineExpr)> callback) const
Walk all of the AffineExpr's in this expression in postorder.
AffineExpr replaceDimsAndSymbols (ArrayRef< AffineExpr > dimReplacements, ArrayRef< AffineExpr > symReplacements) const
This method substitutes any uses of dimensions and symbols (e.g.
AffineExpr operator+ (int64_t v) const
AffineExpr operator+ (AffineExpr other) const
AffineExpr operator- () const
AffineExpr operator- (int64_t v) const
AffineExpr operator- (AffineExpr other) const
AffineExpr operator* (int64_t v) const
AffineExpr operator* (AffineExpr other) const
AffineExpr floorDiv (uint64_t v) const
AffineExpr floorDiv (AffineExpr other) const
AffineExpr ceilDiv (uint64_t v) const
AffineExpr ceilDiv (AffineExpr other) const
AffineExpr operator% (uint64_t v) const
AffineExpr operator% (AffineExpr other) const
AffineExpr compose (AffineMap map) const
Compose with an AffineMap.
Protected Attributes
ImplType * expr
Friends
::llvm::hash_code hash_value (AffineExpr arg)
Make AffineExpr hashable.
Detailed Description
Base type for affine expression.
AffineExpr's are immutable value types with intuitive operators to operate on chainable, lightweight compositions. An AffineExpr is an interface to the underlying storage type pointer.
Definition at line 66 of file AffineExpr.h.
Member Typedef Documentation
ImplType
using mlir::AffineExpr::ImplType = detail::AffineExprStorage
Definition at line 68 of file AffineExpr.h.
Constructor & Destructor Documentation
AffineExpr() [1/2]
constexpr mlir::AffineExpr::AffineExpr () inline
Definition at line 70 of file AffineExpr.h.
AffineExpr() [2/2]
mlir::AffineExpr::AffineExpr (const ImplType * expr) inline
Definition at line 71 of file AffineExpr.h.
Member Function Documentation
cast()
template<typename U > U mlir::AffineExpr::cast () const
Definition at line 241 of file AffineExpr.h.
References mlir::getFlattenedAffineExpr(), mlir::getFlattenedAffineExprs(), mlir::functional::map(), and mlir::simplifyAffineExpr().
Referenced by getDimMap(), mlir::edsc::ops::linalg_conv_nhwc(), mlir::edsc::ops::linalg_dilated_conv_nhwc(), makeTiledLoopRanges(), printDenseFloatElement(), mlir::AffineExprVisitor< SimpleAffineExprFlattener >::visit(), and mlir::AffineExprVisitor< SimpleAffineExprFlattener >::walkPostOrder().
ceilDiv() [1/2]
AffineExpr AffineExpr::ceilDiv (uint64_t v) const
Definition at line 520 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), and getContext().
Referenced by mlir::buildTripCountMapAndOperands(), mlir::edsc::op::ceilDiv(), mlir::getAffineBinaryOpExpr(), and simplifyCeilDiv().
ceilDiv() [2/2]
AffineExpr AffineExpr::ceilDiv (AffineExpr other) const
Definition at line 523 of file AffineExpr.cpp.
References mlir::CeilDiv, mlir::StorageUniquer::get(), mlir::MLIRContext::getAffineUniquer(), getContext(), and simplifyCeilDiv().
compose()
AffineExpr AffineExpr::compose (AffineMap map) const
Compose with an AffineMap.
Returns the composition of this AffineExpr with map.
Prerequisites: this and map are composable, i.e. that the number of AffineDimExpr of this is smaller than the number of results of map. If a result of a map does not have a corresponding AffineDimExpr, that result simply does not appear in the produced AffineExpr.
Example: expr: d0 + d2 map: (d0, d1, d2)[s0, s1] -> (d0 + s1, d1 + s0, d0 + d1 + d2) returned expr: d0 * 2 + d1 + d2 + s1
Definition at line 579 of file AffineExpr.cpp.
References mlir::AffineMap::getResults(), and replaceDimsAndSymbols().
Referenced by mlir::AffineMap::compose().
dump()
void AffineExpr::dump () const
Definition at line 2162 of file AsmPrinter.cpp.
References print().
dyn_cast()
template<typename U > U mlir::AffineExpr::dyn_cast () const
Definition at line 233 of file AffineExpr.h.
Referenced by canonicalizeMapOrSetAndOperands(), computeReshapeCollapsedType(), emitLoopRanges(), extractStrides(), extractStridesFromTerm(), getConstDifference(), getMaxDimIndex(), getMaxPosOfType(), mlir::getStridesAndOffset(), mlir::inversePermutation(), isContiguousAccess(), mlir::AffineMap::isProjectedPermutation(), printBound(), printDenseFloatElement(), simplifyAdd(), simplifyCeilDiv(), simplifyFloorDiv(), simplifyMod(), simplifyMul(), and verifyPermutationMap().
dyn_cast_or_null()
template<typename U > U mlir::AffineExpr::dyn_cast_or_null () const
Definition at line 238 of file AffineExpr.h.
floorDiv() [1/2]
AffineExpr AffineExpr::floorDiv (uint64_t v) const
Definition at line 477 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), and getContext().
Referenced by mlir::edsc::op::floorDiv(), mlir::getAffineBinaryOpExpr(), and simplifyFloorDiv().
floorDiv() [2/2]
AffineExpr AffineExpr::floorDiv (AffineExpr other) const
Definition at line 480 of file AffineExpr.cpp.
References mlir::FloorDiv, mlir::StorageUniquer::get(), mlir::MLIRContext::getAffineUniquer(), getContext(), and simplifyFloorDiv().
getContext()
MLIRContext * AffineExpr::getContext () const
Definition at line 21 of file AffineExpr.cpp.
Referenced by ceilDiv(), mlir::detail::AffineBinaryOpExprStorage::construct(), floorDiv(), mlir::IntegerSetAttr::get(), mlir::getStridesAndOffset(), operator%(), operator*(), operator+(), operator-(), operator==(), mlir::MutableAffineMap::reset(), simplifyAdd(), mlir::simplifyAffineExpr(), simplifyCeilDiv(), simplifyFloorDiv(), simplifyMod(), simplifyMul(), mlir::SDBMExpr::tryConvertAffineExpr(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), and mlir::SimpleAffineExprFlattener::visitModExpr().
getKind()
AffineExprKind AffineExpr::getKind () const
Return the classification for this type.
Definition at line 23 of file AffineExpr.cpp.
Referenced by makeTiledLoopRanges(), printDenseFloatElement(), simplifyAdd(), simplifyMul(), mlir::AffineExprVisitor< SimpleAffineExprFlattener >::visit(), and mlir::AffineExprVisitor< SimpleAffineExprFlattener >::walkPostOrder().
getLargestKnownDivisor()
int64_t AffineExpr::getLargestKnownDivisor () const
Returns the greatest known integral divisor of this affine expression.
The result is always positive.
Definition at line 154 of file AffineExpr.cpp.
References mlir::Add, mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::FloorDiv, getLargestKnownDivisor(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineBinaryOpExpr::getRHS(), mlir::Mod, mlir::Mul, and mlir::SymbolId.
Referenced by getLargestKnownDivisor(), isMultipleOf(), simplifyFloorDiv(), and simplifyMod().
isa()
template<typename U > bool mlir::AffineExpr::isa () const
Definition at line 223 of file AffineExpr.h.
References mlir::Constant, mlir::DimId, mlir::LAST_AFFINE_BINARY_OP, and mlir::SymbolId.
Referenced by simplifyAdd(), simplifyMul(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), mlir::SimpleAffineExprFlattener::visitModExpr(), and mlir::SimpleAffineExprFlattener::visitMulExpr().
isFunctionOfDim()
bool AffineExpr::isFunctionOfDim (unsigned position) const
Return true if the affine expression involves AffineDimExpr position.
Definition at line 216 of file AffineExpr.cpp.
References mlir::DimId, and mlir::getAffineDimExpr().
Referenced by mlir::AffineValueMap::isFunctionOf().
isMultipleOf()
bool AffineExpr::isMultipleOf (int64_t factor) const
Return true if the affine expression is a multiple of 'factor'.
Definition at line 182 of file AffineExpr.cpp.
References mlir::Add, mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::FloorDiv, getLargestKnownDivisor(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineBinaryOpExpr::getRHS(), mlir::Mod, mlir::Mul, and mlir::SymbolId.
isPureAffine()
bool AffineExpr::isPureAffine () const
Returns true if this is a pure affine expression, i.e., multiplication, floordiv, ceildiv, and mod is only allowed w.r.t constants.
Definition at line 123 of file AffineExpr.cpp.
References mlir::Add, mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::FloorDiv, mlir::Mod, mlir::Mul, and mlir::SymbolId.
Referenced by getFlattenedAffineExprs(), and mlir::simplifyAffineExpr().
isSymbolicOrConstant()
bool AffineExpr::isSymbolicOrConstant () const
Returns true if this expression is made out of only symbols and constants, i.e., it does not involve dimensional identifiers.
Returns true if this expression is made out of only symbols and constants (no dimensional identifiers).
Definition at line 99 of file AffineExpr.cpp.
References mlir::Add, mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::FloorDiv, mlir::Mod, mlir::Mul, and mlir::SymbolId.
Referenced by simplifyAdd(), and simplifyMul().
operator bool()
mlir::AffineExpr::operator bool () const inline explicit
Definition at line 78 of file AffineExpr.h.
operator!()
bool mlir::AffineExpr::operator! () const inline
Definition at line 80 of file AffineExpr.h.
References mlir::ceilDiv(), mlir::floorDiv(), mlir::hash_value(), mlir::functional::map(), mlir::edsc::op::operator%(), mlir::operator*(), mlir::operator+(), mlir::operator-(), and print().
operator!=() [1/2]
bool mlir::AffineExpr::operator!= (AffineExpr other) const inline
Definition at line 75 of file AffineExpr.h.
References mlir::operator==().
operator!=() [2/2]
bool mlir::AffineExpr::operator!= (int64_t v) const inline
Definition at line 77 of file AffineExpr.h.
operator%() [1/2]
AffineExpr AffineExpr::operator% (uint64_t v) const
Definition at line 567 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), and getContext().
operator%() [2/2]
AffineExpr AffineExpr::operator% (AffineExpr other) const
Definition at line 570 of file AffineExpr.cpp.
References mlir::StorageUniquer::get(), mlir::MLIRContext::getAffineUniquer(), getContext(), mlir::Mod, and simplifyMod().
operator*() [1/2]
AffineExpr AffineExpr::operator* (int64_t v) const
Definition at line 411 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), and getContext().
operator*() [2/2]
AffineExpr AffineExpr::operator* (AffineExpr other) const
Definition at line 414 of file AffineExpr.cpp.
References mlir::StorageUniquer::get(), mlir::MLIRContext::getAffineUniquer(), getContext(), mlir::Mul, and simplifyMul().
operator+() [1/2]
AffineExpr AffineExpr::operator+ (int64_t v) const
Definition at line 351 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), and getContext().
operator+() [2/2]
AffineExpr AffineExpr::operator+ (AffineExpr other) const
Definition at line 354 of file AffineExpr.cpp.
References mlir::Add, mlir::StorageUniquer::get(), mlir::MLIRContext::getAffineUniquer(), getContext(), and simplifyAdd().
operator-() [1/3]
AffineExpr AffineExpr::operator- () const
Definition at line 424 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), and getContext().
operator-() [2/3]
AffineExpr AffineExpr::operator- (int64_t v) const
Definition at line 429 of file AffineExpr.cpp.
operator-() [3/3]
AffineExpr AffineExpr::operator- (AffineExpr other) const
Definition at line 430 of file AffineExpr.cpp.
operator==() [1/2]
bool mlir::AffineExpr::operator== (AffineExpr other) const inline
Definition at line 74 of file AffineExpr.h.
References expr.
operator==() [2/2]
bool AffineExpr::operator== (int64_t v) const
Definition at line 273 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), and getContext().
print()
void AffineExpr::print (raw_ostream & os) const
Definition at line 2154 of file AsmPrinter.cpp.
Referenced by mlir::operator<<().
replaceDimsAndSymbols()
AffineExpr AffineExpr::replaceDimsAndSymbols (ArrayRef< AffineExpr > dimReplacements, ArrayRef< AffineExpr > symReplacements) const
This method substitutes any uses of dimensions and symbols (e.g.
dim#0 with dimReplacements[0]) and returns the modified expression tree.
Definition at line 64 of file AffineExpr.cpp.
References mlir::Add, mlir::CeilDiv, mlir::Constant, mlir::DimId, mlir::FloorDiv, mlir::getAffineBinaryOpExpr(), mlir::Mod, mlir::Mul, and mlir::SymbolId.
Referenced by compose(), and mlir::AffineMap::replaceDimsAndSymbols().
walk()
void AffineExpr::walk (std::function< void(AffineExpr)> callback) const
Walk all of the AffineExpr's in this expression in postorder.
Walk all of the AffineExprs in this subgraph in postorder.
Definition at line 28 of file AffineExpr.cpp.
Referenced by mlir::AffineMap::walkExprs().
Friends And Related Function Documentation
hash_value
::llvm::hash_code hash_value (AffineExpr arg) friend
Make AffineExpr hashable.
Definition at line 195 of file AffineExpr.h.
Member Data Documentation
expr
ImplType* mlir::AffineExpr::expr protected
Definition at line 153 of file AffineExpr.h.
Referenced by mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineDimExpr::getPosition(), mlir::AffineSymbolExpr::getPosition(), mlir::AffineBinaryOpExpr::getRHS(), mlir::AffineConstantExpr::getValue(), mlir::hash_value(), operator==(), and mlir::toAffineExpr().
The documentation for this class was generated from the following files:
include/mlir/IR/AffineExpr.h
lib/IR/AffineExpr.cpp
lib/IR/AsmPrinter.cpp