MLIR: mlir::VulkanLayoutUtils Class Reference
mlir::VulkanLayoutUtils Class Reference
According to the Vulkan spec "14.5.4. Offset and Stride Assignment": "There are different alignment requirements depending on the specific resources and on the features enabled on the device.
#include "mlir/Dialect/SPIRV/LayoutUtils.h"
Public Types
using Size = uint64_t
Static Public Member Functions
static spirv::StructType decorateType (spirv::StructType structType, Size &size, Size &alignment)
Returns a new StructType with layout info.
static bool isLegalType (Type type)
Checks whether a type is legal in terms of Vulkan layout info decoration.
Detailed Description
According to the Vulkan spec "14.5.4. Offset and Stride Assignment": "There are different alignment requirements depending on the specific resources and on the features enabled on the device.
"
There are 3 types of alignment: scalar, base, extended. See the spec for details.
Note: Even if scalar alignment is supported, it is generally more performant to use the base alignment. So here the calculation is based on base alignment.
The memory layout must obey the following rules:
The Offset decoration of any member must be a multiple of its alignment.
Any ArrayStride or MatrixStride decoration must be a multiple of the alignment of the array or matrix as defined above.
According to the SPIR-V spec: "The ArrayStride, MatrixStride, and Offset decorations must be large enough to hold the size of the objects they affect (that is, specifying overlap is invalid)."
Definition at line 46 of file LayoutUtils.h.
Member Typedef Documentation
Size
using mlir::VulkanLayoutUtils::Size = uint64_t
Definition at line 48 of file LayoutUtils.h.
Member Function Documentation
decorateType()
spirv::StructType VulkanLayoutUtils::decorateType (spirv::StructType structType, VulkanLayoutUtils::Size & size, VulkanLayoutUtils::Size & alignment) static
Returns a new StructType with layout info.
Assigns the type size in bytes to the size. Assigns the type alignment in bytes to the alignment.
Definition at line 20 of file LayoutUtils.cpp.
References mlir::spirv::TypeKind::Array, mlir::Type::cast(), mlir::spirv::ArrayType::get(), mlir::spirv::StructType::get(), mlir::VectorType::get(), mlir::spirv::ArrayType::getElementType(), mlir::spirv::StructType::getElementType(), mlir::Type::getIntOrFloatBitWidth(), mlir::Type::getKind(), mlir::spirv::StructType::getMemberDecorations(), mlir::spirv::ArrayType::getNumElements(), mlir::spirv::StructType::getNumElements(), mlir::spirv::SPIRVDialect::isValidScalarType(), mlir::spirv::TypeKind::Struct, and mlir::StandardTypes::Vector.
Referenced by createGlobalVariableForArg().
isLegalType()
bool VulkanLayoutUtils::isLegalType (Type type) static
Checks whether a type is legal in terms of Vulkan layout info decoration.
A type is dynamically illegal if it's a composite type in the StorageBuffer, PhysicalStorageBuffer, Uniform, and PushConstant Storage Classes without layout information.
Definition at line 135 of file LayoutUtils.cpp.
References mlir::Type::dyn_cast(), mlir::spirv::PointerType::getStorageClass(), and mlir::spirv::StructType::hasLayout().
Referenced by populateSPIRVLayoutInfoPatterns().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/LayoutUtils.h
lib/Dialect/SPIRV/LayoutUtils.cpp