MLIR: mlir::tblgen::CombinedPred Class Reference
mlir::tblgen::CombinedPred Class Reference
#include "mlir/TableGen/Predicate.h"
Public Member Functions
CombinedPred (const llvm::Record *record)
CombinedPred (const llvm::Init *init)
std::string getConditionImpl () const
const llvm::Record * getCombinerDef () const
const std::vector< llvm::Record * > getChildren () const
Public Member Functions inherited from mlir::tblgen::Pred
Pred ()
Pred (const llvm::Record *record)
Pred (const llvm::Init *init)
bool isNull () const
std::string getCondition () const
bool isCombined () const
bool operator== (const Pred &other) const
ArrayRef< llvm::SMLoc > getLoc () const
Additional Inherited Members
Protected Attributes inherited from mlir::tblgen::Pred
const llvm::Record * def
Detailed Description
Definition at line 81 of file Predicate.h.
Constructor & Destructor Documentation
CombinedPred() [1/2]
tblgen::CombinedPred::CombinedPred (const llvm::Record * record) explicit
Definition at line 66 of file Predicate.cpp.
References mlir::tblgen::Pred::def.
CombinedPred() [2/2]
tblgen::CombinedPred::CombinedPred (const llvm::Init * init) explicit
Definition at line 71 of file Predicate.cpp.
References mlir::tblgen::Pred::def.
Member Function Documentation
getChildren()
const std::vector< llvm::Record * > tblgen::CombinedPred::getChildren () const
Definition at line 81 of file Predicate.cpp.
References mlir::tblgen::Pred::def.
getCombinerDef()
const llvm::Record * tblgen::CombinedPred::getCombinerDef () const
Definition at line 76 of file Predicate.cpp.
References mlir::tblgen::Pred::def.
getConditionImpl()
std::string tblgen::CombinedPred::getConditionImpl () const
Definition at line 340 of file Predicate.cpp.
References buildPredicateTree(), getCombinedCondition(), and propagateGroundTruth().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Predicate.h
lib/TableGen/Predicate.cpp