MLIR: mlir::DenseFPElementsAttr Class Reference
mlir::DenseFPElementsAttr Class Reference
An attribute that represents a reference to a dense float vector or tensor object.
#include "mlir/IR/Attributes.h"
Public Types
using iterator = DenseElementsAttr::FloatElementIterator
Public Types inherited from mlir::DenseElementsAttr
template<typename T >
using DerivedAttributeElementIterator = llvm::mapped_iterator< AttributeElementIterator, T(*)(Attribute)>
Return the held element values a range of T, where T is a derived attribute type.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
DenseElementsAttr mapValues (Type newElementType, function_ref< APInt(const APFloat &)> mapping) const
Generates a new DenseElementsAttr by mapping each value attribute, and constructing the DenseElementsAttr given the new element type.
iterator begin () const
Iterator access to the float element values.
iterator end () const
Public Member Functions inherited from mlir::DenseElementsAttr
bool isSplat () const
Returns if this attribute corresponds to a splat, i.e.
Attribute getSplatValue () const
Return the splat value for this attribute.
template<typename T >
std::enable_if<!std::is_base_of< Attribute, T >::value||std::is_same< Attribute, T >::value, T >::type getSplatValue () const
template<typename T >
std::enable_if< std::is_base_of< Attribute, T >::value &&!std::is_same< Attribute, T >::value, T >::type getSplatValue () const
Return the splat value for derived attribute element types.
Attribute getValue (ArrayRef< uint64_t > index) const
Return the value at the given index.
template<typename T >
T getValue (ArrayRef< uint64_t > index) const
template<typename T , typename = typename std::enable_if< (!std::is_same<T, bool>::value && std::numeric_limits<T>::is_integer) || llvm::is_one_of<T, float, double>::value>::type>
llvm::iterator_range< ElementIterator< T > > getValues () const
Return the held element values as a range of integer or floating-point values.
llvm::iterator_range< AttributeElementIterator > getAttributeValues () const
Return the held element values as a range of Attributes.
template<typename T , typename = typename std::enable_if< std::is_same<T, Attribute>::value>::type>
llvm::iterator_range< AttributeElementIterator > getValues () const
AttributeElementIterator attr_value_begin () const
AttributeElementIterator attr_value_end () const
template<typename T , typename = typename std::enable_if< std::is_base_of<Attribute, T>::value && !std::is_same<Attribute, T>::value>::type>
llvm::iterator_range< DerivedAttributeElementIterator< T > > getValues () const
llvm::iterator_range< BoolElementIterator > getBoolValues () const
Return the held element values as a range of bool.
template<typename T , typename = typename std::enable_if< std::is_same<T, bool>::value>::type>
llvm::iterator_range< BoolElementIterator > getValues () const
llvm::iterator_range< IntElementIterator > getIntValues () const
Return the held element values as a range of APInts.
template<typename T , typename = typename std::enable_if< std::is_same<T, APInt>::value>::type>
llvm::iterator_range< IntElementIterator > getValues () const
IntElementIterator int_value_begin () const
IntElementIterator int_value_end () const
llvm::iterator_range< FloatElementIterator > getFloatValues () const
Return the held element values as a range of APFloat.
template<typename T , typename = typename std::enable_if< std::is_same<T, APFloat>::value>::type>
llvm::iterator_range< FloatElementIterator > getValues () const
FloatElementIterator float_value_begin () const
FloatElementIterator float_value_end () const
DenseElementsAttr reshape (ShapedType newType)
Return a new DenseElementsAttr that has the same data as the current attribute, but has been reshaped to 'newType'.
DenseElementsAttr mapValues (Type newElementType, function_ref< APInt(const APInt &)> mapping) const
Generates a new DenseElementsAttr by mapping each int value to a new underlying APInt.
DenseElementsAttr mapValues (Type newElementType, function_ref< APInt(const APFloat &)> mapping) const
Generates a new DenseElementsAttr by mapping each float value to a new underlying APInt.
Static Public Member Functions
template<typename Arg >
static DenseFPElementsAttr get (const ShapedType &type, Arg &&arg)
Get an instance of a DenseFPElementsAttr with the given arguments.
template<typename T >
static DenseFPElementsAttr get (const ShapedType &type, const std::initializer_list< T > &list)
static bool classof (Attribute attr)
Method for supporting type inquiry through isa, cast and dyn_cast.
Static Public Member Functions inherited from mlir::DenseElementsAttr
static bool classof (Attribute attr)
Method for support type inquiry through isa, cast and dyn_cast.
static DenseElementsAttr get (ShapedType type, ArrayRef< Attribute > values)
Constructs a dense elements attribute from an array of element values.
template<typename T , typename = typename std::enable_if< std::numeric_limits<T>::is_integer || llvm::is_one_of<T, float, double>::value>::type>
static DenseElementsAttr get (const ShapedType &type, ArrayRef< T > values)
Constructs a dense integer elements attribute from an array of integer or floating-point values.
template<typename T , typename = typename std::enable_if< std::numeric_limits<T>::is_integer || llvm::is_one_of<T, float, double>::value>::type>
static DenseElementsAttr get (const ShapedType &type, T value)
Constructs a dense integer elements attribute from a single element.
static DenseElementsAttr get (ShapedType type, ArrayRef< bool > values)
Overload of the above 'get' method that is specialized for boolean values.
static DenseElementsAttr get (ShapedType type, ArrayRef< APInt > values)
Constructs a dense integer elements attribute from an array of APInt values.
static DenseElementsAttr get (ShapedType type, ArrayRef< APFloat > values)
Constructs a dense float elements attribute from an array of APFloat values.
template<typename T >
static DenseElementsAttr get (const ShapedType &type, const std::initializer_list< T > &list)
Construct a dense elements attribute for an initializer_list of values.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::DenseElementsAttr
ArrayRef< char > getRawData () const
Return the raw storage data held by this attribute.
IntElementIterator raw_int_begin () const
Get iterators to the raw APInt values for each element in this attribute.
IntElementIterator raw_int_end () const
bool isValidIntOrFloat (int64_t dataEltSize, bool isInt) const
Check the information for a c++ data type, check if this type is valid for the current attribute.
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::DenseElementsAttr
static DenseElementsAttr getRaw (ShapedType type, ArrayRef< APInt > values)
Constructs a dense elements attribute from an array of raw APInt values.
static DenseElementsAttr getRaw (ShapedType type, ArrayRef< char > data, bool isSplat)
Get or create a new dense elements attribute instance with the given raw data buffer.
static DenseElementsAttr getRawIntOrFloat (ShapedType type, ArrayRef< char > data, int64_t dataEltSize, bool isInt)
Overload of the raw 'get' method that asserts that the given type is of integer or floating-point type.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
An attribute that represents a reference to a dense float vector or tensor object.
Each element is stored as a double.
Definition at line 984 of file Attributes.h.
Member Typedef Documentation
iterator
using mlir::DenseFPElementsAttr::iterator = DenseElementsAttr::FloatElementIterator
Definition at line 986 of file Attributes.h.
Member Function Documentation
begin()
iterator mlir::DenseFPElementsAttr::begin () const inline
Iterator access to the float element values.
Definition at line 1011 of file Attributes.h.
Referenced by convertDenseFPElementsAttr().
classof()
bool DenseFPElementsAttr::classof (Attribute attr) static
Method for supporting type inquiry through isa, cast and dyn_cast.
Definition at line 885 of file Attributes.cpp.
References mlir::Type::cast(), getElementType(), mlir::Attribute::getType(), mlir::Attribute::isa(), and mlir::Type::isa().
end()
iterator mlir::DenseFPElementsAttr::end () const inline
Definition at line 1012 of file Attributes.h.
get() [1/2]
template<typename Arg > static DenseFPElementsAttr mlir::DenseFPElementsAttr::get (const ShapedType & type, Arg && arg) inline static
Get an instance of a DenseFPElementsAttr with the given arguments.
This simply wraps the DenseElementsAttr::get calls.
Definition at line 993 of file Attributes.h.
References mlir::DenseElementsAttr::get().
get() [2/2]
template<typename T > static DenseFPElementsAttr mlir::DenseFPElementsAttr::get (const ShapedType & type, const std::initializer_list< T > & list) inline static
Definition at line 998 of file Attributes.h.
References mlir::DenseElementsAttr::get().
mapValues()
DenseElementsAttr DenseFPElementsAttr::mapValues (Type newElementType, function_ref< APInt(const APFloat &)> mapping) const
Generates a new DenseElementsAttr by mapping each value attribute, and constructing the DenseElementsAttr given the new element type.
Definition at line 875 of file Attributes.cpp.
References mlir::AttributeStorage::getType(), and mappingHelper().
Referenced by mlir::quant::UniformQuantizedPerAxisValueConverter::convert().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp