MLIR: mlir::tblgen::Attribute Class Reference
mlir::tblgen::Attribute Class Reference
#include "mlir/TableGen/Attribute.h"
Public Member Functions
Attribute (const llvm::Record *record)
Attribute (const llvm::DefInit *init)
StringRef getStorageType () const
StringRef getReturnType () const
StringRef getConvertFromStorageCall () const
bool isConstBuildable () const
StringRef getConstBuilderTemplate () const
Attribute getBaseAttr () const
bool hasDefaultValue () const
StringRef getDefaultValue () const
bool isOptional () const
bool isDerivedAttr () const
bool isTypeAttr () const
bool isEnumAttr () const
StringRef getAttrDefName () const
StringRef getDerivedCodeBody () const
Public Member Functions inherited from mlir::tblgen::AttrConstraint
AttrConstraint (const llvm::Record *record)
bool isSubClassOf (StringRef className) const
Public Member Functions inherited from mlir::tblgen::Constraint
Constraint (const llvm::Record *record)
bool operator== (const Constraint &that)
bool operator!= (const Constraint &that)
Pred getPredicate () const
std::string getConditionTemplate () const
StringRef getDescription () const
Kind getKind () const
Additional Inherited Members
Public Types inherited from mlir::tblgen::Constraint
enum Kind { CK_Attr, CK_Region, CK_Type, CK_Uncategorized }
Static Public Member Functions inherited from mlir::tblgen::AttrConstraint
static bool classof (const Constraint *c)
Protected Member Functions inherited from mlir::tblgen::Constraint
Constraint (Kind kind, const llvm::Record *record)
Protected Attributes inherited from mlir::tblgen::Constraint
const llvm::Record * def
Detailed Description
Definition at line 45 of file Attribute.h.
Constructor & Destructor Documentation
Attribute() [1/2]
mlir::tblgen::Attribute::Attribute (const llvm::Record * record) explicit
Referenced by mlir::tblgen::AttrConstraint::isSubClassOf().
Attribute() [2/2]
mlir::tblgen::Attribute::Attribute (const llvm::DefInit * init) explicit
Member Function Documentation
getAttrDefName()
StringRef tblgen::Attribute::getAttrDefName () const
Definition at line 115 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getBaseAttr()
tblgen::Attribute tblgen::Attribute::getBaseAttr () const
Definition at line 93 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getBaseAttr().
Referenced by getBaseAttr().
getConstBuilderTemplate()
StringRef tblgen::Attribute::getConstBuilderTemplate () const
Definition at line 88 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getConvertFromStorageCall()
StringRef tblgen::Attribute::getConvertFromStorageCall () const
Definition at line 78 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getDefaultValue()
StringRef tblgen::Attribute::getDefaultValue () const
Definition at line 106 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getDerivedCodeBody()
StringRef tblgen::Attribute::getDerivedCodeBody () const
Definition at line 122 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getReturnType()
StringRef tblgen::Attribute::getReturnType () const
Definition at line 73 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
getStorageType()
StringRef tblgen::Attribute::getStorageType () const
Definition at line 65 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
Referenced by mlir::tblgen::SymbolInfoMap::SymbolInfo::getVarDecl().
hasDefaultValue()
bool tblgen::Attribute::hasDefaultValue () const
Definition at line 101 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
isConstBuildable()
bool tblgen::Attribute::isConstBuildable () const
Definition at line 83 of file Attribute.cpp.
References mlir::tblgen::Constraint::def, and getValueAsString().
isDerivedAttr()
bool tblgen::Attribute::isDerivedAttr () const
Definition at line 53 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
isEnumAttr()
bool tblgen::Attribute::isEnumAttr () const
Definition at line 61 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
isOptional()
bool tblgen::Attribute::isOptional () const
Definition at line 111 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
isTypeAttr()
bool tblgen::Attribute::isTypeAttr () const
Definition at line 57 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Attribute.h
lib/TableGen/Attribute.cpp