MLIR: mlir::edsc::LoopRangeBuilder Class Reference
mlir::edsc::LoopRangeBuilder Class Reference
A LoopRangeBuilder is a generic NestedBuilder for loop.for operations.
#include "mlir/Dialect/Linalg/EDSC/Builders.h"
Public Member Functions
LoopRangeBuilder (ValueHandle *iv, ValueHandle range)
Constructs a new loop.for and captures the associated induction variable.
LoopRangeBuilder (ValueHandle *iv, Value range)
LoopRangeBuilder (ValueHandle *iv, SubViewOp::Range range)
LoopRangeBuilder (const LoopRangeBuilder &)=delete
LoopRangeBuilder (LoopRangeBuilder &&)=default
LoopRangeBuilder & operator= (const LoopRangeBuilder &)=delete
LoopRangeBuilder & operator= (LoopRangeBuilder &&)=default
ValueHandle operator() (std::function< void(void)> fun=nullptr)
The only purpose of this operator is to serve as a sequence point so that the evaluation of fun (which build IR snippets in a scoped fashion) is scoped within a LoopRangeBuilder.
Additional Inherited Members
Protected Member Functions inherited from mlir::edsc::NestedBuilder
NestedBuilder ()=default
NestedBuilder (const NestedBuilder &)=delete
NestedBuilder (NestedBuilder &&other)
NestedBuilder & operator= (const NestedBuilder &)=delete
NestedBuilder & operator= (NestedBuilder &&other)
void enter (mlir::Block *block, int prev=0)
Enter an mlir::Block and setup a ScopedContext to insert operations at the end of it.
void exit ()
Exit the current mlir::Block by explicitly deleting the dynamically allocated OpBuilder and ScopedContext.
~NestedBuilder ()
Custom destructor does nothing because we already destroyed bodyScope manually in exit.
Detailed Description
A LoopRangeBuilder is a generic NestedBuilder for loop.for operations.
More specifically it is meant to be used as a temporary object for representing any nested MLIR construct that is "related to" an mlir::Value (for now an induction variable).
Definition at line 32 of file Builders.h.
Constructor & Destructor Documentation
LoopRangeBuilder() [1/5]
mlir::edsc::LoopRangeBuilder::LoopRangeBuilder (ValueHandle * iv, ValueHandle range)
Constructs a new loop.for and captures the associated induction variable.
A ValueHandle pointer is passed as the first argument and is the only way to capture the loop induction variable.
Definition at line 25 of file Builders.cpp.
References mlir::Value::getDefiningOp(), mlir::edsc::ValueHandle::getType(), and mlir::edsc::ValueHandle::getValue().
LoopRangeBuilder() [2/5]
mlir::edsc::LoopRangeBuilder::LoopRangeBuilder (ValueHandle * iv, Value range)
LoopRangeBuilder() [3/5]
mlir::edsc::LoopRangeBuilder::LoopRangeBuilder (ValueHandle * iv, SubViewOp::Range range)
Definition at line 40 of file Builders.cpp.
References operator()().
LoopRangeBuilder() [4/5]
mlir::edsc::LoopRangeBuilder::LoopRangeBuilder (const LoopRangeBuilder &) delete
LoopRangeBuilder() [5/5]
mlir::edsc::LoopRangeBuilder::LoopRangeBuilder (LoopRangeBuilder &&) default
Member Function Documentation
operator()()
ValueHandle mlir::edsc::LoopRangeBuilder::operator() (std::function< void(void)> fun = nullptr)
The only purpose of this operator is to serve as a sequence point so that the evaluation of fun (which build IR snippets in a scoped fashion) is scoped within a LoopRangeBuilder.
Definition at line 50 of file Builders.cpp.
References mlir::edsc::ValueHandle::null().
Referenced by LoopRangeBuilder().
operator=() [1/2]
LoopRangeBuilder& mlir::edsc::LoopRangeBuilder::operator= (const LoopRangeBuilder &) delete
operator=() [2/2]
LoopRangeBuilder& mlir::edsc::LoopRangeBuilder::operator= (LoopRangeBuilder &&) default
The documentation for this class was generated from the following files:
include/mlir/Dialect/Linalg/EDSC/Builders.h
lib/Dialect/Linalg/EDSC/Builders.cpp