MLIR: mlir::FlatSymbolRefAttr Class Reference
mlir::FlatSymbolRefAttr Class Reference
A symbol reference with a reference path containing a single element.
#include "mlir/IR/Attributes.h"
Public Types
using ValueType = StringRef
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
StringRef getValue () const
Returns the name of the held symbol reference.
Public Member Functions inherited from mlir::SymbolRefAttr
StringRef getRootReference () const
Returns the name of the top level symbol reference, i.e.
StringRef getLeafReference () const
Returns the name of the fully resolved symbol, i.e.
ArrayRef< FlatSymbolRefAttr > getNestedReferences () const
Returns the set of nested references representing the path to the symbol nested under the root reference.
Static Public Member Functions
static FlatSymbolRefAttr get (StringRef value, MLIRContext *ctx)
Construct a symbol reference for the given value name.
static bool classof (Attribute attr)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::SymbolRefAttr
static FlatSymbolRefAttr get (StringRef value, MLIRContext *ctx)
Construct a symbol reference for the given value name.
static SymbolRefAttr get (StringRef value, ArrayRef< FlatSymbolRefAttr > references, MLIRContext *ctx)
Construct a symbol reference for the given value name, and a set of nested references that are further resolve to a nested symbol.
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
A symbol reference with a reference path containing a single element.
This is used to refer to an operation within the current symbol table.
Definition at line 492 of file Attributes.h.
Member Typedef Documentation
ValueType
using mlir::FlatSymbolRefAttr::ValueType = StringRef
Definition at line 495 of file Attributes.h.
Member Function Documentation
classof()
static bool mlir::FlatSymbolRefAttr::classof (Attribute attr) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 506 of file Attributes.h.
References mlir::Attribute::dyn_cast(), mlir::SymbolRefAttr::get(), and mlir::SymbolRefAttr::getNestedReferences().
get()
static FlatSymbolRefAttr mlir::FlatSymbolRefAttr::get (StringRef value, MLIRContext * ctx) inline static
Construct a symbol reference for the given value name.
Definition at line 498 of file Attributes.h.
References mlir::SymbolRefAttr::get().
Referenced by collectValidReferencesFor(), and replaceAllSymbolUsesImpl().
getValue()
StringRef mlir::FlatSymbolRefAttr::getValue () const inline
Returns the name of the held symbol reference.
Definition at line 503 of file Attributes.h.
Referenced by getLastStructuredControlFlowOpMergeBlock(), and getLibraryCallSymbolRef().
The documentation for this class was generated from the following file:
include/mlir/IR/Attributes.h