MLIR: mlir::SDBMSymbolExpr Class Reference
mlir::SDBMSymbolExpr Class Reference
SDBM symbol expression.
#include "mlir/Dialect/SDBM/SDBMExpr.h"
Public Types
using ImplType = detail::SDBMTermExprStorage
Public Types inherited from mlir::SDBMInputExpr
using ImplType = detail::SDBMTermExprStorage
Public Types inherited from mlir::SDBMVaryingExpr
using ImplType = detail::SDBMExprStorage
Public Types inherited from mlir::SDBMExpr
using ImplType = detail::SDBMExprStorage
Static Public Member Functions
static SDBMSymbolExpr get (SDBMDialect *dialect, unsigned position)
Obtain or create a symbol expression unique'ed in the given dialect (which belongs to a context).
static bool isClassFor (const SDBMExpr &expr)
Static Public Member Functions inherited from mlir::SDBMInputExpr
static bool isClassFor (const SDBMExpr &expr)
Static Public Member Functions inherited from mlir::SDBMTermExpr
static bool isClassFor (const SDBMExpr &expr)
Static Public Member Functions inherited from mlir::SDBMDirectExpr
static bool isClassFor (const SDBMExpr &expr)
Static Public Member Functions inherited from mlir::SDBMVaryingExpr
static bool isClassFor (const SDBMExpr &expr)
Static Public Member Functions inherited from mlir::SDBMExpr
static Optional< SDBMExpr > tryConvertAffineExpr (AffineExpr affine)
Try constructing an SDBM expression from the given affine expression.
Additional Inherited Members
Public Member Functions inherited from mlir::SDBMInputExpr
unsigned getPosition () const
Public Member Functions inherited from mlir::SDBMDirectExpr
SDBMTermExpr getTerm ()
If this is a sum expression, return its variable part, otherwise return self.
int64_t getConstant ()
If this is a sum expression, return its constant part, otherwise return 0.
Public Member Functions inherited from mlir::SDBMExpr
SDBMExpr ()
SDBMExpr (ImplType *expr)
SDBMExpr (const SDBMExpr &)=default
SDBM expressions are thin wrappers around a unique'ed immutable pointer, which makes them trivially assignable and trivially copyable.
SDBMExpr & operator= (const SDBMExpr &)=default
bool operator== (const SDBMExpr &other) const
SDBM expressions can be compared straight-forwardly.
bool operator!= (const SDBMExpr &other) const
operator bool () const
SDBM expressions are convertible to bool: null expressions are converted to false, non-null expressions are converted to true.
bool operator! () const
SDBMExpr operator- ()
Negate the given SDBM expression.
void print (raw_ostream &os) const
Prints the SDBM expression.
void dump () const
template<typename U >
bool isa () const
LLVM-style casts.
template<typename U >
U dyn_cast () const
template<typename U >
U cast () const
::llvm::hash_code hash_value () const
Support for LLVM hashing.
SDBMExprKind getKind () const
Returns the kind of the SDBM expression.
MLIRContext * getContext () const
Returns the MLIR context in which this expression lives.
SDBMDialect * getDialect () const
Returns the SDBM dialect instance.
AffineExpr getAsAffineExpr () const
Convert the SDBM expression into an Affine expression.
Protected Attributes inherited from mlir::SDBMExpr
ImplType * impl
Detailed Description
SDBM symbol expression.
Symbols correspond to symbolic constants when defining functions using SDBM expressions.
Definition at line 324 of file SDBMExpr.h.
Member Typedef Documentation
ImplType
using mlir::SDBMSymbolExpr::ImplType = detail::SDBMTermExprStorage
Definition at line 326 of file SDBMExpr.h.
Member Function Documentation
get()
SDBMSymbolExpr SDBMSymbolExpr::get (SDBMDialect * dialect, unsigned position) static
Obtain or create a symbol expression unique'ed in the given dialect (which belongs to a context).
Definition at line 618 of file SDBMExpr.cpp.
References mlir::StorageUniquer::get(), mlir::SDBMDialect::getUniquer(), and mlir::SymbolId.
Referenced by mlir::SDBM::getSDBMExpressions(), and mlir::SDBMExpr::tryConvertAffineExpr().
isClassFor()
static bool mlir::SDBMSymbolExpr::isClassFor (const SDBMExpr & expr) inline static
Definition at line 333 of file SDBMExpr.h.
References mlir::SDBMExpr::getKind(), and mlir::SymbolId.
The documentation for this class was generated from the following files:
include/mlir/Dialect/SDBM/SDBMExpr.h
lib/Dialect/SDBM/SDBMExpr.cpp