MLIR: mlir::SourceMgrDiagnosticHandler Class Reference
mlir::SourceMgrDiagnosticHandler Class Reference
This class is a utility diagnostic handler for use with llvm::SourceMgr.
#include "mlir/IR/Diagnostics.h"
Public Member Functions
SourceMgrDiagnosticHandler (llvm::SourceMgr &mgr, MLIRContext *ctx, raw_ostream &os)
SourceMgrDiagnosticHandler (llvm::SourceMgr &mgr, MLIRContext *ctx)
~SourceMgrDiagnosticHandler ()
void emitDiagnostic (Location loc, Twine message, DiagnosticSeverity kind)
Emit the given diagnostic information with the held source manager.
Public Member Functions inherited from mlir::ScopedDiagnosticHandler
ScopedDiagnosticHandler (MLIRContext *ctx)
template<typename FuncTy >
ScopedDiagnosticHandler (MLIRContext *ctx, FuncTy &&handler)
~ScopedDiagnosticHandler ()
Protected Member Functions
void emitDiagnostic (Diagnostic &diag)
Emit the given diagnostic with the held source manager.
const llvm::MemoryBuffer * getBufferForFile (StringRef filename)
Get a memory buffer for the given file, or nullptr if no file is available.
Protected Member Functions inherited from mlir::ScopedDiagnosticHandler
template<typename FuncTy >
void setHandler (FuncTy &&handler)
Set the handler to manage via RAII.
Protected Attributes
llvm::SourceMgr & mgr
The source manager that we are wrapping.
raw_ostream & os
The output stream to use when printing diagnostics.
Detailed Description
This class is a utility diagnostic handler for use with llvm::SourceMgr.
Definition at line 542 of file Diagnostics.h.
Constructor & Destructor Documentation
SourceMgrDiagnosticHandler() [1/2]
SourceMgrDiagnosticHandler::SourceMgrDiagnosticHandler (llvm::SourceMgr & mgr, MLIRContext * ctx, raw_ostream & os)
Definition at line 396 of file Diagnostics.cpp.
References diag(), emitDiagnostic(), and mlir::ScopedDiagnosticHandler::setHandler().
SourceMgrDiagnosticHandler() [2/2]
SourceMgrDiagnosticHandler::SourceMgrDiagnosticHandler (llvm::SourceMgr & mgr, MLIRContext * ctx)
Definition at line 404 of file Diagnostics.cpp.
~SourceMgrDiagnosticHandler()
SourceMgrDiagnosticHandler::~SourceMgrDiagnosticHandler ()
Definition at line 408 of file Diagnostics.cpp.
Member Function Documentation
emitDiagnostic() [1/2]
void SourceMgrDiagnosticHandler::emitDiagnostic (Location loc, Twine message, DiagnosticSeverity kind)
Emit the given diagnostic information with the held source manager.
Definition at line 410 of file Diagnostics.cpp.
References diag(), getDiagKind(), getFileLineColLoc(), mlir::Location::isa(), mgr, and os.
Referenced by emitDiagnostic(), SourceMgrDiagnosticHandler(), and mlir::SourceMgrDiagnosticVerifierHandler::verify().
emitDiagnostic() [2/2]
void SourceMgrDiagnosticHandler::emitDiagnostic (Diagnostic & diag) protected
Emit the given diagnostic with the held source manager.
Definition at line 438 of file Diagnostics.cpp.
References mlir::Location::dyn_cast(), emitDiagnostic(), mlir::Diagnostic::getLocation(), mlir::Diagnostic::getNotes(), mlir::Diagnostic::getSeverity(), mlir::Note, and mlir::Diagnostic::str().
getBufferForFile()
const llvm::MemoryBuffer * SourceMgrDiagnosticHandler::getBufferForFile (StringRef filename) protected
Get a memory buffer for the given file, or nullptr if no file is available.
Get a memory buffer for the given file, or nullptr if one is not found.
Definition at line 464 of file Diagnostics.cpp.
References mlir::FileLineColLoc::getColumn(), mlir::FileLineColLoc::getFilename(), mlir::FileLineColLoc::getLine(), and mgr.
Referenced by mlir::SourceMgrDiagnosticVerifierHandler::verify().
Member Data Documentation
mgr
llvm::SourceMgr& mlir::SourceMgrDiagnosticHandler::mgr protected
The source manager that we are wrapping.
Definition at line 561 of file Diagnostics.h.
Referenced by emitDiagnostic(), getBufferForFile(), mlir::SourceMgrDiagnosticVerifierHandler::SourceMgrDiagnosticVerifierHandler(), and mlir::SourceMgrDiagnosticVerifierHandler::verify().
os
raw_ostream& mlir::SourceMgrDiagnosticHandler::os protected
The output stream to use when printing diagnostics.
Definition at line 564 of file Diagnostics.h.
Referenced by emitDiagnostic(), and mlir::SourceMgrDiagnosticVerifierHandler::verify().
The documentation for this class was generated from the following files:
include/mlir/IR/Diagnostics.h
lib/IR/Diagnostics.cpp