MLIR: mlir::MemRefDescriptor Class Reference
mlir::MemRefDescriptor Class Reference
Helper class to produce LLVM dialect operations extracting or inserting elements of a MemRef descriptor.
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
Public Member Functions
MemRefDescriptor (Value descriptor)
Construct a helper for the given descriptor value.
Value allocatedPtr (OpBuilder &builder, Location loc)
Builds IR extracting the allocated pointer from the descriptor.
void setAllocatedPtr (OpBuilder &builder, Location loc, Value ptr)
Builds IR inserting the allocated pointer into the descriptor.
Value alignedPtr (OpBuilder &builder, Location loc)
Builds IR extracting the aligned pointer from the descriptor.
void setAlignedPtr (OpBuilder &builder, Location loc, Value ptr)
Builds IR inserting the aligned pointer into the descriptor.
Value offset (OpBuilder &builder, Location loc)
Builds IR extracting the offset from the descriptor.
void setOffset (OpBuilder &builder, Location loc, Value offset)
Builds IR inserting the offset into the descriptor.
void setConstantOffset (OpBuilder &builder, Location loc, uint64_t offset)
Builds IR inserting the offset into the descriptor.
Value size (OpBuilder &builder, Location loc, unsigned pos)
Builds IR extracting the pos-th size from the descriptor.
void setSize (OpBuilder &builder, Location loc, unsigned pos, Value size)
Builds IR inserting the pos-th size into the descriptor.
void setConstantSize (OpBuilder &builder, Location loc, unsigned pos, uint64_t size)
Builds IR inserting the pos-th size into the descriptor.
Value stride (OpBuilder &builder, Location loc, unsigned pos)
Builds IR extracting the pos-th size from the descriptor.
void setStride (OpBuilder &builder, Location loc, unsigned pos, Value stride)
Builds IR inserting the pos-th stride into the descriptor.
void setConstantStride (OpBuilder &builder, Location loc, unsigned pos, uint64_t stride)
Builds IR inserting the pos-th stride into the descriptor.
LLVM::LLVMType getElementType ()
Returns the (LLVM) type this descriptor points to.
Public Member Functions inherited from mlir::StructBuilder
StructBuilder (Value v)
Construct a helper for the given value.
operator Value ()
Static Public Member Functions
static MemRefDescriptor undef (OpBuilder &builder, Location loc, Type descriptorType)
Builds IR creating an undef value of the descriptor type.
static MemRefDescriptor fromStaticShape (OpBuilder &builder, Location loc, LLVMTypeConverter &typeConverter, MemRefType type, Value memory)
Builds IR creating a MemRef descriptor that represents type and populates it with static shape and stride information extracted from the type.
Static Public Member Functions inherited from mlir::StructBuilder
static StructBuilder undef (OpBuilder &builder, Location loc, Type descriptorType)
Builds IR creating an undef value of the descriptor type.
Additional Inherited Members
Protected Member Functions inherited from mlir::StructBuilder
Value extractPtr (OpBuilder &builder, Location loc, unsigned pos)
Builds IR to extract a value from the struct at position pos.
void setPtr (OpBuilder &builder, Location loc, unsigned pos, Value ptr)
Builds IR to set a value in the struct at position pos.
Protected Attributes inherited from mlir::StructBuilder
Value value
Type structType
Detailed Description
Helper class to produce LLVM dialect operations extracting or inserting elements of a MemRef descriptor.
Wraps a Value pointing to the descriptor. The Value may be null, in which case none of the operations are valid.
Definition at line 155 of file ConvertStandardToLLVM.h.
Constructor & Destructor Documentation
MemRefDescriptor()
MemRefDescriptor::MemRefDescriptor (Value descriptor) explicit
Construct a helper for the given descriptor value.
Definition at line 272 of file ConvertStandardToLLVM.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::StructBuilder::value.
Referenced by undef().
Member Function Documentation
alignedPtr()
Value MemRefDescriptor::alignedPtr (OpBuilder & builder, Location loc)
Builds IR extracting the aligned pointer from the descriptor.
Definition at line 330 of file ConvertStandardToLLVM.cpp.
References mlir::StructBuilder::extractPtr().
Referenced by getI64SubArray(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
allocatedPtr()
Value MemRefDescriptor::allocatedPtr (OpBuilder & builder, Location loc)
Builds IR extracting the allocated pointer from the descriptor.
Definition at line 319 of file ConvertStandardToLLVM.cpp.
References mlir::StructBuilder::extractPtr().
Referenced by getI64SubArray().
fromStaticShape()
MemRefDescriptor MemRefDescriptor::fromStaticShape (OpBuilder & builder, Location loc, LLVMTypeConverter & typeConverter, MemRefType type, Value memory) static
Builds IR creating a MemRef descriptor that represents type and populates it with static shape and stride information extracted from the type.
Definition at line 292 of file ConvertStandardToLLVM.cpp.
References mlir::LLVMTypeConverter::convertType(), mlir::MemRefType::getAffineMaps(), and undef().
getElementType()
LLVM::LLVMType MemRefDescriptor::getElementType ()
Returns the (LLVM) type this descriptor points to.
Definition at line 414 of file ConvertStandardToLLVM.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::StructBuilder::value.
Referenced by mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
offset()
Value MemRefDescriptor::offset (OpBuilder & builder, Location loc)
Builds IR extracting the offset from the descriptor.
Definition at line 349 of file ConvertStandardToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), and mlir::StructBuilder::value.
Referenced by mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), and setOffset().
setAlignedPtr()
void MemRefDescriptor::setAlignedPtr (OpBuilder & builder, Location loc, Value ptr)
Builds IR inserting the aligned pointer into the descriptor.
Definition at line 335 of file ConvertStandardToLLVM.cpp.
References mlir::StructBuilder::setPtr().
setAllocatedPtr()
void MemRefDescriptor::setAllocatedPtr (OpBuilder & builder, Location loc, Value ptr)
Builds IR inserting the allocated pointer into the descriptor.
Definition at line 324 of file ConvertStandardToLLVM.cpp.
References mlir::StructBuilder::setPtr().
setConstantOffset()
void MemRefDescriptor::setConstantOffset (OpBuilder & builder, Location loc, uint64_t offset)
Builds IR inserting the offset into the descriptor.
Definition at line 364 of file ConvertStandardToLLVM.cpp.
References createIndexAttrConstant(), and setOffset().
setConstantSize()
void MemRefDescriptor::setConstantSize (OpBuilder & builder, Location loc, unsigned pos, uint64_t size)
Builds IR inserting the pos-th size into the descriptor.
Definition at line 386 of file ConvertStandardToLLVM.cpp.
References createIndexAttrConstant(), and setSize().
setConstantStride()
void MemRefDescriptor::setConstantStride (OpBuilder & builder, Location loc, unsigned pos, uint64_t stride)
Builds IR inserting the pos-th stride into the descriptor.
Definition at line 408 of file ConvertStandardToLLVM.cpp.
References createIndexAttrConstant(), and setStride().
setOffset()
void MemRefDescriptor::setOffset (OpBuilder & builder, Location loc, Value offset)
Builds IR inserting the offset into the descriptor.
Definition at line 356 of file ConvertStandardToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), offset(), mlir::StructBuilder::structType, and mlir::StructBuilder::value.
Referenced by setConstantOffset().
setSize()
void MemRefDescriptor::setSize (OpBuilder & builder, Location loc, unsigned pos, Value size)
Builds IR inserting the pos-th size into the descriptor.
Definition at line 378 of file ConvertStandardToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), kSizePosInMemRefDescriptor, size(), mlir::StructBuilder::structType, and mlir::StructBuilder::value.
Referenced by setConstantSize().
setStride()
void MemRefDescriptor::setStride (OpBuilder & builder, Location loc, unsigned pos, Value stride)
Builds IR inserting the pos-th stride into the descriptor.
Definition at line 400 of file ConvertStandardToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), kStridePosInMemRefDescriptor, stride(), mlir::StructBuilder::structType, and mlir::StructBuilder::value.
Referenced by setConstantStride().
size()
Value MemRefDescriptor::size (OpBuilder & builder, Location loc, unsigned pos)
Builds IR extracting the pos-th size from the descriptor.
Definition at line 371 of file ConvertStandardToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), kSizePosInMemRefDescriptor, and mlir::StructBuilder::value.
Referenced by setSize().
stride()
Value MemRefDescriptor::stride (OpBuilder & builder, Location loc, unsigned pos)
Builds IR extracting the pos-th size from the descriptor.
Definition at line 393 of file ConvertStandardToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), kStridePosInMemRefDescriptor, and mlir::StructBuilder::value.
Referenced by mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), and setStride().
undef()
MemRefDescriptor MemRefDescriptor::undef (OpBuilder & builder, Location loc, Type descriptorType) static
Builds IR creating an undef value of the descriptor type.
Definition at line 280 of file ConvertStandardToLLVM.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), and MemRefDescriptor().
Referenced by convertLinalgType(), fromStaticShape(), getI64SubArray(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
The documentation for this class was generated from the following files:
include/mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h
lib/Conversion/StandardToLLVM/ConvertStandardToLLVM.cpp