MLIR: mlir::edsc::NestedBuilder Class Reference
mlir::edsc::NestedBuilder Class Reference
A NestedBuilder is a scoping abstraction to create an idiomatic syntax embedded in C++ that serves the purpose of building nested MLIR.
#include "mlir/EDSC/Builders.h"
Protected Member Functions
NestedBuilder ()=default
NestedBuilder (const NestedBuilder &)=delete
NestedBuilder (NestedBuilder &&other)
NestedBuilder & operator= (const NestedBuilder &)=delete
NestedBuilder & operator= (NestedBuilder &&other)
void enter (mlir::Block *block, int prev=0)
Enter an mlir::Block and setup a ScopedContext to insert operations at the end of it.
void exit ()
Exit the current mlir::Block by explicitly deleting the dynamically allocated OpBuilder and ScopedContext.
~NestedBuilder ()
Custom destructor does nothing because we already destroyed bodyScope manually in exit.
Detailed Description
A NestedBuilder is a scoping abstraction to create an idiomatic syntax embedded in C++ that serves the purpose of building nested MLIR.
Nesting and compositionality is obtained by using the strict ordering that exists between object construction and method invocation on said object (in our case, the call to operator()). This ordering allows implementing an abstraction that decouples definition from declaration (in a PL sense) on placeholders of type ValueHandle and BlockHandle.
Definition at line 94 of file Builders.h.
Constructor & Destructor Documentation
NestedBuilder() [1/3]
mlir::edsc::NestedBuilder::NestedBuilder () protected default
NestedBuilder() [2/3]
mlir::edsc::NestedBuilder::NestedBuilder (const NestedBuilder &) protected delete
NestedBuilder() [3/3]
mlir::edsc::NestedBuilder::NestedBuilder (NestedBuilder && other) inline protected
Definition at line 98 of file Builders.h.
~NestedBuilder()
mlir::edsc::NestedBuilder::~NestedBuilder () inline protected
Custom destructor does nothing because we already destroyed bodyScope manually in exit.
Insert an assertion to defensively guard against improper usage of scoping.
Definition at line 135 of file Builders.h.
Member Function Documentation
enter()
void mlir::edsc::NestedBuilder::enter (mlir::Block * block, int prev = 0) inline protected
Enter an mlir::Block and setup a ScopedContext to insert operations at the end of it.
Since we cannot use c++ language-level scoping to implement scoping itself, we use enter/exit pairs of operations. As a consequence we must allocate a new OpBuilder + ScopedContext and let the escape. Step back "prev" times from the end of the block to set up the insertion point, which is useful for non-empty blocks.
Definition at line 115 of file Builders.h.
References mlir::Block::end(), mlir::edsc::ScopedContext::getBuilder(), and mlir::edsc::ScopedContext::getLocation().
Referenced by mlir::edsc::LoopBuilder::makeAffine(), and mlir::edsc::LoopBuilder::makeLoop().
exit()
void mlir::edsc::NestedBuilder::exit () inline protected
Exit the current mlir::Block by explicitly deleting the dynamically allocated OpBuilder and ScopedContext.
Definition at line 125 of file Builders.h.
operator=() [1/2]
NestedBuilder& mlir::edsc::NestedBuilder::operator= (const NestedBuilder &) protected delete
operator=() [2/2]
NestedBuilder& mlir::edsc::NestedBuilder::operator= (NestedBuilder && other) inline protected
Definition at line 103 of file Builders.h.
The documentation for this class was generated from the following file:
include/mlir/EDSC/Builders.h