MLIR: mlir::RewritePattern Class Reference
mlir::RewritePattern Class Reference
RewritePattern is the common base class for all DAG to DAG replacements.
#include "mlir/IR/PatternMatch.h"
Public Member Functions
virtual void rewrite (Operation *op, std::unique_ptr< PatternState > state, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified rewriter.
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
PatternMatchResult match (Operation *op) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual PatternMatchResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
OperationName getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
PatternMatchResult matchSuccess (std::unique_ptr< PatternState > state={}) const
This method indicates that a match was found and has the specified cost.
Protected Member Functions
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Protected Attributes
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Additional Inherited Members
Static Public Member Functions inherited from mlir::Pattern
static PatternMatchResult matchFailure ()
This method indicates that no match was found.
Detailed Description
RewritePattern is the common base class for all DAG to DAG replacements.
There are two possible usages of this class:
Multi-step RewritePattern with "match" and "rewrite"
By overloading the "match" and "rewrite" functions, the user can separate the concerns of matching and rewriting.
Single-step RewritePattern with "matchAndRewrite"
By overloading the "matchAndRewrite" function, the user can perform the rewrite in the same call as the match. This removes the need for any PatternState.
Definition at line 142 of file PatternMatch.h.
Constructor & Destructor Documentation
RewritePattern() [1/2]
mlir::RewritePattern::RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext * context) inline protected
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Definition at line 185 of file PatternMatch.h.
RewritePattern() [2/2]
RewritePattern::RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext * context) protected
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
They can also specify the names of operations that may be generated during a successful rewrite.
Definition at line 59 of file PatternMatch.cpp.
References generatedOps.
Member Function Documentation
getGeneratedOps()
ArrayRef<OperationName> mlir::RewritePattern::getGeneratedOps () const inline
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Definition at line 180 of file PatternMatch.h.
Referenced by mlir::ConversionPattern::matchAndRewrite().
match()
PatternMatchResult RewritePattern::match (Operation * op) const override virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
On failure, this returns a None value. On success, it returns a (possibly null) pattern-specific state wrapped in an Optional. This state is passed back into the rewrite function if this match is selected.
Implements mlir::Pattern.
Reimplemented in mlir::OpRewritePattern< SourceOp >.
Definition at line 52 of file PatternMatch.cpp.
matchAndRewrite()
virtual PatternMatchResult mlir::RewritePattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const inline virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented in mlir::OpRewritePattern< SourceOp >, and mlir::ConversionPattern.
Definition at line 169 of file PatternMatch.h.
Referenced by mlir::ConversionPattern::matchAndRewrite().
rewrite() [1/2]
void RewritePattern::rewrite (Operation * op, std::unique_ptr< PatternState > state, PatternRewriter & rewriter) const virtual
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified rewriter.
If an unexpected error is encountered (an internal compiler error), it is emitted through the normal MLIR diagnostic hooks and the IR is left in a valid state.
Reimplemented in mlir::OpRewritePattern< SourceOp >.
Definition at line 42 of file PatternMatch.cpp.
Referenced by mlir::ConversionPattern::matchAndRewrite().
rewrite() [2/2]
void RewritePattern::rewrite (Operation * op, PatternRewriter & rewriter) const virtual
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
If an unexpected error is encountered (an internal compiler error), it is emitted through the normal MLIR diagnostic hooks and the IR is left in a valid state.
Reimplemented in mlir::OpRewritePattern< SourceOp >.
Definition at line 47 of file PatternMatch.cpp.
Member Data Documentation
generatedOps
SmallVector<OperationName, 2> mlir::RewritePattern::generatedOps protected
A list of the potential operations that may be generated when rewriting an op with this pattern.
Definition at line 196 of file PatternMatch.h.
Referenced by RewritePattern().
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp