MLIR: mlir::SDBMVisitor< Derived, Result > Class Template Reference
mlir::SDBMVisitor< Derived, Result > Class Template Reference
A visitor class for SDBM expressions.
#include "mlir/Dialect/SDBM/SDBMExpr.h"
Public Member Functions
Result visit (SDBMExpr expr)
Visit the given SDBM expression, dispatching to kind-specific functions.
void walkPreorder (SDBMExpr expr)
Traverse the SDBM expression tree calling visit on each node in depth-first preorder.
void walkPostorder (SDBMExpr expr)
Traverse the SDBM expression tree calling visit on each node in depth-first postorder.
Protected Member Functions
void visitSum (SDBMSumExpr)
Default visitors do nothing.
void visitDiff (SDBMDiffExpr)
void visitStripe (SDBMStripeExpr)
void visitDim (SDBMDimExpr)
void visitSymbol (SDBMSymbolExpr)
void visitNeg (SDBMNegExpr)
void visitConstant (SDBMConstantExpr)
Result visitDirect (SDBMDirectExpr expr)
Default implementation of visitDirect dispatches to the dedicated for sums or delegates to visitTerm for the other expression kinds.
Result visitTerm (SDBMTermExpr expr)
Default implementation of visitTerm dispatches to the special functions for stripes and other variables.
Result visitInput (SDBMInputExpr expr)
Default implementation of visitInput dispatches to the special functions for dimensions or symbols.
Result visitVarying (SDBMVaryingExpr expr)
Default implementation of visitVarying dispatches to the special functions for variables and negations thereof.
template<bool isPreorder>
void walk (SDBMExpr expr)
Detailed Description
template<typename Derived, typename Result = void>
class mlir::SDBMVisitor< Derived, Result >
A visitor class for SDBM expressions.
Calls the kind-specific function depending on the kind of expression it visits.
Definition at line 357 of file SDBMExpr.h.
Member Function Documentation
visit()
template<typename Derived , typename Result = void> Result mlir::SDBMVisitor< Derived, Result >::visit (SDBMExpr expr) inline
Visit the given SDBM expression, dispatching to kind-specific functions.
Definition at line 360 of file SDBMExpr.h.
References mlir::Add, mlir::SDBMExpr::cast(), mlir::Constant, mlir::Diff, mlir::DimId, mlir::SDBMExpr::getKind(), mlir::Neg, mlir::Stripe, and mlir::SymbolId.
visitConstant()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::visitConstant (SDBMConstantExpr) inline protected
Definition at line 393 of file SDBMExpr.h.
visitDiff()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::visitDiff (SDBMDiffExpr) inline protected
Definition at line 388 of file SDBMExpr.h.
visitDim()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::visitDim (SDBMDimExpr) inline protected
Definition at line 390 of file SDBMExpr.h.
visitDirect()
template<typename Derived , typename Result = void> Result mlir::SDBMVisitor< Derived, Result >::visitDirect (SDBMDirectExpr expr) inline protected
Default implementation of visitDirect dispatches to the dedicated for sums or delegates to visitTerm for the other expression kinds.
Concrete visitors can overload it.
Definition at line 398 of file SDBMExpr.h.
References mlir::SDBMExpr::cast(), and mlir::SDBMExpr::dyn_cast().
visitInput()
template<typename Derived , typename Result = void> Result mlir::SDBMVisitor< Derived, Result >::visitInput (SDBMInputExpr expr) inline protected
Default implementation of visitInput dispatches to the special functions for dimensions or symbols.
Concrete visitors can override it to visit all variables instead.
Definition at line 419 of file SDBMExpr.h.
References mlir::SDBMExpr::cast(), mlir::DimId, and mlir::SDBMExpr::getKind().
visitNeg()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::visitNeg (SDBMNegExpr) inline protected
Definition at line 392 of file SDBMExpr.h.
visitStripe()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::visitStripe (SDBMStripeExpr) inline protected
Definition at line 389 of file SDBMExpr.h.
visitSum()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::visitSum (SDBMSumExpr) inline protected
Default visitors do nothing.
Definition at line 387 of file SDBMExpr.h.
visitSymbol()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::visitSymbol (SDBMSymbolExpr) inline protected
Definition at line 391 of file SDBMExpr.h.
visitTerm()
template<typename Derived , typename Result = void> Result mlir::SDBMVisitor< Derived, Result >::visitTerm (SDBMTermExpr expr) inline protected
Default implementation of visitTerm dispatches to the special functions for stripes and other variables.
Concrete visitors can override it.
Definition at line 408 of file SDBMExpr.h.
References mlir::SDBMExpr::cast(), mlir::SDBMExpr::getKind(), and mlir::Stripe.
visitVarying()
template<typename Derived , typename Result = void> Result mlir::SDBMVisitor< Derived, Result >::visitVarying (SDBMVaryingExpr expr) inline protected
Default implementation of visitVarying dispatches to the special functions for variables and negations thereof.
Concrete visitors can override it to visit all variables and negations instead.
Definition at line 430 of file SDBMExpr.h.
References mlir::SDBMExpr::dyn_cast().
walk()
template<typename Derived , typename Result = void> template<bool isPreorder> void mlir::SDBMVisitor< Derived, Result >::walk (SDBMExpr expr) inline protected
Definition at line 442 of file SDBMExpr.h.
References mlir::SDBMExpr::dyn_cast().
walkPostorder()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::walkPostorder (SDBMExpr expr) inline
Traverse the SDBM expression tree calling visit on each node in depth-first postorder.
Definition at line 383 of file SDBMExpr.h.
walkPreorder()
template<typename Derived , typename Result = void> void mlir::SDBMVisitor< Derived, Result >::walkPreorder (SDBMExpr expr) inline
Traverse the SDBM expression tree calling visit on each node in depth-first preorder.
Definition at line 379 of file SDBMExpr.h.
The documentation for this class was generated from the following file:
include/mlir/Dialect/SDBM/SDBMExpr.h