MLIR: mlir::OpaqueLoc Class Reference
mlir::OpaqueLoc Class Reference
Represents a location that is external to MLIR.
#include "mlir/IR/Location.h"
Public Member Functions
uintptr_t getUnderlyingLocation () const
Returns a pointer to the corresponding object.
ClassID * getClassId () const
Returns a ClassID* that represents the underlying objects c++ type.
Location getFallbackLocation () const
Returns a fallback location.
Static Public Member Functions
template<typename T >
static Location get (T underlyingLocation, MLIRContext *context)
Returns an instance of opaque location which contains a given pointer to an object.
template<typename T >
static Location get (T underlyingLocation, Location fallbackLocation)
Returns an instance of opaque location which contains a given pointer to an object and an additional MLIR location.
template<typename T >
static T getUnderlyingLocation (Location location)
Returns a pointer to some data structure that opaque location stores.
template<typename T >
static T getUnderlyingLocationOrNull (Location location)
Returns a pointer to some data structure that opaque location stores.
template<typename T >
static bool isa (Location location)
Checks whether provided location is opaque location and contains a pointer to an object of particular type.
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents a location that is external to MLIR.
Contains a pointer to some data structure and an optional location that can be used if the first one is not suitable. Since it contains an external structure, only optional location is used during serialization. The class also provides a number of methods for making type-safe casts between a pointer to an object and opaque location.
Definition at line 223 of file Location.h.
Member Function Documentation
get() [1/2]
template<typename T > static Location mlir::OpaqueLoc::get (T underlyingLocation, MLIRContext * context) inline static
Returns an instance of opaque location which contains a given pointer to an object.
The corresponding MLIR location is set to UnknownLoc.
Definition at line 231 of file Location.h.
References mlir::UnknownLoc::get().
Referenced by mlir::NameLoc::getChildLoc().
get() [2/2]
template<typename T > static Location mlir::OpaqueLoc::get (T underlyingLocation, Location fallbackLocation) inline static
Returns an instance of opaque location which contains a given pointer to an object and an additional MLIR location.
Definition at line 239 of file Location.h.
getClassId()
ClassID * OpaqueLoc::getClassId () const
Returns a ClassID* that represents the underlying objects c++ type.
Definition at line 133 of file Location.cpp.
Referenced by isa().
getFallbackLocation()
Location OpaqueLoc::getFallbackLocation () const
Returns a fallback location.
Definition at line 135 of file Location.cpp.
Referenced by mlir::AsmState::~AsmState().
getUnderlyingLocation() [1/2]
template<typename T > static T mlir::OpaqueLoc::getUnderlyingLocation (Location location) inline static
Returns a pointer to some data structure that opaque location stores.
Definition at line 245 of file Location.h.
References mlir::Location::cast().
Referenced by getUnderlyingLocationOrNull().
getUnderlyingLocation() [2/2]
uintptr_t OpaqueLoc::getUnderlyingLocation () const
Returns a pointer to the corresponding object.
Definition at line 129 of file Location.cpp.
getUnderlyingLocationOrNull()
template<typename T > static T mlir::OpaqueLoc::getUnderlyingLocationOrNull (Location location) inline static
Returns a pointer to some data structure that opaque location stores.
Returns nullptr if provided location is not opaque location or if it contains a pointer of different type.
Definition at line 255 of file Location.h.
References mlir::Location::cast(), and getUnderlyingLocation().
isa()
template<typename T > static bool mlir::OpaqueLoc::isa (Location location) inline static
Checks whether provided location is opaque location and contains a pointer to an object of particular type.
Definition at line 264 of file Location.h.
References mlir::Location::dyn_cast(), and getClassId().
kindof()
static bool mlir::OpaqueLoc::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 279 of file Location.h.
References mlir::StandardAttributes::OpaqueLocation.
The documentation for this class was generated from the following files:
include/mlir/IR/Location.h
lib/IR/Location.cpp