MLIR: mlir::spirv::SPIRVConversionTarget Class Reference
mlir::spirv::SPIRVConversionTarget Class Reference
#include "mlir/Dialect/SPIRV/SPIRVLowering.h"
Static Public Member Functions
static std::unique_ptr< SPIRVConversionTarget > get (TargetEnvAttr targetEnv, MLIRContext *context)
Creates a SPIR-V conversion target for the given target environment.
Additional Inherited Members
Public Types inherited from mlir::ConversionTarget
enum LegalizationAction { LegalizationAction::Legal, LegalizationAction::Dynamic, LegalizationAction::Illegal }
This enumeration corresponds to the specific action to take when considering an operation legal for this conversion target.
using DynamicLegalityCallbackFn = std::function< bool(Operation *)>
The signature of the callback used to determine if an operation is dynamically legal on the target.
Public Member Functions inherited from mlir::ConversionTarget
ConversionTarget (MLIRContext &ctx)
virtual ~ConversionTarget ()=default
void setOpAction (OperationName op, LegalizationAction action)
Register a legality action for the given operation.
template<typename OpT >
void setOpAction (LegalizationAction action)
template<typename OpT >
void addLegalOp ()
Register the given operations as legal.
template<typename OpT , typename OpT2 , typename... OpTs>
void addLegalOp ()
template<typename OpT >
void addDynamicallyLegalOp ()
Register the given operation as dynamically legal, i.e.
template<typename OpT , typename OpT2 , typename... OpTs>
void addDynamicallyLegalOp ()
template<typename OpT >
void addDynamicallyLegalOp (const DynamicLegalityCallbackFn &callback)
Register the given operation as dynamically legal and set the dynamic legalization callback to the one provided.
template<typename OpT , typename OpT2 , typename... OpTs>
void addDynamicallyLegalOp (const DynamicLegalityCallbackFn &callback)
template<typename OpT , class Callable >
std::enable_if<!is_invocable< Callable, Operation * >::value >::type addDynamicallyLegalOp (Callable &&callback)
template<typename OpT >
void addIllegalOp ()
Register the given operation as illegal, i.e.
template<typename OpT , typename OpT2 , typename... OpTs>
void addIllegalOp ()
template<typename OpT >
void markOpRecursivelyLegal (const DynamicLegalityCallbackFn &callback={})
Mark an operation, that must have either been set as Legal or DynamicallyLegal, as being recursively legal.
template<typename OpT , typename OpT2 , typename... OpTs>
void markOpRecursivelyLegal (const DynamicLegalityCallbackFn &callback={})
template<typename OpT , class Callable >
std::enable_if<!is_invocable< Callable, Operation * >::value >::type markOpRecursivelyLegal (Callable &&callback)
void setDialectAction (ArrayRef< StringRef > dialectNames, LegalizationAction action)
Register a legality action for the given dialects.
template<typename... Names>
void addLegalDialect (StringRef name, Names... names)
Register the operations of the given dialects as legal.
template<typename... Args>
void addLegalDialect ()
template<typename... Names>
void addDynamicallyLegalDialect (StringRef name, Names... names)
Register the operations of the given dialects as dynamically legal, i.e.
template<typename... Args>
void addDynamicallyLegalDialect (Optional< DynamicLegalityCallbackFn > callback=llvm::None)
void markUnknownOpDynamicallyLegal (const DynamicLegalityCallbackFn &fn)
Register unknown operations as dynamically legal.
void markUnknownOpDynamicallyLegal ()
template<typename... Names>
void addIllegalDialect (StringRef name, Names... names)
Register the operations of the given dialects as illegal, i.e.
template<typename... Args>
void addIllegalDialect ()
Optional< LegalizationAction > getOpAction (OperationName op) const
Get the legality action for the given operation.
Optional< LegalOpDetails > isLegal (Operation *op) const
If the given operation instance is legal on this target, a structure containing legality information is returned.
Protected Member Functions inherited from mlir::ConversionTarget
virtual bool isDynamicallyLegal (Operation *op) const
Runs a custom legalization query for the given operation.
Detailed Description
Definition at line 61 of file SPIRVLowering.h.
Member Function Documentation
get()
std::unique_ptr< spirv::SPIRVConversionTarget > spirv::SPIRVConversionTarget::get (TargetEnvAttr targetEnv, MLIRContext * context) static
Creates a SPIR-V conversion target for the given target environment.
Definition at line 314 of file SPIRVLowering.cpp.
References get(), mlir::spirv::getImpliedExtensions(), mlir::Operation::getName(), mlir::spirv::getRecursiveImpliedCapabilities(), and mlir::StringAttr::getValue().
Referenced by get(), and lowerEntryPointABIAttr().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVLowering.h
lib/Dialect/SPIRV/SPIRVLowering.cpp