MLIR: mlir::FunctionType Class Reference
mlir::FunctionType Class Reference
Function types map from a list of inputs to a list of results.
#include "mlir/IR/Types.h"
Public Member Functions
unsigned getNumInputs () const
Type getInput (unsigned i) const
ArrayRef< Type > getInputs () const
unsigned getNumResults () const
Type getResult (unsigned i) const
ArrayRef< Type > getResults () const
Static Public Member Functions
static FunctionType get (ArrayRef< Type > inputs, ArrayRef< Type > results, MLIRContext *context)
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Function types map from a list of inputs to a list of results.
Definition at line 190 of file Types.h.
Member Function Documentation
get()
FunctionType FunctionType::get (ArrayRef< Type > inputs, ArrayRef< Type > results, MLIRContext * context) static
Definition at line 36 of file Types.cpp.
Referenced by mlir::FuncOp::clone(), mlir::TypeConverter::convertSignatureArg(), mlir::FuncOp::eraseArguments(), mlir::Builder::getFunctionType(), getLibraryCallSymbolRef(), isFnEntryBlock(), makeFunctionType(), outlineKernelFunc(), print(), printAllocaOp(), printCallOp(), printGEPOp(), printNVVMMmaOp(), and verify().
getInput()
Type mlir::FunctionType::getInput (unsigned i) const inline
Definition at line 201 of file Types.h.
Referenced by mlir::FuncOp::clone(), mlir::TypeConverter::convertSignatureArg(), createGlobalVariableForArg(), and verifyFuncArgs().
getInputs()
ArrayRef< Type > FunctionType::getInputs () const
Definition at line 41 of file Types.cpp.
Referenced by mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::SPIRVTypeConverter::convertType(), getLastStructuredControlFlowOpMergeBlock(), mlir::TypeConverter::isSignatureLegal(), lowerEntryPointABIAttr(), parseCallIndirectOp(), parseCallOp(), mlir::FuncOp::print(), printGPUFuncOp(), mlir::FuncOp::verify(), and verify().
getNumInputs()
unsigned mlir::FunctionType::getNumInputs () const inline
Definition at line 199 of file Types.h.
Referenced by mlir::FuncOp::build(), mlir::FuncOp::clone(), mlir::TypeConverter::convertSignatureArg(), mlir::LLVMTypeConverter::getLLVMContext(), lowerEntryPointABIAttr(), parseGPUFuncOp(), printGPUFuncOp(), mlir::FuncOp::setType(), and verifyFuncArgs().
getNumResults()
unsigned FunctionType::getNumResults () const
Definition at line 45 of file Types.cpp.
Referenced by mlir::LLVMTypeConverter::convertFunctionSignature(), getLastStructuredControlFlowOpMergeBlock(), printGPUFuncOp(), mlir::FuncOp::setType(), verify(), and verifyFuncArgs().
getResult()
Type mlir::FunctionType::getResult (unsigned i) const inline
Definition at line 208 of file Types.h.
Referenced by getLastStructuredControlFlowOpMergeBlock(), verify(), and verifyFuncArgsGeneric().
getResults()
ArrayRef< Type > FunctionType::getResults () const
Definition at line 47 of file Types.cpp.
Referenced by mlir::FuncOp::clone(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::TypeConverter::convertSignatureArg(), mlir::FuncOp::getCallableResults(), getLastStructuredControlFlowOpMergeBlock(), mlir::TypeConverter::isSignatureLegal(), parseCallIndirectOp(), parseCallOp(), mlir::FuncOp::print(), printDenseFloatElement(), and printGPUFuncOp().
kindof()
static bool mlir::FunctionType::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 213 of file Types.h.
The documentation for this class was generated from the following files:
include/mlir/IR/Types.h
lib/IR/Types.cpp