MLIR: mlir::BlockAndValueMapping Class Reference
mlir::BlockAndValueMapping Class Reference
#include "mlir/IR/BlockAndValueMapping.h"
Public Member Functions
void map (Block *from, Block *to)
Inserts a new mapping for 'from' to 'to'.
void map (Value from, Value to)
void erase (Block *from)
Erases a mapping for 'from'.
void erase (Value from)
bool contains (Block *from) const
Checks to see if a mapping for 'from' exists.
bool contains (Value from) const
Block * lookupOrNull (Block *from) const
Lookup a mapped value within the map.
Value lookupOrNull (Value from) const
Block * lookupOrDefault (Block *from) const
Lookup a mapped value within the map.
Value lookupOrDefault (Value from) const
template<typename T >
T lookup (T from) const
Lookup a mapped value within the map.
void clear ()
Clears all mappings held by the mapper.
Detailed Description
Definition at line 26 of file BlockAndValueMapping.h.
Member Function Documentation
clear()
void mlir::BlockAndValueMapping::clear () inline
Clears all mappings held by the mapper.
Definition at line 68 of file BlockAndValueMapping.h.
References mlir::Value::getAsOpaquePointer(), and mlir::Value::getFromOpaquePointer().
contains() [1/2]
bool mlir::BlockAndValueMapping::contains (Block * from) const inline
Checks to see if a mapping for 'from' exists.
Definition at line 40 of file BlockAndValueMapping.h.
Referenced by mlir::FuncOp::clone(), mlir::Region::cloneInto(), inlineBeneficiaryOps(), and mlir::inlineRegion().
contains() [2/2]
bool mlir::BlockAndValueMapping::contains (Value from) const inline
Definition at line 41 of file BlockAndValueMapping.h.
References mlir::Value::getAsOpaquePointer().
erase() [1/2]
void mlir::BlockAndValueMapping::erase (Block * from) inline
Erases a mapping for 'from'.
Definition at line 36 of file BlockAndValueMapping.h.
erase() [2/2]
void mlir::BlockAndValueMapping::erase (Value from) inline
Definition at line 37 of file BlockAndValueMapping.h.
References mlir::Value::getAsOpaquePointer().
lookup()
template<typename T > T mlir::BlockAndValueMapping::lookup (T from) const inline
Lookup a mapped value within the map.
This asserts the provided value exists within the map.
Definition at line 61 of file BlockAndValueMapping.h.
References lookupOrNull().
Referenced by mlir::Region::cloneInto(), mlir::ConversionPatternRewriter::cloneRegionBefore(), and emitLoopRanges().
lookupOrDefault() [1/2]
Block* mlir::BlockAndValueMapping::lookupOrDefault (Block * from) const inline
Lookup a mapped value within the map.
If a mapping for the provided value does not exist then return the provided value.
Definition at line 54 of file BlockAndValueMapping.h.
Referenced by mlir::Operation::cloneWithoutRegions().
lookupOrDefault() [2/2]
Value mlir::BlockAndValueMapping::lookupOrDefault (Value from) const inline
Definition at line 57 of file BlockAndValueMapping.h.
lookupOrNull() [1/2]
Block* mlir::BlockAndValueMapping::lookupOrNull (Block * from) const inline
Lookup a mapped value within the map.
If a mapping for the provided value does not exist then return nullptr.
Definition at line 47 of file BlockAndValueMapping.h.
Referenced by mlir::Region::cloneInto(), isFnEntryBlock(), lookup(), and remapInlinedOperands().
lookupOrNull() [2/2]
Value mlir::BlockAndValueMapping::lookupOrNull (Value from) const inline
Definition at line 50 of file BlockAndValueMapping.h.
map() [1/2]
void mlir::BlockAndValueMapping::map (Block * from, Block * to) inline
Inserts a new mapping for 'from' to 'to'.
If there is an existing mapping, it is overwritten.
Definition at line 30 of file BlockAndValueMapping.h.
Referenced by mlir::Region::cloneInto(), mlir::Operation::cloneWithoutRegions(), emitLoopRanges(), generateLoop(), inlineBeneficiaryOps(), mlir::inlineCall(), mlir::inlineRegion(), isFnEntryBlock(), mlir::loopUnrollByFactor(), and mlir::loopUnrollJamByFactor().
map() [2/2]
void mlir::BlockAndValueMapping::map (Value from, Value to) inline
Definition at line 31 of file BlockAndValueMapping.h.
References mlir::Value::getAsOpaquePointer().
The documentation for this class was generated from the following file:
include/mlir/IR/BlockAndValueMapping.h