MLIR: mlir::Dialect Class Reference
mlir::Dialect Class Reference
Dialects are groups of MLIR operations and behavior associated with the entire group.
#include "mlir/IR/Dialect.h"
Classes
class VariadicOperationAdder
class VariadicOperationAdder< First >
struct VariadicSymbolAdder
struct VariadicSymbolAdder< First >
Public Member Functions
virtual ~Dialect ()
MLIRContext * getContext () const
StringRef getNamespace () const
bool allowsUnknownOperations () const
Returns true if this dialect allows for unregistered operations, i.e.
bool allowsUnknownTypes () const
Return true if this dialect allows for unregistered types, i.e., types prefixed with the dialect namespace but not registered with addType.
virtual Operation * materializeConstant (OpBuilder &builder, Attribute value, Type type, Location loc)
Registered hook to materialize a single constant operation from a given attribute value with the desired resultant type.
virtual Attribute parseAttribute (DialectAsmParser &parser, Type type) const
Parse an attribute registered to this dialect.
virtual void printAttribute (Attribute, DialectAsmPrinter &) const
Print an attribute registered to this dialect.
virtual Type parseType (DialectAsmParser &parser) const
Parse a type registered to this dialect.
virtual void printType (Type, DialectAsmPrinter &) const
Print a type registered to this dialect.
virtual LogicalResult verifyRegionArgAttribute (Operation *, unsigned regionIndex, unsigned argIndex, NamedAttribute)
Verify an attribute from this dialect on the argument at 'argIndex' for the region at 'regionIndex' on the given operation.
virtual LogicalResult verifyRegionResultAttribute (Operation *, unsigned regionIndex, unsigned resultIndex, NamedAttribute)
Verify an attribute from this dialect on the result at 'resultIndex' for the region at 'regionIndex' on the given operation.
virtual LogicalResult verifyOperationAttribute (Operation *, NamedAttribute)
Verify an attribute from this dialect on the given operation.
const DialectInterface * getRegisteredInterface (ClassID *interfaceID)
Lookup an interface for the given ID if one is registered, otherwise nullptr.
template<typename InterfaceT >
const InterfaceT * getRegisteredInterface ()
Static Public Member Functions
static bool isValidNamespace (StringRef str)
Utility function that returns if the given string is a valid dialect namespace.
Public Attributes
DialectConstantFoldHook constantFoldHook
Registered fallback constant fold hook for the dialect.
DialectConstantDecodeHook decodeHook
Registered hook to decode opaque constants associated with this dialect.
DialectExtractElementHook extractElementHook
Registered hook to extract an element from an opaque constant associated with this dialect.
Protected Member Functions
Dialect (StringRef name, MLIRContext *context)
The constructor takes a unique namespace for this dialect as well as the context to bind to.
template<typename... Args>
void addOperations ()
This method is used by derived classes to add their operations to the set.
void addOperation (AbstractOperation opInfo)
template<typename... Args>
void addTypes ()
This method is used by derived classes to add their types to the set.
template<typename... Args>
void addAttributes ()
This method is used by derived classes to add their attributes to the set.
void allowUnknownOperations (bool allow=true)
Enable support for unregistered operations.
void allowUnknownTypes (bool allow=true)
Enable support for unregistered types.
void addInterface (std::unique_ptr< DialectInterface > interface)
Register a dialect interface with this dialect instance.
template<typename T , typename T2 , typename... Tys>
void addInterfaces ()
Register a set of dialect interfaces with this dialect instance.
template<typename T >
void addInterfaces ()
Detailed Description
Dialects are groups of MLIR operations and behavior associated with the entire group.
For example, hooks into other systems for constant folding, default named types for asm printing, etc.
Instances of the dialect object are global across all MLIRContext's that may be active in the process.
Definition at line 39 of file Dialect.h.
Constructor & Destructor Documentation
~Dialect()
Dialect::~Dialect () virtual
Definition at line 75 of file Dialect.cpp.
Dialect()
Dialect::Dialect (StringRef name, MLIRContext * context) protected
The constructor takes a unique namespace for this dialect as well as the context to bind to.
Note: The namespace must not contain '.' characters. Note: All operations belonging to this dialect must have names starting with the namespace followed by '.'. Example:
"tf" for the TensorFlow ops like "tf.add".
Definition at line 69 of file Dialect.cpp.
References isValidNamespace().
Referenced by addInterfaces(), and getRegisteredInterface().
Member Function Documentation
addAttributes()
template<typename... Args> void mlir::Dialect::addAttributes () inline protected
This method is used by derived classes to add their attributes to the set.
Definition at line 214 of file Dialect.h.
References mlir::Dialect::VariadicSymbolAdder< First, Rest >::addToSet().
addInterface()
void Dialect::addInterface (std::unique_ptr< DialectInterface > interface) protected
Register a dialect interface with this dialect instance.
Register a set of dialect interfaces with this dialect instance.
Definition at line 126 of file Dialect.cpp.
Referenced by addInterfaces(), and allowUnknownTypes().
addInterfaces() [1/2]
template<typename T , typename T2 , typename... Tys> void mlir::Dialect::addInterfaces () inline protected
Register a set of dialect interfaces with this dialect instance.
Definition at line 245 of file Dialect.h.
addInterfaces() [2/2]
template<typename T > void mlir::Dialect::addInterfaces () inline protected
Definition at line 249 of file Dialect.h.
References addInterface(), Dialect(), and mlir::registerDialect().
addOperation()
void Dialect::addOperation (AbstractOperation opInfo) protected
Definition at line 379 of file MLIRContext.cpp.
References mlir::AbstractOperation::dialect, mlir::MLIRContext::getImpl(), and mlir::AbstractOperation::name.
Referenced by mlir::Dialect::VariadicOperationAdder< First, Rest >::addToSet(), and mlir::Dialect::VariadicOperationAdder< First >::addToSet().
addOperations()
template<typename... Args> void mlir::Dialect::addOperations () inline protected
This method is used by derived classes to add their operations to the set.
Definition at line 183 of file Dialect.h.
References mlir::Dialect::VariadicOperationAdder< First, Rest >::addToSet().
Referenced by mlir::AffineOpsDialect::AffineOpsDialect(), mlir::fxpmath::FxpMathOpsDialect::FxpMathOpsDialect(), mlir::gpu::GPUDialect::GPUDialect(), mlir::linalg::LinalgDialect::LinalgDialect(), mlir::LLVM::LLVMDialect::LLVMDialect(), mlir::loop::LoopOpsDialect::LoopOpsDialect(), mlir::NVVM::NVVMDialect::NVVMDialect(), mlir::quant::QuantizationDialect::QuantizationDialect(), mlir::ROCDL::ROCDLDialect::ROCDLDialect(), mlir::spirv::SPIRVDialect::SPIRVDialect(), mlir::StandardOpsDialect::StandardOpsDialect(), and mlir::vector::VectorOpsDialect::VectorOpsDialect().
addTypes()
template<typename... Args> void mlir::Dialect::addTypes () inline protected
This method is used by derived classes to add their types to the set.
Definition at line 209 of file Dialect.h.
References mlir::Dialect::VariadicSymbolAdder< First, Rest >::addToSet().
Referenced by mlir::quant::QuantizationDialect::QuantizationDialect().
allowsUnknownOperations()
bool mlir::Dialect::allowsUnknownOperations () const inline
Returns true if this dialect allows for unregistered operations, i.e.
operations prefixed with the dialect namespace but not registered with addOperation.
Definition at line 54 of file Dialect.h.
allowsUnknownTypes()
bool mlir::Dialect::allowsUnknownTypes () const inline
Return true if this dialect allows for unregistered types, i.e., types prefixed with the dialect namespace but not registered with addType.
These are represented with OpaqueType.
Definition at line 59 of file Dialect.h.
Referenced by parseType().
allowUnknownOperations()
void mlir::Dialect::allowUnknownOperations (bool allow = true) inline protected
Enable support for unregistered operations.
Definition at line 236 of file Dialect.h.
Referenced by mlir::LLVM::LLVMDialect::LLVMDialect(), mlir::NVVM::NVVMDialect::NVVMDialect(), mlir::ROCDL::ROCDLDialect::ROCDLDialect(), and mlir::spirv::SPIRVDialect::SPIRVDialect().
allowUnknownTypes()
void mlir::Dialect::allowUnknownTypes (bool allow = true) inline protected
Enable support for unregistered types.
Definition at line 239 of file Dialect.h.
References addInterface().
getContext()
MLIRContext* mlir::Dialect::getContext () const inline
Definition at line 47 of file Dialect.h.
Referenced by applyCmpPredicate(), mlir::AffineDmaStartOp::getAffineMapAttrForMemRef(), mlir::AffineDmaWaitOp::getAffineMapAttrForMemRef(), mlir::AffineLoadOp::getAffineMapAttrForMemRef(), mlir::AffineStoreOp::getAffineMapAttrForMemRef(), mlir::LLVM::LLVMType::getArrayElementType(), mlir::SDBMExpr::getContext(), getDimMap(), mlir::LLVM::LLVMType::getFunctionParamType(), mlir::LLVM::LLVMType::getFunctionResultType(), mlir::LLVMTypeConverter::getLLVMContext(), mlir::LLVM::LLVMType::getPointerElementTy(), mlir::LLVM::LLVMType::getStructElementType(), mlir::LLVM::LLVMType::getVectorElementType(), parseRankOp(), parseStructType(), mlir::linalg::LinalgDialect::parseType(), parseType(), mlir::LLVM::LLVMDialect::parseType(), mlir::populateGpuToNVVMConversionPatterns(), mlir::populateVectorToLLVMConversionPatterns(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), and verify().
getNamespace()
StringRef mlir::Dialect::getNamespace () const inline
Definition at line 49 of file Dialect.h.
Referenced by parseAttribute(), and parseType().
getRegisteredInterface() [1/2]
const DialectInterface* mlir::Dialect::getRegisteredInterface (ClassID * interfaceID) inline
Lookup an interface for the given ID if one is registered, otherwise nullptr.
Definition at line 162 of file Dialect.h.
getRegisteredInterface() [2/2]
template<typename InterfaceT > const InterfaceT* mlir::Dialect::getRegisteredInterface () inline
Definition at line 166 of file Dialect.h.
References Dialect().
isValidNamespace()
bool Dialect::isValidNamespace (StringRef str) static
Utility function that returns if the given string is a valid dialect namespace.
Definition at line 118 of file Dialect.cpp.
Referenced by Dialect(), mlir::OpaqueType::verifyConstructionInvariants(), and mlir::OpaqueAttr::verifyConstructionInvariants().
materializeConstant()
virtual Operation* mlir::Dialect::materializeConstant (OpBuilder & builder, Attribute value, Type type, Location loc) inline virtual
Registered hook to materialize a single constant operation from a given attribute value with the desired resultant type.
This method should use the provided builder to create the operation without changing the insertion position. The generated operation is expected to be constant like, i.e. single result, zero operands, non side-effecting, etc. On success, this hook should return the value generated to represent the constant value. Otherwise, it should return null on failure.
Reimplemented in mlir::spirv::SPIRVDialect, mlir::AffineOpsDialect, mlir::StandardOpsDialect, and mlir::vector::VectorOpsDialect.
Definition at line 100 of file Dialect.h.
References parseAttribute().
Referenced by materializeConstant(), and mlir::OpBuilder::tryFold().
parseAttribute()
Attribute Dialect::parseAttribute (DialectAsmParser & parser, Type type) const virtual
Parse an attribute registered to this dialect.
If 'type' is nonnull, it refers to the expected type of the attribute.
Definition at line 96 of file Dialect.cpp.
References mlir::DialectAsmParser::emitError(), mlir::DialectAsmParser::getNameLoc(), and getNamespace().
Referenced by materializeConstant().
parseType()
Type Dialect::parseType (DialectAsmParser & parser) const virtual
Parse a type registered to this dialect.
Reimplemented in mlir::LLVM::LLVMDialect, mlir::spirv::SPIRVDialect, mlir::linalg::LinalgDialect, and mlir::quant::QuantizationDialect.
Definition at line 104 of file Dialect.cpp.
References allowsUnknownTypes(), mlir::DialectAsmParser::emitError(), mlir::Identifier::get(), mlir::OpaqueType::get(), getContext(), mlir::DialectAsmParser::getFullSymbolSpec(), mlir::DialectAsmParser::getNameLoc(), getNamespace(), and mlir::StandardAttributes::Type.
Referenced by printAttribute().
printAttribute()
virtual void mlir::Dialect::printAttribute (Attribute , DialectAsmPrinter &) const inline virtual
Print an attribute registered to this dialect.
Note: The type of the attribute need not be printed by this method as it is always printed by the caller.
Definition at line 116 of file Dialect.h.
References parseType().
printType()
virtual void mlir::Dialect::printType (Type , DialectAsmPrinter &) const inline virtual
Print a type registered to this dialect.
Reimplemented in mlir::LLVM::LLVMDialect, mlir::spirv::SPIRVDialect, mlir::linalg::LinalgDialect, and mlir::quant::QuantizationDialect.
Definition at line 124 of file Dialect.h.
References verifyRegionArgAttribute(), and verifyRegionResultAttribute().
verifyOperationAttribute()
virtual LogicalResult mlir::Dialect::verifyOperationAttribute (Operation * , NamedAttribute) inline virtual
Verify an attribute from this dialect on the given operation.
Returns failure if the verification failed, success otherwise.
Reimplemented in mlir::gpu::GPUDialect, and mlir::spirv::SPIRVDialect.
Definition at line 152 of file Dialect.h.
References mlir::success().
verifyRegionArgAttribute()
LogicalResult Dialect::verifyRegionArgAttribute (Operation * , unsigned regionIndex, unsigned argIndex, NamedAttribute) virtual
Verify an attribute from this dialect on the argument at 'argIndex' for the region at 'regionIndex' on the given operation.
Returns failure if the verification failed, success otherwise. This hook may optionally be invoked from any operation containing a region.
Reimplemented in mlir::LLVM::LLVMDialect, and mlir::spirv::SPIRVDialect.
Definition at line 81 of file Dialect.cpp.
References mlir::success().
Referenced by printType().
verifyRegionResultAttribute()
LogicalResult Dialect::verifyRegionResultAttribute (Operation * , unsigned regionIndex, unsigned resultIndex, NamedAttribute) virtual
Verify an attribute from this dialect on the result at 'resultIndex' for the region at 'regionIndex' on the given operation.
Returns failure if the verification failed, success otherwise. This hook may optionally be invoked from any operation containing a region.
Reimplemented in mlir::spirv::SPIRVDialect.
Definition at line 90 of file Dialect.cpp.
References mlir::success().
Referenced by printType().
Member Data Documentation
constantFoldHook
DialectConstantFoldHook mlir::Dialect::constantFoldHook
Initial value:
=
      [](Operation *op, ArrayRef<Attribute> operands,
         SmallVectorImpl<Attribute> &results) { return failure(); }
Registered fallback constant fold hook for the dialect.
Like the constant fold hook of each operation, it attempts to constant fold the operation with the specified constant operand values - the elements in "operands" will correspond directly to the operands of the operation, but may be null if non-constant. If constant folding is successful, this fills in the results vector. If not, this returns failure and results is unspecified.
Definition at line 72 of file Dialect.h.
Referenced by mlir::DialectHooksRegistration< ConcreteHooks >::DialectHooksRegistration(), and mlir::Operation::fold().
decodeHook
DialectConstantDecodeHook mlir::Dialect::decodeHook
Initial value:
=
      [](const OpaqueElementsAttr input, ElementsAttr &output) { return true; }
Registered hook to decode opaque constants associated with this dialect.
The hook function attempts to decode an opaque constant tensor into a tensor with non-opaque content. If decoding is successful, this method returns false and sets 'output' attribute. If not, it returns true and leaves 'output' unspecified. The default hook fails to decode.
Definition at line 81 of file Dialect.h.
Referenced by mlir::DialectHooksRegistration< ConcreteHooks >::DialectHooksRegistration().
extractElementHook
DialectExtractElementHook mlir::Dialect::extractElementHook
Initial value:
=
      [](const OpaqueElementsAttr input, ArrayRef<uint64_t> index) {
        return Attribute();
      }
Registered hook to extract an element from an opaque constant associated with this dialect.
If element has been successfully extracted, this method returns that element. If not, it returns an empty attribute. The default hook fails to extract an element.
Definition at line 88 of file Dialect.h.
Referenced by mlir::DialectHooksRegistration< ConcreteHooks >::DialectHooksRegistration(), and mlir::OpaqueElementsAttr::getValue().
The documentation for this class was generated from the following files:
include/mlir/IR/Dialect.h
lib/IR/Dialect.cpp
lib/IR/MLIRContext.cpp