MLIR: mlir::SDBM Class Reference
mlir::SDBM Class Reference
Striped difference-bound matrix is a representation of an integer set bound by a system of SDBMExprs interpreted as inequalities "expr <= 0".
#include "mlir/Dialect/SDBM/SDBM.h"
Public Member Functions
void getSDBMExpressions (SDBMDialect *dialect, SmallVectorImpl< SDBMExpr > &inequalities, SmallVectorImpl< SDBMExpr > &equalities)
void print (raw_ostream &os)
void dump ()
IntInfty operator() (int i, int j)
Static Public Member Functions
static SDBM get (ArrayRef< SDBMExpr > inequalities, ArrayRef< SDBMExpr > equalities)
Obtain an SDBM from a list of SDBM expressions treated as inequalities and equalities with zero.
Detailed Description
Striped difference-bound matrix is a representation of an integer set bound by a system of SDBMExprs interpreted as inequalities "expr <= 0".
Definition at line 98 of file SDBM.h.
Member Function Documentation
dump()
void SDBM::dump ()
Definition at line 551 of file SDBM.cpp.
References print().
get()
SDBM SDBM::get (ArrayRef< SDBMExpr > inequalities, ArrayRef< SDBMExpr > equalities) static
Obtain an SDBM from a list of SDBM expressions treated as inequalities and equalities with zero.
Definition at line 187 of file SDBM.cpp.
References mlir::SDBMExpr::cast(), collectSDBMBuildInfo(), mlir::SDBMExpr::dyn_cast(), mlir::SDBMConstantExpr::get(), mlir::SDBMExpr::getDialect(), mlir::SDBMDiffExpr::getLHS(), mlir::IntInfty::infinity(), and mlir::ops_assertions::stripe().
getSDBMExpressions()
void SDBM::getSDBMExpressions (SDBMDialect * dialect, SmallVectorImpl< SDBMExpr > & inequalities, SmallVectorImpl< SDBMExpr > & equalities)
Definition at line 421 of file SDBM.cpp.
References mlir::SDBMConstantExpr::get(), mlir::SDBMDimExpr::get(), and mlir::SDBMSymbolExpr::get().
operator()()
IntInfty mlir::SDBM::operator() (int i, int j) inline
Definition at line 112 of file SDBM.h.
print()
void SDBM::print (raw_ostream & os)
Definition at line 505 of file SDBM.cpp.
References mlir::IntInfty::getValue(), and mlir::IntInfty::isFinite().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SDBM/SDBM.h
lib/Dialect/SDBM/SDBM.cpp