MLIR: mlir::MLIRContext Class Reference
mlir::MLIRContext Class Reference
MLIRContext is the top-level object for a collection of MLIR modules.
#include "mlir/IR/MLIRContext.h"
Public Member Functions
MLIRContext ()
~MLIRContext ()
std::vector< Dialect * > getRegisteredDialects ()
Return information about all registered IR dialects.
Dialect * getRegisteredDialect (StringRef name)
Get a registered IR dialect with the given namespace.
template<typename T >
T * getRegisteredDialect ()
Get a registered IR dialect for the given derived dialect type.
std::vector< AbstractOperation * > getRegisteredOperations ()
Return information about all registered operations.
MLIRContextImpl & getImpl ()
DiagnosticEngine & getDiagEngine ()
Returns the diagnostic engine for this context.
StorageUniquer & getAffineUniquer ()
Returns the storage uniquer used for creating affine constructs.
StorageUniquer & getTypeUniquer ()
Returns the storage uniquer used for constructing type storage instances.
StorageUniquer & getAttributeUniquer ()
Returns the storage uniquer used for constructing attribute storage instances.
Detailed Description
MLIRContext is the top-level object for a collection of MLIR modules.
It holds immortal uniqued objects like types, and the tables used to unique them.
MLIRContext gets a redundant "MLIR" prefix because otherwise it ends up with a very generic name ("Context") and because it is uncommon for clients to interact with it.
Definition at line 34 of file MLIRContext.h.
Constructor & Destructor Documentation
MLIRContext()
MLIRContext::MLIRContext () explicit
Types. Floating-point Types.
Index Type.
Integer Types.
None Type.
of the above types internally. Bool Attributes.
Unit Attribute.
Unknown Location Attribute.
Definition at line 232 of file MLIRContext.cpp.
References mlir::StandardTypes::BF16, mlir::StandardAttributes::Bool, mlir::StandardTypes::F16, mlir::StandardTypes::F32, mlir::StandardTypes::F64, mlir::StandardTypes::Index, mlir::StandardTypes::Integer, mlir::StandardTypes::None, mlir::registerAllDialects(), mlir::StandardAttributes::Unit, and mlir::StandardAttributes::UnknownLocation.
Referenced by getImpl().
~MLIRContext()
MLIRContext::~MLIRContext ()
Definition at line 278 of file MLIRContext.cpp.
Member Function Documentation
getAffineUniquer()
StorageUniquer & MLIRContext::getAffineUniquer ()
Returns the storage uniquer used for creating affine constructs.
Definition at line 567 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::affineUniquer, getImpl(), and safeGetOrCreate().
Referenced by mlir::AffineExpr::ceilDiv(), mlir::AffineExpr::floorDiv(), mlir::getAffineConstantExpr(), getAffineDimOrSymbol(), getImpl(), mlir::AffineExpr::operator%(), mlir::AffineExpr::operator*(), and mlir::AffineExpr::operator+().
getAttributeUniquer()
StorageUniquer & MLIRContext::getAttributeUniquer ()
Returns the storage uniquer used for constructing attribute storage instances.
This should not be used directly.
Definition at line 535 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::attributeUniquer, mlir::NoneType::get(), getImpl(), and lookupDialectForSymbol().
Referenced by getImpl().
getDiagEngine()
DiagnosticEngine & MLIRContext::getDiagEngine ()
Returns the diagnostic engine for this context.
Definition at line 295 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::diagEngine, and getImpl().
Referenced by emitDiag(), emitUniformPerAxisDequantize(), getImpl(), and mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl().
getImpl()
MLIRContextImpl& mlir::MLIRContext::getImpl () inline
Definition at line 59 of file MLIRContext.h.
References getAffineUniquer(), getAttributeUniquer(), getDiagEngine(), getTypeUniquer(), and MLIRContext().
Referenced by mlir::Dialect::addOperation(), mlir::Identifier::get(), mlir::AffineMap::get(), mlir::IndexType::get(), mlir::FloatType::get(), mlir::UnknownLoc::get(), mlir::BoolAttr::get(), mlir::NoneType::get(), mlir::UnitAttr::get(), getAffineUniquer(), getAttributeUniquer(), getCachedIntegerType(), getDiagEngine(), getRegisteredDialect(), getRegisteredDialects(), getRegisteredOperations(), getTypeUniquer(), mlir::AbstractOperation::lookup(), and lookupDialectForSymbol().
getRegisteredDialect() [1/2]
Dialect * MLIRContext::getRegisteredDialect (StringRef name)
Get a registered IR dialect with the given namespace.
If an exact match is not found, then return nullptr.
If none is found, then return nullptr.
Definition at line 315 of file MLIRContext.cpp.
References getImpl().
Referenced by buildHexadecimalFloatLiteral(), buildLLVMFunctionType(), diag(), mlir::DialectHooksRegistration< ConcreteHooks >::DialectHooksRegistration(), getLlvmDialect(), parseAtomicCmpXchgOp(), parseCallOp(), parseCmpOp(), parseCondBrOp(), parseGlobalOp(), parseInvokeOp(), mlir::LLVM::ModuleTranslation::prepareLLVMModule(), translateLLVMIRToModule(), mlir::SDBMExpr::tryConvertAffineExpr(), and mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait().
getRegisteredDialect() [2/2]
template<typename T > T* mlir::MLIRContext::getRegisteredDialect () inline
Get a registered IR dialect for the given derived dialect type.
The derived type must provide a static 'getDialectNamespace' method.
Definition at line 48 of file MLIRContext.h.
References getRegisteredOperations().
getRegisteredDialects()
std::vector< Dialect * > MLIRContext::getRegisteredDialects ()
Return information about all registered IR dialects.
Definition at line 302 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::dialects, and getImpl().
Referenced by mlir::detail::DialectInterfaceCollectionBase::DialectInterfaceCollectionBase().
getRegisteredOperations()
std::vector< AbstractOperation * > MLIRContext::getRegisteredOperations ()
Return information about all registered operations.
This isn't very efficient: typically you should ask the operations about their properties directly.
This isn't very efficient, typically you should ask the operations about their properties directly.
Definition at line 353 of file MLIRContext.cpp.
References getImpl(), and mlir::MLIRContextImpl::registeredOperations.
Referenced by getRegisteredDialect().
getTypeUniquer()
StorageUniquer & MLIRContext::getTypeUniquer ()
Returns the storage uniquer used for constructing type storage instances.
Returns the storage unqiuer used for constructing type storage instances.
This should not be used directly.
Definition at line 461 of file MLIRContext.cpp.
References getImpl(), lookupDialectForSymbol(), and mlir::MLIRContextImpl::typeUniquer.
Referenced by getImpl().
The documentation for this class was generated from the following files:
include/mlir/IR/MLIRContext.h
lib/IR/MLIRContext.cpp