MLIR: mlir::FileLineColLoc Class Reference
mlir::FileLineColLoc Class Reference
Represents a location derived from a file/line/column location.
#include "mlir/IR/Location.h"
Public Member Functions
StringRef getFilename () const
unsigned getLine () const
unsigned getColumn () const
Static Public Member Functions
static Location get (Identifier filename, unsigned line, unsigned column, MLIRContext *context)
Return a uniqued FileLineCol location object.
static Location get (StringRef filename, unsigned line, unsigned column, MLIRContext *context)
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents a location derived from a file/line/column location.
The column and line may be zero to represent unknown column and/or unknown line/column information.
Definition at line 126 of file Location.h.
Member Function Documentation
get() [1/2]
Location FileLineColLoc::get (Identifier filename, unsigned line, unsigned column, MLIRContext * context) static
Return a uniqued FileLineCol location object.
Definition at line 41 of file Location.cpp.
References mlir::StandardAttributes::FileLineColLocation.
Referenced by buildHexadecimalFloatLiteral(), deserializeModule(), diag(), mlir::Lexer::getEncodedSourceLocation(), mlir::Builder::getFileLineColLoc(), mlir::parseSourceFile(), roundTripModule(), and mlir::translateLLVMIRToModule().
get() [2/2]
Location FileLineColLoc::get (StringRef filename, unsigned line, unsigned column, MLIRContext * context) static
Definition at line 47 of file Location.cpp.
References mlir::Identifier::get().
getColumn()
unsigned FileLineColLoc::getColumn () const
Definition at line 55 of file Location.cpp.
Referenced by mlir::SourceMgrDiagnosticHandler::getBufferForFile().
getFilename()
StringRef FileLineColLoc::getFilename () const
Definition at line 53 of file Location.cpp.
Referenced by mlir::SourceMgrDiagnosticHandler::getBufferForFile(), mlir::SourceMgrDiagnosticVerifierHandler::verify(), and mlir::AsmState::~AsmState().
getLine()
unsigned FileLineColLoc::getLine () const
Definition at line 54 of file Location.cpp.
Referenced by mlir::SourceMgrDiagnosticHandler::getBufferForFile(), mlir::SourceMgrDiagnosticVerifierHandler::verify(), and mlir::AsmState::~AsmState().
kindof()
static bool mlir::FileLineColLoc::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 144 of file Location.h.
References mlir::StandardAttributes::FileLineColLocation.
The documentation for this class was generated from the following files:
include/mlir/IR/Location.h
lib/IR/Location.cpp