MLIR: mlir::CallSiteLoc Class Reference
mlir::CallSiteLoc Class Reference
Represents a location as call site.
#include "mlir/IR/Location.h"
Public Member Functions
Location getCallee () const
The concrete location information this object presents.
Location getCaller () const
The caller's location.
Static Public Member Functions
static Location get (Location callee, Location caller)
Return a uniqued call location object.
static Location get (Location name, ArrayRef< Location > frames)
Return a call site location which represents a name reference in one line or a stack of frames.
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents a location as call site.
"callee" is the concrete location (Unknown/NameLocation/FileLineColLoc/OpaqueLoc) and "caller" points to the caller's location (another CallLocation or a concrete location). Multiple CallSiteLocs can be chained to form a call stack.
Definition at line 97 of file Location.h.
Member Function Documentation
get() [1/2]
Location CallSiteLoc::get (Location callee, Location caller) static
Return a uniqued call location object.
Definition at line 20 of file Location.cpp.
References mlir::StandardAttributes::CallSiteLocation, and mlir::Attribute::getContext().
Referenced by buildHexadecimalFloatLiteral(), get(), and remapInlinedLocations().
get() [2/2]
Location CallSiteLoc::get (Location name, ArrayRef< Location > frames) static
Return a call site location which represents a name reference in one line or a stack of frames.
The input frames are ordered from innermost to outermost.
Definition at line 25 of file Location.cpp.
References get().
getCallee()
Location CallSiteLoc::getCallee () const
The concrete location information this object presents.
Definition at line 33 of file Location.cpp.
Referenced by getFileLineColLoc().
getCaller()
Location CallSiteLoc::getCaller () const
The caller's location.
Definition at line 35 of file Location.cpp.
Referenced by mlir::AsmState::~AsmState().
kindof()
static bool mlir::CallSiteLoc::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 118 of file Location.h.
References mlir::StandardAttributes::CallSiteLocation.
The documentation for this class was generated from the following files:
include/mlir/IR/Location.h
lib/IR/Location.cpp