MLIR: mlir::NoneType Class Reference
mlir::NoneType Class Reference
NoneType is a unit type, i.e.
#include "mlir/IR/StandardTypes.h"
Static Public Member Functions
static NoneType get (MLIRContext *context)
Get an instance of the NoneType.
static bool kindof (unsigned kind)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
NoneType is a unit type, i.e.
a type with exactly one possible value, where its value does not have a defined dynamic representation.
Definition at line 521 of file StandardTypes.h.
Member Function Documentation
get()
NoneType NoneType::get (MLIRContext * context) static
Get an instance of the NoneType.
Definition at line 525 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::noneType.
Referenced by extractSymbolReference(), mlir::StringAttr::get(), mlir::MLIRContext::getAttributeUniquer(), and mlir::Builder::getNoneType().
kindof()
static bool mlir::NoneType::kindof (unsigned kind) inline static
Definition at line 528 of file StandardTypes.h.
References mlir::canonicalizeStridedLayout(), mlir::getStridesAndOffset(), mlir::isStrided(), mlir::makeStridedLinearLayoutMap(), and mlir::StandardTypes::None.
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/MLIRContext.cpp