MLIR: mlir::edsc::MemRefView Class Reference
mlir::edsc::MemRefView Class Reference
A MemRefView represents the information required to step through a MemRef.
#include "mlir/EDSC/Helpers.h"
Public Member Functions
MemRefView (Value v)
MemRefView (const MemRefView &)=default
MemRefView & operator= (const MemRefView &)=default
unsigned fastestVarying () const
Public Member Functions inherited from mlir::edsc::View
unsigned rank () const
ValueHandle lb (unsigned idx)
ValueHandle ub (unsigned idx)
int64_t step (unsigned idx)
std::tuple< ValueHandle, ValueHandle, int64_t > range (unsigned idx)
void swapRanges (unsigned i, unsigned j)
ArrayRef< ValueHandle > getLbs ()
ArrayRef< ValueHandle > getUbs ()
ArrayRef< int64_t > getSteps ()
Additional Inherited Members
Protected Attributes inherited from mlir::edsc::View
SmallVector< ValueHandle, 8 > lbs
SmallVector< ValueHandle, 8 > ubs
SmallVector< int64_t, 8 > steps
Detailed Description
A MemRefView represents the information required to step through a MemRef.
It has placeholders for non-contiguous tensors that fit within the Fortran subarray model. At the moment it can only capture a MemRef with an identity layout map.
Definition at line 67 of file Helpers.h.
Constructor & Destructor Documentation
MemRefView() [1/2]
mlir::edsc::MemRefView::MemRefView (Value v) explicit
Definition at line 33 of file Helpers.cpp.
References getMemRefSizes(), mlir::Value::getType(), mlir::Type::isa(), mlir::edsc::View::lbs, mlir::edsc::View::steps, and mlir::edsc::View::ubs.
MemRefView() [2/2]
mlir::edsc::MemRefView::MemRefView (const MemRefView &) default
Member Function Documentation
fastestVarying()
unsigned mlir::edsc::MemRefView::fastestVarying () const inline
Definition at line 73 of file Helpers.h.
References mlir::edsc::View::rank().
operator=()
MemRefView& mlir::edsc::MemRefView::operator= (const MemRefView &) default
The documentation for this class was generated from the following files:
include/mlir/EDSC/Helpers.h
lib/EDSC/Helpers.cpp