MLIR: mlir::tblgen::OpMethod Class Reference
mlir::tblgen::OpMethod Class Reference
#include "mlir/TableGen/OpClass.h"
Public Types
enum Property { MP_None = 0x0, MP_Static = 0x1, MP_Constructor = 0x2, MP_Private = 0x4 }
Public Member Functions
OpMethod (StringRef retType, StringRef name, StringRef params, Property property, bool declOnly)
OpMethodBody & body ()
bool isStatic () const
bool isPrivate () const
void writeDeclTo (raw_ostream &os) const
void writeDefTo (raw_ostream &os, StringRef namePrefix) const
Detailed Description
Definition at line 75 of file OpClass.h.
Member Enumeration Documentation
Property
enum mlir::tblgen::OpMethod::Property
Enumerator
MP_None
MP_Static
MP_Constructor
MP_Private
Definition at line 79 of file OpClass.h.
Constructor & Destructor Documentation
OpMethod()
tblgen::OpMethod::OpMethod (StringRef retType, StringRef name, StringRef params, OpMethod::Property property, bool declOnly)
Definition at line 93 of file OpClass.cpp.
Member Function Documentation
body()
tblgen::OpMethodBody & tblgen::OpMethod::body ()
Definition at line 98 of file OpClass.cpp.
isPrivate()
bool tblgen::OpMethod::isPrivate () const
Definition at line 102 of file OpClass.cpp.
References MP_Private.
isStatic()
bool tblgen::OpMethod::isStatic () const
Definition at line 100 of file OpClass.cpp.
References MP_Static.
Referenced by writeDeclTo().
writeDeclTo()
void tblgen::OpMethod::writeDeclTo (raw_ostream & os) const
Definition at line 104 of file OpClass.cpp.
References isStatic(), and mlir::tblgen::OpMethodSignature::writeDeclTo().
writeDefTo()
void tblgen::OpMethod::writeDefTo (raw_ostream & os, StringRef namePrefix) const
Definition at line 112 of file OpClass.cpp.
References mlir::tblgen::OpMethodSignature::writeDefTo(), and mlir::tblgen::OpMethodBody::writeTo().
The documentation for this class was generated from the following files:
include/mlir/TableGen/OpClass.h
lib/TableGen/OpClass.cpp