MLIR: mlir::NameLoc Class Reference
mlir::NameLoc Class Reference
Represents an identity name attached to a child location.
#include "mlir/IR/Location.h"
Public Member Functions
Identifier getName () const
Return the name identifier.
Location getChildLoc () const
Return the child location.
Static Public Member Functions
static Location get (Identifier name, Location child)
Return a uniqued name location object.
static Location get (Identifier name, MLIRContext *context)
Return a uniqued name location object with an unknown child.
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents an identity name attached to a child location.
Definition at line 178 of file Location.h.
Member Function Documentation
get() [1/2]
Location NameLoc::get (Identifier name, Location child) static
Return a uniqued name location object.
The child location must not be another NameLoc.
Definition at line 101 of file Location.cpp.
References mlir::Attribute::getContext(), mlir::Location::isa(), and mlir::StandardAttributes::NameLocation.
Referenced by buildHexadecimalFloatLiteral().
get() [2/2]
Location NameLoc::get (Identifier name, MLIRContext * context) static
Return a uniqued name location object with an unknown child.
Definition at line 108 of file Location.cpp.
References mlir::UnknownLoc::get().
getChildLoc()
Location NameLoc::getChildLoc () const
Return the child location.
Definition at line 116 of file Location.cpp.
References mlir::OpaqueLoc::get(), mlir::Attribute::getContext(), and mlir::StandardAttributes::OpaqueLocation.
Referenced by getFileLineColLoc().
getName()
Identifier NameLoc::getName () const
Return the name identifier.
Definition at line 113 of file Location.cpp.
Referenced by mlir::AsmState::~AsmState().
kindof()
static bool mlir::NameLoc::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 197 of file Location.h.
References mlir::StandardAttributes::NameLocation.
The documentation for this class was generated from the following files:
include/mlir/IR/Location.h
lib/IR/Location.cpp