MLIR: mlir::quantizer::UniformParamsFromMinMaxSolver Class Reference
mlir::quantizer::UniformParamsFromMinMaxSolver Class Reference
Solves for the uniform quantization scheme parameters delta and z given bounding min/max.
#include "mlir/Quantizer/Support/UniformSolvers.h"
Public Member Functions
UniformParamsFromMinMaxSolver (const UniformStorageParams &storageParams, double boundingMin, double boundingMax)
bool compute ()
Performs the computation, returning whether satisfied.
double getBoundingMin () const
double getBoundingMax () const
bool isSatisfied () const
double getAdjMin () const
double getAdjMax () const
double getScale () const
int64_t getZp () const
int getStepCount () const
int64_t quantize (double x) const
double dequantize (int64_t xq) const
Detailed Description
Solves for the uniform quantization scheme parameters delta and z given bounding min/max.
Definition at line 38 of file UniformSolvers.h.
Constructor & Destructor Documentation
UniformParamsFromMinMaxSolver()
mlir::quantizer::UniformParamsFromMinMaxSolver::UniformParamsFromMinMaxSolver (const UniformStorageParams & storageParams, double boundingMin, double boundingMax) inline
Definition at line 40 of file UniformSolvers.h.
Member Function Documentation
compute()
bool UniformParamsFromMinMaxSolver::compute ()
Performs the computation, returning whether satisfied.
Definition at line 17 of file UniformSolvers.cpp.
References mlir::quantizer::UniformStorageParams::numLevels.
dequantize()
double UniformParamsFromMinMaxSolver::dequantize (int64_t xq) const
Definition at line 117 of file UniformSolvers.cpp.
References getAdjMax(), getAdjMin(), getBoundingMax(), getBoundingMin(), getScale(), getStepCount(), getZp(), isSatisfied(), mlir::quantizer::UniformStorageParams::minValue, mlir::quantizer::UniformStorageParams::numLevels, and mlir::quantizer::operator<<().
getAdjMax()
double mlir::quantizer::UniformParamsFromMinMaxSolver::getAdjMax () const inline
Definition at line 53 of file UniformSolvers.h.
Referenced by dequantize().
getAdjMin()
double mlir::quantizer::UniformParamsFromMinMaxSolver::getAdjMin () const inline
Definition at line 52 of file UniformSolvers.h.
Referenced by dequantize().
getBoundingMax()
double mlir::quantizer::UniformParamsFromMinMaxSolver::getBoundingMax () const inline
Definition at line 50 of file UniformSolvers.h.
Referenced by dequantize().
getBoundingMin()
double mlir::quantizer::UniformParamsFromMinMaxSolver::getBoundingMin () const inline
Definition at line 49 of file UniformSolvers.h.
Referenced by dequantize().
getScale()
double mlir::quantizer::UniformParamsFromMinMaxSolver::getScale () const inline
Definition at line 54 of file UniformSolvers.h.
Referenced by dequantize().
getStepCount()
int mlir::quantizer::UniformParamsFromMinMaxSolver::getStepCount () const inline
Definition at line 56 of file UniformSolvers.h.
References operator<<().
Referenced by dequantize().
getZp()
int64_t mlir::quantizer::UniformParamsFromMinMaxSolver::getZp () const inline
Definition at line 55 of file UniformSolvers.h.
Referenced by dequantize().
isSatisfied()
bool mlir::quantizer::UniformParamsFromMinMaxSolver::isSatisfied () const inline
Definition at line 51 of file UniformSolvers.h.
Referenced by dequantize().
quantize()
int64_t UniformParamsFromMinMaxSolver::quantize (double x) const
Definition at line 112 of file UniformSolvers.cpp.
The documentation for this class was generated from the following files:
include/mlir/Quantizer/Support/UniformSolvers.h
lib/Quantizer/Support/UniformSolvers.cpp