MLIR: mlir::quantizer::UniformConstraintsBuilder Class Reference
mlir::quantizer::UniformConstraintsBuilder Class Reference
Factory methods for adding CAG constraints of various kinds suitable for solving for uniform quantization.
#include "mlir/Quantizer/Support/UniformConstraints.h"
Public Member Functions
UniformConstraintsBuilder (CAGSlice &slice)
void coupleAnchors (CAGAnchorNode *a, CAGAnchorNode *b)
Adds a coupling constraint between two nodes, effectively treating them as a hard identity relationship.
void applyStats (CAGAnchorNode *a, TensorAxisStatistics stats)
Applies statistics constraints to the given anchor, such that the solver ensures that the statistics are representable by chosen types.
void clamp (CAGAnchorNode *a, APFloat minValue, APFloat maxValue)
Applies a constraint to a node which allows solutions that do not extend beyond given min/max bounds (this is a hint that the tensor will not take values outside of these bounds).
void propagateExplicitScale (CAGAnchorNode *from, CAGAnchorNode *to)
Propagates an explicit scale from an anchor that may have a uniform |selectedType| to the |explicitScaleZeroPoint| field of the to node.
Detailed Description
Factory methods for adding CAG constraints of various kinds suitable for solving for uniform quantization.
Definition at line 27 of file UniformConstraints.h.
Constructor & Destructor Documentation
UniformConstraintsBuilder()
mlir::quantizer::UniformConstraintsBuilder::UniformConstraintsBuilder (CAGSlice & slice) inline
Definition at line 29 of file UniformConstraints.h.
References applyStats(), clamp(), coupleAnchors(), and propagateExplicitScale().
Member Function Documentation
applyStats()
void UniformConstraintsBuilder::applyStats (CAGAnchorNode * a, TensorAxisStatistics stats)
Applies statistics constraints to the given anchor, such that the solver ensures that the statistics are representable by chosen types.
Definition at line 240 of file UniformConstraints.cpp.
References mlir::quantizer::BasePropagatedFact< BinaryReducer >::assertValue(), mlir::quantizer::CAGAnchorNode::getUniformMetadata(), mlir::quantizer::TensorAxisStatistics::maxValue, mlir::quantizer::TensorAxisStatistics::minValue, mlir::quantizer::CAGUniformMetadata::requiredRange, and mlir::quantizer::CAGUniformMetadata::SalienceDefault.
Referenced by UniformConstraintsBuilder().
clamp()
void UniformConstraintsBuilder::clamp (CAGAnchorNode * a, APFloat minValue, APFloat maxValue)
Applies a constraint to a node which allows solutions that do not extend beyond given min/max bounds (this is a hint that the tensor will not take values outside of these bounds).
If either minValue or maxValue is NAN, then that side is considered open.
Definition at line 246 of file UniformConstraints.cpp.
References mlir::quantizer::BasePropagatedFact< BinaryReducer >::assertValue(), mlir::quantizer::CAGAnchorNode::getUniformMetadata(), mlir::quantizer::CAGUniformMetadata::requiredRange, and mlir::quantizer::CAGUniformMetadata::SalienceDefault.
Referenced by UniformConstraintsBuilder().
coupleAnchors()
void UniformConstraintsBuilder::coupleAnchors (CAGAnchorNode * a, CAGAnchorNode * b)
Adds a coupling constraint between two nodes, effectively treating them as a hard identity relationship.
Definition at line 235 of file UniformConstraints.cpp.
Referenced by UniformConstraintsBuilder().
propagateExplicitScale()
void UniformConstraintsBuilder::propagateExplicitScale (CAGAnchorNode * from, CAGAnchorNode * to)
Propagates an explicit scale from an anchor that may have a uniform |selectedType| to the |explicitScaleZeroPoint| field of the to node.
This is typically used with a to node that has a candidate quantized type of |UniformExplicitFixedPointScale|, indicating that it can be an arbitrary (signed) type that is expected to share the same scale as the originating node.
Definition at line 253 of file UniformConstraints.cpp.
Referenced by UniformConstraintsBuilder().
The documentation for this class was generated from the following files:
include/mlir/Quantizer/Support/UniformConstraints.h
lib/Quantizer/Support/UniformConstraints.cpp