MLIR: mlir::spirv::SPIRVDialect Class Reference
mlir::spirv::SPIRVDialect Class Reference
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
Public Member Functions
SPIRVDialect (MLIRContext *context)
Type parseType (DialectAsmParser &parser) const override
Parses a type registered to this dialect.
void printType (Type type, DialectAsmPrinter &os) const override
Prints a type registered to this dialect.
Operation * materializeConstant (OpBuilder &builder, Attribute value, Type type, Location loc) override
Provides a hook for materializing a constant to this dialect.
LogicalResult verifyOperationAttribute (Operation *op, NamedAttribute attribute) override
Provides a hook for verifying SPIR-V dialect attributes attached to the given op.
LogicalResult verifyRegionArgAttribute (Operation *op, unsigned regionIndex, unsigned argIndex, NamedAttribute attribute) override
Provides a hook for verifying SPIR-V dialect attributes attached to the given op's region argument.
LogicalResult verifyRegionResultAttribute (Operation *op, unsigned regionIndex, unsigned resultIndex, NamedAttribute attribute) override
Provides a hook for verifying SPIR-V dialect attributes attached to the given op's region result.
Public Member Functions inherited from mlir::Dialect
virtual ~Dialect ()
MLIRContext * getContext () const
StringRef getNamespace () const
bool allowsUnknownOperations () const
Returns true if this dialect allows for unregistered operations, i.e.
bool allowsUnknownTypes () const
Return true if this dialect allows for unregistered types, i.e., types prefixed with the dialect namespace but not registered with addType.
virtual Attribute parseAttribute (DialectAsmParser &parser, Type type) const
Parse an attribute registered to this dialect.
virtual void printAttribute (Attribute, DialectAsmPrinter &) const
Print an attribute registered to this dialect.
const DialectInterface * getRegisteredInterface (ClassID *interfaceID)
Lookup an interface for the given ID if one is registered, otherwise nullptr.
template<typename InterfaceT >
const InterfaceT * getRegisteredInterface ()
Static Public Member Functions
static StringRef getDialectNamespace ()
static bool isValidType (Type type)
Checks if the given type is valid in SPIR-V dialect.
static bool isValidScalarType (Type type)
Checks if the given scalar type is valid in SPIR-V dialect.
static std::string getAttributeName (Decoration decoration)
Returns the attribute name to use when specifying decorations on results of operations.
Static Public Member Functions inherited from mlir::Dialect
static bool isValidNamespace (StringRef str)
Utility function that returns if the given string is a valid dialect namespace.
Additional Inherited Members
Public Attributes inherited from mlir::Dialect
DialectConstantFoldHook constantFoldHook
Registered fallback constant fold hook for the dialect.
DialectConstantDecodeHook decodeHook
Registered hook to decode opaque constants associated with this dialect.
DialectExtractElementHook extractElementHook
Registered hook to extract an element from an opaque constant associated with this dialect.
Protected Member Functions inherited from mlir::Dialect
Dialect (StringRef name, MLIRContext *context)
The constructor takes a unique namespace for this dialect as well as the context to bind to.
template<typename... Args>
void addOperations ()
This method is used by derived classes to add their operations to the set.
void addOperation (AbstractOperation opInfo)
template<typename... Args>
void addTypes ()
This method is used by derived classes to add their types to the set.
template<typename... Args>
void addAttributes ()
This method is used by derived classes to add their attributes to the set.
void allowUnknownOperations (bool allow=true)
Enable support for unregistered operations.
void allowUnknownTypes (bool allow=true)
Enable support for unregistered types.
void addInterface (std::unique_ptr< DialectInterface > interface)
Register a dialect interface with this dialect instance.
template<typename T , typename T2 , typename... Tys>
void addInterfaces ()
Register a set of dialect interfaces with this dialect instance.
template<typename T >
void addInterfaces ()
Detailed Description
Definition at line 23 of file SPIRVDialect.h.
Constructor & Destructor Documentation
SPIRVDialect()
SPIRVDialect::SPIRVDialect (MLIRContext * context) explicit
Definition at line 116 of file SPIRVDialect.cpp.
References mlir::Dialect::addOperations(), and mlir::Dialect::allowUnknownOperations().
Member Function Documentation
getAttributeName()
std::string SPIRVDialect::getAttributeName (Decoration decoration) static
Returns the attribute name to use when specifying decorations on results of operations.
Definition at line 132 of file SPIRVDialect.cpp.
References mlir::convertToSnakeCase(), parseAndVerify(), parseAndVerify< Type >(), and parseAndVerify< uint64_t >().
Referenced by getBuiltinVariable(), and verify().
getDialectNamespace()
static StringRef mlir::spirv::SPIRVDialect::getDialectNamespace () inline static
Definition at line 27 of file SPIRVDialect.h.
References materializeConstant(), and mlir::parseType().
isValidScalarType()
bool SPIRVDialect::isValidScalarType (Type type) static
Checks if the given scalar type is valid in SPIR-V dialect.
Definition at line 157 of file SPIRVDialect.cpp.
References mlir::Type::dyn_cast(), mlir::Type::isa(), mlir::Type::isBF16(), and isValidSPIRVIntType().
Referenced by mlir::VulkanLayoutUtils::decorateType(), getTypeNumBytes(), isScalarOrVectorType(), isValidSPIRVVectorType(), isValidType(), and verify().
isValidType()
bool SPIRVDialect::isValidType (Type type) static
Checks if the given type is valid in SPIR-V dialect.
Definition at line 173 of file SPIRVDialect.cpp.
References mlir::Type::dyn_cast(), mlir::Type::getKind(), isValidScalarType(), isValidSPIRVVectorType(), and mlir::spirv::TypeKind::LAST_SPIRV_TYPE.
Referenced by convertStdType(), and verify().
materializeConstant()
Operation * SPIRVDialect::materializeConstant (OpBuilder & builder, Attribute value, Type type, Location loc) override virtual
Provides a hook for materializing a constant to this dialect.
Reimplemented from mlir::Dialect.
Definition at line 635 of file SPIRVDialect.cpp.
References mlir::OpBuilder::create().
parseType()
Type SPIRVDialect::parseType (DialectAsmParser & parser) const override virtual
Parses a type registered to this dialect.
Reimplemented from mlir::Dialect.
Definition at line 534 of file SPIRVDialect.cpp.
References mlir::DialectAsmParser::emitError(), mlir::DialectAsmParser::getNameLoc(), parseArrayType(), parseImageType(), mlir::DialectAsmParser::parseKeyword(), parsePointerType(), parseRuntimeArrayType(), parseStructType(), and mlir::StandardAttributes::Type.
printType()
void SPIRVDialect::printType (Type type, DialectAsmPrinter & os) const override virtual
Prints a type registered to this dialect.
Reimplemented from mlir::Dialect.
Definition at line 609 of file SPIRVDialect.cpp.
References mlir::spirv::TypeKind::Array, mlir::Type::cast(), mlir::Type::getKind(), mlir::spirv::TypeKind::Image, mlir::spirv::TypeKind::Pointer, print(), mlir::spirv::TypeKind::RuntimeArray, and mlir::spirv::TypeKind::Struct.
verifyOperationAttribute()
LogicalResult SPIRVDialect::verifyOperationAttribute (Operation * op, NamedAttribute attribute) override virtual
Provides a hook for verifying SPIR-V dialect attributes attached to the given op.
Reimplemented from mlir::Dialect.
Definition at line 648 of file SPIRVDialect.cpp.
References mlir::Operation::emitError(), mlir::spirv::getEntryPointABIAttrName(), mlir::spirv::getTargetEnvAttrName(), mlir::Attribute::isa(), and mlir::success().
verifyRegionArgAttribute()
LogicalResult SPIRVDialect::verifyRegionArgAttribute (Operation * op, unsigned regionIndex, unsigned argIndex, NamedAttribute attribute) override virtual
Provides a hook for verifying SPIR-V dialect attributes attached to the given op's region argument.
Reimplemented from mlir::Dialect.
Definition at line 699 of file SPIRVDialect.cpp.
References mlir::Operation::getLoc(), and verifyRegionAttribute().
verifyRegionResultAttribute()
LogicalResult SPIRVDialect::verifyRegionResultAttribute (Operation * op, unsigned regionIndex, unsigned resultIndex, NamedAttribute attribute) override virtual
Provides a hook for verifying SPIR-V dialect attributes attached to the given op's region result.
Reimplemented from mlir::Dialect.
Definition at line 707 of file SPIRVDialect.cpp.
References mlir::Operation::getLoc(), and verifyRegionAttribute().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVDialect.h
lib/Dialect/SPIRV/SPIRVDialect.cpp