MLIR: mlir::tblgen::DagLeaf Class Reference
mlir::tblgen::DagLeaf Class Reference
#include "mlir/TableGen/Pattern.h"
Public Member Functions
DagLeaf (const llvm::Init *def)
bool isUnspecified () const
bool isOperandMatcher () const
bool isAttrMatcher () const
bool isNativeCodeCall () const
bool isConstantAttr () const
bool isEnumAttrCase () const
Constraint getAsConstraint () const
ConstantAttr getAsConstantAttr () const
EnumAttrCase getAsEnumAttrCase () const
std::string getConditionTemplate () const
StringRef getNativeCodeTemplate () const
void print (raw_ostream &os) const
Detailed Description
Definition at line 54 of file Pattern.h.
Constructor & Destructor Documentation
DagLeaf()
mlir::tblgen::DagLeaf::DagLeaf (const llvm::Init * def) inline explicit
Definition at line 56 of file Pattern.h.
References print().
Referenced by mlir::tblgen::DagNode::getArgAsLeaf().
Member Function Documentation
getAsConstantAttr()
tblgen::ConstantAttr tblgen::DagLeaf::getAsConstantAttr () const
Definition at line 64 of file Pattern.cpp.
References isConstantAttr().
getAsConstraint()
tblgen::Constraint tblgen::DagLeaf::getAsConstraint () const
Definition at line 58 of file Pattern.cpp.
References isAttrMatcher(), and isOperandMatcher().
Referenced by getConditionTemplate().
getAsEnumAttrCase()
tblgen::EnumAttrCase tblgen::DagLeaf::getAsEnumAttrCase () const
Definition at line 69 of file Pattern.cpp.
References isEnumAttrCase().
getConditionTemplate()
std::string tblgen::DagLeaf::getConditionTemplate () const
Definition at line 74 of file Pattern.cpp.
References getAsConstraint(), and mlir::tblgen::Constraint::getConditionTemplate().
getNativeCodeTemplate()
llvm::StringRef tblgen::DagLeaf::getNativeCodeTemplate () const
Definition at line 78 of file Pattern.cpp.
References isNativeCodeCall().
isAttrMatcher()
bool tblgen::DagLeaf::isAttrMatcher () const
Definition at line 41 of file Pattern.cpp.
Referenced by getAsConstraint().
isConstantAttr()
bool tblgen::DagLeaf::isConstantAttr () const
Definition at line 50 of file Pattern.cpp.
Referenced by getAsConstantAttr().
isEnumAttrCase()
bool tblgen::DagLeaf::isEnumAttrCase () const
Definition at line 54 of file Pattern.cpp.
Referenced by getAsEnumAttrCase().
isNativeCodeCall()
bool tblgen::DagLeaf::isNativeCodeCall () const
Definition at line 46 of file Pattern.cpp.
Referenced by getNativeCodeTemplate(), mlir::tblgen::DagNode::getNativeCodeTemplate(), and mlir::tblgen::DagNode::isOperation().
isOperandMatcher()
bool tblgen::DagLeaf::isOperandMatcher () const
Definition at line 36 of file Pattern.cpp.
Referenced by getAsConstraint().
isUnspecified()
bool tblgen::DagLeaf::isUnspecified () const
Definition at line 32 of file Pattern.cpp.
print()
void tblgen::DagLeaf::print (raw_ostream & os) const
Definition at line 89 of file Pattern.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Pattern.h
lib/TableGen/Pattern.cpp