MLIR: mlir::detail::OpToOpPassAdaptorBase Class Reference
mlir::detail::OpToOpPassAdaptorBase Class Reference
A base class for Op-to-Op adaptor passes.
#include "Pass/PassDetail.h"
Public Member Functions
OpToOpPassAdaptorBase (OpPassManager &&mgr)
OpToOpPassAdaptorBase (const OpToOpPassAdaptorBase &rhs)=default
void mergeInto (OpToOpPassAdaptorBase &rhs)
Merge the current pass adaptor into given 'rhs'.
MutableArrayRef< OpPassManager > getPassManagers ()
Returns the pass managers held by this adaptor.
std::string getName ()
Returns the adaptor pass name.
Protected Attributes
SmallVector< OpPassManager, 1 > mgrs
Detailed Description
A base class for Op-to-Op adaptor passes.
Definition at line 31 of file PassDetail.h.
Constructor & Destructor Documentation
OpToOpPassAdaptorBase() [1/2]
OpToOpPassAdaptorBase::OpToOpPassAdaptorBase (OpPassManager && mgr)
Definition at line 328 of file Pass.cpp.
OpToOpPassAdaptorBase() [2/2]
mlir::detail::OpToOpPassAdaptorBase::OpToOpPassAdaptorBase (const OpToOpPassAdaptorBase & rhs) default
Member Function Documentation
getName()
std::string OpToOpPassAdaptorBase::getName ()
Returns the adaptor pass name.
Definition at line 355 of file Pass.cpp.
References mlir::OpPassManager::getOpName(), and mlir::interleaveComma().
getPassManagers()
MutableArrayRef<OpPassManager> mlir::detail::OpToOpPassAdaptorBase::getPassManagers () inline
Returns the pass managers held by this adaptor.
Definition at line 40 of file PassDetail.h.
References mlir::detail::PassModel< VerifierPass, OpPassBase< void > >::getName().
Referenced by mlir::detail::OpPassManagerImpl::coalesceAdjacentAdaptorPasses(), and prepareStatistics().
mergeInto()
void OpToOpPassAdaptorBase::mergeInto (OpToOpPassAdaptorBase & rhs)
Merge the current pass adaptor into given 'rhs'.
Definition at line 333 of file Pass.cpp.
References findPassManagerFor(), mlir::OpPassManager::getOpName(), mlir::OperationName::getStringRef(), and mgrs.
Referenced by mlir::detail::OpPassManagerImpl::coalesceAdjacentAdaptorPasses().
Member Data Documentation
mgrs
SmallVector<OpPassManager, 1> mlir::detail::OpToOpPassAdaptorBase::mgrs protected
Definition at line 47 of file PassDetail.h.
Referenced by mergeInto(), mlir::detail::OpToOpPassAdaptor::runOnOperation(), and mlir::detail::OpToOpPassAdaptorParallel::runOnOperation().
The documentation for this class was generated from the following files:
lib/Pass/PassDetail.h
lib/Pass/Pass.cpp