MLIR: mlir::OpaqueType Class Reference
mlir::OpaqueType Class Reference
Opaque types represent types of non-registered dialects.
#include "mlir/IR/Types.h"
Public Member Functions
Identifier getDialectNamespace () const
Returns the dialect namespace of the opaque type.
StringRef getTypeData () const
Returns the raw type data of the opaque type.
Static Public Member Functions
static OpaqueType get (Identifier dialect, StringRef typeData, MLIRContext *context)
Get or create a new OpaqueType with the provided dialect and string data.
static OpaqueType getChecked (Identifier dialect, StringRef typeData, MLIRContext *context, Location location)
Get or create a new OpaqueType with the provided dialect and string data.
static LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *context, Identifier dialect, StringRef typeData)
Verify the construction of an opaque type.
static bool kindof (unsigned kind)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Opaque types represent types of non-registered dialects.
These are types represented in their raw string form, and can only usefully be tested for type equality.
Definition at line 219 of file Types.h.
Member Function Documentation
get()
OpaqueType OpaqueType::get (Identifier dialect, StringRef typeData, MLIRContext * context) static
Get or create a new OpaqueType with the provided dialect and string data.
Definition at line 55 of file Types.cpp.
References mlir::StandardAttributes::Opaque.
Referenced by mlir::Dialect::parseType().
getChecked()
OpaqueType OpaqueType::getChecked (Identifier dialect, StringRef typeData, MLIRContext * context, Location location) static
Get or create a new OpaqueType with the provided dialect and string data.
If the given identifier is not a valid namespace for a dialect, then a null type is returned.
Definition at line 60 of file Types.cpp.
References mlir::StandardAttributes::Opaque.
Referenced by parseSymbol().
getDialectNamespace()
Identifier OpaqueType::getDialectNamespace () const
Returns the dialect namespace of the opaque type.
Definition at line 66 of file Types.cpp.
getTypeData()
StringRef OpaqueType::getTypeData () const
Returns the raw type data of the opaque type.
Definition at line 71 of file Types.cpp.
kindof()
static bool mlir::OpaqueType::kindof (unsigned kind) inline static
Definition at line 246 of file Types.h.
References mlir::StandardAttributes::Opaque.
verifyConstructionInvariants()
LogicalResult OpaqueType::verifyConstructionInvariants (Optional< Location > loc, MLIRContext * context, Identifier dialect, StringRef typeData) static
Verify the construction of an opaque type.
Definition at line 74 of file Types.cpp.
References mlir::emitOptionalError(), mlir::Dialect::isValidNamespace(), mlir::Identifier::strref(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/Types.h
lib/IR/Types.cpp