MLIR: mlir::Token Class Reference
mlir::Token Class Reference
This represents a token in the MLIR syntax.
#include "Parser/Token.h"
Public Types
enum Kind { TOK_IDENTIFIER, TOK_IDENTIFIER, TOK_IDENTIFIER }
Public Member Functions
Token (Kind kind, StringRef spelling)
StringRef getSpelling () const
Kind getKind () const
bool is (Kind K) const
bool isAny (Kind k1, Kind k2) const
template<typename... T>
bool isAny (Kind k1, Kind k2, Kind k3, T... others) const
Return true if this token is one of the specified kinds.
bool isNot (Kind k) const
template<typename... T>
bool isNot (Kind k1, Kind k2, T... others) const
Return true if this token isn't one of the specified kinds.
bool isKeyword () const
Return true if this is one of the keyword token kinds (e.g. kw_if).
Optional< unsigned > getUnsignedIntegerValue () const
For an integer token, return its value as an unsigned.
Optional< uint64_t > getUInt64IntegerValue () const
For an integer token, return its value as an uint64_t.
Optional< double > getFloatingPointValue () const
For a floatliteral token, return its value as a double.
Optional< unsigned > getIntTypeBitwidth () const
For an inttype token, return its bitwidth.
Optional< unsigned > getHashIdentifierNumber () const
Given a hash_identifier token like #123, try to parse the number out of the identifier, returning None if it is a named identifier like #x or if the integer doesn't fit.
std::string getStringValue () const
Given a token containing a string literal, return its value, including removing the quote characters and unescaping the contents of the string.
llvm::SMLoc getLoc () const
llvm::SMLoc getEndLoc () const
llvm::SMRange getLocRange () const
Static Public Member Functions
static StringRef getTokenSpelling (Kind kind)
Given a punctuation or keyword token kind, return the spelling of the token as a string.
Detailed Description
This represents a token in the MLIR syntax.
Definition at line 19 of file Token.h.
Member Enumeration Documentation
Kind
enum mlir::Token::Kind
Enumerator
TOK_IDENTIFIER
TOK_IDENTIFIER
TOK_IDENTIFIER
Definition at line 21 of file Token.h.
Constructor & Destructor Documentation
Token()
mlir::Token::Token (Kind kind, StringRef spelling) inline
Definition at line 31 of file Token.h.
Member Function Documentation
getEndLoc()
SMLoc Token::getEndLoc () const
Definition at line 21 of file Token.cpp.
Referenced by getLocRange().
getFloatingPointValue()
Optional< double > Token::getFloatingPointValue () const
For a floatliteral token, return its value as a double.
For a floatliteral, return its value as a double.
Returns None in the case of underflow or overflow.
Return None if the value underflows or overflows.
Definition at line 51 of file Token.cpp.
References mlir::StandardTypes::None.
Referenced by buildHexadecimalFloatLiteral().
getHashIdentifierNumber()
Optional< unsigned > Token::getHashIdentifierNumber () const
Given a hash_identifier token like #123, try to parse the number out of the identifier, returning None if it is a named identifier like #x or if the integer doesn't fit.
Definition at line 117 of file Token.cpp.
References getKind(), and mlir::StandardTypes::None.
getIntTypeBitwidth()
Optional< unsigned > Token::getIntTypeBitwidth () const
For an inttype token, return its bitwidth.
Definition at line 59 of file Token.cpp.
References mlir::StandardTypes::None.
getKind()
Kind mlir::Token::getKind () const inline
Definition at line 37 of file Token.h.
Referenced by getHashIdentifierNumber(), and getStringValue().
getLoc()
SMLoc Token::getLoc () const
Definition at line 19 of file Token.cpp.
Referenced by buildHexadecimalFloatLiteral(), getLocRange(), and parseSymbol().
getLocRange()
SMRange Token::getLocRange () const
Definition at line 25 of file Token.cpp.
References getEndLoc(), and getLoc().
getSpelling()
StringRef mlir::Token::getSpelling () const inline
Definition at line 34 of file Token.h.
Referenced by buildHexadecimalFloatLiteral(), extractSymbolReference(), and getStringValue().
getStringValue()
std::string Token::getStringValue () const
Given a token containing a string literal, return its value, including removing the quote characters and unescaping the contents of the string.
The lexer has already verified that this token is valid.
Definition at line 70 of file Token.cpp.
References getKind(), and getSpelling().
Referenced by extractSymbolReference().
getTokenSpelling()
StringRef Token::getTokenSpelling (Kind kind) static
Given a punctuation or keyword token kind, return the spelling of the token as a string.
Warning: This will abort on markers, identifiers and literal tokens since they have no fixed spelling.
Definition at line 128 of file Token.cpp.
getUInt64IntegerValue()
Optional< uint64_t > Token::getUInt64IntegerValue () const
For an integer token, return its value as an uint64_t.
For an integer token, return its value as a uint64_t.
If it doesn't fit, return None.
Definition at line 40 of file Token.cpp.
References mlir::StandardTypes::None.
Referenced by buildHexadecimalFloatLiteral().
getUnsignedIntegerValue()
Optional< unsigned > Token::getUnsignedIntegerValue () const
For an integer token, return its value as an unsigned.
If it doesn't fit, return None.
Definition at line 29 of file Token.cpp.
References mlir::StandardTypes::None.
is()
bool mlir::Token::is (Kind K) const inline
Definition at line 38 of file Token.h.
Referenced by buildHexadecimalFloatLiteral(), extractSymbolReference(), isAny(), and mlir::Lexer::lexToken().
isAny() [1/2]
bool mlir::Token::isAny (Kind k1, Kind k2) const inline
Definition at line 40 of file Token.h.
References is().
Referenced by buildHexadecimalFloatLiteral(), and isAny().
isAny() [2/2]
template<typename... T> bool mlir::Token::isAny (Kind k1, Kind k2, Kind k3, T... others) const inline
Return true if this token is one of the specified kinds.
Definition at line 44 of file Token.h.
References is(), and isAny().
isKeyword()
bool Token::isKeyword () const
Return true if this is one of the keyword token kinds (e.g. kw_if).
Definition at line 146 of file Token.cpp.
isNot() [1/2]
bool mlir::Token::isNot (Kind k) const inline
Definition at line 50 of file Token.h.
Referenced by parseSymbol().
isNot() [2/2]
template<typename... T> bool mlir::Token::isNot (Kind k1, Kind k2, T... others) const inline
Return true if this token isn't one of the specified kinds.
Definition at line 53 of file Token.h.
The documentation for this class was generated from the following files:
lib/Parser/Token.h
lib/Parser/Token.cpp