MLIR: mlir::UnrankedTensorType Class Reference
mlir::UnrankedTensorType Class Reference
Unranked tensor types represent multi-dimensional arrays that have an unknown shape.
#include "mlir/IR/StandardTypes.h"
Public Member Functions
ArrayRef< int64_t > getShape () const
Static Public Member Functions
static UnrankedTensorType get (Type elementType)
Get or create a new UnrankedTensorType of the provided shape and element type.
static UnrankedTensorType getChecked (Type elementType, Location location)
Get or create a new UnrankedTensorType of the provided shape and element type declared at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *context, Type elementType)
Verify the construction of a unranked tensor type.
static bool kindof (unsigned kind)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Unranked tensor types represent multi-dimensional arrays that have an unknown shape.
Definition at line 346 of file StandardTypes.h.
Member Function Documentation
get()
UnrankedTensorType UnrankedTensorType::get (Type elementType) static
Get or create a new UnrankedTensorType of the provided shape and element type.
Assumes the arguments define a well-formed type.
Definition at line 279 of file StandardTypes.cpp.
References mlir::Type::getContext(), and mlir::StandardTypes::UnrankedTensor.
Referenced by mlir::fxpmath::detail::castElementType(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::quant::ExpressedToQuantizedConverter::convert(), mlir::OpTrait::util::getBroadcastedType(), getCheckedI1SameShape(), and mlir::detail::inferReturnTensorTypes().
getChecked()
UnrankedTensorType UnrankedTensorType::getChecked (Type elementType, Location location) static
Get or create a new UnrankedTensorType of the provided shape and element type declared at the given, potentially unknown, location.
If the UnrankedTensorType defined by the arguments would be ill-formed, emit errors and return a nullptr-wrapping type.
Definition at line 284 of file StandardTypes.cpp.
References mlir::Type::getContext(), and mlir::StandardTypes::UnrankedTensor.
Referenced by parseSymbol().
getShape()
ArrayRef<int64_t> mlir::UnrankedTensorType::getShape () const inline
Definition at line 367 of file StandardTypes.h.
References mlir::StandardTypes::None.
kindof()
static bool mlir::UnrankedTensorType::kindof (unsigned kind) inline static
Definition at line 369 of file StandardTypes.h.
References mlir::StandardTypes::UnrankedTensor.
verifyConstructionInvariants()
LogicalResult UnrankedTensorType::verifyConstructionInvariants (Optional< Location > loc, MLIRContext * context, Type elementType) static
Verify the construction of a unranked tensor type.
Definition at line 290 of file StandardTypes.cpp.
References checkTensorElementType().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp