MLIR: mlir::OpaqueAttr Class Reference
mlir::OpaqueAttr Class Reference
Opaque attributes represent attributes of non-registered dialects.
#include "mlir/IR/Attributes.h"
Public Member Functions
Identifier getDialectNamespace () const
Returns the dialect namespace of the opaque attribute.
StringRef getAttrData () const
Returns the raw attribute data of the opaque attribute.
Static Public Member Functions
static OpaqueAttr get (Identifier dialect, StringRef attrData, Type type, MLIRContext *context)
Get or create a new OpaqueAttr with the provided dialect and string data.
static OpaqueAttr getChecked (Identifier dialect, StringRef attrData, Type type, Location location)
Get or create a new OpaqueAttr with the provided dialect and string data.
static LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *context, Identifier dialect, StringRef attrData, Type type)
Verify the construction of an opaque attribute.
static bool kindof (unsigned kind)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Opaque attributes represent attributes of non-registered dialects.
These are attribute represented in their raw string form, and can only usefully be tested for attribute equality.
Definition at line 399 of file Attributes.h.
Member Function Documentation
get()
OpaqueAttr OpaqueAttr::get (Identifier dialect, StringRef attrData, Type type, MLIRContext * context) static
Get or create a new OpaqueAttr with the provided dialect and string data.
Definition at line 326 of file Attributes.cpp.
References mlir::StandardAttributes::Opaque.
getAttrData()
StringRef OpaqueAttr::getAttrData () const
Returns the raw attribute data of the opaque attribute.
Definition at line 344 of file Attributes.cpp.
getChecked()
OpaqueAttr OpaqueAttr::getChecked (Identifier dialect, StringRef attrData, Type type, Location location) static
Get or create a new OpaqueAttr with the provided dialect and string data.
If the given identifier is not a valid namespace for a dialect, then a null attribute is returned.
Definition at line 332 of file Attributes.cpp.
References mlir::Type::getContext(), and mlir::StandardAttributes::Opaque.
Referenced by extractSymbolReference().
getDialectNamespace()
Identifier OpaqueAttr::getDialectNamespace () const
Returns the dialect namespace of the opaque attribute.
Definition at line 339 of file Attributes.cpp.
kindof()
static bool mlir::OpaqueAttr::kindof (unsigned kind) inline static
Definition at line 427 of file Attributes.h.
References mlir::StandardAttributes::Opaque.
verifyConstructionInvariants()
LogicalResult OpaqueAttr::verifyConstructionInvariants (Optional< Location > loc, MLIRContext * context, Identifier dialect, StringRef attrData, Type type) static
Verify the construction of an opaque attribute.
Definition at line 347 of file Attributes.cpp.
References mlir::emitOptionalError(), mlir::Dialect::isValidNamespace(), mlir::Identifier::strref(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp