MLIR: mlir::quant::UniformQuantizedPerAxisType Class Reference
mlir::quant::UniformQuantizedPerAxisType Class Reference
Represents per-axis (also known as per-channel quantization).
#include "mlir/Dialect/QuantOps/QuantTypes.h"
Public Member Functions
ArrayRef< double > getScales () const
Gets the quantization scales.
ArrayRef< int64_t > getZeroPoints () const
Gets the storage values corresponding to the real value 0 in the affine equation.
int32_t getQuantizedDimension () const
Specifies the dimension of the Tensor's shape that the scales and zero_points correspond to.
bool isFixedPoint () const
Fixed point values are real numbers divided by a scale.
Static Public Member Functions
static UniformQuantizedPerAxisType get (unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Gets an instance of the type with all parameters specified but not checked.
static UniformQuantizedPerAxisType getChecked (unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax, Location location)
Gets an instance of the type with all specified parameters checked.
static LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *context, unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax)
Verifies construction invariants and issues errors/warnings.
static bool kindof (unsigned kind)
Support method to enable LLVM-style type casting.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Represents per-axis (also known as per-channel quantization).
Syntax synopsis: Per-axis, all parameters expressed: !quant<uniform[StorageType:ExpressedType:QuantizedDim]{QuantParams}> Per-axis, optional parameters omitted: !quant<uniform[StorageType]{Scale}>
StorageType: 'i'|'u' NumBits ExpressedType: 'f16', 'f32', 'bf16', 'f64' QuantizedDim: An integer value QuantParams: (Scale ':' ZeroPoint)+ Scale: A legal double value ZeroPoint: An integer value
Definition at line 331 of file QuantTypes.h.
Member Function Documentation
get()
UniformQuantizedPerAxisType UniformQuantizedPerAxisType::get (unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax) static
Gets an instance of the type with all parameters specified but not checked.
Definition at line 293 of file QuantTypes.cpp.
References mlir::Type::getContext(), and mlir::quant::QuantizationTypes::UniformQuantizedPerAxis.
getChecked()
UniformQuantizedPerAxisType UniformQuantizedPerAxisType::getChecked (unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax, Location location) static
Gets an instance of the type with all specified parameters checked.
Returns a nullptr convertible type on failure.
Definition at line 304 of file QuantTypes.cpp.
References mlir::Type::getContext(), and mlir::quant::QuantizationTypes::UniformQuantizedPerAxis.
Referenced by mlir::quant::fakeQuantAttrsToType(), and parseUniformType().
getQuantizedDimension()
int32_t UniformQuantizedPerAxisType::getQuantizedDimension () const
Specifies the dimension of the Tensor's shape that the scales and zero_points correspond to.
For example, a tensor t, with dims=[4, 3, 2, 1] with quantization params: scales=[1.0, 2.0, 3.0], zeroPoints=[1, 2, 3], quantizedDimension=1 will be quantized across the second dimension of t. t[:, 0, :, :] will have scale[0]=1.0, zero_point[0]=1 t[:, 1, :, :] will have scale[1]=2.0, zero_point[0]=2 t[:, 2, :, :] will have scale[2]=3.0, zero_point[0]=3
Definition at line 360 of file QuantTypes.cpp.
Referenced by printUniformQuantizedPerAxisType().
getScales()
ArrayRef< double > UniformQuantizedPerAxisType::getScales () const
Gets the quantization scales.
The scales designate the difference between the real values corresponding to consecutive quantized values differing by 1. The ith scale corresponds to the ith slice in the quantized_dimension.
Definition at line 352 of file QuantTypes.cpp.
Referenced by printUniformQuantizedPerAxisType().
getZeroPoints()
ArrayRef< int64_t > UniformQuantizedPerAxisType::getZeroPoints () const
Gets the storage values corresponding to the real value 0 in the affine equation.
The ith zero point corresponds to the ith slice in the quantized_dimension.
Definition at line 356 of file QuantTypes.cpp.
Referenced by printUniformQuantizedPerAxisType().
isFixedPoint()
bool mlir::quant::UniformQuantizedPerAxisType::isFixedPoint () const inline
Fixed point values are real numbers divided by a scale.
Currently, only signed storage types are treated as fixed point. A fixed point value can be obtained from an affine value by subtracting the zeroPoint. In the future, this may be explicit versus implied by type and zeroPoint.
Definition at line 391 of file QuantTypes.h.
kindof()
static bool mlir::quant::UniformQuantizedPerAxisType::kindof (unsigned kind) inline static
Support method to enable LLVM-style type casting.
Definition at line 361 of file QuantTypes.h.
References mlir::quant::QuantizationTypes::UniformQuantizedPerAxis.
verifyConstructionInvariants()
LogicalResult UniformQuantizedPerAxisType::verifyConstructionInvariants (Optional< Location > loc, MLIRContext * context, unsigned flags, Type storageType, Type expressedType, ArrayRef< double > scales, ArrayRef< int64_t > zeroPoints, int32_t quantizedDimension, int64_t storageTypeMin, int64_t storageTypeMax) static
Verifies construction invariants and issues errors/warnings.
Definition at line 315 of file QuantTypes.cpp.
References mlir::emitOptionalError(), mlir::failed(), mlir::failure(), mlir::Type::isa(), mlir::success(), and mlir::quant::QuantizedType::verifyConstructionInvariants().
The documentation for this class was generated from the following files:
include/mlir/Dialect/QuantOps/QuantTypes.h
lib/Dialect/QuantOps/IR/QuantTypes.cpp