MLIR: mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > Class Template Reference
mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > Class Template Reference
The class represents the base of a range of indexed_accessor_iterators.
#include "mlir/Support/STLExtras.h"
Classes
class iterator
An iterator element of this range.
Public Types
using RangeBaseT = indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >
Public Member Functions
indexed_accessor_range_base (iterator begin, iterator end)
indexed_accessor_range_base (const iterator_range< iterator > &range)
indexed_accessor_range_base (BaseT base, ptrdiff_t count)
iterator begin () const
iterator end () const
ReferenceT operator[] (unsigned index) const
size_t size () const
Return the size of this range.
bool empty () const
Return if the range is empty.
DerivedT slice (size_t n, size_t m) const
Drop the first N elements, and keep M elements.
DerivedT drop_front (size_t n=1) const
Drop the first n elements.
DerivedT drop_back (size_t n=1) const
Drop the last n elements.
DerivedT take_front (size_t n=1) const
Take the first n elements.
template<typename SVT , unsigned N>
operator SmallVector< SVT, N > () const
Allow conversion to SmallVector if necessary.
Protected Member Functions
indexed_accessor_range_base (const indexed_accessor_range_base &)=default
indexed_accessor_range_base (indexed_accessor_range_base &&)=default
indexed_accessor_range_base & operator= (const indexed_accessor_range_base &)=default
Protected Attributes
BaseT base
The base that owns the provided range of values.
ptrdiff_t count
The size from the owning range.
Detailed Description
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &>
class mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >
The class represents the base of a range of indexed_accessor_iterators.
It provides support for many different range functionalities, e.g. drop_front/slice/etc.. Derived range classes must implement the following static methods:
ReferenceT dereference_iterator(const BaseT &base, ptrdiff_t index)
Dereference an iterator pointing to the base object at the given index.
BaseT offset_base(const BaseT &base, ptrdiff_t index)
Return a new base that is offset from the provide base by 'index' elements.
Definition at line 197 of file STLExtras.h.
Member Typedef Documentation
RangeBaseT
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> using mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::RangeBaseT = indexed_accessor_range_base<DerivedT, BaseT, T, PointerT, ReferenceT>
Definition at line 200 of file STLExtras.h.
Constructor & Destructor Documentation
indexed_accessor_range_base() [1/5]
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (iterator begin, iterator end) inline
Definition at line 221 of file STLExtras.h.
indexed_accessor_range_base() [2/5]
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (const iterator_range< iterator > & range) inline
Definition at line 224 of file STLExtras.h.
indexed_accessor_range_base() [3/5]
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (BaseT base, ptrdiff_t count) inline
Definition at line 226 of file STLExtras.h.
indexed_accessor_range_base() [4/5]
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &) protected default
indexed_accessor_range_base() [5/5]
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &&) protected default
Member Function Documentation
begin()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> iterator mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin () const inline
Definition at line 229 of file STLExtras.h.
Referenced by mlir::OperationState::addOperands(), mlir::OperationState::addSuccessor(), buildMinMaxReductionSeq(), canonicalizeLoopBounds(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getInputs(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getInputsAndOutputBuffers(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getOutputBuffers(), mlir::Operation::operand_begin(), printBound(), mlir::Operation::result_begin(), mlir::Block::succ_begin(), mlir::Operation::successor_begin(), vectorizeOneOperation(), vectorizeRootOrTerminal(), and verifySuccessor().
drop_back()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> DerivedT mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_back (size_t n = 1) const inline
Drop the last n elements.
Definition at line 254 of file STLExtras.h.
drop_front()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> DerivedT mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front (size_t n = 1) const inline
Drop the first n elements.
Definition at line 249 of file STLExtras.h.
Referenced by expandAffineMap(), print(), mlir::printDimAndSymbolList(), and printLaunchOp().
empty()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> bool mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty () const inline
Return if the range is empty.
Definition at line 240 of file STLExtras.h.
Referenced by mlir::AffineDmaWaitOp::fold(), getElementPtrType(), print(), and verify().
end()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> iterator mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end () const inline
Definition at line 230 of file STLExtras.h.
Referenced by mlir::OperationState::addOperands(), mlir::OperationState::addSuccessor(), buildMinMaxReductionSeq(), canonicalizeLoopBounds(), mlir::Operation::operand_end(), printBound(), mlir::Operation::result_end(), mlir::Block::succ_end(), mlir::Operation::successor_end(), vectorizeOneOperation(), and vectorizeRootOrTerminal().
operator SmallVector< SVT, N >()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> template<typename SVT , unsigned N> mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator SmallVector< SVT, N > () const inline
Allow conversion to SmallVector if necessary.
TODO(riverriddle) Remove this when SmallVector accepts different range types in its constructor.
Definition at line 268 of file STLExtras.h.
operator=()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> indexed_accessor_range_base& mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator= (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &) protected default
operator[]()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> ReferenceT mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator[] (unsigned index) const inline
Definition at line 231 of file STLExtras.h.
size()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> size_t mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size () const inline
Return the size of this range.
Definition at line 237 of file STLExtras.h.
Referenced by mlir::AffineLoadOp::build(), mlir::AffineStoreOp::build(), canonicalizeLoopBounds(), canRegisterAlias(), mlir::Operation::create(), mlir::AffineDmaWaitOp::fold(), inferSubViewResultType(), mlir::LLVM::ModuleTranslation::lookupValues(), mlir::PatternRewriter::mergeBlocks(), parseLaunchOp(), print(), printDenseFloatElement(), mlir::printDimAndSymbolList(), mlir::LLVMTypeConverter::promoteMemRefDescriptors(), mlir::PatternRewriter::replaceOp(), mlir::detail::ConversionPatternRewriterImpl::replaceOp(), resolveSourceIndices(), mlir::detail::OperandStorage::setOperands(), and verify().
slice()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> DerivedT mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::slice (size_t n, size_t m) const inline
Drop the first N elements, and keep M elements.
Definition at line 243 of file STLExtras.h.
Referenced by printLaunchOp().
take_front()
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> DerivedT mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front (size_t n = 1) const inline
Take the first n elements.
Definition at line 260 of file STLExtras.h.
Referenced by expandAffineMap(), mlir::Operation::getNonSuccessorOperands(), print(), printDenseFloatElement(), mlir::printDimAndSymbolList(), and printLaunchOp().
Member Data Documentation
base
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> BaseT mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base protected
The base that owns the provided range of values.
Definition at line 279 of file STLExtras.h.
count
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &> ptrdiff_t mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::count protected
The size from the owning range.
Definition at line 281 of file STLExtras.h.
The documentation for this class was generated from the following file:
include/mlir/Support/STLExtras.h