MLIR: mlir::detail::PassOptions Class Reference
mlir::detail::PassOptions Class Reference
Base container class and manager for all pass options.
#include "mlir/Pass/PassOptions.h"
Classes
class ListOption
This class represents a specific pass option that contains a list of values of the provided data type.
class Option
This class represents a specific pass option, with a provided data type.
Public Member Functions
PassOptions ()=default
void copyOptionValuesFrom (const PassOptions &other)
Copy the option values from 'other' into 'this', where 'other' has the same options as 'this'.
LogicalResult parseFromString (StringRef options)
Parse options out as key=value pairs that can then be handed off to the llvm::cl command line passing infrastructure.
void print (raw_ostream &os)
Print the options held by this struct in a form that can be parsed via 'parseFromString'.
Detailed Description
Base container class and manager for all pass options.
Definition at line 28 of file PassOptions.h.
Constructor & Destructor Documentation
PassOptions()
mlir::detail::PassOptions::PassOptions () default
Referenced by mlir::detail::PassOptions::ListOption< DataType >::operator->().
Member Function Documentation
copyOptionValuesFrom()
void detail::PassOptions::copyOptionValuesFrom (const PassOptions & other)
Copy the option values from 'other' into 'this', where 'other' has the same options as 'this'.
Copy the option values from 'other'.
Definition at line 83 of file PassRegistry.cpp.
References options.
Referenced by mlir::detail::PassOptions::ListOption< DataType >::operator->().
parseFromString()
LogicalResult detail::PassOptions::parseFromString (StringRef options)
Parse options out as key=value pairs that can then be handed off to the llvm::cl command line passing infrastructure.
Everything is space separated.
Definition at line 91 of file PassRegistry.cpp.
References mlir::failure(), options, and mlir::success().
Referenced by mlir::detail::PassOptions::ListOption< DataType >::operator->().
print()
void detail::PassOptions::print (raw_ostream & os)
Print the options held by this struct in a form that can be parsed via 'parseFromString'.
Definition at line 134 of file PassRegistry.cpp.
References mlir::PassRegistryEntry::addToPipeline(), mlir::failed(), mlir::failure(), mlir::interleave(), mlir::OpPassManager::nest(), options, passPipelineRegistry, passRegistry, and mlir::success().
Referenced by mlir::detail::PassOptions::ListOption< DataType >::operator->(), and mlir::detail::PassOptions::Option< DataType >::Option().
The documentation for this class was generated from the following files:
include/mlir/Pass/PassOptions.h
lib/Pass/PassRegistry.cpp