MLIR: mlir::FuncOp Class Reference
mlir::FuncOp Class Reference
FuncOp represents a function, or an operation containing one region that forms a CFG(Control Flow Graph).
#include "mlir/IR/Function.h"
Public Member Functions
void print (OpAsmPrinter &p)
LogicalResult verify ()
void eraseArgument (unsigned argIndex)
Erase a single argument at argIndex.
void eraseArguments (ArrayRef< unsigned > argIndices)
Erases the arguments listed in argIndices.
FunctionType getType ()
Returns the type of this function.
void setType (FunctionType newType)
Change the type of this function in place.
FuncOp clone (BlockAndValueMapping &mapper)
Create a deep copy of this function and all of its blocks, remapping any operands that use values outside of the function using the map that is provided (leaving them alone if no entry is present).
FuncOp clone ()
void cloneInto (FuncOp dest, BlockAndValueMapping &mapper)
Clone the internal blocks and attributes from this function into dest.
Block * addEntryBlock ()
Add an entry block to an empty function, and set up the block arguments to match the signature of the function.
Block * addBlock ()
Add a normal block to the end of the function's block list.
Region * getCallableRegion ()
Returns the region on the current operation that is callable.
ArrayRef< Type > getCallableResults ()
Returns the results types that the callable region produces when executed.
Public Member Functions inherited from mlir::Op< FuncOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::Symbol, OpTrait::FunctionLike, CallableOpInterface::Trait >
Operation * getOperation ()
Return the operation that this refers to.
FuncOp clone ()
Create a deep copy of this operation.
FuncOp cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Dialect * getDialect ()
Return the dialect that this refers to.
Region * getParentRegion ()
Return the parent Region of this operation.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow implicit conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * getOperation ()
Return the operation that this refers to.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
template<typename OpTy >
OpTy getParentOfType ()
Return the closest surrounding parent operation that is of type 'OpTy'.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState, OpPrintingFlags flags=llvm::None)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
void setLoc (Location loc)
ArrayRef< NamedAttribute > getAttrs ()
Return all of the attributes on this operation.
dialect_attr_range getDialectAttrs ()
Return a range corresponding to the dialect attributes for this operation.
dialect_attr_iterator dialect_attr_begin ()
dialect_attr_iterator dialect_attr_end ()
Attribute getAttr (StringRef name)
Return an attribute with the specified name.
template<typename AttrClass >
AttrClass getAttrOfType (StringRef name)
If the operation has an attribute of the specified type, return it.
void setAttr (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setAttr (StringRef name, Attribute value)
void setAttrs (ArrayRef< NamedAttribute > attributes)
Set the attributes held by this operation.
void setAttrs (NamedAttributeList newAttrs)
template<typename DialectAttrs >
void setDialectAttrs (DialectAttrs &&attrs)
Set the dialect attributes for this operation, and preserve all dependent.
NamedAttributeList::RemoveResult removeAttr (Identifier name)
Remove the attribute with the specified name if it exists.
NamedAttributeList::RemoveResult removeAttr (StringRef name)
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk the operation in postorder, calling the callback for each nested operation(including this one).
Public Member Functions inherited from mlir::FoldingHook< FuncOp, llvm::is_one_of< OpTrait::OneResult< FuncOp >, OpTrait::ZeroOperands< FuncOp >... >::value >
LogicalResult fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This hook implements a generalized folder for this operation.
Static Public Member Functions
static StringRef getOperationName ()
static FuncOp create (Location location, StringRef name, FunctionType type, ArrayRef< NamedAttribute > attrs={})
static FuncOp create (Location location, StringRef name, FunctionType type, iterator_range< dialect_attr_iterator > attrs)
static FuncOp create (Location location, StringRef name, FunctionType type, ArrayRef< NamedAttribute > attrs, ArrayRef< NamedAttributeList > argAttrs)
static void build (Builder *builder, OperationState &result, StringRef name, FunctionType type, ArrayRef< NamedAttribute > attrs)
static void build (Builder *builder, OperationState &result, StringRef name, FunctionType type, ArrayRef< NamedAttribute > attrs, ArrayRef< NamedAttributeList > argAttrs)
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Operation hooks.
Static Public Member Functions inherited from mlir::Op< FuncOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::Symbol, OpTrait::FunctionLike, CallableOpInterface::Trait >
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
static ParseResult parseAssembly (OpAsmParser &parser, OperationState &result)
This is the hook used by the AsmParser to parse the custom form of this op from an .mlir file.
static void printAssembly (Operation *op, OpAsmPrinter &p)
This is the hook used by the AsmPrinter to emit this to the .mlir file.
static LogicalResult verifyInvariants (Operation *op)
This is the hook that checks whether or not this operation is well formed according to the invariants of its opcode.
static AbstractOperation::OperationProperties getOperationProperties ()
static ConcreteOpType getFromOpaquePointer (const void *pointer)
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (OwningRewritePatternList &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Static Public Member Functions inherited from mlir::OpTrait::ZeroOperands< FuncOp >
static LogicalResult verifyTrait (Operation *op)
Static Public Member Functions inherited from mlir::FoldingHook< FuncOp, llvm::is_one_of< OpTrait::OneResult< FuncOp >, OpTrait::ZeroOperands< FuncOp >... >::value >
static LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This is an implementation detail of the constant folder hook for AbstractOperation.
Friends
class OpTrait::FunctionLike< FuncOp >
Additional Inherited Members
Public Types inherited from mlir::Op< FuncOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::Symbol, OpTrait::FunctionLike, CallableOpInterface::Trait >
using ConcreteOpType = FuncOp
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
Public Types inherited from mlir::OpState
using dialect_attr_iterator = Operation::dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
using dialect_attr_range = Operation::dialect_attr_range
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
void print (OpAsmPrinter &p)
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< FuncOp, ZeroOperands >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Unless overridden, the custom assembly form of an op is always rejected.
Static Protected Member Functions inherited from mlir::OpTrait::TraitBase< FuncOp, ZeroOperands >
static LogicalResult verifyTrait (Operation *op)
Provide default implementations of trait hooks.
static AbstractOperation::OperationProperties getTraitProperties ()
Detailed Description
FuncOp represents a function, or an operation containing one region that forms a CFG(Control Flow Graph).
The region of a function is not allowed to implicitly capture global values, and all external references must use Function arguments or attributes that establish a symbolic connection(e.g. symbols referenced by name via a string attribute).
Definition at line 32 of file Function.h.
Member Function Documentation
addBlock()
Block * FuncOp::addBlock ()
Add a normal block to the end of the function's block list.
The function should at least already have an entry block.
Definition at line 154 of file Function.cpp.
Referenced by setType().
addEntryBlock()
Block * FuncOp::addEntryBlock ()
Add an entry block to an empty function, and set up the block arguments to match the signature of the function.
The newly inserted entry block is returned.
Definition at line 144 of file Function.cpp.
References getType().
Referenced by setType().
build() [1/2]
void FuncOp::build (Builder * builder, OperationState & result, StringRef name, FunctionType type, ArrayRef< NamedAttribute > attrs) static
Definition at line 49 of file Function.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::TypeAttr::get(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), and mlir::impl::getTypeAttrName().
Referenced by build(), create(), and getOperationName().
build() [2/2]
void FuncOp::build (Builder * builder, OperationState & result, StringRef name, FunctionType type, ArrayRef< NamedAttribute > attrs, ArrayRef< NamedAttributeList > argAttrs) static
Definition at line 58 of file Function.cpp.
References mlir::OperationState::addAttribute(), build(), mlir::impl::getArgAttrName(), and mlir::FunctionType::getNumInputs().
clone() [1/2]
FuncOp FuncOp::clone (BlockAndValueMapping & mapper)
Create a deep copy of this function and all of its blocks, remapping any operands that use values outside of the function using the map that is provided (leaving them alone if no entry is present).
If the mapper contains entries for function arguments, these arguments are not included in the new function. Replaces references to cloned sub-values with the corresponding value that is copied, and adds those mappings to the mapper.
Replaces references to cloned sub-values with the corresponding value that is copied, and adds those mappings to the mapper.
Set the argument attributes for arguments that aren't being replaced.
Clone the current function into the new one and return it.
Definition at line 181 of file Function.cpp.
References cloneInto(), mlir::Operation::cloneWithoutRegions(), mlir::BlockAndValueMapping::contains(), mlir::FunctionType::get(), mlir::impl::getArgAttrs(), mlir::OpState::getContext(), mlir::FunctionType::getInput(), mlir::FunctionType::getNumInputs(), mlir::Op< FuncOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::Symbol, OpTrait::FunctionLike, CallableOpInterface::Trait >::getOperation(), mlir::FunctionType::getResults(), getType(), and setType().
clone() [2/2]
FuncOp FuncOp::clone ()
Definition at line 210 of file Function.cpp.
Referenced by setType().
cloneInto()
void FuncOp::cloneInto (FuncOp dest, BlockAndValueMapping & mapper)
Clone the internal blocks and attributes from this function into dest.
Clone the internal blocks from this function into dest and all attributes from this function to dest.
Any cloned blocks are appended to the back of dest. This function asserts that the attributes of the current function and dest are compatible.
Definition at line 162 of file Function.cpp.
References mlir::DictionaryAttr::get(), mlir::OpState::getAttrs(), mlir::OpState::getContext(), mlir::Op< ConcreteType, Traits >::getOperation(), and mlir::Operation::setAttrs().
Referenced by clone(), and setType().
create() [1/3]
FuncOp FuncOp::create (Location location, StringRef name, FunctionType type, ArrayRef< NamedAttribute > attrs = {}) static
Definition at line 29 of file Function.cpp.
References build(), mlir::Operation::create(), and mlir::Attribute::getContext().
Referenced by create(), and getOperationName().
create() [2/3]
FuncOp FuncOp::create (Location location, StringRef name, FunctionType type, iterator_range< dialect_attr_iterator > attrs) static
Definition at line 36 of file Function.cpp.
References create().
create() [3/3]
FuncOp FuncOp::create (Location location, StringRef name, FunctionType type, ArrayRef< NamedAttribute > attrs, ArrayRef< NamedAttributeList > argAttrs) static
Definition at line 41 of file Function.cpp.
References create().
eraseArgument()
void mlir::FuncOp::eraseArgument (unsigned argIndex) inline
Erase a single argument at argIndex.
Definition at line 61 of file Function.h.
References eraseArguments().
eraseArguments()
void FuncOp::eraseArguments (ArrayRef< unsigned > argIndices)
Erases the arguments listed in argIndices.
argIndices is allowed to have duplicates and can be in any order.
Definition at line 108 of file Function.cpp.
References mlir::Block::eraseArgument(), mlir::FunctionType::get(), mlir::impl::getArgAttrDict(), mlir::OpState::getContext(), getType(), and setType().
Referenced by eraseArgument().
getCallableRegion()
Region* mlir::FuncOp::getCallableRegion () inline
Returns the region on the current operation that is callable.
This may return null in the case of an external callable object, e.g. an external function.
Definition at line 128 of file Function.h.
getCallableResults()
ArrayRef<Type> mlir::FuncOp::getCallableResults () inline
Returns the results types that the callable region produces when executed.
Definition at line 131 of file Function.h.
References mlir::FunctionType::getResults(), and getType().
getOperationName()
static StringRef mlir::FuncOp::getOperationName () inline static
Definition at line 39 of file Function.h.
References build(), create(), parse(), print(), and verify().
getType()
FunctionType mlir::FuncOp::getType () inline
Returns the type of this function.
Definition at line 67 of file Function.h.
References mlir::impl::getTypeAttrName().
Referenced by addEntryBlock(), clone(), mlir::TypeConverter::convertSignatureArg(), mlir::SPIRVTypeConverter::convertType(), createGlobalVariableForArg(), eraseArguments(), getCallableResults(), getLastStructuredControlFlowOpMergeBlock(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), print(), setType(), verify(), and verify().
parse()
ParseResult FuncOp::parse (OpAsmParser & parser, OperationState & result) static
Operation hooks.
Parsing/Printing methods.
Definition at line 71 of file Function.cpp.
References mlir::Builder::getFunctionType(), and mlir::impl::parseFunctionLikeOp().
Referenced by getOperationName().
print()
void FuncOp::print (OpAsmPrinter & p)
Definition at line 82 of file Function.cpp.
References mlir::FunctionType::getInputs(), mlir::FunctionType::getResults(), getType(), and mlir::impl::printFunctionLikeOp().
Referenced by fuseLinalgOpsGreedily(), getOperationName(), and vectorizeRootMatch().
setType()
void mlir::FuncOp::setType (FunctionType newType) inline
Change the type of this function in place.
This is an extremely dangerous operation and it is up to the caller to ensure that this is legal for this function, and to restore invariants:
the entry block args must be updated to match the function params.
the argument/result attributes may need an update: if the new type has less parameters we drop the extra attributes, if there are more parameters they won't have any attributes.
Definition at line 80 of file Function.h.
References addBlock(), addEntryBlock(), clone(), cloneInto(), mlir::TypeAttr::get(), mlir::impl::getArgAttrName(), mlir::FunctionType::getNumInputs(), mlir::FunctionType::getNumResults(), mlir::impl::getResultAttrName(), getType(), mlir::impl::getTypeAttrName(), mlir::OpState::removeAttr(), and mlir::OpState::setAttr().
Referenced by clone(), mlir::TypeConverter::convertSignatureArg(), mlir::SPIRVTypeConverter::convertType(), eraseArguments(), and lowerEntryPointABIAttr().
verify()
LogicalResult FuncOp::verify ()
Definition at line 88 of file Function.cpp.
References mlir::OpState::emitOpError(), mlir::Block::getArgument(), mlir::FunctionType::getInputs(), mlir::Block::getNumArguments(), getType(), mlir::BlockArgument::getType(), and mlir::success().
Referenced by getOperationName().
Friends And Related Function Documentation
OpTrait::FunctionLike< FuncOp >
friend class OpTrait::FunctionLike< FuncOp > friend
Definition at line 135 of file Function.h.
The documentation for this class was generated from the following files:
include/mlir/IR/Function.h
lib/IR/Function.cpp