MLIR: mlir::quantizer::CAGAnchorNode Class Reference
mlir::quantizer::CAGAnchorNode Class Reference abstract
Anchor nodes represent points in the source IR where we may choose to introduce a type transition.
#include "mlir/Quantizer/Support/ConstraintAnalysisGraph.h"
Public Types
enum TypeTransformRule { TypeTransformRule::Direct, TypeTransformRule::DirectStorage, TypeTransformRule::ExpressedOnly }
Public Types inherited from mlir::quantizer::CAGNode
enum Kind {
Kind::Anchor, Kind::OperandAnchor, Kind::ResultAnchor, Kind::LastAnchor = ResultAnchor,
Kind::Constraint, Kind::SolveUniformConstraint, Kind::UniformPropagateExplicitScale, Kind::LastConstraint = UniformPropagateExplicitScale
}
using node_vector = SmallVector< CAGNode *, 1 >
using iterator = node_vector::iterator
using const_iterator = node_vector::const_iterator
Public Member Functions
CAGUniformMetadata & getUniformMetadata ()
Metadata for solving uniform quantization params.
const CAGUniformMetadata & getUniformMetadata () const
virtual Operation * getOp () const =0
virtual Value getValue () const =0
void propagate (SolverContext &solverContext, const TargetConfiguration &config) override
void printLabel (raw_ostream &os) const override
Prints the node label, suitable for one-line display.
Type getTransformedType ()
Given the anchor metadata and resolved solutions, chooses the most salient and returns an appropriate type to represent it.
TypeTransformRule getTypeTransformRule () const
void setTypeTransformRule (TypeTransformRule r)
Type getOriginalType () const
Gets the Type that was defined for this anchor at the time of construction.
Public Member Functions inherited from mlir::quantizer::CAGNode
virtual ~CAGNode ()=default
Kind getKind () const
int getNodeId () const
Unique id of the node within the slice.
bool isDirty () const
Whether the node is dirty, requiring one or more calls to propagate().
void markDirty ()
void clearDirty ()
const_iterator begin () const
Iterator over this node's children (outgoing) nodes.
const_iterator end () const
iterator begin ()
iterator end ()
const_iterator incoming_begin () const
Iterator over this parents (incoming) nodes.
const_iterator incoming_end () const
iterator incoming_begin ()
iterator incoming_end ()
template<typename T >
void findChildrenOfKind (SmallVectorImpl< T *> &found)
void replaceIncoming (CAGNode *otherNode)
Replaces this node by rerouting any parent nodes to have otherNode as a child.
void addOutgoing (CAGNode *toNode)
Adds an outgoing connection to this node (and corresponding back incoming connection).
bool isOrphan () const
Whether this node is an orphan (has no incoming or outgoing connections).
Static Public Member Functions
static bool classof (const CAGNode *n)
Protected Member Functions
CAGAnchorNode (Kind kind, Type originalType)
Protected Member Functions inherited from mlir::quantizer::CAGNode
CAGNode (Kind kind)
Detailed Description
Anchor nodes represent points in the source IR where we may choose to introduce a type transition.
These include operands, results, arguments returns, etc.
Definition at line 132 of file ConstraintAnalysisGraph.h.
Member Enumeration Documentation
TypeTransformRule
enum mlir::quantizer::CAGAnchorNode::TypeTransformRule strong
Enumerator
Direct
The owning op directly supports all transformed types.
In practice, this means that the op supports QuantizedType for this anchor.
DirectStorage
The type of this anchor should be set to the QuantizedType storage type.
This will only be valid if constraints are such that all inputs/outputs converge to the same storage type (i.e. coupled).
ExpressedOnly
The anchor must only be typed based on the expressed type.
This is used for ops that do not natively support quantization, and suitable casts will be inserted.
Definition at line 134 of file ConstraintAnalysisGraph.h.
Constructor & Destructor Documentation
CAGAnchorNode()
mlir::quantizer::CAGAnchorNode::CAGAnchorNode (Kind kind, Type originalType) inline protected
Definition at line 181 of file ConstraintAnalysisGraph.h.
Member Function Documentation
classof()
static bool mlir::quantizer::CAGAnchorNode::classof (const CAGNode * n) inline static
Definition at line 159 of file ConstraintAnalysisGraph.h.
References mlir::quantizer::CAGNode::Anchor, mlir::quantizer::CAGNode::getKind(), mlir::quantizer::CAGNode::LastAnchor, mlir::quantizer::CAGNode::printLabel(), and mlir::quantizer::CAGNode::propagate().
getOp()
virtual Operation* mlir::quantizer::CAGAnchorNode::getOp () const pure virtual
Implemented in mlir::quantizer::CAGResultAnchor, and mlir::quantizer::CAGOperandAnchor.
getOriginalType()
Type mlir::quantizer::CAGAnchorNode::getOriginalType () const inline
Gets the Type that was defined for this anchor at the time of construction.
Definition at line 178 of file ConstraintAnalysisGraph.h.
Referenced by validateTypeConversion().
getTransformedType()
Type CAGAnchorNode::getTransformedType ()
Given the anchor metadata and resolved solutions, chooses the most salient and returns an appropriate type to represent it.
Definition at line 143 of file ConstraintAnalysisGraph.cpp.
getTypeTransformRule()
TypeTransformRule mlir::quantizer::CAGAnchorNode::getTypeTransformRule () const inline
Definition at line 172 of file ConstraintAnalysisGraph.h.
Referenced by validateTypeConversion().
getUniformMetadata() [1/2]
CAGUniformMetadata& mlir::quantizer::CAGAnchorNode::getUniformMetadata () inline
Metadata for solving uniform quantization params.
Definition at line 151 of file ConstraintAnalysisGraph.h.
Referenced by mlir::quantizer::UniformConstraintsBuilder::applyStats(), and mlir::quantizer::UniformConstraintsBuilder::clamp().
getUniformMetadata() [2/2]
const CAGUniformMetadata& mlir::quantizer::CAGAnchorNode::getUniformMetadata () const inline
Definition at line 152 of file ConstraintAnalysisGraph.h.
getValue()
virtual Value mlir::quantizer::CAGAnchorNode::getValue () const pure virtual
Implemented in mlir::quantizer::CAGResultAnchor, and mlir::quantizer::CAGOperandAnchor.
printLabel()
void CAGAnchorNode::printLabel (raw_ostream & os) const override virtual
Prints the node label, suitable for one-line display.
Reimplemented from mlir::quantizer::CAGNode.
Reimplemented in mlir::quantizer::CAGResultAnchor, and mlir::quantizer::CAGOperandAnchor.
Definition at line 155 of file ConstraintAnalysisGraph.cpp.
Referenced by mlir::quantizer::CAGOperandAnchor::printLabel(), and mlir::quantizer::CAGResultAnchor::printLabel().
propagate()
void CAGAnchorNode::propagate (SolverContext & solverContext, const TargetConfiguration & config) override virtual
Reimplemented from mlir::quantizer::CAGNode.
Definition at line 136 of file ConstraintAnalysisGraph.cpp.
References mlir::quantizer::CAGNode::markDirty().
setTypeTransformRule()
void mlir::quantizer::CAGAnchorNode::setTypeTransformRule (TypeTransformRule r) inline
Definition at line 174 of file ConstraintAnalysisGraph.h.
The documentation for this class was generated from the following files:
include/mlir/Quantizer/Support/ConstraintAnalysisGraph.h
lib/Quantizer/Support/ConstraintAnalysisGraph.cpp