MLIR: mlir::TupleType Class Reference
mlir::TupleType Class Reference
Tuple types represent a collection of other types.
#include "mlir/IR/StandardTypes.h"
Public Types
using iterator = ArrayRef< Type >::iterator
Iterate over the held elements.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
ArrayRef< Type > getTypes () const
Return the elements types for this tuple.
void getFlattenedTypes (SmallVectorImpl< Type > &types)
Accumulate the types contained in this tuple and tuples nested within it.
size_t size () const
Return the number of held types.
iterator begin () const
iterator end () const
Type getType (size_t index) const
Return the element type at index 'index'.
Static Public Member Functions
static TupleType get (ArrayRef< Type > elementTypes, MLIRContext *context)
Get or create a new TupleType with the provided element types.
static TupleType get (MLIRContext *context)
Get or create an empty tuple type.
static bool kindof (unsigned kind)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Tuple types represent a collection of other types.
Note: This type merely provides a common mechanism for representing tuples in MLIR. It is up to dialect authors to provides operations for manipulating them, e.g. extract_tuple_element. When possible, users should prefer multi-result operations in the place of tuples.
Definition at line 527 of file StandardTypes.h.
Member Typedef Documentation
iterator
using mlir::TupleType::iterator = ArrayRef<Type>::iterator
Iterate over the held elements.
Definition at line 552 of file StandardTypes.h.
Member Function Documentation
begin()
iterator mlir::TupleType::begin () const inline
Definition at line 553 of file StandardTypes.h.
end()
iterator mlir::TupleType::end () const inline
Definition at line 554 of file StandardTypes.h.
get() [1/2]
TupleType TupleType::get (ArrayRef< Type > elementTypes, MLIRContext * context) static
Get or create a new TupleType with the provided element types.
TupleType.
Assumes the arguments define a well-formed type.
Get or create a new TupleType with the provided element types. Assumes the arguments define a well-formed type.
Definition at line 643 of file StandardTypes.cpp.
References mlir::StandardTypes::Tuple.
Referenced by mlir::Operation::create(), generateExtractSlicesOpResultType(), mlir::Builder::getTupleType(), parseSymbol(), parseTupleOp(), and mlir::Value::setType().
get() [2/2]
static TupleType mlir::TupleType::get (MLIRContext * context) inline static
Get or create an empty tuple type.
Definition at line 537 of file StandardTypes.h.
References mlir::getFlattenedTypes().
getFlattenedTypes()
void TupleType::getFlattenedTypes (SmallVectorImpl< Type > & types)
Accumulate the types contained in this tuple and tuples nested within it.
Note that this only flattens nested tuples, not any other container type, e.g. a tuple<i32, tensor<i32>, tuple<f32, tuple<i64>>> is flattened to (i32, tensor<i32>, f32, i64)
Definition at line 654 of file StandardTypes.cpp.
Referenced by mlir::getFlattenedTypes().
getType()
Type mlir::TupleType::getType (size_t index) const inline
Return the element type at index 'index'.
Definition at line 557 of file StandardTypes.h.
Referenced by isValidExtractOrInsertSlicesType(), parseTupleGetOp(), and verify().
getTypes()
ArrayRef< Type > TupleType::getTypes () const
Return the elements types for this tuple.
Definition at line 648 of file StandardTypes.cpp.
Referenced by isValidExtractOrInsertSlicesType().
kindof()
static bool mlir::TupleType::kindof (unsigned kind) inline static
Definition at line 562 of file StandardTypes.h.
References mlir::StandardTypes::Tuple.
size()
size_t TupleType::size () const
Return the number of held types.
Return the number of element types.
Definition at line 664 of file StandardTypes.cpp.
Referenced by generateTransferOpSlices(), isValidExtractOrInsertSlicesType(), parseTupleGetOp(), and verify().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp