MLIR: mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type > Class Template Reference
mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type > Class Template Reference
This template specialization defines the foldHook as used by AbstractOperation for single-result operations.
#include "mlir/IR/OpDefinition.h"
Public Member Functions
operator Value ()
If the operation returns a single value, then the Op can be implicitly converted to an Value.
OpFoldResult fold (ArrayRef< Attribute > operands)
This hook implements a generalized folder for this operation.
Static Public Member Functions
static LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This is an implementation detail of the constant folder hook for AbstractOperation.
Detailed Description
template<typename ConcreteType, bool isSingleResult>
class mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >
This template specialization defines the foldHook as used by AbstractOperation for single-result operations.
This gives the hook a nicer signature that is easier to implement.
Definition at line 305 of file OpDefinition.h.
Member Function Documentation
fold()
template<typename ConcreteType , bool isSingleResult> OpFoldResult mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::fold (ArrayRef< Attribute > operands) inline
This hook implements a generalized folder for this operation.
Operations can implement this to provide simplifications rules that are applied by the Builder::createOrFold API and the canonicalization pass.
This is an intentionally limited interface - implementations of this hook can only perform the following changes to the operation:
They can leave the operation alone and without changing the IR, and return nullptr.
They can mutate the operation in place, without changing anything else in the IR. In this case, return the operation itself.
They can return an existing SSA value that can be used instead of the operation. In this case, return that value. The caller will remove the operation and use that result instead.
This allows expression of some simple in-place canonicalizations (e.g. "x+0 -> x", "min(x,y,x,z) -> min(x,y,z)", "x+y-x -> y", etc), as well as generalized constant folding.
If not overridden, this fallback implementation always fails to fold.
Definition at line 350 of file OpDefinition.h.
References mlir::OpTrait::impl::verifyAtLeastNOperands(), mlir::OpTrait::impl::verifyAtLeastNResults(), mlir::OpTrait::impl::verifyIsTerminator(), mlir::OpTrait::impl::verifyNOperands(), mlir::OpTrait::impl::verifyNResults(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOneResult(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreIntegerLike(), mlir::OpTrait::impl::verifyOperandSizeAttr(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreIntegerLike(), mlir::OpTrait::impl::verifyResultSizeAttr(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), mlir::OpTrait::impl::verifyZeroOperands(), and mlir::OpTrait::impl::verifyZeroResult().
foldHook()
template<typename ConcreteType , bool isSingleResult> static LogicalResult mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::foldHook (Operation * op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > & results) inline static
This is an implementation detail of the constant folder hook for AbstractOperation.
Definition at line 316 of file OpDefinition.h.
References mlir::failure(), mlir::Operation::getResult(), and mlir::success().
operator Value()
template<typename ConcreteType , bool isSingleResult> mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::operator Value () inline
If the operation returns a single value, then the Op can be implicitly converted to an Value.
This yields the value of the only result.
Definition at line 310 of file OpDefinition.h.
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h