MLIR: mlir::ConstantIndexOp Class Reference
mlir::ConstantIndexOp Class Reference
This is a refinement of the "constant" op for the case where it is returning an integer value of Index type.
#include "mlir/Dialect/StandardOps/Ops.h"
Public Member Functions
int64_t getValue ()
Static Public Member Functions
static void build (Builder *builder, OperationState &result, int64_t value)
Build a constant int op producing an index.
static bool classof (Operation *op)
ConstantIndexOp only matches values whose result type is Index.
Detailed Description
This is a refinement of the "constant" op for the case where it is returning an integer value of Index type.
%1 = "std.constant"(){value: 99} : () -> index
Definition at line 122 of file Ops.h.
Member Function Documentation
build()
void ConstantIndexOp::build (Builder * builder, OperationState & result, int64_t value) static
Build a constant int op producing an index.
Definition at line 1128 of file Ops.cpp.
References mlir::PatternRewriter::eraseOp(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), and mlir::Value::getUsers().
classof()
bool ConstantIndexOp::classof (Operation * op) static
ConstantIndexOp only matches values whose result type is Index.
Definition at line 1124 of file Ops.cpp.
References mlir::Operation::getResult(), mlir::Value::getType(), and mlir::Type::isIndex().
getValue()
int64_t mlir::ConstantIndexOp::getValue () inline
Definition at line 129 of file Ops.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/StandardOps/Ops.h
lib/Dialect/StandardOps/Ops.cpp