MLIR: mlir::tblgen::EnumAttr Class Reference
mlir::tblgen::EnumAttr Class Reference
#include "mlir/TableGen/Attribute.h"
Public Member Functions
EnumAttr (const llvm::Record *record)
EnumAttr (const llvm::Record &record)
EnumAttr (const llvm::DefInit *init)
bool isBitEnum () const
StringRef getEnumClassName () const
StringRef getCppNamespace () const
StringRef getUnderlyingType () const
StringRef getUnderlyingToSymbolFnName () const
StringRef getStringToSymbolFnName () const
StringRef getSymbolToStringFnName () const
StringRef getSymbolToStringFnRetType () const
StringRef getMaxEnumValFnName () const
std::vector< EnumAttrCase > getAllCases () const
Public Member Functions inherited from mlir::tblgen::Attribute
Attribute (const llvm::Record *record)
Attribute (const llvm::DefInit *init)
StringRef getStorageType () const
StringRef getReturnType () const
StringRef getConvertFromStorageCall () const
bool isConstBuildable () const
StringRef getConstBuilderTemplate () const
Attribute getBaseAttr () const
bool hasDefaultValue () const
StringRef getDefaultValue () const
bool isOptional () const
bool isDerivedAttr () const
bool isTypeAttr () const
bool isEnumAttr () const
StringRef getAttrDefName () const
StringRef getDerivedCodeBody () const
Public Member Functions inherited from mlir::tblgen::AttrConstraint
AttrConstraint (const llvm::Record *record)
bool isSubClassOf (StringRef className) const
Public Member Functions inherited from mlir::tblgen::Constraint
Constraint (const llvm::Record *record)
bool operator== (const Constraint &that)
bool operator!= (const Constraint &that)
Pred getPredicate () const
std::string getConditionTemplate () const
StringRef getDescription () const
Kind getKind () const
Static Public Member Functions
static bool classof (const Attribute *attr)
Static Public Member Functions inherited from mlir::tblgen::AttrConstraint
static bool classof (const Constraint *c)
Additional Inherited Members
Public Types inherited from mlir::tblgen::Constraint
enum Kind { CK_Attr, CK_Region, CK_Type, CK_Uncategorized }
Protected Member Functions inherited from mlir::tblgen::Constraint
Constraint (Kind kind, const llvm::Record *record)
Protected Attributes inherited from mlir::tblgen::Constraint
const llvm::Record * def
Detailed Description
Definition at line 147 of file Attribute.h.
Constructor & Destructor Documentation
EnumAttr() [1/3]
tblgen::EnumAttr::EnumAttr (const llvm::Record * record) explicit
Definition at line 163 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
EnumAttr() [2/3]
tblgen::EnumAttr::EnumAttr (const llvm::Record & record) explicit
Definition at line 168 of file Attribute.cpp.
EnumAttr() [3/3]
tblgen::EnumAttr::EnumAttr (const llvm::DefInit * init) explicit
Definition at line 170 of file Attribute.cpp.
Member Function Documentation
classof()
bool tblgen::EnumAttr::classof (const Attribute * attr) static
Definition at line 173 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
getAllCases()
std::vector< tblgen::EnumAttrCase > tblgen::EnumAttr::getAllCases () const
Definition at line 211 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getCppNamespace()
StringRef tblgen::EnumAttr::getCppNamespace () const
Definition at line 183 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getEnumClassName()
StringRef tblgen::EnumAttr::getEnumClassName () const
Definition at line 179 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getMaxEnumValFnName()
StringRef tblgen::EnumAttr::getMaxEnumValFnName () const
Definition at line 207 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getStringToSymbolFnName()
StringRef tblgen::EnumAttr::getStringToSymbolFnName () const
Definition at line 195 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getSymbolToStringFnName()
StringRef tblgen::EnumAttr::getSymbolToStringFnName () const
Definition at line 199 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getSymbolToStringFnRetType()
StringRef tblgen::EnumAttr::getSymbolToStringFnRetType () const
Definition at line 203 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getUnderlyingToSymbolFnName()
StringRef tblgen::EnumAttr::getUnderlyingToSymbolFnName () const
Definition at line 191 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
getUnderlyingType()
StringRef tblgen::EnumAttr::getUnderlyingType () const
Definition at line 187 of file Attribute.cpp.
References mlir::tblgen::Constraint::def.
isBitEnum()
bool tblgen::EnumAttr::isBitEnum () const
Definition at line 177 of file Attribute.cpp.
References mlir::tblgen::AttrConstraint::isSubClassOf().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Attribute.h
lib/TableGen/Attribute.cpp