MLIR: mlir::detail::OpToOpPassAdaptorParallel Class Reference
mlir::detail::OpToOpPassAdaptorParallel Class Reference
An adaptor pass used to run operation passes over nested operations asynchronously across multiple threads.
#include "Pass/PassDetail.h"
Public Member Functions
OpToOpPassAdaptorParallel (OpPassManager &&mgr)
void runOnOperation () override
Run the held pipeline over all operations.
MutableArrayRef< SmallVector< OpPassManager, 1 > > getParallelPassManagers ()
Return the async pass managers held by this parallel adaptor.
Public Member Functions inherited from mlir::Pass
virtual ~Pass ()=default
const PassID * getPassID () const
Returns the unique identifier that corresponds to this pass.
const PassInfo * lookupPassInfo () const
Returns the pass info for this pass.
Optional< StringRef > getOpName () const
Returns the name of the operation that this pass operates on, or None if this is a generic OperationPass.
LogicalResult initializeOptions (StringRef options)
Attempt to initialize the options of this pass from the given string.
void printAsTextualPipeline (raw_ostream &os)
Prints out the pass in the textual representation of pipelines.
ArrayRef< Statistic * > getStatistics () const
Returns the main statistics for this pass instance.
MutableArrayRef< Statistic * > getStatistics ()
Public Member Functions inherited from mlir::detail::OpToOpPassAdaptorBase
OpToOpPassAdaptorBase (OpPassManager &&mgr)
OpToOpPassAdaptorBase (const OpToOpPassAdaptorBase &rhs)=default
void mergeInto (OpToOpPassAdaptorBase &rhs)
Merge the current pass adaptor into given 'rhs'.
MutableArrayRef< OpPassManager > getPassManagers ()
Returns the pass managers held by this adaptor.
std::string getName ()
Returns the adaptor pass name.
Additional Inherited Members
Static Public Member Functions inherited from mlir::detail::PassModel< OpToOpPassAdaptorParallel, OpPassBase< void > >
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality for the derived pass class.
Static Public Member Functions inherited from mlir::OpPassBase< void >
static bool classof (const Pass *pass)
Support isa/dyn_cast functionality.
Static Public Member Functions inherited from mlir::Pass
static const PassInfo * lookupPassInfo (const PassID *passID)
Returns the pass info for the specified pass class or null if unknown.
template<typename PassT >
static const PassInfo * lookupPassInfo ()
Protected Member Functions inherited from mlir::OperationPass< OpToOpPassAdaptorParallel >
OperationPass ()
void getOperation ()
Return the current operation being transformed.
Protected Member Functions inherited from mlir::detail::PassModel< OpToOpPassAdaptorParallel, OpPassBase< void > >
PassModel (Optional< StringRef > opName=llvm::None)
void signalPassFailure ()
Signal that some invariant was broken when running.
AnalysisT & getAnalysis ()
Query an analysis for the current ir unit.
Optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis ()
Query a cached instance of an analysis for the current ir unit if one exists.
void markAllAnalysesPreserved ()
Mark all analyses as preserved.
void markAnalysesPreserved ()
Mark the provided analyses as preserved.
void markAnalysesPreserved (const AnalysisID *id)
StringRef getName () override
Returns the derived pass name.
std::unique_ptr< Pass > clone () const override
A clone method to create a copy of this pass.
Optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parent)
Returns the analysis for the parent operation if it exists.
Optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis ()
Optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *child)
Returns the analysis for the given child operation if it exists.
AnalysisT & getChildAnalysis (Operation *child)
Returns the analysis for the given child operation, or creates it if it doesn't exist.
Protected Member Functions inherited from mlir::Pass
Pass (const PassID *passID, Optional< StringRef > opName=llvm::None)
detail::PassExecutionState & getPassState ()
Returns the current pass state.
MLIRContext & getContext ()
Return the MLIR context for the current function being transformed.
Operation * getOperation ()
Return the current operation being transformed.
AnalysisManager getAnalysisManager ()
Returns the current analysis manager.
void copyOptionValuesFrom (const Pass *other)
Copy the option values from 'other', which is another instance of this pass.
Protected Attributes inherited from mlir::detail::OpToOpPassAdaptorBase
SmallVector< OpPassManager, 1 > mgrs
Detailed Description
An adaptor pass used to run operation passes over nested operations asynchronously across multiple threads.
Definition at line 63 of file PassDetail.h.
Constructor & Destructor Documentation
OpToOpPassAdaptorParallel()
OpToOpPassAdaptorParallel::OpToOpPassAdaptorParallel (OpPassManager && mgr)
Definition at line 395 of file Pass.cpp.
Member Function Documentation
getParallelPassManagers()
MutableArrayRef<SmallVector<OpPassManager, 1> > mlir::detail::OpToOpPassAdaptorParallel::getParallelPassManagers () inline
Return the async pass managers held by this parallel adaptor.
Definition at line 73 of file PassDetail.h.
References mlir::detail::getAdaptorPassBase(), and pass.
runOnOperation()
void OpToOpPassAdaptorParallel::runOnOperation () override virtual
Run the held pipeline over all operations.
Implements mlir::Pass.
Definition at line 408 of file Pass.cpp.
References mlir::ParallelDiagnosticHandler::eraseOrderIDForThread(), mlir::failed(), findPassManagerFor(), mlir::Pass::getAnalysisManager(), mlir::Pass::getContext(), mlir::Operation::getName(), mlir::OperationPass< OpToOpPassAdaptorParallel >::getOperation(), mlir::AnalysisManager::getPassInstrumentor(), hasSizeMismatch(), mlir::detail::OpToOpPassAdaptorBase::mgrs, runPipeline(), mlir::ParallelDiagnosticHandler::setOrderIDForThread(), mlir::detail::PassModel< OpToOpPassAdaptorParallel, OpPassBase< void > >::signalPassFailure(), and mlir::AnalysisManager::slice().
The documentation for this class was generated from the following files:
lib/Pass/PassDetail.h
lib/Pass/Pass.cpp