MLIR: mlir::Region Class Reference
mlir::Region Class Reference
This class contains a list of basic blocks and a link to the parent operation it is attached to.
#include "mlir/IR/Region.h"
Public Types
using BlockListType = llvm::iplist< Block >
using iterator = BlockListType::iterator
using reverse_iterator = BlockListType::reverse_iterator
Public Member Functions
Region ()=default
Region (Operation *container)
~Region ()
MLIRContext * getContext ()
Return the context this region is inserted in.
Location getLoc ()
Return a location for this region.
BlockListType & getBlocks ()
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
bool empty ()
void push_back (Block *block)
void push_front (Block *block)
Block & back ()
Block & front ()
Region * getParentRegion ()
Return the region containing this region or nullptr if the region is attached to a top-level operation.
Operation * getParentOp ()
Return the parent operation this region is attached to.
template<typename ParentT >
ParentT getParentOfType ()
Find the first parent operation of the given type, or nullptr if there is no ancestor operation.
unsigned getRegionNumber ()
Return the number of this region in the parent operation.
bool isProperAncestor (Region *other)
Return true if this region is a proper ancestor of the other region.
bool isAncestor (Region *other)
Return true if this region is ancestor of the other region.
void cloneInto (Region *dest, BlockAndValueMapping &mapper)
Clone the internal blocks from this region into dest.
void cloneInto (Region *dest, Region::iterator destPos, BlockAndValueMapping &mapper)
Clone this region into 'dest' before the given position in 'dest'.
void takeBody (Region &other)
Takes body of another region (that region will have no body after this operation completes).
bool isIsolatedFromAbove (Optional< Location > noteLoc=llvm::None)
Check that this does not use any value defined outside it.
void dropAllReferences ()
Drop all operand uses from operations within this region, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if< std::is_same< RetT, void >::value, RetT >::type walk (FnT &&callback)
Walk the operations in this region in postorder, calling the callback for each operation.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
std::enable_if< std::is_same< RetT, WalkResult >::value, RetT >::type walk (FnT &&callback)
Walk the operations in this region in postorder, calling the callback for each operation.
void viewGraph (const Twine &regionName)
Displays the CFG in a window.
void viewGraph ()
Static Public Member Functions
static BlockListType Region::* getSublistAccess (Block *)
getSublistAccess() - Returns pointer to member of region.
Detailed Description
This class contains a list of basic blocks and a link to the parent operation it is attached to.
Definition at line 23 of file Region.h.
Member Typedef Documentation
BlockListType
using mlir::Region::BlockListType = llvm::iplist<Block>
Definition at line 37 of file Region.h.
iterator
using mlir::Region::iterator = BlockListType::iterator
Definition at line 41 of file Region.h.
reverse_iterator
using mlir::Region::reverse_iterator = BlockListType::reverse_iterator
Definition at line 42 of file Region.h.
Constructor & Destructor Documentation
Region() [1/2]
mlir::Region::Region () default
Region() [2/2]
Region::Region (Operation * container) explicit
Definition at line 14 of file Region.cpp.
~Region()
Region::~Region ()
Definition at line 16 of file Region.cpp.
References dropAllReferences().
Member Function Documentation
back()
Block& mlir::Region::back () inline
Definition at line 53 of file Region.h.
Referenced by mlir::edsc::BlockHandle::createInRegion(), mlir::impl::ensureRegionTerminator(), and isFnEntryBlock().
begin()
iterator mlir::Region::begin () inline
Definition at line 44 of file Region.h.
Referenced by eraseUnreachableBlocks(), getOrInsertBuiltinVariable(), mlir::inlineRegion(), llvm::GraphTraits< mlir::Region * >::nodes_begin(), mlir::detail::ConversionPatternRewriterImpl::undoBlockActions(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait().
cloneInto() [1/2]
void Region::cloneInto (Region * dest, BlockAndValueMapping & mapper)
Clone the internal blocks from this region into dest.
Clone the internal blocks from this region into dest.
Any cloned blocks are appended to the back of dest. If the mapper contains entries for block arguments, these arguments are not included in the respective cloned block.
Any cloned blocks are appended to the back of dest.
Definition at line 63 of file Region.cpp.
References end().
Referenced by mlir::PatternRewriter::cloneRegionBefore(), mlir::inlineRegion(), and isAncestor().
cloneInto() [2/2]
void Region::cloneInto (Region * dest, Region::iterator destPos, BlockAndValueMapping & mapper)
Clone this region into 'dest' before the given position in 'dest'.
Definition at line 69 of file Region.cpp.
References mlir::Block::addArgument(), mlir::BlockAndValueMapping::contains(), empty(), front(), mlir::Block::getArguments(), getBlocks(), mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::lookupOrNull(), mlir::BlockAndValueMapping::map(), and mlir::Block::push_back().
dropAllReferences()
void Region::dropAllReferences ()
Drop all operand uses from operations within this region, which is an essential step in breaking cyclic dependences between references when they are to be deleted.
Definition at line 111 of file Region.cpp.
References mlir::Block::dropAllReferences().
Referenced by takeBody(), and ~Region().
empty()
bool mlir::Region::empty () inline
Definition at line 49 of file Region.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), canRegisterAlias(), cloneInto(), mlir::ConversionPatternRewriter::cloneRegionBefore(), deleteDeadness(), mlir::impl::ensureRegionTerminator(), eraseUnreachableBlocks(), mlir::inlineCall(), mlir::inlineRegion(), mlir::OpBuilder::OpBuilder(), printDenseFloatElement(), mlir::impl::printFunctionSignature(), printGlobalOp(), propagateLiveness(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait().
end()
iterator mlir::Region::end () inline
Definition at line 45 of file Region.h.
Referenced by cloneInto(), mlir::OpBuilder::createBlock(), eraseUnreachableBlocks(), mlir::inlineRegion(), llvm::GraphTraits< mlir::Region * >::nodes_end(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait().
front()
Block& mlir::Region::front () inline
Definition at line 54 of file Region.h.
Referenced by mlir::detail::ConversionPatternRewriterImpl::applySignatureConversion(), canRegisterAlias(), cloneInto(), mlir::ConversionPatternRewriter::cloneRegionBefore(), deleteDeadness(), eraseUnreachableBlocks(), mlir::ModuleOp::getBody(), llvm::GraphTraits< mlir::Region * >::getEntryNode(), mlir::LLVM::ModuleTranslation::getModuleBody(), injectGpuIndexOperations(), mlir::inlineCall(), mlir::inlineRegion(), mlir::SymbolTable::insert(), insertCopies(), mlir::loop::LoopOpsDialect::LoopOpsDialect(), mlir::OpBuilder::OpBuilder(), printDenseFloatElement(), mlir::impl::printFunctionSignature(), propagateLiveness(), mlir::SymbolTable::SymbolTable(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait().
getBlocks()
BlockListType& mlir::Region::getBlocks () inline
Definition at line 38 of file Region.h.
Referenced by cloneInto(), computeConversionSet(), mlir::OpBuilder::createBlock(), deleteDeadness(), mlir::inlineRegion(), mlir::PatternRewriter::inlineRegionBefore(), mlir::Block::insertBefore(), mlir::Block::moveBefore(), printDenseFloatElement(), takeBody(), mlir::detail::ConversionPatternRewriterImpl::undoBlockActions(), and verify().
getContext()
MLIRContext * Region::getContext ()
Return the context this region is inserted in.
The region must have a valid parent container.
Definition at line 24 of file Region.cpp.
References mlir::Operation::getContext().
Referenced by insertCopies().
getLoc()
Location Region::getLoc ()
Return a location for this region.
This is the location attached to the parent container. The region must have a valid parent container.
Definition at line 31 of file Region.cpp.
References mlir::Operation::getLoc().
Referenced by mlir::ConversionPatternRewriter::cloneRegionBefore().
getParentOfType()
template<typename ParentT > ParentT mlir::Region::getParentOfType () inline
Find the first parent operation of the given type, or nullptr if there is no ancestor operation.
Definition at line 70 of file Region.h.
References getRegionNumber(), and isProperAncestor().
Referenced by generateCopy().
getParentOp()
Operation * Region::getParentOp ()
Return the parent operation this region is attached to.
Definition at line 41 of file Region.cpp.
Referenced by canRegisterAlias(), collectSymbolScopes(), computeConversionSet(), containsReturn(), mlir::getForInductionVarOwner(), getInsertionRegion(), mlir::CallGraph::getOrAddNode(), getRegionNumber(), getSublistAccess(), inlineCallsInSCC(), isFunctionRegion(), mlir::InlinerInterface::isLegalToInline(), and mlir::CallGraph::print().
getParentRegion()
Region * Region::getParentRegion ()
Return the region containing this region or nullptr if the region is attached to a top-level operation.
Definition at line 36 of file Region.cpp.
References mlir::Operation::getParentRegion().
Referenced by llvm::ilist_traits<::mlir::Block >::addNodeToList(), mlir::Value::getParentRegion(), mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >::getParentRegion(), getSublistAccess(), isProperAncestor(), llvm::ilist_traits<::mlir::Block >::transferNodesFromList(), and mlir::visitUsedValuesDefinedAbove().
getRegionNumber()
unsigned Region::getRegionNumber ()
Return the number of this region in the parent operation.
Definition at line 55 of file Region.cpp.
References getParentOp(), and mlir::Operation::getRegions().
Referenced by getParentOfType().
getSublistAccess()
static BlockListType Region::* mlir::Region::getSublistAccess (Block *) inline static
getSublistAccess() - Returns pointer to member of region.
Definition at line 57 of file Region.h.
References getParentOp(), and getParentRegion().
Referenced by isIsolatedFromAbove().
isAncestor()
bool mlir::Region::isAncestor (Region * other) inline
Return true if this region is ancestor of the other region.
A region is considered as its own ancestor, use isProperAncestor to avoid this.
Definition at line 87 of file Region.h.
References cloneInto(), and isProperAncestor().
Referenced by isIsolatedAbove(), mlir::DominanceInfo::properlyDominates(), mlir::replaceAllUsesInRegionWith(), and mlir::visitUsedValuesDefinedAbove().
isIsolatedFromAbove()
bool Region::isIsolatedFromAbove (Optional< Location > noteLoc = llvm::None)
Check that this does not use any value defined outside it.
Emit errors if noteLoc is provided; this location is used to point to the operation containing the region, the actual error is reported at the operation with an offending use.
Definition at line 168 of file Region.cpp.
References getSublistAccess(), and isIsolatedAbove().
Referenced by takeBody().
isProperAncestor()
bool Region::isProperAncestor (Region * other)
Return true if this region is a proper ancestor of the other region.
Definition at line 43 of file Region.cpp.
References getParentRegion().
Referenced by getParentOfType(), and isAncestor().
push_back()
void mlir::Region::push_back (Block * block) inline
Definition at line 50 of file Region.h.
Referenced by mlir::edsc::BlockHandle::createInRegion(), ensureDistinctSuccessors(), mlir::impl::ensureRegionTerminator(), mlir::AffineDmaWaitOp::fold(), and parseShuffleOp().
push_front()
void mlir::Region::push_front (Block * block) inline
Definition at line 51 of file Region.h.
rbegin()
reverse_iterator mlir::Region::rbegin () inline
Definition at line 46 of file Region.h.
rend()
reverse_iterator mlir::Region::rend () inline
Definition at line 47 of file Region.h.
takeBody()
void mlir::Region::takeBody (Region & other) inline
Takes body of another region (that region will have no body after this operation completes).
The current body of this region is cleared.
Definition at line 102 of file Region.h.
References dropAllReferences(), getBlocks(), isIsolatedFromAbove(), and mlir::StandardTypes::None.
Referenced by mlir::Operation::create().
viewGraph() [1/2]
void mlir::Region::viewGraph (const Twine & regionName)
Displays the CFG in a window.
This is for use from the debugger and depends on Graphviz to generate the graph. This function is defined in ViewRegionGraph and only works with that target linked.
Definition at line 57 of file ViewRegionGraph.cpp.
References mlir::viewGraph().
viewGraph() [2/2]
void mlir::Region::viewGraph ()
Definition at line 60 of file ViewRegionGraph.cpp.
References mlir::viewGraph(), and mlir::writeGraph().
Referenced by walk().
walk() [1/2]
template<typename FnT , typename RetT = detail::walkResultType<FnT>> std::enable_if<std::is_same<RetT, void>::value, RetT>::type mlir::Region::walk (FnT && callback) inline
Walk the operations in this region in postorder, calling the callback for each operation.
This method is invoked for void-returning callbacks. See Operation::walk for more details.
Definition at line 123 of file Region.h.
Referenced by mlir::visitUsedValuesDefinedAbove().
walk() [2/2]
template<typename FnT , typename RetT = detail::walkResultType<FnT>> std::enable_if<std::is_same<RetT, WalkResult>::value, RetT>::type mlir::Region::walk (FnT && callback) inline
Walk the operations in this region in postorder, calling the callback for each operation.
This method is invoked for interruptible callbacks. See Operation::walk for more details.
Definition at line 133 of file Region.h.
References mlir::WalkResult::advance(), mlir::WalkResult::interrupt(), and viewGraph().
The documentation for this class was generated from the following files:
include/mlir/IR/Region.h
lib/IR/Region.cpp
lib/Transforms/ViewRegionGraph.cpp