MLIR: mlir::SDBMExpr Class Reference
mlir::SDBMExpr Class Reference
Striped Difference-Bounded Matrix (SDBM) expression is a base left-hand side expression for the SDBM framework.
#include "mlir/Dialect/SDBM/SDBMExpr.h"
Public Types
using ImplType = detail::SDBMExprStorage
Public Member Functions
SDBMExpr ()
SDBMExpr (ImplType *expr)
SDBMExpr (const SDBMExpr &)=default
SDBM expressions are thin wrappers around a unique'ed immutable pointer, which makes them trivially assignable and trivially copyable.
SDBMExpr & operator= (const SDBMExpr &)=default
bool operator== (const SDBMExpr &other) const
SDBM expressions can be compared straight-forwardly.
bool operator!= (const SDBMExpr &other) const
operator bool () const
SDBM expressions are convertible to bool: null expressions are converted to false, non-null expressions are converted to true.
bool operator! () const
SDBMExpr operator- ()
Negate the given SDBM expression.
void print (raw_ostream &os) const
Prints the SDBM expression.
void dump () const
template<typename U >
bool isa () const
LLVM-style casts.
template<typename U >
U dyn_cast () const
template<typename U >
U cast () const
::llvm::hash_code hash_value () const
Support for LLVM hashing.
SDBMExprKind getKind () const
Returns the kind of the SDBM expression.
MLIRContext * getContext () const
Returns the MLIR context in which this expression lives.
SDBMDialect * getDialect () const
Returns the SDBM dialect instance.
AffineExpr getAsAffineExpr () const
Convert the SDBM expression into an Affine expression.
Static Public Member Functions
static Optional< SDBMExpr > tryConvertAffineExpr (AffineExpr affine)
Try constructing an SDBM expression from the given affine expression.
Protected Attributes
ImplType * impl
Detailed Description
Striped Difference-Bounded Matrix (SDBM) expression is a base left-hand side expression for the SDBM framework.
SDBM expressions are a subset of affine expressions supporting low-complexity algorithms for the operations used in loop transformations. In particular, are supported:
constant expressions;
single variables (dimensions and symbols) with +1 or -1 coefficient;
stripe expressions: "x # C", where "x" is a single variable or another stripe expression, "#" is the stripe operator, and "C" is a constant expression; "#" is defined as x - x mod C.
sum expressions between single variable/stripe expressions and constant expressions;
difference expressions between single variable/stripe expressions. SDBMExpr class hierarchy provides a type-safe interface to constructing and operating on SDBM expressions. For example, it requires the LHS of a sum expression to be a single variable or a stripe expression. These restrictions are intended to force the caller to perform the necessary simplifications to stay within the SDBM domain, because SDBM expressions do not combine in more cases than they do. This choice may be reconsidered in the future.
SDBM expressions are grouped into the following structure
expression
varying
direct
sum <- (term, constant)
term
symbol
dimension
stripe <- (direct, constant)
negation <- (direct)
difference <- (direct, term)
constant The notation <- (...) denotes the types of subexpressions a compound expression can combine. The tree of subexpressions essentially imposes the following canonicalization rules:
constants are always folded;
constants can only appear on the RHS of an expression;
double negation must be elided;
an additive constant term is only allowed in a sum expression, and should be sunk into the nearest such expression in the tree;
zero constant expression can only appear at the top level.
SDBMExpr and derived classes are thin wrappers around a pointer owned by an MLIRContext, and should be used by-value. They are uniqued in the MLIRContext and immortal.
Definition at line 88 of file SDBMExpr.h.
Member Typedef Documentation
ImplType
using mlir::SDBMExpr::ImplType = detail::SDBMExprStorage
Definition at line 90 of file SDBMExpr.h.
Constructor & Destructor Documentation
SDBMExpr() [1/3]
mlir::SDBMExpr::SDBMExpr () inline
Definition at line 91 of file SDBMExpr.h.
SDBMExpr() [2/3]
mlir::SDBMExpr::SDBMExpr (ImplType * expr) inline
Definition at line 92 of file SDBMExpr.h.
SDBMExpr() [3/3]
mlir::SDBMExpr::SDBMExpr (const SDBMExpr &) default
SDBM expressions are thin wrappers around a unique'ed immutable pointer, which makes them trivially assignable and trivially copyable.
Member Function Documentation
cast()
template<typename U > U mlir::SDBMExpr::cast () const inline
Definition at line 122 of file SDBMExpr.h.
Referenced by addConstant(), addConstantAndSink(), dump(), mlir::SDBM::get(), mlir::SDBMStripeExpr::getLHS(), mlir::ops_assertions::operator+(), mlir::ops_assertions::operator-(), mlir::ops_assertions::stripe(), mlir::SDBMVisitor< Derived, Result >::visit(), mlir::SDBMVisitor< Derived, Result >::visitDirect(), mlir::SDBMVisitor< Derived, Result >::visitInput(), and mlir::SDBMVisitor< Derived, Result >::visitTerm().
dump()
void SDBMExpr::dump () const
Definition at line 194 of file SDBMExpr.cpp.
References cast(), dyn_cast(), mlir::SDBMConstantExpr::get(), mlir::SDBMSumExpr::get(), mlir::SDBMDiffExpr::get(), mlir::SDBMNegExpr::get(), getDialect(), mlir::SDBMSumExpr::getLHS(), mlir::SDBMDiffExpr::getLHS(), mlir::SDBMDiffExpr::getRHS(), mlir::SDBMConstantExpr::getValue(), mlir::SDBMNegExpr::getVar(), and print().
dyn_cast()
template<typename U > U mlir::SDBMExpr::dyn_cast () const inline
Definition at line 117 of file SDBMExpr.h.
Referenced by addConstant(), addConstantAndSink(), dump(), foldSumDiff(), mlir::SDBM::get(), mlir::SDBMSumExpr::get(), mlir::ops_assertions::operator+(), mlir::ops_assertions::operator-(), tryConvertAffineExpr(), mlir::SDBMVisitor< Derived, Result >::visitDirect(), mlir::SDBMVisitor< Derived, Result >::visitVarying(), and mlir::SDBMVisitor< Derived, Result >::walk().
getAsAffineExpr()
AffineExpr SDBMExpr::getAsAffineExpr () const
Convert the SDBM expression into an Affine expression.
This always succeeds because SDBM are a subset of affine.
Definition at line 260 of file SDBMExpr.cpp.
References mlir::getAffineBinaryOpExpr(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), getContext(), mlir::SDBMSumExpr::getLHS(), mlir::SDBMDiffExpr::getLHS(), mlir::SDBMStripeExpr::getLHS(), mlir::SDBMInputExpr::getPosition(), mlir::SDBMSumExpr::getRHS(), mlir::SDBMDiffExpr::getRHS(), mlir::SDBMStripeExpr::getStripeFactor(), mlir::SDBMConstantExpr::getValue(), mlir::SDBMNegExpr::getVar(), and mlir::Mul.
getContext()
MLIRContext * SDBMExpr::getContext () const
Returns the MLIR context in which this expression lives.
Definition at line 144 of file SDBMExpr.cpp.
References mlir::detail::SDBMExprStorage::dialect, mlir::Dialect::getContext(), and impl.
Referenced by getAsAffineExpr().
getDialect()
SDBMDialect * SDBMExpr::getDialect () const
Returns the SDBM dialect instance.
Definition at line 148 of file SDBMExpr.cpp.
References mlir::detail::SDBMExprStorage::dialect, and impl.
Referenced by addConstant(), addConstantAndSink(), buildDiffExpr(), mlir::detail::SDBMBinaryExprStorage::construct(), mlir::detail::SDBMDiffExprStorage::construct(), mlir::detail::SDBMNegExprStorage::construct(), dump(), mlir::SDBM::get(), mlir::SDBMSumExpr::get(), mlir::SDBMDiffExpr::get(), mlir::SDBMStripeExpr::get(), mlir::SDBMNegExpr::get(), mlir::ops_assertions::operator+(), mlir::ops_assertions::operator-(), and mlir::ops_assertions::stripe().
getKind()
SDBMExprKind SDBMExpr::getKind () const
Returns the kind of the SDBM expression.
Definition at line 142 of file SDBMExpr.cpp.
References mlir::detail::SDBMExprStorage::getKind(), and impl.
Referenced by mlir::SDBMConstantExpr::isClassFor(), mlir::SDBMVaryingExpr::isClassFor(), mlir::SDBMDirectExpr::isClassFor(), mlir::SDBMTermExpr::isClassFor(), mlir::SDBMSumExpr::isClassFor(), mlir::SDBMDiffExpr::isClassFor(), mlir::SDBMStripeExpr::isClassFor(), mlir::SDBMInputExpr::isClassFor(), mlir::SDBMDimExpr::isClassFor(), mlir::SDBMSymbolExpr::isClassFor(), mlir::SDBMNegExpr::isClassFor(), mlir::SDBMVisitor< Derived, Result >::visit(), mlir::SDBMVisitor< Derived, Result >::visitInput(), and mlir::SDBMVisitor< Derived, Result >::visitTerm().
hash_value()
::llvm::hash_code mlir::SDBMExpr::hash_value () const inline
Support for LLVM hashing.
Definition at line 128 of file SDBMExpr.h.
References mlir::hash_value().
Referenced by llvm::DenseMapInfo< mlir::SDBMExpr >::getHashValue(), llvm::DenseMapInfo< mlir::SDBMDirectExpr >::getHashValue(), llvm::DenseMapInfo< mlir::SDBMTermExpr >::getHashValue(), and llvm::DenseMapInfo< mlir::SDBMConstantExpr >::getHashValue().
isa()
template<typename U > bool mlir::SDBMExpr::isa () const inline
LLVM-style casts.
Definition at line 116 of file SDBMExpr.h.
Referenced by mlir::ops_assertions::operator+(), and print().
operator bool()
mlir::SDBMExpr::operator bool () const inline explicit
SDBM expressions are convertible to bool: null expressions are converted to false, non-null expressions are converted to true.
Definition at line 105 of file SDBMExpr.h.
operator!()
bool mlir::SDBMExpr::operator! () const inline
Definition at line 106 of file SDBMExpr.h.
References mlir::operator-(), and print().
operator!=()
bool mlir::SDBMExpr::operator!= (const SDBMExpr & other) const inline
Definition at line 101 of file SDBMExpr.h.
operator-()
SDBMExpr SDBMExpr::operator- ()
Negate the given SDBM expression.
Definition at line 230 of file SDBMExpr.cpp.
operator=()
SDBMExpr& mlir::SDBMExpr::operator= (const SDBMExpr &) default
operator==()
bool mlir::SDBMExpr::operator== (const SDBMExpr & other) const inline
SDBM expressions can be compared straight-forwardly.
Definition at line 100 of file SDBMExpr.h.
References impl.
print()
void SDBMExpr::print (raw_ostream & os) const
Prints the SDBM expression.
Definition at line 150 of file SDBMExpr.cpp.
References mlir::SDBMSumExpr::getLHS(), mlir::SDBMDiffExpr::getLHS(), mlir::SDBMStripeExpr::getLHS(), mlir::SDBMInputExpr::getPosition(), mlir::SDBMSumExpr::getRHS(), mlir::SDBMDiffExpr::getRHS(), mlir::SDBMStripeExpr::getStripeFactor(), mlir::SDBMConstantExpr::getValue(), mlir::SDBMNegExpr::getVar(), and isa().
Referenced by dump().
tryConvertAffineExpr()
Optional< SDBMExpr > SDBMExpr::tryConvertAffineExpr (AffineExpr affine) static
Try constructing an SDBM expression from the given affine expression.
This may fail if the affine expression is not representable as SDBM, in which case llvm::None is returned. The conversion procedure recognizes (nested) multiplicative ((x floordiv B) * B) and additive (x - x mod B) patterns for the stripe expression.
Definition at line 421 of file SDBMExpr.cpp.
References addConstant(), dyn_cast(), foldSumDiff(), mlir::SDBMConstantExpr::get(), mlir::SDBMDiffExpr::get(), mlir::SDBMStripeExpr::get(), mlir::SDBMDimExpr::get(), mlir::SDBMSymbolExpr::get(), mlir::SDBMNegExpr::get(), mlir::AffineExpr::getContext(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineDimExpr::getPosition(), mlir::AffineSymbolExpr::getPosition(), mlir::MLIRContext::getRegisteredDialect(), mlir::AffineBinaryOpExpr::getRHS(), mlir::AffineConstantExpr::getValue(), and mlir::StandardTypes::None.
Member Data Documentation
impl
ImplType* mlir::SDBMExpr::impl protected
Definition at line 151 of file SDBMExpr.h.
Referenced by getContext(), getDialect(), getKind(), mlir::SDBMSumExpr::getLHS(), mlir::SDBMDiffExpr::getLHS(), mlir::SDBMStripeExpr::getLHS(), mlir::SDBMInputExpr::getPosition(), mlir::SDBMSumExpr::getRHS(), mlir::SDBMDiffExpr::getRHS(), mlir::SDBMStripeExpr::getStripeFactor(), mlir::SDBMConstantExpr::getValue(), mlir::SDBMNegExpr::getVar(), and operator==().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SDBM/SDBMExpr.h
lib/Dialect/SDBM/SDBMExpr.cpp