MLIR: mlir::SparseElementsAttr Class Reference
mlir::SparseElementsAttr Class Reference
An attribute that represents a reference to a sparse vector or tensor object.
#include "mlir/IR/Attributes.h"
Public Types
template<typename T >
using iterator = llvm::mapped_iterator< llvm::detail::value_sequence_iterator< ptrdiff_t >, std::function< T(ptrdiff_t)> >
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
DenseIntElementsAttr getIndices () const
DenseElementsAttr getValues () const
template<typename T >
llvm::iterator_range< iterator< T > > getValues () const
Return the values of this attribute in the form of the given type 'T'.
Attribute getValue (ArrayRef< uint64_t > index) const
Return the value of the element at the given index.
Static Public Member Functions
static SparseElementsAttr get (ShapedType type, DenseElementsAttr indices, DenseElementsAttr values)
'type' must be a vector or tensor with static shape.
static bool kindof (unsigned kind)
Method for support type inquiry through isa, cast and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
An attribute that represents a reference to a sparse vector or tensor object.
This class uses COO (coordinate list) encoding to represent the sparse elements in an element attribute. Specifically, the sparse vector/tensor stores the indices and values as two separate dense elements attributes of tensor type (even if the sparse attribute is of vector type, in order to support empty lists). The dense elements attribute indices is a 2-D tensor of 64-bit integer elements with shape [N, ndims], which specifies the indices of the elements in the sparse tensor that contains nonzero values. The dense elements attribute values is a 1-D tensor with shape [N], and it supplies the corresponding values for the indices.
For example, sparse<tensor<3x4xi32>, [[0, 0], [1, 2]], [1, 5]> represents tensor [[1, 0, 0, 0], [0, 0, 5, 0], [0, 0, 0, 0]].
Definition at line 1101 of file Attributes.h.
Member Typedef Documentation
iterator
template<typename T > using mlir::SparseElementsAttr::iterator = llvm::mapped_iterator<llvm::detail::value_sequence_iterator<ptrdiff_t>, std::function<T(ptrdiff_t)> >
Definition at line 1110 of file Attributes.h.
Member Function Documentation
get()
SparseElementsAttr SparseElementsAttr::get (ShapedType type, DenseElementsAttr indices, DenseElementsAttr values) static
'type' must be a vector or tensor with static shape.
Definition at line 917 of file Attributes.cpp.
References mlir::Type::getContext(), mlir::ShapedType::hasStaticShape(), mlir::Type::isa(), and mlir::StandardAttributes::SparseElements.
Referenced by buildHexadecimalFloatLiteral(), and convertSparseElementsAttr().
getIndices()
DenseIntElementsAttr SparseElementsAttr::getIndices () const
Definition at line 929 of file Attributes.cpp.
Referenced by convertSparseElementsAttr().
getValue()
Attribute SparseElementsAttr::getValue (ArrayRef< uint64_t > index) const
Return the value of the element at the given index.
The 'index' is expected to refer to a valid element.
Definition at line 938 of file Attributes.cpp.
References mlir::Type::cast(), mlir::BoolAttr::get(), mlir::FloatAttr::get(), mlir::IntegerAttr::get(), and mlir::AttributeStorage::getType().
getValues() [1/2]
DenseElementsAttr SparseElementsAttr::getValues () const
Definition at line 933 of file Attributes.cpp.
Referenced by convertSparseElementsAttr().
getValues() [2/2]
template<typename T > llvm::iterator_range<iterator<T> > mlir::SparseElementsAttr::getValues () const inline
Return the values of this attribute in the form of the given type 'T'.
'T' may be any of Attribute, APInt, APFloat, c++ integer/float types, etc.
Definition at line 1122 of file Attributes.h.
kindof()
static bool mlir::SparseElementsAttr::kindof (unsigned kind) inline static
Method for support type inquiry through isa, cast and dyn_cast.
Definition at line 1144 of file Attributes.h.
References mlir::StandardAttributes::SparseElements.
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp