MLIR: mlir::IRMultiObjectWithUseList< OperandType > Class Template Reference
mlir::IRMultiObjectWithUseList< OperandType > Class Template Reference
This class represents multiple IR objects with a single use list.
#include "mlir/IR/UseDefLists.h"
Public Types
using BaseType = IRObjectWithUseList< OperandType >
using ValueType = typename OperandType::ValueType
using filtered_use_iterator = FilteredValueUseIterator< OperandType >
using filtered_use_range = iterator_range< filtered_use_iterator >
using filtered_user_iterator = ValueUserIterator< filtered_use_iterator, OperandType >
using filtered_user_range = iterator_range< filtered_user_iterator >
Public Types inherited from mlir::IRObjectWithUseList< OperandType >
using use_iterator = ValueUseIterator< OperandType >
using use_range = iterator_range< use_iterator >
using user_iterator = ValueUserIterator< use_iterator, OperandType >
using user_range = iterator_range< user_iterator >
Public Member Functions
void dropAllUses (ValueType value)
Drop all uses of value from their respective owners.
void replaceAllUsesWith (ValueType oldValue, ValueType newValue)
Replace all uses of oldValue with the new value, updating anything in the IR that uses 'this' to use the other value instead.
filtered_use_iterator use_begin (ValueType value) const
filtered_use_iterator use_end (ValueType) const
filtered_use_range getUses (ValueType value) const
bool hasOneUse (ValueType value) const
bool use_empty (ValueType value) const
filtered_user_iterator user_begin (ValueType value) const
filtered_user_iterator user_end (ValueType value) const
filtered_user_range getUsers (ValueType value) const
Public Member Functions inherited from mlir::IRObjectWithUseList< OperandType >
~IRObjectWithUseList ()
void dropAllUses ()
Drop all uses of this object from their respective owners.
void replaceAllUsesWith (typename OperandType::ValueType newValue)
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead.
use_iterator use_begin () const
use_iterator use_end () const
use_range getUses () const
Returns a range of all uses, which is useful for iterating over all uses.
bool hasOneUse () const
Returns true if this value has exactly one use.
bool use_empty () const
Returns true if this value has no uses.
user_iterator user_begin () const
user_iterator user_end () const
user_range getUsers () const
Returns a range of all users.
Additional Inherited Members
Protected Member Functions inherited from mlir::IRObjectWithUseList< OperandType >
IRObjectWithUseList ()
OperandType * getFirstUse () const
Return the first operand that is using this value, for use by custom use/def iterators.
Detailed Description
template<typename OperandType>
class mlir::IRMultiObjectWithUseList< OperandType >
This class represents multiple IR objects with a single use list.
This class provides wrapper functionality for manipulating the uses of a single object.
Definition at line 109 of file UseDefLists.h.
Member Typedef Documentation
BaseType
template<typename OperandType> using mlir::IRMultiObjectWithUseList< OperandType >::BaseType = IRObjectWithUseList<OperandType>
Definition at line 111 of file UseDefLists.h.
filtered_use_iterator
template<typename OperandType> using mlir::IRMultiObjectWithUseList< OperandType >::filtered_use_iterator = FilteredValueUseIterator<OperandType>
Definition at line 140 of file UseDefLists.h.
filtered_use_range
template<typename OperandType> using mlir::IRMultiObjectWithUseList< OperandType >::filtered_use_range = iterator_range<filtered_use_iterator>
Definition at line 141 of file UseDefLists.h.
filtered_user_iterator
template<typename OperandType> using mlir::IRMultiObjectWithUseList< OperandType >::filtered_user_iterator = ValueUserIterator<filtered_use_iterator, OperandType>
Definition at line 167 of file UseDefLists.h.
filtered_user_range
template<typename OperandType> using mlir::IRMultiObjectWithUseList< OperandType >::filtered_user_range = iterator_range<filtered_user_iterator>
Definition at line 168 of file UseDefLists.h.
ValueType
template<typename OperandType> using mlir::IRMultiObjectWithUseList< OperandType >::ValueType = typename OperandType::ValueType
Definition at line 112 of file UseDefLists.h.
Member Function Documentation
dropAllUses()
template<typename OperandType> void mlir::IRMultiObjectWithUseList< OperandType >::dropAllUses (ValueType value) inline
Drop all uses of value from their respective owners.
Definition at line 115 of file UseDefLists.h.
Referenced by mlir::Value::dropAllUses().
getUsers()
template<typename OperandType> filtered_user_range mlir::IRMultiObjectWithUseList< OperandType >::getUsers (ValueType value) const inline
Definition at line 174 of file UseDefLists.h.
getUses()
template<typename OperandType> filtered_use_range mlir::IRMultiObjectWithUseList< OperandType >::getUses (ValueType value) const inline
Definition at line 147 of file UseDefLists.h.
hasOneUse()
template<typename OperandType> bool mlir::IRMultiObjectWithUseList< OperandType >::hasOneUse (ValueType value) const inline
Definition at line 150 of file UseDefLists.h.
Referenced by mlir::Value::hasOneUse().
replaceAllUsesWith()
template<typename OperandType> void mlir::IRMultiObjectWithUseList< OperandType >::replaceAllUsesWith (ValueType oldValue, ValueType newValue) inline
Replace all uses of oldValue with the new value, updating anything in the IR that uses 'this' to use the other value instead.
When this returns there are zero uses of 'this'.
Definition at line 126 of file UseDefLists.h.
Referenced by mlir::Value::replaceAllUsesWith().
use_begin()
template<typename OperandType> filtered_use_iterator mlir::IRMultiObjectWithUseList< OperandType >::use_begin (ValueType value) const inline
Definition at line 143 of file UseDefLists.h.
Referenced by mlir::Value::use_begin().
use_empty()
template<typename OperandType> bool mlir::IRMultiObjectWithUseList< OperandType >::use_empty (ValueType value) const inline
Definition at line 153 of file UseDefLists.h.
Referenced by mlir::PatternRewriter::eraseOp(), and mlir::Value::use_empty().
use_end()
template<typename OperandType> filtered_use_iterator mlir::IRMultiObjectWithUseList< OperandType >::use_end (ValueType) const inline
Definition at line 146 of file UseDefLists.h.
Referenced by mlir::IRMultiObjectWithUseList< OpOperand >::use_end().
user_begin()
template<typename OperandType> filtered_user_iterator mlir::IRMultiObjectWithUseList< OperandType >::user_begin (ValueType value) const inline
Definition at line 170 of file UseDefLists.h.
Referenced by llvm::GraphTraits< Block * >::child_begin().
user_end()
template<typename OperandType> filtered_user_iterator mlir::IRMultiObjectWithUseList< OperandType >::user_end (ValueType value) const inline
Definition at line 173 of file UseDefLists.h.
Referenced by llvm::GraphTraits< Block * >::child_end().
The documentation for this class was generated from the following file:
include/mlir/IR/UseDefLists.h