MLIR: mlir::ShapedType Class Reference
mlir::ShapedType Class Reference
This is a common base class between Vector, UnrankedTensor, RankedTensor, and MemRef types because they share behavior and semantics around shape, rank, and fixed element type.
#include "mlir/IR/StandardTypes.h"
Public Types
using ImplType = detail::ShapedTypeStorage
Public Types inherited from mlir::Type
enum Kind {
Function, Opaque, LAST_BUILTIN_TYPE = Opaque, DEFINE_SYM_KIND_RANGE,
DEFINE_SYM_KIND_RANGE
}
Integer identifier for all the concrete type kinds.
template<typename ConcreteType , typename BaseType , typename StorageType = DefaultTypeStorage>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer >
Utility class for implementing types.
using ImplType = TypeStorage
Public Member Functions
Type getElementType () const
Return the element type.
unsigned getElementTypeBitWidth () const
If an element type is an integer or a float, return its width.
int64_t getNumElements () const
If it has static shape, return the number of elements. Otherwise, abort.
int64_t getRank () const
If this is a ranked type, return the rank. Otherwise, abort.
bool hasRank () const
Whether or not this is a ranked type.
ArrayRef< int64_t > getShape () const
If this is a ranked type, return the shape. Otherwise, abort.
bool hasStaticShape () const
If this is unranked type or any dimension has unknown size (<0), it doesn't have static shape.
bool hasStaticShape (ArrayRef< int64_t > shape) const
If this has a static shape and the shape is equal to shape return true.
int64_t getNumDynamicDims () const
If this is a ranked type, return the number of dimensions with dynamic size.
int64_t getDimSize (int64_t i) const
If this is ranked type, return the size of the specified dimension.
unsigned getDynamicDimIndex (unsigned index) const
Returns the position of the dynamic dimension relative to just the dynamic dimensions, given its index within the shape.
int64_t getSizeInBits () const
Get the total amount of bits occupied by a value of this type.
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
unsigned getKind () const
Return the classification for this type.
MLIRContext * getContext () const
Return the LLVMContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex ()
bool isBF16 ()
bool isF16 ()
bool isF32 ()
bool isF64 ()
bool isInteger (unsigned width)
Return true if this is an integer type with the specified width.
unsigned getIntOrFloatBitWidth ()
Return the bit width of an integer or a float type, assert failure on other types.
bool isIntOrIndex ()
Return true if this is an integer or index type.
bool isIntOrIndexOrFloat ()
Return true if this is an integer, index, or float type.
bool isIntOrFloat ()
Return true of this is an integer or a float type.
void print (raw_ostream &os)
Print the current type.
void dump ()
unsigned getSubclassData () const
void setSubclassData (unsigned val)
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Static Public Member Functions
static bool classof (Type type)
Methods for support type inquiry through isa, cast, and dyn_cast.
static constexpr bool isDynamic (int64_t dSize)
Whether the given dimension size indicates a dynamic dimension.
static constexpr bool isDynamicStrideOrOffset (int64_t dStrideOrOffset)
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Static Public Attributes
static constexpr int64_t kDynamicSize = -1
static constexpr int64_t kDynamicStrideOrOffset
Additional Inherited Members
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
This is a common base class between Vector, UnrankedTensor, RankedTensor, and MemRef types because they share behavior and semantics around shape, rank, and fixed element type.
Any type with these semantics should inherit from ShapedType.
Definition at line 178 of file StandardTypes.h.
Member Typedef Documentation
ImplType
using mlir::ShapedType::ImplType = detail::ShapedTypeStorage
Definition at line 180 of file StandardTypes.h.
Member Function Documentation
classof()
static bool mlir::ShapedType::classof (Type type) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 239 of file StandardTypes.h.
References mlir::Type::getKind(), mlir::StandardTypes::MemRef, mlir::StandardTypes::RankedTensor, mlir::StandardTypes::UnrankedMemRef, mlir::StandardTypes::UnrankedTensor, and mlir::StandardTypes::Vector.
getDimSize()
int64_t ShapedType::getDimSize (int64_t i) const
If this is ranked type, return the size of the specified dimension.
Otherwise, abort.
Definition at line 140 of file StandardTypes.cpp.
References getShape().
Referenced by buildHexadecimalFloatLiteral(), and mlir::quant::UniformQuantizedPerAxisValueConverter::convert().
getDynamicDimIndex()
unsigned ShapedType::getDynamicDimIndex (unsigned index) const
Returns the position of the dynamic dimension relative to just the dynamic dimensions, given its index within the shape.
Definition at line 145 of file StandardTypes.cpp.
References getShape(), and isDynamic().
getElementType()
Type ShapedType::getElementType () const
Return the element type.
Definition at line 119 of file StandardTypes.cpp.
Referenced by buildHexadecimalFloatLiteral(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::DenseElementsAttr::get(), mlir::OpaqueElementsAttr::get(), getElementsStatistics(), mlir::detail::DenseElementsAttributeStorage::getKey(), mlir::DenseElementsAttr::getRaw(), isValidIntOrFloat(), parseExtractElementOp(), parseSplatOp(), mlir::DenseElementsAttr::reshape(), verify(), verifyFuncArgs(), and verifyFuncArgsGeneric().
getElementTypeBitWidth()
unsigned ShapedType::getElementTypeBitWidth () const
If an element type is an integer or a float, return its width.
Otherwise, abort.
Definition at line 123 of file StandardTypes.cpp.
References getElementType(), and mlir::Type::getIntOrFloatBitWidth().
Referenced by mlir::detail::DenseElementsAttributeStorage::construct(), mlir::detail::DenseElementsAttributeStorage::getKey(), and mlir::detail::DenseElementsAttributeStorage::operator==().
getNumDynamicDims()
int64_t ShapedType::getNumDynamicDims () const
If this is a ranked type, return the number of dimensions with dynamic size.
Otherwise, abort.
Definition at line 183 of file StandardTypes.cpp.
References getShape().
getNumElements()
int64_t ShapedType::getNumElements () const
If it has static shape, return the number of elements. Otherwise, abort.
Definition at line 127 of file StandardTypes.cpp.
References getShape().
Referenced by getElementsStatistics(), mlir::detail::DenseElementsAttributeStorage::getKey(), mlir::DenseElementsAttr::getRawIntOrFloat(), hasSameElementsOrSplat(), mappingHelper(), mlir::DenseElementsAttr::reshape(), and verify().
getRank()
int64_t ShapedType::getRank () const
If this is a ranked type, return the rank. Otherwise, abort.
Definition at line 136 of file StandardTypes.cpp.
References getShape().
Referenced by buildHexadecimalFloatLiteral(), and getElementsStatistics().
getShape()
ArrayRef< int64_t > ShapedType::getShape () const
If this is a ranked type, return the shape. Otherwise, abort.
Definition at line 170 of file StandardTypes.cpp.
References getShape(), mlir::StandardTypes::MemRef, mlir::StandardTypes::RankedTensor, and mlir::StandardTypes::Vector.
Referenced by buildHexadecimalFloatLiteral(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::quant::UniformQuantizedPerAxisValueConverter::convert(), getElementsStatistics(), mappingHelper(), and mlir::verifyCompatibleShape().
getSizeInBits()
int64_t ShapedType::getSizeInBits () const
Get the total amount of bits occupied by a value of this type.
Get the number of bits require to store a value of the given shaped type.
This does not take into account any memory layout or widening constraints, e.g. a vector<3xi57> is reported to occupy 3x57=171 bit, even though in practice it will likely be stored as in a 4xi64 vector register. Fail an assertion if the size cannot be computed statically, i.e. if the type has a dynamic shape or if its elemental type does not have a known bit width.
Compute the value recursively since tensors are allowed to have vectors as elements.
Definition at line 154 of file StandardTypes.cpp.
References getElementType().
hasRank()
bool ShapedType::hasRank () const
Whether or not this is a ranked type.
Memrefs, vectors and ranked tensors have a rank, while unranked tensors do not.
Definition at line 138 of file StandardTypes.cpp.
Referenced by mlir::verifyCompatibleShape().
hasStaticShape() [1/2]
bool ShapedType::hasStaticShape () const
If this is unranked type or any dimension has unknown size (<0), it doesn't have static shape.
If all dimensions have known size (>= 0), it has static shape.
Definition at line 187 of file StandardTypes.cpp.
References getShape().
Referenced by mlir::SparseElementsAttr::get(), getElementsStatistics(), mlir::DenseElementsAttr::getRaw(), and mlir::linalg::vectorizeLinalgOpPrecondition().
hasStaticShape() [2/2]
bool ShapedType::hasStaticShape (ArrayRef< int64_t > shape) const
If this has a static shape and the shape is equal to shape return true.
Definition at line 191 of file StandardTypes.cpp.
References getShape().
isDynamic()
static constexpr bool mlir::ShapedType::isDynamic (int64_t dSize) inline static
Whether the given dimension size indicates a dynamic dimension.
Definition at line 248 of file StandardTypes.h.
Referenced by mlir::MemRefRegion::compute(), getDynamicDimIndex(), isMemRefSizeValidSymbol(), isReshapableDimBand(), parseSymbol(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), verify(), mlir::verifyCompatibleShape(), and verifyDynamicStrides().
isDynamicStrideOrOffset()
static constexpr bool mlir::ShapedType::isDynamicStrideOrOffset (int64_t dStrideOrOffset) inline static
Definition at line 249 of file StandardTypes.h.
Referenced by convertLinalgType().
Member Data Documentation
kDynamicSize
constexpr int64_t ShapedType::kDynamicSize = -1 static
Definition at line 186 of file StandardTypes.h.
Referenced by computeReshapeCollapsedType(), mlir::Type::getIntOrFloatBitWidth(), getTypeNumBytes(), inferSubViewResultType(), and verify().
kDynamicStrideOrOffset
constexpr int64_t ShapedType::kDynamicStrideOrOffset static
Initial value:
=
      std::numeric_limits<int64_t>::min()
Definition at line 187 of file StandardTypes.h.
Referenced by computeReshapeCollapsedType(), mlir::Type::getIntOrFloatBitWidth(), and mlir::getStridesAndOffset().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp