MLIR: mlir::BlockArgument Class Reference
mlir::BlockArgument Class Reference
Block arguments are values.
#include "mlir/IR/Value.h"
Public Member Functions
Block * getOwner () const
Returns the block that owns this argument.
Type getType () const
Return the type of this value.
void setType (Type newType)
Set the type of this value.
unsigned getArgNumber () const
Returns the number of this argument.
Public Member Functions inherited from mlir::Value
constexpr Value (std::nullptr_t)
Value (ImplType ownerAndKind={})
Value (const Value &)=default
Value & operator= (const Value &)=default
template<typename U >
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
operator bool () const
bool operator== (const Value &other) const
bool operator!= (const Value &other) const
Type getType () const
Return the type of this value.
MLIRContext * getContext () const
Utility to get the associated MLIRContext that this value is defined in.
void setType (Type newType)
Mutate the type of this Value to be of the specified type.
Operation * getDefiningOp () const
If this value is the result of an operation, return the operation that defines it.
Location getLoc () const
If this value is the result of an operation, use it as a location, otherwise return an unknown location.
Region * getParentRegion ()
Return the Region in which this Value is defined.
IRObjectWithUseList< OpOperand > * getUseList () const
Provide the use list that is attached to this value.
void dropAllUses () const
Drop all uses of this object from their respective owners.
void replaceAllUsesWith (Value newValue) const
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead.
use_iterator use_begin () const
use_iterator use_end () const
use_range getUses () const
Returns a range of all uses, which is useful for iterating over all uses.
bool hasOneUse () const
Returns true if this value has exactly one use.
bool use_empty () const
Returns true if this value has no uses.
user_iterator user_begin () const
user_iterator user_end () const
user_range getUsers () const
Kind getKind () const
Returns the kind of this value.
void print (raw_ostream &os)
void print (raw_ostream &os, AsmState &state)
void dump ()
void printAsOperand (raw_ostream &os, AsmState &state)
Print this value as if it were an operand.
void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Static Public Member Functions
static bool classof (Value value)
Static Public Member Functions inherited from mlir::Value
static Value getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::Value
enum Kind { Kind::OpResult0 = 0, Kind::OpResult1 = 1, Kind::TrailingOpResult = 2, Kind::BlockArgument = 3 }
The enumeration represents the various different kinds of values the internal representation may take.
using ImplType = llvm::PointerIntPair< void *, 2, Kind, ImplTypeTraits >
using use_iterator = FilteredValueUseIterator< OpOperand >
This class implements an iterator over the uses of a value.
using use_range = iterator_range< use_iterator >
using user_iterator = ValueUserIterator< use_iterator, OpOperand >
using user_range = iterator_range< user_iterator >
Protected Member Functions inherited from mlir::Value
Value (detail::BlockArgumentImpl *impl)
Construct a value.
Value (Operation *op, unsigned resultNo)
Static Protected Member Functions inherited from mlir::Value
static bool canPackResultInline (unsigned resultNo)
Returns true if the given operation result can be packed inline.
Protected Attributes inherited from mlir::Value
ImplType ownerAndKind
This value represents the 'owner' of the value and its kind.
Detailed Description
Block arguments are values.
Definition at line 234 of file Value.h.
Member Function Documentation
classof()
static bool mlir::BlockArgument::classof (Value value) inline static
Definition at line 238 of file Value.h.
References mlir::Value::getKind().
getArgNumber()
unsigned BlockArgument::getArgNumber () const
Returns the number of this argument.
Definition at line 19 of file Block.cpp.
References mlir::Block::getArguments(), and getOwner().
Referenced by mlir::Liveness::print().
getOwner()
Block* mlir::BlockArgument::getOwner () const inline
Returns the block that owns this argument.
Definition at line 243 of file Value.h.
Referenced by canRegisterAlias(), getArgNumber(), mlir::getForInductionVarOwner(), and mlir::DominanceInfo::properlyDominates().
getType()
Type mlir::BlockArgument::getType () const inline
Return the type of this value.
Definition at line 246 of file Value.h.
Referenced by computeConversionSet(), mlir::TypeConverter::convertBlockSignature(), getLastStructuredControlFlowOpMergeBlock(), mlir::inlineCall(), mlir::inlineRegion(), printAttributions(), topologicalSort(), mlir::FuncOp::verify(), verify(), verifyBlockArgs(), and verifySuccessor().
setType()
void mlir::BlockArgument::setType (Type newType) inline
Set the type of this value.
Definition at line 249 of file Value.h.
The documentation for this class was generated from the following files:
include/mlir/IR/Value.h
lib/IR/Block.cpp