MLIR: mlir::detail::PassOptions::ListOption< DataType > Class Template Reference
mlir::detail::PassOptions::ListOption< DataType > Class Template Reference
This class represents a specific pass option that contains a list of values of the provided data type.
#include "mlir/Pass/PassOptions.h"
Public Member Functions
template<typename... Args>
ListOption (PassOptions &parent, StringRef arg, Args &&... args)
~ListOption () override=default
ListOption< DataType > & operator= (ArrayRef< DataType > values)
Allow assigning from an ArrayRef.
std::vector< DataType > * operator-> ()
Detailed Description
template<typename DataType>
class mlir::detail::PassOptions::ListOption< DataType >
This class represents a specific pass option that contains a list of values of the provided data type.
Definition at line 141 of file PassOptions.h.
Constructor & Destructor Documentation
ListOption()
template<typename DataType > template<typename... Args> mlir::detail::PassOptions::ListOption< DataType >::ListOption (PassOptions & parent, StringRef arg, Args &&... args) inline
Definition at line 146 of file PassOptions.h.
~ListOption()
template<typename DataType > mlir::detail::PassOptions::ListOption< DataType >::~ListOption () override default
Member Function Documentation
operator->()
template<typename DataType > std::vector<DataType>* mlir::detail::PassOptions::ListOption< DataType >::operator-> () inline
Definition at line 162 of file PassOptions.h.
References mlir::detail::PassOptions::copyOptionValuesFrom(), mlir::interleave(), mlir::detail::PassOptions::parseFromString(), mlir::detail::PassOptions::PassOptions(), and mlir::detail::PassOptions::print().
operator=()
template<typename DataType > ListOption<DataType>& mlir::detail::PassOptions::ListOption< DataType >::operator= (ArrayRef< DataType > values) inline
Allow assigning from an ArrayRef.
Definition at line 157 of file PassOptions.h.
The documentation for this class was generated from the following file:
include/mlir/Pass/PassOptions.h