MLIR: mlir::Identifier Class Reference
mlir::Identifier Class Reference
This class represents a uniqued string owned by an MLIRContext.
#include "mlir/IR/Identifier.h"
Public Member Functions
Identifier (const Identifier &)=default
Identifier & operator= (const Identifier &other)=default
StringRef strref () const
Return a StringRef for the string.
operator StringRef () const
Identifiers implicitly convert to StringRefs.
std::string str () const
Return an std::string.
const char * c_str () const
Return a null terminated C string.
const char * data () const
Return a pointer to the start of the string data.
unsigned size () const
Return the number of bytes in this string.
bool is (StringRef string) const
Return true if this identifier is the specified string.
const char * begin () const
const char * end () const
void print (raw_ostream &os) const
void dump () const
const void * getAsOpaquePointer () const
Static Public Member Functions
static Identifier get (StringRef str, MLIRContext *context)
Return an identifier for the specified string.
static Identifier getFromOpaquePointer (const void *pointer)
Detailed Description
This class represents a uniqued string owned by an MLIRContext.
Strings represented by this type cannot contain nul characters, and may not have a zero length.
This is a POD type with pointer size, so it should be passed around by value. The underlying data is owned by MLIRContext and is thus immortal for almost all clients.
Definition at line 26 of file Identifier.h.
Constructor & Destructor Documentation
Identifier()
mlir::Identifier::Identifier (const Identifier &) default
Referenced by getFromOpaquePointer().
Member Function Documentation
begin()
const char* mlir::Identifier::begin () const inline
Definition at line 54 of file Identifier.h.
c_str()
const char* mlir::Identifier::c_str () const inline
Return a null terminated C string.
Definition at line 43 of file Identifier.h.
data()
const char* mlir::Identifier::data () const inline
Return a pointer to the start of the string data.
Definition at line 46 of file Identifier.h.
Referenced by llvm::DenseMapInfo< mlir::Identifier >::getHashValue(), mlir::operator!=(), and mlir::operator==().
dump()
void Identifier::dump () const
Definition at line 45 of file AsmPrinter.cpp.
References print().
Referenced by end().
end()
const char* mlir::Identifier::end () const inline
Definition at line 55 of file Identifier.h.
References dump(), print(), and size().
get()
Identifier Identifier::get (StringRef str, MLIRContext * context) static
Return an identifier for the specified string.
Definition at line 426 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl().
Referenced by mlir::OperationState::addAttribute(), buildHexadecimalFloatLiteral(), extractSymbolReference(), mlir::FileLineColLoc::get(), mlir::AffineDmaStartOp::getAffineMapAttrForMemRef(), mlir::AffineDmaWaitOp::getAffineMapAttrForMemRef(), mlir::AffineLoadOp::getAffineMapAttrForMemRef(), mlir::AffineStoreOp::getAffineMapAttrForMemRef(), mlir::Builder::getIdentifier(), lowerAsEntryFunction(), mlir::OperationName::OperationName(), parseSymbol(), mlir::Dialect::parseType(), mlir::OpState::removeAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr(), mlir::OpState::setAttr(), mlir::Operation::setAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr(), and mlir::SymbolTable::setSymbolVisibility().
getAsOpaquePointer()
const void* mlir::Identifier::getAsOpaquePointer () const inline
Definition at line 60 of file Identifier.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::Identifier >::getAsVoidPointer().
getFromOpaquePointer()
static Identifier mlir::Identifier::getFromOpaquePointer (const void * pointer) inline static
Definition at line 63 of file Identifier.h.
References Identifier().
Referenced by llvm::DenseMapInfo< mlir::Identifier >::getEmptyKey(), llvm::PointerLikeTypeTraits< mlir::Identifier >::getFromVoidPointer(), and llvm::DenseMapInfo< mlir::Identifier >::getTombstoneKey().
is()
bool mlir::Identifier::is (StringRef string) const inline
Return true if this identifier is the specified string.
Definition at line 52 of file Identifier.h.
References strref().
Referenced by mlir::operator!=(), and mlir::operator==().
operator StringRef()
mlir::Identifier::operator StringRef () const inline
Identifiers implicitly convert to StringRefs.
Definition at line 37 of file Identifier.h.
References strref().
operator=()
Identifier& mlir::Identifier::operator= (const Identifier & other) default
print()
void Identifier::print (raw_ostream & os) const
Definition at line 43 of file AsmPrinter.cpp.
Referenced by end(), and mlir::operator<<().
size()
unsigned mlir::Identifier::size () const inline
Return the number of bytes in this string.
Definition at line 49 of file Identifier.h.
Referenced by end(), and strref().
str()
std::string mlir::Identifier::str () const inline
Return an std::string.
Definition at line 40 of file Identifier.h.
References strref().
strref()
StringRef mlir::Identifier::strref () const inline
Return a StringRef for the string.
Definition at line 34 of file Identifier.h.
References size().
Referenced by mlir::hash_value(), is(), operator StringRef(), mlir::Diagnostic::operator<<(), str(), mlir::OpaqueType::verifyConstructionInvariants(), and mlir::OpaqueAttr::verifyConstructionInvariants().
The documentation for this class was generated from the following files:
include/mlir/IR/Identifier.h
lib/IR/AsmPrinter.cpp
lib/IR/MLIRContext.cpp