MLIR: mlir::tblgen::Pred Class Reference
mlir::tblgen::Pred Class Reference
#include "mlir/TableGen/Predicate.h"
Public Member Functions
Pred ()
Pred (const llvm::Record *record)
Pred (const llvm::Init *init)
bool isNull () const
std::string getCondition () const
bool isCombined () const
bool operator== (const Pred &other) const
ArrayRef< llvm::SMLoc > getLoc () const
Protected Attributes
const llvm::Record * def
Detailed Description
Definition at line 33 of file Predicate.h.
Constructor & Destructor Documentation
Pred() [1/3]
mlir::tblgen::Pred::Pred () inline explicit
Definition at line 36 of file Predicate.h.
Pred() [2/3]
tblgen::Pred::Pred (const llvm::Record * record) explicit
Definition at line 24 of file Predicate.cpp.
References def.
Pred() [3/3]
tblgen::Pred::Pred (const llvm::Init * init) explicit
Definition at line 30 of file Predicate.cpp.
References def.
Member Function Documentation
getCondition()
std::string tblgen::Pred::getCondition () const
Definition at line 35 of file Predicate.cpp.
References def.
Referenced by buildPredicateTree(), mlir::tblgen::Constraint::getConditionTemplate(), and mlir::tblgen::PredOpTrait::getPredTemplate().
getLoc()
ArrayRef< llvm::SMLoc > tblgen::Pred::getLoc () const
Definition at line 48 of file Predicate.cpp.
References def.
isCombined()
bool tblgen::Pred::isCombined () const
Definition at line 44 of file Predicate.cpp.
References def.
Referenced by buildPredicateTree(), and getPredCombinerKind().
isNull()
bool mlir::tblgen::Pred::isNull () const inline
Definition at line 45 of file Predicate.h.
Referenced by mlir::tblgen::CPred::getConditionImpl(), and mlir::tblgen::NamedTypeConstraint::hasPredicate().
operator==()
bool mlir::tblgen::Pred::operator== (const Pred & other) const inline
Definition at line 56 of file Predicate.h.
References def.
Member Data Documentation
def
const llvm::Record* mlir::tblgen::Pred::def protected
Definition at line 63 of file Predicate.h.
Referenced by mlir::tblgen::CombinedPred::CombinedPred(), mlir::tblgen::CPred::CPred(), mlir::tblgen::CombinedPred::getChildren(), mlir::tblgen::CombinedPred::getCombinerDef(), getCondition(), mlir::tblgen::CPred::getConditionImpl(), getLoc(), mlir::tblgen::SubstLeavesPred::getPattern(), mlir::tblgen::ConcatPred::getPrefix(), mlir::tblgen::SubstLeavesPred::getReplacement(), mlir::tblgen::ConcatPred::getSuffix(), isCombined(), operator==(), and Pred().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Predicate.h
lib/TableGen/Predicate.cpp