MLIR: mlir::DominanceInfo Class Reference
mlir::DominanceInfo Class Reference
A class for computing basic dominance information.
#include "mlir/Analysis/Dominance.h"
Public Member Functions
bool properlyDominates (Operation *a, Operation *b)
Return true if operation A properly dominates operation B.
bool dominates (Operation *a, Operation *b)
Return true if operation A dominates operation B.
bool properlyDominates (Value a, Operation *b)
Return true if value A properly dominates operation B.
bool dominates (Value a, Operation *b)
Return true if operation A dominates operation B.
bool dominates (Block *a, Block *b)
Return true if the specified block A dominates block B.
bool properlyDominates (Block *a, Block *b)
Return true if the specified block A properly dominates block B.
DominanceInfoNode * getNode (Block *a)
Return the dominance node from the Region containing block A.
void updateDFSNumbers ()
Update the internal DFS numbers for the dominance nodes.
Public Member Functions inherited from mlir::detail::DominanceInfoBase< false >
DominanceInfoBase (Operation *op)
DominanceInfoBase (DominanceInfoBase &&)=default
DominanceInfoBase (const DominanceInfoBase &)=delete
DominanceInfoBase & operator= (DominanceInfoBase &&)=default
DominanceInfoBase & operator= (const DominanceInfoBase &)=delete
void recalculate (Operation *op)
Recalculate the dominance info.
DominanceInfoNode * getRootNode (Region *region)
Get the root dominance node of the given region.
Additional Inherited Members
Protected Types inherited from mlir::detail::DominanceInfoBase< false >
using super = DominanceInfoBase< IsPostDom >
Protected Member Functions inherited from mlir::detail::DominanceInfoBase< false >
bool properlyDominates (Block *a, Block *b)
Return true if the specified block A properly dominates block B.
Protected Attributes inherited from mlir::detail::DominanceInfoBase< false >
DenseMap< Region *, std::unique_ptr< base > > dominanceInfos
A mapping of regions to their base dominator tree.
Detailed Description
A class for computing basic dominance information.
Definition at line 55 of file Dominance.h.
Member Function Documentation
dominates() [1/3]
bool mlir::DominanceInfo::dominates (Operation * a, Operation * b) inline
Return true if operation A dominates operation B.
Definition at line 63 of file Dominance.h.
dominates() [2/3]
bool mlir::DominanceInfo::dominates (Value a, Operation * b) inline
Return true if operation A dominates operation B.
Definition at line 71 of file Dominance.h.
References mlir::Value::getDefiningOp().
dominates() [3/3]
bool mlir::DominanceInfo::dominates (Block * a, Block * b) inline
Return true if the specified block A dominates block B.
Definition at line 76 of file Dominance.h.
getNode()
DominanceInfoNode * DominanceInfo::getNode (Block * a)
Return the dominance node from the Region containing block A.
Definition at line 135 of file Dominance.cpp.
References mlir::Block::getParent().
properlyDominates() [1/3]
bool DominanceInfo::properlyDominates (Operation * a, Operation * b)
Return true if operation A properly dominates operation B.
Definition at line 97 of file Dominance.cpp.
References mlir::Operation::getBlock(), and mlir::Operation::isBeforeInBlock().
properlyDominates() [2/3]
bool DominanceInfo::properlyDominates (Value a, Operation * b)
Return true if value A properly dominates operation B.
Definition at line 121 of file Dominance.cpp.
References mlir::Value::cast(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::BlockArgument::getOwner(), mlir::Operation::getParentRegion(), and mlir::Region::isAncestor().
properlyDominates() [3/3]
bool mlir::DominanceInfo::properlyDominates (Block * a, Block * b) inline
Return true if the specified block A properly dominates block B.
Definition at line 81 of file Dominance.h.
updateDFSNumbers()
void DominanceInfo::updateDFSNumbers ()
Update the internal DFS numbers for the dominance nodes.
Definition at line 141 of file Dominance.cpp.
The documentation for this class was generated from the following files:
include/mlir/Analysis/Dominance.h
lib/Analysis/Dominance.cpp