MLIR: mlir::tblgen::Pattern Class Reference
mlir::tblgen::Pattern Class Reference
#include "mlir/TableGen/Pattern.h"
Public Types
using IdentifierLine = std::pair< StringRef, unsigned >
Public Member Functions
Pattern (const llvm::Record *def, RecordOperatorMap *mapper)
DagNode getSourcePattern () const
int getNumResultPatterns () const
DagNode getResultPattern (unsigned index) const
void collectSourcePatternBoundSymbols (SymbolInfoMap &infoMap)
void collectResultPatternBoundSymbols (SymbolInfoMap &infoMap)
const Operator & getSourceRootOp ()
Operator & getDialectOp (DagNode node)
std::vector< AppliedConstraint > getConstraints () const
int getBenefit () const
std::vector< IdentifierLine > getLocation () const
Detailed Description
Definition at line 351 of file Pattern.h.
Member Typedef Documentation
IdentifierLine
using mlir::tblgen::Pattern::IdentifierLine = std::pair<StringRef, unsigned>
Definition at line 384 of file Pattern.h.
Constructor & Destructor Documentation
Pattern()
tblgen::Pattern::Pattern (const llvm::Record * def, RecordOperatorMap * mapper) explicit
Definition at line 422 of file Pattern.cpp.
Member Function Documentation
collectResultPatternBoundSymbols()
void tblgen::Pattern::collectResultPatternBoundSymbols (tblgen::SymbolInfoMap & infoMap)
Definition at line 446 of file Pattern.cpp.
References getNumResultPatterns(), and getResultPattern().
collectSourcePatternBoundSymbols()
void tblgen::Pattern::collectSourcePatternBoundSymbols (tblgen::SymbolInfoMap & infoMap)
Definition at line 439 of file Pattern.cpp.
References getSourcePattern().
getBenefit()
int tblgen::Pattern::getBenefit () const
Definition at line 492 of file Pattern.cpp.
References mlir::tblgen::DagNode::getNumOps(), and getSourcePattern().
getConstraints()
std::vector< tblgen::AppliedConstraint > tblgen::Pattern::getConstraints () const
Definition at line 464 of file Pattern.cpp.
getDialectOp()
tblgen::Operator & tblgen::Pattern::getDialectOp (DagNode node)
Definition at line 460 of file Pattern.cpp.
References mlir::tblgen::DagNode::getDialectOp().
Referenced by getLocation().
getLocation()
std::vector< tblgen::Pattern::IdentifierLine > tblgen::Pattern::getLocation () const
Definition at line 505 of file Pattern.cpp.
References mlir::tblgen::SymbolInfoMap::bindOpArgument(), mlir::tblgen::SymbolInfoMap::bindOpResult(), mlir::tblgen::DagNode::getArgAsNestedDag(), mlir::tblgen::DagNode::getArgName(), getDialectOp(), mlir::tblgen::Operator::getNumArgs(), mlir::tblgen::DagNode::getNumArgs(), mlir::tblgen::Operator::getOperationName(), mlir::tblgen::DagNode::getSymbol(), and mlir::tblgen::DagNode::isOperation().
getNumResultPatterns()
int tblgen::Pattern::getNumResultPatterns () const
Definition at line 429 of file Pattern.cpp.
Referenced by collectResultPatternBoundSymbols().
getResultPattern()
tblgen::DagNode tblgen::Pattern::getResultPattern (unsigned index) const
Definition at line 434 of file Pattern.cpp.
Referenced by collectResultPatternBoundSymbols().
getSourcePattern()
tblgen::DagNode tblgen::Pattern::getSourcePattern () const
Definition at line 425 of file Pattern.cpp.
Referenced by collectSourcePatternBoundSymbols(), getBenefit(), and getSourceRootOp().
getSourceRootOp()
const tblgen::Operator & tblgen::Pattern::getSourceRootOp ()
Definition at line 456 of file Pattern.cpp.
References mlir::tblgen::DagNode::getDialectOp(), and getSourcePattern().
The documentation for this class was generated from the following files:
include/mlir/TableGen/Pattern.h
lib/TableGen/Pattern.cpp