MLIR: mlir::LinalgTypeConverter Class Reference
mlir::LinalgTypeConverter Class Reference
#include "mlir/Conversion/LinalgToLLVM/LinalgToLLVM.h"
Public Member Functions
Type convertType (Type t) override
This hook simplifies defining 1-1 type conversions.
Public Member Functions inherited from mlir::LLVMTypeConverter
LLVMTypeConverter (MLIRContext *ctx)
Type convertType (Type t) override
Convert types to LLVM IR.
LLVM::LLVMType convertFunctionSignature (FunctionType type, bool isVariadic, SignatureConversion &result)
Convert a function type.
Type packFunctionResults (ArrayRef< Type > types)
Convert a non-empty list of types to be returned from a function into a supported LLVM IR type.
llvm::LLVMContext & getLLVMContext ()
Returns the LLVM context.
LLVM::LLVMDialect * getDialect ()
Returns the LLVM dialect.
SmallVector< Value, 4 > promoteMemRefDescriptors (Location loc, ValueRange opOperands, ValueRange operands, OpBuilder &builder)
Promote the LLVM struct representation of all MemRef descriptors to stack and use pointers to struct to avoid the complexity of the platform-specific C/C++ ABI lowering related to struct argument passing.
Value promoteOneMemRefDescriptor (Location loc, Value operand, OpBuilder &builder)
Promote the LLVM struct representation of one MemRef descriptor to stack and use pointer to struct to avoid the complexity of the platform-specific C/C++ ABI lowering related to struct argument passing.
Public Member Functions inherited from mlir::TypeConverter
virtual ~TypeConverter ()=default
virtual LogicalResult convertType (Type t, SmallVectorImpl< Type > &results)
This hook allows for converting a type.
LogicalResult convertTypes (ArrayRef< Type > types, SmallVectorImpl< Type > &results)
Convert the given set of types, filling 'results' as necessary.
bool isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
bool isSignatureLegal (FunctionType funcType)
Return true if the inputs and outputs of the given function type are legal.
virtual LogicalResult convertSignatureArg (unsigned inputNo, Type type, SignatureConversion &result)
This hook allows for converting a specific argument of a signature.
Optional< SignatureConversion > convertBlockSignature (Block *block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
virtual Operation * materializeConversion (PatternRewriter &rewriter, Type resultType, ArrayRef< Value > inputs, Location loc)
This hook allows for materializing a conversion from a set of types into one result type by generating a cast operation of some kind.
Additional Inherited Members
Protected Attributes inherited from mlir::LLVMTypeConverter
llvm::Module * module
LLVM IR module used to parse/create types.
LLVM::LLVMDialect * llvmDialect
Detailed Description
Definition at line 19 of file LinalgToLLVM.h.
Member Function Documentation
convertType()
Type LinalgTypeConverter::convertType (Type t) override virtual
This hook simplifies defining 1-1 type conversions.
This function returns the type to convert to on success, and a null type on failure.
Reimplemented from mlir::TypeConverter.
Definition at line 422 of file LinalgToLLVM.cpp.
References convertLinalgType(), mlir::LLVMTypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::AffineMapAttr::get(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::OwningRewritePatternList::insert(), and mlir::PatternRewriter::replaceOpWithNewOp().
The documentation for this class was generated from the following files:
include/mlir/Conversion/LinalgToLLVM/LinalgToLLVM.h
lib/Conversion/LinalgToLLVM/LinalgToLLVM.cpp