MLIR: mlir::tblgen::DagNode Class Reference
mlir::tblgen::DagNode Class Reference
#include "mlir/TableGen/Pattern.h"
Public Member Functions
DagNode (const llvm::DagInit *node)
operator bool () const
StringRef getSymbol () const
Operator & getDialectOp (RecordOperatorMap *mapper) const
int getNumOps () const
int getNumArgs () const
bool isNestedDagArg (unsigned index) const
DagNode getArgAsNestedDag (unsigned index) const
DagLeaf getArgAsLeaf (unsigned index) const
StringRef getArgName (unsigned index) const
bool isReplaceWithValue () const
bool isNativeCodeCall () const
bool isOperation () const
StringRef getNativeCodeTemplate () const
void print (raw_ostream &os) const
Detailed Description
Definition at line 122 of file Pattern.h.
Constructor & Destructor Documentation
DagNode()
mlir::tblgen::DagNode::DagNode (const llvm::DagInit * node) inline explicit
Definition at line 124 of file Pattern.h.
Member Function Documentation
getArgAsLeaf()
tblgen::DagLeaf tblgen::DagNode::getArgAsLeaf (unsigned index) const
Definition at line 147 of file Pattern.cpp.
References mlir::tblgen::DagLeaf::DagLeaf().
getArgAsNestedDag()
tblgen::DagNode tblgen::DagNode::getArgAsNestedDag (unsigned index) const
Definition at line 143 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::getLocation().
getArgName()
StringRef tblgen::DagNode::getArgName (unsigned index) const
Definition at line 152 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::getLocation().
getDialectOp()
Operator & tblgen::DagNode::getDialectOp (RecordOperatorMap * mapper) const
Definition at line 119 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::getDialectOp(), and mlir::tblgen::Pattern::getSourceRootOp().
getNativeCodeTemplate()
llvm::StringRef tblgen::DagNode::getNativeCodeTemplate () const
Definition at line 108 of file Pattern.cpp.
References mlir::tblgen::DagLeaf::isNativeCodeCall().
getNumArgs()
int tblgen::DagNode::getNumArgs () const
Definition at line 137 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::getLocation().
getNumOps()
int tblgen::DagNode::getNumOps () const
Definition at line 128 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::getBenefit().
getSymbol()
llvm::StringRef tblgen::DagNode::getSymbol () const
Definition at line 115 of file Pattern.cpp.
Referenced by mlir::tblgen::Pattern::getLocation().
isNativeCodeCall()
bool tblgen::DagNode::isNativeCodeCall () const
Definition at line 98 of file Pattern.cpp.
isNestedDagArg()
bool tblgen::DagNode::isNestedDagArg (unsigned index) const
Definition at line 139 of file Pattern.cpp.
isOperation()
bool tblgen::DagNode::isOperation () const
Definition at line 104 of file Pattern.cpp.
References mlir::tblgen::DagLeaf::isNativeCodeCall().
Referenced by mlir::tblgen::Pattern::getLocation().
isReplaceWithValue()
bool tblgen::DagNode::isReplaceWithValue () const
Definition at line 156 of file Pattern.cpp.
operator bool()
mlir::tblgen::DagNode::operator bool () const inline
Definition at line 128 of file Pattern.h.
References print().
print()
void tblgen::DagNode::print (raw_ostream & os) const
Definition at line 161 of file Pattern.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/Pattern.h
lib/TableGen/Pattern.cpp