MLIR: mlir::quantizer::TargetConfiguration Class Reference
mlir::quantizer::TargetConfiguration Class Reference abstract
Defines quantization configuration for the target.
#include "mlir/Quantizer/Support/Configuration.h"
Public Types
using OpHandlerFn = std::function< void(Operation *op, CAGSlice &cag)>
Public Member Functions
TargetConfiguration (SolverContext &context)
virtual ~TargetConfiguration ()=default
unsigned addCandidateType (quant::AnyQuantizedType quantizedType, CandidateQuantizedType::Scheme scheme)
Adds a candidate type, returning its ordinal.
const CandidateQuantizedType & getCandidateType (unsigned index) const
Gets a prototype scheme by index.
ArrayRef< CandidateQuantizedType > getCandidateTypes () const
llvm::SmallBitVector getAllCandidateTypesMask () const
Gets a mask of all enabled candidate types by ordinal.
llvm::SmallBitVector getCandidateTypeDisabledExceptMask (ArrayRef< unsigned > exceptOrdinals) const
Gets a mask with every candidate type except those in the given mask.
template<typename OpTy >
void addOpHandler (OpHandlerFn fn)
Adds an op handler.
template<typename OpTy >
void addRequireStatsOp ()
Adds an operation which requires statistics at its result nodes for best quantization performance.
bool isRequireStatsOp (Operation *op) const
Returns whether opName is a RequireStatsOp.
template<typename OpTy >
void addValueIdentityOp ()
Adds an op which does not mutate its values but may mutate its shape or combine its operands in an arbitrary way.
void handleOp (Operation *op, CAGSlice &cag) const
Handles the operation if a handler is defined for it.
virtual void finalizeAnchors (CAGSlice &cag) const
Finalizes the CAG after all anchors have been added.
virtual bool isHandledType (Type t) const =0
Whether an operand or result type is subject to analysis by this config.
Static Public Attributes
static constexpr size_t MaxSchemeIndex = 31
Protected Member Functions
virtual void addValueIdentityOpByName (StringRef opName)=0
void addOpHandlerByName (StringRef name, OpHandlerFn fn)
Detailed Description
Defines quantization configuration for the target.
The settings here depend on a variety of details about the deployment environment, although, where we have control over such things, we do try to standardize as possible.
Non-const methods are used to setup the configuration. It is expected that const instances/references are used post-build.
Definition at line 43 of file Configuration.h.
Member Typedef Documentation
OpHandlerFn
using mlir::quantizer::TargetConfiguration::OpHandlerFn = std::function<void(Operation *op, CAGSlice &cag)>
Definition at line 46 of file Configuration.h.
Constructor & Destructor Documentation
TargetConfiguration()
TargetConfiguration::TargetConfiguration (SolverContext & context)
Definition at line 20 of file Configuration.cpp.
~TargetConfiguration()
virtual mlir::quantizer::TargetConfiguration::~TargetConfiguration () virtual default
Member Function Documentation
addCandidateType()
unsigned mlir::quantizer::TargetConfiguration::addCandidateType (quant::AnyQuantizedType quantizedType, CandidateQuantizedType::Scheme scheme) inline
Adds a candidate type, returning its ordinal.
Definition at line 52 of file Configuration.h.
addOpHandler()
template<typename OpTy > void mlir::quantizer::TargetConfiguration::addOpHandler (OpHandlerFn fn) inline
Adds an op handler.
Definition at line 89 of file Configuration.h.
References addOpHandlerByName().
addOpHandlerByName()
void TargetConfiguration::addOpHandlerByName (StringRef name, OpHandlerFn fn) protected
Definition at line 22 of file Configuration.cpp.
Referenced by addOpHandler(), and finalizeAnchors().
addRequireStatsOp()
template<typename OpTy > void mlir::quantizer::TargetConfiguration::addRequireStatsOp () inline
Adds an operation which requires statistics at its result nodes for best quantization performance.
Note that the opName StringRef is expected to come from getOperationName() and be static.
Definition at line 97 of file Configuration.h.
References isRequireStatsOp().
addValueIdentityOp()
template<typename OpTy > void mlir::quantizer::TargetConfiguration::addValueIdentityOp () inline
Adds an op which does not mutate its values but may mutate its shape or combine its operands in an arbitrary way.
Such ops are expected to have the same types for operands and results and must be capable of operating on storage types.
Definition at line 109 of file Configuration.h.
References addValueIdentityOpByName(), and handleOp().
addValueIdentityOpByName()
virtual void mlir::quantizer::TargetConfiguration::addValueIdentityOpByName (StringRef opName) protected pure virtual
Referenced by addValueIdentityOp(), and finalizeAnchors().
finalizeAnchors()
virtual void mlir::quantizer::TargetConfiguration::finalizeAnchors (CAGSlice & cag) const inline virtual
Finalizes the CAG after all anchors have been added.
Definition at line 117 of file Configuration.h.
References addOpHandlerByName(), addValueIdentityOpByName(), and isHandledType().
Referenced by validateTypeConversion().
getAllCandidateTypesMask()
llvm::SmallBitVector mlir::quantizer::TargetConfiguration::getAllCandidateTypesMask () const inline
Gets a mask of all enabled candidate types by ordinal.
Definition at line 73 of file Configuration.h.
Referenced by solveUniformType().
getCandidateType()
const CandidateQuantizedType& mlir::quantizer::TargetConfiguration::getCandidateType (unsigned index) const inline
Gets a prototype scheme by index.
Definition at line 63 of file Configuration.h.
getCandidateTypeDisabledExceptMask()
llvm::SmallBitVector mlir::quantizer::TargetConfiguration::getCandidateTypeDisabledExceptMask (ArrayRef< unsigned > exceptOrdinals) const inline
Gets a mask with every candidate type except those in the given mask.
Definition at line 79 of file Configuration.h.
getCandidateTypes()
ArrayRef<CandidateQuantizedType> mlir::quantizer::TargetConfiguration::getCandidateTypes () const inline
Definition at line 68 of file Configuration.h.
Referenced by solveUniformType().
handleOp()
void TargetConfiguration::handleOp (Operation * op, CAGSlice & cag) const
Handles the operation if a handler is defined for it.
Definition at line 35 of file Configuration.cpp.
References mlir::Operation::getName(), and mlir::OperationName::getStringRef().
Referenced by addValueIdentityOp(), and validateTypeConversion().
isHandledType()
virtual bool mlir::quantizer::TargetConfiguration::isHandledType (Type t) const pure virtual
Whether an operand or result type is subject to analysis by this config.
Referenced by finalizeAnchors().
isRequireStatsOp()
bool TargetConfiguration::isRequireStatsOp (Operation * op) const
Returns whether opName is a RequireStatsOp.
Definition at line 30 of file Configuration.cpp.
References mlir::Operation::getName(), and mlir::OperationName::getStringRef().
Referenced by addRequireStatsOp().
Member Data Documentation
MaxSchemeIndex
constexpr size_t mlir::quantizer::TargetConfiguration::MaxSchemeIndex = 31 static
Definition at line 45 of file Configuration.h.
The documentation for this class was generated from the following files:
include/mlir/Quantizer/Support/Configuration.h
lib/Quantizer/Support/Configuration.cpp