MLIR: mlir::edsc::ScopedContext Class Reference
mlir::edsc::ScopedContext Class Reference
Helper class to transparently handle builder insertion points by RAII.
#include "mlir/EDSC/Builders.h"
Public Member Functions
ScopedContext (OpBuilder &builder, Location location)
ScopedContext (OpBuilder &builder, OpBuilder::InsertPoint newInsertPt, Location location)
Sets the insertion point of the builder to 'newInsertPt' for the duration of the scope.
~ScopedContext ()
Static Public Member Functions
static MLIRContext * getContext ()
static OpBuilder & getBuilder ()
static Location getLocation ()
Friends
class NestedBuilder
Only NestedBuilder (which is used to create an operation with a body) may access private members in order to implement scoping.
Detailed Description
Helper class to transparently handle builder insertion points by RAII.
As its name indicates, a ScopedContext is means to be used locally in a scoped fashion. This abstracts away all the boilerplate related to checking proper usage of captures, NestedBuilders as well as handling the setting and restoring of insertion points.
Definition at line 43 of file Builders.h.
Constructor & Destructor Documentation
ScopedContext() [1/2]
mlir::edsc::ScopedContext::ScopedContext (OpBuilder & builder, Location location)
Definition at line 18 of file Builders.cpp.
References ScopedContext().
Referenced by ScopedContext().
ScopedContext() [2/2]
mlir::edsc::ScopedContext::ScopedContext (OpBuilder & builder, OpBuilder::InsertPoint newInsertPt, Location location)
Sets the insertion point of the builder to 'newInsertPt' for the duration of the scope.
The existing insertion point of the builder is restored on destruction.
Definition at line 28 of file Builders.cpp.
References mlir::OpBuilder::restoreInsertionPoint(), and ScopedContext().
~ScopedContext()
mlir::edsc::ScopedContext::~ScopedContext ()
Definition at line 39 of file Builders.cpp.
References mlir::OpBuilder::restoreInsertionPoint().
Member Function Documentation
getBuilder()
OpBuilder & mlir::edsc::ScopedContext::getBuilder () static
Definition at line 52 of file Builders.cpp.
Referenced by convertLinalgType(), mlir::edsc::ValueHandle::create(), mlir::edsc::OperationHandle::create(), mlir::edsc::BlockHandle::create(), mlir::edsc::ValueHandle::createComposedAffineApply(), createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::BlockHandle::createInRegion(), mlir::edsc::OperationHandle::createOp(), emitLoopRanges(), mlir::edsc::NestedBuilder::enter(), getContext(), mlir::edsc::IndexHandle::IndexHandle(), mlir::edsc::LoopBuilder::makeAffine(), mlir::edsc::makeGenericLinalgOp(), mlir::edsc::IndexHandle::operator=(), permuteIvs(), mlir::linalg::tileLinalgOp(), and mlir::edsc::ValueHandle::ValueHandle().
getContext()
MLIRContext * mlir::edsc::ScopedContext::getContext () static
Definition at line 64 of file Builders.cpp.
References getBuilder(), and mlir::Builder::getContext().
Referenced by createBinaryIndexHandle(), mlir::edsc::ops::linalg_conv_nhwc(), mlir::edsc::ops::linalg_dilated_conv_nhwc(), mlir::edsc::ops::linalg_matmul(), and mlir::linalg::tileLinalgOp().
getLocation()
Location mlir::edsc::ScopedContext::getLocation () static
Definition at line 58 of file Builders.cpp.
Referenced by convertLinalgType(), mlir::edsc::ValueHandle::create(), mlir::edsc::OperationHandle::create(), mlir::edsc::ValueHandle::createComposedAffineApply(), createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::OperationHandle::createOp(), emitLoopRanges(), mlir::edsc::NestedBuilder::enter(), mlir::edsc::makeGenericLinalgOp(), permuteIvs(), mlir::linalg::tileLinalgOp(), and mlir::edsc::ValueHandle::ValueHandle().
Friends And Related Function Documentation
NestedBuilder
friend class NestedBuilder friend
Only NestedBuilder (which is used to create an operation with a body) may access private members in order to implement scoping.
Definition at line 61 of file Builders.h.
The documentation for this class was generated from the following files:
include/mlir/EDSC/Builders.h
lib/EDSC/Builders.cpp