MLIR: mlir::SDBMDiffExpr Class Reference
mlir::SDBMDiffExpr Class Reference
SDBM difference expression.
#include "mlir/Dialect/SDBM/SDBMExpr.h"
Public Types
using ImplType = detail::SDBMDiffExprStorage
Public Types inherited from mlir::SDBMVaryingExpr
using ImplType = detail::SDBMExprStorage
Public Types inherited from mlir::SDBMExpr
using ImplType = detail::SDBMExprStorage
Public Member Functions
SDBMDirectExpr getLHS () const
SDBMTermExpr getRHS () const
Public Member Functions inherited from mlir::SDBMExpr
SDBMExpr ()
SDBMExpr (ImplType *expr)
SDBMExpr (const SDBMExpr &)=default
SDBM expressions are thin wrappers around a unique'ed immutable pointer, which makes them trivially assignable and trivially copyable.
SDBMExpr & operator= (const SDBMExpr &)=default
bool operator== (const SDBMExpr &other) const
SDBM expressions can be compared straight-forwardly.
bool operator!= (const SDBMExpr &other) const
operator bool () const
SDBM expressions are convertible to bool: null expressions are converted to false, non-null expressions are converted to true.
bool operator! () const
SDBMExpr operator- ()
Negate the given SDBM expression.
void print (raw_ostream &os) const
Prints the SDBM expression.
void dump () const
template<typename U >
bool isa () const
LLVM-style casts.
template<typename U >
U dyn_cast () const
template<typename U >
U cast () const
::llvm::hash_code hash_value () const
Support for LLVM hashing.
SDBMExprKind getKind () const
Returns the kind of the SDBM expression.
MLIRContext * getContext () const
Returns the MLIR context in which this expression lives.
SDBMDialect * getDialect () const
Returns the SDBM dialect instance.
AffineExpr getAsAffineExpr () const
Convert the SDBM expression into an Affine expression.
Static Public Member Functions
static SDBMDiffExpr get (SDBMDirectExpr lhs, SDBMTermExpr rhs)
Obtain or create a difference expression unique'ed in the given context.
static bool isClassFor (const SDBMExpr &expr)
Static Public Member Functions inherited from mlir::SDBMVaryingExpr
static bool isClassFor (const SDBMExpr &expr)
Static Public Member Functions inherited from mlir::SDBMExpr
static Optional< SDBMExpr > tryConvertAffineExpr (AffineExpr affine)
Try constructing an SDBM expression from the given affine expression.
Additional Inherited Members
Protected Attributes inherited from mlir::SDBMExpr
ImplType * impl
Detailed Description
SDBM difference expression.
LHS is a direct expression, i.e. it may be a sum of a term and a constant. RHS is a term expression. Thus the expression (t1 - t2 + C) with term expressions t1,t2 is represented as diff(sum(t1, C), t2) and it is possible to extract the constant factor without negating it.
Definition at line 255 of file SDBMExpr.h.
Member Typedef Documentation
ImplType
using mlir::SDBMDiffExpr::ImplType = detail::SDBMDiffExprStorage
Definition at line 257 of file SDBMExpr.h.
Member Function Documentation
get()
SDBMDiffExpr SDBMDiffExpr::get (SDBMDirectExpr lhs, SDBMTermExpr rhs) static
Obtain or create a difference expression unique'ed in the given context.
Definition at line 530 of file SDBMExpr.cpp.
References mlir::Diff, mlir::StorageUniquer::get(), mlir::SDBMExpr::getDialect(), and mlir::SDBMDialect::getUniquer().
Referenced by addConstant(), buildDiffExpr(), mlir::SDBMExpr::dump(), and mlir::SDBMExpr::tryConvertAffineExpr().
getLHS()
SDBMDirectExpr SDBMDiffExpr::getLHS () const
Definition at line 539 of file SDBMExpr.cpp.
References mlir::SDBMExpr::impl.
Referenced by collectSDBMBuildInfo(), mlir::SDBMExpr::dump(), foldSumDiff(), mlir::SDBM::get(), mlir::SDBMExpr::getAsAffineExpr(), mlir::ops_assertions::operator+(), and mlir::SDBMExpr::print().
getRHS()
SDBMTermExpr SDBMDiffExpr::getRHS () const
Definition at line 543 of file SDBMExpr.cpp.
References mlir::SDBMExpr::impl.
Referenced by collectSDBMBuildInfo(), mlir::SDBMExpr::dump(), foldSumDiff(), mlir::SDBMExpr::getAsAffineExpr(), mlir::ops_assertions::operator+(), and mlir::SDBMExpr::print().
isClassFor()
static bool mlir::SDBMDiffExpr::isClassFor (const SDBMExpr & expr) inline static
Definition at line 263 of file SDBMExpr.h.
References mlir::Diff, and mlir::SDBMExpr::getKind().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SDBM/SDBMExpr.h
lib/Dialect/SDBM/SDBMExpr.cpp