MLIR: mlir::TensorType Class Reference
mlir::TensorType Class Reference
Tensor types represent multi-dimensional arrays, and have two variants: RankedTensorType and UnrankedTensorType.
#include "mlir/IR/StandardTypes.h"
Static Public Member Functions
static bool isValidElementType (Type type)
Return true if the specified element type is ok in a tensor.
static bool classof (Type type)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::ShapedType
static bool classof (Type type)
Methods for support type inquiry through isa, cast, and dyn_cast.
static constexpr bool isDynamic (int64_t dSize)
Whether the given dimension size indicates a dynamic dimension.
static constexpr bool isDynamicStrideOrOffset (int64_t dStrideOrOffset)
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::ShapedType
using ImplType = detail::ShapedTypeStorage
Public Types inherited from mlir::Type
enum Kind {
Function, Opaque, LAST_BUILTIN_TYPE = Opaque, DEFINE_SYM_KIND_RANGE,
DEFINE_SYM_KIND_RANGE
}
Integer identifier for all the concrete type kinds.
template<typename ConcreteType , typename BaseType , typename StorageType = DefaultTypeStorage>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer >
Utility class for implementing types.
using ImplType = TypeStorage
Public Member Functions inherited from mlir::ShapedType
Type getElementType () const
Return the element type.
unsigned getElementTypeBitWidth () const
If an element type is an integer or a float, return its width.
int64_t getNumElements () const
If it has static shape, return the number of elements. Otherwise, abort.
int64_t getRank () const
If this is a ranked type, return the rank. Otherwise, abort.
bool hasRank () const
Whether or not this is a ranked type.
ArrayRef< int64_t > getShape () const
If this is a ranked type, return the shape. Otherwise, abort.
bool hasStaticShape () const
If this is unranked type or any dimension has unknown size (<0), it doesn't have static shape.
bool hasStaticShape (ArrayRef< int64_t > shape) const
If this has a static shape and the shape is equal to shape return true.
int64_t getNumDynamicDims () const
If this is a ranked type, return the number of dimensions with dynamic size.
int64_t getDimSize (int64_t i) const
If this is ranked type, return the size of the specified dimension.
unsigned getDynamicDimIndex (unsigned index) const
Returns the position of the dynamic dimension relative to just the dynamic dimensions, given its index within the shape.
int64_t getSizeInBits () const
Get the total amount of bits occupied by a value of this type.
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
unsigned getKind () const
Return the classification for this type.
MLIRContext * getContext () const
Return the LLVMContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex ()
bool isBF16 ()
bool isF16 ()
bool isF32 ()
bool isF64 ()
bool isInteger (unsigned width)
Return true if this is an integer type with the specified width.
unsigned getIntOrFloatBitWidth ()
Return the bit width of an integer or a float type, assert failure on other types.
bool isIntOrIndex ()
Return true if this is an integer or index type.
bool isIntOrIndexOrFloat ()
Return true if this is an integer, index, or float type.
bool isIntOrFloat ()
Return true of this is an integer or a float type.
void print (raw_ostream &os)
Print the current type.
void dump ()
unsigned getSubclassData () const
void setSubclassData (unsigned val)
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Static Public Attributes inherited from mlir::ShapedType
static constexpr int64_t kDynamicSize = -1
static constexpr int64_t kDynamicStrideOrOffset
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
Tensor types represent multi-dimensional arrays, and have two variants: RankedTensorType and UnrankedTensorType.
Definition at line 290 of file StandardTypes.h.
Member Function Documentation
classof()
static bool mlir::TensorType::classof (Type type) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 305 of file StandardTypes.h.
References mlir::Type::getKind(), mlir::StandardTypes::RankedTensor, and mlir::StandardTypes::UnrankedTensor.
isValidElementType()
static bool mlir::TensorType::isValidElementType (Type type) inline static
Return true if the specified element type is ok in a tensor.
Definition at line 295 of file StandardTypes.h.
References mlir::Type::getKind(), mlir::Type::isa(), and mlir::Type::isIntOrFloat().
Referenced by checkTensorElementType(), and mlir::OpaqueElementsAttr::get().
The documentation for this class was generated from the following file:
include/mlir/IR/StandardTypes.h