MLIR: mlir::NamedAttributeList Class Reference
mlir::NamedAttributeList Class Reference
A NamedAttributeList is used to manage a list of named attributes.
#include "mlir/IR/Attributes.h"
Public Types
enum RemoveResult { RemoveResult::Removed, RemoveResult::NotFound }
Public Member Functions
NamedAttributeList (DictionaryAttr attrs=nullptr)
NamedAttributeList (ArrayRef< NamedAttribute > attributes)
bool operator!= (const NamedAttributeList &other) const
bool operator== (const NamedAttributeList &other) const
DictionaryAttr getDictionary () const
Return the underlying dictionary attribute.
ArrayRef< NamedAttribute > getAttrs () const
Return all of the attributes on this operation.
void setAttrs (ArrayRef< NamedAttribute > attributes)
Replace the held attributes with ones provided in 'newAttrs'.
Attribute get (StringRef name) const
Return the specified attribute if present, null otherwise.
Attribute get (Identifier name) const
Return the specified attribute if present, null otherwise.
void set (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
RemoveResult remove (Identifier name)
Remove the attribute with the specified name if it exists.
Detailed Description
A NamedAttributeList is used to manage a list of named attributes.
This provides simple interfaces for adding/removing/finding attributes from within a DictionaryAttr.
We assume there will be relatively few attributes on a given operation (maybe a dozen or so, but not hundreds or thousands) so we use linear searches for everything.
Definition at line 1382 of file Attributes.h.
Member Enumeration Documentation
RemoveResult
enum mlir::NamedAttributeList::RemoveResult strong
Enumerator
Removed
NotFound
Definition at line 1413 of file Attributes.h.
Constructor & Destructor Documentation
NamedAttributeList() [1/2]
mlir::NamedAttributeList::NamedAttributeList (DictionaryAttr attrs = nullptr) inline
Definition at line 1384 of file Attributes.h.
NamedAttributeList() [2/2]
NamedAttributeList::NamedAttributeList (ArrayRef< NamedAttribute > attributes)
Definition at line 1061 of file Attributes.cpp.
Member Function Documentation
get() [1/2]
Attribute NamedAttributeList::get (StringRef name) const
Return the specified attribute if present, null otherwise.
Definition at line 1079 of file Attributes.cpp.
Referenced by mlir::Operation::getAttr().
get() [2/2]
Attribute NamedAttributeList::get (Identifier name) const
Return the specified attribute if present, null otherwise.
Definition at line 1084 of file Attributes.cpp.
getAttrs()
ArrayRef< NamedAttribute > NamedAttributeList::getAttrs () const
Return all of the attributes on this operation.
Definition at line 1065 of file Attributes.cpp.
References mlir::StandardTypes::None.
Referenced by mlir::Operation::getAttrs(), and mlir::ModuleOp::verify().
getDictionary()
DictionaryAttr mlir::NamedAttributeList::getDictionary () const inline
Return the underlying dictionary attribute.
This may be null, if this list has no attributes.
Definition at line 1397 of file Attributes.h.
Referenced by replaceAllSymbolUsesImpl(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttrs(), mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr(), mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttrs(), and walkSymbolRefs().
operator!=()
bool mlir::NamedAttributeList::operator!= (const NamedAttributeList & other) const inline
Definition at line 1388 of file Attributes.h.
operator==()
bool mlir::NamedAttributeList::operator== (const NamedAttributeList & other) const inline
Definition at line 1391 of file Attributes.h.
remove()
auto NamedAttributeList::remove (Identifier name)
Remove the attribute with the specified name if it exists.
The return value indicates whether the attribute was present or not.
Definition at line 1110 of file Attributes.cpp.
References mlir::DictionaryAttr::get().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::removeArgAttr(), mlir::Operation::removeAttr(), and mlir::OpTrait::FunctionLike< ConcreteType >::removeResultAttr().
set()
void NamedAttributeList::set (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
Otherwise, add a new attribute with the specified name/value.
Definition at line 1090 of file Attributes.cpp.
References mlir::DictionaryAttr::get(), and mlir::Attribute::getContext().
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::setArgAttr(), mlir::Operation::setAttr(), and mlir::OpTrait::FunctionLike< ConcreteType >::setResultAttr().
setAttrs()
void NamedAttributeList::setAttrs (ArrayRef< NamedAttribute > attributes)
Replace the held attributes with ones provided in 'newAttrs'.
Definition at line 1070 of file Attributes.cpp.
References mlir::DictionaryAttr::get().
The documentation for this class was generated from the following files:
include/mlir/IR/Attributes.h
lib/IR/Attributes.cpp