MLIR: mlir::OperationFolder Class Reference
mlir::OperationFolder Class Reference
A utility class for folding operations, and unifying duplicated constants generated along the way.
#include "mlir/Transforms/FoldUtils.h"
Public Member Functions
OperationFolder (MLIRContext *ctx)
LogicalResult tryToFold (Operation *op, function_ref< void(Operation *)> processGeneratedConstants=nullptr, function_ref< void(Operation *)> preReplaceAction=nullptr)
Tries to perform folding on the given op, including unifying deduplicated constants.
void notifyRemoval (Operation *op)
Notifies that the given constant op should be remove from this OperationFolder's internal bookkeeping.
template<typename OpTy , typename... Args>
void create (OpBuilder &builder, SmallVectorImpl< Value > &results, Location location, Args &&... args)
Create an operation of specific op type with the given builder, and immediately try to fold it.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::OneResult >), Value >::type create (OpBuilder &builder, Location location, Args &&... args)
Overload to create or fold a single result operation.
template<typename OpTy , typename... Args>
std::enable_if< OpTy::template hasTrait< OpTrait::ZeroResult >), OpTy >::type create (OpBuilder &builder, Location location, Args &&... args)
Overload to create or fold a zero result operation.
Detailed Description
A utility class for folding operations, and unifying duplicated constants generated along the way.
Definition at line 50 of file FoldUtils.h.
Constructor & Destructor Documentation
OperationFolder()
mlir::OperationFolder::OperationFolder (MLIRContext * ctx) inline
Definition at line 52 of file FoldUtils.h.
Member Function Documentation
create() [1/3]
template<typename OpTy , typename... Args> void mlir::OperationFolder::create (OpBuilder & builder, SmallVectorImpl< Value > & results, Location location, Args &&... args) inline
Create an operation of specific op type with the given builder, and immediately try to fold it.
This function populates 'results' with the results after folding the operation.
Definition at line 76 of file FoldUtils.h.
References mlir::OpBuilder::create(), mlir::Operation::erase(), mlir::failed(), mlir::Operation::getNumResults(), mlir::Operation::result_begin(), and mlir::Operation::result_end().
Referenced by mlir::edsc::ValueHandle::create(), and emitOrFoldComposedAffineApply().
create() [2/3]
template<typename OpTy , typename... Args> std::enable_if<OpTy::template hasTrait<OpTrait::OneResult>), Value>::type mlir::OperationFolder::create (OpBuilder & builder, Location location, Args &&... args) inline
Overload to create or fold a single result operation.
Definition at line 89 of file FoldUtils.h.
create() [3/3]
template<typename OpTy , typename... Args> std::enable_if<OpTy::template hasTrait<OpTrait::ZeroResult>), OpTy>::type mlir::OperationFolder::create (OpBuilder & builder, Location location, Args &&... args) inline
Overload to create or fold a zero result operation.
Definition at line 99 of file FoldUtils.h.
References mlir::OpBuilder::create().
notifyRemoval()
void OperationFolder::notifyRemoval (Operation * op)
Notifies that the given constant op should be remove from this OperationFolder's internal bookkeeping.
Note: this method must be called if a constant op is to be deleted externally to this OperationFolder. op must be a constant op.
Definition at line 107 of file FoldUtils.cpp.
References mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Operation::fold(), mlir::Operation::getDialect(), getInsertionRegion(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getOpOperand(), mlir::Operation::getResult(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::Operation::isCommutative(), mlir::m_Constant(), mlir::matchPattern(), materializeConstant(), mlir::success(), and tryToFold().
tryToFold()
LogicalResult OperationFolder::tryToFold (Operation * op, function_ref< void(Operation *)> processGeneratedConstants = nullptr, function_ref< void(Operation *)> preReplaceAction = nullptr)
Tries to perform folding on the given op, including unifying deduplicated constants.
If successful, replaces op's uses with folded results, and returns success. preReplaceAction is invoked on op before it is replaced. 'processGeneratedConstants' is invoked for any new operations generated when folding. If the op was completely folded it is erased.
Definition at line 75 of file FoldUtils.cpp.
References mlir::Operation::erase(), mlir::failed(), mlir::failure(), mlir::Operation::getResult(), mlir::Value::replaceAllUsesWith(), and mlir::success().
Referenced by notifyRemoval().
The documentation for this class was generated from the following files:
include/mlir/Transforms/FoldUtils.h
lib/Transforms/Utils/FoldUtils.cpp