MLIR: mlir::UnrankedMemRefType Class Reference
mlir::UnrankedMemRefType Class Reference
Unranked MemRef type represent multi-dimensional MemRefs that have an unknown rank.
#include "mlir/IR/StandardTypes.h"
Public Member Functions
ArrayRef< int64_t > getShape () const
unsigned getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Static Public Member Functions
static UnrankedMemRefType get (Type elementType, unsigned memorySpace)
Get or create a new UnrankedMemRefType of the provided element type and memory space.
static UnrankedMemRefType getChecked (Type elementType, unsigned memorySpace, Location location)
Get or create a new UnrankedMemRefType of the provided element type and memory space declared at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *context, Type elementType, unsigned memorySpace)
Verify the construction of a unranked memref type.
static bool kindof (unsigned kind)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Unranked MemRef type represent multi-dimensional MemRefs that have an unknown rank.
Definition at line 444 of file StandardTypes.h.
Member Function Documentation
get()
UnrankedMemRefType UnrankedMemRefType::get (Type elementType, unsigned memorySpace) static
Get or create a new UnrankedMemRefType of the provided element type and memory space.
Definition at line 392 of file StandardTypes.cpp.
References mlir::Type::getContext(), and mlir::StandardTypes::UnrankedMemRef.
getChecked()
UnrankedMemRefType UnrankedMemRefType::getChecked (Type elementType, unsigned memorySpace, Location location) static
Get or create a new UnrankedMemRefType of the provided element type and memory space declared at the given, potentially unknown, location.
If the UnrankedMemRefType defined by the arguments would be ill-formed, emit errors and return a nullptr-wrapping type.
Definition at line 398 of file StandardTypes.cpp.
References mlir::Type::getContext(), and mlir::StandardTypes::UnrankedMemRef.
Referenced by parseSymbol().
getMemorySpace()
unsigned UnrankedMemRefType::getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Definition at line 406 of file StandardTypes.cpp.
Referenced by verify().
getShape()
ArrayRef<int64_t> mlir::UnrankedMemRefType::getShape () const inline
Definition at line 467 of file StandardTypes.h.
References mlir::StandardTypes::None.
kindof()
static bool mlir::UnrankedMemRefType::kindof (unsigned kind) inline static
Definition at line 471 of file StandardTypes.h.
References mlir::StandardTypes::UnrankedMemRef.
verifyConstructionInvariants()
LogicalResult UnrankedMemRefType::verifyConstructionInvariants (Optional< Location > loc, MLIRContext * context, Type elementType, unsigned memorySpace) static
Verify the construction of a unranked memref type.
Definition at line 410 of file StandardTypes.cpp.
References mlir::emitOptionalError(), mlir::Type::isa(), mlir::Type::isIntOrFloat(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp