MLIR: mlir::TypeStorage Class Reference
mlir::TypeStorage Class Reference
Base storage class appearing in a Type.
#include "mlir/IR/TypeSupport.h"
Public Member Functions
Dialect & getDialect ()
Get the dialect that this type is registered to.
unsigned getSubclassData () const
Get the subclass data.
void setSubclassData (unsigned val)
Set the subclass data.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Protected Member Functions
TypeStorage (unsigned subclassData=0)
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Base storage class appearing in a Type.
Definition at line 33 of file TypeSupport.h.
Constructor & Destructor Documentation
TypeStorage()
mlir::TypeStorage::TypeStorage (unsigned subclassData = 0) inline protected
This constructor is used by derived classes as part of the TypeUniquer.
When using this constructor, the initializeTypeInfo function must be invoked afterwards for the storage to be valid.
Definition at line 41 of file TypeSupport.h.
Member Function Documentation
getDialect()
Dialect& mlir::TypeStorage::getDialect () inline
Get the dialect that this type is registered to.
Definition at line 46 of file TypeSupport.h.
getSubclassData()
unsigned mlir::TypeStorage::getSubclassData () const inline
Get the subclass data.
Definition at line 51 of file TypeSupport.h.
Referenced by mlir::detail::FunctionTypeStorage::getInputs(), mlir::detail::FunctionTypeStorage::getResults(), mlir::detail::VectorTypeStorage::getShape(), mlir::detail::RankedTensorTypeStorage::getShape(), mlir::detail::MemRefTypeStorage::getShape(), and mlir::detail::TupleTypeStorage::size().
setSubclassData()
void mlir::TypeStorage::setSubclassData (unsigned val) inline
Set the subclass data.
Definition at line 54 of file TypeSupport.h.
The documentation for this class was generated from the following file:
include/mlir/IR/TypeSupport.h