MLIR: mlir::AnalysisManager Class Reference
mlir::AnalysisManager Class Reference
This class represents an analysis manager for a particular operation instance.
#include "mlir/Pass/AnalysisManager.h"
Public Types
using PreservedAnalyses = detail::PreservedAnalyses
Public Member Functions
template<typename AnalysisT >
Optional< std::reference_wrapper< AnalysisT > > getCachedParentAnalysis (Operation *parentOp) const
template<typename AnalysisT >
AnalysisT & getAnalysis ()
template<typename AnalysisT >
Optional< std::reference_wrapper< AnalysisT > > getCachedAnalysis () const
template<typename AnalysisT >
AnalysisT & getChildAnalysis (Operation *op)
Query for a analysis of a child operation, constructing it if necessary.
template<typename AnalysisT >
Optional< std::reference_wrapper< AnalysisT > > getCachedChildAnalysis (Operation *op) const
Query for a cached analysis of a child operation, or return null.
AnalysisManager slice (Operation *op)
Get an analysis manager for the given child operation.
void invalidate (const PreservedAnalyses &pa)
Invalidate any non preserved analyses,.
void clear ()
Clear any held analyses.
PassInstrumentor * getPassInstrumentor () const
Returns a pass instrumentation object for the current operation.
Friends
class ModuleAnalysisManager
Allow access to the constructor.
Detailed Description
This class represents an analysis manager for a particular operation instance.
It is used to manage and cache analyses on the operation as well as those for child operations, via nested AnalysisManager instances accessible via 'slice'. This class is intended to be passed around by value, and cannot be constructed directly.
Definition at line 217 of file AnalysisManager.h.
Member Typedef Documentation
PreservedAnalyses
using mlir::AnalysisManager::PreservedAnalyses = detail::PreservedAnalyses
Definition at line 222 of file AnalysisManager.h.
Member Function Documentation
clear()
void mlir::AnalysisManager::clear () inline
Clear any held analyses.
Definition at line 272 of file AnalysisManager.h.
Referenced by runPipeline().
getAnalysis()
template<typename AnalysisT > AnalysisT& mlir::AnalysisManager::getAnalysis () inline
Definition at line 239 of file AnalysisManager.h.
getCachedAnalysis()
template<typename AnalysisT > Optional<std::reference_wrapper<AnalysisT> > mlir::AnalysisManager::getCachedAnalysis () const inline
Definition at line 245 of file AnalysisManager.h.
getCachedChildAnalysis()
template<typename AnalysisT > Optional<std::reference_wrapper<AnalysisT> > mlir::AnalysisManager::getCachedChildAnalysis (Operation * op) const inline
Query for a cached analysis of a child operation, or return null.
Definition at line 257 of file AnalysisManager.h.
References mlir::Operation::getParentOp(), and mlir::StandardTypes::None.
getCachedParentAnalysis()
template<typename AnalysisT > Optional<std::reference_wrapper<AnalysisT> > mlir::AnalysisManager::getCachedParentAnalysis (Operation * parentOp) const inline
Definition at line 228 of file AnalysisManager.h.
References mlir::StandardTypes::None.
getChildAnalysis()
template<typename AnalysisT > AnalysisT& mlir::AnalysisManager::getChildAnalysis (Operation * op) inline
Query for a analysis of a child operation, constructing it if necessary.
Definition at line 250 of file AnalysisManager.h.
getPassInstrumentor()
PassInstrumentor * AnalysisManager::getPassInstrumentor () const
Returns a pass instrumentation object for the current operation.
This value may be null.
Definition at line 620 of file Pass.cpp.
Referenced by mlir::Pass::printAsTextualPipeline(), mlir::detail::OpToOpPassAdaptor::runOnOperation(), and mlir::detail::OpToOpPassAdaptorParallel::runOnOperation().
invalidate()
void mlir::AnalysisManager::invalidate (const PreservedAnalyses & pa) inline
Invalidate any non preserved analyses,.
Definition at line 269 of file AnalysisManager.h.
Referenced by mlir::Pass::printAsTextualPipeline().
slice()
AnalysisManager AnalysisManager::slice (Operation * op)
Get an analysis manager for the given child operation.
Definition at line 628 of file Pass.cpp.
References mlir::Operation::getParentOp().
Referenced by mlir::detail::OpToOpPassAdaptor::runOnOperation(), and mlir::detail::OpToOpPassAdaptorParallel::runOnOperation().
Friends And Related Function Documentation
ModuleAnalysisManager
friend class ModuleAnalysisManager friend
Allow access to the constructor.
Definition at line 297 of file AnalysisManager.h.
The documentation for this class was generated from the following files:
include/mlir/Pass/AnalysisManager.h
lib/Pass/Pass.cpp