MLIR: mlir::AffineLoadOp Class Reference
mlir::AffineLoadOp Class Reference
The "affine.load" op reads an element from a memref, where the index for each memref dimension is an affine expression of loop induction variables and symbols.
#include "mlir/Dialect/AffineOps/AffineOps.h"
Public Member Functions
unsigned getMemRefOperandIndex ()
Returns the operand index of the memref.
Value getMemRef ()
Get memref operand.
void setMemRef (Value value)
MemRefType getMemRefType ()
operand_range getMapOperands ()
Get affine map operands.
AffineMap getAffineMap ()
Returns the affine map used to index the memref for this operation.
AffineMapAttr getAffineMapAttr ()
NamedAttribute getAffineMapAttrForMemRef (Value memref)
Returns the AffineMapAttr associated with 'memref'.
void print (OpAsmPrinter &p)
LogicalResult verify ()
OpFoldResult fold (ArrayRef< Attribute > operands)
Public Member Functions inherited from mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >
Operation * getOperation ()
Return the operation that this refers to.
AffineLoadOp clone ()
Create a deep copy of this operation.
AffineLoadOp cloneWithoutRegions ()
Create a partial copy of this operation without traversing into attached regions.
Dialect * getDialect ()
Return the dialect that this refers to.
Region * getParentRegion ()
Return the parent Region of this operation.
Op ()
This is a public constructor. Any op can be initialized to null.
Op (std::nullptr_t)
Op (Operation *state)
This is a public constructor to enable access via the llvm::cast family of methods.
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
Public Member Functions inherited from mlir::OpState
operator bool ()
Ops are pointer-like, so we allow implicit conversion to bool.
operator Operation * () const
This implicitly converts to Operation*.
Operation * getOperation ()
Return the operation that this refers to.
Operation * getParentOp ()
Returns the closest surrounding operation that contains this operation or nullptr if this is a top-level operation.
template<typename OpTy >
OpTy getParentOfType ()
Return the closest surrounding parent operation that is of type 'OpTy'.
MLIRContext * getContext ()
Return the context this operation belongs to.
void print (raw_ostream &os, OpPrintingFlags flags=llvm::None)
Print the operation to the given stream.
void print (raw_ostream &os, AsmState &asmState, OpPrintingFlags flags=llvm::None)
void dump ()
Dump this operation.
Location getLoc ()
The source location the operation was defined or derived from.
void setLoc (Location loc)
ArrayRef< NamedAttribute > getAttrs ()
Return all of the attributes on this operation.
dialect_attr_range getDialectAttrs ()
Return a range corresponding to the dialect attributes for this operation.
dialect_attr_iterator dialect_attr_begin ()
dialect_attr_iterator dialect_attr_end ()
Attribute getAttr (StringRef name)
Return an attribute with the specified name.
template<typename AttrClass >
AttrClass getAttrOfType (StringRef name)
If the operation has an attribute of the specified type, return it.
void setAttr (Identifier name, Attribute value)
If the an attribute exists with the specified name, change it to the new value.
void setAttr (StringRef name, Attribute value)
void setAttrs (ArrayRef< NamedAttribute > attributes)
Set the attributes held by this operation.
void setAttrs (NamedAttributeList newAttrs)
template<typename DialectAttrs >
void setDialectAttrs (DialectAttrs &&attrs)
Set the dialect attributes for this operation, and preserve all dependent.
NamedAttributeList::RemoveResult removeAttr (Identifier name)
Remove the attribute with the specified name if it exists.
NamedAttributeList::RemoveResult removeAttr (StringRef name)
bool use_empty ()
Return true if there are no users of any results of this operation.
void erase ()
Remove this operation from its parent block and delete it.
InFlightDiagnostic emitOpError (const Twine &message={})
Emit an error with the op name prefixed, like "'dim' op " which is convenient for verifiers.
InFlightDiagnostic emitError (const Twine &message={})
Emit an error about fatal conditions with this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitWarning (const Twine &message={})
Emit a warning about this operation, reporting up to any diagnostic handlers that may be listening.
InFlightDiagnostic emitRemark (const Twine &message={})
Emit a remark about this operation, reporting up to any diagnostic handlers that may be listening.
template<typename FnT , typename RetT = detail::walkResultType<FnT>>
RetT walk (FnT &&callback)
Walk the operation in postorder, calling the callback for each nested operation(including this one).
Public Member Functions inherited from mlir::OpTrait::OneResult< AffineLoadOp >
Value getResult ()
Type getType ()
void replaceAllUsesWith (Value newValue)
Replace all uses of 'this' value with the new value, updating anything in the IR that uses 'this' to use the other value instead.
void replaceAllUsesWith (Operation *op)
Replace all uses of 'this' value with the result of 'op'.
Public Member Functions inherited from mlir::FoldingHook< AffineLoadOp, llvm::is_one_of< OpTrait::OneResult< AffineLoadOp >, OpTrait::OneResult< AffineLoadOp >... >::value >
LogicalResult fold (ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This hook implements a generalized folder for this operation.
Static Public Member Functions
static void build (Builder *builder, OperationState &result, AffineMap map, ValueRange operands)
Builds an affine load op with the specified map and operands.
static void build (Builder *builder, OperationState &result, Value memref, ValueRange indices={})
Builds an affine load op with an identity map and operands.
static void build (Builder *builder, OperationState &result, Value memref, AffineMap map, ValueRange mapOperands)
Builds an affine load op with the specified map and its operands.
static StringRef getMapAttrName ()
static StringRef getOperationName ()
static ParseResult parse (OpAsmParser &parser, OperationState &result)
static void getCanonicalizationPatterns (OwningRewritePatternList &results, MLIRContext *context)
Static Public Member Functions inherited from mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >
static constexpr bool hasTrait ()
Return if this operation contains the provided trait.
static bool classof (Operation *op)
Return true if this "op class" can match against the specified operation.
static ParseResult parseAssembly (OpAsmParser &parser, OperationState &result)
This is the hook used by the AsmParser to parse the custom form of this op from an .mlir file.
static void printAssembly (Operation *op, OpAsmPrinter &p)
This is the hook used by the AsmPrinter to emit this to the .mlir file.
static LogicalResult verifyInvariants (Operation *op)
This is the hook that checks whether or not this operation is well formed according to the invariants of its opcode.
static AbstractOperation::OperationProperties getOperationProperties ()
static ConcreteOpType getFromOpaquePointer (const void *pointer)
Static Public Member Functions inherited from mlir::OpState
static void getCanonicalizationPatterns (OwningRewritePatternList &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Static Public Member Functions inherited from mlir::OpTrait::OneResult< AffineLoadOp >
static LogicalResult verifyTrait (Operation *op)
Static Public Member Functions inherited from mlir::FoldingHook< AffineLoadOp, llvm::is_one_of< OpTrait::OneResult< AffineLoadOp >, OpTrait::OneResult< AffineLoadOp >... >::value >
static LogicalResult foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This is an implementation detail of the constant folder hook for AbstractOperation.
Additional Inherited Members
Public Types inherited from mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >
using ConcreteOpType = AffineLoadOp
Expose the type we are instantiated on to template machinery that may want to introspect traits on this operation.
Public Types inherited from mlir::OpState
using dialect_attr_iterator = Operation::dialect_attr_iterator
A utility iterator that filters out non-dialect attributes.
using dialect_attr_range = Operation::dialect_attr_range
Protected Member Functions inherited from mlir::OpState
LogicalResult verify ()
If the concrete type didn't implement a custom verifier hook, just fall back to this one which accepts everything.
void print (OpAsmPrinter &p)
OpState (Operation *state)
Mutability management is handled by the OpWrapper/OpConstWrapper classes, so we can cast it away here.
Protected Member Functions inherited from mlir::OpTrait::TraitBase< AffineLoadOp, OneResult >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpState
static ParseResult parse (OpAsmParser &parser, OperationState &result)
Unless overridden, the custom assembly form of an op is always rejected.
Static Protected Member Functions inherited from mlir::OpTrait::TraitBase< AffineLoadOp, OneResult >
static LogicalResult verifyTrait (Operation *op)
Provide default implementations of trait hooks.
static AbstractOperation::OperationProperties getTraitProperties ()
Detailed Description
The "affine.load" op reads an element from a memref, where the index for each memref dimension is an affine expression of loop induction variables and symbols.
The output of 'affine.load' is a new value with the same type as the elements of the memref. An affine expression of loop IVs and symbols must be specified for each dimension of the memref. The keyword 'symbol' can be used to indicate SSA identifiers which are symbolic.
Definition at line 392 of file AffineOps.h.
Member Function Documentation
build() [1/3]
void AffineLoadOp::build (Builder * builder, OperationState & result, AffineMap map, ValueRange operands) static
Builds an affine load op with the specified map and operands.
Definition at line 1742 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::AffineMapAttr::get(), mlir::AffineMap::getNumInputs(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), and mlir::OperationState::types.
build() [2/3]
void AffineLoadOp::build (Builder * builder, OperationState & result, Value memref, ValueRange indices = {}) static
Builds an affine load op with an identity map and operands.
Definition at line 1762 of file AffineOps.cpp.
References mlir::Type::cast(), mlir::Builder::getEmptyAffineMap(), mlir::Builder::getMultiDimIdentityMap(), and mlir::Value::getType().
build() [3/3]
void AffineLoadOp::build (Builder * builder, OperationState & result, Value memref, AffineMap map, ValueRange mapOperands) static
Builds an affine load op with the specified map and its operands.
Definition at line 1752 of file AffineOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::Type::cast(), mlir::AffineMapAttr::get(), mlir::AffineMap::getNumInputs(), mlir::Value::getType(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), and mlir::OperationState::types.
fold()
OpFoldResult AffineLoadOp::fold (ArrayRef< Attribute > operands)
load(memrefcast) -> load
Definition at line 1833 of file AffineOps.cpp.
References foldMemRefCast(), and mlir::succeeded().
getAffineMap()
AffineMap mlir::AffineLoadOp::getAffineMap () inline
Returns the affine map used to index the memref for this operation.
Definition at line 421 of file AffineOps.h.
Referenced by mlir::lowerAffineUpperBound().
getAffineMapAttr()
AffineMapAttr mlir::AffineLoadOp::getAffineMapAttr () inline
Definition at line 422 of file AffineOps.h.
getAffineMapAttrForMemRef()
NamedAttribute mlir::AffineLoadOp::getAffineMapAttrForMemRef (Value memref) inline
Returns the AffineMapAttr associated with 'memref'.
Definition at line 427 of file AffineOps.h.
References mlir::Identifier::get(), and mlir::Dialect::getContext().
getCanonicalizationPatterns()
void AffineLoadOp::getCanonicalizationPatterns (OwningRewritePatternList & results, MLIRContext * context) static
Definition at line 1828 of file AffineOps.cpp.
References mlir::OwningRewritePatternList::insert().
getMapAttrName()
static StringRef mlir::AffineLoadOp::getMapAttrName () inline static
Definition at line 433 of file AffineOps.h.
getMapOperands()
operand_range mlir::AffineLoadOp::getMapOperands () inline
Get affine map operands.
Definition at line 418 of file AffineOps.h.
Referenced by mlir::lowerAffineUpperBound(), and mlir::MemRefAccess::MemRefAccess().
getMemRef()
Value mlir::AffineLoadOp::getMemRef () inline
Get memref operand.
Definition at line 411 of file AffineOps.h.
Referenced by mlir::canonicalizeSetAndOperands(), mlir::createMemRefDataFlowOptPass(), mlir::lowerAffineUpperBound(), and mlir::MemRefAccess::MemRefAccess().
getMemRefOperandIndex()
unsigned mlir::AffineLoadOp::getMemRefOperandIndex () inline
Returns the operand index of the memref.
Definition at line 408 of file AffineOps.h.
getMemRefType()
MemRefType mlir::AffineLoadOp::getMemRefType () inline
Definition at line 413 of file AffineOps.h.
Referenced by mlir::MemRefAccess::MemRefAccess().
getOperationName()
static StringRef mlir::AffineLoadOp::getOperationName () inline static
Definition at line 434 of file AffineOps.h.
References print(), and mlir::verify().
parse()
ParseResult AffineLoadOp::parse (OpAsmParser & parser, OperationState & result) static
Definition at line 1773 of file AffineOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMapOfSSAIds(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
print()
void AffineLoadOp::print (OpAsmPrinter & p)
Definition at line 1792 of file AffineOps.cpp.
References mlir::OpAsmPrinter::printAffineMapOfSSAIds(), and mlir::OpAsmPrinter::printOptionalAttrDict().
setMemRef()
void mlir::AffineLoadOp::setMemRef (Value value) inline
Definition at line 412 of file AffineOps.h.
verify()
LogicalResult AffineLoadOp::verify ()
Definition at line 1801 of file AffineOps.cpp.
References getElementType(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), isValidAffineIndexOperand(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/AffineOps/AffineOps.h
lib/Dialect/AffineOps/AffineOps.cpp