MLIR: mlir::IROperand< DerivedT, IRValueTy > Class Template Reference
mlir::IROperand< DerivedT, IRValueTy > Class Template Reference
A reference to a value, suitable for use as an operand of an operation.
#include "mlir/IR/UseDefLists.h"
Public Types
using ValueType = IRValueTy
Public Member Functions
IROperand (Operation *owner)
IROperand (Operation *owner, ValueType value)
ValueType get () const
Return the current value being used by this operand.
void set (ValueType newValue)
Set the current value being used by this operand.
Operation * getOwner ()
Return the owner of this operand.
Operation * getOwner () const
void drop ()
Remove this use of the operand.
~IROperand ()
DerivedT * getNextOperandUsingThisValue ()
Return the next operand on the use-list of the value we are referring to.
IROperand (IROperand &&other)
We support a move constructor so IROperand's can be in vectors, but this shouldn't be used by general clients.
IROperand & operator= (IROperand &&other)
Detailed Description
template<typename DerivedT, typename IRValueTy>
class mlir::IROperand< DerivedT, IRValueTy >
A reference to a value, suitable for use as an operand of an operation.
IRValueTy is the root type to use for values this tracks. Derived operand types are expected to provide the following:
static IRObjectWithUseList *getUseList(IRValueTy value);
Provide the use list that is attached to the given value.
Definition at line 191 of file UseDefLists.h.
Member Typedef Documentation
ValueType
template<typename DerivedT, typename IRValueTy> using mlir::IROperand< DerivedT, IRValueTy >::ValueType = IRValueTy
Definition at line 193 of file UseDefLists.h.
Constructor & Destructor Documentation
IROperand() [1/3]
template<typename DerivedT, typename IRValueTy> mlir::IROperand< DerivedT, IRValueTy >::IROperand (Operation * owner) inline
Definition at line 195 of file UseDefLists.h.
IROperand() [2/3]
template<typename DerivedT, typename IRValueTy> mlir::IROperand< DerivedT, IRValueTy >::IROperand (Operation * owner, ValueType value) inline
Definition at line 196 of file UseDefLists.h.
~IROperand()
template<typename DerivedT, typename IRValueTy> mlir::IROperand< DerivedT, IRValueTy >::~IROperand () inline
Definition at line 224 of file UseDefLists.h.
IROperand() [3/3]
template<typename DerivedT, typename IRValueTy> mlir::IROperand< DerivedT, IRValueTy >::IROperand (IROperand< DerivedT, IRValueTy > && other) inline
We support a move constructor so IROperand's can be in vectors, but this shouldn't be used by general clients.
Definition at line 233 of file UseDefLists.h.
Member Function Documentation
drop()
template<typename DerivedT, typename IRValueTy> void mlir::IROperand< DerivedT, IRValueTy >::drop () inline
Remove this use of the operand.
Definition at line 217 of file UseDefLists.h.
get()
template<typename DerivedT, typename IRValueTy> ValueType mlir::IROperand< DerivedT, IRValueTy >::get () const inline
Return the current value being used by this operand.
Definition at line 201 of file UseDefLists.h.
Referenced by mlir::OpOperand::get().
getNextOperandUsingThisValue()
template<typename DerivedT, typename IRValueTy> DerivedT* mlir::IROperand< DerivedT, IRValueTy >::getNextOperandUsingThisValue () inline
Return the next operand on the use-list of the value we are referring to.
This should generally only be used by the internal implementation details of the SSA machinery.
Definition at line 229 of file UseDefLists.h.
getOwner() [1/2]
template<typename DerivedT, typename IRValueTy> Operation* mlir::IROperand< DerivedT, IRValueTy >::getOwner () inline
Return the owner of this operand.
Definition at line 213 of file UseDefLists.h.
Referenced by isUseSpeciallyKnownDead(), and mlir::Block::splitBlock().
getOwner() [2/2]
template<typename DerivedT, typename IRValueTy> Operation* mlir::IROperand< DerivedT, IRValueTy >::getOwner () const inline
Definition at line 214 of file UseDefLists.h.
operator=()
template<typename DerivedT, typename IRValueTy> IROperand& mlir::IROperand< DerivedT, IRValueTy >::operator= (IROperand< DerivedT, IRValueTy > && other) inline
Definition at line 236 of file UseDefLists.h.
set()
template<typename DerivedT, typename IRValueTy> void mlir::IROperand< DerivedT, IRValueTy >::set (ValueType newValue) inline
Set the current value being used by this operand.
Definition at line 204 of file UseDefLists.h.
Referenced by mlir::OpOperand::set().
The documentation for this class was generated from the following file:
include/mlir/IR/UseDefLists.h