MLIR: mlir::quantizer::BasePropagatedFact< BinaryReducer > Class Template Reference
mlir::quantizer::BasePropagatedFact< BinaryReducer > Class Template Reference
A fact that can converge through forward propagation alone without the need to track ownership or individual assertions.
#include "mlir/Quantizer/Support/Rules.h"
Public Types
using ValueTy = typename BinaryReducer::ValueTy
using ThisTy = BasePropagatedFact< BinaryReducer >
Public Member Functions
BasePropagatedFact ()
int getSalience () const
bool hasValue () const
ValueTy getValue () const
ModificationResult assertValue (int assertSalience, ValueTy assertValue)
ModificationResult mergeFrom (const ThisTy &other)
Detailed Description
template<typename BinaryReducer>
class mlir::quantizer::BasePropagatedFact< BinaryReducer >
A fact that can converge through forward propagation alone without the need to track ownership or individual assertions.
In practice, this works for static assertions that are either minimized or maximized and do not vary dynamically.
It is expected that ValueTy is appropriate to pass by value and has an operator==. The BinaryReducer type should have two static methods: using ValueTy : Type of the value. ValueTy initialValue() : Returns the initial value of the fact. ValueTy reduce(ValueTy lhs, ValueTy rhs) : Reduces two values.
Definition at line 67 of file Rules.h.
Member Typedef Documentation
ThisTy
template<typename BinaryReducer> using mlir::quantizer::BasePropagatedFact< BinaryReducer >::ThisTy = BasePropagatedFact<BinaryReducer>
Definition at line 70 of file Rules.h.
ValueTy
template<typename BinaryReducer> using mlir::quantizer::BasePropagatedFact< BinaryReducer >::ValueTy = typename BinaryReducer::ValueTy
Definition at line 69 of file Rules.h.
Constructor & Destructor Documentation
BasePropagatedFact()
template<typename BinaryReducer> mlir::quantizer::BasePropagatedFact< BinaryReducer >::BasePropagatedFact () inline
Definition at line 71 of file Rules.h.
Member Function Documentation
assertValue()
template<typename BinaryReducer> ModificationResult mlir::quantizer::BasePropagatedFact< BinaryReducer >::assertValue (int assertSalience, ValueTy assertValue) inline
Definition at line 78 of file Rules.h.
Referenced by mlir::quantizer::UniformConstraintsBuilder::applyStats(), mlir::quantizer::UniformConstraintsBuilder::clamp(), and solveUniformType().
getSalience()
template<typename BinaryReducer> int mlir::quantizer::BasePropagatedFact< BinaryReducer >::getSalience () const inline
Definition at line 75 of file Rules.h.
Referenced by mlir::quantizer::BasePropagatedFact< ExpandingMinMaxReducer >::mergeFrom().
getValue()
template<typename BinaryReducer> ValueTy mlir::quantizer::BasePropagatedFact< BinaryReducer >::getValue () const inline
Definition at line 77 of file Rules.h.
Referenced by mlir::quantizer::BasePropagatedFact< ExpandingMinMaxReducer >::mergeFrom(), and mlir::quantizer::CAGUniformMetadata::printSummary().
hasValue()
template<typename BinaryReducer> bool mlir::quantizer::BasePropagatedFact< BinaryReducer >::hasValue () const inline
Definition at line 76 of file Rules.h.
Referenced by mlir::quantizer::BasePropagatedFact< ExpandingMinMaxReducer >::mergeFrom(), mlir::quantizer::CAGUniformMetadata::printSummary(), and solveUniformType().
mergeFrom()
template<typename BinaryReducer> ModificationResult mlir::quantizer::BasePropagatedFact< BinaryReducer >::mergeFrom (const ThisTy & other) inline
Definition at line 94 of file Rules.h.
The documentation for this class was generated from the following file:
include/mlir/Quantizer/Support/Rules.h