MLIR: mlir::AbstractOperation Class Reference
mlir::AbstractOperation Class Reference
This is a "type erased" representation of a registered operation.
#include "mlir/IR/OperationSupport.h"
Public Types
using OperationProperties = uint32_t
Public Member Functions
bool hasProperty (OperationProperty property) const
Returns whether the operation has a particular property.
template<typename T >
T::Concept * getInterface () const
Returns an instance of the concept object for the given interface if it was registered to this operation, null otherwise.
template<template< typename T > class Trait>
bool hasTrait () const
Returns if the operation has a particular trait.
Static Public Member Functions
static const AbstractOperation * lookup (StringRef opName, MLIRContext *context)
Look up the specified operation in the specified MLIRContext and return a pointer to it if present.
template<typename T >
static AbstractOperation get (Dialect &dialect)
This constructor is used by Dialect objects when they register the list of operations they contain.
Public Attributes
const StringRef name
This is the name of the operation.
Dialect & dialect
This is the dialect that this operation belongs to.
ClassID * classID
The unique identifier of the derived Op class.
ParseResult(&) parseAssembly (OpAsmParser &parser, OperationState &result)
Use the specified object to parse this ops custom assembly format.
void(&) printAssembly (Operation *op, OpAsmPrinter &p)
This hook implements the AsmPrinter for this operation.
LogicalResult(&) verifyInvariants (Operation *op)
This hook implements the verifier for this operation.
LogicalResult(&) foldHook (Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This hook implements a generalized folder for this operation.
void(&) getCanonicalizationPatterns (OwningRewritePatternList &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Detailed Description
This is a "type erased" representation of a registered operation.
This should only be used by things like the AsmPrinter and other things that need to be parameterized by generic operation hooks. Most user code should use the concrete operation types.
Definition at line 83 of file OperationSupport.h.
Member Typedef Documentation
OperationProperties
using mlir::AbstractOperation::OperationProperties = uint32_t
Definition at line 85 of file OperationSupport.h.
Member Function Documentation
get()
template<typename T > static AbstractOperation mlir::AbstractOperation::get (Dialect & dialect) inline static
This constructor is used by Dialect objects when they register the list of operations they contain.
Definition at line 159 of file OperationSupport.h.
getInterface()
template<typename T > T::Concept* mlir::AbstractOperation::getInterface () const inline
Returns an instance of the concept object for the given interface if it was registered to this operation, null otherwise.
This should not be used directly.
Definition at line 142 of file OperationSupport.h.
Referenced by mlir::OpInterface< ConcreteType, Traits >::getImpl().
hasProperty()
bool mlir::AbstractOperation::hasProperty (OperationProperty property) const inline
Returns whether the operation has a particular property.
Definition at line 135 of file OperationSupport.h.
Referenced by mlir::detail::OpPassManagerImpl::coalesceAdjacentAdaptorPasses().
hasTrait()
template<template< typename T > class Trait> bool mlir::AbstractOperation::hasTrait () const inline
Returns if the operation has a particular trait.
Definition at line 148 of file OperationSupport.h.
lookup()
const AbstractOperation * AbstractOperation::lookup (StringRef opName, MLIRContext * context) static
Look up the specified operation in the specified MLIRContext and return a pointer to it if present.
Look up the specified operation in the operation set and return a pointer to it if present.
Otherwise, return a null pointer.
Definition at line 409 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl().
Referenced by mlir::OperationName::OperationName().
Member Data Documentation
classID
ClassID* mlir::AbstractOperation::classID
The unique identifier of the derived Op class.
Definition at line 94 of file OperationSupport.h.
dialect
Dialect& mlir::AbstractOperation::dialect
This is the dialect that this operation belongs to.
Definition at line 91 of file OperationSupport.h.
Referenced by mlir::Dialect::addOperation().
foldHook
LogicalResult(&) mlir::AbstractOperation::foldHook(Operation *op, ArrayRef< Attribute > operands, SmallVectorImpl< OpFoldResult > &results)
This hook implements a generalized folder for this operation.
Operations can implement this to provide simplifications rules that are applied by the Builder::createOrFold API and the canonicalization pass.
This is an intentionally limited interface - implementations of this hook can only perform the following changes to the operation:
They can leave the operation alone and without changing the IR, and return failure.
They can mutate the operation in place, without changing anything else in the IR. In this case, return success.
They can return a list of existing values that can be used instead of the operation. In this case, fill in the results list and return success. The caller will remove the operation and use those results instead.
This allows expression of some simple in-place canonicalizations (e.g. "x+0 -> x", "min(x,y,x,z) -> min(x,y,z)", "x+y-x -> y", etc), as well as generalized constant folding.
Definition at line 126 of file OperationSupport.h.
getCanonicalizationPatterns
void(&) mlir::AbstractOperation::getCanonicalizationPatterns(OwningRewritePatternList &results, MLIRContext *context)
This hook returns any canonicalization pattern rewrites that the operation supports, for use by the canonicalization pass.
Definition at line 131 of file OperationSupport.h.
name
const StringRef mlir::AbstractOperation::name
This is the name of the operation.
Definition at line 88 of file OperationSupport.h.
Referenced by mlir::Dialect::addOperation().
parseAssembly
ParseResult(&) mlir::AbstractOperation::parseAssembly(OpAsmParser &parser, OperationState &result)
Use the specified object to parse this ops custom assembly format.
Definition at line 97 of file OperationSupport.h.
printAssembly
void(&) mlir::AbstractOperation::printAssembly(Operation *op, OpAsmPrinter &p)
This hook implements the AsmPrinter for this operation.
Definition at line 100 of file OperationSupport.h.
verifyInvariants
LogicalResult(&) mlir::AbstractOperation::verifyInvariants(Operation *op)
This hook implements the verifier for this operation.
It should emits an error message and returns failure if a problem is detected, or returns success if everything is ok.
Definition at line 105 of file OperationSupport.h.
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/MLIRContext.cpp