MLIR: mlir::edsc::ValueHandle Class Reference
mlir::edsc::ValueHandle Class Reference
ValueHandle implements a (potentially "delayed") typed Value abstraction.
#include "mlir/EDSC/Builders.h"
Public Member Functions
ValueHandle (Type t)
A ValueHandle that is constructed from a Type represents a typed "delayed" Value.
ValueHandle (Value v)
A ValueHandle that is constructed from an mlir::Value is an "eager" Value.
ValueHandle (index_type cst)
Builds a ConstantIndexOp of value cst.
ValueHandle (const ValueHandle &other)=default
ValueHandle is a value type, use the default copy constructor.
ValueHandle & operator= (const ValueHandle &other)
ValueHandle is a value type, the assignment operator typechecks before assigning.
void swap (ValueHandle &other)
Provide a swap operator.
operator Value () const
Implicit conversion useful for automatic conversion to Container<Value>.
operator Type () const
operator bool () const
bool hasValue () const
Value getValue () const
bool hasType () const
Type getType () const
Operation * getOperation () const
Static Public Member Functions
static ValueHandle null ()
A ValueHandle in a null state can never be captured;.
template<typename Op , typename... Args>
static ValueHandle create (Args... args)
Generic mlir::Op create.
template<typename Op , typename... Args>
static ValueHandle create (OperationFolder *folder, Args... args)
Generic mlir::Op create.
static ValueHandle createComposedAffineApply (AffineMap map, ArrayRef< Value > operands)
Special case to build composed AffineApply operations.
static ValueHandle create (StringRef name, ArrayRef< ValueHandle > operands, ArrayRef< Type > resultTypes, ArrayRef< NamedAttribute > attributes={})
Generic create for a named operation producing a single value.
Protected Member Functions
ValueHandle ()
Protected Member Functions inherited from mlir::edsc::CapturableHandle
CapturableHandle ()=default
Protected Attributes
Type t
Value v
Detailed Description
ValueHandle implements a (potentially "delayed") typed Value abstraction.
ValueHandle should be captured by pointer but otherwise passed by Value everywhere. A ValueHandle can have 3 states:
null state (empty type and empty value), in which case it does not hold a value and must never hold a Value (now or in the future). This is used for MLIR operations with zero returns as well as the result of calling a NestedBuilder::operator(). In both cases the objective is to have an object that can be inserted in an ArrayRef<ValueHandle> to implement nesting;
delayed state (empty value), in which case it represents an eagerly typed "delayed" value that can be hold a Value in the future;
constructed state,in which case it holds a Value.
A ValueHandle is meant to capture a single Value and should be used for operations that have a single result. For convenience of use, we also include AffineForOp in this category although it does not return a value. In the case of AffineForOp, the captured Value is the loop induction variable.
Definition at line 300 of file Builders.h.
Constructor & Destructor Documentation
ValueHandle() [1/5]
mlir::edsc::ValueHandle::ValueHandle (Type t) inline explicit
A ValueHandle that is constructed from a Type represents a typed "delayed" Value.
A delayed Value can only capture Values of the specified type. Such a delayed value represents the declaration (in the PL sense) of a placeholder for an mlir::Value that will be constructed and captured at some later point in the program.
Definition at line 310 of file Builders.h.
ValueHandle() [2/5]
mlir::edsc::ValueHandle::ValueHandle (Value v) inline explicit
A ValueHandle that is constructed from an mlir::Value is an "eager" Value.
An eager Value represents both the declaration and the definition (in the PL sense) of a placeholder for an mlir::Value that has already been constructed in the past and that is captured "now" in the program.
Definition at line 316 of file Builders.h.
ValueHandle() [3/5]
mlir::edsc::ValueHandle::ValueHandle (index_type cst)
Builds a ConstantIndexOp of value cst.
The constant is created at the current insertion point. This implicit constructor is provided to each build an eager Value for a constant at the current insertion point in the IR. An implicit constructor allows idiomatic expressions mixing ValueHandle and literals.
Definition at line 68 of file Builders.cpp.
References mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getLocation(), and mlir::edsc::index_type::v.
ValueHandle() [4/5]
mlir::edsc::ValueHandle::ValueHandle (const ValueHandle & other) default
ValueHandle is a value type, use the default copy constructor.
ValueHandle() [5/5]
mlir::edsc::ValueHandle::ValueHandle () inline protected
Definition at line 383 of file Builders.h.
Member Function Documentation
create() [1/3]
template<typename Op , typename... Args> ValueHandle mlir::edsc::ValueHandle::create (Args... args) static
Generic mlir::Op create.
This is the key to being extensible to the whole of MLIR without duplicating the type system or the op definitions.
Definition at line 492 of file Builders.h.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getLocation(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), and mlir::matcher::Op().
create() [2/3]
template<typename Op , typename... Args> ValueHandle mlir::edsc::ValueHandle::create (OperationFolder * folder, Args... args) static
Generic mlir::Op create.
This is the key to being extensible to the whole of MLIR without duplicating the type system or the op definitions. When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 507 of file Builders.h.
References mlir::OperationFolder::create(), mlir::edsc::ScopedContext::getBuilder(), and mlir::edsc::ScopedContext::getLocation().
create() [3/3]
ValueHandle ValueHandle::create (StringRef name, ArrayRef< ValueHandle > operands, ArrayRef< Type > resultTypes, ArrayRef< NamedAttribute > attributes = {}) static
Generic create for a named operation producing a single value.
Definition at line 93 of file Builders.cpp.
References mlir::edsc::OperationHandle::create(), mlir::Operation::getNumResults(), and mlir::Operation::getResult().
createComposedAffineApply()
ValueHandle mlir::edsc::ValueHandle::createComposedAffineApply (AffineMap map, ArrayRef< Value > operands) static
Special case to build composed AffineApply operations.
Definition at line 83 of file Builders.cpp.
References mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getLocation(), mlir::Operation::getNumResults(), mlir::Op< ConcreteType, Traits >::getOperation(), mlir::Operation::getResult(), and mlir::makeComposedAffineApply().
Referenced by createBinaryIndexHandle().
getOperation()
Operation* mlir::edsc::ValueHandle::getOperation () const inline
Definition at line 376 of file Builders.h.
References mlir::edsc::index_type::v.
getType()
Type mlir::edsc::ValueHandle::getType () const inline
Definition at line 374 of file Builders.h.
Referenced by createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::IndexHandle::IndexHandle(), mlir::edsc::ops::linalg_pointwise(), mlir::edsc::LoopRangeBuilder::LoopRangeBuilder(), mlir::edsc::op::operator!(), mlir::edsc::op::operator!=(), mlir::edsc::op::operator<(), mlir::edsc::op::operator<=(), mlir::edsc::IndexHandle::operator=(), mlir::edsc::op::operator==(), mlir::edsc::op::operator>(), and mlir::edsc::op::operator>=().
getValue()
Value mlir::edsc::ValueHandle::getValue () const inline
Definition at line 369 of file Builders.h.
References mlir::edsc::index_type::v.
Referenced by categorizeValueByAffineType(), clip(), createBinaryHandle(), createBinaryIndexHandle(), createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::LoopRangeBuilder::LoopRangeBuilder(), mlir::edsc::LoopBuilder::makeAffine(), and mlir::edsc::IndexHandle::operator=().
hasType()
bool mlir::edsc::ValueHandle::hasType () const inline
Definition at line 373 of file Builders.h.
References mlir::StandardAttributes::Type.
hasValue()
bool mlir::edsc::ValueHandle::hasValue () const inline
Definition at line 368 of file Builders.h.
References mlir::edsc::index_type::v.
null()
static ValueHandle mlir::edsc::ValueHandle::null () inline static
A ValueHandle in a null state can never be captured;.
Definition at line 303 of file Builders.h.
Referenced by mlir::edsc::LoopNestRangeBuilder::LoopNestRangeBuilder(), and mlir::edsc::LoopRangeBuilder::operator()().
operator bool()
mlir::edsc::ValueHandle::operator bool () const inline
Definition at line 343 of file Builders.h.
References mlir::functional::map(), and mlir::matcher::Op().
operator Type()
mlir::edsc::ValueHandle::operator Type () const inline
Definition at line 342 of file Builders.h.
operator Value()
mlir::edsc::ValueHandle::operator Value () const inline
Implicit conversion useful for automatic conversion to Container<Value>.
Definition at line 341 of file Builders.h.
operator=()
ValueHandle & mlir::edsc::ValueHandle::operator= (const ValueHandle & other)
ValueHandle is a value type, the assignment operator typechecks before assigning.
Definition at line 75 of file Builders.cpp.
References t, and v.
swap()
void mlir::edsc::ValueHandle::swap (ValueHandle & other) inline
Provide a swap operator.
Definition at line 333 of file Builders.h.
References t, mlir::edsc::index_type::v, and v.
Member Data Documentation
t
Type mlir::edsc::ValueHandle::t protected
Definition at line 385 of file Builders.h.
Referenced by mlir::edsc::IndexHandle::operator=(), operator=(), and swap().
v
Value mlir::edsc::ValueHandle::v protected
Definition at line 386 of file Builders.h.
Referenced by operator=(), and swap().
The documentation for this class was generated from the following files:
include/mlir/EDSC/Builders.h
lib/EDSC/Builders.cpp