MLIR: mlir::OwningModuleRef Class Reference
mlir::OwningModuleRef Class Reference
This class acts as an owning reference to a module, and will automatically destroy the held module if valid.
#include "mlir/IR/Module.h"
Public Member Functions
OwningModuleRef (std::nullptr_t=nullptr)
OwningModuleRef (ModuleOp module)
OwningModuleRef (OwningModuleRef &&other)
~OwningModuleRef ()
OwningModuleRef & operator= (OwningModuleRef &&other)
ModuleOp get () const
Allow accessing the internal module.
ModuleOp operator* () const
ModuleOp * operator-> ()
operator bool () const
ModuleOp release ()
Release the referenced module.
Detailed Description
This class acts as an owning reference to a module, and will automatically destroy the held module if valid.
Definition at line 116 of file Module.h.
Constructor & Destructor Documentation
OwningModuleRef() [1/3]
mlir::OwningModuleRef::OwningModuleRef (std::nullptr_t = nullptr) inline
Definition at line 118 of file Module.h.
OwningModuleRef() [2/3]
mlir::OwningModuleRef::OwningModuleRef (ModuleOp module) inline
Definition at line 119 of file Module.h.
OwningModuleRef() [3/3]
mlir::OwningModuleRef::OwningModuleRef (OwningModuleRef && other) inline
Definition at line 120 of file Module.h.
~OwningModuleRef()
mlir::OwningModuleRef::~OwningModuleRef () inline
Definition at line 121 of file Module.h.
Member Function Documentation
get()
ModuleOp mlir::OwningModuleRef::get () const inline
Allow accessing the internal module.
Definition at line 135 of file Module.h.
Referenced by mlir::translateLLVMIRToModule().
operator bool()
mlir::OwningModuleRef::operator bool () const inline explicit
Definition at line 138 of file Module.h.
operator*()
ModuleOp mlir::OwningModuleRef::operator* (void) const inline
Definition at line 136 of file Module.h.
operator->()
ModuleOp* mlir::OwningModuleRef::operator-> () inline
Definition at line 137 of file Module.h.
operator=()
OwningModuleRef& mlir::OwningModuleRef::operator= (OwningModuleRef && other) inline
Definition at line 127 of file Module.h.
References release().
release()
ModuleOp mlir::OwningModuleRef::release () inline
Release the referenced module.
Definition at line 141 of file Module.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
include/mlir/IR/Module.h