MLIR: mlir::IntInfty Class Reference
mlir::IntInfty Class Reference
A utility class for SDBM to represent an integer with potentially infinite positive value.
#include "mlir/Dialect/SDBM/SDBM.h"
Public Member Functions
IntInfty (int64_t v)
IntInfty & operator= (int64_t v)
int64_t getValue () const
operator int64_t () const
bool isFinite ()
Static Public Member Functions
static IntInfty infinity ()
Static Public Attributes
static constexpr int64_t infty = std::numeric_limits<int64_t>::max()
Detailed Description
A utility class for SDBM to represent an integer with potentially infinite positive value.
This uses the largest value of int64_t to represent infinity and redefines the arithmetic operators so that the infinity "saturates": inf + x = inf, inf - x = inf. If a sum of two finite values reaches the largest value of int64_t, the behavior of IntInfty is undefined (in practice, it asserts), similarly to regular signed integer overflow.
Definition at line 35 of file SDBM.h.
Constructor & Destructor Documentation
IntInfty()
mlir::IntInfty::IntInfty (int64_t v) inline
Definition at line 39 of file SDBM.h.
Referenced by infinity().
Member Function Documentation
getValue()
int64_t mlir::IntInfty::getValue () const inline
Definition at line 48 of file SDBM.h.
Referenced by mlir::operator+(), mlir::operator<(), mlir::operator<=(), mlir::operator==(), and mlir::SDBM::print().
infinity()
static IntInfty mlir::IntInfty::infinity () inline static
Definition at line 46 of file SDBM.h.
References IntInfty().
Referenced by mlir::SDBM::get().
isFinite()
bool mlir::IntInfty::isFinite () inline
Definition at line 51 of file SDBM.h.
References infty.
Referenced by mlir::operator+(), and mlir::SDBM::print().
operator int64_t()
mlir::IntInfty::operator int64_t () const inline explicit
Definition at line 49 of file SDBM.h.
operator=()
IntInfty& mlir::IntInfty::operator= (int64_t v) inline
Definition at line 41 of file SDBM.h.
Member Data Documentation
infty
constexpr int64_t mlir::IntInfty::infty = std::numeric_limits<int64_t>::max() static
Definition at line 37 of file SDBM.h.
Referenced by isFinite(), and mlir::operator+().
The documentation for this class was generated from the following file:
include/mlir/Dialect/SDBM/SDBM.h