MLIR: mlir::ConversionPattern Class Reference
mlir::ConversionPattern Class Reference
Base class for the conversion patterns that require type changes.
#include "mlir/Transforms/DialectConversion.h"
Public Member Functions
ConversionPattern (StringRef rootName, PatternBenefit benefit, MLIRContext *ctx)
Construct an ConversionPattern.
virtual void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement rewriting.
virtual void rewrite (Operation *op, ArrayRef< Value > properOperands, ArrayRef< Block *> destinations, ArrayRef< ArrayRef< Value >> operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement rewriting.
virtual PatternMatchResult matchAndRewrite (Operation *op, ArrayRef< Value > properOperands, ArrayRef< Block *> destinations, ArrayRef< ArrayRef< Value >> operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
virtual PatternMatchResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
PatternMatchResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
Public Member Functions inherited from mlir::RewritePattern
virtual void rewrite (Operation *op, std::unique_ptr< PatternState > state, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified rewriter.
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
PatternMatchResult match (Operation *op) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Public Member Functions inherited from mlir::Pattern
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
OperationName getRootKind () const
Return the root node that this pattern matches.
virtual ~Pattern ()
PatternMatchResult matchSuccess (std::unique_ptr< PatternState > state={}) const
This method indicates that a match was found and has the specified cost.
Additional Inherited Members
Static Public Member Functions inherited from mlir::Pattern
static PatternMatchResult matchFailure ()
This method indicates that no match was found.
Protected Member Functions inherited from mlir::RewritePattern
RewritePattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
RewritePattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
Protected Attributes inherited from mlir::RewritePattern
SmallVector< OperationName, 2 > generatedOps
A list of the potential operations that may be generated when rewriting an op with this pattern.
Detailed Description
Base class for the conversion patterns that require type changes.
Specific conversions must derive this class and implement least one rewrite method. NOTE: These conversion patterns can only be used with the 'apply*' methods below.
Definition at line 151 of file DialectConversion.h.
Constructor & Destructor Documentation
ConversionPattern()
mlir::ConversionPattern::ConversionPattern (StringRef rootName, PatternBenefit benefit, MLIRContext * ctx) inline
Construct an ConversionPattern.
rootName must correspond to the canonical name of the first operation matched by the pattern.
Definition at line 155 of file DialectConversion.h.
Member Function Documentation
matchAndRewrite() [1/3]
virtual PatternMatchResult mlir::ConversionPattern::matchAndRewrite (Operation * op, ArrayRef< Value > properOperands, ArrayRef< Block *> destinations, ArrayRef< ArrayRef< Value >> operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement combined matching and rewriting.
Reimplemented in mlir::OpConversionPattern< SourceOp >.
Definition at line 190 of file DialectConversion.h.
Referenced by mlir::OpConversionPattern< SourceOp >::matchAndRewrite().
matchAndRewrite() [2/3]
virtual PatternMatchResult mlir::ConversionPattern::matchAndRewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement combined matching and rewriting.
Reimplemented in mlir::OpConversionPattern< SourceOp >, mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >, and mlir::OpToFuncCallLowering< SourceOp >.
Definition at line 202 of file DialectConversion.h.
References mlir::RewritePattern::rewrite().
matchAndRewrite() [3/3]
PatternMatchResult ConversionPattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const final virtual
Attempt to match and rewrite the IR root at the specified operation.
Reimplemented from mlir::RewritePattern.
Definition at line 966 of file DialectConversion.cpp.
References mlir::failed(), mlir::failure(), mlir::detail::ConversionPatternRewriterImpl::getCurrentState(), mlir::RewritePattern::getGeneratedOps(), mlir::ConversionPatternRewriter::getImpl(), mlir::Operation::getName(), mlir::Operation::getNumSuccessorOperands(), mlir::Operation::getNumSuccessors(), mlir::ConversionTarget::getOpAction(), mlir::Operation::getOperands(), mlir::Pattern::getRootKind(), mlir::Operation::getSuccessor(), mlir::Operation::getSuccessorOperandIndex(), mlir::ConversionPatternRewriter::insert(), mlir::interleaveComma(), mlir::detail::ConversionPatternRewriterImpl::isOpIgnored(), mlir::detail::ConversionPatternRewriterImpl::markNestedOpsIgnored(), mlir::RewritePattern::matchAndRewrite(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), mlir::ConversionPatternRewriter::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::succeeded(), mlir::success(), and mlir::OpBuilder::tryFold().
rewrite() [1/2]
virtual void mlir::ConversionPattern::rewrite (Operation * op, ArrayRef< Value > operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement rewriting.
op is the (first) operation matched by the pattern, operands is a list of rewritten values that are passed to this operation, rewriter can be used to emit the new operations. This function must be reimplemented if the ConversionPattern ever needs to replace an operation that does not have successors. This function should not fail. If some specific cases of the operation are not supported, these cases should not be matched.
Reimplemented in mlir::OpConversionPattern< SourceOp >.
Definition at line 166 of file DialectConversion.h.
rewrite() [2/2]
virtual void mlir::ConversionPattern::rewrite (Operation * op, ArrayRef< Value > properOperands, ArrayRef< Block *> destinations, ArrayRef< ArrayRef< Value >> operands, ConversionPatternRewriter & rewriter) const inline virtual
Hook for derived classes to implement rewriting.
op is the (first) operation matched by the pattern, properOperands is a list of rewritten values that are passed to the operation itself, destinations is a list of (potentially rewritten) successor blocks, operands is a list of lists of rewritten values passed to each of the successors, co-indexed with destinations, rewriter can be used to emit the new operations. It must be reimplemented if the ConversionPattern ever needs to replace a terminator operation that has successors. This function should not fail the pass. If some specific cases of the operation are not supported, these cases should not be matched.
Reimplemented in mlir::OpConversionPattern< SourceOp >.
Definition at line 181 of file DialectConversion.h.
The documentation for this class was generated from the following files:
include/mlir/Transforms/DialectConversion.h
lib/Transforms/DialectConversion.cpp