MLIR: mlir::OpTrait::Symbol< ConcreteType > Class Template Reference
mlir::OpTrait::Symbol< ConcreteType > Class Template Reference
A trait used to define a symbol that can be used on operations within a symbol table.
#include "mlir/IR/SymbolTable.h"
Public Types
using Visibility = mlir::SymbolTable::Visibility
Public Member Functions
StringRef getName ()
Returns the name of this symbol.
void setName (StringRef name)
Set the name of this symbol.
Visibility getVisibility ()
Returns the visibility of the current symbol.
void setVisibility (Visibility vis)
Sets the visibility of the current symbol.
Optional<::mlir::SymbolTable::UseRange > getSymbolUses (Operation *from)
Get all of the uses of the current symbol that are nested within the given operation 'from'.
bool symbolKnownUseEmpty (Operation *from)
Return if the current symbol is known to have no uses that are nested within the given operation 'from'.
LLVM_NODISCARD LogicalResult replaceAllSymbolUses (StringRef newSymbol, Operation *from)
Attempt to replace all uses of the current symbol with the provided symbol 'newSymbol' that are nested within the given operation 'from'.
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, Symbol >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, Symbol >
static LogicalResult verifyTrait (Operation *op)
Provide default implementations of trait hooks.
static AbstractOperation::OperationProperties getTraitProperties ()
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::Symbol< ConcreteType >
A trait used to define a symbol that can be used on operations within a symbol table.
Operations using this trait must adhere to the following:
Have a StringAttr attribute named 'SymbolTable::getSymbolAttrName()'.
Definition at line 236 of file SymbolTable.h.
Member Typedef Documentation
Visibility
template<typename ConcreteType > using mlir::OpTrait::Symbol< ConcreteType >::Visibility = mlir::SymbolTable::Visibility
Definition at line 238 of file SymbolTable.h.
Member Function Documentation
getName()
template<typename ConcreteType > StringRef mlir::OpTrait::Symbol< ConcreteType >::getName () inline
Returns the name of this symbol.
Definition at line 245 of file SymbolTable.h.
References mlir::SymbolTable::getSymbolAttrName().
getSymbolUses()
template<typename ConcreteType > Optional<::mlir::SymbolTable::UseRange> mlir::OpTrait::Symbol< ConcreteType >::getSymbolUses (Operation * from) inline
Get all of the uses of the current symbol that are nested within the given operation 'from'.
Note: See mlir::SymbolTable::getSymbolUses for more details.
Definition at line 272 of file SymbolTable.h.
getVisibility()
template<typename ConcreteType > Visibility mlir::OpTrait::Symbol< ConcreteType >::getVisibility () inline
Returns the visibility of the current symbol.
Definition at line 260 of file SymbolTable.h.
References mlir::SymbolTable::getSymbolVisibility().
replaceAllSymbolUses()
template<typename ConcreteType > LLVM_NODISCARD LogicalResult mlir::OpTrait::Symbol< ConcreteType >::replaceAllSymbolUses (StringRef newSymbol, Operation * from) inline
Attempt to replace all uses of the current symbol with the provided symbol 'newSymbol' that are nested within the given operation 'from'.
Note: See mlir::SymbolTable::replaceAllSymbolUses for more details.
Definition at line 286 of file SymbolTable.h.
setName()
template<typename ConcreteType > void mlir::OpTrait::Symbol< ConcreteType >::setName (StringRef name) inline
Set the name of this symbol.
Definition at line 253 of file SymbolTable.h.
References mlir::StringAttr::get(), and mlir::SymbolTable::getSymbolAttrName().
setVisibility()
template<typename ConcreteType > void mlir::OpTrait::Symbol< ConcreteType >::setVisibility (Visibility vis) inline
Sets the visibility of the current symbol.
Definition at line 265 of file SymbolTable.h.
References mlir::SymbolTable::setSymbolVisibility().
symbolKnownUseEmpty()
template<typename ConcreteType > bool mlir::OpTrait::Symbol< ConcreteType >::symbolKnownUseEmpty (Operation * from) inline
Return if the current symbol is known to have no uses that are nested within the given operation 'from'.
Note: See mlir::SymbolTable::symbolKnownUseEmpty for more details.
Definition at line 279 of file SymbolTable.h.
verifyTrait()
template<typename ConcreteType > static LogicalResult mlir::OpTrait::Symbol< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 240 of file SymbolTable.h.
References mlir::OpTrait::impl::verifySymbol().
The documentation for this class was generated from the following file:
include/mlir/IR/SymbolTable.h