MLIR: mlir::MemRefType Class Reference
mlir::MemRefType Class Reference
MemRef types represent a region of memory that have a shape with a fixed number of dimensions.
#include "mlir/IR/StandardTypes.h"
Public Member Functions
ArrayRef< int64_t > getShape () const
ArrayRef< AffineMap > getAffineMaps () const
Returns an array of affine map pointers representing the memref affine map composition.
unsigned getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Static Public Member Functions
static MemRefType get (ArrayRef< int64_t > shape, Type elementType, ArrayRef< AffineMap > affineMapComposition={}, unsigned memorySpace=0)
Get or create a new MemRefType based on shape, element type, affine map composition, and memory space.
static MemRefType getChecked (ArrayRef< int64_t > shape, Type elementType, ArrayRef< AffineMap > affineMapComposition, unsigned memorySpace, Location location)
Get or create a new MemRefType based on shape, element type, affine map composition, and memory space declared at the given location.
static int64_t getDynamicStrideOrOffset ()
static bool kindof (unsigned kind)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Static Public Attributes
static constexpr int64_t kDynamicSize = -1
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
MemRef types represent a region of memory that have a shape with a fixed number of dimensions.
Each shape element can be a non-negative integer or unknown (represented by any negative integer). MemRef types also have an affine map composition, represented as an array AffineMap pointers.
Definition at line 390 of file StandardTypes.h.
Member Function Documentation
get()
MemRefType MemRefType::get (ArrayRef< int64_t > shape, Type elementType, ArrayRef< AffineMap > affineMapComposition = {}, unsigned memorySpace = 0) static
Get or create a new MemRefType based on shape, element type, affine map composition, and memory space.
Assumes the arguments define a well-formed MemRef type. Use getChecked to gracefully handle MemRefType construction failures.
Definition at line 303 of file StandardTypes.cpp.
References mlir::StandardTypes::None.
Referenced by allocBuffer(), mlir::canonicalizeStridedLayout(), mlir::fxpmath::detail::castElementType(), clip(), computeReshapeCollapsedType(), createPrivateMemRef(), doubleBuffer(), generateCopy(), inferSubViewResultType(), inferVectorTypeCastResultType(), makeMemRefType(), mlir::normalizeMemRef(), mlir::operator<<(), promoteFullTileBuffer(), and verify().
getAffineMaps()
ArrayRef< AffineMap > MemRefType::getAffineMaps () const
Returns an array of affine map pointers representing the memref affine map composition.
Definition at line 382 of file StandardTypes.cpp.
Referenced by mlir::canonicalizeStridedLayout(), mlir::MemRefDescriptor::fromStaticShape(), generateCopy(), mlir::MemRefRegion::getRegionSize(), mlir::getStridesAndOffset(), mlir::normalizeMemRef(), mlir::operator<<(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), and verify().
getChecked()
MemRefType MemRefType::getChecked (ArrayRef< int64_t > shape, Type elementType, ArrayRef< AffineMap > affineMapComposition, unsigned memorySpace, Location location) static
Get or create a new MemRefType based on shape, element type, affine map composition, and memory space declared at the given location.
If the location is unknown, the last argument should be an instance of UnknownLoc. If the MemRefType defined by the arguments would be ill-formed, emits errors (to the handler registered with the context or to the error stream) and returns nullptr.
Definition at line 318 of file StandardTypes.cpp.
References mlir::emitError(), mlir::emitOptionalError(), mlir::Type::getContext(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::getImpl(), mlir::Type::isa(), mlir::Type::isIntOrFloat(), mlir::functional::map(), and mlir::StandardTypes::MemRef.
Referenced by parseSymbol().
getDynamicStrideOrOffset()
static int64_t mlir::MemRefType::getDynamicStrideOrOffset () inline static
Definition at line 426 of file StandardTypes.h.
Referenced by getElementPtr(), getTypeNumBytes(), inferSubViewResultType(), mlir::makeStridedLinearLayoutMap(), mlir::operator<<(), parseSymbol(), print(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), verify(), and verifyDynamicStrides().
getMemorySpace()
unsigned MemRefType::getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Definition at line 386 of file StandardTypes.cpp.
Referenced by inferSubViewResultType(), mlir::operator<<(), and verify().
getShape()
ArrayRef< int64_t > MemRefType::getShape () const
Definition at line 380 of file StandardTypes.cpp.
Referenced by mlir::canonicalizeStridedLayout(), computeReshapeCollapsedType(), getMemRefSizes(), mlir::getStridesAndOffset(), inferVectorTypeCastResultType(), insertCopies(), mlir::normalizeMemRef(), mlir::operator<<(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), verify(), and verifyDynamicStrides().
kindof()
static bool mlir::MemRefType::kindof (unsigned kind) inline static
Definition at line 430 of file StandardTypes.h.
References mlir::StandardTypes::MemRef.
Member Data Documentation
kDynamicSize
constexpr int64_t mlir::MemRefType::kDynamicSize = -1 static
Definition at line 425 of file StandardTypes.h.
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp