MLIR: mlir::VectorType Class Reference
mlir::VectorType Class Reference
Vector types represent multi-dimensional SIMD vectors, and have a fixed known constant shape with one or more dimension.
#include "mlir/IR/StandardTypes.h"
Public Member Functions
ArrayRef< int64_t > getShape () const
Static Public Member Functions
static VectorType get (ArrayRef< int64_t > shape, Type elementType)
Get or create a new VectorType of the provided shape and element type.
static VectorType getChecked (ArrayRef< int64_t > shape, Type elementType, Location location)
Get or create a new VectorType of the provided shape and element type declared at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Optional< Location > loc, MLIRContext *context, ArrayRef< int64_t > shape, Type elementType)
Verify the construction of a vector type.
static bool isValidElementType (Type t)
Returns true of the given type can be used as an element of a vector type.
static bool kindof (unsigned kind)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
static ClassID * getClassID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide a default implementation of 'classof' that invokes a 'kindof' method on the concrete type.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename... Args>
static ConcreteT getChecked (const Location &loc, MLIRContext *ctx, unsigned kind, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Vector types represent multi-dimensional SIMD vectors, and have a fixed known constant shape with one or more dimension.
Definition at line 256 of file StandardTypes.h.
Member Function Documentation
get()
VectorType VectorType::get (ArrayRef< int64_t > shape, Type elementType) static
Get or create a new VectorType of the provided shape and element type.
Assumes the arguments define a well-formed VectorType.
Definition at line 199 of file StandardTypes.cpp.
References mlir::Type::getContext(), and mlir::StandardTypes::Vector.
Referenced by mlir::fxpmath::detail::castElementType(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::quant::ExpressedToQuantizedConverter::convert(), mlir::VulkanLayoutUtils::decorateType(), generateExtractSlicesOpResultType(), mlir::OpTrait::util::getBroadcastedType(), getCheckedI1SameShape(), mlir::spirv::getEntryPointABIAttr(), mlir::Builder::getI32VectorAttr(), getOrCreateUnrolledVectorSlice(), getOrInsertBuiltinVariable(), getUnaryOpResultType(), inferExtractOpResultType(), inferStridedSliceOpResultType(), inferVectorTypeCastResultType(), isFnEntryBlock(), isValidExtractOrInsertSlicesType(), mappingHelper(), parseContractionOp(), parseOuterProductOp(), parseShuffleOp(), reducedVectorTypeBack(), reducedVectorTypeFront(), unrollSingleResultStructuredOp(), vectorizeOneOperation(), vectorizeOperand(), and vectorizeRootOrTerminal().
getChecked()
VectorType VectorType::getChecked (ArrayRef< int64_t > shape, Type elementType, Location location) static
Get or create a new VectorType of the provided shape and element type declared at the given, potentially unknown, location.
If the VectorType defined by the arguments would be ill-formed, emit errors and return nullptr-wrapping type.
Definition at line 204 of file StandardTypes.cpp.
References mlir::Type::getContext(), and mlir::StandardTypes::Vector.
Referenced by parseSymbol().
getShape()
ArrayRef< int64_t > VectorType::getShape () const
Definition at line 228 of file StandardTypes.cpp.
Referenced by mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::ExpressedToQuantizedConverter::convert(), generateExtractSlicesOpResultType(), generateTransferOpSlices(), inferExtractOpResultType(), inferStridedSliceOpResultType(), initUnrolledVectorState(), isValidExtractOrInsertSlicesType(), parseContractionOp(), reducedVectorTypeBack(), reducedVectorTypeFront(), mlir::shapeRatio(), verify(), verifyOutputShape(), and verifyTransferOp().
isValidElementType()
static bool mlir::VectorType::isValidElementType (Type t) inline static
Returns true of the given type can be used as an element of a vector type.
In particular, vectors can consist of integer or float primitives.
Definition at line 280 of file StandardTypes.h.
References getShape(), and mlir::Type::isIntOrFloat().
Referenced by vectorizeConstant(), vectorizeRootOrTerminal(), and verify().
kindof()
static bool mlir::VectorType::kindof (unsigned kind) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 285 of file StandardTypes.h.
References mlir::StandardTypes::Vector.
verifyConstructionInvariants()
LogicalResult VectorType::verifyConstructionInvariants (Optional< Location > loc, MLIRContext * context, ArrayRef< int64_t > shape, Type elementType) static
Verify the construction of a vector type.
Definition at line 210 of file StandardTypes.cpp.
References mlir::emitOptionalError(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/StandardTypes.h
lib/IR/StandardTypes.cpp