MLIR: mlir::SPIRVTypeConverter Class Reference
mlir::SPIRVTypeConverter Class Reference final
Type conversion from standard types to SPIR-V types for shader interface.
#include "mlir/Dialect/SPIRV/SPIRVLowering.h"
Public Member Functions
Type convertType (Type type) override
Converts the given standard type to SPIR-V correspondence.
Public Member Functions inherited from mlir::TypeConverter
virtual ~TypeConverter ()=default
virtual LogicalResult convertType (Type t, SmallVectorImpl< Type > &results)
This hook allows for converting a type.
LogicalResult convertTypes (ArrayRef< Type > types, SmallVectorImpl< Type > &results)
Convert the given set of types, filling 'results' as necessary.
bool isLegal (Type type)
Return true if the given type is legal for this type converter, i.e.
bool isSignatureLegal (FunctionType funcType)
Return true if the inputs and outputs of the given function type are legal.
virtual LogicalResult convertSignatureArg (unsigned inputNo, Type type, SignatureConversion &result)
This hook allows for converting a specific argument of a signature.
Optional< SignatureConversion > convertBlockSignature (Block *block)
This function converts the type signature of the given block, by invoking 'convertSignatureArg' for each argument.
virtual Operation * materializeConversion (PatternRewriter &rewriter, Type resultType, ArrayRef< Value > inputs, Location loc)
This hook allows for materializing a conversion from a set of types into one result type by generating a cast operation of some kind.
Static Public Member Functions
static Type getIndexType (MLIRContext *context)
Gets the SPIR-V correspondence for the standard index type.
Detailed Description
Type conversion from standard types to SPIR-V types for shader interface.
For composite types, this converter additionally performs type wrapping to satisfy shader interface requirements: shader interface types must be pointers to structs.
Definition at line 28 of file SPIRVLowering.h.
Member Function Documentation
convertType()
Type SPIRVTypeConverter::convertType (Type type) override virtual
Converts the given standard type to SPIR-V correspondence.
Reimplemented from mlir::TypeConverter.
Definition at line 171 of file SPIRVLowering.cpp.
References mlir::ConversionPatternRewriter::applySignatureConversion(), convertStdType(), mlir::detail::enumerate(), mlir::Builder::getFunctionType(), mlir::FunctionType::getInputs(), mlir::FuncOp::getType(), mlir::StandardTypes::None, mlir::FuncOp::setType(), and mlir::PatternRewriter::updateRootInPlace().
Referenced by lowerAsEntryFunction().
getIndexType()
Type SPIRVTypeConverter::getIndexType (MLIRContext * context) static
Gets the SPIR-V correspondence for the standard index type.
Definition at line 30 of file SPIRVLowering.cpp.
References mlir::IntegerType::get().
Referenced by convertStdType(), and mlir::spirv::getElementPtr().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVLowering.h
lib/Dialect/SPIRV/SPIRVLowering.cpp