MLIR: mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType > Class Template Reference
mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType > Class Template Reference
This class provides the API for structured ops that are known to operate on buffers or tensors.
#include "mlir/Dialect/Linalg/IR/LinalgTraits.h"
Public Member Functions
unsigned getNumParallelLoops ()
unsigned getNumReductionLoops ()
unsigned getNumWindowLoops ()
unsigned getNumLoops ()
bool hasSingleReductionLoop ()
Value getInput (unsigned i)
Return the i-th input value.
Optional< unsigned > getIndexOfInput (Value value)
Return the index of value in the list of inputs if found, llvm::None otherwise.
ShapedType getInputShapedType (unsigned i)
Return the i-th input buffer type.
Operation::operand_range getInputs ()
Return the range over inputs.
SmallVector< RankedTensorType, 4 > getInputTensorTypes ()
Query the subset of input operands that are of ranked tensor type.
Value getOutputBuffer (unsigned i)
Return the i-th output, asserts that this is a buffer operand and not a tensor result.
Optional< unsigned > getIndexOfOutputBuffer (Value value)
Return the index of value in the list of output buffers if found, llvm::None otherwise.
MemRefType getOutputBufferType (unsigned i)
Return the i-th output buffer type.
ShapedType getOutputShapedType (unsigned i)
Return the i-th output shaped type, irrespective of buffer of tensor type.
SmallVector< RankedTensorType, 4 > getOutputTensorTypes ()
Query the subset of results that are of ranked tensor type.
Operation::operand_range getOutputBuffers ()
Return the range over outputs.
unsigned getNumInputsAndOutputs ()
Return the number of inputs and outputs, irrespective of their buffer or tensor type.
unsigned getNumInputsAndOutputBuffers ()
Return the number of inputs, irrespective of their buffer or tensor type, and output buffers.
Operation::operand_range getInputsAndOutputBuffers ()
Return the range over inputs (irrespective of type) and output buffers.
ShapedType getShapedType (unsigned i)
Return the i-th shaped type, there are 3 cases:
bool hasBufferSemantics ()
Query whether the op has only buffer inputs and no returns.
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, StructuredOpTraits >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Static Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, StructuredOpTraits >
static LogicalResult verifyTrait (Operation *op)
Provide default implementations of trait hooks.
static AbstractOperation::OperationProperties getTraitProperties ()
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >
This class provides the API for structured ops that are known to operate on buffers or tensors.
This trait must be used in conjunction with an op definition or a trait that provides the methods getNumInputs and getNumOutputs. Use as a trait as follows:
class DotOp : public Op<DotOp, OpTrait::StructuredOpTraits> {
Definition at line 58 of file LinalgTraits.h.
Member Function Documentation
getIndexOfInput()
template<typename ConcreteType > Optional<unsigned> mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getIndexOfInput (Value value) inline
Return the index of value in the list of inputs if found, llvm::None otherwise.
Definition at line 115 of file LinalgTraits.h.
References mlir::StandardTypes::None.
getIndexOfOutputBuffer()
template<typename ConcreteType > Optional<unsigned> mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getIndexOfOutputBuffer (Value value) inline
Return the index of value in the list of output buffers if found, llvm::None otherwise.
Definition at line 154 of file LinalgTraits.h.
References mlir::StandardTypes::None.
getInput()
template<typename ConcreteType > Value mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getInput (unsigned i) inline
Return the i-th input value.
Definition at line 109 of file LinalgTraits.h.
References mlir::Operation::getOperand(), and mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getInputs()
template<typename ConcreteType > Operation::operand_range mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getInputs () inline
Return the range over inputs.
Definition at line 126 of file LinalgTraits.h.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), mlir::Operation::getOperands(), and mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getInputsAndOutputBuffers()
template<typename ConcreteType > Operation::operand_range mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getInputsAndOutputBuffers () inline
Return the range over inputs (irrespective of type) and output buffers.
Definition at line 196 of file LinalgTraits.h.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), mlir::Operation::getOperands(), and mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getInputShapedType()
template<typename ConcreteType > ShapedType mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getInputShapedType (unsigned i) inline
Return the i-th input buffer type.
Definition at line 122 of file LinalgTraits.h.
getInputTensorTypes()
template<typename ConcreteType > SmallVector<RankedTensorType, 4> mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getInputTensorTypes () inline
Query the subset of input operands that are of ranked tensor type.
Definition at line 131 of file LinalgTraits.h.
getNumInputsAndOutputBuffers()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumInputsAndOutputBuffers () inline
Return the number of inputs, irrespective of their buffer or tensor type, and output buffers.
Definition at line 191 of file LinalgTraits.h.
References mlir::Operation::getNumResults(), and mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getNumInputsAndOutputs()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumInputsAndOutputs () inline
Return the number of inputs and outputs, irrespective of their buffer or tensor type.
Definition at line 188 of file LinalgTraits.h.
getNumLoops()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumLoops () inline
Definition at line 91 of file LinalgTraits.h.
References mlir::getNumIterators(), and mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getNumParallelLoops()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumParallelLoops () inline
Definition at line 76 of file LinalgTraits.h.
References mlir::getNumIterators(), mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation(), and mlir::getParallelIteratorTypeName().
getNumReductionLoops()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumReductionLoops () inline
Definition at line 81 of file LinalgTraits.h.
References mlir::getNumIterators(), mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation(), and mlir::getReductionIteratorTypeName().
getNumWindowLoops()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumWindowLoops () inline
Definition at line 86 of file LinalgTraits.h.
References mlir::getNumIterators(), mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation(), and mlir::getWindowIteratorTypeName().
getOutputBuffer()
template<typename ConcreteType > Value mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getOutputBuffer (unsigned i) inline
Return the i-th output, asserts that this is a buffer operand and not a tensor result.
Definition at line 147 of file LinalgTraits.h.
References mlir::Operation::getOperand(), and mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getOutputBuffers()
template<typename ConcreteType > Operation::operand_range mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getOutputBuffers () inline
Return the range over outputs.
Definition at line 177 of file LinalgTraits.h.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), mlir::Operation::getOperands(), and mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getOutputBufferType()
template<typename ConcreteType > MemRefType mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getOutputBufferType (unsigned i) inline
Return the i-th output buffer type.
Definition at line 161 of file LinalgTraits.h.
getOutputShapedType()
template<typename ConcreteType > ShapedType mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getOutputShapedType (unsigned i) inline
Return the i-th output shaped type, irrespective of buffer of tensor type.
Definition at line 166 of file LinalgTraits.h.
getOutputTensorTypes()
template<typename ConcreteType > SmallVector<RankedTensorType, 4> mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getOutputTensorTypes () inline
Query the subset of results that are of ranked tensor type.
Definition at line 170 of file LinalgTraits.h.
References mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getShapedType()
template<typename ConcreteType > ShapedType mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getShapedType (unsigned i) inline
Return the i-th shaped type, there are 3 cases:
if i < nInputs() then return getInputShapedType(i); otherwise
if i < getNumInputsAndOutputBuffers() then return the getOutputBufferType(i - nInputs()); otherwise
return the i - getNumInputsAndOutputBuffers() result type.
Definition at line 205 of file LinalgTraits.h.
hasBufferSemantics()
template<typename ConcreteType > bool mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::hasBufferSemantics () inline
Query whether the op has only buffer inputs and no returns.
Definition at line 218 of file LinalgTraits.h.
References mlir::Operation::getNumResults(), mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation(), mlir::Value::getType(), and mlir::Type::isa().
hasSingleReductionLoop()
template<typename ConcreteType > bool mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::hasSingleReductionLoop () inline
Definition at line 96 of file LinalgTraits.h.
References mlir::getNumIterators(), mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation(), and mlir::getReductionIteratorTypeName().
verifyTrait()
template<typename ConcreteType > static LogicalResult mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 227 of file LinalgTraits.h.
References mlir::failed(), mlir::failure(), mlir::success(), and mlir::OpTrait::impl::verifyAtLeastNOperands().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Linalg/IR/LinalgTraits.h