MLIR: mlir::OpPassManager Class Reference
mlir::OpPassManager Class Reference
This class represents a pass manager that runs passes on a specific operation type.
#include "mlir/Pass/PassManager.h"
Public Types
using pass_iterator = llvm::pointee_iterator< std::vector< std::unique_ptr< Pass > >::iterator >
Iterator over the passes in this pass manager.
Public Member Functions
OpPassManager (OpPassManager &&rhs)
OpPassManager (const OpPassManager &rhs)
~OpPassManager ()
OpPassManager & operator= (const OpPassManager &rhs)
pass_iterator begin ()
pass_iterator end ()
iterator_range< pass_iterator > getPasses ()
LogicalResult run (Operation *op, AnalysisManager am)
Run the held passes over the given operation.
OpPassManager & nest (const OperationName &nestedName)
Nest a new operation pass manager for the given operation kind under this pass manager.
OpPassManager & nest (StringRef nestedName)
template<typename OpT >
OpPassManager & nest ()
void addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
template<typename OpT >
void addNestedPass (std::unique_ptr< Pass > pass)
Add the given pass to a nested pass manager for the given operation kind OpT.
size_t size () const
Returns the number of passes held by this manager.
MLIRContext * getContext () const
Return an instance of the context.
const OperationName & getOpName () const
Return the operation name that this pass manager operates on.
detail::OpPassManagerImpl & getImpl ()
Returns the internal implementation instance.
void printAsTextualPipeline (raw_ostream &os)
Prints out the passes of the pass manager as the textual representation of pipelines.
void mergeStatisticsInto (OpPassManager &other)
Merge the pass statistics of this class into 'other'.
Friends
class PassManager
Allow access to the constructor.
Detailed Description
This class represents a pass manager that runs passes on a specific operation type.
This class is not constructed directly, but nested within other OpPassManagers or the top-level PassManager.
Definition at line 44 of file PassManager.h.
Member Typedef Documentation
pass_iterator
using mlir::OpPassManager::pass_iterator = llvm::pointee_iterator<std::vector<std::unique_ptr<Pass> >::iterator>
Iterator over the passes in this pass manager.
Definition at line 53 of file PassManager.h.
Constructor & Destructor Documentation
OpPassManager() [1/2]
OpPassManager::OpPassManager (OpPassManager && rhs)
Definition at line 212 of file Pass.cpp.
Referenced by mlir::detail::OpPassManagerImpl::coalesceAdjacentAdaptorPasses().
OpPassManager() [2/2]
OpPassManager::OpPassManager (const OpPassManager & rhs)
Definition at line 213 of file Pass.cpp.
~OpPassManager()
OpPassManager::~OpPassManager ()
Definition at line 222 of file Pass.cpp.
Member Function Documentation
addNestedPass()
template<typename OpT > void mlir::OpPassManager::addNestedPass (std::unique_ptr< Pass > pass) inline
Add the given pass to a nested pass manager for the given operation kind OpT.
Definition at line 75 of file PassManager.h.
addPass()
void OpPassManager::addPass (std::unique_ptr< Pass > pass)
Add the given pass to this pass manager.
If this pass has a concrete operation type, it must be the same type as this pass manager.
Definition at line 261 of file Pass.cpp.
References addPass(), and nest().
Referenced by addPass(), buildDefaultRegistryFn(), and nest().
begin()
OpPassManager::pass_iterator OpPassManager::begin ()
Definition at line 224 of file Pass.cpp.
end()
OpPassManager::pass_iterator OpPassManager::end ()
Definition at line 227 of file Pass.cpp.
getContext()
MLIRContext * OpPassManager::getContext () const
Return an instance of the context.
Definition at line 280 of file Pass.cpp.
Referenced by nest(), and runWithCrashRecovery().
getImpl()
OpPassManagerImpl & OpPassManager::getImpl ()
Returns the internal implementation instance.
Definition at line 277 of file Pass.cpp.
Referenced by mlir::PassManager::disableMultithreading(), mlir::PassManager::run(), and runWithCrashRecovery().
getOpName()
const OperationName & OpPassManager::getOpName () const
Return the operation name that this pass manager operates on.
Definition at line 285 of file Pass.cpp.
Referenced by findPassManagerFor(), mlir::detail::OpToOpPassAdaptorBase::getName(), and mlir::detail::OpToOpPassAdaptorBase::mergeInto().
getPasses()
iterator_range<pass_iterator> mlir::OpPassManager::getPasses () inline
Definition at line 56 of file PassManager.h.
Referenced by mergeStatisticsInto(), prepareStatistics(), printResultsAsList(), and printResultsAsPipeline().
mergeStatisticsInto()
void OpPassManager::mergeStatisticsInto (OpPassManager & other)
Merge the pass statistics of this class into 'other'.
Definition at line 191 of file PassStatistics.cpp.
References mlir::detail::getAdaptorPassBase(), getPasses(), and pass.
nest() [1/3]
OpPassManager & OpPassManager::nest (const OperationName & nestedName)
Nest a new operation pass manager for the given operation kind under this pass manager.
Create an adaptor for this pass. If multi-threading is disabled, then create a synchronous adaptor.
Definition at line 240 of file Pass.cpp.
References addPass().
Referenced by mlir::detail::PassOptions::print().
nest() [2/3]
OpPassManager & OpPassManager::nest (StringRef nestedName)
Definition at line 255 of file Pass.cpp.
References getContext(), and nest().
nest() [3/3]
template<typename OpT > OpPassManager& mlir::OpPassManager::nest () inline
Definition at line 65 of file PassManager.h.
References pass.
Referenced by addPass(), and nest().
operator=()
OpPassManager & OpPassManager::operator= (const OpPassManager & rhs)
Definition at line 214 of file Pass.cpp.
References pass.
printAsTextualPipeline()
void OpPassManager::printAsTextualPipeline (raw_ostream & os)
Prints out the passes of the pass manager as the textual representation of pipelines.
Note: The quality of the string representation depends entirely on the the correctness of per-pass overrides of Pass::printAsTextualPipeline.
Definition at line 289 of file Pass.cpp.
References mlir::interleaveComma(), and pass.
Referenced by runWithCrashRecovery().
run()
LogicalResult OpPassManager::run (Operation * op, AnalysisManager am)
Run the held passes over the given operation.
Run all of the passes in this manager over the current operation.
Definition at line 230 of file Pass.cpp.
References mlir::failed(), mlir::failure(), pass, and mlir::success().
Referenced by mlir::PassManager::run(), runPipeline(), and runWithCrashRecovery().
size()
size_t OpPassManager::size () const
Returns the number of passes held by this manager.
Definition at line 274 of file Pass.cpp.
Friends And Related Function Documentation
PassManager
friend class PassManager friend
Allow access to the constructor.
Definition at line 107 of file PassManager.h.
The documentation for this class was generated from the following files:
include/mlir/Pass/PassManager.h
lib/Pass/Pass.cpp
lib/Pass/PassStatistics.cpp