MLIR: lib/Target/LLVMIR/ConvertFromLLVMIR.cpp File Reference
ConvertFromLLVMIR.cpp File Reference
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Target/LLVMIR.h"
#include "mlir/Translation.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Type.h"
#include "llvm/IRReader/IRReader.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/SourceMgr.h"
Macros
#define INST(llvm_n, mlir_n) { llvm::Instruction::llvm_n, LLVM::mlir_n##Op::getOperationName() }
Functions
static std::string diag (llvm::Value &v)
static LLVM::Linkage processLinkage (llvm::GlobalVariable::LinkageTypes linkage)
Converts LLVM global variable linkage type into the LLVM dialect predicate.
static ICmpPredicate getICmpPredicate (llvm::CmpInst::Predicate p)
OwningModuleRef translateLLVMIRToModule (llvm::SourceMgr &sourceMgr, MLIRContext *context)
Variables
static const DenseMap< unsigned, StringRef > opcMap
static TranslateToMLIRRegistration fromLLVM ("import-llvm", [](llvm::SourceMgr &sourceMgr, MLIRContext *context) { return translateLLVMIRToModule(sourceMgr, context);})
Macro Definition Documentation
INST
#define INST (llvm_n, mlir_n) { llvm::Instruction::llvm_n, LLVM::mlir_n##Op::getOperationName() }
Definition at line 494 of file ConvertFromLLVMIR.cpp.
Function Documentation
diag()
static std::string diag (llvm::Value & v) static
Definition at line 36 of file ConvertFromLLVMIR.cpp.
References mlir::Block::begin(), mlir::edsc::intrinsics::br(), mlir::Constant, mlir::emitError(), mlir::Block::end(), mlir::IntegerType::get(), mlir::FileLineColLoc::get(), mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::DenseElementsAttr::get(), mlir::LLVM::LLVMType::getArrayElementType(), mlir::LLVM::LLVMType::getArrayNumElements(), mlir::LLVM::LLVMType::getArrayTy(), mlir::ModuleOp::getBody(), mlir::LLVM::LLVMType::getDoubleTy(), mlir::FloatType::getF32(), mlir::FloatType::getF64(), mlir::LLVM::LLVMType::getFloatTy(), mlir::LLVM::LLVMType::getFP128Ty(), mlir::LLVM::LLVMType::getFunctionTy(), mlir::LLVM::LLVMType::getIntNTy(), mlir::LLVM::LLVMType::getPointerTo(), mlir::MLIRContext::getRegisteredDialect(), mlir::LLVM::LLVMType::getStructTy(), mlir::LLVM::LLVMType::getUnderlyingType(), mlir::LLVM::LLVMType::getVectorElementType(), mlir::LLVM::LLVMType::getVectorTy(), mlir::LLVM::LLVMType::getVoidTy(), mlir::LLVM::LLVMType::getX86_FP80Ty(), mlir::LLVM::LLVMType::isArrayTy(), mlir::LLVM::LLVMType::isDoubleTy(), mlir::LLVM::LLVMType::isFloatTy(), mlir::LLVM::LLVMType::isIntegerTy(), mlir::LLVM::LLVMType::isVectorTy(), processValue(), and mlir::StandardAttributes::Type.
Referenced by adjustToDivisorsOfTripCounts(), mlir::DiagnosticEngine::emit(), emitDiag(), mlir::SourceMgrDiagnosticHandler::emitDiagnostic(), mlir::Operation::emitError(), mlir::Operation::emitRemark(), mlir::Operation::emitWarning(), getICmpPredicate(), parseSymbol(), processLinkage(), mlir::DiagnosticEngine::registerHandler(), mlir::SourceMgrDiagnosticHandler::SourceMgrDiagnosticHandler(), mlir::SourceMgrDiagnosticVerifierHandler::SourceMgrDiagnosticVerifierHandler(), and mlir::SourceMgrDiagnosticVerifierHandler::verify().
getICmpPredicate()
static ICmpPredicate getICmpPredicate (llvm::CmpInst::Predicate p) static
Definition at line 542 of file ConvertFromLLVMIR.cpp.
References Add, mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::edsc::intrinsics::br(), mlir::Operation::create(), diag(), mlir::emitError(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::UnknownLoc::get(), mlir::LLVM::LLVMType::getFunctionParamType(), mlir::Operation::getResult(), Mul, processValue(), mlir::Value::replaceAllUsesWith(), Sub, and mlir::success().
processLinkage()
static LLVM::Linkage processLinkage (llvm::GlobalVariable::LinkageTypes linkage) static
Converts LLVM global variable linkage type into the LLVM dialect predicate.
Definition at line 368 of file ConvertFromLLVMIR.cpp.
References mlir::OperationState::addTypes(), mlir::Constant, diag(), mlir::emitError(), mlir::failed(), mlir::UnknownLoc::get(), and processValue().
translateLLVMIRToModule()
OwningModuleRef translateLLVMIRToModule (llvm::SourceMgr & sourceMgr, MLIRContext * context)
Definition at line 816 of file ConvertFromLLVMIR.cpp.
References mlir::emitError(), fromLLVM, mlir::UnknownLoc::get(), mlir::LLVM::LLVMDialect::getLLVMContext(), mlir::MLIRContext::getRegisteredDialect(), and mlir::translateLLVMIRToModule().
Variable Documentation
fromLLVM
TranslateToMLIRRegistration fromLLVM("import-llvm", [](llvm::SourceMgr &sourceMgr, MLIRContext *context) { return translateLLVMIRToModule(sourceMgr, context);}) static
Referenced by translateLLVMIRToModule().
opcMap
const DenseMap<unsigned, StringRef> opcMap static
Definition at line 496 of file ConvertFromLLVMIR.cpp.