MLIR: lib/Conversion/VectorToLLVM/ConvertVectorToLLVM.cpp File Reference
ConvertVectorToLLVM.cpp File Reference
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/Dialect/VectorOps/VectorOps.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/Types.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/ErrorHandling.h"
Functions
template<typename T >
static LLVM::LLVMType getPtrToElementType (T containerType, LLVMTypeConverter &lowering)
static VectorType reducedVectorTypeFront (VectorType tp)
static VectorType reducedVectorTypeBack (VectorType tp)
static Value insertOne (ConversionPatternRewriter &rewriter, LLVMTypeConverter &lowering, Location loc, Value val1, Value val2, Type llvmType, int64_t rank, int64_t pos)
static Value insertOne (PatternRewriter &rewriter, Location loc, Value from, Value into, int64_t offset)
static Value extractOne (ConversionPatternRewriter &rewriter, LLVMTypeConverter &lowering, Location loc, Value val, Type llvmType, int64_t rank, int64_t pos)
static Value extractOne (PatternRewriter &rewriter, Location loc, Value vector, int64_t offset)
static SmallVector< int64_t, 4 > getI64SubArray (ArrayAttr arrayAttr, unsigned dropFront=0, unsigned dropBack=0)
Variables
static PassRegistration< LowerVectorToLLVMPass > pass ("convert-vector-to-llvm", "Lower the operations from the vector dialect into the LLVM dialect")
Function Documentation
extractOne() [1/2]
static Value extractOne (ConversionPatternRewriter & rewriter, LLVMTypeConverter & lowering, Location loc, Value val, Type llvmType, int64_t rank, int64_t pos) static
Definition at line 85 of file ConvertVectorToLLVM.cpp.
References mlir::LLVMTypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), and mlir::Builder::getIntegerAttr().
Referenced by getI64SubArray().
extractOne() [2/2]
static Value extractOne (PatternRewriter & rewriter, Location loc, Value vector, int64_t offset) static
Definition at line 101 of file ConvertVectorToLLVM.cpp.
References mlir::Type::cast(), mlir::PatternRewriter::create(), and mlir::Value::getType().
getI64SubArray()
static SmallVector<int64_t, 4> getI64SubArray (ArrayAttr arrayAttr, unsigned dropFront = 0, unsigned dropBack = 0) static
Definition at line 113 of file ConvertVectorToLLVM.cpp.
References mlir::MemRefDescriptor::alignedPtr(), mlir::MemRefDescriptor::allocatedPtr(), mlir::Value::cast(), mlir::PatternRewriter::create(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), extractOne(), mlir::failed(), mlir::ArrayAttr::get(), mlir::ArrayAttr::getAsRange(), mlir::Operation::getContext(), mlir::Operation::getDialect(), mlir::LLVM::LLVMType::getDoubleTy(), mlir::LLVM::LLVMType::getFloatTy(), mlir::LLVM::LLVMType::getFunctionTy(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), mlir::LLVM::LLVMType::getInt64Ty(), mlir::Builder::getIntegerAttr(), mlir::Operation::getLoc(), mlir::Operation::getParentOfType(), mlir::getStridesAndOffset(), mlir::Builder::getSymbolRefAttr(), mlir::Value::getType(), mlir::LLVM::LLVMType::getUnderlyingType(), mlir::LLVM::LLVMType::getVoidTy(), mlir::Builder::getZeroAttr(), insertOne(), mlir::Type::isa(), reducedVectorTypeBack(), reducedVectorTypeFront(), mlir::PatternRewriter::replaceOp(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::ArrayAttr::size(), mlir::success(), and mlir::MemRefDescriptor::undef().
getPtrToElementType()
template<typename T > static LLVM::LLVMType getPtrToElementType (T containerType, LLVMTypeConverter & lowering) static
Definition at line 38 of file ConvertVectorToLLVM.cpp.
References mlir::LLVMTypeConverter::convertType().
insertOne() [1/2]
static Value insertOne (ConversionPatternRewriter & rewriter, LLVMTypeConverter & lowering, Location loc, Value val1, Value val2, Type llvmType, int64_t rank, int64_t pos) static
Definition at line 58 of file ConvertVectorToLLVM.cpp.
References mlir::LLVMTypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), and mlir::Builder::getIntegerAttr().
Referenced by getI64SubArray().
insertOne() [2/2]
static Value insertOne (PatternRewriter & rewriter, Location loc, Value from, Value into, int64_t offset) static
Definition at line 74 of file ConvertVectorToLLVM.cpp.
References mlir::Type::cast(), mlir::PatternRewriter::create(), and mlir::Value::getType().
reducedVectorTypeBack()
static VectorType reducedVectorTypeBack (VectorType tp) static
Definition at line 52 of file ConvertVectorToLLVM.cpp.
References mlir::VectorType::get(), and mlir::VectorType::getShape().
Referenced by getI64SubArray().
reducedVectorTypeFront()
static VectorType reducedVectorTypeFront (VectorType tp) static
Definition at line 46 of file ConvertVectorToLLVM.cpp.
References mlir::VectorType::get(), and mlir::VectorType::getShape().
Referenced by getI64SubArray().
Variable Documentation
pass
PassRegistration<LowerVectorToLLVMPass> pass("convert-vector-to-llvm", "Lower the operations from the vector dialect into the LLVM dialect") static
Referenced by mlir::createLowerVectorToLLVMPass().