MLIR: lib/Conversion/VectorToLoops/ConvertVectorToLoops.cpp File Reference
ConvertVectorToLoops.cpp File Reference
#include <type_traits>
#include "mlir/Conversion/VectorToLoops/ConvertVectorToLoops.h"
#include "mlir/Dialect/VectorOps/VectorOps.h"
#include "mlir/EDSC/Builders.h"
#include "mlir/EDSC/Helpers.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
Functions
template<typename TransferOpTy >
static void coalesceCopy (TransferOpTy transfer, SmallVectorImpl< edsc::ValueHandle *> *pivs, edsc::VectorView *vectorView)
Analyzes the transfer to find an access dimension along the fastest remote MemRef dimension.
template<typename TransferOpTy >
static SmallVector< edsc::ValueHandle, 8 > clip (TransferOpTy transfer, edsc::MemRefView &view, ArrayRef< edsc::IndexHandle > ivs)
Emits remote memory accesses that are clipped to the boundaries of the MemRef.
Function Documentation
clip()
template<typename TransferOpTy > static SmallVector<edsc::ValueHandle, 8> clip (TransferOpTy transfer, edsc::MemRefView & view, ArrayRef< edsc::IndexHandle > ivs) static
Emits remote memory accesses that are clipped to the boundaries of the MemRef.
Definition at line 71 of file ConvertVectorToLoops.cpp.
References coalesceCopy(), mlir::detail::enumerate(), mlir::PatternRewriter::eraseOp(), mlir::MemRefType::get(), mlir::edsc::ValueHandle::getValue(), mlir::edsc::makeHandlePointers(), mlir::edsc::makeIndexHandles(), mlir::PatternRewriter::replaceOp(), and mlir::edsc::View::ub().
coalesceCopy()
template<typename TransferOpTy > static void coalesceCopy (TransferOpTy transfer, SmallVectorImpl< edsc::ValueHandle *> * pivs, edsc::VectorView * vectorView) static
Analyzes the transfer to find an access dimension along the fastest remote MemRef dimension.
If such a dimension with coalescing properties is found, pivs and vectorView are swapped so that the invocation of LoopNestBuilder captures it in the innermost loop.
Definition at line 38 of file ConvertVectorToLoops.cpp.
References mlir::detail::enumerate(), and mlir::edsc::View::swapRanges().
Referenced by clip().