MLIR: lib/Conversion/GPUToSPIRV/ConvertGPUToSPIRV.cpp File Reference
ConvertGPUToSPIRV.cpp File Reference
#include "mlir/Conversion/GPUToSPIRV/ConvertGPUToSPIRV.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVLowering.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/IR/Module.h"
#include "GPUToSPIRV.cpp.inc"
Functions
static FuncOp lowerAsEntryFunction (gpu::GPUFuncOp funcOp, SPIRVTypeConverter &typeConverter, ConversionPatternRewriter &rewriter, spirv::EntryPointABIAttr entryPointInfo, ArrayRef< spirv::InterfaceVarABIAttr > argABIInfo)
Function Documentation
lowerAsEntryFunction()
static FuncOp lowerAsEntryFunction (gpu::GPUFuncOp funcOp, SPIRVTypeConverter & typeConverter, ConversionPatternRewriter & rewriter, spirv::EntryPointABIAttr entryPointInfo, ArrayRef< spirv::InterfaceVarABIAttr > argABIInfo) static
Definition at line 277 of file ConvertGPUToSPIRV.cpp.
References mlir::ConversionPatternRewriter::applySignatureConversion(), mlir::SPIRVTypeConverter::convertType(), mlir::PatternRewriter::create(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::Identifier::get(), mlir::Builder::getContext(), mlir::spirv::getEntryPointABIAttr(), mlir::Builder::getFunctionType(), mlir::spirv::getInterfaceVarABIAttr(), mlir::gpu::GPUDialect::getKernelFuncAttrName(), mlir::SymbolTable::getSymbolAttrName(), mlir::FuncOp::getType(), mlir::impl::getTypeAttrName(), mlir::ConversionPatternRewriter::inlineRegionBefore(), mlir::gpu::GPUDialect::isKernel(), mlir::StandardTypes::None, mlir::OpState::removeAttr(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::spirv::setABIAttrs(), and mlir::OpState::setAttr().