MLIR: lib/Conversion/StandardToSPIRV/ConvertStandardToSPIRV.cpp File Reference
ConvertStandardToSPIRV.cpp File Reference
#include "mlir/Dialect/SPIRV/LayoutUtils.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVLowering.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/AffineMap.h"
#include "llvm/ADT/SetVector.h"
#include "StandardToSPIRV.cpp.inc"
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
Macros
#define DISPATCH(cmpPredicate, spirvOp)
#define DISPATCH(cmpPredicate, spirvOp)
Functions
static spirv::AccessChainOp getElementPtr (OpBuilder &builder, SPIRVTypeConverter &typeConverter, Location loc, MemRefType origBaseType, Value basePtr, ArrayRef< Value > indices)
Performs the index computation to get to the element pointed to by indices using the layout map of baseType.
void mlir::populateStandardToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating StandardOps to SPIR-V ops.
Macro Definition Documentation
DISPATCH [1/2]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpFOp, cmpFOp.getResult().getType(), \
                                         cmpFOpOperands.lhs(),                 \
                                         cmpFOpOperands.rhs());                \
    return matchSuccess();
Referenced by getElementPtr().
DISPATCH [2/2]
#define DISPATCH (cmpPredicate, spirvOp)
Value:
case cmpPredicate:                                                           \
    rewriter.replaceOpWithNewOp<spirvOp>(cmpIOp, cmpIOp.getResult().getType(), \
                                         cmpIOpOperands.lhs(),                 \
                                         cmpIOpOperands.rhs());                \
    return matchSuccess();
Function Documentation
getElementPtr()
static spirv::AccessChainOp getElementPtr (OpBuilder & builder, SPIRVTypeConverter & typeConverter, Location loc, MemRefType origBaseType, Value basePtr, ArrayRef< Value > indices) static
Performs the index computation to get to the element pointed to by indices using the layout map of baseType.
Definition at line 153 of file ConvertStandardToSPIRV.cpp.
References mlir::OpBuilder::create(), DISPATCH, mlir::detail::enumerate(), mlir::failed(), mlir::RankedTensorType::get(), mlir::IntegerAttr::get(), mlir::Builder::getContext(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::SPIRVTypeConverter::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::getStridesAndOffset(), mlir::Builder::getType(), mlir::OEQ, mlir::OGE, mlir::OGT, mlir::OLE, mlir::OLT, mlir::ONE, mlir::PatternRewriter::replaceOpWithNewOp(), mlir::UEQ, mlir::UGE, mlir::UGT, mlir::ULE, mlir::ULT, and mlir::UNE.