MLIR: lib/Target/LLVMIR/ConvertToNVVMIR.cpp File Reference
ConvertToNVVMIR.cpp File Reference
#include "mlir/Target/NVVMIR.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/IR/Module.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "mlir/Translation.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/ToolOutputFile.h"
#include "mlir/Dialect/LLVMIR/NVVMConversions.inc"
Functions
static llvm::Value * createIntrinsicCall (llvm::IRBuilder<> &builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value *> args={})
static llvm::Intrinsic::ID getShflBflyIntrinsicId (llvm::Type *resultType, bool withPredicate)
Variables
static TranslateFromMLIRRegistration registration ("mlir-to-nvvmir", [](ModuleOp module, raw_ostream &output) { auto llvmModule=mlir::translateModuleToNVVMIR(module);if(!llvmModule) return failure();llvmModule->print(output, nullptr);return success();})
Function Documentation
createIntrinsicCall()
static llvm::Value* createIntrinsicCall (llvm::IRBuilder<> & builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value *> args = {}) static
Definition at line 30 of file ConvertToNVVMIR.cpp.
getShflBflyIntrinsicId()
static llvm::Intrinsic::ID getShflBflyIntrinsicId (llvm::Type * resultType, bool withPredicate) static
Definition at line 38 of file ConvertToNVVMIR.cpp.
References mlir::LLVM::ModuleTranslation::convertOperation(), and getElementType().
Variable Documentation
registration
TranslateFromMLIRRegistration registration("mlir-to-nvvmir", [](ModuleOp module, raw_ostream &output) { auto llvmModule=mlir::translateModuleToNVVMIR(module);if(!llvmModule) return failure();llvmModule->print(output, nullptr);return success();}) static
Referenced by mlir::translateModuleToNVVMIR().