MLIR: lib/Conversion/StandardToLLVM/ConvertStandardToLLVM.cpp File Reference
ConvertStandardToLLVM.cpp File Reference
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/ADT/TypeSwitch.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/Functional.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
Macros
#define PASS_NAME "convert-std-to-llvm"
Functions
static llvm::cl::OptionCategory clOptionsCategory ("Standard to LLVM lowering options")
static llvm::cl::opt< bool > clUseAlloca (PASS_NAME "-use-alloca", llvm::cl::desc("Replace emission of malloc/free by alloca"), llvm::cl::init(false))
static llvm::cl::opt< bool > clUseBarePtrCallConv (PASS_NAME "-use-bare-ptr-memref-call-conv", llvm::cl::desc("Replace FuncOp's MemRef arguments with " "bare pointers to the MemRef element types"), llvm::cl::init(false))
static LLVM::LLVMType unwrap (Type type)
static Type convertMemRefTypeToBarePtr (LLVMTypeConverter &converter, MemRefType type)
Convert a MemRef type to a bare pointer to the MemRef element type.
static Value createIndexAttrConstant (OpBuilder &builder, Location loc, Type resultType, int64_t value)
static void ensureDistinctSuccessors (Block &bb)
static void populateStdToLLVMBarePtrFuncOpConversionPattern (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
static std::unique_ptr< LLVMTypeConverter > makeStandardToLLVMTypeConverter (MLIRContext *context)
Create an instance of LLVMTypeConverter in the given context.
static std::unique_ptr< LLVMTypeConverter > makeStandardToLLVMBarePtrTypeConverter (MLIRContext *context)
Create an instance of BarePtrTypeConverter in the given context.
Variables
static constexpr unsigned kAllocatedPtrPosInMemRefDescriptor = 0
static constexpr unsigned kAlignedPtrPosInMemRefDescriptor = 1
static constexpr unsigned kOffsetPosInMemRefDescriptor = 2
static constexpr unsigned kSizePosInMemRefDescriptor = 3
static constexpr unsigned kStridePosInMemRefDescriptor = 4
static constexpr unsigned kRankInUnrankedMemRefDescriptor = 0
static constexpr unsigned kPtrInUnrankedMemRefDescriptor = 1
static PassRegistration< LLVMLoweringPass > pass ("convert-std-to-llvm", "Convert scalar and vector operations from the " "Standard to the LLVM dialect", [] { return std::make_unique< LLVMLoweringPass >(clUseAlloca.getValue(), clUseBarePtrCallConv ? populateStdToLLVMBarePtrConversionPatterns :populateStdToLLVMConversionPatterns, clUseBarePtrCallConv ? makeStandardToLLVMBarePtrTypeConverter :makeStandardToLLVMTypeConverter);})
Macro Definition Documentation
PASS_NAME
#define PASS_NAME "convert-std-to-llvm"
Definition at line 36 of file ConvertStandardToLLVM.cpp.
Function Documentation
clOptionsCategory()
static llvm::cl::OptionCategory clOptionsCategory ("Standard to LLVM lowering options") static
clUseAlloca()
static llvm::cl::opt<bool> clUseAlloca (PASS_NAME "-use-alloca" , llvm::cl::desc("Replace emission of malloc/free by alloca") , llvm::cl::init(false)) static
Referenced by mlir::createLowerToLLVMPass(), and mlir::populateStdToLLVMMemoryConversionPatters().
clUseBarePtrCallConv()
static llvm::cl::opt<bool> clUseBarePtrCallConv (PASS_NAME "-use-bare-ptr-memref-call-conv" , llvm::cl::desc("Replace FuncOp's MemRef arguments with " "bare pointers to the MemRef element types") , llvm::cl::init(false)) static
Referenced by mlir::createLowerToLLVMPass().
convertMemRefTypeToBarePtr()
static Type convertMemRefTypeToBarePtr (LLVMTypeConverter & converter, MemRefType type) static
Convert a MemRef type to a bare pointer to the MemRef element type.
Definition at line 84 of file ConvertStandardToLLVM.cpp.
References mlir::LLVMTypeConverter::convertType(), mlir::failed(), mlir::MemRefType::getMemorySpace(), mlir::LLVM::LLVMType::getPointerTo(), mlir::getStridesAndOffset(), and unwrap().
Referenced by mlir::barePtrFuncArgTypeConverter().
createIndexAttrConstant()
static Value createIndexAttrConstant (OpBuilder & builder, Location loc, Type resultType, int64_t value) static
Definition at line 399 of file ConvertStandardToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), and mlir::StructBuilder::value.
Referenced by mlir::MemRefDescriptor::setConstantOffset(), mlir::MemRefDescriptor::setConstantSize(), mlir::MemRefDescriptor::setConstantStride(), and mlir::UnrankedMemRefDescriptor::setMemRefDescPtr().
ensureDistinctSuccessors()
static void ensureDistinctSuccessors (Block & bb) static
Definition at line 2153 of file ConvertStandardToLLVM.cpp.
References mlir::Block::getNumArguments(), mlir::Block::getParent(), mlir::Block::getSuccessor(), mlir::Block::getTerminator(), mlir::Region::push_back(), and mlir::Block::push_back().
Referenced by mlir::createLowerToLLVMPass(), and mlir::LLVM::ensureDistinctSuccessors().
makeStandardToLLVMBarePtrTypeConverter()
static std::unique_ptr<LLVMTypeConverter> makeStandardToLLVMBarePtrTypeConverter (MLIRContext * context) static
Create an instance of BarePtrTypeConverter in the given context.
Definition at line 2367 of file ConvertStandardToLLVM.cpp.
References mlir::ConversionTarget::addLegalDialect(), mlir::applyPartialConversion(), mlir::barePtrFuncArgTypeConverter(), mlir::LLVM::ensureDistinctSuccessors(), mlir::failed(), mlir::LLVMTypeConverterCustomization::funcArgConverter, makeStandardToLLVMTypeConverter(), and mlir::populateStdToLLVMConversionPatterns().
Referenced by mlir::createLowerToLLVMPass().
makeStandardToLLVMTypeConverter()
static std::unique_ptr<LLVMTypeConverter> makeStandardToLLVMTypeConverter (MLIRContext * context) static
Create an instance of LLVMTypeConverter in the given context.
Definition at line 2359 of file ConvertStandardToLLVM.cpp.
References mlir::LLVMTypeConverterCustomization::funcArgConverter, and mlir::structFuncArgTypeConverter().
Referenced by mlir::createLowerToLLVMPass(), and makeStandardToLLVMBarePtrTypeConverter().
populateStdToLLVMBarePtrFuncOpConversionPattern()
static void populateStdToLLVMBarePtrFuncOpConversionPattern (LLVMTypeConverter & converter, OwningRewritePatternList & patterns) static
Definition at line 2286 of file ConvertStandardToLLVM.cpp.
References mlir::LLVMTypeConverter::getDialect(), and mlir::OwningRewritePatternList::insert().
Referenced by mlir::populateStdToLLVMBarePtrConversionPatterns().
unwrap()
static LLVM::LLVMType unwrap (Type type) static
Definition at line 53 of file ConvertStandardToLLVM.cpp.
References mlir::Type::dyn_cast(), mlir::emitError(), mlir::UnknownLoc::get(), and mlir::Type::getContext().
Referenced by llvm::GraphTraits< const mlir::CallGraphNode * >::child_begin(), llvm::GraphTraits< const mlir::CallGraphNode * >::child_end(), mlir::LLVMTypeConverter::convertFunctionSignature(), convertMemRefTypeToBarePtr(), mlir::ValueTypeIterator< ValueIteratorT >::operator*(), and mlir::FilteredValueUseIterator< OperandType >::operator++().
Variable Documentation
kAlignedPtrPosInMemRefDescriptor
constexpr unsigned kAlignedPtrPosInMemRefDescriptor = 1 static
Definition at line 227 of file ConvertStandardToLLVM.cpp.
kAllocatedPtrPosInMemRefDescriptor
constexpr unsigned kAllocatedPtrPosInMemRefDescriptor = 0 static
Definition at line 226 of file ConvertStandardToLLVM.cpp.
kOffsetPosInMemRefDescriptor
constexpr unsigned kOffsetPosInMemRefDescriptor = 2 static
Definition at line 228 of file ConvertStandardToLLVM.cpp.
kPtrInUnrankedMemRefDescriptor
constexpr unsigned kPtrInUnrankedMemRefDescriptor = 1 static
Definition at line 259 of file ConvertStandardToLLVM.cpp.
kRankInUnrankedMemRefDescriptor
constexpr unsigned kRankInUnrankedMemRefDescriptor = 0 static
Definition at line 258 of file ConvertStandardToLLVM.cpp.
kSizePosInMemRefDescriptor
constexpr unsigned kSizePosInMemRefDescriptor = 3 static
Definition at line 229 of file ConvertStandardToLLVM.cpp.
Referenced by mlir::MemRefDescriptor::setSize(), and mlir::MemRefDescriptor::size().
kStridePosInMemRefDescriptor
constexpr unsigned kStridePosInMemRefDescriptor = 4 static
Definition at line 230 of file ConvertStandardToLLVM.cpp.
Referenced by mlir::MemRefDescriptor::setStride(), and mlir::MemRefDescriptor::stride().
pass
PassRegistration<LLVMLoweringPass> pass("convert-std-to-llvm", "Convert scalar and vector operations from the " "Standard to the LLVM dialect", [] { return std::make_unique< LLVMLoweringPass >(clUseAlloca.getValue(), clUseBarePtrCallConv ? populateStdToLLVMBarePtrConversionPatterns :populateStdToLLVMConversionPatterns, clUseBarePtrCallConv ? makeStandardToLLVMBarePtrTypeConverter :makeStandardToLLVMTypeConverter);}) static
Referenced by mlir::createLowerToLLVMPass().