MLIR: include/mlir-c/Core.h File Reference
Core.h File Reference
#include <stdint.h>
Classes
struct int64_list_t
Simple C lists for non-owning mlir Opaque C types.
struct mlir_type_list_t
struct mlir_named_attr_t
struct mlir_named_attr_list_t
Typedefs
typedef void * mlir_context_t
Opaque MLIR types.
typedef const void * mlir_type_t
Opaque C type for mlir::Type.
typedef void * mlir_func_t
Opaque C type for mlir::FuncOp.
typedef const void * mlir_attr_t
Opaque C type for mlir::Attribute.
Functions
mlir_type_t makeMemRefType (mlir_context_t context, mlir_type_t elemType, int64_list_t sizes)
Minimal C API for exposing EDSCs to Swift, Python and other languages.
mlir_type_t makeFunctionType (mlir_context_t context, mlir_type_list_t inputs, mlir_type_list_t outputs)
Returns an mlir::FunctionType of the element type elemType and shape sizes.
mlir_type_t makeIndexType (mlir_context_t context)
Returns an mlir::IndexType.
mlir_attr_t makeIntegerAttr (mlir_type_t type, int64_t value)
Returns an mlir::IntegerAttr of the specified type that contains the given value.
mlir_attr_t makeBoolAttr (mlir_context_t context, bool value)
Returns an mlir::BoolAttr with the given value.
mlir_attr_t makeFloatAttr (mlir_context_t context, float value)
Returns an mlir::FloatAttr with the given value.
mlir_attr_t makeStringAttr (mlir_context_t context, const char *value)
Returns an mlir::StringAttr with the given value.
mlir_type_t mlirParseType (const char *type, mlir_context_t context, uint64_t *charsRead)
Parses an MLIR type from the string type in the given context.
unsigned getFunctionArity (mlir_func_t function)
Returns the arity of function.
unsigned getRankOfFunctionArgument (mlir_func_t function, unsigned pos)
Returns the rank of the function argument at position pos.
mlir_type_t getTypeOfFunctionArgument (mlir_func_t function, unsigned pos)
Returns an opaque mlir::Type of the function argument at position pos.
Typedef Documentation
mlir_attr_t
typedef const void* mlir_attr_t
Opaque C type for mlir::Attribute.
Definition at line 31 of file Core.h.
mlir_context_t
typedef void* mlir_context_t
Opaque MLIR types.
Opaque C type for mlir::MLIRContext*.
Definition at line 25 of file Core.h.
mlir_func_t
typedef void* mlir_func_t
Opaque C type for mlir::FuncOp.
Definition at line 29 of file Core.h.
mlir_type_t
typedef const void* mlir_type_t
Opaque C type for mlir::Type.
Definition at line 27 of file Core.h.
Function Documentation
getFunctionArity()
unsigned getFunctionArity (mlir_func_t function)
Returns the arity of function.
Definition at line 80 of file CoreAPIs.cpp.
References mlir::Op< FuncOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::Symbol, OpTrait::FunctionLike, CallableOpInterface::Trait >::getFromOpaquePointer().
getRankOfFunctionArgument()
unsigned getRankOfFunctionArgument (mlir_func_t function, unsigned pos)
Returns the rank of the function argument at position pos.
If the argument is of MemRefType, this returns the rank of the MemRef. Otherwise returns 0. TODO(ntv): support more than MemRefType and scalar Type.
getTypeOfFunctionArgument()
mlir_type_t getTypeOfFunctionArgument (mlir_func_t function, unsigned pos)
Returns an opaque mlir::Type of the function argument at position pos.
makeBoolAttr()
mlir_attr_t makeBoolAttr (mlir_context_t context, bool value)
Returns an mlir::BoolAttr with the given value.
Definition at line 62 of file CoreAPIs.cpp.
References mlir::BoolAttr::get().
makeFloatAttr()
mlir_attr_t makeFloatAttr (mlir_context_t context, float value)
Returns an mlir::FloatAttr with the given value.
Definition at line 68 of file CoreAPIs.cpp.
References mlir::FloatAttr::get(), and mlir::FloatType::getF32().
makeFunctionType()
mlir_type_t makeFunctionType (mlir_context_t context, mlir_type_list_t inputs, mlir_type_list_t outputs)
Returns an mlir::FunctionType of the element type elemType and shape sizes.
Definition at line 36 of file CoreAPIs.cpp.
References mlir::FunctionType::get(), mlir::Type::getFromOpaquePointer(), mlir_type_list_t::n, and mlir_type_list_t::types.
makeIndexType()
mlir_type_t makeIndexType (mlir_context_t context)
Returns an mlir::IndexType.
Definition at line 50 of file CoreAPIs.cpp.
References mlir::IndexType::get().
makeIntegerAttr()
mlir_attr_t makeIntegerAttr (mlir_type_t type, int64_t value)
Returns an mlir::IntegerAttr of the specified type that contains the given value.
Definition at line 56 of file CoreAPIs.cpp.
References mlir::IntegerAttr::get(), and mlir::Type::getFromOpaquePointer().
makeMemRefType()
mlir_type_t makeMemRefType (mlir_context_t context, mlir_type_t elemType, int64_list_t sizes)
Minimal C API for exposing EDSCs to Swift, Python and other languages.
Returns an mlir::MemRefType of the element type elemType and shape sizes.
Definition at line 25 of file CoreAPIs.cpp.
References mlir::MemRefType::get(), mlir::Type::getFromOpaquePointer(), int64_list_t::n, and int64_list_t::values.
makeStringAttr()
mlir_attr_t makeStringAttr (mlir_context_t context, const char * value)
Returns an mlir::StringAttr with the given value.
Definition at line 74 of file CoreAPIs.cpp.
References mlir::StringAttr::get().
mlirParseType()
mlir_type_t mlirParseType (const char * type, mlir_context_t context, uint64_t * charsRead)
Parses an MLIR type from the string type in the given context.
Returns a NULL type on error. If non-NULL, charsRead will contain the number of characters that were processed by the parser.
Definition at line 85 of file CoreAPIs.cpp.
References mlir::Type::getAsOpaquePointer(), and mlir::parseType().