MLIR: lib/Dialect/SPIRV/Transforms/DecorateSPIRVCompositeTypeLayoutPass.cpp File Reference
DecorateSPIRVCompositeTypeLayoutPass.cpp File Reference
#include "mlir/Dialect/SPIRV/LayoutUtils.h"
#include "mlir/Dialect/SPIRV/Passes.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static void populateSPIRVLayoutInfoPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Variables
static PassRegistration< DecorateSPIRVCompositeTypeLayoutPass > pass ("decorate-spirv-composite-type-layout", "Decorate SPIR-V composite type with layout info")
Function Documentation
populateSPIRVLayoutInfoPatterns()
static void populateSPIRVLayoutInfoPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx) static
Definition at line 75 of file DecorateSPIRVCompositeTypeLayoutPass.cpp.
References mlir::applyFullConversion(), mlir::failed(), mlir::OwningRewritePatternList::insert(), and mlir::VulkanLayoutUtils::isLegalType().
Variable Documentation
pass
PassRegistration<DecorateSPIRVCompositeTypeLayoutPass> pass("decorate-spirv-composite-type-layout", "Decorate SPIR-V composite type with layout info") static
Referenced by mlir::spirv::createDecorateSPIRVCompositeTypeLayoutPass().