MLIR: lib/Dialect/Linalg/Analysis/DependenceAnalysis.cpp File Reference
DependenceAnalysis.cpp File Reference
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "linalg-dependence-analysis"
Functions
static StringRef toStringRef (LinalgDependenceGraph::DependenceType dt)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-dependence-analysis"
Definition at line 20 of file DependenceAnalysis.cpp.
Function Documentation
toStringRef()
static StringRef toStringRef (LinalgDependenceGraph::DependenceType dt) static
Definition at line 28 of file DependenceAnalysis.cpp.
References mlir::Value::getDefiningOp(), mlir::Value::isa(), and mlir::isStrided().
Referenced by mlir::linalg::LinalgDependenceGraph::findCoveringReads(), and mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraph().