MLIR: lib/Dialect/Linalg/Utils/Utils.cpp File Reference
Utils.cpp File Reference
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/EDSC/Helpers.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/STLExtras.h"
#include "mlir/Transforms/FoldUtils.h"
Functions
static Value emitOrFoldComposedAffineApply (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > operandsRef, OperationFolder *folder)
Function Documentation
emitOrFoldComposedAffineApply()
static Value emitOrFoldComposedAffineApply (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > operandsRef, OperationFolder * folder) static
Definition at line 32 of file Utils.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::OperationFolder::create(), mlir::fullyComposeAffineMapAndOperands(), and mlir::functional::map().
Referenced by mlir::linalg::applyMapToValues().