MLIR: lib/Transforms/DialectConversion.cpp File Reference
DialectConversion.cpp File Reference
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Module.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Debug.h"
Classes
struct mlir::detail::ConversionPatternRewriterImpl
struct mlir::detail::ConversionPatternRewriterImpl::OpReplacement
This class represents one requested operation replacement via 'replaceOp'.
struct mlir::detail::ConversionPatternRewriterImpl::BlockPosition
Original position of the given block in its parent region.
struct mlir::detail::ConversionPatternRewriterImpl::BlockAction
The storage class for an undoable block action (one of BlockActionKind), contains the information necessary to undo this action.
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::detail
Utilities for detecting if a given trait holds for some set of arguments 'Args'.
Macros
#define DEBUG_TYPE "dialect-conversion"
Enumerations
enum OpConversionMode
Functions
static LogicalResult computeConversionSet (iterator_range< Region::iterator > region, Location regionLoc, std::vector< Operation *> &toConvert, ConversionTarget *target=nullptr)
Recursively collect all of the operations to convert from within 'region'.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dialect-conversion"
Definition at line 23 of file DialectConversion.cpp.
Enumeration Type Documentation
OpConversionMode
enum OpConversionMode
Definition at line 1394 of file DialectConversion.cpp.
Function Documentation
computeConversionSet()
static LogicalResult computeConversionSet (iterator_range< Region::iterator > region, Location regionLoc, std::vector< Operation *> & toConvert, ConversionTarget * target = nullptr) static
Recursively collect all of the operations to convert from within 'region'.
If 'target' is nonnull, operations that are recursively legal have their regions pre-filtered to avoid considering them for legalization.
Definition at line 29 of file DialectConversion.cpp.
References mlir::Block::addArguments(), mlir::Block::begin(), mlir::IRObjectWithUseList< OperandType >::dropAllUses(), mlir::Value::dropAllUses(), mlir::emitError(), mlir::Block::end(), mlir::detail::enumerate(), mlir::Block::erase(), mlir::Operation::erase(), mlir::Block::getArgument(), mlir::Block::getArguments(), mlir::Operation::getAttrList(), mlir::Region::getBlocks(), mlir::TypeConverter::SignatureConversion::getConvertedTypes(), mlir::Value::getDefiningOp(), mlir::TypeConverter::SignatureConversion::getInputMapping(), mlir::Operation::getLoc(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::Region::getParentOp(), mlir::Operation::getRegions(), mlir::Operation::getResult(), mlir::Block::getSuccessors(), mlir::BlockArgument::getType(), mlir::Builder::getUnknownLoc(), mlir::functional::map(), mlir::Block::moveBefore(), mlir::StandardTypes::None, mlir::Operation::operand_begin(), mlir::Operation::operand_end(), mlir::IRObjectWithUseList< OperandType >::replaceAllUsesWith(), mlir::Value::replaceAllUsesWith(), mlir::Operation::setAttrs(), mlir::Operation::setLoc(), mlir::Operation::setOperands(), mlir::Operation::setSuccessor(), mlir::Block::splitBlock(), mlir::success(), mlir::Operation::successor_begin(), mlir::Operation::successor_end(), and mlir::Value::use_empty().
Referenced by mlir::detail::ConversionPatternRewriterImpl::notifyRegionWasClonedBefore().