MLIR: lib/EDSC/Builders.cpp File Reference
Builders.cpp File Reference
#include "mlir/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/AffineExpr.h"
#include "llvm/ADT/Optional.h"
Functions
static Optional< ValueHandle > emitStaticFor (ArrayRef< ValueHandle > lbs, ArrayRef< ValueHandle > ubs, int64_t step)
template<typename Op >
static ValueHandle createBinaryHandle (ValueHandle lhs, ValueHandle rhs)
static std::pair< AffineExpr, Value > categorizeValueByAffineType (MLIRContext *context, Value val, unsigned &numDims, unsigned &numSymbols)
static ValueHandle createBinaryIndexHandle (ValueHandle lhs, ValueHandle rhs, function_ref< AffineExpr(AffineExpr, AffineExpr)> affCombiner)
template<typename IOp , typename FOp >
static ValueHandle createBinaryHandle (ValueHandle lhs, ValueHandle rhs, function_ref< AffineExpr(AffineExpr, AffineExpr)> affCombiner)
static ValueHandle createIComparisonExpr (CmpIPredicate predicate, ValueHandle lhs, ValueHandle rhs)
static ValueHandle createFComparisonExpr (CmpFPredicate predicate, ValueHandle lhs, ValueHandle rhs)
Function Documentation
categorizeValueByAffineType()
static std::pair<AffineExpr, Value> categorizeValueByAffineType (MLIRContext * context, Value val, unsigned & numDims, unsigned & numSymbols) static
Definition at line 337 of file Builders.cpp.
References mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::Value::getDefiningOp(), mlir::edsc::ValueHandle::getValue(), mlir::isValidDim(), and mlir::isValidSymbol().
Referenced by createBinaryIndexHandle().
createBinaryHandle() [1/2]
template<typename Op > static ValueHandle createBinaryHandle (ValueHandle lhs, ValueHandle rhs) static
Definition at line 332 of file Builders.cpp.
References mlir::edsc::ValueHandle::getValue().
createBinaryHandle() [2/2]
template<typename IOp , typename FOp > static ValueHandle createBinaryHandle (ValueHandle lhs, ValueHandle rhs, function_ref< AffineExpr(AffineExpr, AffineExpr)> affCombiner) static
Definition at line 377 of file Builders.cpp.
References createBinaryIndexHandle(), mlir::Value::getType(), and mlir::edsc::ValueHandle::getValue().
createBinaryIndexHandle()
static ValueHandle createBinaryIndexHandle (ValueHandle lhs, ValueHandle rhs, function_ref< AffineExpr(AffineExpr, AffineExpr)> affCombiner) static
Definition at line 353 of file Builders.cpp.
References categorizeValueByAffineType(), mlir::edsc::ValueHandle::createComposedAffineApply(), mlir::AffineMap::get(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ValueHandle::getValue(), and mlir::functional::map().
Referenced by mlir::edsc::op::ceilDiv(), createBinaryHandle(), and mlir::edsc::op::floorDiv().
createFComparisonExpr()
static ValueHandle createFComparisonExpr (CmpFPredicate predicate, ValueHandle lhs, ValueHandle rhs) static
Definition at line 468 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getLocation(), mlir::edsc::ValueHandle::getType(), and mlir::edsc::ValueHandle::getValue().
Referenced by mlir::edsc::op::operator!=(), mlir::edsc::op::operator<(), mlir::edsc::op::operator<=(), mlir::edsc::op::operator==(), mlir::edsc::op::operator>(), and mlir::edsc::op::operator>=().
createIComparisonExpr()
static ValueHandle createIComparisonExpr (CmpIPredicate predicate, ValueHandle lhs, ValueHandle rhs) static
Definition at line 453 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getLocation(), mlir::edsc::ValueHandle::getType(), and mlir::edsc::ValueHandle::getValue().
Referenced by mlir::edsc::op::operator!=(), mlir::edsc::op::operator<(), mlir::edsc::op::operator<=(), mlir::edsc::op::operator==(), mlir::edsc::op::operator>(), and mlir::edsc::op::operator>=().
emitStaticFor()
static Optional<ValueHandle> emitStaticFor (ArrayRef< ValueHandle > lbs, ArrayRef< ValueHandle > ubs, int64_t step) static
Definition at line 152 of file Builders.cpp.
Referenced by mlir::edsc::LoopBuilder::makeAffine().