MLIR: lib/ExecutionEngine/ExecutionEngine.cpp File Reference
ExecutionEngine.cpp File Reference
#include "mlir/ExecutionEngine/ExecutionEngine.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Module.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Target/LLVMIR.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/ExecutionEngine/ObjectCache.h"
#include "llvm/ExecutionEngine/Orc/CompileUtils.h"
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
#include "llvm/ExecutionEngine/Orc/IRCompileLayer.h"
#include "llvm/ExecutionEngine/Orc/IRTransformLayer.h"
#include "llvm/ExecutionEngine/Orc/JITTargetMachineBuilder.h"
#include "llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h"
#include "llvm/ExecutionEngine/SectionMemoryManager.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/ToolOutputFile.h"
Macros
#define DEBUG_TYPE "execution-engine"
Functions
static Error make_string_error (const Twine &message)
Wrap a string into an llvm::StringError.
static std::string makePackedFunctionName (StringRef name)
static void packFunctionArguments (Module *module)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "execution-engine"
Definition at line 35 of file ExecutionEngine.cpp.
Function Documentation
make_string_error()
static Error make_string_error (const Twine & message) static
Wrap a string into an llvm::StringError.
Definition at line 58 of file ExecutionEngine.cpp.
References mlir::Error.
Referenced by mlir::ExecutionEngine::create(), and mlir::ExecutionEngine::lookup().
makePackedFunctionName()
static std::string makePackedFunctionName (StringRef name) static
Definition at line 118 of file ExecutionEngine.cpp.
Referenced by mlir::ExecutionEngine::lookup(), and packFunctionArguments().
packFunctionArguments()
static void packFunctionArguments (Module * module) static
Definition at line 125 of file ExecutionEngine.cpp.
References mlir::detail::enumerate(), and makePackedFunctionName().
Referenced by mlir::ExecutionEngine::create().