MLIR: lib/IR/FunctionImplementation.cpp File Reference
FunctionImplementation.cpp File Reference
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/FunctionSupport.h"
#include "mlir/IR/SymbolTable.h"
Functions
static ParseResult parseArgumentList (OpAsmParser &parser, bool allowVariadic, SmallVectorImpl< Type > &argTypes, SmallVectorImpl< OpAsmParser::OperandType > &argNames, SmallVectorImpl< SmallVector< NamedAttribute, 2 >> &argAttrs, bool &isVariadic)
static ParseResult parseFunctionResultList (OpAsmParser &parser, SmallVectorImpl< Type > &resultTypes, SmallVectorImpl< SmallVector< NamedAttribute, 2 >> &resultAttrs)
Parse a function result list.
static void printFunctionResultList (OpAsmPrinter &p, ArrayRef< Type > types, ArrayRef< ArrayRef< NamedAttribute >> attrs)
Function Documentation
parseArgumentList()
static ParseResult parseArgumentList (OpAsmParser & parser, bool allowVariadic, SmallVectorImpl< Type > & argTypes, SmallVectorImpl< OpAsmParser::OperandType > & argNames, SmallVectorImpl< SmallVector< NamedAttribute, 2 >> & argAttrs, bool & isVariadic) static
Definition at line 17 of file FunctionImplementation.cpp.
References mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OpAsmParser::OperandType::name, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalEllipsis(), mlir::OpAsmParser::parseOptionalRegionArgument(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseType(), mlir::succeeded(), and mlir::success().
Referenced by mlir::impl::parseFunctionSignature().
parseFunctionResultList()
static ParseResult parseFunctionResultList (OpAsmParser & parser, SmallVectorImpl< Type > & resultTypes, SmallVectorImpl< SmallVector< NamedAttribute, 2 >> & resultAttrs) static
Parse a function result list.
function-result-list ::= function-result-list-parens | non-function-type function-result-list-parens ::= () | (function-result-list-no-parens) function-result-list-no-parens ::= function-result (, function-result)* function-result ::= type attribute-dict?
Definition at line 93 of file FunctionImplementation.cpp.
References mlir::failed(), mlir::failure(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseType(), mlir::succeeded(), and mlir::success().
Referenced by mlir::impl::parseFunctionSignature().
printFunctionResultList()
static void printFunctionResultList (OpAsmPrinter & p, ArrayRef< Type > types, ArrayRef< ArrayRef< NamedAttribute >> attrs) static
Definition at line 211 of file FunctionImplementation.cpp.
References mlir::OpAsmPrinter::getStream(), mlir::interleaveComma(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printType().
Referenced by mlir::impl::printFunctionSignature().