MLIR: lib/Dialect/Linalg/Transforms/Fusion.cpp File Reference
Fusion.cpp File Reference
#include "mlir/Analysis/Dominance.h"
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/EDSC/Helpers.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/STLExtras.h"
#include "mlir/Transforms/FoldUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Classes
struct ViewDimension
Macros
#define DEBUG_TYPE "linalg-fusion"
Functions
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options")
Implements a simple high-level fusion pass of linalg library operations.
static llvm::cl::list< unsigned > clTileSizes ("linalg-fusion-tile-sizes", llvm::cl::desc("Tile sizes by which to tile linalg operations during linalg fusion"), llvm::cl::ZeroOrMore, llvm::cl::MiscFlags::CommaSeparated, llvm::cl::cat(clOptionsCategory))
static LinalgOp cloneWithLoopRanges (OpBuilder &b, Location loc, LinalgOp op, ArrayRef< SubViewOp::Range > loopRanges)
static ViewDimension getViewDefiningLoopRange (LinalgOp op, unsigned loopDepth)
static LinalgOp fuse (Value producedView, LinalgOp producer, LinalgOp consumer, unsigned consumerIdx, unsigned producerIdx, OperationFolder *folder)
static bool isStructurallyFusableProducer (LinalgOp producer, Value consumedView, LinalgOp consumer)
static void fuseLinalgOpsGreedily (FuncOp f)
Variables
static PassRegistration< LinalgFusionPass > pass ("linalg-fusion", "Fuse operations in the linalg dialect")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-fusion"
Definition at line 31 of file Fusion.cpp.
Function Documentation
cloneWithLoopRanges()
static LinalgOp cloneWithLoopRanges (OpBuilder & b, Location loc, LinalgOp op, ArrayRef< SubViewOp::Range > loopRanges) static
Definition at line 66 of file Fusion.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::linalg::getAssumedNonViewOperands(), mlir::linalg::loopToOperandRangesMaps(), and mlir::functional::map().
Referenced by fuse().
clOptionsCategory()
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options") static
Implements a simple high-level fusion pass of linalg library operations.
In each block, linalg ops are processed in reverse textual order. Given a linalg op O, fusion occurs by:
inspecting the linalg ops that write into the views read by O. This uses the SSA value of the views and a simple subview/slice analysis to determine producer-consumer dependences;
greedily fuse the linalg ops that produce subview
inspect the fused ops and determine whether they have other remaining LinalgOp uses. If not, then erase the original producing linalg op.
More advanced use cases, analyses as well as profitability heuristics are left for future work.
clTileSizes()
static llvm::cl::list<unsigned> clTileSizes ("linalg-fusion-tile-sizes" , llvm::cl::desc("Tile sizes by which to tile linalg operations during linalg fusion") , llvm::cl::ZeroOrMore , llvm::cl::MiscFlags::CommaSeparated , llvm::cl::cat(clOptionsCategory)) static
fuse()
static LinalgOp fuse (Value producedView, LinalgOp producer, LinalgOp consumer, unsigned consumerIdx, unsigned producerIdx, OperationFolder * folder) static
Definition at line 144 of file Fusion.cpp.
References cloneWithLoopRanges(), mlir::detail::enumerate(), mlir::AffineMap::getResults(), getViewDefiningLoopRange(), mlir::linalg::loopToOperandRangesMaps(), and mlir::linalg::Range.
Referenced by mlir::linalg::fuseProducerOf().
fuseLinalgOpsGreedily()
static void fuseLinalgOpsGreedily (FuncOp f) static
Definition at line 321 of file Fusion.cpp.
References mlir::linalg::fuseProducerOf(), mlir::OpState::getContext(), mlir::FuncOp::print(), and mlir::OpState::walk().
getViewDefiningLoopRange()
static ViewDimension getViewDefiningLoopRange (LinalgOp op, unsigned loopDepth) static
Definition at line 119 of file Fusion.cpp.
References mlir::detail::enumerate(), mlir::linalg::loopToOperandRangesMaps(), and mlir::functional::map().
Referenced by fuse().
isStructurallyFusableProducer()
static bool isStructurallyFusableProducer (LinalgOp producer, Value consumedView, LinalgOp consumer) static
Definition at line 202 of file Fusion.cpp.
Referenced by mlir::linalg::isProducerLastWriteOfView().
Variable Documentation
pass
PassRegistration<LinalgFusionPass> pass("linalg-fusion", "Fuse operations in the linalg dialect") static
Referenced by mlir::createLinalgFusionPass().