MLIR: lib/EDSC/Helpers.cpp File Reference
Helpers.cpp File Reference
#include "mlir/EDSC/Helpers.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/AffineExpr.h"
Functions
static SmallVector< ValueHandle, 8 > getMemRefSizes (Value memRef)
Function Documentation
getMemRefSizes()
static SmallVector<ValueHandle, 8> getMemRefSizes (Value memRef) static
Definition at line 16 of file Helpers.cpp.
References mlir::Type::cast(), mlir::MemRefType::getShape(), mlir::Value::getType(), and mlir::isStrided().
Referenced by mlir::edsc::MemRefView::MemRefView().