MLIR: lib/Quantizer/Transforms/InferQuantizedTypesPass.cpp File Reference
InferQuantizedTypesPass.cpp File Reference
#include "mlir/Dialect/QuantOps/QuantOps.h"
#include "mlir/Dialect/QuantOps/QuantTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/Quantizer/Configurations/FxpMathConfig.h"
#include "mlir/Quantizer/Support/Configuration.h"
#include "mlir/Quantizer/Support/ConstraintAnalysisGraph.h"
#include "mlir/Quantizer/Support/ConstraintAnalysisGraphTraits.h"
#include "mlir/Quantizer/Transforms/Passes.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/Support/DOTGraphTraits.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct llvm::DOTGraphTraits< const CAGSlice * >
Namespaces
llvm
Functions
static LogicalResult validateTypeConversion (Type newType, Type origType, Operation *op)
Variables
static const int kMaximumPropagationRounds = 1000
Maximum number of propagation rounds to run to converge the CAG before signalling an error.
static PassRegistration< InferQuantizedTypesPass > pass ("quantizer-infer-quantized-types", "Infers quantized types for a module")
Function Documentation
validateTypeConversion()
static LogicalResult validateTypeConversion (Type newType, Type origType, Operation * op) static
Definition at line 99 of file InferQuantizedTypesPass.cpp.
References mlir::quantizer::FxpMathTargetConfig::create(), mlir::quantizer::CAGAnchorNode::Direct, mlir::quantizer::CAGAnchorNode::DirectStorage, mlir::emitError(), mlir::Operation::emitOpError(), mlir::quantizer::CAGAnchorNode::ExpressedOnly, mlir::failed(), mlir::quantizer::TargetConfiguration::finalizeAnchors(), mlir::UnknownLoc::get(), mlir::Operation::getBlock(), mlir::quantizer::SolverContext::getDebugCAGDotPath(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::quantizer::CAGOperandAnchor::getOp(), mlir::quantizer::CAGOperandAnchor::getOperandIdx(), mlir::quantizer::CAGAnchorNode::getOriginalType(), mlir::quantizer::CAGAnchorNode::getTypeTransformRule(), mlir::quantizer::CAGOperandAnchor::getValue(), mlir::quantizer::CAGResultAnchor::getValue(), mlir::quantizer::TargetConfiguration::handleOp(), kMaximumPropagationRounds, mlir::quantizer::CAGSlice::propagate(), mlir::Value::replaceAllUsesWith(), mlir::Operation::setOperand(), mlir::Value::setType(), and mlir::success().
Variable Documentation
kMaximumPropagationRounds
const int kMaximumPropagationRounds = 1000 static
Maximum number of propagation rounds to run to converge the CAG before signalling an error.
Definition at line 97 of file InferQuantizedTypesPass.cpp.
Referenced by validateTypeConversion().
pass
PassRegistration<InferQuantizedTypesPass> pass("quantizer-infer-quantized-types", "Infers quantized types for a module") static
Referenced by mlir::quantizer::createInferQuantizedTypesPass().