MLIR: lib/Transforms/Inliner.cpp File Reference
Inliner.cpp File Reference
#include "mlir/Analysis/CallGraph.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Parallel.h"
Macros
#define DEBUG_TYPE "inlining"
Functions
static llvm::cl::opt< bool > disableCanonicalization ("mlir-disable-inline-simplify", llvm::cl::desc("Disable running simplifications during inlining"), llvm::cl::ReallyHidden, llvm::cl::init(false))
static llvm::cl::opt< unsigned > maxInliningIterations ("mlir-max-inline-iterations", llvm::cl::desc("Maximum number of iterations when inlining within an SCC"), llvm::cl::ReallyHidden, llvm::cl::init(4))
static void runTransformOnCGSCCs (const CallGraph &cg, function_ref< void(ArrayRef< CallGraphNode *>)> sccTransformer)
Run a given transformation over the SCCs of the callgraph in a bottom up traversal.
static void collectCallOps (iterator_range< Region::iterator > blocks, CallGraph &cg, SmallVectorImpl< ResolvedCall > &calls, bool traverseNestedCGNodes)
Collect all of the callable operations within the given range of blocks.
static bool shouldInline (ResolvedCall &resolvedCall)
Returns true if the given call should be inlined.
static LogicalResult inlineCallsInSCC (Inliner &inliner, ArrayRef< CallGraphNode *> currentSCC)
Attempt to inline calls within the given scc.
static void canonicalizeSCC (CallGraph &cg, ArrayRef< CallGraphNode *> currentSCC, MLIRContext *context, const OwningRewritePatternList &canonPatterns)
Canonicalize the nodes within the given SCC with the given set of canonicalization patterns.
static void inlineSCC (Inliner &inliner, ArrayRef< CallGraphNode *> currentSCC, MLIRContext *context, const OwningRewritePatternList &canonPatterns)
Attempt to inline calls within the given scc, and run canonicalizations with the given patterns, until a fixed point is reached.
Variables
static PassRegistration< InlinerPass > pass ("inline", "Inline function calls")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inlining"
Definition at line 26 of file Inliner.cpp.
Function Documentation
canonicalizeSCC()
static void canonicalizeSCC (CallGraph & cg, ArrayRef< CallGraphNode *> currentSCC, MLIRContext * context, const OwningRewritePatternList & canonPatterns) static
Canonicalize the nodes within the given SCC with the given set of canonicalization patterns.
Definition at line 202 of file Inliner.cpp.
References mlir::applyPatternsGreedily(), mlir::ParallelDiagnosticHandler::eraseOrderIDForThread(), and mlir::ParallelDiagnosticHandler::setOrderIDForThread().
Referenced by inlineSCC().
collectCallOps()
static void collectCallOps (iterator_range< Region::iterator > blocks, CallGraph & cg, SmallVectorImpl< ResolvedCall > & calls, bool traverseNestedCGNodes) static
Collect all of the callable operations within the given range of blocks.
If traverseNestedCGNodes is true, this will also collect call operations inside of nested callgraph nodes.
Definition at line 76 of file Inliner.cpp.
References mlir::CallGraphNode::isExternal(), mlir::CallGraph::lookupNode(), and mlir::CallGraph::resolveCallable().
Referenced by inlineCallsInSCC().
disableCanonicalization()
static llvm::cl::opt<bool> disableCanonicalization ("mlir-disable-inline-simplify" , llvm::cl::desc("Disable running simplifications during inlining") , llvm::cl::ReallyHidden , llvm::cl::init(false)) static
Referenced by inlineSCC().
inlineCallsInSCC()
static LogicalResult inlineCallsInSCC (Inliner & inliner, ArrayRef< CallGraphNode *> currentSCC) static
Attempt to inline calls within the given scc.
This function returns success if any calls were inlined, failure otherwise.
Definition at line 156 of file Inliner.cpp.
References collectCallOps(), mlir::failed(), mlir::failure(), mlir::Region::getParentOp(), mlir::inlineCall(), shouldInline(), and mlir::success().
Referenced by inlineSCC().
inlineSCC()
static void inlineSCC (Inliner & inliner, ArrayRef< CallGraphNode *> currentSCC, MLIRContext * context, const OwningRewritePatternList & canonPatterns) static
Attempt to inline calls within the given scc, and run canonicalizations with the given patterns, until a fixed point is reached.
This allows for the inlining of newly devirtualized calls.
Definition at line 255 of file Inliner.cpp.
References canonicalizeSCC(), disableCanonicalization(), mlir::Operation::emitOpError(), mlir::Operation::hasTrait(), inlineCallsInSCC(), maxInliningIterations(), runTransformOnCGSCCs(), and mlir::succeeded().
maxInliningIterations()
static llvm::cl::opt<unsigned> maxInliningIterations ("mlir-max-inline-iterations" , llvm::cl::desc("Maximum number of iterations when inlining within an SCC") , llvm::cl::ReallyHidden , llvm::cl::init(4)) static
Referenced by inlineSCC().
runTransformOnCGSCCs()
static void runTransformOnCGSCCs (const CallGraph & cg, function_ref< void(ArrayRef< CallGraphNode *>)> sccTransformer) static
Run a given transformation over the SCCs of the callgraph in a bottom up traversal.
Definition at line 46 of file Inliner.cpp.
Referenced by inlineSCC().
shouldInline()
static bool shouldInline (ResolvedCall & resolvedCall) static
Returns true if the given call should be inlined.
Definition at line 138 of file Inliner.cpp.
Referenced by inlineCallsInSCC().
Variable Documentation
pass
PassRegistration<InlinerPass> pass("inline", "Inline function calls") static
Referenced by mlir::createInlinerPass().