MLIR: lib/Support/JitRunner.cpp File Reference
JitRunner.cpp File Reference
#include "mlir/Support/JitRunner.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/ExecutionEngine/ExecutionEngine.h"
#include "mlir/ExecutionEngine/OptUtils.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ExecutionEngine/Orc/JITTargetMachineBuilder.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassNameParser.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/ToolOutputFile.h"
#include <numeric>
Functions
static llvm::cl::opt< std::string > inputFilename (llvm::cl::Positional, llvm::cl::desc("<input file>"), llvm::cl::init("-"))
static llvm::cl::opt< std::string > mainFuncName ("e", llvm::cl::desc("The function to be called"), llvm::cl::value_desc("<function name>"), llvm::cl::init("main"))
static llvm::cl::opt< std::string > mainFuncType ("entry-point-result", llvm::cl::desc("Textual description of the function type to be called"), llvm::cl::value_desc("f32 | void"), llvm::cl::init("f32"))
static llvm::cl::OptionCategory optFlags ("opt-like flags")
static llvm::cl::list< const llvm::PassInfo *, bool, llvm::PassNameParser > llvmPasses (llvm::cl::desc("LLVM optimizing passes to run"), llvm::cl::cat(optFlags))
static llvm::cl::opt< bool > optO0 ("O0", llvm::cl::desc("Run opt passes and codegen at O0"), llvm::cl::cat(optFlags))
static llvm::cl::opt< bool > optO1 ("O1", llvm::cl::desc("Run opt passes and codegen at O1"), llvm::cl::cat(optFlags))
static llvm::cl::opt< bool > optO2 ("O2", llvm::cl::desc("Run opt passes and codegen at O2"), llvm::cl::cat(optFlags))
static llvm::cl::opt< bool > optO3 ("O3", llvm::cl::desc("Run opt passes and codegen at O3"), llvm::cl::cat(optFlags))
static llvm::cl::OptionCategory clOptionsCategory ("linking options")
static llvm::cl::list< std::string > clSharedLibs ("shared-libs", llvm::cl::desc("Libraries to link dynamically"), llvm::cl::ZeroOrMore, llvm::cl::MiscFlags::CommaSeparated, llvm::cl::cat(clOptionsCategory))
static llvm::cl::opt< bool > dumpObjectFile ("dump-object-file", llvm::cl::desc("Dump JITted-compiled object to file specified with " "-object-filename (<input file>.o by default)."))
static llvm::cl::opt< std::string > objectFilename ("object-filename", llvm::cl::desc("Dump JITted-compiled object to file <input file>.o"))
static OwningModuleRef parseMLIRInput (StringRef inputFilename, MLIRContext *context)
static void initializeLLVM ()
static Error make_string_error (const Twine &message)
static Optional< unsigned > getCommandLineOptLevel ()
static Error compileAndExecute (ModuleOp module, StringRef entryPoint, std::function< llvm::Error(llvm::Module *)> transformer, void **args)
static Error compileAndExecuteVoidFunction (ModuleOp module, StringRef entryPoint, std::function< llvm::Error(llvm::Module *)> transformer)
static Error compileAndExecuteSingleFloatReturnFunction (ModuleOp module, StringRef entryPoint, std::function< llvm::Error(llvm::Module *)> transformer)
Function Documentation
clOptionsCategory()
static llvm::cl::OptionCategory clOptionsCategory ("linking options") static
clSharedLibs()
static llvm::cl::list<std::string> clSharedLibs ("shared-libs" , llvm::cl::desc("Libraries to link dynamically") , llvm::cl::ZeroOrMore , llvm::cl::MiscFlags::CommaSeparated , llvm::cl::cat(clOptionsCategory)) static
Referenced by compileAndExecute().
compileAndExecute()
static Error compileAndExecute (ModuleOp module, StringRef entryPoint, std::function< llvm::Error(llvm::Module *)> transformer, void ** args) static
Definition at line 139 of file JitRunner.cpp.
References clSharedLibs(), mlir::ExecutionEngine::create(), dumpObjectFile(), getCommandLineOptLevel(), inputFilename(), objectFilename(), and mlir::success().
Referenced by compileAndExecuteSingleFloatReturnFunction(), and compileAndExecuteVoidFunction().
compileAndExecuteSingleFloatReturnFunction()
static Error compileAndExecuteSingleFloatReturnFunction (ModuleOp module, StringRef entryPoint, std::function< llvm::Error(llvm::Module *)> transformer) static
Definition at line 177 of file JitRunner.cpp.
References compileAndExecute(), compileAndExecuteVoidFunction(), mlir::Error, mlir::failed(), getCommandLineOptLevel(), initializeLLVM(), mlir::initializeLLVMPasses(), inputFilename(), mlir::JitRunnerMain(), llvmPasses(), mainFuncName(), mainFuncType(), make_string_error(), mlir::makeLLVMPassesTransformer, optFlags(), optO0(), optO1(), optO2(), optO3(), parseMLIRInput(), and mlir::success().
compileAndExecuteVoidFunction()
static Error compileAndExecuteVoidFunction (ModuleOp module, StringRef entryPoint, std::function< llvm::Error(llvm::Module *)> transformer) static
Definition at line 167 of file JitRunner.cpp.
References compileAndExecute(), mlir::Error, and make_string_error().
Referenced by compileAndExecuteSingleFloatReturnFunction().
dumpObjectFile()
static llvm::cl::opt<bool> dumpObjectFile ("dump-object-file" , llvm::cl::desc("Dump JITted-compiled object to file specified with " "-object-filename (<input file>.o by default).")) static
Referenced by compileAndExecute().
getCommandLineOptLevel()
static Optional<unsigned> getCommandLineOptLevel () static
Definition at line 121 of file JitRunner.cpp.
References mlir::Error, optFlags(), optO0(), optO1(), optO2(), and optO3().
Referenced by compileAndExecute(), and compileAndExecuteSingleFloatReturnFunction().
initializeLLVM()
static void initializeLLVM () static
Definition at line 111 of file JitRunner.cpp.
Referenced by compileAndExecuteSingleFloatReturnFunction().
inputFilename()
static llvm::cl::opt<std::string> inputFilename (llvm::cl::Positional , llvm::cl::desc("<input file>") , llvm::cl::init("-")) static
Referenced by compileAndExecute(), and compileAndExecuteSingleFloatReturnFunction().
llvmPasses()
static llvm::cl::list<const llvm::PassInfo *, bool, llvm::PassNameParser> llvmPasses (llvm::cl::desc("LLVM optimizing passes to run") , llvm::cl::cat(optFlags)) static
Referenced by compileAndExecuteSingleFloatReturnFunction(), and populatePassManagers().
mainFuncName()
static llvm::cl::opt<std::string> mainFuncName ("e" , llvm::cl::desc("The function to be called") , llvm::cl::value_desc("<function name>") , llvm::cl::init("main")) static
Referenced by compileAndExecuteSingleFloatReturnFunction().
mainFuncType()
static llvm::cl::opt<std::string> mainFuncType ("entry-point-result" , llvm::cl::desc("Textual description of the function type to be called") , llvm::cl::value_desc("f32 | void") , llvm::cl::init("f32")) static
Referenced by compileAndExecuteSingleFloatReturnFunction().
make_string_error()
static Error make_string_error (const Twine & message) inline static
Definition at line 116 of file JitRunner.cpp.
References mlir::Error.
Referenced by compileAndExecuteSingleFloatReturnFunction(), and compileAndExecuteVoidFunction().
objectFilename()
static llvm::cl::opt<std::string> objectFilename ("object-filename" , llvm::cl::desc("Dump JITted-compiled object to file <input file>.o")) static
Referenced by compileAndExecute().
optFlags()
static llvm::cl::OptionCategory optFlags ("opt-like flags") static
Referenced by compileAndExecuteSingleFloatReturnFunction(), and getCommandLineOptLevel().
optO0()
static llvm::cl::opt<bool> optO0 ("O0" , llvm::cl::desc("Run opt passes and codegen at O0") , llvm::cl::cat(optFlags)) static
Referenced by compileAndExecuteSingleFloatReturnFunction(), and getCommandLineOptLevel().
optO1()
static llvm::cl::opt<bool> optO1 ("O1" , llvm::cl::desc("Run opt passes and codegen at O1") , llvm::cl::cat(optFlags)) static
Referenced by compileAndExecuteSingleFloatReturnFunction(), and getCommandLineOptLevel().
optO2()
static llvm::cl::opt<bool> optO2 ("O2" , llvm::cl::desc("Run opt passes and codegen at O2") , llvm::cl::cat(optFlags)) static
Referenced by compileAndExecuteSingleFloatReturnFunction(), and getCommandLineOptLevel().
optO3()
static llvm::cl::opt<bool> optO3 ("O3" , llvm::cl::desc("Run opt passes and codegen at O3") , llvm::cl::cat(optFlags)) static
Referenced by compileAndExecuteSingleFloatReturnFunction(), and getCommandLineOptLevel().
parseMLIRInput()
static OwningModuleRef parseMLIRInput (StringRef inputFilename, MLIRContext * context) static
Definition at line 95 of file JitRunner.cpp.
References mlir::openInputFile(), and mlir::parseSourceFile().
Referenced by compileAndExecuteSingleFloatReturnFunction().