MLIR: lib/Dialect/GPU/Transforms/KernelOutlining.cpp File Reference
KernelOutlining.cpp File Reference
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/GPU/Passes.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Pass/Pass.h"
Functions
template<typename OpTy >
static void createForAllDimensions (OpBuilder &builder, Location loc, SmallVectorImpl< Value > &values)
static void injectGpuIndexOperations (Location loc, Region &body)
static bool isInliningBeneficiary (Operation *op)
static gpu::LaunchFuncOp inlineBeneficiaryOps (gpu::GPUFuncOp kernelFunc, gpu::LaunchFuncOp launch)
static gpu::GPUFuncOp outlineKernelFunc (gpu::LaunchOp launchOp)
static void convertToLaunchFuncOp (gpu::LaunchOp &launchOp, gpu::GPUFuncOp kernelFunc)
Variables
static PassRegistration< GpuKernelOutliningPass > pass ("gpu-kernel-outlining", "Outline gpu.launch bodies to kernel functions.")
Function Documentation
convertToLaunchFuncOp()
static void convertToLaunchFuncOp (gpu::LaunchOp & launchOp, gpu::GPUFuncOp kernelFunc) static
Definition at line 125 of file KernelOutlining.cpp.
References mlir::Operation::clone(), mlir::Operation::create(), mlir::OpBuilder::create(), mlir::UnitAttr::get(), mlir::gpu::GPUDialect::getContainerModuleAttrName(), mlir::SymbolTable::getSymbolUses(), inlineBeneficiaryOps(), mlir::SymbolTable::insert(), mlir::SymbolTable::lookup(), mlir::quantizer::modified(), and outlineKernelFunc().
createForAllDimensions()
template<typename OpTy > static void createForAllDimensions (OpBuilder & builder, Location loc, SmallVectorImpl< Value > & values) static
Definition at line 24 of file KernelOutlining.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIndexType(), and mlir::Builder::getStringAttr().
injectGpuIndexOperations()
static void injectGpuIndexOperations (Location loc, Region & body) static
Definition at line 36 of file KernelOutlining.cpp.
References mlir::Region::front(), and mlir::Attribute::getContext().
Referenced by outlineKernelFunc().
inlineBeneficiaryOps()
static gpu::LaunchFuncOp inlineBeneficiaryOps (gpu::GPUFuncOp kernelFunc, gpu::LaunchFuncOp launch) static
Definition at line 59 of file KernelOutlining.cpp.
References mlir::BlockAndValueMapping::contains(), isInliningBeneficiary(), mlir::functional::map(), and mlir::BlockAndValueMapping::map().
Referenced by convertToLaunchFuncOp().
isInliningBeneficiary()
static bool isInliningBeneficiary (Operation * op) static
Definition at line 53 of file KernelOutlining.cpp.
Referenced by inlineBeneficiaryOps().
outlineKernelFunc()
static gpu::GPUFuncOp outlineKernelFunc (gpu::LaunchOp launchOp) static
Definition at line 103 of file KernelOutlining.cpp.
References mlir::FunctionType::get(), mlir::gpu::GPUDialect::getKernelFuncAttrName(), and injectGpuIndexOperations().
Referenced by convertToLaunchFuncOp().
Variable Documentation
pass
PassRegistration<GpuKernelOutliningPass> pass("gpu-kernel-outlining", "Outline gpu.launch bodies to kernel functions.") static
Referenced by mlir::createGpuKernelOutliningPass().