MLIR: lib/Conversion/StandardToSPIRV/LegalizeStandardForSPIRV.cpp File Reference
LegalizeStandardForSPIRV.cpp File Reference
#include "mlir/Conversion/StandardToSPIRV/ConvertStandardToSPIRV.h"
#include "mlir/Conversion/StandardToSPIRV/ConvertStandardToSPIRVPass.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Pass/Pass.h"
Functions
static LogicalResult resolveSourceIndices (Location loc, PatternRewriter &rewriter, SubViewOp subViewOp, ValueRange indices, SmallVectorImpl< Value > &sourceIndices)
Given the 'indices' of an load/store operation where the memref is a result of a subview op, returns the indices w.r.t to the source memref of the subview op.
Variables
static PassRegistration< SPIRVLegalization > pass ("legalize-std-for-spirv", "Legalize standard ops for SPIR-V lowering")
Function Documentation
resolveSourceIndices()
static LogicalResult resolveSourceIndices (Location loc, PatternRewriter & rewriter, SubViewOp subViewOp, ValueRange indices, SmallVectorImpl< Value > & sourceIndices) static
Given the 'indices' of an load/store operation where the memref is a result of a subview op, returns the indices w.r.t to the source memref of the subview op.
For example
%0 = ... : memref<12x42xf32> %1 = subview %0[arg0, arg1][][stride1, stride2] : memref<12x42xf32> to memref<4x4xf32, offset=?, strides=[?, ?]> %2 = load %1[i1, i2] : memref<4x4xf32, offset=?, strides=[?, ?]>
could be folded into
%2 = load %0[arg0 + i1 * stride1][arg1 + i2 * stride2] : memref<12x42xf32>
Definition at line 61 of file LegalizeStandardForSPIRV.cpp.
References mlir::PatternRewriter::create(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::IndexType::get(), mlir::Builder::getContext(), mlir::Builder::getIntegerAttr(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), and mlir::success().
Variable Documentation
pass
PassRegistration<SPIRVLegalization> pass("legalize-std-for-spirv", "Legalize standard ops for SPIR-V lowering") static
Referenced by mlir::createLegalizeStdOpsForSPIRVLoweringPass().