MLIR: lib/Dialect/Linalg/IR/LinalgOps.cpp File Reference
LinalgOps.cpp File Reference
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Support/Functional.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOpsInterfaces.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgOps.cpp.inc"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::linalg
Macros
#define GET_OP_CLASSES
#define GET_OP_CLASSES
Functions
template<typename GenericOpType >
static void printGenericOp (OpAsmPrinter &p, GenericOpType op)
static void print (OpAsmPrinter &p, GenericOp op)
static void print (OpAsmPrinter &p, IndexedGenericOp op)
static ParseResult parseGenericOp (OpAsmParser &parser, OperationState &result)
template<typename GenericOpType >
static LogicalResult verifyBlockArgs (GenericOpType op, Block &block)
template<>
LogicalResult verifyBlockArgs (GenericOp op, Block &block)
template<>
LogicalResult verifyBlockArgs (IndexedGenericOp op, Block &block)
template<typename GenericOpType >
static LogicalResult verifyFuncArgs (GenericOpType op, FunctionType funType)
template<typename GenericOpType >
LogicalResult verifyFuncArgsGeneric (GenericOpType op, FunctionType funType)
template<>
LogicalResult verifyFuncArgs (GenericOp op, FunctionType funType)
template<>
LogicalResult verifyFuncArgs (IndexedGenericOp op, FunctionType funType)
template<typename GenericOpType >
static LogicalResult verifyGenericOp (GenericOpType op)
static LogicalResult verify (GenericOp op)
static LogicalResult verify (IndexedGenericOp op)
static void print (OpAsmPrinter &p, RangeOp op)
static ParseResult parseRangeOp (OpAsmParser &parser, OperationState &result)
static bool isReassociationValid (ArrayRef< AffineMap > reassociation, int *invalidIndex=nullptr)
Return true if the reassociation specification is valid, false otherwise.
static bool isReshapableDimBand (unsigned dim, unsigned extent, ArrayRef< int64_t > sizes, ArrayRef< AffineExpr > strides)
Detect whether memref dims [dim, dim + extent) can be reshaped without copies.
static MemRefType computeReshapeCollapsedType (MemRefType type, ArrayRef< AffineMap > reassociation)
Compute the MemRefType obtained by applying the reassociation (which is expected to be valid) to type.
static SmallVector< AffineMap, 4 > getAffineMaps (ArrayAttr attrs)
Helper functions assert Attribute of the proper type in attr and returns the corresponding vector.
template<typename AffineExprTy >
unsigned getMaxPosOfType (ArrayRef< ArrayRef< AffineExpr >> exprArrays)
static SmallVector< AffineMap, 4 > getSymbolLessAffineMaps (ArrayRef< ArrayRef< AffineExpr >> reassociation)
static void print (OpAsmPrinter &p, ReshapeOp op)
static ParseResult parseReshapeOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ReshapeOp op)
static void print (OpAsmPrinter &p, SliceOp op)
static ParseResult parseSliceOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (SliceOp op)
static void print (OpAsmPrinter &p, TransposeOp op)
static ParseResult parseTransposeOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, YieldOp op)
static ParseResult parseYieldOp (OpAsmParser &parser, OperationState &result)
template<typename GenericOpType >
static LogicalResult verifyYield (YieldOp op, GenericOpType genericOp)
static LogicalResult verify (YieldOp op)
static void printLinalgStructuredOp (OpAsmPrinter &p, Operation *op)
static ParseResult parseLinalgStructuredOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (FillOp op)
static LogicalResult verify (CopyOp op)
static LogicalResult verifyStrideOrDilation (ConvOp op, ArrayRef< Attribute > attrs, bool isStride)
static LogicalResult verify (ConvOp op)
static AffineMap extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext *context)
static SmallVector< AffineExpr, 4 > makeAffineDimExprs (unsigned num, unsigned &curIdx, MLIRContext *context)
static SmallVector< AffineExpr, 4 > weightedConvInputIndex (ConvOp op, ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
static SmallVector< AffineExpr, 4 > concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
static void appendMangledType (llvm::raw_string_ostream &ss, Type t)
static ArrayAttr getIndexingMaps (Operation *op)
Macro Definition Documentation
GET_OP_CLASSES [1/2]
#define GET_OP_CLASSES
Definition at line 877 of file LinalgOps.cpp.
GET_OP_CLASSES [2/2]
#define GET_OP_CLASSES
Definition at line 877 of file LinalgOps.cpp.
Function Documentation
appendMangledType()
static void appendMangledType (llvm::raw_string_ostream & ss, Type t) static
Definition at line 1019 of file LinalgOps.cpp.
References mlir::Type::dyn_cast(), mlir::interleave(), and mlir::Type::isIntOrIndexOrFloat().
Referenced by mlir::linalg::generateLibraryCallName().
computeReshapeCollapsedType()
static MemRefType computeReshapeCollapsedType (MemRefType type, ArrayRef< AffineMap > reassociation) static
Compute the MemRefType obtained by applying the reassociation (which is expected to be valid) to type.
If type is Contiguous MemRefType, this always produce a contiguous MemRefType.
Definition at line 387 of file LinalgOps.cpp.
References mlir::canonicalizeStridedLayout(), mlir::AffineExpr::dyn_cast(), mlir::MemRefType::get(), getAffineMaps(), mlir::MemRefType::getShape(), mlir::getStridesAndOffset(), isReassociationValid(), isReshapableDimBand(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::makeStridedLinearLayoutMap(), and mlir::succeeded().
Referenced by getSymbolLessAffineMaps(), and verify().
concat()
static SmallVector<AffineExpr, 4> concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b) static
Definition at line 915 of file LinalgOps.cpp.
Referenced by mlir::linalg::loopToOperandRangesMaps().
extractOrIdentityMap()
static AffineMap extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext * context) static
Definition at line 883 of file LinalgOps.cpp.
References mlir::StandardAttributes::AffineMap, and mlir::AffineMap::getMultiDimIdentityMap().
Referenced by mlir::linalg::loopToOperandRangesMaps().
getAffineMaps()
static SmallVector<AffineMap, 4> getAffineMaps (ArrayAttr attrs) static
Helper functions assert Attribute of the proper type in attr and returns the corresponding vector.
TODO(rridle,ntv) this should be evolved into a generic getRangeOfType<AffineMap>(ArrayAttr attrs) that does not copy.
Definition at line 449 of file LinalgOps.cpp.
References mlir::Attribute::cast(), and mlir::functional::map().
Referenced by mlir::fxpmath::detail::castElementType(), computeReshapeCollapsedType(), mlir::detail::MemRefTypeStorage::operator==(), and verify().
getIndexingMaps()
static ArrayAttr getIndexingMaps (Operation * op) static
Definition at line 1054 of file LinalgOps.cpp.
References mlir::AffineMapAttr::get(), mlir::ArrayAttr::get(), mlir::Operation::getContext(), mlir::linalg::loopToOperandRangesMaps(), and mlir::functional::map().
Referenced by getDimMap().
getMaxPosOfType()
template<typename AffineExprTy > unsigned getMaxPosOfType (ArrayRef< ArrayRef< AffineExpr >> exprArrays)
Definition at line 455 of file LinalgOps.cpp.
References mlir::AffineExpr::dyn_cast().
getSymbolLessAffineMaps()
static SmallVector<AffineMap, 4> getSymbolLessAffineMaps (ArrayRef< ArrayRef< AffineExpr >> reassociation) static
Definition at line 469 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), computeReshapeCollapsedType(), mlir::AffineMap::get(), mlir::Builder::getAffineMapArrayAttr(), and mlir::Value::getType().
isReassociationValid()
static bool isReassociationValid (ArrayRef< AffineMap > reassociation, int * invalidIndex = nullptr) static
Return true if the reassociation specification is valid, false otherwise.
When false, the invalidIndex integer pointer is optionally filled with the index of the offending reassociation map.
Definition at line 329 of file LinalgOps.cpp.
References mlir::detail::enumerate().
Referenced by computeReshapeCollapsedType(), and verify().
isReshapableDimBand()
static bool isReshapableDimBand (unsigned dim, unsigned extent, ArrayRef< int64_t > sizes, ArrayRef< AffineExpr > strides) static
Detect whether memref dims [dim, dim + extent) can be reshaped without copies.
Definition at line 361 of file LinalgOps.cpp.
References mlir::ShapedType::isDynamic().
Referenced by computeReshapeCollapsedType().
makeAffineDimExprs()
static SmallVector<AffineExpr, 4> makeAffineDimExprs (unsigned num, unsigned & curIdx, MLIRContext * context) static
Definition at line 895 of file LinalgOps.cpp.
References mlir::getAffineDimExpr().
Referenced by mlir::linalg::loopToOperandRangesMaps().
parseGenericOp()
static ParseResult parseGenericOp (OpAsmParser & parser, OperationState & result) static
Definition at line 71 of file LinalgOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::DictionaryAttr::get(), mlir::OpAsmParser::getCurrentLocation(), mlir::getFunAttrName(), mlir::DictionaryAttr::getValue(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalRegion(), mlir::OpAsmParser::resolveOperands(), and verifyBlockArgs().
parseLinalgStructuredOp()
static ParseResult parseLinalgStructuredOp (OpAsmParser & parser, OperationState & result) static
Definition at line 784 of file LinalgOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OpAsmParser::resolveOperands().
parseRangeOp()
static ParseResult parseRangeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 309 of file LinalgOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseReshapeOp()
static ParseResult parseReshapeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 509 of file LinalgOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseSliceOp()
static ParseResult parseSliceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 596 of file LinalgOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
parseTransposeOp()
static ParseResult parseTransposeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 677 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::AffineMapAttr::get(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMap(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseYieldOp()
static ParseResult parseYieldOp (OpAsmParser & parser, OperationState & result) static
Definition at line 707 of file LinalgOps.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OpAsmParser::resolveOperands().
print() [1/7]
static void print (OpAsmPrinter & p, GenericOp op) static
Definition at line 65 of file LinalgOps.cpp.
References printGenericOp().
print() [2/7]
static void print (OpAsmPrinter & p, IndexedGenericOp op) static
Definition at line 67 of file LinalgOps.cpp.
References printGenericOp().
print() [3/7]
static void print (OpAsmPrinter & p, RangeOp op) static
Definition at line 302 of file LinalgOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [4/7]
static void print (OpAsmPrinter & p, ReshapeOp op) static
Definition at line 502 of file LinalgOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [5/7]
static void print (OpAsmPrinter & p, SliceOp op) static
Definition at line 585 of file LinalgOps.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [6/7]
static void print (OpAsmPrinter & p, TransposeOp op) static
Definition at line 670 of file LinalgOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [7/7]
static void print (OpAsmPrinter & p, YieldOp op) static
Definition at line 698 of file LinalgOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printGenericOp()
template<typename GenericOpType > static void printGenericOp (OpAsmPrinter & p, GenericOpType op) static
Definition at line 44 of file LinalgOps.cpp.
References mlir::DictionaryAttr::get(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
Referenced by print(), and printDenseFloatElement().
printLinalgStructuredOp()
static void printLinalgStructuredOp (OpAsmPrinter & p, Operation * op) static
Definition at line 777 of file LinalgOps.cpp.
References mlir::Operation::getAbstractOperation(), mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getOperands(), mlir::Operation::getOperandTypes(), mlir::OperationName::getStringRef(), and mlir::OpAsmPrinter::printOptionalAttrDict().
verify() [1/8]
static LogicalResult verify (GenericOp op) static
Definition at line 295 of file LinalgOps.cpp.
References verifyGenericOp().
verify() [2/8]
static LogicalResult verify (IndexedGenericOp op) static
Definition at line 296 of file LinalgOps.cpp.
References verifyGenericOp().
verify() [3/8]
static LogicalResult verify (ReshapeOp op) static
Definition at line 524 of file LinalgOps.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), computeReshapeCollapsedType(), mlir::detail::enumerate(), mlir::MemRefType::get(), getAffineMaps(), mlir::Builder::getContext(), mlir::getStridesAndOffset(), mlir::Value::getType(), isReassociationValid(), mlir::makeStridedLinearLayoutMap(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), mlir::succeeded(), and mlir::success().
verify() [4/8]
static LogicalResult verify (SliceOp op) static
Definition at line 619 of file LinalgOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), mlir::detail::enumerate(), mlir::MemRefType::get(), mlir::Builder::getContext(), mlir::MemRefType::getShape(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::AffineMapAttr::getValue(), mlir::makeStridedLinearLayoutMap(), mlir::functional::map(), mlir::succeeded(), and mlir::success().
verify() [5/8]
static LogicalResult verify (YieldOp op) static
Definition at line 738 of file LinalgOps.cpp.
References verifyYield().
verify() [6/8]
static LogicalResult verify (FillOp op) static
Definition at line 795 of file LinalgOps.cpp.
References mlir::success(), and mlir::LogicalResult::value.
verify() [7/8]
static LogicalResult verify (CopyOp op) static
Definition at line 803 of file LinalgOps.cpp.
References mlir::success().
verify() [8/8]
static LogicalResult verify (ConvOp op) static
Definition at line 847 of file LinalgOps.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifyStrideOrDilation().
verifyBlockArgs() [1/3]
template<typename GenericOpType > static LogicalResult verifyBlockArgs (GenericOpType op, Block & block) static
Referenced by parseGenericOp(), and verifyGenericOp().
verifyBlockArgs() [2/3]
template<> LogicalResult verifyBlockArgs (GenericOp op, Block & block)
Definition at line 108 of file LinalgOps.cpp.
References mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::BlockArgument::getType(), and mlir::success().
verifyBlockArgs() [3/3]
template<> LogicalResult verifyBlockArgs (IndexedGenericOp op, Block & block)
Definition at line 127 of file LinalgOps.cpp.
References mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::BlockArgument::getType(), mlir::Type::isIndex(), mlir::success(), and verifyFuncArgs().
verifyFuncArgs() [1/3]
template<typename GenericOpType > static LogicalResult verifyFuncArgs (GenericOpType op, FunctionType funType) static
Referenced by verifyBlockArgs(), and verifyFuncArgsGeneric().
verifyFuncArgs() [2/3]
template<> LogicalResult verifyFuncArgs (GenericOp op, FunctionType funType)
Definition at line 178 of file LinalgOps.cpp.
References mlir::ShapedType::getElementType(), mlir::FunctionType::getInput(), mlir::FunctionType::getNumInputs(), mlir::FunctionType::getNumResults(), and mlir::success().
verifyFuncArgs() [3/3]
template<> LogicalResult verifyFuncArgs (IndexedGenericOp op, FunctionType funType)
Definition at line 202 of file LinalgOps.cpp.
References mlir::ShapedType::getElementType(), mlir::FunctionType::getInput(), mlir::FunctionType::getNumInputs(), mlir::FunctionType::getNumResults(), mlir::Type::isIndex(), and mlir::success().
verifyFuncArgsGeneric()
template<typename GenericOpType > LogicalResult verifyFuncArgsGeneric (GenericOpType op, FunctionType funType)
Definition at line 160 of file LinalgOps.cpp.
References mlir::failed(), mlir::ShapedType::getElementType(), mlir::FunctionType::getResult(), mlir::success(), and verifyFuncArgs().
Referenced by verifyGenericOp().
verifyGenericOp()
template<typename GenericOpType > static LogicalResult verifyGenericOp (GenericOpType op) static
Definition at line 231 of file LinalgOps.cpp.
References mlir::concatAffineMaps(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::inversePermutation(), mlir::success(), verifyBlockArgs(), and verifyFuncArgsGeneric().
Referenced by verify().
verifyStrideOrDilation()
static LogicalResult verifyStrideOrDilation (ConvOp op, ArrayRef< Attribute > attrs, bool isStride) static
Definition at line 837 of file LinalgOps.cpp.
References mlir::success().
Referenced by verify().
verifyYield()
template<typename GenericOpType > static LogicalResult verifyYield (YieldOp op, GenericOpType genericOp) static
Definition at line 718 of file LinalgOps.cpp.
References mlir::success().
Referenced by verify().
weightedConvInputIndex()
static SmallVector<AffineExpr, 4> weightedConvInputIndex (ConvOp op, ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b) static
Definition at line 904 of file LinalgOps.cpp.
Referenced by mlir::linalg::loopToOperandRangesMaps().