MLIR: lib/Dialect/Linalg/Transforms/LinalgToLoops.cpp File Reference
LinalgToLoops.cpp File Reference
#include "mlir/Dialect/Linalg/EDSC/Builders.h"
#include "mlir/Dialect/Linalg/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/LinalgTransforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/EDSC/Helpers.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/STLExtras.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define GET_OP_LIST
#define INSTANTIATE_LINALG_OP_TO_LOOPS(OP_TYPE)
Typedefs
using IndexedStdValue = TemplatedIndexedValue< std_load, std_store >
using IndexedAffineValue = TemplatedIndexedValue< affine_load, affine_store >
Functions
static SmallVector< ValueHandle, 8 > makeCanonicalAffineApplies (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > vals)
static SmallVector< Value, 4 > permuteIvs (ArrayRef< Value > ivs, Optional< AffineMap > permutation)
static SmallVector< Value, 4 > emitLoopRanges (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > allViewSizes)
Variables
static PassRegistration< LowerLinalgToLoopsPass< loop::ForOp, IndexedStdValue > > structuredLoopsPass ("convert-linalg-to-loops", "Lower the operations from the linalg dialect into loops")
static PassRegistration< LowerLinalgToLoopsPass< AffineForOp, IndexedAffineValue > > affineLoopsPass ("convert-linalg-to-affine-loops", "Lower the operations from the linalg dialect into affine loops")
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
INSTANTIATE_LINALG_OP_TO_LOOPS
#define INSTANTIATE_LINALG_OP_TO_LOOPS (OP_TYPE)
Value:
template LogicalResult mlir::linalg::linalgOpToLoops<OP_TYPE>(\
      PatternRewriter & rewriter, Operation * op);                             \
  template LogicalResult mlir::linalg::linalgOpToAffineLoops<OP_TYPE>(         \
      PatternRewriter & rewriter, Operation * op);
Definition at line 595 of file LinalgToLoops.cpp.
Typedef Documentation
IndexedAffineValue
using IndexedAffineValue = TemplatedIndexedValue<affine_load, affine_store>
Definition at line 35 of file LinalgToLoops.cpp.
IndexedStdValue
using IndexedStdValue = TemplatedIndexedValue<std_load, std_store>
Definition at line 34 of file LinalgToLoops.cpp.
Function Documentation
emitLoopRanges()
SmallVector< Value, 4 > emitLoopRanges (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > allViewSizes) static
Definition at line 71 of file LinalgToLoops.cpp.
References mlir::linalg::applyMapToValues(), mlir::applyPatternsGreedily(), mlir::concatAffineMaps(), mlir::AffineExpr::dyn_cast(), mlir::PatternRewriter::eraseOp(), mlir::edsc::extractValues(), mlir::failed(), mlir::AffineApplyOp::getAffineMap(), mlir::edsc::ScopedContext::getBuilder(), mlir::AffineApplyOp::getCanonicalizationPatterns(), mlir::Operation::getLoc(), mlir::edsc::ScopedContext::getLocation(), mlir::AffineMap::getNumResults(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::AffineApplyOp::getOperationName(), mlir::Operation::getResult(), mlir::linalg::getViewSizes(), mlir::OwningRewritePatternList::insert(), mlir::inversePermutation(), LinalgOps, mlir::BlockAndValueMapping::lookup(), mlir::linalg::loopToOperandRangesMaps(), makeCanonicalAffineApplies(), mlir::edsc::makeHandlePointers(), mlir::functional::map(), mlir::BlockAndValueMapping::map(), permuteIvs(), mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by permuteIvs().
makeCanonicalAffineApplies()
static SmallVector<ValueHandle, 8> makeCanonicalAffineApplies (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > vals) static
Definition at line 41 of file LinalgToLoops.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by emitLoopRanges().
permuteIvs()
static SmallVector<Value, 4> permuteIvs (ArrayRef< Value > ivs, Optional< AffineMap > permutation) static
Definition at line 57 of file LinalgToLoops.cpp.
References mlir::linalg::applyMapToValues(), emitLoopRanges(), mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getLocation(), and mlir::functional::map().
Referenced by emitLoopRanges().
Variable Documentation
affineLoopsPass
PassRegistration<LowerLinalgToLoopsPass<AffineForOp, IndexedAffineValue> > affineLoopsPass("convert-linalg-to-affine-loops", "Lower the operations from the linalg dialect into affine loops") static
structuredLoopsPass
PassRegistration<LowerLinalgToLoopsPass<loop::ForOp, IndexedStdValue> > structuredLoopsPass("convert-linalg-to-loops", "Lower the operations from the linalg dialect into loops") static