MLIR: lib/Conversion/LinalgToLLVM/LinalgToLLVM.cpp File Reference
LinalgToLLVM.cpp File Reference
#include "mlir/Conversion/LinalgToLLVM/LinalgToLLVM.h"
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Conversion/LoopToStandard/ConvertLoopToStandard.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/EDSC/Builders.h"
#include "mlir/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/Types.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/ErrorHandling.h"
Typedefs
using add = ValueBuilder< mlir::LLVM::AddOp >
using addi = ValueBuilder< mlir::AddIOp >
using bitcast = ValueBuilder< mlir::LLVM::BitcastOp >
using cmpi = ValueBuilder< mlir::CmpIOp >
using constant = ValueBuilder< mlir::LLVM::ConstantOp >
using extractvalue = ValueBuilder< mlir::LLVM::ExtractValueOp >
using gep = ValueBuilder< mlir::LLVM::GEPOp >
using insertvalue = ValueBuilder< mlir::LLVM::InsertValueOp >
using llvm_call = OperationBuilder< mlir::LLVM::CallOp >
using llvm_icmp = ValueBuilder< LLVM::ICmpOp >
using llvm_load = ValueBuilder< LLVM::LoadOp >
using llvm_store = OperationBuilder< LLVM::StoreOp >
using llvm_select = ValueBuilder< LLVM::SelectOp >
using mul = ValueBuilder< mlir::LLVM::MulOp >
using ptrtoint = ValueBuilder< mlir::LLVM::PtrToIntOp >
using sub = ValueBuilder< mlir::LLVM::SubOp >
using llvm_undef = ValueBuilder< mlir::LLVM::UndefOp >
using urem = ValueBuilder< mlir::LLVM::URemOp >
using llvm_alloca = ValueBuilder< LLVM::AllocaOp >
using llvm_return = OperationBuilder< LLVM::ReturnOp >
Functions
template<typename T >
static LLVMType getPtrToElementType (T containerType, LLVMTypeConverter &lowering)
static Type convertLinalgType (Type t, LLVMTypeConverter &lowering)
template<typename LinalgOp >
static SmallVector< Type, 4 > ExtractOperandTypes (Operation *op)
template<>
SmallVector< Type, 4 > ExtractOperandTypes< IndexedGenericOp > (Operation *op)
template<typename LinalgOp >
static FlatSymbolRefAttr getLibraryCallSymbolRef (Operation *op, PatternRewriter &rewriter)
Variables
static PassRegistration< ConvertLinalgToLLVMPass > pass ("convert-linalg-to-llvm", "Convert the operations from the linalg dialect into the LLVM dialect")
Typedef Documentation
add
using add = ValueBuilder<mlir::LLVM::AddOp>
Definition at line 50 of file LinalgToLLVM.cpp.
addi
using addi = ValueBuilder<mlir::AddIOp>
Definition at line 51 of file LinalgToLLVM.cpp.
bitcast
using bitcast = ValueBuilder<mlir::LLVM::BitcastOp>
Definition at line 52 of file LinalgToLLVM.cpp.
cmpi
using cmpi = ValueBuilder<mlir::CmpIOp>
Definition at line 53 of file LinalgToLLVM.cpp.
constant
using constant = ValueBuilder<mlir::LLVM::ConstantOp>
Definition at line 54 of file LinalgToLLVM.cpp.
extractvalue
using extractvalue = ValueBuilder<mlir::LLVM::ExtractValueOp>
Definition at line 55 of file LinalgToLLVM.cpp.
gep
using gep = ValueBuilder<mlir::LLVM::GEPOp>
Definition at line 56 of file LinalgToLLVM.cpp.
insertvalue
using insertvalue = ValueBuilder<mlir::LLVM::InsertValueOp>
Definition at line 57 of file LinalgToLLVM.cpp.
llvm_alloca
using llvm_alloca = ValueBuilder<LLVM::AllocaOp>
Definition at line 68 of file LinalgToLLVM.cpp.
llvm_call
using llvm_call = OperationBuilder<mlir::LLVM::CallOp>
Definition at line 58 of file LinalgToLLVM.cpp.
llvm_icmp
using llvm_icmp = ValueBuilder<LLVM::ICmpOp>
Definition at line 59 of file LinalgToLLVM.cpp.
llvm_load
using llvm_load = ValueBuilder<LLVM::LoadOp>
Definition at line 60 of file LinalgToLLVM.cpp.
llvm_return
using llvm_return = OperationBuilder<LLVM::ReturnOp>
Definition at line 69 of file LinalgToLLVM.cpp.
llvm_select
using llvm_select = ValueBuilder<LLVM::SelectOp>
Definition at line 62 of file LinalgToLLVM.cpp.
llvm_store
using llvm_store = OperationBuilder<LLVM::StoreOp>
Definition at line 61 of file LinalgToLLVM.cpp.
llvm_undef
using llvm_undef = ValueBuilder<mlir::LLVM::UndefOp>
Definition at line 66 of file LinalgToLLVM.cpp.
mul
using mul = ValueBuilder<mlir::LLVM::MulOp>
Definition at line 63 of file LinalgToLLVM.cpp.
ptrtoint
using ptrtoint = ValueBuilder<mlir::LLVM::PtrToIntOp>
Definition at line 64 of file LinalgToLLVM.cpp.
sub
using sub = ValueBuilder<mlir::LLVM::SubOp>
Definition at line 65 of file LinalgToLLVM.cpp.
urem
using urem = ValueBuilder<mlir::LLVM::URemOp>
Definition at line 67 of file LinalgToLLVM.cpp.
Function Documentation
convertLinalgType()
static Type convertLinalgType (Type t, LLVMTypeConverter & lowering) static
Definition at line 87 of file LinalgToLLVM.cpp.
References mlir::Type::cast(), mlir::LLVMTypeConverter::convertType(), mlir::detail::enumerate(), mlir::failed(), mlir::IntegerType::get(), mlir::edsc::ScopedContext::getBuilder(), mlir::Type::getContext(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::Operation::getLoc(), mlir::edsc::ScopedContext::getLocation(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::StandardAttributes::Type, and mlir::MemRefDescriptor::undef().
Referenced by mlir::LinalgTypeConverter::convertType().
ExtractOperandTypes()
template<typename LinalgOp > static SmallVector<Type, 4> ExtractOperandTypes (Operation * op) static
Definition at line 367 of file LinalgToLLVM.cpp.
References mlir::Operation::getOperandTypes().
ExtractOperandTypes< IndexedGenericOp >()
template<> SmallVector<Type, 4> ExtractOperandTypes< IndexedGenericOp > (Operation * op)
Definition at line 372 of file LinalgToLLVM.cpp.
References mlir::IndexType::get().
getLibraryCallSymbolRef()
template<typename LinalgOp > static FlatSymbolRefAttr getLibraryCallSymbolRef (Operation * op, PatternRewriter & rewriter) static
Definition at line 391 of file LinalgToLLVM.cpp.
References mlir::PatternRewriter::create(), mlir::Operation::emitWarning(), mlir::FunctionType::get(), mlir::Builder::getContext(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getParentOfType(), mlir::Builder::getSymbolRefAttr(), mlir::FlatSymbolRefAttr::getValue(), and mlir::OpBuilder::setInsertionPoint().
getPtrToElementType()
template<typename T > static LLVMType getPtrToElementType (T containerType, LLVMTypeConverter & lowering) static
Definition at line 72 of file LinalgToLLVM.cpp.
References mlir::LLVMTypeConverter::convertType().
Variable Documentation
pass
PassRegistration<ConvertLinalgToLLVMPass> pass("convert-linalg-to-llvm", "Convert the operations from the linalg dialect into the LLVM dialect") static
Referenced by mlir::createConvertLinalgToLLVMPass().