MLIR: lib/Dialect/LLVMIR/IR/LLVMDialect.cpp File Reference
LLVMDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/LLVMOpsEnums.cpp.inc"
#include "mlir/Dialect/LLVMIR/LLVMOps.cpp.inc"
Classes
struct mlir::LLVM::detail::LLVMDialectImpl
struct mlir::LLVM::detail::LLVMTypeStorage
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::LLVM
mlir::LLVM::detail
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void printICmpOp (OpAsmPrinter &p, ICmpOp &op)
static void printFCmpOp (OpAsmPrinter &p, FCmpOp &op)
template<typename CmpPredicateType >
static ParseResult parseCmpOp (OpAsmParser &parser, OperationState &result)
static void printAllocaOp (OpAsmPrinter &p, AllocaOp &op)
static ParseResult parseAllocaOp (OpAsmParser &parser, OperationState &result)
static void printGEPOp (OpAsmPrinter &p, GEPOp &op)
static ParseResult parseGEPOp (OpAsmParser &parser, OperationState &result)
static void printLoadOp (OpAsmPrinter &p, LoadOp &op)
static Type getLoadStoreElementType (OpAsmParser &parser, Type type, llvm::SMLoc trailingTypeLoc)
static ParseResult parseLoadOp (OpAsmParser &parser, OperationState &result)
static void printStoreOp (OpAsmPrinter &p, StoreOp &op)
static ParseResult parseStoreOp (OpAsmParser &parser, OperationState &result)
static void printCallOp (OpAsmPrinter &p, CallOp &op)
static ParseResult parseCallOp (OpAsmParser &parser, OperationState &result)
static void printExtractElementOp (OpAsmPrinter &p, ExtractElementOp &op)
static ParseResult parseExtractElementOp (OpAsmParser &parser, OperationState &result)
static void printExtractValueOp (OpAsmPrinter &p, ExtractValueOp &op)
static LLVM::LLVMType getInsertExtractValueElementType (OpAsmParser &parser, Type containerType, ArrayAttr positionAttr, llvm::SMLoc attributeLoc, llvm::SMLoc typeLoc)
static ParseResult parseExtractValueOp (OpAsmParser &parser, OperationState &result)
static void printInsertElementOp (OpAsmPrinter &p, InsertElementOp &op)
static ParseResult parseInsertElementOp (OpAsmParser &parser, OperationState &result)
static void printInsertValueOp (OpAsmPrinter &p, InsertValueOp &op)
static ParseResult parseInsertValueOp (OpAsmParser &parser, OperationState &result)
static void printSelectOp (OpAsmPrinter &p, SelectOp &op)
static ParseResult parseSelectOp (OpAsmParser &parser, OperationState &result)
static void printBrOp (OpAsmPrinter &p, BrOp &op)
static ParseResult parseBrOp (OpAsmParser &parser, OperationState &result)
static void printCondBrOp (OpAsmPrinter &p, CondBrOp &op)
static ParseResult parseCondBrOp (OpAsmParser &parser, OperationState &result)
static void printReturnOp (OpAsmPrinter &p, ReturnOp &op)
static ParseResult parseReturnOp (OpAsmParser &parser, OperationState &result)
static void printUndefOp (OpAsmPrinter &p, UndefOp &op)
static ParseResult parseUndefOp (OpAsmParser &parser, OperationState &result)
static void printAddressOfOp (OpAsmPrinter &p, AddressOfOp op)
static ParseResult parseAddressOfOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (AddressOfOp op)
static void printConstantOp (OpAsmPrinter &p, ConstantOp &op)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &result)
static StringRef getLinkageAttrName ()
Returns the name used for the linkage attribute.
static StringRef linkageToStr (LLVM::Linkage linkage)
static void printLinkage (OpAsmPrinter &p, LLVM::Linkage linkage)
static void printGlobalOp (OpAsmPrinter &p, GlobalOp op)
static int parseOptionalKeywordAlternative (OpAsmParser &parser, ArrayRef< StringRef > keywords)
static ParseResult parseOptionalLinkageKeyword (OpAsmParser &parser, OperationState &result)
static ParseResult parseGlobalOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (GlobalOp op)
static void printShuffleVectorOp (OpAsmPrinter &p, ShuffleVectorOp &op)
static ParseResult parseShuffleVectorOp (OpAsmParser &parser, OperationState &result)
static Type buildLLVMFunctionType (OpAsmParser &parser, llvm::SMLoc loc, ArrayRef< Type > inputs, ArrayRef< Type > outputs, impl::VariadicFlag variadicFlag)
static ParseResult parseLLVMFuncOp (OpAsmParser &parser, OperationState &result)
static void printLLVMFuncOp (OpAsmPrinter &p, LLVMFuncOp op)
static LogicalResult verify (LLVMFuncOp op)
static void printNullOp (OpAsmPrinter &p, LLVM::NullOp op)
static ParseResult parseNullOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (LLVM::NullOp op)
static ParseResult parseAtomicBinOp (OpAsmParser &parser, OperationState &result, StringRef attrName)
static ParseResult parseAtomicOrdering (OpAsmParser &parser, OperationState &result, StringRef attrName)
static void printAtomicRMWOp (OpAsmPrinter &p, AtomicRMWOp &op)
static ParseResult parseAtomicRMWOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (AtomicRMWOp op)
static void printAtomicCmpXchgOp (OpAsmPrinter &p, AtomicCmpXchgOp &op)
static ParseResult parseAtomicCmpXchgOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (AtomicCmpXchgOp op)
static SmallVector< llvm::Type *, 8 > toUnderlyingTypes (ArrayRef< LLVMType > elements)
Variables
static DialectRegistration< LLVMDialect > llvmDialect
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1587 of file LLVMDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
buildLLVMFunctionType()
static Type buildLLVMFunctionType (OpAsmParser & parser, llvm::SMLoc loc, ArrayRef< Type > inputs, ArrayRef< Type > outputs, impl::VariadicFlag variadicFlag) static
Definition at line 1128 of file LLVMDialect.cpp.
References mlir::OpAsmParser::emitError(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::LLVM::LLVMType::getFunctionTy(), mlir::MLIRContext::getRegisteredDialect(), mlir::LLVM::LLVMType::getVoidTy(), and mlir::impl::VariadicFlag::isVariadic().
Referenced by parseLLVMFuncOp().
getInsertExtractValueElementType()
static LLVM::LLVMType getInsertExtractValueElementType (OpAsmParser & parser, Type containerType, ArrayAttr positionAttr, llvm::SMLoc attributeLoc, llvm::SMLoc typeLoc) static
Definition at line 446 of file LLVMDialect.cpp.
References mlir::Type::dyn_cast(), and mlir::OpAsmParser::emitError().
Referenced by parseExtractValueOp(), and parseInsertValueOp().
getLinkageAttrName()
static StringRef getLinkageAttrName () static
Returns the name used for the linkage attribute.
This must correspond to the name of the attribute in ODS.
Definition at line 836 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::TypeAttr::get(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), and mlir::Builder::getUnitAttr().
Referenced by parseLLVMFuncOp(), parseOptionalLinkageKeyword(), parseShuffleVectorOp(), printGlobalOp(), and printLLVMFuncOp().
getLoadStoreElementType()
static Type getLoadStoreElementType (OpAsmParser & parser, Type type, llvm::SMLoc trailingTypeLoc) static
Definition at line 212 of file LLVMDialect.cpp.
References mlir::Type::dyn_cast(), and mlir::OpAsmParser::emitError().
Referenced by parseLoadOp(), and parseStoreOp().
linkageToStr()
static StringRef linkageToStr (LLVM::Linkage linkage) static
Definition at line 858 of file LLVMDialect.cpp.
Referenced by printLinkage(), and verify().
parseAddressOfOp()
static ParseResult parseAddressOfOp (OpAsmParser & parser, OperationState & result) static
Definition at line 776 of file LLVMDialect.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getNameLoc(), mlir::Attribute::isa(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::success(), and mlir::OperationState::types.
parseAllocaOp()
static ParseResult parseAllocaOp (OpAsmParser & parser, OperationState & result) static
Definition at line 130 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseAtomicBinOp()
static ParseResult parseAtomicBinOp (OpAsmParser & parser, OperationState & result, StringRef attrName) static
Definition at line 1355 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI64IntegerAttr(), mlir::OpAsmParser::parseKeyword(), and mlir::success().
Referenced by parseAtomicRMWOp().
parseAtomicCmpXchgOp()
static ParseResult parseAtomicCmpXchgOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1478 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getPointerTo(), mlir::MLIRContext::getRegisteredDialect(), mlir::LLVM::LLVMType::getStructTy(), mlir::OperationState::operands, parseAtomicOrdering(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseAtomicOrdering()
static ParseResult parseAtomicOrdering (OpAsmParser & parser, OperationState & result, StringRef attrName) static
Definition at line 1381 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI64IntegerAttr(), mlir::OpAsmParser::parseKeyword(), and mlir::success().
Referenced by parseAtomicCmpXchgOp(), and parseAtomicRMWOp().
parseAtomicRMWOp()
static ParseResult parseAtomicRMWOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1418 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::LLVM::LLVMType::getPointerTo(), mlir::OperationState::operands, parseAtomicBinOp(), parseAtomicOrdering(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseBrOp()
static ParseResult parseBrOp (OpAsmParser & parser, OperationState & result) static
Definition at line 650 of file LLVMDialect.cpp.
References mlir::OperationState::addSuccessor(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseSuccessorAndUseList(), and mlir::success().
parseCallOp()
static ParseResult parseCallOp (OpAsmParser & parser, OperationState & result) static
Definition at line 304 of file LLVMDialect.cpp.
References mlir::OperationState::addAttributes(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getCurrentLocation(), mlir::LLVM::LLVMType::getFunctionTy(), mlir::OpAsmParser::getNameLoc(), mlir::MLIRContext::getRegisteredDialect(), mlir::Value::getType(), mlir::LLVM::LLVMType::getVectorElementType(), mlir::LLVM::LLVMType::getVoidTy(), llvmDialect, mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseCmpOp()
template<typename CmpPredicateType > static ParseResult parseCmpOp (OpAsmParser & parser, OperationState & result) static
Definition at line 55 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI64IntegerAttr(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::MLIRContext::getRegisteredDialect(), mlir::StringAttr::getValue(), mlir::LLVM::LLVMType::getVectorTy(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseCondBrOp()
static ParseResult parseCondBrOp (OpAsmParser & parser, OperationState & result) static
Definition at line 676 of file LLVMDialect.cpp.
References mlir::OperationState::addSuccessor(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::MLIRContext::getRegisteredDialect(), llvmDialect, mlir::OperationState::operands, mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseSuccessorAndUseList(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 815 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRParen(), and mlir::success().
parseExtractElementOp()
static ParseResult parseExtractElementOp (OpAsmParser & parser, OperationState & result) static
Definition at line 410 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseExtractValueOp()
static ParseResult parseExtractValueOp (OpAsmParser & parser, OperationState & result) static
Definition at line 492 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), getInsertExtractValueElementType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseGEPOp()
static ParseResult parseGEPOp (OpAsmParser & parser, OperationState & result) static
Definition at line 171 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::success().
parseGlobalOp()
static ParseResult parseGlobalOp (OpAsmParser & parser, OperationState & result) static
Definition at line 952 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast_or_null(), mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::TypeAttr::get(), mlir::LLVM::LLVMType::getArrayTy(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getCurrentLocation(), mlir::LLVM::LLVMType::getInt8Ty(), mlir::OpAsmParser::getNameLoc(), mlir::MLIRContext::getRegisteredDialect(), mlir::SymbolTable::getSymbolAttrName(), mlir::Builder::getUnitAttr(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalColonTypeList(), mlir::OpAsmParser::parseOptionalKeyword(), parseOptionalLinkageKeyword(), mlir::OpAsmParser::parseOptionalRegion(), mlir::OpAsmParser::parseOptionalRParen(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::parseSymbolName(), mlir::succeeded(), and mlir::success().
parseInsertElementOp()
static ParseResult parseInsertElementOp (OpAsmParser & parser, OperationState & result) static
Definition at line 530 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseInsertValueOp()
static ParseResult parseInsertValueOp (OpAsmParser & parser, OperationState & result) static
Definition at line 575 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), getInsertExtractValueElementType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseLLVMFuncOp()
static ParseResult parseLLVMFuncOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1173 of file LLVMDialect.cpp.
References mlir::impl::addArgAndResultAttrs(), mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, buildLLVMFunctionType(), mlir::failed(), mlir::failure(), mlir::TypeAttr::get(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI64IntegerAttr(), getLinkageAttrName(), mlir::SymbolTable::getSymbolAttrName(), mlir::impl::getTypeAttrName(), mlir::impl::parseFunctionSignature(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), parseOptionalLinkageKeyword(), mlir::OpAsmParser::parseOptionalRegion(), and mlir::OpAsmParser::parseSymbolName().
parseLoadOp()
static ParseResult parseLoadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 225 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), getLoadStoreElementType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseNullOp()
static ParseResult parseNullOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1332 of file LLVMDialect.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OperationState::types.
parseOptionalKeywordAlternative()
static int parseOptionalKeywordAlternative (OpAsmParser & parser, ArrayRef< StringRef > keywords) static
Definition at line 919 of file LLVMDialect.cpp.
References mlir::detail::enumerate(), mlir::OpAsmParser::parseOptionalKeyword(), and mlir::succeeded().
Referenced by parseOptionalLinkageKeyword().
parseOptionalLinkageKeyword()
static ParseResult parseOptionalLinkageKeyword (OpAsmParser & parser, OperationState & result) static
Definition at line 934 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI64IntegerAttr(), getLinkageAttrName(), parseOptionalKeywordAlternative(), and mlir::success().
Referenced by parseGlobalOp(), and parseLLVMFuncOp().
parseReturnOp()
static ParseResult parseReturnOp (OpAsmParser & parser, OperationState & result) static
Definition at line 718 of file LLVMDialect.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseSelectOp()
static ParseResult parseSelectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 617 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseShuffleVectorOp()
static ParseResult parseShuffleVectorOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1058 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::TypeAttr::get(), mlir::impl::getArgAttrName(), mlir::OpAsmParser::getCurrentLocation(), mlir::LLVM::LLVMType::getFunctionNumParams(), mlir::LLVM::LLVMType::getFunctionParamType(), mlir::Builder::getI64IntegerAttr(), getLinkageAttrName(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::LLVM::LLVMType::getUnderlyingType(), mlir::LLVM::LLVMType::getVectorTy(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::ArrayAttr::size(), and mlir::success().
parseStoreOp()
static ParseResult parseStoreOp (OpAsmParser & parser, OperationState & result) static
Definition at line 253 of file LLVMDialect.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), getLoadStoreElementType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseUndefOp()
static ParseResult parseUndefOp (OpAsmParser & parser, OperationState & result) static
Definition at line 745 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::Operation::getParentOp(), mlir::SymbolTable::lookupSymbolIn(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::LLVM::satisfiesLLVMModule(), and mlir::success().
printAddressOfOp()
static void printAddressOfOp (OpAsmPrinter & p, AddressOfOp op) static
Definition at line 769 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printSymbolName().
printAllocaOp()
static void printAllocaOp (OpAsmPrinter & p, AllocaOp & op) static
Definition at line 114 of file LLVMDialect.cpp.
References mlir::FunctionType::get(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printAtomicCmpXchgOp()
static void printAtomicCmpXchgOp (OpAsmPrinter & p, AtomicCmpXchgOp & op) static
Definition at line 1467 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printAtomicRMWOp()
static void printAtomicRMWOp (OpAsmPrinter & p, AtomicRMWOp & op) static
Definition at line 1408 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printBrOp()
static void printBrOp (OpAsmPrinter & p, BrOp & op) static
Definition at line 642 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printSuccessorAndUseList().
printCallOp()
static void printCallOp (OpAsmPrinter & p, CallOp & op) static
Definition at line 279 of file LLVMDialect.cpp.
References mlir::FunctionType::get(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printSymbolName().
printCondBrOp()
static void printCondBrOp (OpAsmPrinter & p, CondBrOp & op) static
Definition at line 665 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printSuccessorAndUseList().
printConstantOp()
static void printConstantOp (OpAsmPrinter & p, ConstantOp & op) static
Definition at line 808 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printExtractElementOp()
static void printExtractElementOp (OpAsmPrinter & p, ExtractElementOp & op) static
Definition at line 401 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printExtractValueOp()
static void printExtractValueOp (OpAsmPrinter & p, ExtractValueOp & op) static
Definition at line 436 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printFCmpOp()
static void printFCmpOp (OpAsmPrinter & p, FCmpOp & op) static
Definition at line 43 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printGEPOp()
static void printGEPOp (OpAsmPrinter & p, GEPOp & op) static
Definition at line 159 of file LLVMDialect.cpp.
References mlir::FunctionType::get(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printGlobalOp()
static void printGlobalOp (OpAsmPrinter & p, GlobalOp op) static
Definition at line 891 of file LLVMDialect.cpp.
References mlir::Region::empty(), getLinkageAttrName(), mlir::SymbolTable::getSymbolAttrName(), printLinkage(), and mlir::OpAsmPrinter::printSymbolName().
printICmpOp()
static void printICmpOp (OpAsmPrinter & p, ICmpOp & op) static
Definition at line 36 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printInsertElementOp()
static void printInsertElementOp (OpAsmPrinter & p, InsertElementOp & op) static
Definition at line 521 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printInsertValueOp()
static void printInsertValueOp (OpAsmPrinter & p, InsertValueOp & op) static
Definition at line 565 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printLinkage()
static void printLinkage (OpAsmPrinter & p, LLVM::Linkage linkage) static
Definition at line 887 of file LLVMDialect.cpp.
References linkageToStr().
Referenced by printGlobalOp(), and printLLVMFuncOp().
printLLVMFuncOp()
static void printLLVMFuncOp (OpAsmPrinter & p, LLVMFuncOp op) static
Definition at line 1217 of file LLVMDialect.cpp.
References mlir::LLVM::LLVMType::getFunctionNumParams(), mlir::LLVM::LLVMType::getFunctionParamType(), mlir::LLVM::LLVMType::getFunctionResultType(), getLinkageAttrName(), mlir::impl::getTypeAttrName(), mlir::LLVM::LLVMType::getUnderlyingType(), mlir::impl::printFunctionAttributes(), mlir::impl::printFunctionSignature(), printLinkage(), mlir::OpAsmPrinter::printRegion(), mlir::OpAsmPrinter::printSymbolName(), and mlir::success().
printLoadOp()
static void printLoadOp (OpAsmPrinter & p, LoadOp & op) static
Definition at line 204 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printNullOp()
static void printNullOp (OpAsmPrinter & p, LLVM::NullOp op) static
Definition at line 1325 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printReturnOp()
static void printReturnOp (OpAsmPrinter & p, ReturnOp & op) static
Definition at line 705 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printSelectOp()
static void printSelectOp (OpAsmPrinter & p, SelectOp & op) static
Definition at line 608 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printShuffleVectorOp()
static void printShuffleVectorOp (OpAsmPrinter & p, ShuffleVectorOp & op) static
Definition at line 1048 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printStoreOp()
static void printStoreOp (OpAsmPrinter & p, StoreOp & op) static
Definition at line 246 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printUndefOp()
static void printUndefOp (OpAsmPrinter & p, UndefOp & op) static
Definition at line 738 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
toUnderlyingTypes()
static SmallVector<llvm::Type *, 8> toUnderlyingTypes (ArrayRef< LLVMType > elements) inline static
Definition at line 1800 of file LLVMDialect.cpp.
Referenced by mlir::LLVM::LLVMType::createStructTy(), and mlir::LLVM::LLVMType::setStructTyBody().
verify() [1/6]
static LogicalResult verify (AddressOfOp op) static
Definition at line 790 of file LLVMDialect.cpp.
References mlir::success().
verify() [2/6]
static LogicalResult verify (GlobalOp op) static
Definition at line 1001 of file LLVMDialect.cpp.
References mlir::OperationState::addAttributes(), mlir::Type::cast(), mlir::LLVM::LLVMType::getArrayElementType(), mlir::LLVM::LLVMType::getArrayNumElements(), mlir::Value::getType(), mlir::LLVM::LLVMType::getUnderlyingType(), mlir::LLVM::LLVMType::getVectorTy(), mlir::LLVM::satisfiesLLVMModule(), mlir::ArrayAttr::size(), and mlir::success().
verify() [3/6]
static LogicalResult verify (LLVMFuncOp op) static
Definition at line 1285 of file LLVMDialect.cpp.
References mlir::Type::dyn_cast(), mlir::Block::front(), mlir::Block::getArgument(), mlir::BlockArgument::getType(), linkageToStr(), and mlir::success().
verify() [4/6]
static LogicalResult verify (LLVM::NullOp op) static
Definition at line 1340 of file LLVMDialect.cpp.
References mlir::success().
verify() [5/6]
static LogicalResult verify (AtomicRMWOp op) static
Definition at line 1435 of file LLVMDialect.cpp.
References mlir::success().
verify() [6/6]
static LogicalResult verify (AtomicCmpXchgOp op) static
Definition at line 1503 of file LLVMDialect.cpp.
References mlir::LLVM::LLVMType::isDoubleTy(), mlir::LLVM::LLVMType::isFloatTy(), mlir::LLVM::LLVMType::isHalfTy(), mlir::LLVM::LLVMType::isIntegerTy(), mlir::LLVM::LLVMType::isPointerTy(), and mlir::success().
Variable Documentation
llvmDialect
DialectRegistration<LLVMDialect> llvmDialect static
Definition at line 1628 of file LLVMDialect.cpp.
Referenced by mlir::LLVMTypeConverter::getDialect(), mlir::LLVM::LLVMDialect::getDialectNamespace(), mlir::LLVMTypeConverter::packFunctionResults(), parseCallOp(), parseCondBrOp(), and parseNVVMVoteBallotOp().