MLIR: lib/Transforms/LoopFusion.cpp File Reference
LoopFusion.cpp File Reference
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/LoopFusionUtils.h"
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <iomanip>
#include <sstream>
Macros
#define DEBUG_TYPE "affine-loop-fusion"
Functions
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options")
static llvm::cl::opt< bool > clMaximalLoopFusion ("fusion-maximal", llvm::cl::desc("Enables maximal loop fusion"), llvm::cl::cat(clOptionsCategory))
Disables fusion profitability check and fuses if valid.
static llvm::cl::opt< double > clFusionAddlComputeTolerance ("fusion-compute-tolerance", llvm::cl::desc("Fractional increase in additional " "computation tolerated while fusing"), llvm::cl::cat(clOptionsCategory))
A threshold in percent of additional computation allowed when fusing.
static llvm::cl::opt< unsigned > clFusionFastMemorySpace ("fusion-fast-mem-space", llvm::cl::desc("Faster memory space number to promote fusion buffers to"), llvm::cl::cat(clOptionsCategory))
static llvm::cl::opt< unsigned long long > clFusionLocalBufThreshold ("fusion-local-buf-threshold", llvm::cl::desc("Threshold size (KiB) for promoting local buffers to fast " "memory space"), llvm::cl::cat(clOptionsCategory))
static bool isMemRefDereferencingOp (Operation &op)
static void moveLoadsAccessingMemrefTo (Value memref, SmallVectorImpl< Operation *> *srcLoads, SmallVectorImpl< Operation *> *dstLoads)
static unsigned getInnermostCommonLoopDepth (ArrayRef< Operation *> ops)
static unsigned getMaxLoopDepth (ArrayRef< Operation *> loadOpInsts, ArrayRef< Operation *> storeOpInsts)
static void sinkSequentialLoops (MemRefDependenceGraph::Node *node)
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType)
static Value createPrivateMemRef (AffineForOp forOp, Operation *srcStoreOpInst, unsigned dstLoopDepth, Optional< unsigned > fastMemorySpace, uint64_t localBufSizeThreshold)
static bool canFuseSrcWhichWritesToLiveOut (unsigned srcId, unsigned dstId, AffineStoreOp srcLiveOutStoreOp, MemRefDependenceGraph *mdg)
static bool isFusionProfitable (Operation *srcOpInst, Operation *srcStoreOpInst, ArrayRef< Operation *> dstLoadOpInsts, ArrayRef< Operation *> dstStoreOpInsts, ComputationSliceState *sliceState, unsigned *dstLoopDepth, bool maximalFusion)
Variables
static PassRegistration< LoopFusion > pass ("affine-loop-fusion", "Fuse loop nests")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-loop-fusion"
Definition at line 35 of file LoopFusion.cpp.
Function Documentation
canFuseSrcWhichWritesToLiveOut()
static bool canFuseSrcWhichWritesToLiveOut (unsigned srcId, unsigned dstId, AffineStoreOp srcLiveOutStoreOp, MemRefDependenceGraph * mdg) static
Definition at line 1005 of file LoopFusion.cpp.
References mlir::failed(), mlir::OpState::getLoc(), and mlir::AffineStoreOp::getMemRef().
Referenced by isFusionProfitable().
clFusionAddlComputeTolerance()
static llvm::cl::opt<double> clFusionAddlComputeTolerance ("fusion-compute-tolerance" , llvm::cl::desc("Fractional increase in additional " "computation tolerated while fusing") , llvm::cl::cat(clOptionsCategory)) static
A threshold in percent of additional computation allowed when fusing.
Referenced by isFusionProfitable().
clFusionFastMemorySpace()
static llvm::cl::opt<unsigned> clFusionFastMemorySpace ("fusion-fast-mem-space" , llvm::cl::desc("Faster memory space number to promote fusion buffers to") , llvm::cl::cat(clOptionsCategory)) static
Referenced by isFusionProfitable().
clFusionLocalBufThreshold()
static llvm::cl::opt<unsigned long long> clFusionLocalBufThreshold ("fusion-local-buf-threshold" , llvm::cl::desc("Threshold size (KiB) for promoting local buffers to fast " "memory space") , llvm::cl::cat(clOptionsCategory)) static
Referenced by isFusionProfitable().
clMaximalLoopFusion()
static llvm::cl::opt<bool> clMaximalLoopFusion ("fusion-maximal" , llvm::cl::desc("Enables maximal loop fusion") , llvm::cl::cat(clOptionsCategory)) static
Disables fusion profitability check and fuses if valid.
Ignore any additional (redundant) computation tolerance threshold that would have prevented fusion.
Referenced by isFusionProfitable().
clOptionsCategory()
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options") static
createPrivateMemRef()
static Value createPrivateMemRef (AffineForOp forOp, Operation * srcStoreOpInst, unsigned dstLoopDepth, Optional< unsigned > fastMemorySpace, uint64_t localBufSizeThreshold) static
Definition at line 887 of file LoopFusion.cpp.
References mlir::StandardAttributes::AffineMap, mlir::floorDiv(), mlir::AffineMap::get(), mlir::MemRefType::get(), mlir::Builder::getAffineDimExpr(), mlir::Operation::getLoc(), getMemRefEltSizeInBytes(), mlir::replaceAllMemRefUsesWith(), mlir::simplifyAffineExpr(), and mlir::succeeded().
Referenced by isFusionProfitable(), and isMemRefDereferencingOp().
getInnermostCommonLoopDepth()
static unsigned getInnermostCommonLoopDepth (ArrayRef< Operation *> ops) static
Definition at line 786 of file LoopFusion.cpp.
References mlir::getLoopIVs().
Referenced by getMaxLoopDepth(), and isFusionProfitable().
getMaxLoopDepth()
static unsigned getMaxLoopDepth (ArrayRef< Operation *> loadOpInsts, ArrayRef< Operation *> storeOpInsts) static
Definition at line 814 of file LoopFusion.cpp.
References mlir::checkMemrefAccessDependence(), getInnermostCommonLoopDepth(), mlir::getNumCommonSurroundingLoops(), and mlir::hasDependence().
Referenced by isFusionProfitable().
getMemRefEltSizeInBytes()
static unsigned getMemRefEltSizeInBytes (MemRefType memRefType) static
Definition at line 868 of file LoopFusion.cpp.
Referenced by createPrivateMemRef().
isFusionProfitable()
static bool isFusionProfitable (Operation * srcOpInst, Operation * srcStoreOpInst, ArrayRef< Operation *> dstLoadOpInsts, ArrayRef< Operation *> dstStoreOpInsts, ComputationSliceState * sliceState, unsigned * dstLoopDepth, bool maximalFusion) static
Definition at line 1099 of file LoopFusion.cpp.
References mlir::canFuseLoops(), canFuseSrcWhichWritesToLiveOut(), mlir::canonicalizeMapAndOperands(), clFusionAddlComputeTolerance(), clFusionFastMemorySpace(), clFusionLocalBufThreshold(), clMaximalLoopFusion(), mlir::computeSliceUnion(), createPrivateMemRef(), mlir::failed(), mlir::getComputeCost(), mlir::getFusionComputeCost(), getInnermostCommonLoopDepth(), mlir::Operation::getLoc(), mlir::getLoopIVs(), mlir::getLoopNestStats(), getMaxLoopDepth(), mlir::getMemoryFootprintBytes(), mlir::getNestingDepth(), mlir::insertBackwardComputationSlice(), mlir::Operation::isBeforeInBlock(), mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, moveLoadsAccessingMemrefTo(), mlir::StandardTypes::None, pass, mlir::promoteIfSingleIteration(), mlir::sinkSequentialLoops(), mlir::FusionResult::Success, mlir::ComputationSliceState::ubOperands, mlir::ComputationSliceState::ubs, and mlir::FusionResult::value.
isMemRefDereferencingOp()
static bool isMemRefDereferencingOp (Operation & op) static
Definition at line 113 of file LoopFusion.cpp.
References createPrivateMemRef(), getFusedLoopNestInsertionPoint(), mlir::getLoopIVs(), mlir::Operation::getNumRegions(), mlir::Value::getType(), mlir::Type::isa(), mlir::StandardTypes::None, print(), and mlir::Operation::walk().
moveLoadsAccessingMemrefTo()
static void moveLoadsAccessingMemrefTo (Value memref, SmallVectorImpl< Operation *> * srcLoads, SmallVectorImpl< Operation *> * dstLoads) static
Definition at line 771 of file LoopFusion.cpp.
Referenced by isFusionProfitable().
sinkSequentialLoops()
static void sinkSequentialLoops (MemRefDependenceGraph::Node * node) static
Definition at line 861 of file LoopFusion.cpp.
References mlir::sinkSequentialLoops().
Variable Documentation
pass
PassRegistration<LoopFusion> pass("affine-loop-fusion", "Fuse loop nests") static
Referenced by isFusionProfitable().