MLIR: lib/Dialect/LoopOps/LoopOps.cpp File Reference
LoopOps.cpp File Reference
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Support/STLExtras.h"
#include "mlir/Transforms/SideEffectsInterface.h"
#include "mlir/Dialect/LoopOps/LoopOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static LogicalResult verify (ForOp op)
static void print (OpAsmPrinter &p, ForOp op)
static ParseResult parseForOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (IfOp op)
static ParseResult parseIfOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, IfOp op)
static LogicalResult verify (ParallelOp op)
static ParseResult parseParallelOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ParallelOp op)
static LogicalResult verify (ReduceOp op)
static ParseResult parseReduceOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReduceOp op)
static LogicalResult verify (ReduceReturnOp op)
static ParseResult parseReduceReturnOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReduceReturnOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 421 of file LoopOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseForOp()
static ParseResult parseForOp (OpAsmParser & parser, OperationState & result) static
Definition at line 94 of file LoopOps.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Value::dyn_cast(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::loop::getForInductionVarOwner(), mlir::Builder::getIndexType(), mlir::Value::getParentRegion(), mlir::OperationState::location, mlir::Operation::moveBefore(), mlir::OperationState::operands, mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgument(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseIfOp()
static ParseResult parseIfOp (OpAsmParser & parser, OperationState & result) static
Definition at line 174 of file LoopOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIntegerType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseParallelOp()
static ParseResult parseParallelOp (OpAsmParser & parser, OperationState & result) static
Definition at line 274 of file LoopOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalColonTypeList(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
parseReduceOp()
static ParseResult parseReduceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 359 of file LoopOps.cpp.
References mlir::OperationState::addRegion(), mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseReduceReturnOp()
static ParseResult parseReduceReturnOp (OpAsmParser & parser, OperationState & result) static
Definition at line 401 of file LoopOps.cpp.
References mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
print() [1/5]
static void print (OpAsmPrinter & p, ForOp op) static
Definition at line 85 of file LoopOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [2/5]
static void print (OpAsmPrinter & p, IfOp op) static
Definition at line 206 of file LoopOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [3/5]
static void print (OpAsmPrinter & p, ParallelOp op) static
Definition at line 323 of file LoopOps.cpp.
References mlir::OpAsmPrinter::printOperands(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [4/5]
static void print (OpAsmPrinter & p, ReduceOp op) static
Definition at line 380 of file LoopOps.cpp.
References mlir::OpAsmPrinter::printRegion().
print() [5/5]
static void print (OpAsmPrinter & p, ReduceReturnOp op) static
Definition at line 412 of file LoopOps.cpp.
verify() [1/5]
static LogicalResult verify (ForOp op) static
Definition at line 71 of file LoopOps.cpp.
References mlir::success().
verify() [2/5]
static LogicalResult verify (IfOp op) static
Definition at line 160 of file LoopOps.cpp.
References mlir::success().
verify() [3/5]
static LogicalResult verify (ParallelOp op) static
Definition at line 228 of file LoopOps.cpp.
References mlir::Operation::emitOpError(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty(), mlir::Block::front(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Block::getOps(), and mlir::success().
verify() [4/5]
static LogicalResult verify (ReduceOp op) static
Definition at line 338 of file LoopOps.cpp.
References mlir::Operation::emitOpError(), mlir::Block::empty(), mlir::Block::front(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Block::getTerminator(), and mlir::success().
verify() [5/5]
static LogicalResult verify (ReduceReturnOp op) static
Definition at line 390 of file LoopOps.cpp.
References mlir::success().