MLIR: lib/Transforms/LoopTiling.cpp File Reference
LoopTiling.cpp File Reference
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "affine-loop-tile"
Functions
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options")
static llvm::cl::opt< unsigned long long > clCacheSizeKiB ("tile-cache-size", llvm::cl::desc("Set size of cache to tile for in KiB"), llvm::cl::cat(clOptionsCategory))
static llvm::cl::opt< unsigned > clTileSize ("tile-size", llvm::cl::desc("Use this tile size for all loops"), llvm::cl::cat(clOptionsCategory))
static llvm::cl::list< unsigned > clTileSizes ("tile-sizes", llvm::cl::desc("List of tile sizes for each perfect nest (overridden by -tile-size)"), llvm::cl::ZeroOrMore, llvm::cl::cat(clOptionsCategory))
static void moveLoopBody (AffineForOp src, AffineForOp dest, Block::iterator loc)
static void moveLoopBody (AffineForOp src, AffineForOp dest)
static void constructTiledIndexSetHyperRect (MutableArrayRef< AffineForOp > origLoops, MutableArrayRef< AffineForOp > newLoops, ArrayRef< unsigned > tileSizes)
Constructs and sets new loop bounds after tiling for the case of hyper-rectangular index sets, where the bounds of one dimension do not depend on other dimensions.
static void getTileableBands (FuncOp f, std::vector< SmallVector< AffineForOp, 6 >> *bands)
static void adjustToDivisorsOfTripCounts (ArrayRef< AffineForOp > band, SmallVectorImpl< unsigned > *tileSizes)
Variables
static PassRegistration< LoopTiling > pass ("affine-loop-tile", "Tile loop nests")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-loop-tile"
Definition at line 27 of file LoopTiling.cpp.
Function Documentation
adjustToDivisorsOfTripCounts()
static void adjustToDivisorsOfTripCounts (ArrayRef< AffineForOp > band, SmallVectorImpl< unsigned > * tileSizes) static
Definition at line 274 of file LoopTiling.cpp.
References clCacheSizeKiB(), clTileSize(), clTileSizes(), diag(), mlir::failed(), mlir::getConstantTripCount(), mlir::getMemoryFootprintBytes(), getTileableBands(), pass, and mlir::tileCodeGen().
clCacheSizeKiB()
static llvm::cl::opt<unsigned long long> clCacheSizeKiB ("tile-cache-size" , llvm::cl::desc("Set size of cache to tile for in KiB") , llvm::cl::cat(clOptionsCategory)) static
Referenced by adjustToDivisorsOfTripCounts().
clOptionsCategory()
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options") static
clTileSize()
static llvm::cl::opt<unsigned> clTileSize ("tile-size" , llvm::cl::desc("Use this tile size for all loops") , llvm::cl::cat(clOptionsCategory)) static
Referenced by adjustToDivisorsOfTripCounts().
clTileSizes()
static llvm::cl::list<unsigned> clTileSizes ("tile-sizes" , llvm::cl::desc("List of tile sizes for each perfect nest (overridden by -tile-size)") , llvm::cl::ZeroOrMore , llvm::cl::cat(clOptionsCategory)) static
Referenced by adjustToDivisorsOfTripCounts().
constructTiledIndexSetHyperRect()
static void constructTiledIndexSetHyperRect (MutableArrayRef< AffineForOp > origLoops, MutableArrayRef< AffineForOp > newLoops, ArrayRef< unsigned > tileSizes) static
Constructs and sets new loop bounds after tiling for the case of hyper-rectangular index sets, where the bounds of one dimension do not depend on other dimensions.
Bounds of each dimension can thus be treated independently, and deriving the new bounds is much simpler and faster than for the case of tiling arbitrary polyhedral shapes.
Definition at line 101 of file LoopTiling.cpp.
References mlir::AffineMap::get(), mlir::getConstantTripCount(), and mlir::getLargestDivisorOfTripCount().
Referenced by mlir::tileCodeGen().
getTileableBands()
static void getTileableBands (FuncOp f, std::vector< SmallVector< AffineForOp, 6 >> * bands) static
Definition at line 256 of file LoopTiling.cpp.
References mlir::getPerfectlyNestedLoops().
Referenced by adjustToDivisorsOfTripCounts().
moveLoopBody() [1/2]
static void moveLoopBody (AffineForOp src, AffineForOp dest, Block::iterator loc) inline static
Definition at line 82 of file LoopTiling.cpp.
Referenced by moveLoopBody(), and mlir::tileCodeGen().
moveLoopBody() [2/2]
static void moveLoopBody (AffineForOp src, AffineForOp dest) inline static
Definition at line 91 of file LoopTiling.cpp.
References moveLoopBody().
Variable Documentation
pass
PassRegistration<LoopTiling> pass("affine-loop-tile", "Tile loop nests") static
Referenced by adjustToDivisorsOfTripCounts().