MLIR: lib/Conversion/LoopsToGPU/LoopsToGPUPass.cpp File Reference
LoopsToGPUPass.cpp File Reference
#include "mlir/Conversion/LoopsToGPU/LoopsToGPUPass.h"
#include "mlir/Conversion/LoopsToGPU/LoopsToGPU.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Support/CommandLine.h"
Macros
#define PASS_NAME "convert-loops-to-gpu"
#define LOOPOP_TO_GPU_PASS_NAME "convert-loop-op-to-gpu"
Functions
static llvm::cl::OptionCategory clOptionsCategory (PASS_NAME " options")
static llvm::cl::opt< unsigned > clNumBlockDims ("gpu-block-dims", llvm::cl::desc("Number of GPU block dimensions for mapping"), llvm::cl::cat(clOptionsCategory), llvm::cl::init(1u))
static llvm::cl::opt< unsigned > clNumThreadDims ("gpu-thread-dims", llvm::cl::desc("Number of GPU thread dimensions for mapping"), llvm::cl::cat(clOptionsCategory), llvm::cl::init(1u))
static llvm::cl::OptionCategory clLoopOpToGPUCategory (LOOPOP_TO_GPU_PASS_NAME " options")
static llvm::cl::list< unsigned > clNumWorkGroups ("gpu-num-workgroups", llvm::cl::desc("Num workgroups in the GPU launch"), llvm::cl::ZeroOrMore, llvm::cl::MiscFlags::CommaSeparated, llvm::cl::cat(clLoopOpToGPUCategory))
static llvm::cl::list< unsigned > clWorkGroupSize ("gpu-workgroup-size", llvm::cl::desc("Workgroup Size in the GPU launch"), llvm::cl::ZeroOrMore, llvm::cl::MiscFlags::CommaSeparated, llvm::cl::cat(clLoopOpToGPUCategory))
Variables
static PassRegistration< ForLoopMapper > registration (PASS_NAME, "Convert top-level loops to GPU kernels", [] { return std::make_unique< ForLoopMapper >(clNumBlockDims.getValue(), clNumThreadDims.getValue());})
static PassRegistration< ImperfectlyNestedForLoopMapper > loopOpToGPU (LOOPOP_TO_GPU_PASS_NAME, "Convert top-level loop::ForOp to GPU kernels", [] { SmallVector< int64_t, 3 > numWorkGroups, workGroupSize;numWorkGroups.assign(clNumWorkGroups.begin(), clNumWorkGroups.end());workGroupSize.assign(clWorkGroupSize.begin(), clWorkGroupSize.end());return std::make_unique< ImperfectlyNestedForLoopMapper >(numWorkGroups, workGroupSize);})
Macro Definition Documentation
LOOPOP_TO_GPU_PASS_NAME
#define LOOPOP_TO_GPU_PASS_NAME "convert-loop-op-to-gpu"
Definition at line 20 of file LoopsToGPUPass.cpp.
Referenced by mlir::createLoopToGPUPass().
PASS_NAME
#define PASS_NAME "convert-loops-to-gpu"
Definition at line 19 of file LoopsToGPUPass.cpp.
Referenced by mlir::createLoopToGPUPass().
Function Documentation
clLoopOpToGPUCategory()
static llvm::cl::OptionCategory clLoopOpToGPUCategory (LOOPOP_TO_GPU_PASS_NAME " options") static
clNumBlockDims()
static llvm::cl::opt<unsigned> clNumBlockDims ("gpu-block-dims" , llvm::cl::desc("Number of GPU block dimensions for mapping") , llvm::cl::cat(clOptionsCategory) , llvm::cl::init(1u)) static
Referenced by mlir::createLoopToGPUPass().
clNumThreadDims()
static llvm::cl::opt<unsigned> clNumThreadDims ("gpu-thread-dims" , llvm::cl::desc("Number of GPU thread dimensions for mapping") , llvm::cl::cat(clOptionsCategory) , llvm::cl::init(1u)) static
Referenced by mlir::createLoopToGPUPass().
clNumWorkGroups()
static llvm::cl::list<unsigned> clNumWorkGroups ("gpu-num-workgroups" , llvm::cl::desc("Num workgroups in the GPU launch") , llvm::cl::ZeroOrMore , llvm::cl::MiscFlags::CommaSeparated , llvm::cl::cat(clLoopOpToGPUCategory)) static
Referenced by mlir::createLoopToGPUPass().
clOptionsCategory()
static llvm::cl::OptionCategory clOptionsCategory (PASS_NAME " options") static
clWorkGroupSize()
static llvm::cl::list<unsigned> clWorkGroupSize ("gpu-workgroup-size" , llvm::cl::desc("Workgroup Size in the GPU launch") , llvm::cl::ZeroOrMore , llvm::cl::MiscFlags::CommaSeparated , llvm::cl::cat(clLoopOpToGPUCategory)) static
Referenced by mlir::createLoopToGPUPass().
Variable Documentation
loopOpToGPU
PassRegistration<ImperfectlyNestedForLoopMapper> loopOpToGPU(LOOPOP_TO_GPU_PASS_NAME, "Convert top-level loop::ForOp to GPU kernels", [] { SmallVector< int64_t, 3 > numWorkGroups, workGroupSize;numWorkGroups.assign(clNumWorkGroups.begin(), clNumWorkGroups.end());workGroupSize.assign(clWorkGroupSize.begin(), clWorkGroupSize.end());return std::make_unique< ImperfectlyNestedForLoopMapper >(numWorkGroups, workGroupSize);}) static
Referenced by mlir::createLoopToGPUPass().
registration
PassRegistration<ForLoopMapper> registration(PASS_NAME, "Convert top-level loops to GPU kernels", [] { return std::make_unique< ForLoopMapper >(clNumBlockDims.getValue(), clNumThreadDims.getValue());}) static
Referenced by mlir::createLoopToGPUPass().