MLIR: lib/Transforms/Utils/LoopUtils.cpp File Reference
LoopUtils.cpp File Reference
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Function.h"
#include "mlir/Transforms/RegionUtils.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct StrideInfo
Macros
#define DEBUG_TYPE "LoopUtils"
Functions
static AffineForOp generateLoop (AffineMap lbMap, AffineMap ubMap, const std::vector< std::pair< uint64_t, ArrayRef< Operation *>>> &instGroupQueue, unsigned offset, AffineForOp srcForInst, OpBuilder b)
Generates a 'affine.for' op with the specified lower and upper bounds while generating the right IV remappings for the shifted operations.
template<typename T >
static void getPerfectlyNestedLoopsImpl (SmallVectorImpl< T > &forOps, T rootForOp, unsigned maxLoops=std::numeric_limits< unsigned >::max())
static bool checkLoopInterchangeDependences (const std::vector< SmallVector< DependenceComponent, 2 >> &depCompsVec, ArrayRef< AffineForOp > loops, ArrayRef< unsigned > loopPermMap)
static void augmentMapAndBounds (OpBuilder &b, Value iv, AffineMap *map, SmallVector< Value, 4 > *operands, int64_t offset=0)
static SmallVector< AffineForOp, 8 > stripmineSink (AffineForOp forOp, uint64_t factor, ArrayRef< AffineForOp > targets)
static Loops stripmineSink (loop::ForOp forOp, Value factor, ArrayRef< loop::ForOp > targets)
template<typename ForType , typename SizeType >
static ForType stripmineSink (ForType forOp, SizeType factor, ForType target)
template<typename ForType , typename SizeType >
static SmallVector< SmallVector< ForType, 8 >, 8 > tileImpl (ArrayRef< ForType > forOps, ArrayRef< SizeType > sizes, ArrayRef< ForType > targets)
template<typename ForType , typename SizeType >
static SmallVector< ForType, 8 > tileImpl (ArrayRef< ForType > forOps, ArrayRef< SizeType > sizes, ForType target)
static Value ceilDivPositive (OpBuilder &builder, Location loc, Value dividend, int64_t divisor)
static Value ceilDivPositive (OpBuilder &builder, Location loc, Value dividend, Value divisor)
static LogicalResult hoistOpsBetween (loop::ForOp outer, loop::ForOp inner)
static LogicalResult tryIsolateBands (const TileLoops &tileLoops)
static void replaceAllUsesExcept (Value orig, Value replacement, const SmallPtrSetImpl< Operation *> &exceptions)
static void normalizeLoop (loop::ForOp loop, loop::ForOp outer, loop::ForOp inner)
static void findHighestBlockForPlacement (const MemRefRegion &region, Block &block, Block::iterator &begin, Block::iterator &end, Block **copyPlacementBlock, Block::iterator *copyInPlacementStart, Block::iterator *copyOutPlacementStart)
Given a memref region, determine the lowest depth at which transfers can be placed for it, and return the corresponding block, start and end positions in the block for placing incoming (read) and outgoing (write) copies respectively.
static void getMultiLevelStrides (const MemRefRegion &region, ArrayRef< int64_t > bufferShape, SmallVectorImpl< StrideInfo > *strideInfos)
Returns striding information for a copy/transfer of this region with potentially multiple striding levels from outermost to innermost.
static AffineForOp generatePointWiseCopy (Location loc, Value memref, Value fastMemRef, AffineMap memAffineMap, ArrayRef< Value > memIndicesStart, ArrayRef< int64_t > fastBufferShape, bool isCopyOut, OpBuilder b)
Generates a point-wise copy from/to `memref' to/from `fastMemRef' and returns the outermost AffineForOp of the copy loop nest.
static InFlightDiagnostic LLVM_ATTRIBUTE_UNUSED emitRemarkForBlock (Block &block)
static LogicalResult generateCopy (const MemRefRegion &region, Block *block, Block::iterator begin, Block::iterator end, Block *copyPlacementBlock, Block::iterator copyInPlacementStart, Block::iterator copyOutPlacementStart, AffineCopyOptions copyOptions, DenseMap< Value, Value > &fastBufferMap, DenseSet< Operation *> &copyNests, uint64_t *sizeInBytes, Block::iterator *nBegin, Block::iterator *nEnd)
Creates a buffer in the faster memory space for the specified memref region; generates a copy from the lower memory space to this one, and replaces all loads/stores in the block range [`begin', `end') of `block' to load/store from that buffer.
static bool getFullMemRefAsRegion (Operation *opInst, unsigned numParamLoopIVs, MemRefRegion *region)
Construct the memref region to just include the entire memref.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "LoopUtils"
Definition at line 33 of file LoopUtils.cpp.
Function Documentation
augmentMapAndBounds()
static void augmentMapAndBounds (OpBuilder & b, Value iv, AffineMap * map, SmallVector< Value, 4 > * operands, int64_t offset = 0) static
Definition at line 662 of file LoopUtils.cpp.
References mlir::canonicalizeMapAndOperands(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by stripmineSink().
ceilDivPositive() [1/2]
static Value ceilDivPositive (OpBuilder & builder, Location loc, Value dividend, int64_t divisor) static
Definition at line 834 of file LoopUtils.cpp.
References mlir::OpBuilder::create(), mlir::Value::getType(), and mlir::Type::isIndex().
Referenced by mlir::extractFixedOuterLoops(), and normalizeLoop().
ceilDivPositive() [2/2]
static Value ceilDivPositive (OpBuilder & builder, Location loc, Value dividend, Value divisor) static
Definition at line 849 of file LoopUtils.cpp.
References mlir::OpBuilder::create(), mlir::Value::getType(), and mlir::Type::isIndex().
checkLoopInterchangeDependences()
static bool checkLoopInterchangeDependences (const std::vector< SmallVector< DependenceComponent, 2 >> & depCompsVec, ArrayRef< AffineForOp > loops, ArrayRef< unsigned > loopPermMap) static
Definition at line 524 of file LoopUtils.cpp.
Referenced by mlir::isValidLoopInterchangePermutation(), and mlir::sinkSequentialLoops().
emitRemarkForBlock()
static InFlightDiagnostic LLVM_ATTRIBUTE_UNUSED emitRemarkForBlock (Block & block) static
Definition at line 1247 of file LoopUtils.cpp.
References mlir::Operation::emitRemark(), and mlir::Block::getParentOp().
Referenced by generateCopy().
findHighestBlockForPlacement()
static void findHighestBlockForPlacement (const MemRefRegion & region, Block & block, Block::iterator & begin, Block::iterator & end, Block ** copyPlacementBlock, Block::iterator * copyInPlacementStart, Block::iterator * copyOutPlacementStart) static
Given a memref region, determine the lowest depth at which transfers can be placed for it, and return the corresponding block, start and end positions in the block for placing incoming (read) and outgoing (write) copies respectively.
The lowest depth depends on whether the region being accessed is hoistable with respect to one or more immediately surrounding loops.
Definition at line 1124 of file LoopUtils.cpp.
References mlir::Block::begin(), mlir::MemRefRegion::getConstraints(), and mlir::getLoopIVs().
Referenced by mlir::affineDataCopyGenerate().
generateCopy()
static LogicalResult generateCopy (const MemRefRegion & region, Block * block, Block::iterator begin, Block::iterator end, Block * copyPlacementBlock, Block::iterator copyInPlacementStart, Block::iterator copyOutPlacementStart, AffineCopyOptions copyOptions, DenseMap< Value, Value > & fastBufferMap, DenseSet< Operation *> & copyNests, uint64_t * sizeInBytes, Block::iterator * nBegin, Block::iterator * nEnd) static
Creates a buffer in the faster memory space for the specified memref region; generates a copy from the lower memory space to this one, and replaces all loads/stores in the block range [`begin', `end') of `block' to load/store from that buffer.
Returns failure if copies could not be generated due to yet unimplemented cases. copyInPlacementStart and copyOutPlacementStart in copyPlacementBlock specify the insertion points where the incoming copies and outgoing copies, respectively, should be inserted (the insertion happens right before the insertion point). Since begin can itself be invalidated due to the memref rewriting done from this method, the output argument nBegin is set to its replacement (set to begin if no invalidation happens). Since outgoing copies could have been inserted at end, the output argument nEnd is set to the new end. sizeInBytes is set to the size of the fast buffer allocated.
Definition at line 1264 of file LoopUtils.cpp.
References mlir::Block::begin(), mlir::Type::cast(), mlir::OpBuilder::create(), emitRemarkForBlock(), mlir::failure(), mlir::AffineCopyOptions::fastMemorySpace, mlir::floorDiv(), mlir::fullyComposeAffineMapAndOperands(), mlir::AffineCopyOptions::generateDma, generatePointWiseCopy(), mlir::AffineMap::get(), mlir::MemRefType::get(), mlir::Builder::getAffineDimExpr(), mlir::MemRefType::getAffineMaps(), mlir::MemRefRegion::getConstantBoundingSizeAndShape(), mlir::MemRefRegion::getConstraints(), mlir::FlatAffineConstraints::getIdValues(), mlir::OpState::getLoc(), mlir::getMemRefSizeInBytes(), mlir::Builder::getMultiDimIdentityMap(), getMultiLevelStrides(), mlir::FlatAffineConstraints::getNumCols(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumIds(), mlir::FlatAffineConstraints::getNumSymbolIds(), mlir::Op< ConcreteType, Traits >::getOperation(), mlir::Block::getParent(), mlir::Region::getParentOfType(), mlir::OpState::getParentOfType(), mlir::Value::getType(), mlir::MemRefRegion::isWrite(), mlir::MemRefRegion::loc, mlir::functional::map(), mlir::MemRefRegion::memref, mlir::replaceAllMemRefUsesWith(), mlir::success(), and mlir::AffineCopyOptions::tagMemorySpace.
Referenced by mlir::affineDataCopyGenerate().
generateLoop()
static AffineForOp generateLoop (AffineMap lbMap, AffineMap ubMap, const std::vector< std::pair< uint64_t, ArrayRef< Operation *>>> & instGroupQueue, unsigned offset, AffineForOp srcForInst, OpBuilder b) static
Generates a 'affine.for' op with the specified lower and upper bounds while generating the right IV remappings for the shifted operations.
The operation blocks that go into the loop are specified in instGroupQueue starting from the specified offset, and in that order; the first element of the pair specifies the shift applied to that group of operations; note that the shift is multiplied by the loop step before being applied. Returns nullptr if the generated loop simplifies to a single iteration one.
Definition at line 167 of file LoopUtils.cpp.
References mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::AffineMap::getNumInputs(), mlir::Builder::getSingleDimShiftAffineMap(), mlir::BlockAndValueMapping::map(), mlir::promoteIfSingleIteration(), and mlir::succeeded().
Referenced by mlir::instBodySkew().
generatePointWiseCopy()
static AffineForOp generatePointWiseCopy (Location loc, Value memref, Value fastMemRef, AffineMap memAffineMap, ArrayRef< Value > memIndicesStart, ArrayRef< int64_t > fastBufferShape, bool isCopyOut, OpBuilder b) static
Generates a point-wise copy from/to `memref' to/from `fastMemRef' and returns the outermost AffineForOp of the copy loop nest.
`memIndicesStart' holds the lower coordinates of the region in the original memref to copy in/out. If `copyOut' is true, generates a copy-out; otherwise a copy-in.
Definition at line 1193 of file LoopUtils.cpp.
References mlir::OpBuilder::create(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getMultiDimIdentityMap(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResult().
Referenced by generateCopy().
getFullMemRefAsRegion()
static bool getFullMemRefAsRegion (Operation * opInst, unsigned numParamLoopIVs, MemRefRegion * region) static
Construct the memref region to just include the entire memref.
Returns false dynamic shaped memref's for now. numParamLoopIVs is the number of enclosing loop IVs of opInst (starting from the outermost) that the region is parametric on.
Definition at line 1547 of file LoopUtils.cpp.
References mlir::Type::cast(), mlir::extractForInductionVars(), mlir::MemRefRegion::getConstraints(), mlir::getLoopIVs(), mlir::Value::getType(), mlir::MemRefRegion::memref, and mlir::MemRefRegion::setWrite().
Referenced by mlir::affineDataCopyGenerate().
getMultiLevelStrides()
static void getMultiLevelStrides (const MemRefRegion & region, ArrayRef< int64_t > bufferShape, SmallVectorImpl< StrideInfo > * strideInfos) static
Returns striding information for a copy/transfer of this region with potentially multiple striding levels from outermost to innermost.
For an n-dimensional region, there can be at most n-1 levels of striding successively nested.
Definition at line 1168 of file LoopUtils.cpp.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::MemRefRegion::memref.
Referenced by generateCopy().
getPerfectlyNestedLoopsImpl()
template<typename T > static void getPerfectlyNestedLoopsImpl (SmallVectorImpl< T > & forOps, T rootForOp, unsigned maxLoops = std::numeric_limits<unsigned>::max()) static
Definition at line 354 of file LoopUtils.cpp.
References mlir::Block::begin(), mlir::Block::end(), and mlir::Block::front().
Referenced by mlir::extractFixedOuterLoops(), mlir::getPerfectlyNestedLoops(), and mlir::tilePerfectlyNested().
hoistOpsBetween()
static LogicalResult hoistOpsBetween (loop::ForOp outer, loop::ForOp inner) static
Definition at line 864 of file LoopUtils.cpp.
References mlir::failure(), mlir::getForwardSlice(), and mlir::success().
Referenced by tryIsolateBands().
normalizeLoop()
static void normalizeLoop (loop::ForOp loop, loop::ForOp outer, loop::ForOp inner) static
Definition at line 985 of file LoopUtils.cpp.
References ceilDivPositive(), mlir::OpBuilder::create(), replaceAllUsesExcept(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::coalesceLoops().
replaceAllUsesExcept()
static void replaceAllUsesExcept (Value orig, Value replacement, const SmallPtrSetImpl< Operation *> & exceptions) static
Definition at line 968 of file LoopUtils.cpp.
References mlir::Value::getUses().
Referenced by normalizeLoop().
stripmineSink() [1/3]
static SmallVector<AffineForOp, 8> stripmineSink (AffineForOp forOp, uint64_t factor, ArrayRef< AffineForOp > targets) static
Definition at line 681 of file LoopUtils.cpp.
References augmentMapAndBounds(), mlir::OpBuilder::create(), and mlir::replaceAllUsesInRegionWith().
Referenced by stripmineSink(), and tileImpl().
stripmineSink() [2/3]
static Loops stripmineSink (loop::ForOp forOp, Value factor, ArrayRef< loop::ForOp > targets) static
Definition at line 722 of file LoopUtils.cpp.
References mlir::OpBuilder::create(), and mlir::replaceAllUsesInRegionWith().
stripmineSink() [3/3]
template<typename ForType , typename SizeType > static ForType stripmineSink (ForType forOp, SizeType factor, ForType target) static
Definition at line 761 of file LoopUtils.cpp.
References stripmineSink().
tileImpl() [1/2]
template<typename ForType , typename SizeType > static SmallVector<SmallVector<ForType, 8>, 8> tileImpl (ArrayRef< ForType > forOps, ArrayRef< SizeType > sizes, ArrayRef< ForType > targets) static
Definition at line 773 of file LoopUtils.cpp.
References stripmineSink().
Referenced by mlir::tile().
tileImpl() [2/2]
template<typename ForType , typename SizeType > static SmallVector<ForType, 8> tileImpl (ArrayRef< ForType > forOps, ArrayRef< SizeType > sizes, ForType target) static
Definition at line 799 of file LoopUtils.cpp.
References mlir::tile().
tryIsolateBands()
static LogicalResult tryIsolateBands (const TileLoops & tileLoops) static
Definition at line 906 of file LoopUtils.cpp.
References mlir::failure(), hoistOpsBetween(), mlir::succeeded(), and mlir::success().
Referenced by mlir::extractFixedOuterLoops().