MLIR: lib/Dialect/FxpMathOps/Transforms/LowerUniformRealMath.cpp File Reference
LowerUniformRealMath.cpp File Reference
#include "UniformKernelUtils.h"
#include "mlir/Dialect/FxpMathOps/FxpMathOps.h"
#include "mlir/Dialect/FxpMathOps/Passes.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
Functions
static Value emitUniformPerLayerDequantize (Location loc, Value input, UniformQuantizedType elementType, PatternRewriter &rewriter)
static Value emitUniformPerAxisDequantize (Location loc, Value input, UniformQuantizedPerAxisType elementType, PatternRewriter &rewriter)
static Value emitDequantize (Location loc, Value input, PatternRewriter &rewriter)
static LogicalResult tryRewriteAffineAddEwIsomorphicSigned (const UniformBinaryOpInfo &info, PatternRewriter &rewriter)
static LogicalResult tryRewriteAffineMulEwSigned (const UniformBinaryOpInfo &info, PatternRewriter &rewriter)
Variables
static PassRegistration< LowerUniformRealMathPass > lowerUniformRealMathPass ("fxpmath-lower-uniform-real-math", "Lowers uniform-quantized real math ops to integer arithmetic.")
static PassRegistration< LowerUniformCastsPass > lowerUniformCastsPass ("fxpmath-lower-uniform-casts", "Lowers uniform-quantized casts.")
Function Documentation
emitDequantize()
static Value emitDequantize (Location loc, Value input, PatternRewriter & rewriter) static
Definition at line 91 of file LowerUniformRealMath.cpp.
References mlir::quant::QuantizedType::castToExpressedType(), mlir::Type::dyn_cast_or_null(), emitUniformPerAxisDequantize(), emitUniformPerLayerDequantize(), mlir::Value::getType(), and mlir::PatternRewriter::replaceOp().
emitUniformPerAxisDequantize()
static Value emitUniformPerAxisDequantize (Location loc, Value input, UniformQuantizedPerAxisType elementType, PatternRewriter & rewriter) static
Definition at line 82 of file LowerUniformRealMath.cpp.
References mlir::DiagnosticEngine::emit(), mlir::Builder::getContext(), mlir::MLIRContext::getDiagEngine(), and mlir::Warning.
Referenced by emitDequantize().
emitUniformPerLayerDequantize()
static Value emitUniformPerLayerDequantize (Location loc, Value input, UniformQuantizedType elementType, PatternRewriter & rewriter) static
Definition at line 40 of file LowerUniformRealMath.cpp.
References mlir::fxpmath::detail::broadcastScalarConstFloatValue(), mlir::fxpmath::detail::broadcastScalarConstIntValue(), mlir::fxpmath::detail::castElementType(), mlir::PatternRewriter::create(), mlir::emitWarning(), mlir::IntegerType::get(), mlir::Builder::getContext(), mlir::quant::UniformQuantizedType::getScale(), mlir::Value::getType(), and mlir::quant::UniformQuantizedType::getZeroPoint().
Referenced by emitDequantize().
tryRewriteAffineAddEwIsomorphicSigned()
static LogicalResult tryRewriteAffineAddEwIsomorphicSigned (const UniformBinaryOpInfo & info, PatternRewriter & rewriter) static
Definition at line 144 of file LowerUniformRealMath.cpp.
References mlir::fxpmath::detail::broadcastScalarConstIntValue(), mlir::fxpmath::detail::castElementType(), mlir::PatternRewriter::create(), mlir::failure(), mlir::IntegerType::get(), mlir::fxpmath::detail::UniformBinaryOpInfo::getClampMinMax(), mlir::Builder::getContext(), mlir::Operation::getLoc(), mlir::fxpmath::detail::UniformBinaryOpInfo::getQuantizedResultType(), mlir::quant::UniformQuantizedType::getZeroPoint(), mlir::fxpmath::detail::UniformBinaryOpInfo::lhs, mlir::fxpmath::detail::UniformBinaryOpInfo::lhsStorageType, mlir::fxpmath::detail::UniformBinaryOpInfo::lhsType, mlir::fxpmath::detail::UniformBinaryOpInfo::op, mlir::PatternRewriter::replaceOpWithNewOp(), mlir::fxpmath::detail::UniformBinaryOpInfo::resultStorageType, mlir::fxpmath::detail::UniformBinaryOpInfo::resultType, mlir::fxpmath::detail::UniformBinaryOpInfo::rhs, mlir::fxpmath::detail::UniformBinaryOpInfo::rhsStorageType, mlir::fxpmath::detail::UniformBinaryOpInfo::rhsType, and mlir::success().
Referenced by tryRewriteAffineMulEwSigned().
tryRewriteAffineMulEwSigned()
static LogicalResult tryRewriteAffineMulEwSigned (const UniformBinaryOpInfo & info, PatternRewriter & rewriter) static
Definition at line 216 of file LowerUniformRealMath.cpp.
References mlir::applyPatternsGreedily(), mlir::fxpmath::detail::broadcastScalarConstIntValue(), mlir::fxpmath::detail::castElementType(), mlir::PatternRewriter::create(), mlir::Operation::emitWarning(), mlir::failure(), mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::fxpmath::detail::UniformBinaryOpInfo::getClampMinMax(), mlir::Builder::getContext(), mlir::Operation::getLoc(), mlir::fxpmath::detail::UniformBinaryOpInfo::getQuantizedResultType(), mlir::quant::UniformQuantizedType::getScale(), mlir::quant::UniformQuantizedType::getZeroPoint(), mlir::OwningRewritePatternList::insert(), mlir::fxpmath::detail::UniformBinaryOpInfo::lhs, mlir::fxpmath::detail::UniformBinaryOpInfo::lhsStorageType, mlir::fxpmath::detail::UniformBinaryOpInfo::lhsType, mlir::fxpmath::detail::UniformBinaryOpInfo::op, mlir::PatternRewriter::replaceOpWithNewOp(), mlir::fxpmath::detail::UniformBinaryOpInfo::resultStorageType, mlir::fxpmath::detail::UniformBinaryOpInfo::resultType, mlir::fxpmath::detail::UniformBinaryOpInfo::rhs, mlir::fxpmath::detail::UniformBinaryOpInfo::rhsStorageType, mlir::fxpmath::detail::UniformBinaryOpInfo::rhsType, mlir::succeeded(), mlir::success(), and tryRewriteAffineAddEwIsomorphicSigned().
Variable Documentation
lowerUniformCastsPass
PassRegistration<LowerUniformCastsPass> lowerUniformCastsPass("fxpmath-lower-uniform-casts", "Lowers uniform-quantized casts.") static
Referenced by mlir::fxpmath::createLowerUniformCastsPass().
lowerUniformRealMathPass
PassRegistration<LowerUniformRealMathPass> lowerUniformRealMathPass("fxpmath-lower-uniform-real-math", "Lowers uniform-quantized real math ops to integer arithmetic.") static
Referenced by mlir::fxpmath::createLowerUniformRealMathPass().