MLIR: lib/Dialect/SPIRV/Transforms/LowerABIAttributesPass.cpp File Reference
LowerABIAttributesPass.cpp File Reference
#include "mlir/Dialect/SPIRV/LayoutUtils.h"
#include "mlir/Dialect/SPIRV/Passes.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVLowering.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/SetVector.h"
Functions
static bool isScalarOrVectorType (Type type)
Checks if the type is a scalar or vector type.
static spirv::GlobalVariableOp createGlobalVariableForArg (FuncOp funcOp, OpBuilder &builder, unsigned argNum, spirv::InterfaceVarABIAttr abiInfo)
Creates a global variable for an argument based on the ABI info.
static LogicalResult getInterfaceVariables (FuncOp funcOp, SmallVectorImpl< Attribute > &interfaceVars)
Gets the global variables that need to be specified as interface variable with an spv.EntryPointOp.
static LogicalResult lowerEntryPointABIAttr (FuncOp funcOp, OpBuilder &builder)
Lowers the entry point attribute.
Variables
static PassRegistration< LowerABIAttributesPass > pass ("spirv-lower-abi-attrs", "Lower SPIR-V ABI Attributes")
Function Documentation
createGlobalVariableForArg()
static spirv::GlobalVariableOp createGlobalVariableForArg (FuncOp funcOp, OpBuilder & builder, unsigned argNum, spirv::InterfaceVarABIAttr abiInfo) static
Creates a global variable for an argument based on the ABI info.
Definition at line 33 of file LowerABIAttributesPass.cpp.
References mlir::OpBuilder::create(), mlir::VulkanLayoutUtils::decorateType(), mlir::spirv::PointerType::get(), mlir::spirv::StructType::get(), mlir::FunctionType::getInput(), mlir::OpState::getLoc(), mlir::Op< ConcreteType, Traits >::getOperation(), mlir::OpState::getParentOfType(), mlir::FuncOp::getType(), isScalarOrVectorType(), and mlir::OpBuilder::setInsertionPoint().
Referenced by lowerEntryPointABIAttr().
getInterfaceVariables()
static LogicalResult getInterfaceVariables (FuncOp funcOp, SmallVectorImpl< Attribute > & interfaceVars) static
Gets the global variables that need to be specified as interface variable with an spv.EntryPointOp.
Traverses the body of a entry function to do so.
Definition at line 73 of file LowerABIAttributesPass.cpp.
References mlir::failure(), mlir::SymbolRefAttr::get(), mlir::OpState::getContext(), mlir::OpState::getParentOfType(), mlir::success(), and mlir::OpState::walk().
Referenced by lowerEntryPointABIAttr().
isScalarOrVectorType()
static bool isScalarOrVectorType (Type type) static
Checks if the type is a scalar or vector type.
It is assumed that they are valid for SPIR-V dialect already.
Definition at line 27 of file LowerABIAttributesPass.cpp.
References mlir::Type::isa(), and mlir::spirv::SPIRVDialect::isValidScalarType().
Referenced by createGlobalVariableForArg(), and lowerEntryPointABIAttr().
lowerEntryPointABIAttr()
static LogicalResult lowerEntryPointABIAttr (FuncOp funcOp, OpBuilder & builder) static
Lowers the entry point attribute.
Definition at line 100 of file LowerABIAttributesPass.cpp.
References mlir::applyPartialConversion(), mlir::ConversionPatternRewriter::applySignatureConversion(), mlir::PatternRewriter::create(), mlir::OpBuilder::create(), createGlobalVariableForArg(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::spirv::SPIRVConversionTarget::get(), mlir::IndexType::get(), mlir::OpState::getAttrOfType(), mlir::OpState::getContext(), mlir::spirv::getEntryPointABIAttrName(), mlir::Builder::getFunctionType(), mlir::FunctionType::getInputs(), mlir::spirv::getInterfaceVarABIAttrName(), getInterfaceVariables(), mlir::OpState::getLoc(), mlir::FunctionType::getNumInputs(), mlir::OpState::getParentOfType(), mlir::FuncOp::getType(), mlir::OwningRewritePatternList::insert(), isScalarOrVectorType(), mlir::spirv::lookupTargetEnvOrDefault(), mlir::StandardTypes::None, mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), mlir::FuncOp::setType(), mlir::success(), and mlir::PatternRewriter::updateRootInPlace().
Variable Documentation
pass
PassRegistration<LowerABIAttributesPass> pass("spirv-lower-abi-attrs", "Lower SPIR-V ABI Attributes") static
Referenced by mlir::spirv::createLowerABIAttributesPass().