MLIR: lib/IR/MLIRContext.cpp File Reference
MLIRContext.cpp File Reference
#include "mlir/IR/MLIRContext.h"
#include "AffineExprDetail.h"
#include "AffineMapDetail.h"
#include "AttributeDetail.h"
#include "IntegerSetDetail.h"
#include "LocationDetail.h"
#include "TypeDetail.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Identifier.h"
#include "mlir/IR/IntegerSet.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/Types.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/RWMutex.h"
#include "llvm/Support/raw_ostream.h"
#include <memory>
Classes
class mlir::MLIRContextImpl
This is the implementation of the MLIRContext class, using the pImpl idiom.
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
Functions
template<typename ValueT , typename DenseInfoT , typename KeyT , typename ConstructorFn >
static ValueT safeGetOrCreate (DenseSet< ValueT, DenseInfoT > &container, KeyT &&key, llvm::sys::SmartRWMutex< true > &mutex, ConstructorFn &&constructorFn)
A utility function to safely get or create a uniqued instance within the given set container.
template<typename T >
static ArrayRef< T > copyArrayRefInto (llvm::BumpPtrAllocator &allocator, ArrayRef< T > elements)
Copy the specified array of elements into memory managed by the provided bump pointer allocator.
static Dialect & lookupDialectForSymbol (MLIRContext *ctx, const ClassID *const classID)
static IntegerType getCachedIntegerType (unsigned width, MLIRContext *context)
Return an existing integer type instance if one is cached within the context.
Function Documentation
copyArrayRefInto()
template<typename T > static ArrayRef<T> copyArrayRefInto (llvm::BumpPtrAllocator & allocator, ArrayRef< T > elements) static
Copy the specified array of elements into memory managed by the provided bump pointer allocator.
This assumes the elements are all PODs.
Definition at line 283 of file MLIRContext.cpp.
Referenced by mlir::IntegerSet::get().
getCachedIntegerType()
static IntegerType getCachedIntegerType (unsigned width, MLIRContext * context) static
Return an existing integer type instance if one is cached within the context.
Definition at line 492 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl(), mlir::MLIRContextImpl::int128Ty, mlir::MLIRContextImpl::int16Ty, mlir::MLIRContextImpl::int1Ty, mlir::MLIRContextImpl::int32Ty, mlir::MLIRContextImpl::int64Ty, and mlir::MLIRContextImpl::int8Ty.
Referenced by mlir::IntegerType::get(), and mlir::IntegerType::getChecked().
lookupDialectForSymbol()
static Dialect& lookupDialectForSymbol (MLIRContext * ctx, const ClassID *const classID) static
Definition at line 450 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl().
Referenced by mlir::MLIRContext::getAttributeUniquer(), and mlir::MLIRContext::getTypeUniquer().
safeGetOrCreate()
template<typename ValueT , typename DenseInfoT , typename KeyT , typename ConstructorFn > static ValueT safeGetOrCreate (DenseSet< ValueT, DenseInfoT > & container, KeyT && key, llvm::sys::SmartRWMutex< true > & mutex, ConstructorFn && constructorFn) static
A utility function to safely get or create a uniqued instance within the given set container.
Definition at line 48 of file MLIRContext.cpp.
References mlir::IntegerSet::getConstraints(), mlir::IntegerSet::getEqFlags(), mlir::IntegerSet::getNumDims(), mlir::AffineMap::getNumDims(), mlir::IntegerSet::getNumSymbols(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by mlir::IntegerSet::get(), and mlir::MLIRContext::getAffineUniquer().