MLIR: mlir::edsc::op Namespace Reference
mlir::edsc::op Namespace Reference
Functions
ValueHandle operator+ (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator- (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator* (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator/ (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator% (ValueHandle lhs, ValueHandle rhs)
ValueHandle floorDiv (ValueHandle lhs, ValueHandle rhs)
ValueHandle ceilDiv (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator! (ValueHandle value)
ValueHandle operator && (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator|| (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator^ (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator== (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator!= (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator< (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator<= (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator> (ValueHandle lhs, ValueHandle rhs)
ValueHandle operator>= (ValueHandle lhs, ValueHandle rhs)
Function Documentation
ceilDiv()
ValueHandle mlir::edsc::op::ceilDiv (ValueHandle lhs, ValueHandle rhs)
Definition at line 433 of file Builders.cpp.
References mlir::AffineExpr::ceilDiv(), and createBinaryIndexHandle().
floorDiv()
ValueHandle mlir::edsc::op::floorDiv (ValueHandle lhs, ValueHandle rhs)
Definition at line 428 of file Builders.cpp.
References createBinaryIndexHandle(), and mlir::AffineExpr::floorDiv().
operator &&()
ValueHandle mlir::edsc::op::operator&& (ValueHandle lhs, ValueHandle rhs)
Referenced by operator!().
operator!()
ValueHandle mlir::edsc::op::operator! (ValueHandle value)
Definition at line 438 of file Builders.cpp.
References mlir::edsc::ValueHandle::getType(), mlir::Type::isInteger(), and operator &&().
operator!=()
ValueHandle mlir::edsc::op::operator!= (ValueHandle lhs, ValueHandle rhs)
Definition at line 489 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::ValueHandle::getType(), mlir::Type::isa(), and mlir::ONE.
operator%()
ValueHandle mlir::edsc::op::operator% (ValueHandle lhs, ValueHandle rhs)
Definition at line 423 of file Builders.cpp.
Referenced by mlir::AffineExpr::operator!().
operator*()
ValueHandle mlir::edsc::op::operator* (ValueHandle lhs, ValueHandle rhs)
Definition at line 411 of file Builders.cpp.
operator+()
ValueHandle mlir::edsc::op::operator+ (ValueHandle lhs, ValueHandle rhs)
Definition at line 401 of file Builders.cpp.
operator-()
ValueHandle mlir::edsc::op::operator- (ValueHandle lhs, ValueHandle rhs)
Definition at line 406 of file Builders.cpp.
operator/()
ValueHandle mlir::edsc::op::operator/ (ValueHandle lhs, ValueHandle rhs)
Definition at line 416 of file Builders.cpp.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getBase().
operator<()
ValueHandle mlir::edsc::op::operator< (ValueHandle lhs, ValueHandle rhs)
Definition at line 495 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::ValueHandle::getType(), mlir::Type::isa(), and mlir::OLT.
operator<=()
ValueHandle mlir::edsc::op::operator<= (ValueHandle lhs, ValueHandle rhs)
Definition at line 503 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::ValueHandle::getType(), mlir::Type::isa(), and mlir::OLE.
operator==()
ValueHandle mlir::edsc::op::operator== (ValueHandle lhs, ValueHandle rhs)
Definition at line 483 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::ValueHandle::getType(), mlir::Type::isa(), and mlir::OEQ.
operator>()
ValueHandle mlir::edsc::op::operator> (ValueHandle lhs, ValueHandle rhs)
Definition at line 509 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::ValueHandle::getType(), mlir::Type::isa(), and mlir::OGT.
operator>=()
ValueHandle mlir::edsc::op::operator>= (ValueHandle lhs, ValueHandle rhs)
Definition at line 515 of file Builders.cpp.
References createFComparisonExpr(), createIComparisonExpr(), mlir::edsc::ValueHandle::getType(), mlir::Type::isa(), and mlir::OGE.
operator^()
ValueHandle mlir::edsc::op::operator^ (ValueHandle lhs, ValueHandle rhs)
operator||()
ValueHandle mlir::edsc::op::operator|| (ValueHandle lhs, ValueHandle rhs)
Definition at line 449 of file Builders.cpp.