MLIR: mlir::quantizer Namespace Reference
mlir::quantizer Namespace Reference
Classes
class AbstractTensorStatistics
Base class for querying statistics about a tensor.
class AttributeTensorStatistics
Wraps an MLIR Attribute and returns statistics about it.
class BasePropagatedFact
A fact that can converge through forward propagation alone without the need to track ownership or individual assertions.
class CAGAnchorNode
Anchor nodes represent points in the source IR where we may choose to introduce a type transition.
class CAGConstraintNode
Base class for constraint nodes.
class CAGNode
A node in the Constraint Analysis Graph.
class CAGOperandAnchor
An anchor tied to a specific operand.
class CAGResultAnchor
An anchor tied to a specific result.
class CAGSlice
A slice of a CAG (which may be the whole graph).
struct CAGUniformMetadata
struct CandidateQuantizedType
Candidate for a quantized type conversion.
struct DiscreteReducer
A fact and reducer for tracking agreement of discrete values.
struct ExpandingMinMaxReducer
A binary reducer that expands a min/max range represented by a pair of doubles such that it represents the largest of all inputs.
class FxpMathTargetConfig
Target configuration for a reference affine/fixed-point quantization scheme defined in terms of the FxpMathOps dialect.
struct MaximizingNumericReducer
A binary reducer that maximizes a numeric type.
struct MinimizingNumericReducer
A binary reducer that minimizing a numeric type.
struct ModificationResult
Typed indicator of whether a mutator produces a modification.
class SolverContext
class TargetConfiguration
Defines quantization configuration for the target.
struct TensorAxisStatistics
Statistics about a tensor axis (or the whole tensor).
class UniformConstraintsBuilder
Factory methods for adding CAG constraints of various kinds suitable for solving for uniform quantization.
class UniformParamsFromMinMaxSolver
Solves for the uniform quantization scheme parameters delta and z given bounding min/max.
struct UniformStorageParams
Typedefs
using ExpandingMinMaxFact = BasePropagatedFact< ExpandingMinMaxReducer >
using MinimizingDoubleFact = BasePropagatedFact< MinimizingNumericReducer< double > >
using MinimizingIntFact = BasePropagatedFact< MinimizingNumericReducer< int > >
using MaximizingDoubleFact = BasePropagatedFact< MaximizingNumericReducer< double > >
using MaximizingIntFact = BasePropagatedFact< MaximizingNumericReducer< int > >
template<typename T >
using DiscreteFact = BasePropagatedFact< DiscreteReducer< T > >
using DiscreteScaleZeroPointFact = DiscreteFact< std::pair< double, int64_t > >
Discrete scale/zeroPoint fact.
Functions
raw_ostream & operator<< (raw_ostream &os, const CAGNode &node)
ModificationResult modify (bool isModified=true)
bool modified (ModificationResult m)
raw_ostream & operator<< (raw_ostream &os, const TensorAxisStatistics &stats)
Type getElementOrPrimitiveType (Type t)
Given an arbitrary container or primitive type, returns the element type, where the element type is just the type for non-containers.
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const UniformStorageParams &p)
llvm::raw_ostream & operator<< (llvm::raw_ostream &os, const UniformParamsFromMinMaxSolver &s)
std::unique_ptr< OpPassBase< ModuleOp > > createInferQuantizedTypesPass (SolverContext &solverContext, const TargetConfiguration &config)
Creates a pass that infers quantized types based on metadata discovered in the computation.
std::unique_ptr< OpPassBase< FuncOp > > createRemoveInstrumentationPass ()
Creates a pass which removes any instrumentation and hint ops which have no effect on final runtime.
std::unique_ptr< OpPassBase< FuncOp > > createAddDefaultStatsPass ()
Adds default (dummy) statistics to ops that can benefit from runtime stats.
Typedef Documentation
DiscreteFact
template<typename T > using mlir::quantizer::DiscreteFact = typedef BasePropagatedFact<DiscreteReducer<T> >
Definition at line 192 of file Rules.h.
DiscreteScaleZeroPointFact
using mlir::quantizer::DiscreteScaleZeroPointFact = typedef DiscreteFact<std::pair<double, int64_t> >
Discrete scale/zeroPoint fact.
Definition at line 195 of file Rules.h.
ExpandingMinMaxFact
using mlir::quantizer::ExpandingMinMaxFact = typedef BasePropagatedFact<ExpandingMinMaxReducer>
Definition at line 120 of file Rules.h.
MaximizingDoubleFact
using mlir::quantizer::MaximizingDoubleFact = typedef BasePropagatedFact<MaximizingNumericReducer<double> >
Definition at line 153 of file Rules.h.
MaximizingIntFact
using mlir::quantizer::MaximizingIntFact = typedef BasePropagatedFact<MaximizingNumericReducer<int> >
Definition at line 154 of file Rules.h.
MinimizingDoubleFact
using mlir::quantizer::MinimizingDoubleFact = typedef BasePropagatedFact<MinimizingNumericReducer<double> >
Definition at line 136 of file Rules.h.
MinimizingIntFact
using mlir::quantizer::MinimizingIntFact = typedef BasePropagatedFact<MinimizingNumericReducer<int> >
Definition at line 137 of file Rules.h.
Function Documentation
createAddDefaultStatsPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::quantizer::createAddDefaultStatsPass ()
Adds default (dummy) statistics to ops that can benefit from runtime stats.
Meant for testing.
Definition at line 113 of file AddDefaultStatsTestPass.cpp.
References pass.
createInferQuantizedTypesPass()
std::unique_ptr< OpPassBase< ModuleOp > > mlir::quantizer::createInferQuantizedTypesPass (SolverContext & solverContext, const TargetConfiguration & config)
Creates a pass that infers quantized types based on metadata discovered in the computation.
Definition at line 281 of file InferQuantizedTypesPass.cpp.
References pass.
createRemoveInstrumentationPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::quantizer::createRemoveInstrumentationPass ()
Creates a pass which removes any instrumentation and hint ops which have no effect on final runtime.
Definition at line 61 of file RemoveInstrumentationPass.cpp.
References pass.
getElementOrPrimitiveType()
Type mlir::quantizer::getElementOrPrimitiveType (Type t)
Given an arbitrary container or primitive type, returns the element type, where the element type is just the type for non-containers.
Definition at line 16 of file TypeUtils.cpp.
References mlir::Type::dyn_cast().
Referenced by solveUniformType().
modified()
bool mlir::quantizer::modified (ModificationResult m) inline
Definition at line 52 of file Rules.h.
References mlir::quantizer::ModificationResult::Modified, and mlir::quantizer::ModificationResult::value.
Referenced by convertToLaunchFuncOp(), and solveUniformType().
modify()
ModificationResult mlir::quantizer::modify (bool isModified = true) inline
Definition at line 47 of file Rules.h.
References mlir::quantizer::ModificationResult::Modified, and mlir::quantizer::ModificationResult::Retained.
Referenced by mlir::quantizer::BasePropagatedFact< ExpandingMinMaxReducer >::assertValue(), and mlir::quantizer::BasePropagatedFact< ExpandingMinMaxReducer >::mergeFrom().
operator<<() [1/4]
llvm::raw_ostream& mlir::quantizer::operator<< (llvm::raw_ostream & os, const UniformStorageParams & p)
operator<<() [2/4]
raw_ostream & mlir::quantizer::operator<< (raw_ostream & os, const TensorAxisStatistics & stats)
Definition at line 89 of file Statistics.cpp.
References mlir::quantizer::TensorAxisStatistics::maxValue, mlir::quantizer::TensorAxisStatistics::mean, mlir::quantizer::TensorAxisStatistics::minValue, mlir::quantizer::TensorAxisStatistics::sampleSize, and mlir::quantizer::TensorAxisStatistics::variance.
operator<<() [3/4]
llvm::raw_ostream& mlir::quantizer::operator<< (llvm::raw_ostream & os, const UniformParamsFromMinMaxSolver & s)
operator<<() [4/4]
raw_ostream& mlir::quantizer::operator<< (raw_ostream & os, const CAGNode & node) inline
Definition at line 352 of file ConstraintAnalysisGraph.h.
References mlir::quantizer::CAGNode::printLabel().
Referenced by mlir::quantizer::AttributeTensorStatistics::AttributeTensorStatistics(), and mlir::quantizer::UniformParamsFromMinMaxSolver::dequantize().