MLIR: mlir::detail Namespace Reference
mlir::detail Namespace Reference
Utilities for detecting if a given trait holds for some set of arguments 'Args'.
Namespaces
analysis_impl
Classes
struct AffineBinaryOpExprStorage
A binary operation appearing in an affine expression.
struct AffineConstantExprStorage
An integer constant appearing in affine expression.
struct AffineDimExprStorage
A dimensional or symbolic identifier appearing in an affine expression.
struct AffineExprStorage
Base storage class appearing in an affine expression.
struct AffineMapAttributeStorage
struct AffineMapStorage
struct AnalysisConcept
The abstract polymorphic base class representing an analysis.
class AnalysisMap
This class represents a cache of analyses for a single operation.
struct AnalysisModel
A derived analysis model used to hold a specific analysis object.
struct AnyValueMatcher
Terminal matcher, always returns true.
struct ArrayAttributeStorage
An attribute representing an array of other attributes.
class AsmStateImpl
struct attr_value_binder
The matcher that matches a certain kind of Attribute and binds the value inside the Attribute.
class AttributeUniquer
class BlockArgumentImpl
The internal implementation of a BlockArgument.
struct BoolAttributeStorage
An attribute representing a boolean value.
struct CallSiteLocationStorage
struct ComplexTypeStorage
Complex Type Storage.
struct constant_int_not_value_matcher
The matcher that matches anything except the given target constant scalar / vector splat / tensor splat integer value.
struct constant_int_op_binder
The matcher that matches a constant scalar / vector splat / tensor splat integer operation and binds the constant integer value.
struct constant_int_value_matcher
The matcher that matches a given target constant scalar / vector splat / tensor splat integer value.
struct constant_op_binder
The matcher that matches a constant foldable operation that has no side effect, no operands and produces a single result.
struct ConversionPatternRewriterImpl
class DenseElementDataPointerTypeTraits
DenseElementsAttr data is aligned to uint64_t, so this traits class is necessary to interop with PointerIntPair.
class DenseElementIndexedIteratorImpl
Impl iterator for indexed DenseElementAttr iterators that records a data pointer and data index that is adjusted for the case of a splat attribute.
struct DenseElementsAttributeStorage
An attribute representing a reference to a dense vector or tensor object.
struct detector
struct detector< void_t< Op< Args... > >, Op, Args... >
struct DiagnosticEngineImpl
class DialectInterfaceBase
The base class used for all derived interface types.
class DialectInterfaceCollectionBase
This class is the base class for a collection of instances for a specific interface kind.
struct DictionaryAttributeStorage
An attribute representing a dictionary of sorted named attributes.
class DominanceInfoBase
class ElementsAttrIterator
This class represents a general iterator over the values of an ElementsAttr.
class ElementsAttrRange
struct ExpectedDiag
struct FileLineColLocationStorage
struct FloatAttributeStorage
An attribute representing a floating point value.
struct FunctionTypeStorage
Function Type Storage and Uniquing.
struct FusedLocationStorage
class indexed_accessor_range_base
The class represents the base of a range of indexed_accessor_iterators.
struct IntegerAttributeStorage
An attribute representing a integral value.
struct IntegerSetAttributeStorage
struct IntegerSetStorage
struct IntegerTypeStorage
Integer Type Storage and Uniquing.
struct MemRefTypeStorage
struct NameLocationStorage
struct NestedAnalysisMap
An analysis map that contains a map for the current operation, and a set of maps for any child operations.
struct op_matcher
The matcher that matches a certain kind of op.
struct OpaqueAttributeStorage
Opaque Attribute Storage and Uniquing.
struct OpaqueElementsAttributeStorage
An attribute representing a reference to a tensor constant with opaque content.
struct OpaqueLocationStorage
struct OpaqueTypeStorage
Opaque Type Storage and Uniquing.
class OpaqueValue
This class provides an opaque type erased wrapper around a Value.
class OperandStorage
This class handles the management of operation operands.
struct OpPassManagerImpl
class OpToOpPassAdaptor
An adaptor pass used to run operation passes over nested operations synchronously on a single thread.
class OpToOpPassAdaptorBase
A base class for Op-to-Op adaptor passes.
class OpToOpPassAdaptorParallel
An adaptor pass used to run operation passes over nested operations asynchronously across multiple threads.
struct ParallelDiagnosticHandlerImpl
struct PassExecutionState
The state for a single execution of a pass.
struct PassInstrumentorImpl
class PassModel
The opaque CRTP model of a pass.
class PassOptions
Base container class and manager for all pass options.
struct PassPipelineCLParserImpl
struct PatternMatcherValue
Binds to a specific value and matches it.
class PreservedAnalyses
A utility class to represent the analyses that are known to be preserved.
struct RankedTensorTypeStorage
struct RecursivePatternMatcher
RecursivePatternMatcher that composes.
struct ResizableStorage
A utility class holding the information necessary to dynamically resize operands.
struct SDBMBinaryExprStorage
struct SDBMConstantExprStorage
struct SDBMDiffExprStorage
struct SDBMExprStorage
struct SDBMNegExprStorage
struct SDBMTermExprStorage
struct ShapedTypeStorage
Shaped Type Storage.
struct SourceMgrDiagnosticHandlerImpl
struct SourceMgrDiagnosticVerifierHandlerImpl
struct SparseElementsAttributeStorage
An attribute representing a reference to a sparse vector or tensor object.
struct StorageUniquerImpl
This is the implementation of the StorageUniquer class.
class StorageUserBase
Utility class for implementing users of storage classes uniqued by a StorageUniquer.
struct StringAttributeStorage
An attribute representing a string value.
struct SymbolRefAttributeStorage
An attribute representing a symbol reference.
struct TrailingOpResult
This class provides the implementation for a trailing operation result.
struct TupleTypeStorage
A type representing a collection of other types.
struct TypeAttributeStorage
An attribute representing a reference to a type.
class TypeSwitchBase
class TypeUniquer
struct UnrankedMemRefTypeStorage
Unranked MemRef is a MemRef with unknown rank.
struct UnrankedTensorTypeStorage
struct ValueRangeOwner
The type representing the owner of a ValueRange.
class ValueUseIteratorImpl
A base iterator class that allows for iterating over the uses of a value.
struct VectorTypeStorage
Vector Type Storage and Uniquing.
class VerifierPass
Pass to verify an operation and signal failure if necessary.
Typedefs
using DenseIterPtrAndSplat = llvm::PointerIntPair< const char *, 1, bool, DenseElementDataPointerTypeTraits >
Pair of raw pointer and a boolean flag of whether the pointer holds a splat,.
template<typename T , typename OperationOrValue >
using has_operation_or_value_matcher_t = decltype(std::declval< T >().match(std::declval< OperationOrValue >()))
Trait to check whether T provides a 'match' method with type OperationOrValue.
template<typename T >
using first_argument = decltype(first_argument_type(std::declval< T >()))
Type definition of the first argument to the given callable 'T'.
template<typename FnT >
using walkResultType = decltype(walkOperations(nullptr, std::declval< FnT >()))
Utility to provide the return type of a templated walk method.
template<typename RangeT >
using ValueOfRange = typename std::remove_reference< decltype(*std::begin(std::declval< RangeT & >()))>::type
template<typename... >
using void_t = void
template<typename Callable , typename... Args>
using is_invocable = decltype(std::declval< Callable & >()(std::declval< Args >()...))
template<typename ImplTy , typename... Args>
using has_impltype_getkey_t = decltype(ImplTy::getKey(std::declval< Args >()...))
Trait to check if ImplTy provides a 'getKey' method with types 'Args'.
template<typename ImplTy , typename T >
using has_impltype_hash_t = decltype(ImplTy::hashKey(std::declval< T >()))
Trait to check if ImplTy provides a 'hashKey' method for 'T'.
Functions
LogicalResult inferReturnTensorTypes (function_ref< LogicalResult(MLIRContext *, Optional< Location > location, ValueRange operands, ArrayRef< NamedAttribute > attributes, RegionRange regions, SmallVectorImpl< ShapedTypeComponents > &retComponents)> componentTypeFn, MLIRContext *context, Optional< Location > location, ValueRange operands, ArrayRef< NamedAttribute > attributes, RegionRange regions, SmallVectorImpl< Type > &inferedReturnTypes)
LogicalResult verifyInferredResultTypes (Operation *op)
Verifies that the inferred result types match the actual result types for the op.
template<int N>
void bindDims (MLIRContext *ctx)
template<int N, typename AffineExprTy , typename... AffineExprTy2>
void bindDims (MLIRContext *ctx, AffineExprTy &e, AffineExprTy2 &... exprs)
template<typename MatcherClass >
std::enable_if_t< is_detected< detail::has_operation_or_value_matcher_t, MatcherClass, Value >::value, bool > matchOperandOrValueAtIndex (Operation *op, unsigned idx, MatcherClass &matcher)
Statically switch to a Value matcher.
template<typename MatcherClass >
std::enable_if_t< is_detected< detail::has_operation_or_value_matcher_t, MatcherClass, Operation * >::value, bool > matchOperandOrValueAtIndex (Operation *op, unsigned idx, MatcherClass &matcher)
Statically switch to an Operation matcher.
template<typename TupleT , class CallbackT , std::size_t... Is>
constexpr void enumerateImpl (TupleT &&tuple, CallbackT &&callback, std::index_sequence< Is... >)
template<typename... Tys, typename CallbackT >
constexpr void enumerate (std::tuple< Tys... > &tuple, CallbackT &&callback)
template<typename Ret , typename Arg >
Arg first_argument_type (Ret(*)(Arg))
Helper templates to deduce the first argument of a callback parameter.
template<typename Ret , typename F , typename Arg >
Arg first_argument_type (Ret(F::*)(Arg))
void walkOperations (Operation *op, function_ref< void(Operation *op)> callback)
Walk all of the operations nested under and including the given operation.
WalkResult walkOperations (Operation *op, function_ref< WalkResult(Operation *op)> callback)
Walk all of the operations nested under and including the given operation.
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))>
std::enable_if< std::is_same< ArgT, Operation * >::value, RetT >::type walkOperations (Operation *op, FuncTy &&callback)
Walk all of the operations nested under and including the given operation.
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))>
std::enable_if<!std::is_same< ArgT, Operation * >::value &&std::is_same< RetT, void >::value, RetT >::type walkOperations (Operation *op, FuncTy &&callback)
Walk all of the operations of type 'ArgT' nested under and including the given operation.
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))>
std::enable_if<!std::is_same< ArgT, Operation * >::value &&std::is_same< RetT, WalkResult >::value, RetT >::type walkOperations (Operation *op, FuncTy &&callback)
Walk all of the operations of type 'ArgT' nested under and including the given operation.
OpToOpPassAdaptorBase * getAdaptorPassBase (Pass *pass)
Utility function to convert the given class to the base adaptor it is an adaptor pass, returns nullptr otherwise.
bool isAdaptorPass (Pass *pass)
Utility function to return if a pass refers to an adaptor pass.
Variables
template<typename F >
decltype(first_argument_type(&F::operator())) first_argument_type (F)
Detailed Description
Utilities for detecting if a given trait holds for some set of arguments 'Args'.
Check if a Callable type can be invoked with the given set of arg types.
For example, the given trait could be used to detect if a given type has a copy assignment operator: template<class T> using has_copy_assign_t = decltype(std::declval<T&>() = std::declval<const T&>()); bool fooHasCopyAssign = is_detected<has_copy_assign_t, FooClass>::value;
Typedef Documentation
DenseIterPtrAndSplat
using mlir::detail::DenseIterPtrAndSplat = typedef llvm::PointerIntPair<const char *, 1, bool, DenseElementDataPointerTypeTraits>
Pair of raw pointer and a boolean flag of whether the pointer holds a splat,.
Definition at line 632 of file Attributes.h.
first_argument
template<typename T > using mlir::detail::first_argument = typedef decltype(first_argument_type(std::declval<T>()))
Type definition of the first argument to the given callable 'T'.
Definition at line 62 of file Visitors.h.
has_impltype_getkey_t
template<typename ImplTy , typename... Args> using mlir::detail::has_impltype_getkey_t = typedef decltype(ImplTy::getKey(std::declval<Args>()...))
Trait to check if ImplTy provides a 'getKey' method with types 'Args'.
Definition at line 23 of file StorageUniquer.h.
has_impltype_hash_t
template<typename ImplTy , typename T > using mlir::detail::has_impltype_hash_t = typedef decltype(ImplTy::hashKey(std::declval<T>()))
Trait to check if ImplTy provides a 'hashKey' method for 'T'.
Definition at line 27 of file StorageUniquer.h.
has_operation_or_value_matcher_t
template<typename T , typename OperationOrValue > using mlir::detail::has_operation_or_value_matcher_t = typedef decltype(std::declval<T>().match(std::declval<OperationOrValue>()))
Trait to check whether T provides a 'match' method with type OperationOrValue.
Definition at line 136 of file Matchers.h.
is_invocable
template<typename Callable , typename... Args> using mlir::detail::is_invocable = typedef decltype(std::declval<Callable &>()(std::declval<Args>()...))
Definition at line 131 of file STLExtras.h.
ValueOfRange
template<typename RangeT > using mlir::detail::ValueOfRange = typedef typename std::remove_reference<decltype(*std::begin(std::declval<RangeT &>()))>::type
Definition at line 25 of file STLExtras.h.
void_t
template<typename... > using mlir::detail::void_t = typedef void
Definition at line 114 of file STLExtras.h.
walkResultType
template<typename FnT > using mlir::detail::walkResultType = typedef decltype(walkOperations(nullptr, std::declval<FnT>()))
Utility to provide the return type of a templated walk method.
Definition at line 138 of file Visitors.h.
Function Documentation
bindDims() [1/2]
template<int N> void mlir::detail::bindDims (MLIRContext * ctx)
Definition at line 274 of file AffineExpr.h.
Referenced by bindDims().
bindDims() [2/2]
template<int N, typename AffineExprTy , typename... AffineExprTy2> void mlir::detail::bindDims (MLIRContext * ctx, AffineExprTy & e, AffineExprTy2 &... exprs)
Definition at line 277 of file AffineExpr.h.
References bindDims(), and mlir::getAffineDimExpr().
enumerate()
template<typename... Tys, typename CallbackT > constexpr void mlir::detail::enumerate (std::tuple< Tys... > & tuple, CallbackT && callback)
Definition at line 180 of file Matchers.h.
References enumerateImpl().
Referenced by mlir::AffineApplyNormalizer::AffineApplyNormalizer(), clip(), cloneWithLoopRanges(), coalesceCopy(), computeConversionSet(), mlir::LLVMTypeConverter::convertFunctionSignature(), convertLinalgType(), mlir::SPIRVTypeConverter::convertType(), createLaunchFromOp(), fuse(), generateTransferOpSlices(), getBackwardSliceImpl(), getDimMap(), getElementPtr(), getI64SubArray(), getICmpPredicate(), getPHISourceValue(), getTypeNumBytes(), getViewDefiningLoopRange(), indicesFromAffineApplyOp(), insertCopyLoops(), mlir::inversePermutation(), mlir::isInstwiseShiftValid(), isReassociationValid(), mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraph(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), makeCanonicalStridedLayoutExpr(), mlir::edsc::makeGenericLinalgOp(), mlir::makeStridedLinearLayoutMap(), mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::match(), mlir::detail::ConversionPatternRewriterImpl::notifyRegionIsBeingInlinedBefore(), mlir::operator<<(), packFunctionArguments(), parseOptionalKeywordAlternative(), printResultsAsList(), promoteFullTileBuffer(), mlir::replaceAllMemRefUsesWith(), resolveSourceIndices(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), topologicalSort(), mlir::OpBuilder::tryFold(), verify(), and verifyGenericOp().
enumerateImpl()
template<typename TupleT , class CallbackT , std::size_t... Is> constexpr void mlir::detail::enumerateImpl (TupleT && tuple, CallbackT && callback, std::index_sequence< Is... >)
Definition at line 171 of file Matchers.h.
Referenced by enumerate().
first_argument_type() [1/2]
template<typename Ret , typename Arg > Arg mlir::detail::first_argument_type (Ret(*)(Arg))
Helper templates to deduce the first argument of a callback parameter.
first_argument_type() [2/2]
template<typename Ret , typename F , typename Arg > Arg mlir::detail::first_argument_type (Ret(F::*)(Arg))
Referenced by mlir::WalkResult::wasInterrupted().
getAdaptorPassBase()
OpToOpPassAdaptorBase * mlir::detail::getAdaptorPassBase (Pass * pass)
Utility function to convert the given class to the base adaptor it is an adaptor pass, returns nullptr otherwise.
Definition at line 490 of file Pass.cpp.
Referenced by mlir::detail::OpPassManagerImpl::coalesceAdjacentAdaptorPasses(), mlir::detail::OpToOpPassAdaptorParallel::getParallelPassManagers(), mlir::OpPassManager::mergeStatisticsInto(), prepareStatistics(), mlir::Pass::printAsTextualPipeline(), printResultsAsList(), and printResultsAsPipeline().
inferReturnTensorTypes()
LogicalResult mlir::detail::inferReturnTensorTypes (function_ref< LogicalResult(MLIRContext *, Optional< Location > location, ValueRange operands, ArrayRef< NamedAttribute > attributes, RegionRange regions, SmallVectorImpl< ShapedTypeComponents > &retComponents)> componentTypeFn, MLIRContext * context, Optional< Location > location, ValueRange operands, ArrayRef< NamedAttribute > attributes, RegionRange regions, SmallVectorImpl< Type > & inferedReturnTypes)
Definition at line 24 of file InferTypeOpInterface.cpp.
References mlir::failed(), mlir::failure(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), and mlir::success().
Referenced by mlir::ShapedTypeComponents::getAttribute(), and mlir::OpTrait::InferTensorType< ConcreteType >::inferReturnTypes().
isAdaptorPass()
bool mlir::detail::isAdaptorPass (Pass * pass) inline
Utility function to return if a pass refers to an adaptor pass.
Adaptor passes are those that internally execute a pipeline.
Definition at line 89 of file PassDetail.h.
References pass.
Referenced by mlir::detail::OpPassManagerImpl::coalesceAdjacentAdaptorPasses(), isHiddenPass(), and printIR().
matchOperandOrValueAtIndex() [1/2]
template<typename MatcherClass > std::enable_if_t<is_detected<detail::has_operation_or_value_matcher_t, MatcherClass, Value>::value, bool> mlir::detail::matchOperandOrValueAtIndex (Operation * op, unsigned idx, MatcherClass & matcher)
Statically switch to a Value matcher.
Definition at line 143 of file Matchers.h.
References mlir::Operation::getOperand().
Referenced by mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::match().
matchOperandOrValueAtIndex() [2/2]
template<typename MatcherClass > std::enable_if_t<is_detected<detail::has_operation_or_value_matcher_t, MatcherClass, Operation *>::value, bool> mlir::detail::matchOperandOrValueAtIndex (Operation * op, unsigned idx, MatcherClass & matcher)
Statically switch to an Operation matcher.
Definition at line 152 of file Matchers.h.
References mlir::Value::getDefiningOp(), and mlir::Operation::getOperand().
verifyInferredResultTypes()
LogicalResult mlir::detail::verifyInferredResultTypes (Operation * op)
Verifies that the inferred result types match the actual result types for the op.
Precondition: op implements InferTypeOpInterface.
Definition at line 49 of file InferTypeOpInterface.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getAttrs(), mlir::Operation::getContext(), mlir::Operation::getLoc(), mlir::Operation::getOperands(), mlir::Operation::getRegions(), mlir::Operation::getResultTypes(), and mlir::success().
Referenced by mlir::ShapedTypeComponents::getAttribute().
walkOperations() [1/5]
void mlir::detail::walkOperations (Operation * op, function_ref< void(Operation *op)> callback)
Walk all of the operations nested under and including the given operation.
Walk all of the operations nested under and including the given operations.
Definition at line 15 of file Visitors.cpp.
References mlir::Operation::getRegions().
Referenced by mlir::Block::walk(), mlir::Operation::walk(), and walkOperations().
walkOperations() [2/5]
WalkResult mlir::detail::walkOperations (Operation * op, function_ref< WalkResult(Operation *op)> callback)
Walk all of the operations nested under and including the given operation.
Walk all of the operations nested under and including the given operations.
This methods walks operations until an interrupt result is returned by the callback.
This methods walks operations until an interrupt signal is received.
Definition at line 30 of file Visitors.cpp.
References mlir::Operation::getRegions(), mlir::WalkResult::interrupt(), and walkOperations().
walkOperations() [3/5]
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))> std::enable_if<std::is_same<ArgT, Operation *>::value, RetT>::type mlir::detail::walkOperations (Operation * op, FuncTy && callback)
Walk all of the operations nested under and including the given operation.
This method is selected for callbacks that operation on Operation*.
Example: op->walk([](Operation *op) { ... });
Definition at line 87 of file Visitors.h.
References walkOperations().
walkOperations() [4/5]
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))> std::enable_if<!std::is_same<ArgT, Operation *>::value && std::is_same<RetT, void>::value, RetT>::type mlir::detail::walkOperations (Operation * op, FuncTy && callback)
Walk all of the operations of type 'ArgT' nested under and including the given operation.
This method is selected for void returning callbacks that operate on a specific derived operation type.
Example: op->walk([](ReturnOp op) { ... });
Definition at line 103 of file Visitors.h.
References walkOperations().
walkOperations() [5/5]
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))> std::enable_if<!std::is_same<ArgT, Operation *>::value && std::is_same<RetT, WalkResult>::value, RetT>::type mlir::detail::walkOperations (Operation * op, FuncTy && callback)
Walk all of the operations of type 'ArgT' nested under and including the given operation.
This method is selected for WalkReturn returning interruptible callbacks that operate on a specific derived operation type.
Example: op->walk([](ReturnOp op) { if (some_invariant) return WalkResult::interrupt(); return WalkResult::advance(); });
Definition at line 127 of file Visitors.h.
References mlir::WalkResult::advance(), and walkOperations().
Variable Documentation
first_argument_type
template<typename F > decltype(first_argument_type(&F::operator())) mlir::detail::first_argument_type(F)
Definition at line 58 of file Visitors.h.