MLIR: mlir Namespace Reference
mlir Namespace Reference
This file provides some simple template functional-style sugar to operate on value types.
Namespaces
detail
Utilities for detecting if a given trait holds for some set of arguments 'Args'.
edsc
functional
fxpmath
gpu
impl
linalg
LLVM
loop
matcher
matchers
NVVM
ops_assertions
Overloaded arithmetic operators for SDBM expressions asserting that their arguments have the proper SDBM expression subtype.
OpTrait
quant
quantizer
ROCDL
spirv
StandardAttributes
StandardTypes
tblgen
vector
Classes
class AbstractOperation
This is a "type erased" representation of a registered operation.
struct AffineApplyNormalizer
An AffineApplyNormalizer is a helper class that supports renumbering operands of AffineApplyOp.
class AffineApplyOp
The "affine.apply" operation applies an affine map to a list of operands, yielding a single result.
class AffineBinaryOpExpr
Affine binary operation expression.
class AffineBound
AffineBound represents a lower or upper bound in the for operation.
class AffineConstantExpr
An integer constant appearing in affine expression.
struct AffineCopyOptions
Explicit copy / DMA generation options for mlir::affineDataCopyGenerate.
class AffineDimExpr
A dimensional identifier appearing in an affine expression.
class AffineDmaStartOp
AffineDmaStartOp starts a non-blocking DMA operation that transfers data from a source memref to a destination memref.
class AffineDmaWaitOp
AffineDmaWaitOp blocks until the completion of a DMA operation associated with the tag element 'tag[index]'.
class AffineExpr
Base type for affine expression.
class AffineExprVisitor
Base class for AffineExpr visitors/walkers.
class AffineLoadOp
The "affine.load" op reads an element from a memref, where the index for each memref dimension is an affine expression of loop induction variables and symbols.
class AffineMap
A multi-dimensional affine map Affine map's are immutable like Type's, and they are uniqued.
class AffineMapAttr
class AffineOpsDialect
class AffineStoreOp
The "affine.store" op writes an element to a memref, where the index for each memref dimension is an affine expression of loop induction variables and symbols.
class AffineSymbolExpr
A symbolic identifier appearing in an affine expression.
class AffineValueMap
An AffineValueMap is an affine map plus its ML value operands and results for analysis purposes.
class AnalysisManager
This class represents an analysis manager for a particular operation instance.
class ArrayAttr
Array attributes are lists of other attributes.
class AsmState
This class provides management for the lifetime of the state used when printing the IR.
class Attribute
Attributes are known-constant values of operations and functions.
class AttributeStorage
Base storage class appearing in an attribute.
class BaseMemRefType
Base MemRef for Ranked and Unranked variants.
class Block
Block represents an ordered list of Operations.
class BlockAndValueMapping
class BlockArgument
Block arguments are values.
class BlockOperand
Terminator operations can have Block operands to represent successors.
class BoolAttr
class Builder
This class is a general helper class for creating context-global objects like types, attributes, and affine expressions.
class CallGraph
class CallGraphNode
This class represents a single callable in the callgraph.
struct CallInterfaceCallable
A callable is either a symbol, or an SSA value, that is referenced by a call-like operation.
class CallSiteLoc
Represents a location as call site.
struct ClassID
A special type used to provide an address for a given class that can act as a unique identifier during pass registration.
class ComplexType
The 'complex' type represents a complex number with a parameterized element type, which is composed of a real and imaginary value of that element type.
struct ComputationSliceState
ComputationSliceState aggregates loop IVs, loop bound AffineMaps and their associated operands for a set of loops within a loop nest (typically the set of loops surrounding a store operation).
class ConstantFloatOp
This is a refinement of the "constant" op for the case where it is returning a float value of FloatType.
class ConstantIndexOp
This is a refinement of the "constant" op for the case where it is returning an integer value of Index type.
class ConstantIntOp
This is a refinement of the "constant" op for the case where it is returning an integer value of IntegerType.
class ConversionPattern
Base class for the conversion patterns that require type changes.
class ConversionPatternRewriter
This class implements a pattern rewriter for use with ConversionPatterns.
class ConversionTarget
This class describes a specific conversion target.
class DenseElementsAttr
An attribute that represents a reference to a dense vector or tensor object.
class DenseFPElementsAttr
An attribute that represents a reference to a dense float vector or tensor object.
class DenseIntElementsAttr
An attribute that represents a reference to a dense integer vector or tensor object.
struct DependenceComponent
struct DependenceResult
Checks whether two accesses to the same memref access the same element.
class Diagnostic
This class contains all of the information necessary to report a diagnostic to the DiagnosticEngine.
class DiagnosticArgument
A variant type that holds a single argument for a diagnostic.
class DiagnosticEngine
This class is the main interface for diagnostics.
class Dialect
Dialects are groups of MLIR operations and behavior associated with the entire group.
class DialectAsmParser
The DialectAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
class DialectAsmPrinter
This is a pure-virtual base class that exposes the asmprinter hooks necessary to implement a custom printAttribute/printType() method on a dialect.
class DialectHooks
Dialect hooks allow external components to register their functions to be called for specific tasks specialized per dialect, such as decoding of opaque constants.
struct DialectHooksRegistration
DialectHooksRegistration provides a global initializer that registers a dialect hooks setter routine.
class DialectInlinerInterface
This is the interface that must be implemented by the dialects of operations to be inlined.
class DialectInterface
This class represents an interface overridden for a single dialect.
class DialectInterfaceCollection
A collection of dialect interfaces within a context, for a given concrete interface type.
struct DialectRegistration
DialectRegistration provides a global initializer that registers a Dialect allocation routine.
class DictionaryAttr
Dictionary attribute is an attribute that represents a sorted collection of named attribute values.
class DmaStartOp
class DmaWaitOp
class DominanceInfo
A class for computing basic dominance information.
class ElementsAttr
A base attribute that represents a reference to a static shaped tensor or vector constant.
struct EmptyPipelineOptions
A default empty option struct to be used for passes that do not need to take any options.
class ExecutionEngine
JIT-backed execution engine for MLIR modules.
class FileLineColLoc
Represents a location derived from a file/line/column location.
class FilteredValueUseIterator
This class represents an iterator of the uses of a IR object that optionally filters on a specific sub-value.
class FlatAffineConstraints
A flat list of affine equalities and inequalities in the form.
class FlatSymbolRefAttr
A symbol reference with a reference path containing a single element.
class FloatAttr
class FloatType
class FoldingHook
This template defines the foldHook as used by AbstractOperation.
class FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >
This template specialization defines the foldHook as used by AbstractOperation for single-result operations.
class FuncOp
FuncOp represents a function, or an operation containing one region that forms a CFG(Control Flow Graph).
struct FunctionPass
A model for providing function pass specific utilities.
struct FunctionTraits
This class provides various trait information about a callable object.
struct FunctionTraits< ReturnType(*)(Args...), false >
Overload for non-class function types.
struct FunctionTraits< ReturnType(ClassType::*)(Args...) const, false >
Overload for class function types.
class FunctionType
Function types map from a list of inputs to a list of results.
class FusedLoc
Represents a value composed of multiple source constructs, with an optional metadata attribute.
struct FusionResult
class GenInfo
Structure to group information about a generator (argument to invoke via mlir-tblgen, description, and generator function).
struct GenNameParser
Adds command line option for each registered generator.
struct GenRegistration
GenRegistration provides a global initializer that registers a generator function.
struct GPUIndexIntrinsicOpLowering
class Identifier
This class represents a uniqued string owned by an MLIRContext.
class indexed_accessor_iterator
A utility class used to implement an iterator that contains some base object and an index.
class indexed_accessor_range
This class provides an implementation of a range of indexed_accessor_iterators where the base is not indexable.
class IndexType
Index is a special integer-like type with unknown platform-dependent bit width.
class InFlightDiagnostic
This class represents a diagnostic that is inflight and set to be reported.
class InlinerInterface
This interface provides the hooks into the inlining interface.
class IntegerAttr
class IntegerSet
An integer set representing a conjunction of one or more affine equalities and inequalities.
class IntegerSetAttr
class IntegerType
Integer types can have arbitrary bitwidth up to a large fixed limit.
class IntegerValueSet
An IntegerValueSet is an integer set plus its operands.
class IntInfty
A utility class for SDBM to represent an integer with potentially infinite positive value.
class IRMultiObjectWithUseList
This class represents multiple IR objects with a single use list.
class IRObjectWithUseList
This class represents a single IR object that contains a use list.
class IROperand
A reference to a value, suitable for use as an operand of an operation.
class Lexer
This class breaks up the current file into a token stream.
class LinalgTypeConverter
class Liveness
Represents an analysis for computing liveness information from a given top-level operation.
class LivenessBlockInfo
This class represents liveness information on block level.
class LLVMOpLowering
Base class for operation conversions targeting the LLVM IR dialect.
class LLVMTypeConverter
Conversion from types in the Standard dialect to the LLVM IR dialect.
class Location
This class defines the main interface for locations in MLIR and acts as a non-nullable wrapper around a LocationAttr.
class LocationAttr
Location objects represent source locations information in MLIR.
struct LogicalResult
struct LoopNestStats
LoopNestStats aggregates various per-loop statistics (eg.
struct MemRefAccess
Encapsulates a memref load or store access information.
class MemRefDescriptor
Helper class to produce LLVM dialect operations extracting or inserting elements of a MemRef descriptor.
struct MemRefRegion
A region of a memref's data space; this is typically constructed by analyzing load/store op's on this memref and the index space of loops surrounding such op's.
class MemRefType
MemRef types represent a region of memory that have a shape with a fixed number of dimensions.
class MLIRContext
MLIRContext is the top-level object for a collection of MLIR modules.
class MLIRContextImpl
This is the implementation of the MLIRContext class, using the pImpl idiom.
class ModuleAnalysisManager
An analysis manager class specifically for the top-level module operation.
class ModuleOp
ModuleOp represents a module, or an operation containing one region with a single block containing opaque operations.
struct ModulePass
A model for providing module pass specific utilities.
class ModuleTerminatorOp
The ModuleTerminatorOp is a special terminator operation for the body of a ModuleOp, it has no semantic meaning beyond keeping the body of a ModuleOp well-formed.
struct MutableAffineMap
A mutable affine map. Its affine expressions are however unique.
struct MutableIntegerSet
A mutable integer set. Its affine expressions are however unique.
class NamedAttributeList
A NamedAttributeList is used to manage a list of named attributes.
class NameLoc
Represents an identity name attached to a child location.
class NestedMatch
An NestedPattern captures nested patterns in the IR.
class NestedPattern
class NestedPatternContext
RAII structure to transparently manage the bump allocator for NestedPattern and NestedMatch classes.
class NoneType
NoneType is a unit type, i.e.
class Op
This provides public APIs that all operations should have.
class OpaqueAttr
Opaque attributes represent attributes of non-registered dialects.
class OpaqueElementsAttr
An opaque attribute that represents a reference to a vector or tensor constant with opaque content.
class OpaqueLoc
Represents a location that is external to MLIR.
class OpaqueType
Opaque types represent types of non-registered dialects.
class OpAsmDialectInterface
class OpAsmParser
The OpAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
class OpAsmPrinter
This is a pure-virtual base class that exposes the asmprinter hooks necessary to implement a custom print() method.
class OpBuilder
This class helps build Operations.
struct OpConversionPattern
OpConversionPattern is a wrapper around ConversionPattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
class OperandElementTypeIterator
class OperandRange
This class implements the operand iterators for the Operation class.
class Operation
Operation is a basic unit of execution within a function.
class OperationFolder
A utility class for folding operations, and unifying duplicated constants generated along the way.
class OperationName
class OperationPass
Pass to transform an operation of a specific type.
struct OperationPass< PassT, void >
Pass to transform an operation.
struct OperationState
This represents an operation in an abstracted form, suitable for use with the builder APIs.
class OpFolderDialectInterface
This class defines a dialect interface used to assist the operation folder.
class OpFoldResult
This class represents a single result from folding an operation.
class OpInterface
This class represents the base of an operation interface.
class OpOperand
A reference to a value, suitable for use as an operand of an operation.
class OpPassBase
Utility base class for OpPass below to denote an opaque pass operating on a specific operation type.
class OpPassManager
This class represents a pass manager that runs passes on a specific operation type.
class OpPrintingFlags
Set of flags used to control the behavior of the various IR print methods (e.g.
class OpResult
This is a value defined by a result of an operation.
struct OpRewritePattern
OpRewritePattern is a wrapper around RewritePattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
class OpState
This is the concrete base class that holds the operation pointer and has non-generic methods that only depend on State (to avoid having them instantiated on template types that don't affect them.
class OptionalParseResult
This class implements Optional functionality for ParseResult.
struct OpToFuncCallLowering
Rewriting that replace SourceOp with a CallOp to f32Func or f64Func depending on the element type that Op operates upon.
class OwningModuleRef
This class acts as an owning reference to a module, and will automatically destroy the held module if valid.
class OwningRewritePatternList
class ParallelDiagnosticHandler
This class is a utility diagnostic handler for use when multi-threading some part of the compiler where diagnostics may be emitted.
class ParseResult
This class represents success/failure for operation parsing.
class Pass
The abstract base pass class.
class PassInfo
A structure to represent the information for a derived pass class.
class PassInstrumentation
PassInstrumentation provides several entry points into the pass manager infrastructure.
class PassInstrumentor
This class holds a collection of PassInstrumentation objects, and invokes their respective call backs.
class PassManager
The main pass manager and pipeline builder.
class PassPipelineCLParser
This class implements a command-line parser for MLIR passes.
class PassPipelineInfo
A structure to represent the information of a registered pass pipeline.
class PassPipelineOptions
Subclasses of PassPipelineOptions provide a set of options that can be used to initialize a pass pipeline.
struct PassPipelineRegistration
PassPipelineRegistration provides a global initializer that registers a Pass pipeline builder routine.
struct PassPipelineRegistration< EmptyPipelineOptions >
Convenience specialization of PassPipelineRegistration for EmptyPassOptions that does not pass an empty options struct to the pass builder function.
struct PassRegistration
PassRegistration provides a global initializer that registers a Pass allocation routine for a concrete pass instance.
class PassRegistryEntry
Structure to group information about a passes and pass pipelines (argument to invoke via mlir-opt, description, pass pipeline builder).
class Pattern
Instances of Pattern can be matched against SSA IR.
class PatternBenefit
This class represents the benefit of a pattern match in a unitless scheme that ranges from 0 (very little benefit) to 65K.
class PatternRewriter
This class coordinates the application of a pattern to the current function, providing a way to create operations and keep track of what gets deleted.
class PatternState
Pattern state is used by patterns that want to maintain state between their match and rewrite phases.
class PostDominanceInfo
A class for computing basic postdominance information.
class PredecessorIterator
Implement a predecessor iterator for blocks.
class RankedTensorType
Ranked tensor types represent multi-dimensional arrays that have a shape with a fixed number of dimensions.
class Region
This class contains a list of basic blocks and a link to the parent operation it is attached to.
class RegionRange
This class provides an abstraction over the different types of ranges over Regions.
class ResultElementTypeIterator
class ResultRange
This class implements the result iterators for the Operation class.
class RewritePattern
RewritePattern is the common base class for all DAG to DAG replacements.
class RewritePatternMatcher
This class manages optimization and execution of a group of rewrite patterns, providing an API for finding and applying, the best match against a given node.
class ScopedDiagnosticHandler
This diagnostic handler is a simple RAII class that registers and erases a diagnostic handler on a given context.
class SDBM
Striped difference-bound matrix is a representation of an integer set bound by a system of SDBMExprs interpreted as inequalities "expr <= 0".
class SDBMConstantExpr
SDBM constant expression, wraps a 64-bit integer.
class SDBMDialect
class SDBMDiffExpr
SDBM difference expression.
class SDBMDimExpr
SDBM dimension expression.
class SDBMDirectExpr
SDBM direct expression includes exactly one variable (symbol or dimension), which is not negated in the expression.
class SDBMExpr
Striped Difference-Bounded Matrix (SDBM) expression is a base left-hand side expression for the SDBM framework.
class SDBMInputExpr
SDBM "input" variable expression can be either a dimension identifier or a symbol identifier.
class SDBMNegExpr
Negation of an SDBM variable expression.
class SDBMStripeExpr
SDBM stripe expression "x # C" where "x" is a term expression, "C" is a constant expression and "#" is the stripe operator defined as: x # C = x - x mod C.
class SDBMSumExpr
SDBM sum expression. LHS is a term expression and RHS is a constant.
class SDBMSymbolExpr
SDBM symbol expression.
class SDBMTermExpr
SDBM term expression can be one of:
class SDBMVaryingExpr
SDBM varying expression can be one of:
class SDBMVisitor
A visitor class for SDBM expressions.
class ShapedType
This is a common base class between Vector, UnrankedTensor, RankedTensor, and MemRef types because they share behavior and semantics around shape, rank, and fixed element type.
class ShapedTypeComponents
ShapedTypeComponents that represents the components of a ShapedType.
class SideEffectsDialectInterface
Specifies an interface for basic side-effect modelling that is used by the loop-invariant code motion pass.
class SideEffectsInterface
class SimpleAffineExprFlattener
class SimpleObjectCache
A simple object cache following Lang's LLJITWithObjectCache example.
class SourceMgrDiagnosticHandler
This class is a utility diagnostic handler for use with llvm::SourceMgr.
class SourceMgrDiagnosticVerifierHandler
This class is a utility diagnostic handler for use with llvm::SourceMgr that verifies that emitted diagnostics match 'expected-*' lines on the corresponding line of the source file.
class SparseElementsAttr
An attribute that represents a reference to a sparse vector or tensor object.
class SPIRVOpLowering
Base class to define a conversion pattern to lower SourceOp into SPIR-V.
class SPIRVTypeConverter
Type conversion from standard types to SPIR-V types for shader interface.
class SplatElementsAttr
An attribute that represents a reference to a splat vector or tensor constant, meaning all of the elements have the same value.
class StandardOpsDialect
class StorageUniquer
A utility class to get, or create instances of storage classes.
class StringAttr
class StructBuilder
Helper class to produce LLVM dialect operations extracting or inserting values to a struct.
class SuccessorRange
This class implements the successor iterators for Block.
class SymbolRefAttr
A symbol reference attribute represents a symbolic reference to another operation.
class SymbolTable
This class allows for representing and managing the symbol table used by operations with the 'SymbolTable' trait.
class TensorType
Tensor types represent multi-dimensional arrays, and have two variants: RankedTensorType and UnrankedTensorType.
class Token
This represents a token in the MLIR syntax.
struct TranslateFromMLIRRegistration
struct TranslateRegistration
struct TranslateToMLIRRegistration
Use Translate[ToMLIR|FromMLIR]Registration as a global initializer that registers a function and associates it with name.
struct TranslationParser
Custom parser for TranslateFunction.
class TupleType
Tuple types represent a collection of other types.
class Type
Instances of the Type class are immutable and uniqued.
class TypeAttr
class TypeConverter
Base class for type conversion interface.
class TypeStorage
Base storage class appearing in a Type.
class TypeSwitch
This class implements a switch-like dispatch statement for a value of 'T' using dyn_cast functionality.
class TypeSwitch< T, void >
Specialization of TypeSwitch for void returning callables.
class UnitAttr
Unit attributes are attributes that hold no specific value and are given meaning by their existence.
class UnknownLoc
Represents an unknown location.
class UnrankedMemRefDescriptor
class UnrankedMemRefType
Unranked MemRef type represent multi-dimensional MemRefs that have an unknown rank.
class UnrankedTensorType
Unranked tensor types represent multi-dimensional arrays that have an unknown shape.
class Value
This class represents an instance of an SSA value in the MLIR system, representing a computable value that has a type and a set of users.
class ValueRange
This class provides an abstraction over the different types of ranges over Values.
class ValueTypeIterator
This class implements iteration on the types of a given range of values.
class ValueUseIterator
An iterator over all of the uses of an IR object.
class ValueUserIterator
An iterator over all users of a ValueBase.
class VectorType
Vector types represent multi-dimensional SIMD vectors, and have a fixed known constant shape with one or more dimension.
class VulkanLayoutUtils
According to the Vulkan spec "14.5.4. Offset and Stride Assignment": "There are different alignment requirements depending on the specific resources and on the features enabled on the device.
class WalkResult
A utility result that is used to signal if a walk method should be interrupted or advance.
Typedefs
using DominanceInfoNode = llvm::DomTreeNodeBase< Block >
using VectorizableLoopFun = std::function< bool(AffineForOp)>
using FilterFunctionType = std::function< bool(Operation &)>
A NestedPattern is a nested operation walker that:
using TransitiveFilter = std::function< bool(Operation *)>
Type of the condition to limit the propagation of transitive use-defs.
using OwnedCubin = std::unique_ptr< std::vector< char > >
using CubinGenerator = std::function< OwnedCubin(const std::string &, Location, StringRef)>
using LLVMPatternListFiller = std::function< void(LLVMTypeConverter &, OwningRewritePatternList &)>
Type for a callback constructing the owning list of patterns for the conversion to the LLVMIR dialect.
using LLVMTypeConverterMaker = std::function< std::unique_ptr< LLVMTypeConverter >(MLIRContext *)>
Type for a callback constructing the type converter for the conversion to the LLVMIR dialect.
using NamedAttribute = std::pair< Identifier, Attribute >
NamedAttribute is used for dictionary attributes, it holds an identifier for the name and a value for the attribute.
using DefaultAttributeStorage = AttributeStorage
Default storage type for attributes that require no additional initialization or storage.
using AttributeStorageAllocator = StorageUniquer::StorageAllocator
using DialectConstantDecodeHook = std::function< bool(const OpaqueElementsAttr, ElementsAttr &)>
using DialectConstantFoldHook = std::function< LogicalResult(Operation *, ArrayRef< Attribute >, SmallVectorImpl< Attribute > &)>
using DialectExtractElementHook = std::function< Attribute(const OpaqueElementsAttr, ArrayRef< uint64_t >)>
using DialectAllocatorFunction = std::function< void(MLIRContext *)>
using DialectHooksSetter = std::function< void(MLIRContext *)>
template<typename OpTy >
using OperandAdaptor = typename OpTy::OperandAdaptor
This is an adaptor from a list of values to named operands of OpTy.
using OpAsmSetValueNameFn = function_ref< void(Value, StringRef)>
A functor used to set the name of the start of a result group of an operation.
using PatternMatchResult = Optional< std::unique_ptr< PatternState > >
This is the type returned by a pattern match.
using DefaultTypeStorage = TypeStorage
Default storage type for types that require no additional initialization or storage.
using TypeStorageAllocator = StorageUniquer::StorageAllocator
using OperandElementTypeRange = iterator_range< OperandElementTypeIterator >
using ResultElementTypeRange = iterator_range< ResultElementTypeIterator >
using AnalysisID = ClassID
A special type used by analyses to provide an address that identifies a particular analysis set or a concrete analysis type.
using PassRegistryFunction = std::function< LogicalResult(OpPassManager &, StringRef options)>
A registry function that adds passes to the given pass manager.
using PassAllocatorFunction = std::function< std::unique_ptr< Pass >()>
using PassID = ClassID
A special type used by transformation passes to provide an address that can act as a unique identifier during pass registration.
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>>
using DenseMap = llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >
template<typename ValueT , typename ValueInfoT = DenseMapInfo<ValueT>>
using DenseSet = llvm::DenseSet< ValueT, ValueInfoT >
template<typename Fn >
using function_ref = llvm::function_ref< Fn >
template<template< class... > class Op, class... Args>
using is_detected = typename detail::detector< void, Op, Args... >::value_t
template<typename Callable , typename... Args>
using is_invocable = is_detected< detail::is_invocable, Callable, Args... >
using ChunkBufferHandler = function_ref< LogicalResult(std::unique_ptr< llvm::MemoryBuffer > chunkBuffer, raw_ostream &os)>
using GenFunction = std::function< bool(const llvm::RecordKeeper &recordKeeper, raw_ostream &os)>
Generator function to invoke.
using Loops = SmallVector< loop::ForOp, 8 >
Performs tiling fo imperfectly nested loops (with interchange) by strip-mining the forOps by sizes and sinking them, in their order of occurrence in forOps, under each of the targets.
using TileLoops = std::pair< Loops, Loops >
using TranslateSourceMgrToMLIRFunction = std::function< OwningModuleRef(llvm::SourceMgr &sourceMgr, MLIRContext *)>
Interface of the function that translates the sources managed by sourceMgr to MLIR.
using TranslateStringRefToMLIRFunction = std::function< OwningModuleRef(llvm::StringRef, MLIRContext *)>
Interface of the function that translates the given string to MLIR.
using TranslateFromMLIRFunction = std::function< LogicalResult(ModuleOp, llvm::raw_ostream &output)>
Interface of the function that translates MLIR to a different format and outputs the result to a stream.
using TranslateFunction = std::function< LogicalResult(llvm::SourceMgr &sourceMgr, llvm::raw_ostream &output, MLIRContext *)>
Interface of the function that performs file-to-file translation involving MLIR.
Enumerations
enum SDBMExprKind {
SDBMExprKind::Add, SDBMExprKind::Stripe, SDBMExprKind::Diff, SDBMExprKind::Constant,
SDBMExprKind::DimId, SDBMExprKind::SymbolId, SDBMExprKind::Neg
}
enum CmpFPredicate {
CmpFPredicate::FirstValidValue, CmpFPredicate::AlwaysFalse = FirstValidValue, CmpFPredicate::OEQ, CmpFPredicate::OGT,
CmpFPredicate::OGE, CmpFPredicate::OLT, CmpFPredicate::OLE, CmpFPredicate::ONE,
CmpFPredicate::ORD, CmpFPredicate::UEQ, CmpFPredicate::UGT, CmpFPredicate::UGE,
CmpFPredicate::ULT, CmpFPredicate::ULE, CmpFPredicate::UNE, CmpFPredicate::UNO,
CmpFPredicate::AlwaysTrue, CmpFPredicate::NumPredicates
}
The predicate indicates the type of the comparison to perform: (un)orderedness, (in)equality and less/greater than (or equal to) as well as predicates that are always true or false.
enum AffineExprKind {
AffineExprKind::Add, AffineExprKind::Mul, AffineExprKind::Mod, AffineExprKind::FloorDiv,
AffineExprKind::CeilDiv, AffineExprKind::LAST_AFFINE_BINARY_OP = CeilDiv, AffineExprKind::Constant, AffineExprKind::DimId,
AffineExprKind::SymbolId
}
enum DiagnosticSeverity { DiagnosticSeverity::Note, DiagnosticSeverity::Warning, DiagnosticSeverity::Error, DiagnosticSeverity::Remark }
Defines the different supported severity of a diagnostic.
enum OperationProperty { OperationProperty::Commutative = 0x1, OperationProperty::NoSideEffect = 0x2, OperationProperty::Terminator = 0x4, OperationProperty::IsolatedFromAbove = 0x8 }
enum PassDisplayMode { PassDisplayMode::List, PassDisplayMode::Pipeline }
An enum describing the different display modes for the information within the pass manager.
Functions
void getReachableAffineApplyOps (ArrayRef< Value > operands, SmallVectorImpl< Operation *> &affineApplyOps)
Returns in affineApplyOps, the sequence of those AffineApplyOp Operations that are reachable via a search starting from operands and ending at those operands that are not the result of an AffineApplyOp.
LogicalResult getIndexSet (MutableArrayRef< AffineForOp > forOps, FlatAffineConstraints *domain)
Builds a system of constraints with dimensional identifiers corresponding to the loop IVs of the forOps appearing in that order.
DependenceResult checkMemrefAccessDependence (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess, unsigned loopDepth, FlatAffineConstraints *dependenceConstraints, SmallVector< DependenceComponent, 2 > *dependenceComponents, bool allowRAR=false)
bool hasDependence (DependenceResult result)
Utility function that returns true if the provided DependenceResult corresponds to a dependence result.
void getDependenceComponents (AffineForOp forOp, unsigned maxLoopDepth, std::vector< SmallVector< DependenceComponent, 2 >> *depCompsVec)
Returns in 'depCompsVec', dependence components for dependences between all load and store ops in loop nest rooted at 'forOp', at loop depths in range [1, maxLoopDepth].
AffineExpr simplifyAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols)
Simplify an affine expression by flattening and some amount of simple analysis.
LogicalResult getFlattenedAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols, SmallVectorImpl< int64_t > *flattenedExpr, FlatAffineConstraints *cst=nullptr)
Flattens 'expr' into 'flattenedExpr', which contains the coefficients of the dimensions, symbols, and additional variables that represent floor divisions of dimensions, symbols, and in turn other floor divisions.
LogicalResult getFlattenedAffineExprs (AffineMap map, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs, FlatAffineConstraints *cst=nullptr)
Flattens the result expressions of the map to their corresponding flattened forms and set in 'flattenedExprs'.
LogicalResult getFlattenedAffineExprs (IntegerSet set, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs, FlatAffineConstraints *cst=nullptr)
void buildTripCountMapAndOperands (AffineForOp forOp, AffineMap *map, SmallVectorImpl< Value > *operands)
Returns the trip count of the loop as an affine map with its corresponding operands if the latter is expressible as an affine expression, and nullptr otherwise.
Optional< uint64_t > getConstantTripCount (AffineForOp forOp)
Returns the trip count of the loop if it's a constant, None otherwise.
uint64_t getLargestDivisorOfTripCount (AffineForOp forOp)
Returns the greatest known integral divisor of the trip count.
DenseSet< Value, DenseMapInfo< Value > > getInvariantAccesses (Value iv, ArrayRef< Value > indices)
Given an induction variable iv of type AffineForOp and indices of type IndexType, returns the set of indices that are independent of iv.
bool isVectorizableLoopBody (AffineForOp loop, NestedPattern &vectorTransferMatcher)
Checks whether the loop is structurally vectorizable; i.e.
bool isVectorizableLoopBody (AffineForOp loop, int *memRefDim, NestedPattern &vectorTransferMatcher)
Checks whether the loop is structurally vectorizable and that all the LoadOp and StoreOp matched have access indexing functions that are are either:
bool isInstwiseShiftValid (AffineForOp forOp, ArrayRef< uint64_t > shifts)
Checks where SSA dominance would be violated if a for op's body operations are shifted by the specified shifts.
bool defaultFilterFunction (Operation &)
std::unique_ptr< OpPassBase< FuncOp > > createMemRefBoundCheckPass ()
Creates a pass to check memref accesses in a Function.
std::unique_ptr< OpPassBase< FuncOp > > createTestMemRefDependenceCheckPass ()
Creates a pass to check memref access dependences in a Function.
std::unique_ptr< OpPassBase< FuncOp > > createParallelismDetectionTestPass ()
Creates a pass to test parallelism detection; emits note for parallel loops.
void getForwardSlice (Operation *op, llvm::SetVector< Operation *> *forwardSlice, TransitiveFilter filter=[](Operation *) { return true;})
Fills forwardSlice with the computed forward slice (i.e.
void getBackwardSlice (Operation *op, llvm::SetVector< Operation *> *backwardSlice, TransitiveFilter filter=[](Operation *) { return true;})
Fills backwardSlice with the computed backward slice (i.e.
llvm::SetVector< Operation * > getSlice (Operation *op, TransitiveFilter backwardFilter=[](Operation *) { return true;}, TransitiveFilter forwardFilter=[](Operation *) { return true;})
Iteratively computes backward slices and forward slices until a fixed point is reached.
llvm::SetVector< Operation * > topologicalSort (const llvm::SetVector< Operation *> &toSort)
Multi-root DAG topological sort.
void getLoopIVs (Operation &op, SmallVectorImpl< AffineForOp > *loops)
Populates 'loops' with IVs of the loops surrounding 'op' ordered from the outermost 'affine.for' operation to the innermost one.
unsigned getNestingDepth (Operation &op)
Returns the nesting depth of this operation, i.e., the number of loops surrounding this operation.
void getSequentialLoops (AffineForOp forOp, llvm::SmallDenseSet< Value, 8 > *sequentialLoops)
Returns in 'sequentialLoops' all sequential loops in loop nest rooted at 'forOp'.
void getComputationSliceState (Operation *depSourceOp, Operation *depSinkOp, FlatAffineConstraints *dependenceConstraints, unsigned loopDepth, bool isBackwardSlice, ComputationSliceState *sliceState)
Computes the computation slice loop bounds for one loop nest as affine maps of the other loop nest's IVs and symbols, using 'dependenceConstraints' computed between 'depSourceAccess' and 'depSinkAccess'.
LogicalResult computeSliceUnion (ArrayRef< Operation *> opsA, ArrayRef< Operation *> opsB, unsigned loopDepth, unsigned numCommonLoops, bool isBackwardSlice, ComputationSliceState *sliceUnion)
Computes in 'sliceUnion' the union of all slice bounds computed at 'loopDepth' between all dependent pairs of ops in 'opsA' and 'opsB'.
AffineForOp insertBackwardComputationSlice (Operation *srcOpInst, Operation *dstOpInst, unsigned dstLoopDepth, ComputationSliceState *sliceState)
Creates a clone of the computation contained in the loop nest surrounding 'srcOpInst', slices the iteration space of src loop based on slice bounds in 'sliceState', and inserts the computation slice at the beginning of the operation block of the loop at 'dstLoopDepth' in the loop nest surrounding 'dstOpInst'.
Optional< uint64_t > getMemRefSizeInBytes (MemRefType memRefType)
Returns the size of memref data in bytes if it's statically shaped, None otherwise.
template<typename LoadOrStoreOpPointer >
LogicalResult boundCheckLoadOrStoreOp (LoadOrStoreOpPointer loadOrStoreOp, bool emitError=true)
Checks a load or store op for an out of bound access; returns failure if the access is out of bounds along any of the dimensions, success otherwise.
unsigned getNumCommonSurroundingLoops (Operation &A, Operation &B)
Returns the number of surrounding loops common to both A and B.
Optional< int64_t > getMemoryFootprintBytes (AffineForOp forOp, int memorySpace=-1)
Gets the memory footprint of all data touched in the specified memory space in bytes; if the memory space is unspecified, considers all memory spaces.
bool isLoopParallel (AffineForOp forOp)
Returns true if `forOp' is a parallel loop.
LogicalResult verify (Operation *op)
Perform (potentially expensive) checks of invariants, used to detect compiler bugs, on this operation and any nested operations.
Value expandAffineExpr (OpBuilder &builder, Location loc, AffineExpr expr, ArrayRef< Value > dimValues, ArrayRef< Value > symbolValues)
Emit code that computes the given affine expression using standard arithmetic operations applied to the provided dimension and symbol values.
void populateAffineToStdConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Collect a set of patterns to convert from the Affine dialect to the Standard dialect, in particular convert structured affine control flow into CFG branch-based control flow.
Value lowerAffineLowerBound (AffineForOp op, OpBuilder &builder)
Emit code that computes the lower bound of the given affine loop using standard arithmetic operations.
Value lowerAffineUpperBound (AffineForOp op, OpBuilder &builder)
Emit code that computes the upper bound of the given affine loop using standard arithmetic operations.
std::unique_ptr< OpPassBase< gpu::GPUModuleOp > > createConvertGPUKernelToCubinPass (CubinGenerator cubinGenerator)
Creates a pass to convert kernel functions into CUBIN blobs.
std::unique_ptr< OpPassBase< ModuleOp > > createConvertGpuLaunchFuncToCudaCallsPass ()
Creates a pass to convert a gpu.launch_func operation into a sequence of CUDA calls.
void populateGpuToNVVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the GPU dialect to NVVM.
std::unique_ptr< OpPassBase< gpu::GPUModuleOp > > createLowerGpuOpsToNVVMOpsPass ()
Creates a pass that lowers GPU dialect operations to NVVM counterparts.
std::unique_ptr< OpPassBase< gpu::GPUModuleOp > > createLowerGpuOpsToROCDLOpsPass ()
Creates a pass that lowers GPU dialect operations to ROCDL counterparts.
void populateGPUToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns, ArrayRef< int64_t > workGroupSize)
Appends to a pattern list additional patterns for translating GPU Ops to SPIR-V ops.
std::unique_ptr< OpPassBase< ModuleOp > > createConvertGPUToSPIRVPass (ArrayRef< int64_t > workGroupSize)
Pass to convert GPU Ops to SPIR-V ops.
void populateLinalgToLLVMConversionPatterns (LinalgTypeConverter &converter, OwningRewritePatternList &patterns, MLIRContext *ctx)
Populate the given list with patterns that convert from Linalg to LLVM.
std::unique_ptr< OpPassBase< ModuleOp > > createConvertLinalgToLLVMPass ()
Create a pass to convert Linalg operations to the LLVMIR dialect.
LogicalResult convertAffineLoopNestToGPULaunch (AffineForOp forOp, unsigned numBlockDims, unsigned numThreadDims)
Convert a perfect affine loop nest with the outermost loop identified by forOp into a gpu::Launch operation.
LogicalResult convertLoopNestToGPULaunch (loop::ForOp forOp, unsigned numBlockDims, unsigned numThreadDims)
Convert a perfect linalg loop nest with the outermost loop identified by forOp into a gpu::Launch operation.
LogicalResult convertLoopToGPULaunch (loop::ForOp forOp, ArrayRef< Value > numWorkGroups, ArrayRef< Value > workGroupSizes)
Convert a loop operation into a GPU launch with the values provided in numWorkGroups as the grid size and the values provided in workGroupSizes as the block size.
std::unique_ptr< OpPassBase< FuncOp > > createSimpleLoopsToGPUPass (unsigned numBlockDims, unsigned numThreadDims)
Create a pass that converts loop nests into GPU kernels.
std::unique_ptr< OpPassBase< FuncOp > > createLoopToGPUPass (ArrayRef< int64_t > numWorkGroups, ArrayRef< int64_t > workGroupSize)
Create a pass that converts every loop operation within the body of the FuncOp into a GPU launch.
void populateLoopToStdConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Collect a set of patterns to lower from loop.for, loop.if, and loop.terminator to CFG operations within the Standard dialect, in particular convert structured control flow into CFG branch-based control flow.
std::unique_ptr< Pass > createLowerToCFGPass ()
Creates a pass to convert loop.for, loop.if and loop.terminator ops to CFG.
void populateStdToLLVMMemoryConversionPatters (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert memory-related operations from the Standard dialect to the LLVM dialect, excluding the memory-related operations.
void populateStdToLLVMNonMemoryConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the Standard dialect to the LLVM dialect, excluding the memory-related operations.
void populateStdToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the Standard dialect to LLVM.
std::unique_ptr< OpPassBase< ModuleOp > > createLowerToLLVMPass (bool useAlloca=false)
Creates a pass to convert the Standard dialect into the LLVMIR dialect.
std::unique_ptr< OpPassBase< ModuleOp > > createLowerToLLVMPass (LLVMPatternListFiller patternListFiller, LLVMTypeConverterMaker typeConverterMaker, bool useAlloca=false)
Creates a pass to convert operations to the LLVMIR dialect.
template<typename TypeConverter = LLVMTypeConverter>
std::unique_ptr< OpPassBase< ModuleOp > > createLowerToLLVMPass (LLVMPatternListFiller patternListFiller, bool useAlloca=false)
Creates a pass to convert operations to the LLVMIR dialect.
void populateStandardToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating StandardOps to SPIR-V ops.
void populateStdLegalizationPatternsForSPIRVLowering (MLIRContext *context, OwningRewritePatternList &patterns)
Appends to a pattern list patterns to legalize ops that are not directly lowered to SPIR-V.
std::unique_ptr< OpPassBase< ModuleOp > > createConvertStandardToSPIRVPass ()
Pass to convert StandardOps to SPIR-V ops.
std::unique_ptr< Pass > createLegalizeStdOpsForSPIRVLoweringPass ()
Pass to legalize ops that are not directly lowered to SPIR-V.
void populateVectorToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the Vector dialect to LLVM.
OpPassBase< ModuleOp > * createLowerVectorToLLVMPass ()
Create a pass to convert vector operations to the LLVMIR dialect.
void populateVectorToAffineLoopsConversionPatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the Vector dialect to loops + std.
OpPassBase< ModuleOp > * createLowerVectorToLoopsPass ()
Create a pass to convert vector operations to affine loops + std dialect.
bool isTopLevelValue (Value value)
A utility function to check if a value is defined at the top level of a function.
bool isValidDim (Value value)
Returns true if the given Value can be used as a dimension id.
bool isValidSymbol (Value value)
Returns true if the given Value can be used as a symbol.
void canonicalizeMapAndOperands (AffineMap *map, SmallVectorImpl< Value > *operands)
Modifies both map and operands in-place so as to:
void canonicalizeSetAndOperands (IntegerSet *set, SmallVectorImpl< Value > *operands)
Canonicalizes an integer set the same way canonicalizeMapAndOperands does for affine maps.
AffineApplyOp makeComposedAffineApply (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > operands)
Returns a composed AffineApplyOp by composing map and operands with other AffineApplyOps supplying those operands.
void fullyComposeAffineMapAndOperands (AffineMap *map, SmallVectorImpl< Value > *operands)
Given an affine map map and its input operands, this method composes into map, maps of AffineApplyOps whose results are the values in operands, iteratively until no more of operands are the result of an AffineApplyOp.
bool isForInductionVar (Value val)
Returns if the provided value is the induction variable of a AffineForOp.
AffineForOp getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
void extractForInductionVars (ArrayRef< AffineForOp > forInsts, SmallVectorImpl< Value > *ivs)
Extracts the induction variables from a list of AffineForOps and places them in the output argument ivs.
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref<ElementValueT(ElementValueT, ElementValueT)>>
Attribute constFoldBinaryOp (ArrayRef< Attribute > operands, const CalculationT &calculate)
Performs constant folding calculate with element-wise behavior on the two attributes in operands and returns the result if possible.
void promoteToWorkgroupMemory (gpu::GPUFuncOp op, unsigned arg)
Promotes a function argument to workgroup memory in the given function.
std::unique_ptr< OpPassBase< ModuleOp > > createGpuKernelOutliningPass ()
void populateGpuRewritePatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Collect a set of patterns to rewrite ops within the GPU dialect.
std::unique_ptr< OpPassBase< FuncOp > > createLinalgFusionPass ()
std::unique_ptr< OpPassBase< FuncOp > > createLinalgTilingPass (ArrayRef< int64_t > tileSizes={})
std::unique_ptr< OpPassBase< FuncOp > > createLinalgPromotionPass (bool dynamicBuffers)
std::unique_ptr< OpPassBase< FuncOp > > createConvertLinalgToLoopsPass ()
Create a pass to convert Linalg operations to loop.for loops and std.load/std.store accesses.
std::unique_ptr< OpPassBase< FuncOp > > createConvertLinalgToAffineLoopsPass ()
Create a pass to convert Linalg operations to affine.for loops and affine_load/affine_store accesses.
IntInfty operator+ (IntInfty lhs, IntInfty rhs)
bool operator< (IntInfty lhs, IntInfty rhs)
bool operator<= (IntInfty lhs, IntInfty rhs)
bool operator== (IntInfty lhs, IntInfty rhs)
bool operator!= (IntInfty lhs, IntInfty rhs)
void populateBuiltinFuncToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating the builtin func op to the SPIR-V dialect.
void printDimAndSymbolList (Operation::operand_iterator begin, Operation::operand_iterator end, unsigned numDims, OpAsmPrinter &p)
Prints dimension and symbol list.
ParseResult parseDimAndSymbolList (OpAsmParser &parser, SmallVectorImpl< Value > &operands, unsigned &numDims)
Parses dimension and symbol list and returns true if parsing failed.
raw_ostream & operator<< (raw_ostream &os, SubViewOp::Range &range)
static constexpr StringLiteral getIndexingMapsAttrName ()
Attribute name for the AffineArrayAttr which encodes the relationship between a structured op iterators' and its operands.
static constexpr StringLiteral getIteratorTypesAttrName ()
Attribute name for the StrArrayAttr which encodes the type of a structured op's iterators.
static constexpr StringLiteral getArgsInAttrName ()
Attribute name for the IntegerAttr which encodes the number of input buffer arguments.
static constexpr StringLiteral getArgsOutAttrName ()
Attribute name for the IntegerAttr which encodes the number of input buffer arguments.
static constexpr StringLiteral getDocAttrName ()
Attribute name for the StringAttr which encodes an optional documentation string of the structured op.
static constexpr StringLiteral getFunAttrName ()
Attribute name for the StrArrayAttr which encodes the SymbolAttr for the MLIR function that implements the body of the structured op.
static constexpr StringLiteral getLibraryCallAttrName ()
Attribute name for the StrArrayAttr which encodes the external library function that implements the structured op.
static constexpr StringLiteral getParallelIteratorTypeName ()
Use to encode that a particular iterator type has parallel semantics.
static constexpr StringLiteral getReductionIteratorTypeName ()
Use to encode that a particular iterator type has reduction semantics.
static constexpr StringLiteral getWindowIteratorTypeName ()
Use to encode that a particular iterator type has window semantics.
static ArrayRef< StringRef > getAllIteratorTypeNames ()
Use to encode that a particular iterator type has window semantics.
unsigned getNumIterators (StringRef name, ArrayAttr iteratorTypes)
Returns the iterator of a certain type.
unsigned getNumIterators (ArrayAttr iteratorTypes)
void populateVectorToVectorConversionPatterns (MLIRContext *context, OwningRewritePatternList &patterns, ArrayRef< int64_t > coarseVectorShape={}, ArrayRef< int64_t > fineVectorShape={})
Collect a set of patterns to convert from the Vector dialect to itself.
Optional< SmallVector< int64_t, 4 > > shapeRatio (ArrayRef< int64_t > superShape, ArrayRef< int64_t > subShape)
Computes and returns the multi-dimensional ratio of superShape to subShape.
Optional< SmallVector< int64_t, 4 > > shapeRatio (VectorType superVectorType, VectorType subVectorType)
Computes and returns the multi-dimensional ratio of the shapes of superVector to subVector.
void initializeLLVMPasses ()
Initialize LLVM passes that can be when running MLIR code using ExecutionEngine.
inline ::llvm::hash_code hash_value (AffineExpr arg)
Make AffineExpr hashable.
AffineExpr operator+ (int64_t val, AffineExpr expr)
AffineExpr operator* (int64_t val, AffineExpr expr)
AffineExpr operator- (int64_t val, AffineExpr expr)
AffineExpr getAffineDimExpr (unsigned position, MLIRContext *context)
These free functions allow clients of the API to not use classes in detail.
AffineExpr getAffineSymbolExpr (unsigned position, MLIRContext *context)
AffineExpr getAffineConstantExpr (int64_t constant, MLIRContext *context)
AffineExpr getAffineBinaryOpExpr (AffineExprKind kind, AffineExpr lhs, AffineExpr rhs)
AffineExpr toAffineExpr (ArrayRef< int64_t > eq, unsigned numDims, unsigned numSymbols, ArrayRef< AffineExpr > localExprs, MLIRContext *context)
Constructs an affine expression from a flat ArrayRef.
raw_ostream & operator<< (raw_ostream &os, AffineExpr &expr)
bool getFlattenedAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols, SmallVectorImpl< int64_t > *flattenedExpr)
Flattens 'expr' into 'flattenedExpr'.
bool getFlattenedAffineExprs (AffineMap map, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs)
Flattens the result expressions of the map to their corresponding flattened forms and set in 'flattenedExprs'.
bool getFlattenedAffineExprs (IntegerSet set, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs)
template<typename... AffineExprTy>
void bindDims (MLIRContext *ctx, AffineExprTy &... exprs)
Bind a list of AffineExpr references to DimExpr at positions: [0 .
inline ::llvm::hash_code hash_value (AffineMap arg)
AffineMap simplifyAffineMap (AffineMap map)
Simplify an affine map by simplifying its underlying AffineExpr results.
AffineMap inversePermutation (AffineMap map)
Returns a map of codomain to domain dimensions such that the first codomain dimension for a particular domain dimension is selected.
AffineMap concatAffineMaps (ArrayRef< AffineMap > maps)
Concatenates a list of maps into a single AffineMap, stepping over potentially empty maps.
raw_ostream & operator<< (raw_ostream &os, AffineMap map)
raw_ostream & operator<< (raw_ostream &os, Attribute attr)
inline ::llvm::hash_code hash_value (Attribute arg)
raw_ostream & operator<< (raw_ostream &os, const DiagnosticArgument &arg)
raw_ostream & operator<< (raw_ostream &os, const Diagnostic &diag)
InFlightDiagnostic emitError (Location loc)
Utility method to emit an error message using this location.
InFlightDiagnostic emitError (Location loc, const Twine &message)
InFlightDiagnostic emitWarning (Location loc)
Utility method to emit a warning message using this location.
InFlightDiagnostic emitWarning (Location loc, const Twine &message)
InFlightDiagnostic emitRemark (Location loc)
Utility method to emit a remark message using this location.
InFlightDiagnostic emitRemark (Location loc, const Twine &message)
template<typename... Args>
LogicalResult emitOptionalError (Optional< Location > loc, Args &&... args)
Overloads of the above emission functions that take an optionally null location.
template<typename... Args>
LogicalResult emitOptionalWarning (Optional< Location > loc, Args &&... args)
template<typename... Args>
LogicalResult emitOptionalRemark (Optional< Location > loc, Args &&... args)
void registerDialectAllocator (const DialectAllocatorFunction &function)
Registers a specific dialect creation function with the system, typically used through the DialectRegistration template.
void registerAllDialects (MLIRContext *context)
Registers all dialects with the specified MLIRContext.
template<typename ConcreteDialect >
void registerDialect ()
Utility to register a dialect.
void registerDialectHooksSetter (const DialectHooksSetter &function)
Registers a function that will set hooks in the registered dialects based on information coming from DialectHooksRegistration.
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, Attribute attr)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, const APFloat &value)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, float value)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, double value)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, Type type)
template<typename T , typename std::enable_if< !std::is_convertible< T &, Attribute &>::value &&!std::is_convertible< T &, Type &>::value &&!std::is_convertible< T &, APFloat &>::value &&!llvm::is_one_of< T, double, float >::value, T >::type * = nullptr>
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, const T &other)
raw_ostream & operator<< (raw_ostream &os, Identifier identifier)
bool operator== (Identifier lhs, Identifier rhs)
bool operator!= (Identifier lhs, Identifier rhs)
bool operator== (Identifier lhs, StringRef rhs)
bool operator!= (Identifier lhs, StringRef rhs)
bool operator== (StringRef lhs, Identifier rhs)
bool operator!= (StringRef lhs, Identifier rhs)
llvm::hash_code hash_value (Identifier arg)
inline ::llvm::hash_code hash_value (IntegerSet arg)
raw_ostream & operator<< (raw_ostream &os, const Location &loc)
inline ::llvm::hash_code hash_value (Location arg)
detail::constant_op_binder< Attribute > m_Constant ()
Matches a constant foldable operation.
template<typename AttrT >
detail::constant_op_binder< AttrT > m_Constant (AttrT *bind_value)
Matches a value from a constant foldable operation and writes the value to bind_value.
detail::constant_int_value_matcher< 1 > m_One ()
Matches a constant scalar / vector splat / tensor splat integer one.
template<typename OpClass >
detail::op_matcher< OpClass > m_Op ()
Matches the given OpClass.
detail::constant_int_value_matcher< 0 > m_Zero ()
Matches a constant scalar / vector splat / tensor splat integer zero.
detail::constant_int_not_value_matcher< 0 > m_NonZero ()
Matches a constant scalar / vector splat / tensor splat integer that is any non-zero value.
template<typename Pattern >
bool matchPattern (Value value, const Pattern &pattern)
Entry point for matching a pattern over a Value.
template<typename Pattern >
bool matchPattern (Operation *op, const Pattern &pattern)
Entry point for matching a pattern over an Operation.
detail::constant_int_op_binder m_ConstantInt (IntegerAttr::ValueType *bind_value)
Matches a constant holding a scalar/vector/tensor integer (splat) and writes the integer value to bind_value.
template<typename OpType , typename... Matchers>
auto m_Op (Matchers... matchers)
bool operator== (OpState lhs, OpState rhs)
bool operator!= (OpState lhs, OpState rhs)
raw_ostream & operator<< (raw_ostream &os, Operation &op)
raw_ostream & operator<< (raw_ostream &os, OperationName identifier)
bool operator== (OperationName lhs, OperationName rhs)
bool operator!= (OperationName lhs, OperationName rhs)
llvm::hash_code hash_value (OperationName arg)
OpAsmPrinter & operator<< (OpAsmPrinter &p, Value value)
template<typename T , typename std::enable_if< std::is_convertible< T &, ValueRange >::value &&!std::is_convertible< T &, Value &>::value, T >::type * = nullptr>
OpAsmPrinter & operator<< (OpAsmPrinter &p, const T &values)
OpAsmPrinter & operator<< (OpAsmPrinter &p, Type type)
OpAsmPrinter & operator<< (OpAsmPrinter &p, Attribute attr)
OpAsmPrinter & operator<< (OpAsmPrinter &p, bool value)
template<typename IteratorT >
OpAsmPrinter & operator<< (OpAsmPrinter &p, const iterator_range< ValueTypeIterator< IteratorT >> &types)
bool applyPatternsGreedily (Operation *op, const OwningRewritePatternList &patterns)
Rewrite the regions of the specified operation, which must be isolated from above, by repeatedly applying the highest benefit patterns in a greedy work-list driven manner.
bool applyPatternsGreedily (MutableArrayRef< Region > regions, const OwningRewritePatternList &patterns)
Rewrite the given regions, which must be isolated from above.
LogicalResult getStridesAndOffset (MemRefType t, SmallVectorImpl< int64_t > &strides, int64_t &offset)
Returns the strides of the MemRef if the layout map is in strided form.
LogicalResult getStridesAndOffset (MemRefType t, SmallVectorImpl< AffineExpr > &strides, AffineExpr &offset)
AffineMap makeStridedLinearLayoutMap (ArrayRef< int64_t > strides, int64_t offset, MLIRContext *context)
Given a list of strides (in which MemRefType::getDynamicStrideOrOffset() represents a dynamic value), return the single result AffineMap which represents the linearized strided layout map.
MemRefType canonicalizeStridedLayout (MemRefType t)
Return a version of t with identity layout if it can be determined statically that the layout is the canonical contiguous strided layout.
bool isStrided (MemRefType t)
Return true if the layout for t is compatible with strided semantics.
raw_ostream & operator<< (raw_ostream &os, Type type)
inline ::llvm::hash_code hash_value (Type arg)
Type getElementTypeOrSelf (Type type)
Return the element type or return the type itself.
Type getElementTypeOrSelf (Attribute attr)
Return the element type or return the type itself.
Type getElementTypeOrSelf (Value val)
SmallVector< Type, 10 > getFlattenedTypes (TupleType t)
Get the types within a nested Tuple.
bool isOpaqueTypeWithName (Type type, StringRef dialect, StringRef typeData)
Return true if the specified type is an opaque type with the specified dialect and typeData.
LogicalResult verifyCompatibleShape (ArrayRef< int64_t > shape1, ArrayRef< int64_t > shape2)
Returns success if the given two shapes are compatible.
LogicalResult verifyCompatibleShape (Type type1, Type type2)
Returns success if the given two types have compatible shape.
raw_ostream & operator<< (raw_ostream &os, Value value)
inline ::llvm::hash_code hash_value (Value arg)
Make Value hashable.
OwningModuleRef parseSourceFile (const llvm::SourceMgr &sourceMgr, MLIRContext *context)
This parses the file specified by the indicated SourceMgr and returns an MLIR module if it was valid.
OwningModuleRef parseSourceFile (llvm::StringRef filename, MLIRContext *context)
This parses the file specified by the indicated filename and returns an MLIR module if it was valid.
OwningModuleRef parseSourceFile (llvm::StringRef filename, llvm::SourceMgr &sourceMgr, MLIRContext *context)
This parses the file specified by the indicated filename using the provided SourceMgr and returns an MLIR module if it was valid.
OwningModuleRef parseSourceString (llvm::StringRef moduleStr, MLIRContext *context)
This parses the module string to a MLIR module if it was valid.
Attribute parseAttribute (llvm::StringRef attrStr, MLIRContext *context)
This parses a single MLIR attribute to an MLIR context if it was valid.
Attribute parseAttribute (llvm::StringRef attrStr, Type type)
Attribute parseAttribute (llvm::StringRef attrStr, MLIRContext *context, size_t &numRead)
This parses a single MLIR attribute to an MLIR context if it was valid.
Attribute parseAttribute (llvm::StringRef attrStr, Type type, size_t &numRead)
Type parseType (llvm::StringRef typeStr, MLIRContext *context)
This parses a single MLIR type to an MLIR context if it was valid.
Type parseType (llvm::StringRef typeStr, MLIRContext *context, size_t &numRead)
This parses a single MLIR type to an MLIR context if it was valid.
void registerPassManagerCLOptions ()
Register a set of useful command-line options that can be used to configure a pass manager.
void applyPassManagerCLOptions (PassManager &pm)
Apply any values provided to the pass manager options that were registered with 'registerPassManagerOptions'.
void registerPassPipeline (StringRef arg, StringRef description, const PassRegistryFunction &function)
Register a specific dialect pipeline registry function with the system, typically used through the PassPipelineRegistration template.
void registerPass (StringRef arg, StringRef description, const PassID *passID, const PassAllocatorFunction &function)
Register a specific dialect pass allocator function with the system, typically used through the PassRegistration template.
LogicalResult parsePassPipeline (StringRef pipeline, OpPassManager &pm, raw_ostream &errorStream=llvm::errs())
This function parses the textual representation of a pass pipeline, and adds the result to 'pm' on success.
template<typename T >
static std::string debugString (T &op)
std::unique_ptr< llvm::MemoryBuffer > openInputFile (llvm::StringRef inputFilename, std::string *errorMessage=nullptr)
Open the file specified by its name for reading.
std::unique_ptr< llvm::ToolOutputFile > openOutputFile (llvm::StringRef outputFilename, std::string *errorMessage=nullptr)
Open the file specified by its name for writing.
int JitRunnerMain (int argc, char **argv, llvm::function_ref< LogicalResult(mlir::ModuleOp)> mlirTransformer)
LogicalResult success (bool isSuccess=true)
Utility function to generate a LogicalResult.
LogicalResult failure (bool isFailure=true)
Utility function to generate a LogicalResult.
bool succeeded (LogicalResult result)
Utility function that returns true if the provided LogicalResult corresponds to a success value.
bool failed (LogicalResult result)
Utility function that returns true if the provided LogicalResult corresponds to a failure value.
int64_t ceilDiv (int64_t lhs, int64_t rhs)
Returns the result of MLIR's ceildiv operation on constants.
int64_t floorDiv (int64_t lhs, int64_t rhs)
Returns the result of MLIR's floordiv operation on constants.
int64_t mod (int64_t lhs, int64_t rhs)
Returns MLIR's mod operation on constants.
int64_t lcm (int64_t a, int64_t b)
Returns the least common multiple of 'a' and 'b'.
LogicalResult MlirOptMain (llvm::raw_ostream &os, std::unique_ptr< llvm::MemoryBuffer > buffer, const PassPipelineCLParser &passPipeline, bool splitInputFile, bool verifyDiagnostics, bool verifyPasses)
template<typename ForwardIterator , typename UnaryFunctor , typename NullaryFunctor , typename = typename std::enable_if< !std::is_constructible<StringRef, UnaryFunctor>::value && !std::is_constructible<StringRef, NullaryFunctor>::value>::type>
void interleave (ForwardIterator begin, ForwardIterator end, UnaryFunctor each_fn, NullaryFunctor between_fn)
An STL-style algorithm similar to std::for_each that applies a second functor between every pair of elements.
template<typename Container , typename UnaryFunctor , typename NullaryFunctor , typename = typename std::enable_if< !std::is_constructible<StringRef, UnaryFunctor>::value && !std::is_constructible<StringRef, NullaryFunctor>::value>::type>
void interleave (const Container &c, UnaryFunctor each_fn, NullaryFunctor between_fn)
template<typename Container , typename UnaryFunctor , typename raw_ostream , typename T = detail::ValueOfRange<Container>>
void interleave (const Container &c, raw_ostream &os, UnaryFunctor each_fn, const StringRef &separator)
Overload of interleave for the common case of string separator.
template<typename Container , typename raw_ostream , typename T = detail::ValueOfRange<Container>>
void interleave (const Container &c, raw_ostream &os, const StringRef &separator)
template<typename Container , typename UnaryFunctor , typename raw_ostream , typename T = detail::ValueOfRange<Container>>
void interleaveComma (const Container &c, raw_ostream &os, UnaryFunctor each_fn)
template<typename Container , typename raw_ostream , typename T = detail::ValueOfRange<Container>>
void interleaveComma (const Container &c, raw_ostream &os)
template<typename ContainerTy >
auto make_second_range (ContainerTy &&c)
Given a container of pairs, return a range over the second elements.
template<typename ContainerTy >
bool has_single_element (ContainerTy &&c)
Returns true of the given range only contains a single element.
std::string convertToSnakeCase (llvm::StringRef input)
Converts a string to snake-case from camel-case by replacing all uppercase letters with '_' followed by the letter in lowercase, except if the uppercase letter is the first character of the string.
std::string convertToCamelCase (llvm::StringRef input, bool capitalizeFirst=false)
Converts a string from camel-case to snake_case by replacing all occurrences of '_' followed by a lowercase letter with the letter in uppercase.
LogicalResult splitAndProcessBuffer (std::unique_ptr< llvm::MemoryBuffer > originalBuffer, ChunkBufferHandler processChunkBuffer, raw_ostream &os)
Splits the specified buffer on a marker (// -----), processes each chunk independently according to the normal processChunkBuffer logic, and writes all results to os.
std::unique_ptr< llvm::Module > translateModuleToLLVMIR (ModuleOp m)
Convert the given MLIR module into LLVM IR.
OwningModuleRef translateLLVMIRToModule (std::unique_ptr< llvm::Module > llvmModule, MLIRContext *context)
Convert the given LLVM module into MLIR's LLVM dialect.
std::unique_ptr< llvm::Module > translateModuleToNVVMIR (Operation *m)
Convert the given LLVM-module-like operation into NVVM IR.
std::unique_ptr< llvm::Module > translateModuleToROCDLIR (Operation *m)
Convert the given LLVM-module-like operation into ROCDL IR.
void populateFuncOpTypeConversionPattern (OwningRewritePatternList &patterns, MLIRContext *ctx, TypeConverter &converter)
Add a pattern to the given pattern list to convert the signature of a FuncOp with the given type converter.
LLVM_NODISCARD LogicalResult applyPartialConversion (ArrayRef< Operation *> ops, ConversionTarget &target, const OwningRewritePatternList &patterns, TypeConverter *converter=nullptr)
Below we define several entry points for operation conversion.
LLVM_NODISCARD LogicalResult applyPartialConversion (Operation *op, ConversionTarget &target, const OwningRewritePatternList &patterns, TypeConverter *converter=nullptr)
LLVM_NODISCARD LogicalResult applyFullConversion (ArrayRef< Operation *> ops, ConversionTarget &target, const OwningRewritePatternList &patterns, TypeConverter *converter=nullptr)
Apply a complete conversion on the given operations, and all nested operations.
LLVM_NODISCARD LogicalResult applyFullConversion (Operation *op, ConversionTarget &target, const OwningRewritePatternList &patterns, TypeConverter *converter=nullptr)
LLVM_NODISCARD LogicalResult applyAnalysisConversion (ArrayRef< Operation *> ops, ConversionTarget &target, const OwningRewritePatternList &patterns, DenseSet< Operation *> &convertedOps, TypeConverter *converter=nullptr)
Apply an analysis conversion on the given operations, and all nested operations.
LLVM_NODISCARD LogicalResult applyAnalysisConversion (Operation *op, ConversionTarget &target, const OwningRewritePatternList &patterns, DenseSet< Operation *> &convertedOps, TypeConverter *converter=nullptr)
LogicalResult inlineRegion (InlinerInterface &interface, Region *src, Operation *inlinePoint, BlockAndValueMapping &mapper, ArrayRef< Value > resultsToReplace, Optional< Location > inlineLoc=llvm::None, bool shouldCloneInlinedRegion=true)
This function inlines a region, 'src', into another.
LogicalResult inlineRegion (InlinerInterface &interface, Region *src, Operation *inlinePoint, ArrayRef< Value > inlinedOperands, ArrayRef< Value > resultsToReplace, Optional< Location > inlineLoc=llvm::None, bool shouldCloneInlinedRegion=true)
This function is an overload of the above 'inlineRegion' that allows for providing the set of operands ('inlinedOperands') that should be used in-favor of the region arguments when inlining.
LogicalResult inlineCall (InlinerInterface &interface, CallOpInterface call, CallableOpInterface callable, Region *src, bool shouldCloneInlinedRegion=true)
This function inlines a given region, 'src', of a callable operation, 'callable', into the location defined by the given call operation.
FusionResult canFuseLoops (AffineForOp srcForOp, AffineForOp dstForOp, unsigned dstLoopDepth, ComputationSliceState *srcSlice)
Checks the feasibility of fusing the loop nest rooted at 'srcForOp' into the loop nest rooted at 'dstForOp' at 'dstLoopDepth'.
bool getLoopNestStats (AffineForOp forOp, LoopNestStats *stats)
Collect loop nest statistics (eg.
int64_t getComputeCost (AffineForOp forOp, LoopNestStats &stats)
Computes the total cost of the loop nest rooted at 'forOp' using 'stats'.
bool getFusionComputeCost (AffineForOp srcForOp, LoopNestStats &srcStats, AffineForOp dstForOp, LoopNestStats &dstStats, ComputationSliceState *slice, int64_t *computeCost)
Computes and returns in 'computeCost', the total compute cost of fusing the 'slice' of the loop nest rooted at 'srcForOp' into 'dstForOp'.
LogicalResult loopUnrollFull (AffineForOp forOp)
Unrolls this for operation completely if the trip count is known to be constant.
LogicalResult loopUnrollByFactor (AffineForOp forOp, uint64_t unrollFactor)
Unrolls this for operation by the specified unroll factor.
LogicalResult loopUnrollUpToFactor (AffineForOp forOp, uint64_t unrollFactor)
Unrolls this loop by the specified unroll factor or its trip count, whichever is lower.
void getPerfectlyNestedLoops (SmallVectorImpl< AffineForOp > &nestedLoops, AffineForOp root)
Get perfectly nested sequence of loops starting at root of loop nest (the first op being another AffineFor, and the second op - a terminator).
void getPerfectlyNestedLoops (SmallVectorImpl< loop::ForOp > &nestedLoops, loop::ForOp root)
LogicalResult loopUnrollJamByFactor (AffineForOp forOp, uint64_t unrollJamFactor)
Unrolls and jams this loop by the specified factor.
LogicalResult loopUnrollJamUpToFactor (AffineForOp forOp, uint64_t unrollJamFactor)
Unrolls and jams this loop by the specified factor or by the trip count (if constant), whichever is lower.
LogicalResult promoteIfSingleIteration (AffineForOp forOp)
Promotes the loop body of a AffineForOp to its containing block if the AffineForOp was known to have a single iteration.
void promoteSingleIterationLoops (FuncOp f)
Promotes all single iteration AffineForOp's in the Function, i.e., moves their body into the containing Block.
void getCleanupLoopLowerBound (AffineForOp forOp, unsigned unrollFactor, AffineMap *map, SmallVectorImpl< Value > *operands, OpBuilder &builder)
Computes the cleanup loop lower bound of the loop being unrolled with the specified unroll factor; this bound will also be upper bound of the main part of the unrolled loop.
LLVM_NODISCARD LogicalResult instBodySkew (AffineForOp forOp, ArrayRef< uint64_t > shifts, bool unrollPrologueEpilogue=false)
Skew the operations in the body of a 'affine.for' operation with the specified operation-wise shifts.
LLVM_NODISCARD LogicalResult tileCodeGen (MutableArrayRef< AffineForOp > band, ArrayRef< unsigned > tileSizes)
Tiles the specified band of perfectly nested loops creating tile-space loops and intra-tile loops.
void interchangeLoops (AffineForOp forOpA, AffineForOp forOpB)
Performs loop interchange on 'forOpA' and 'forOpB'.
bool isValidLoopInterchangePermutation (ArrayRef< AffineForOp > loops, ArrayRef< unsigned > loopPermMap)
Checks if the loop interchange permutation 'loopPermMap', of the perfectly nested sequence of loops in 'loops', would violate dependences (loop 'i' in 'loops' is mapped to location 'j = 'loopPermMap[i]' in the interchange).
unsigned interchangeLoops (ArrayRef< AffineForOp > loops, ArrayRef< unsigned > loopPermMap)
Performs a sequence of loop interchanges on perfectly nested 'loops', as specified by permutation 'loopPermMap' (loop 'i' in 'loops' is mapped to location 'j = 'loopPermMap[i]' after the loop interchange).
AffineForOp sinkSequentialLoops (AffineForOp forOp)
void sinkLoop (AffineForOp forOp, unsigned loopDepth)
Sinks 'forOp' by 'loopDepth' levels by performing a series of loop interchanges.
SmallVector< SmallVector< AffineForOp, 8 >, 8 > tile (ArrayRef< AffineForOp > forOps, ArrayRef< uint64_t > sizes, ArrayRef< AffineForOp > targets)
SmallVector< Loops, 8 > tile (ArrayRef< loop::ForOp > forOps, ArrayRef< Value > sizes, ArrayRef< loop::ForOp > targets)
SmallVector< AffineForOp, 8 > tile (ArrayRef< AffineForOp > forOps, ArrayRef< uint64_t > sizes, AffineForOp target)
Performs tiling (with interchange) by strip-mining the forOps by sizes and sinking them, in their order of occurrence in forOps, under target.
Loops tile (ArrayRef< loop::ForOp > forOps, ArrayRef< Value > sizes, loop::ForOp target)
Loops tilePerfectlyNested (loop::ForOp rootForOp, ArrayRef< Value > sizes)
Tile a nest of loop::ForOp loops rooted at rootForOp with the given (parametric) sizes.
uint64_t affineDataCopyGenerate (Block::iterator begin, Block::iterator end, const AffineCopyOptions &copyOptions, DenseSet< Operation *> &copyNests)
Performs explicit copying for the contiguous sequence of operations in the block iterator range [`begin', `end'), where `end' can't be past the terminator of the block (since additional operations are potentially inserted right before end.
TileLoops extractFixedOuterLoops (loop::ForOp rootFOrOp, ArrayRef< int64_t > sizes)
Tile a nest of standard for loops rooted at rootForOp by finding such parametric tile sizes that the outer loops have a fixed number of iterations as defined in sizes.
void coalesceLoops (MutableArrayRef< loop::ForOp > loops)
Replace a perfect nest of "for" loops with a single linearized loop.
void mapLoopToProcessorIds (loop::ForOp forOp, ArrayRef< Value > processorId, ArrayRef< Value > numProcessors)
Maps forOp for execution on a parallel grid of virtual processorIds of size given by numProcessors.
std::unique_ptr< Pass > createCanonicalizerPass ()
Creates an instance of the Canonicalizer pass.
std::unique_ptr< Pass > createCSEPass ()
Creates a pass to perform common sub expression elimination.
std::unique_ptr< OpPassBase< FuncOp > > createVectorizePass (ArrayRef< int64_t > virtualVectorSize)
Creates a pass to vectorize loops, operations and data types using a target-independent, n-D super-vector abstraction.
std::unique_ptr< OpPassBase< FuncOp > > createVectorizerTestPass ()
Creates a pass to allow independent testing of vectorizer functionality with FileCheck.
std::unique_ptr< OpPassBase< FuncOp > > createMaterializeVectorsPass (ArrayRef< int64_t > vectorSize)
Creates a pass to lower super-vectors to target-dependent HW vectors.
std::unique_ptr< OpPassBase< FuncOp > > createLoopUnrollPass (int unrollFactor=-1, int unrollFull=-1, const std::function< unsigned(AffineForOp)> &getUnrollFactor=nullptr)
Creates a loop unrolling pass with the provided parameters.
std::unique_ptr< OpPassBase< FuncOp > > createLoopUnrollAndJamPass (int unrollJamFactor=-1)
Creates a loop unroll jam pass to unroll jam by the specified factor.
std::unique_ptr< OpPassBase< FuncOp > > createSimplifyAffineStructuresPass ()
Creates a simplification pass for affine structures (maps and sets).
std::unique_ptr< OpPassBase< FuncOp > > createLoopFusionPass (unsigned fastMemorySpace=0, uint64_t localBufSizeThreshold=0, bool maximalFusion=false)
Creates a loop fusion pass which fuses loops.
std::unique_ptr< Pass > createLoopInvariantCodeMotionPass ()
Creates a loop invariant code motion pass that hoists loop invariant instructions out of the loop.
std::unique_ptr< OpPassBase< FuncOp > > createAffineLoopInvariantCodeMotionPass ()
Creates a loop invariant code motion pass that hoists loop invariant instructions out of affine loop.
std::unique_ptr< OpPassBase< FuncOp > > createPipelineDataTransferPass ()
Creates a pass to pipeline explicit movement of data across levels of the memory hierarchy.
std::unique_ptr< OpPassBase< FuncOp > > createLowerAffinePass ()
Lowers affine control flow operations (ForStmt, IfStmt and AffineApplyOp) to equivalent lower-level constructs (flow of basic blocks and arithmetic primitives).
std::unique_ptr< OpPassBase< FuncOp > > createLoopTilingPass (uint64_t cacheSizeBytes)
Creates a pass to perform tiling on loop nests.
std::unique_ptr< OpPassBase< FuncOp > > createSimpleParametricTilingPass (ArrayRef< int64_t > outerLoopSizes)
Creates a pass that performs parametric tiling so that the outermost loops have the given fixed number of iterations.
std::unique_ptr< OpPassBase< FuncOp > > createLoopCoalescingPass ()
Creates a pass that transforms perfectly nested loops with independent bounds into a single loop.
std::unique_ptr< OpPassBase< FuncOp > > createAffineDataCopyGenerationPass (unsigned slowMemorySpace, unsigned fastMemorySpace, unsigned tagMemorySpace=0, int minDmaTransferSize=1024, uint64_t fastMemCapacityBytes=std::numeric_limits< uint64_t >::max())
Performs packing (or explicit copying) of accessed memref regions into buffers in the specified faster memory space through either pointwise copies or DMA operations.
std::unique_ptr< OpPassBase< FuncOp > > createMemRefDataFlowOptPass ()
Creates a pass to perform optimizations relying on memref dataflow such as store to load forwarding, elimination of dead stores, and dead allocs.
std::unique_ptr< OpPassBase< FuncOp > > createStripDebugInfoPass ()
Creates a pass to strip debug information from a function.
std::unique_ptr< OpPassBase< FuncOp > > createTestLoopFusionPass ()
Creates a pass which tests loop fusion utilities.
std::unique_ptr< Pass > createInlinerPass ()
Creates a pass which inlines calls and callable operations as defined by the CallGraph.
template<typename Range >
bool areValuesDefinedAbove (Range values, Region &limit)
Check if all values in the provided range are defined above the limit region.
void replaceAllUsesInRegionWith (Value orig, Value replacement, Region &region)
Replace all uses of orig within the given region with replacement.
void visitUsedValuesDefinedAbove (Region &region, Region &limit, function_ref< void(OpOperand *)> callback)
Calls callback for each use of a value within region or its descendants that was defined at the ancestors of the limit.
void visitUsedValuesDefinedAbove (MutableArrayRef< Region > regions, function_ref< void(OpOperand *)> callback)
Calls callback for each use of a value within any of the regions provided that was defined in one of the ancestors.
void getUsedValuesDefinedAbove (Region &region, Region &limit, llvm::SetVector< Value > &values)
Fill values with a list of values defined at the ancestors of the limit region and used within region or its descendants.
void getUsedValuesDefinedAbove (MutableArrayRef< Region > regions, llvm::SetVector< Value > &values)
Fill values with a list of values used within any of the regions provided but defined in one of the ancestors.
LogicalResult simplifyRegions (MutableArrayRef< Region > regions)
Run a set of structural simplifications over the given regions.
LogicalResult replaceAllMemRefUsesWith (Value oldMemRef, Value newMemRef, ArrayRef< Value > extraIndices={}, AffineMap indexRemap=AffineMap(), ArrayRef< Value > extraOperands={}, ArrayRef< Value > symbolOperands={}, Operation *domInstFilter=nullptr, Operation *postDomInstFilter=nullptr)
Replaces all "dereferencing" uses of oldMemRef with newMemRef while optionally remapping the old memref's indices using the supplied affine map, indexRemap.
LogicalResult replaceAllMemRefUsesWith (Value oldMemRef, Value newMemRef, Operation *op, ArrayRef< Value > extraIndices={}, AffineMap indexRemap=AffineMap(), ArrayRef< Value > extraOperands={}, ArrayRef< Value > symbolOperands={})
Performs the same replacement as the other version above but only for the dereferencing uses of oldMemRef in op.
LogicalResult normalizeMemRef (AllocOp op)
Rewrites the memref defined by this alloc op to have an identity layout map and updates all its indexing uses.
Operation * createComposedAffineApplyOp (OpBuilder &builder, Location loc, ArrayRef< Value > operands, ArrayRef< Operation *> affineApplyOps, SmallVectorImpl< Value > *results)
Creates and inserts into 'builder' a new AffineApplyOp, with the number of its results equal to the number of operands, as a composition of all other AffineApplyOps reachable from input parameter 'operands'.
void createAffineComputationSlice (Operation *opInst, SmallVectorImpl< AffineApplyOp > *sliceOps)
Given an operation, inserts one or more single result affine apply operations, results of which are exclusively used by this operation.
void viewGraph (Block &block, const Twine &name, bool shortNames=false, const Twine &title="", llvm::GraphProgram::Name program=llvm::GraphProgram::DOT)
Displays the graph in a window.
raw_ostream & writeGraph (raw_ostream &os, Block &block, bool shortNames=false, const Twine &title="")
std::unique_ptr< OpPassBase< ModuleOp > > createPrintOpGraphPass (raw_ostream &os=llvm::errs(), bool shortNames=false, const Twine &title="")
Creates a pass to print op graphs.
void viewGraph (Region &region, const Twine &name, bool shortNames=false, const Twine &title="", llvm::GraphProgram::Name program=llvm::GraphProgram::DOT)
Displays the CFG in a window.
raw_ostream & writeGraph (raw_ostream &os, Region &region, bool shortNames=false, const Twine &title="")
std::unique_ptr< mlir::OpPassBase< mlir::FuncOp > > createPrintCFGGraphPass (raw_ostream &os=llvm::errs(), bool shortNames=false, const Twine &title="")
Creates a pass to print CFG graphs.
const llvm::StringMap< TranslateSourceMgrToMLIRFunction > & getTranslationToMLIRRegistry ()
Get a read-only reference to the translator registry.
const llvm::StringMap< TranslateFromMLIRFunction > & getTranslationFromMLIRRegistry ()
const llvm::StringMap< TranslateFunction > & getTranslationRegistry ()
Variables
std::function< llvm::Error(llvm::Module *)> makeOptimizingTransformer (unsigned optLevel, unsigned sizeLevel, llvm::TargetMachine *targetMachine)
Create a module transformer function for MLIR ExecutionEngine that runs LLVM IR passes corresponding to the given speed and size optimization levels (e.g.
std::function< llvm::Error(llvm::Module *)> makeLLVMPassesTransformer (llvm::ArrayRef< const llvm::PassInfo *> llvmPasses, llvm::Optional< unsigned > mbOptLevel, llvm::TargetMachine *targetMachine, unsigned optPassesInsertPos=0)
Create a module transformer function for MLIR ExecutionEngine that runs LLVM IR passes explicitly specified, plus an optional optimization level, Any optimization passes, if present, will be inserted before the pass at position optPassesInsertPos.
Detailed Description
This file provides some simple template functional-style sugar to operate on value types.
Make sure when using that the stored type is cheap to copy!
TODO(ntv): add some static_assert but we need proper traits for this.
Typedef Documentation
AnalysisID
typedef ClassID mlir::AnalysisID
A special type used by analyses to provide an address that identifies a particular analysis set or a concrete analysis type.
Definition at line 22 of file AnalysisManager.h.
AttributeStorageAllocator
using mlir::AttributeStorageAllocator = typedef StorageUniquer::StorageAllocator
Definition at line 81 of file AttributeSupport.h.
ChunkBufferHandler
using mlir::ChunkBufferHandler = typedef function_ref<LogicalResult(std::unique_ptr<llvm::MemoryBuffer> chunkBuffer, raw_ostream &os)>
Definition at line 28 of file ToolUtilities.h.
CubinGenerator
using mlir::CubinGenerator = typedef std::function<OwnedCubin(const std::string &, Location, StringRef)>
Definition at line 34 of file GPUToCUDAPass.h.
DefaultAttributeStorage
using mlir::DefaultAttributeStorage = typedef AttributeStorage
Default storage type for attributes that require no additional initialization or storage.
Definition at line 73 of file AttributeSupport.h.
DefaultTypeStorage
using mlir::DefaultTypeStorage = typedef TypeStorage
Default storage type for types that require no additional initialization or storage.
Definition at line 70 of file TypeSupport.h.
DenseMap
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> using mlir::DenseMap = typedef llvm::DenseMap<KeyT, ValueT, KeyInfoT, BucketT>
Definition at line 73 of file LLVM.h.
DenseSet
template<typename ValueT , typename ValueInfoT = DenseMapInfo<ValueT>> using mlir::DenseSet = typedef llvm::DenseSet<ValueT, ValueInfoT>
Definition at line 75 of file LLVM.h.
DialectAllocatorFunction
using mlir::DialectAllocatorFunction = typedef std::function<void(MLIRContext *)>
Definition at line 284 of file Dialect.h.
DialectConstantDecodeHook
using mlir::DialectConstantDecodeHook = typedef std::function<bool(const OpaqueElementsAttr, ElementsAttr &)>
Definition at line 26 of file Dialect.h.
DialectConstantFoldHook
using mlir::DialectConstantFoldHook = typedef std::function<LogicalResult(Operation *, ArrayRef<Attribute>, SmallVectorImpl<Attribute> &)>
Definition at line 28 of file Dialect.h.
DialectExtractElementHook
using mlir::DialectExtractElementHook = typedef std::function<Attribute(const OpaqueElementsAttr, ArrayRef<uint64_t>)>
Definition at line 30 of file Dialect.h.
DialectHooksSetter
using mlir::DialectHooksSetter = typedef std::function<void(MLIRContext *)>
Definition at line 20 of file DialectHooks.h.
DominanceInfoNode
using mlir::DominanceInfoNode = typedef llvm::DomTreeNodeBase<Block>
Definition at line 19 of file Dominance.h.
FilterFunctionType
using mlir::FilterFunctionType = typedef std::function<bool(Operation &)>
A NestedPattern is a nested operation walker that:
recursively matches a substructure in the tree;
uses a filter function to refine matches with extra semantic constraints (passed via a lambda of type FilterFunctionType);
TODO(ntv) optionally applies actions (lambda).
Nested patterns are meant to capture imperfectly nested loops while matching properties over the whole loop nest. For instance, in vectorization we are interested in capturing all the imperfectly nested loops of a certain type and such that all the load and stores have certain access patterns along the loops' induction variables). Such NestedMatches are first captured using the match function and are later processed to analyze properties and apply transformations in a non-greedy way.
The NestedMatches captured in the IR can grow large, especially after aggressive unrolling. As experience has shown, it is generally better to use a plain walk over operations to match flat patterns but the current implementation is competitive nonetheless.
Definition at line 90 of file NestedMatcher.h.
function_ref
template<typename Fn > using mlir::function_ref = typedef llvm::function_ref<Fn>
Definition at line 76 of file LLVM.h.
GenFunction
using mlir::GenFunction = typedef std::function<bool(const llvm::RecordKeeper &recordKeeper, raw_ostream &os)>
Generator function to invoke.
Definition at line 24 of file GenInfo.h.
is_detected
template<template< class... > class Op, class... Args> using mlir::is_detected = typedef typename detail::detector<void, Op, Args...>::value_t
Definition at line 125 of file STLExtras.h.
is_invocable
template<typename Callable , typename... Args> using mlir::is_invocable = typedef is_detected<detail::is_invocable, Callable, Args...>
Definition at line 135 of file STLExtras.h.
LLVMPatternListFiller
using mlir::LLVMPatternListFiller = typedef std::function<void(LLVMTypeConverter &, OwningRewritePatternList &)>
Type for a callback constructing the owning list of patterns for the conversion to the LLVMIR dialect.
The callback is expected to append patterns to the owning list provided as the second argument.
Definition at line 38 of file ConvertStandardToLLVMPass.h.
LLVMTypeConverterMaker
using mlir::LLVMTypeConverterMaker = typedef std::function<std::unique_ptr<LLVMTypeConverter>(MLIRContext *)>
Type for a callback constructing the type converter for the conversion to the LLVMIR dialect.
The callback is expected to return an instance of the converter.
Definition at line 44 of file ConvertStandardToLLVMPass.h.
Loops
using mlir::Loops = typedef SmallVector<loop::ForOp, 8>
Performs tiling fo imperfectly nested loops (with interchange) by strip-mining the forOps by sizes and sinking them, in their order of occurrence in forOps, under each of the targets.
Returns the new AffineForOps, one per each of (forOps, targets) pair, nested immediately under each of targets.
Definition at line 127 of file LoopUtils.h.
NamedAttribute
using mlir::NamedAttribute = typedef std::pair<Identifier, Attribute>
NamedAttribute is used for dictionary attributes, it holds an identifier for the name and a value for the attribute.
The attribute pointer should always be non-null.
Definition at line 265 of file Attributes.h.
OpAsmSetValueNameFn
using mlir::OpAsmSetValueNameFn = typedef function_ref<void(Value, StringRef)>
A functor used to set the name of the start of a result group of an operation.
See 'getAsmResultNames' below for more details.
Definition at line 629 of file OpImplementation.h.
OperandAdaptor
template<typename OpTy > using mlir::OperandAdaptor = typedef typename OpTy::OperandAdaptor
This is an adaptor from a list of values to named operands of OpTy.
In a generic operation context, e.g., in dialect conversions, an ordered array of Values is treated as operands of OpTy. This adaptor takes a reference to the array and provides accessors with the same names as OpTy for operands. This makes possible to create function templates that operate on either OpTy or OperandAdaptor<OpTy> seamlessly.
Definition at line 50 of file OperationSupport.h.
OperandElementTypeRange
using mlir::OperandElementTypeRange = typedef iterator_range<OperandElementTypeIterator>
Definition at line 77 of file TypeUtilities.h.
OwnedCubin
using mlir::OwnedCubin = typedef std::unique_ptr<std::vector<char> >
Definition at line 32 of file GPUToCUDAPass.h.
PassAllocatorFunction
using mlir::PassAllocatorFunction = typedef std::function<std::unique_ptr<Pass>()>
Definition at line 28 of file PassRegistry.h.
PassID
using mlir::PassID = typedef ClassID
A special type used by transformation passes to provide an address that can act as a unique identifier during pass registration.
Definition at line 32 of file PassRegistry.h.
PassRegistryFunction
using mlir::PassRegistryFunction = typedef std::function<LogicalResult(OpPassManager &, StringRef options)>
A registry function that adds passes to the given pass manager.
This should also parse options and return success() if parsing succeeded.
Definition at line 27 of file PassRegistry.h.
PatternMatchResult
using mlir::PatternMatchResult = typedef Optional<std::unique_ptr<PatternState> >
This is the type returned by a pattern match.
A match failure returns a None value. A match success returns a Some value with any state the pattern may need to maintain (but may also be null).
Definition at line 72 of file PatternMatch.h.
ResultElementTypeRange
using mlir::ResultElementTypeRange = typedef iterator_range<ResultElementTypeIterator>
Definition at line 94 of file TypeUtilities.h.
TileLoops
using mlir::TileLoops = typedef std::pair<Loops, Loops>
Definition at line 128 of file LoopUtils.h.
TransitiveFilter
using mlir::TransitiveFilter = typedef std::function<bool(Operation *)>
Type of the condition to limit the propagation of transitive use-defs.
This can be used in particular to limit the propagation to a given Scope or to avoid passing through certain types of operation in a configurable manner.
Definition at line 27 of file SliceAnalysis.h.
TranslateFromMLIRFunction
using mlir::TranslateFromMLIRFunction = typedef std::function<LogicalResult(ModuleOp, llvm::raw_ostream &output)>
Interface of the function that translates MLIR to a different format and outputs the result to a stream.
It is allowed to modify the module.
Definition at line 48 of file Translation.h.
TranslateFunction
using mlir::TranslateFunction = typedef std::function<LogicalResult(llvm::SourceMgr &sourceMgr, llvm::raw_ostream &output, MLIRContext *)>
Interface of the function that performs file-to-file translation involving MLIR.
The input file is held in the given MemoryBuffer; the output file should be written to the given raw_ostream. The implementation should create all MLIR constructs needed during the process inside the given context. This can be used for round-tripping external formats through the MLIR system.
Definition at line 56 of file Translation.h.
TranslateSourceMgrToMLIRFunction
using mlir::TranslateSourceMgrToMLIRFunction = typedef std::function<OwningModuleRef(llvm::SourceMgr &sourceMgr, MLIRContext *)>
Interface of the function that translates the sources managed by sourceMgr to MLIR.
The source manager has at least one buffer. The implementation should create a new MLIR ModuleOp in the given context and return a pointer to it, or a nullptr in case of any error.
Definition at line 36 of file Translation.h.
TranslateStringRefToMLIRFunction
using mlir::TranslateStringRefToMLIRFunction = typedef std::function<OwningModuleRef(llvm::StringRef, MLIRContext *)>
Interface of the function that translates the given string to MLIR.
The implementation should create a new MLIR ModuleOp in the given context. If source-related error reporting is required from within the function, use TranslateSourceMgrToMLIRFunction instead.
Definition at line 43 of file Translation.h.
TypeStorageAllocator
using mlir::TypeStorageAllocator = typedef StorageUniquer::StorageAllocator
Definition at line 78 of file TypeSupport.h.
VectorizableLoopFun
using mlir::VectorizableLoopFun = typedef std::function<bool(AffineForOp)>
Definition at line 63 of file LoopAnalysis.h.
Enumeration Type Documentation
AffineExprKind
enum mlir::AffineExprKind strong
Enumerator
Add
Mul
RHS of mul is always a constant or a symbolic expression.
Mod
RHS of mod is always a constant or a symbolic expression with a positive value.
FloorDiv
RHS of floordiv is always a constant or a symbolic expression.
CeilDiv
RHS of ceildiv is always a constant or a symbolic expression.
LAST_AFFINE_BINARY_OP
This is a marker for the last affine binary op.
The range of binary op's is expected to be this element and earlier.
Constant
Constant integer.
DimId
Dimensional identifier.
SymbolId
Symbolic identifier.
Definition at line 38 of file AffineExpr.h.
CmpFPredicate
enum mlir::CmpFPredicate strong
The predicate indicates the type of the comparison to perform: (un)orderedness, (in)equality and less/greater than (or equal to) as well as predicates that are always true or false.
Enumerator
FirstValidValue
AlwaysFalse
OEQ
OGT
OGE
OLT
OLE
ONE
ORD
UEQ
UGT
UGE
ULT
ULE
UNE
UNO
AlwaysTrue
NumPredicates
Definition at line 46 of file Ops.h.
DiagnosticSeverity
enum mlir::DiagnosticSeverity strong
Defines the different supported severity of a diagnostic.
Enumerator
Note
Warning
Error
Remark
Definition at line 40 of file Diagnostics.h.
OperationProperty
enum mlir::OperationProperty strong
Enumerator
Commutative
This bit is set for an operation if it is a commutative operation: that is a binary operator (two inputs) where "a op b" and "b op a" produce the same results.
NoSideEffect
This bit is set for operations that have no side effects: that means that they do not read or write memory, or access any hidden state.
Terminator
This bit is set for an operation if it is a terminator: that means an operation at the end of a block.
IsolatedFromAbove
This bit is set for operations that are completely isolated from above.
This is used for operations whose regions are explicit capture only, i.e. they are never allowed to implicitly reference values defined above the parent operation.
Definition at line 58 of file OperationSupport.h.
PassDisplayMode
enum mlir::PassDisplayMode strong
An enum describing the different display modes for the information within the pass manager.
Enumerator
List
Pipeline
Definition at line 116 of file PassManager.h.
SDBMExprKind
enum mlir::SDBMExprKind strong
Enumerator
Add
Stripe
Diff
Constant
DimId
SymbolId
Neg
Definition at line 26 of file SDBMExpr.h.
Function Documentation
affineDataCopyGenerate()
uint64_t mlir::affineDataCopyGenerate (Block::iterator begin, Block::iterator end, const AffineCopyOptions & copyOptions, DenseSet< Operation *> & copyNests)
Performs explicit copying for the contiguous sequence of operations in the block iterator range [`begin', `end'), where `end' can't be past the terminator of the block (since additional operations are potentially inserted right before end.
Generates copies for a contiguous sequence of operations in block in the iterator range [`begin', `end'), where `end' can't be past the terminator of the block (since additional operations are potentially inserted right before `end'.
Returns the total size of fast memory space buffers used. copyOptions provides various parameters, and the output argument copyNests is the set of all copy nests inserted, each represented by its root affine.for. Since we generate alloc's and dealloc's for all fast buffers (before and after the range of operations resp. or at a hoisted position), all of the fast memory capacity is assumed to be available for processing this block range.
Returns the total size of the fast buffers used.
Definition at line 1595 of file LoopUtils.cpp.
References mlir::Operation::emitError(), failed(), mlir::AffineCopyOptions::fastMemCapacityBytes, findHighestBlockForPlacement(), generateCopy(), getFullMemRefAsRegion(), mlir::Operation::getLoc(), getNestingDepth(), mlir::AffineCopyOptions::slowMemorySpace, and succeeded().
Referenced by createAffineDataCopyGenerationPass().
applyAnalysisConversion() [1/2]
LogicalResult mlir::applyAnalysisConversion (ArrayRef< Operation *> ops, ConversionTarget & target, const OwningRewritePatternList & patterns, DenseSet< Operation *> & convertedOps, TypeConverter * converter = nullptr)
Apply an analysis conversion on the given operations, and all nested operations.
This method analyzes which operations would be successfully converted to the target if a conversion was applied. All operations that were found to be legalizable to the given 'target' are placed within the provided 'convertedOps' set; note that no actual rewrites are applied to the operations on success and only pre-existing operations are added to the set. This method only returns failure if there are unreachable blocks in any of the regions nested within 'ops', or if a type conversion failed. If 'converter' is provided, the signatures of blocks and regions are also considered for conversion.
This method analyzes which operations would be successfully converted to the target if a conversion was applied. All operations that were found to be legalizable to the given 'target' are placed within the provided 'convertedOps' set; note that no actual rewrites are applied to the operations on success and only pre-existing operations are added to the set.
Definition at line 1829 of file DialectConversion.cpp.
Referenced by applyAnalysisConversion(), and mlir::ConversionTarget::isDynamicallyLegal().
applyAnalysisConversion() [2/2]
LogicalResult mlir::applyAnalysisConversion (Operation * op, ConversionTarget & target, const OwningRewritePatternList & patterns, DenseSet< Operation *> & convertedOps, TypeConverter * converter = nullptr)
Definition at line 1838 of file DialectConversion.cpp.
References applyAnalysisConversion().
applyFullConversion() [1/2]
LogicalResult mlir::applyFullConversion (ArrayRef< Operation *> ops, ConversionTarget & target, const OwningRewritePatternList & patterns, TypeConverter * converter = nullptr)
Apply a complete conversion on the given operations, and all nested operations.
This method returns failure if the conversion of any operation fails, or if there are unreachable blocks in any of the regions nested within 'ops'. If 'converter' is provided, the signatures of blocks and regions are also converted.
This method will return failure if the conversion of any operation fails.
Definition at line 1809 of file DialectConversion.cpp.
Referenced by applyFullConversion(), mlir::ConversionTarget::isDynamicallyLegal(), populateLinalgToLLVMConversionPatterns(), and populateSPIRVLayoutInfoPatterns().
applyFullConversion() [2/2]
LogicalResult mlir::applyFullConversion (Operation * op, ConversionTarget & target, const OwningRewritePatternList & patterns, TypeConverter * converter = nullptr)
Definition at line 1816 of file DialectConversion.cpp.
References applyFullConversion().
applyPartialConversion() [1/2]
LogicalResult mlir::applyPartialConversion (ArrayRef< Operation *> ops, ConversionTarget & target, const OwningRewritePatternList & patterns, TypeConverter * converter = nullptr)
Below we define several entry points for operation conversion.
Apply a partial conversion on the given operations, and all nested operations.
It is important to note that the patterns provided to the conversion framework may have additional constraints. See the PatternRewriter Hooks section of the ConversionPatternRewriter, to see what additional constraints are imposed on the use of the PatternRewriter. Apply a partial conversion on the given operations, and all nested operations. This method converts as many operations to the target as possible, ignoring operations that failed to legalize. This method only returns failure if there are unreachable blocks in any of the regions nested within 'ops'. If 'converter' is provided, the signatures of blocks and regions are also converted.
This method converts as many operations to the target as possible, ignoring operations that failed to legalize.
Definition at line 1791 of file DialectConversion.cpp.
Referenced by applyPartialConversion(), mlir::ConversionTarget::isDynamicallyLegal(), lowerEntryPointABIAttr(), makeStandardToLLVMTypeConverter(), populateAffineToStdConversionPatterns(), populateLoopToStdConversionPatterns(), and populateVectorToLLVMConversionPatterns().
applyPartialConversion() [2/2]
LogicalResult mlir::applyPartialConversion (Operation * op, ConversionTarget & target, const OwningRewritePatternList & patterns, TypeConverter * converter = nullptr)
Definition at line 1798 of file DialectConversion.cpp.
References applyPartialConversion().
applyPassManagerCLOptions()
void mlir::applyPassManagerCLOptions (PassManager & pm)
Apply any values provided to the pass manager options that were registered with 'registerPassManagerOptions'.
Definition at line 153 of file PassManagerOptions.cpp.
References mlir::PassManager::disableMultithreading(), mlir::PassManager::enableCrashReproducerGeneration(), and mlir::PassManager::enableStatistics().
Referenced by performActions(), and mlir::PassManager::IRPrinterConfig::shouldPrintAfterOnlyOnChange().
applyPatternsGreedily() [1/2]
bool mlir::applyPatternsGreedily (Operation * op, const OwningRewritePatternList & patterns)
Rewrite the regions of the specified operation, which must be isolated from above, by repeatedly applying the highest benefit patterns in a greedy work-list driven manner.
Return true if no more patterns can be matched in the result operation regions. Note: This does not apply patterns to the top-level operation itself. Note: These methods also perform folding and simple dead-code elimination before attempting to match any of the provided patterns.
Return true if no more patterns can be matched in the result operation regions. Note: This does not apply patterns to the top-level operation itself.
Definition at line 218 of file GreedyPatternRewriteDriver.cpp.
References mlir::Operation::getRegions().
Referenced by canonicalizeSCC(), mlir::fxpmath::createLowerUniformRealMathPass(), emitLoopRanges(), populateStdLegalizationPatternsForSPIRVLowering(), populateVectorToLLVMConversionPatterns(), and tryRewriteAffineMulEwSigned().
applyPatternsGreedily() [2/2]
bool mlir::applyPatternsGreedily (MutableArrayRef< Region > regions, const OwningRewritePatternList & patterns)
Rewrite the given regions, which must be isolated from above.
Definition at line 224 of file GreedyPatternRewriteDriver.cpp.
References maxPatternMatchIterations().
areValuesDefinedAbove()
template<typename Range > bool mlir::areValuesDefinedAbove (Range values, Region & limit)
Check if all values in the provided range are defined above the limit region.
That is, if they are defined in a region that is a proper ancestor of limit.
Definition at line 23 of file RegionUtils.h.
References getUsedValuesDefinedAbove(), replaceAllUsesInRegionWith(), simplifyRegions(), and visitUsedValuesDefinedAbove().
Referenced by checkLoopNestMappableImpl().
bindDims()
template<typename... AffineExprTy> void mlir::bindDims (MLIRContext * ctx, AffineExprTy &... exprs)
Bind a list of AffineExpr references to DimExpr at positions: [0 .
. sizeof...(exprs)]
Definition at line 286 of file AffineExpr.h.
Referenced by mlir::edsc::ops::linalg_conv_nhwc(), mlir::edsc::ops::linalg_dilated_conv_nhwc(), and mlir::edsc::ops::linalg_matmul().
boundCheckLoadOrStoreOp()
template<typename LoadOrStoreOpPointer > LogicalResult mlir::boundCheckLoadOrStoreOp (LoadOrStoreOpPointer loadOrStoreOp, bool emitError = true)
Checks a load or store op for an out of bound access; returns failure if the access is out of bounds along any of the dimensions, success otherwise.
Emits a diagnostic error (with location information) if emitError is true.
Definition at line 371 of file Utils.cpp.
References mlir::FlatAffineConstraints::addConstantUpperBound(), emitError(), failed(), failure(), mlir::Operation::getLoc(), and success().
Referenced by createMemRefBoundCheckPass().
buildTripCountMapAndOperands()
void mlir::buildTripCountMapAndOperands (AffineForOp forOp, AffineMap * tripCountMap, SmallVectorImpl< Value > * tripCountOperands)
Returns the trip count of the loop as an affine map with its corresponding operands if the latter is expressible as an affine expression, and nullptr otherwise.
Returns the trip count of the loop as an affine expression if the latter is expressible as an affine expression, and nullptr otherwise.
This method always succeeds as long as the lower bound is not a multi-result map. The trip count expression is simplified before returning. This method only utilizes map composition to construct lower and upper bounds before computing the trip count expressions
The trip count expression is simplified before returning. This method only utilizes map composition to construct lower and upper bounds before computing the trip count expressions.
Definition at line 35 of file LoopAnalysis.cpp.
References mlir::StandardAttributes::AffineMap, ceilDiv(), mlir::AffineExpr::ceilDiv(), mlir::AffineValueMap::difference(), mlir::AffineMap::get(), mlir::AffineValueMap::getAffineMap(), mlir::AffineValueMap::getNumResults(), mlir::AffineValueMap::getOperands(), mlir::AffineValueMap::getResult(), and mlir::AffineValueMap::setResult().
Referenced by getCleanupLoopLowerBound(), getConstantTripCount(), and getLargestDivisorOfTripCount().
canFuseLoops()
FusionResult mlir::canFuseLoops (AffineForOp srcForOp, AffineForOp dstForOp, unsigned dstLoopDepth, ComputationSliceState * srcSlice)
Checks the feasibility of fusing the loop nest rooted at 'srcForOp' into the loop nest rooted at 'dstForOp' at 'dstLoopDepth'.
Returns FusionResult 'Success' if fusion of the src/dst loop nests is feasible (i.e. they are in the same block and dependences would not be violated). Otherwise returns a FusionResult explaining why fusion is not feasible. NOTE: This function is not feature complete and should only be used in testing. TODO(andydavis) Update comments when this function is fully implemented.
Definition at line 191 of file LoopFusionUtils.cpp.
References computeSliceUnion(), mlir::FusionResult::FailBlockDependence, failed(), mlir::FusionResult::FailPrecondition, gatherLoadsAndStores(), getFusedLoopNestInsertionPoint(), getNumCommonSurroundingLoops(), and mlir::FusionResult::Success.
Referenced by mlir::FusionResult::FusionResult(), and isFusionProfitable().
canonicalizeMapAndOperands()
void mlir::canonicalizeMapAndOperands (AffineMap * map, SmallVectorImpl< Value > * operands)
Modifies both map and operands in-place so as to:
drop duplicate operands
drop unused dims and symbols from map
promote valid symbols to symbolic operands in case they appeared as dimensional operands
propagate constant operands and drop them
Definition at line 731 of file AffineOps.cpp.
References mlir::functional::map().
Referenced by mlir::FlatAffineConstraints::addLowerOrUpperBound(), augmentMapAndBounds(), canonicalizeLoopBounds(), composeAffineMapAndOperands(), mlir::AffineValueMap::difference(), emitOrFoldComposedAffineApply(), mlir::MemRefAccess::getAccessMap(), getCleanupLoopLowerBound(), mlir::AffineStoreOp::getOperationName(), isFusionProfitable(), makeCanonicalAffineApplies(), and replaceAllMemRefUsesWith().
canonicalizeSetAndOperands()
void mlir::canonicalizeSetAndOperands (IntegerSet * set, SmallVectorImpl< Value > * operands)
Canonicalizes an integer set the same way canonicalizeMapAndOperands does for affine maps.
Definition at line 736 of file AffineOps.cpp.
References mlir::functional::apply(), composeAffineMapAndOperands(), mlir::AffineLoadOp::getMemRef(), mlir::AffineStoreOp::getMemRef(), mlir::AffineStoreOp::getValueToStore(), mlir::functional::map(), and mlir::PatternRewriter::replaceOpWithNewOp().
Referenced by mlir::AffineStoreOp::getOperationName(), and print().
canonicalizeStridedLayout()
MemRefType mlir::canonicalizeStridedLayout (MemRefType t)
Return a version of t with identity layout if it can be determined statically that the layout is the canonical contiguous strided layout.
Otherwise pass t's layout into simplifyAffineMap and return a copy of t with simplified layout.
Otherwise pass t's layout into simplifyAffineMap and return a copy of t with simplified layout. If t has multiple layout maps or a multi-result layout, just return t.
Definition at line 707 of file StandardTypes.cpp.
References mlir::AffineMap::get(), mlir::MemRefType::get(), mlir::MemRefType::getAffineMaps(), mlir::MemRefType::getShape(), makeCanonicalStridedLayoutExpr(), and simplifyAffineExpr().
Referenced by computeReshapeCollapsedType(), and mlir::NoneType::kindof().
ceilDiv()
int64_t mlir::ceilDiv (int64_t lhs, int64_t rhs) inline
Returns the result of MLIR's ceildiv operation on constants.
The RHS is expected to be positive.
Definition at line 23 of file MathExtras.h.
Referenced by buildTripCountMapAndOperands(), generateTransferOpSlices(), mlir::FlatAffineConstraints::getConstantBoundOnDimSize(), isValidExtractOrInsertSlicesType(), and mlir::AffineExpr::operator!().
checkMemrefAccessDependence()
DependenceResult mlir::checkMemrefAccessDependence (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess, unsigned loopDepth, FlatAffineConstraints * dependenceConstraints, SmallVector< DependenceComponent, 2 > * dependenceComponents, bool allowRAR = false)
Definition at line 764 of file AffineAnalysis.cpp.
References addDomainConstraints(), addMemRefAccessConstraints(), addOrderingConstraints(), buildDimAndSymbolPositionMaps(), computeDirectionVector(), mlir::Operation::dump(), mlir::FlatAffineConstraints::dump(), failed(), mlir::DependenceResult::Failure, mlir::MemRefAccess::getAccessMap(), getInstIndexSet(), getNumCommonLoops(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::DependenceResult::HasDependence, initDependenceConstraints(), mlir::FlatAffineConstraints::isEmpty(), mlir::MemRefAccess::memref, mlir::DependenceResult::NoDependence, mlir::MemRefAccess::opInst, and srcAppearsBeforeDstInAncestralBlock().
Referenced by checkDependences(), computeSliceUnion(), createMemRefDataFlowOptPass(), mlir::DependenceResult::DependenceResult(), getDependenceComponents(), getMaxLoopDepth(), and isLoopParallel().
coalesceLoops()
void mlir::coalesceLoops (MutableArrayRef< loop::ForOp > loops)
Replace a perfect nest of "for" loops with a single linearized loop.
Assumes loops contains a list of perfectly nested loops with bounds and steps independent of any loop induction variable involved in the nest.
Definition at line 1041 of file LoopUtils.cpp.
References mlir::OpBuilder::create(), normalizeLoop(), replaceAllUsesInRegionWith(), and mlir::OpBuilder::setInsertionPointToStart().
computeSliceUnion()
LogicalResult mlir::computeSliceUnion (ArrayRef< Operation *> opsA, ArrayRef< Operation *> opsB, unsigned loopDepth, unsigned numCommonLoops, bool isBackwardSlice, ComputationSliceState * sliceUnion)
Computes in 'sliceUnion' the union of all slice bounds computed at 'loopDepth' between all dependent pairs of ops in 'opsA' and 'opsB'.
The parameter 'numCommonLoops' is the number of loops common to the operations in 'opsA' and 'opsB'. If 'isBackwardSlice' is true, computes slice bounds for loop nest surrounding ops in 'opsA', as a function of IVs and symbols of loop nest surrounding ops in 'opsB' at 'loopDepth'. If 'isBackwardSlice' is false, computes slice bounds for loop nest surrounding ops in 'opsB', as a function of IVs and symbols of loop nest surrounding ops in 'opsA' at 'loopDepth'. Returns 'success' if union was computed, 'failure' otherwise.
Returns 'Success' if union was computed, 'failure' otherwise.
Definition at line 520 of file Utils.cpp.
References addMissingLoopIVBounds(), mlir::StandardAttributes::AffineMap, mlir::FlatAffineConstraints::areIdsAlignedWithOther(), checkMemrefAccessDependence(), mlir::ComputationSliceState::clearBounds(), mlir::FlatAffineConstraints::convertLoopIVSymbolsToDims(), failed(), failure(), mlir::DependenceResult::Failure, mlir::ComputationSliceState::getAsConstraints(), getComputationSliceState(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getIdValues(), getInnermostCommonLoopDepth(), getNestingDepth(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::ComputationSliceState::insertPoint, mlir::ComputationSliceState::ivs, mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, mlir::MemRefAccess::memref, mlir::FlatAffineConstraints::mergeAndAlignIdsWithOther(), mlir::DependenceResult::NoDependence, mlir::MemRefAccess::opInst, success(), mlir::ComputationSliceState::ubOperands, mlir::ComputationSliceState::ubs, mlir::FlatAffineConstraints::unionBoundingBox(), and mlir::DependenceResult::value.
Referenced by canFuseLoops(), and isFusionProfitable().
concatAffineMaps()
AffineMap mlir::concatAffineMaps (ArrayRef< AffineMap > maps)
Concatenates a list of maps into a single AffineMap, stepping over potentially empty maps.
Assumes each of the underlying map has 0 symbols. The resulting map has a number of dims equal to the max of maps' dims and the concatenated results as its results. Returns an empty map if all input maps are empty.
Example: When applied to the following list of 3 affine maps,
{
  (i, j, k) -> (i, k),
  (i, j, k) -> (k, j),
  (i, j, k) -> (i, j)
}
Returns the map:
(i, j, k) -> (i, k, k, j, i, j)
Definition at line 313 of file AffineMap.cpp.
References mlir::StandardAttributes::AffineMap, mlir::AffineMap::get(), and mlir::AffineMap::getNumResults().
Referenced by emitLoopRanges(), hash_value(), mlir::linalg::tileLinalgOp(), and verifyGenericOp().
constFoldBinaryOp()
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref<ElementValueT(ElementValueT, ElementValueT)>> Attribute mlir::constFoldBinaryOp (ArrayRef< Attribute > operands, const CalculationT & calculate)
Performs constant folding calculate with element-wise behavior on the two attributes in operands and returns the result if possible.
Definition at line 30 of file CommonFolders.h.
References mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getSplatValue(), and mlir::ElementsAttr::getValues().
convertAffineLoopNestToGPULaunch()
LogicalResult mlir::convertAffineLoopNestToGPULaunch (AffineForOp forOp, unsigned numBlockDims, unsigned numThreadDims)
Convert a perfect affine loop nest with the outermost loop identified by forOp into a gpu::Launch operation.
Map numBlockDims outer loops to GPU blocks and numThreadDims to GPU threads. The bounds of the loops that are mapped should be independent of the induction variables of the other mapped loops.
No check on the size of the block or grid, or on the validity of parallelization is performed, it is under the responsibility of the caller to strip-mine the loops and to perform the dependence analysis before calling the conversion.
Definition at line 514 of file LoopsToGPU.cpp.
References convertLoopNestToGPULaunch(), and convertLoopNestToGPULaunch().
convertLoopNestToGPULaunch()
LogicalResult mlir::convertLoopNestToGPULaunch (loop::ForOp forOp, unsigned numBlockDims, unsigned numThreadDims)
Convert a perfect linalg loop nest with the outermost loop identified by forOp into a gpu::Launch operation.
Map numBlockDims outer loops to GPU blocks and numThreadDims to GPU threads. The bounds of the loops that are mapped should be independent of the induction variables of the other mapped loops.
No check on the size of the block or grid, or on the validity of parallelization is performed, it is under the responsibility of the caller to strip-mine the loops and to perform the dependence analysis before calling the conversion.
Referenced by convertAffineLoopNestToGPULaunch().
convertLoopToGPULaunch()
LogicalResult mlir::convertLoopToGPULaunch (loop::ForOp forOp, ArrayRef< Value > numWorkGroups, ArrayRef< Value > workGroupSizes)
Convert a loop operation into a GPU launch with the values provided in numWorkGroups as the grid size and the values provided in workGroupSizes as the block size.
Size of numWorkGroups and workGroupSizes` must be less than or equal to 3. The loop operation can be an imperfectly nested computation with the following restrictions: 1) The loop nest must contain as many perfectly nested loops as the number of values passed in through numWorkGroups. This corresponds to the number of grid dimensions of the launch. All loops within the loop nest must be parallel. 2) The body of the innermost loop of the above perfectly nested loops, must contain statements that satisfy one of the two conditions below: a) A perfect loop nest of depth greater than or equal to the number of values passed in through workGroupSizes, i.e. the number of thread dimensions of the launch. Loops at depth less than or equal to size of workGroupSizes must be parallel. Loops nested deeper can be sequential and are retained as such in the generated GPU launch code. b) Statements that are safe to be executed by all threads within the workgroup. No checks are performed that this is indeed the case. TODO(ravishankarm) : Add checks that verify 2(b) above. The above conditions are assumed to be satisfied by the computation rooted at forOp.
Definition at line 526 of file LoopsToGPU.cpp.
References convertLoopToGPULaunch().
convertToCamelCase()
std::string mlir::convertToCamelCase (llvm::StringRef input, bool capitalizeFirst = false) inline
Converts a string from camel-case to snake_case by replacing all occurrences of '_' followed by a lowercase letter with the letter in uppercase.
Optionally allow capitalization of the first letter (if it is a lowercase letter)
Definition at line 44 of file StringExtras.h.
Referenced by getLastStructuredControlFlowOpMergeBlock().
convertToSnakeCase()
std::string mlir::convertToSnakeCase (llvm::StringRef input) inline
Converts a string to snake-case from camel-case by replacing all uppercase letters with '_' followed by the letter in lowercase, except if the uppercase letter is the first character of the string.
Definition at line 24 of file StringExtras.h.
Referenced by mlir::spirv::SPIRVDialect::getAttributeName(), isFnEntryBlock(), parseVariableDecorations(), printVariableDecorations(), and verify().
createAffineComputationSlice()
void mlir::createAffineComputationSlice (Operation * opInst, SmallVectorImpl< AffineApplyOp > * sliceOps)
Given an operation, inserts one or more single result affine apply operations, results of which are exclusively used by this operation.
Given an operation, inserts one or more single result affine apply operations, results of which are exclusively used by this operation operation.
The operands of these newly created affine apply ops are guaranteed to be loop iterators or terminal symbols of a function.
Before
affine.for i = 0 to #map(N) idx = affine.apply (d0) -> (d0 mod 2) (i) send A[idx], ... v = "compute"(idx, ...)
After
affine.for i = 0 to #map(N) idx = affine.apply (d0) -> (d0 mod 2) (i) send A[idx], ... idx_ = affine.apply (d0) -> (d0 mod 2) (i) v = "compute"(idx_, ...) This allows the application of different transformations on send and compute (for eg. different shifts/delays)
Fills sliceOps with the list of affine.apply operations. In the following cases, sliceOps remains empty:
If none of opInst's operands were the result of an affine.apply (i.e., there was no affine computation slice to create).
If all the affine.apply op's supplying operands to this opInst did not have any uses other than those in this opInst.
The operands of these newly created affine apply ops are guaranteed to be loop iterators or terminal symbols of a function.
Before
affine.for i = 0 to #map(N) idx = affine.apply (d0) -> (d0 mod 2) (i) "send"(idx, A, ...) "compute"(idx)
After
affine.for i = 0 to #map(N) idx = affine.apply (d0) -> (d0 mod 2) (i) "send"(idx, A, ...) idx_ = affine.apply (d0) -> (d0 mod 2) (i) "compute"(idx_)
This allows applying different transformations on send and compute (for eg. different shifts/delays).
Returns nullptr either if none of opInst's operands were the result of an affine.apply and thus there was no affine computation slice to create, or if all the affine.apply op's supplying operands to this opInst did not have any uses besides this opInst; otherwise returns the list of affine.apply operations created in output argument sliceOps.
Definition at line 322 of file Utils.cpp.
References mlir::OpBuilder::create(), fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::Operation::getLoc(), mlir::Builder::getMultiDimIdentityMap(), mlir::Operation::getNumOperands(), mlir::Operation::getOperands(), getReachableAffineApplyOps(), and mlir::Operation::setOperand().
Referenced by findMatchingStartFinishInsts().
createAffineDataCopyGenerationPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createAffineDataCopyGenerationPass (unsigned slowMemorySpace, unsigned fastMemorySpace, unsigned tagMemorySpace = 0, int minDmaTransferSize = 1024, uint64_t fastMemCapacityBytes = std::numeric_limits<uint64_t>::max())
Performs packing (or explicit copying) of accessed memref regions into buffers in the specified faster memory space through either pointwise copies or DMA operations.
Generates copies for memref's living in 'slowMemorySpace' into newly created buffers in 'fastMemorySpace', and replaces memory operations to the former by the latter.
Only load op's handled for now. TODO(bondhugula): extend this to store op's.
Definition at line 133 of file AffineDataCopyGeneration.cpp.
References affineDataCopyGenerate(), mlir::Block::begin(), mlir::OpBuilder::create(), mlir::Block::empty(), mlir::Block::end(), mlir::OpState::getLoc(), getMemoryFootprintBytes(), pass, promoteIfSingleIteration(), and success().
createAffineLoopInvariantCodeMotionPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createAffineLoopInvariantCodeMotionPass ()
Creates a loop invariant code motion pass that hoists loop invariant instructions out of affine loop.
Definition at line 233 of file AffineLoopInvariantCodeMotion.cpp.
References pass.
createCanonicalizerPass()
std::unique_ptr< Pass > mlir::createCanonicalizerPass ()
Creates an instance of the Canonicalizer pass.
Create a Canonicalizer pass.
Definition at line 40 of file Canonicalizer.cpp.
References pass.
createComposedAffineApplyOp()
Operation* mlir::createComposedAffineApplyOp (OpBuilder & builder, Location loc, ArrayRef< Value > operands, ArrayRef< Operation *> affineApplyOps, SmallVectorImpl< Value > * results)
Creates and inserts into 'builder' a new AffineApplyOp, with the number of its results equal to the number of operands, as a composition of all other AffineApplyOps reachable from input parameter 'operands'.
If different operands were drawing results from multiple affine apply ops, these will also be collected into a single (multi-result) affine apply op. The final results of the composed AffineApplyOp are returned in output parameter 'results'. Returns the affine apply op created.
createConvertGPUKernelToCubinPass()
std::unique_ptr< OpPassBase< gpu::GPUModuleOp > > mlir::createConvertGPUKernelToCubinPass (CubinGenerator cubinGenerator)
Creates a pass to convert kernel functions into CUBIN blobs.
This transformation takes the body of each function that is annotated with the 'nvvm.kernel' attribute, copies it to a new LLVM module, compiles the module with help of the nvptx backend to PTX and then invokes the provided cubinGenerator to produce a binary blob (the cubin). Such blob is then attached as a string attribute named 'nvvm.cubin' to the kernel function. After the transformation, the body of the kernel function is removed (i.e., it is turned into a declaration).
Definition at line 158 of file ConvertKernelFuncToCubin.cpp.
References pass.
createConvertGpuLaunchFuncToCudaCallsPass()
std::unique_ptr< mlir::OpPassBase< mlir::ModuleOp > > mlir::createConvertGpuLaunchFuncToCudaCallsPass ()
Creates a pass to convert a gpu.launch_func operation into a sequence of CUDA calls.
This pass does not generate code to call CUDA directly but instead uses a small wrapper library that exports a stable and conveniently typed ABI on top of CUDA.
Definition at line 417 of file ConvertLaunchFuncToCudaCalls.cpp.
References pass.
createConvertGPUToSPIRVPass()
std::unique_ptr< OpPassBase< ModuleOp > > mlir::createConvertGPUToSPIRVPass (ArrayRef< int64_t > workGroupSize)
Pass to convert GPU Ops to SPIR-V ops.
Needs the workgroup size as input since SPIR-V/Vulkan requires the workgroup size to be statically specified.
Definition at line 88 of file ConvertGPUToSPIRVPass.cpp.
References pass.
createConvertLinalgToAffineLoopsPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createConvertLinalgToAffineLoopsPass ()
Create a pass to convert Linalg operations to affine.for loops and affine_load/affine_store accesses.
Placeholder for now, this is NYI.
Definition at line 572 of file LinalgToLoops.cpp.
createConvertLinalgToLLVMPass()
std::unique_ptr< OpPassBase< ModuleOp > > mlir::createConvertLinalgToLLVMPass ()
Create a pass to convert Linalg operations to the LLVMIR dialect.
Definition at line 594 of file LinalgToLLVM.cpp.
References pass.
createConvertLinalgToLoopsPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createConvertLinalgToLoopsPass ()
Create a pass to convert Linalg operations to loop.for loops and std.load/std.store accesses.
Definition at line 563 of file LinalgToLoops.cpp.
createConvertStandardToSPIRVPass()
std::unique_ptr< OpPassBase< ModuleOp > > mlir::createConvertStandardToSPIRVPass ()
Pass to convert StandardOps to SPIR-V ops.
Definition at line 49 of file ConvertStandardToSPIRVPass.cpp.
References pass.
createCSEPass()
std::unique_ptr< Pass > mlir::createCSEPass ()
Creates a pass to perform common sub expression elimination.
Definition at line 261 of file CSE.cpp.
References pass.
createGpuKernelOutliningPass()
std::unique_ptr< OpPassBase< ModuleOp > > mlir::createGpuKernelOutliningPass ()
Definition at line 217 of file KernelOutlining.cpp.
References pass.
createInlinerPass()
std::unique_ptr< Pass > mlir::createInlinerPass ()
Creates a pass which inlines calls and callable operations as defined by the CallGraph.
Definition at line 308 of file Inliner.cpp.
References pass.
createLegalizeStdOpsForSPIRVLoweringPass()
std::unique_ptr< Pass > mlir::createLegalizeStdOpsForSPIRVLoweringPass ()
Pass to legalize ops that are not directly lowered to SPIR-V.
Definition at line 175 of file LegalizeStandardForSPIRV.cpp.
References pass.
createLinalgFusionPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLinalgFusionPass ()
Definition at line 361 of file Fusion.cpp.
References pass.
createLinalgPromotionPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLinalgPromotionPass (bool dynamicBuffers)
Definition at line 243 of file Promotion.cpp.
References clPromoteDynamic(), and pass.
createLinalgTilingPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLinalgTilingPass (ArrayRef< int64_t > tileSizes = {})
Definition at line 458 of file Tiling.cpp.
References clTileSizes(), and pass.
createLoopCoalescingPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLoopCoalescingPass ()
Creates a pass that transforms perfectly nested loops with independent bounds into a single loop.
Definition at line 90 of file LoopCoalescing.cpp.
References PASS_NAME, and reg.
createLoopFusionPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLoopFusionPass (unsigned fastMemorySpace = 0, uint64_t localBufSizeThreshold = 0, bool maximalFusion = false)
Creates a loop fusion pass which fuses loops.
Buffers of size less than or equal to localBufSizeThreshold are promoted to memory space `fastMemorySpace'.
Definition at line 106 of file LoopFusion.cpp.
createLoopInvariantCodeMotionPass()
std::unique_ptr< Pass > mlir::createLoopInvariantCodeMotionPass ()
Creates a loop invariant code motion pass that hoists loop invariant instructions out of the loop.
Definition at line 134 of file LoopInvariantCodeMotion.cpp.
References pass.
createLoopTilingPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLoopTilingPass (uint64_t cacheSizeBytes)
Creates a pass to perform tiling on loop nests.
Creates a pass to perform loop tiling on all suitable loop nests of a Function.
Definition at line 76 of file LoopTiling.cpp.
createLoopToGPUPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLoopToGPUPass (ArrayRef< int64_t > numWorkGroups, ArrayRef< int64_t > workGroupSize)
Create a pass that converts every loop operation within the body of the FuncOp into a GPU launch.
The number of workgroups and workgroup size for the implementation is controlled by SSA values passed into conversion method. For testing, the values are set as constants obtained from a command line flag. See convertLoopToGPULaunch for a description of the required semantics of the converted loop operation.
Definition at line 127 of file LoopsToGPUPass.cpp.
References clNumBlockDims(), clNumThreadDims(), clNumWorkGroups(), clWorkGroupSize(), LOOPOP_TO_GPU_PASS_NAME, loopOpToGPU, PASS_NAME, and registration.
createLoopUnrollAndJamPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLoopUnrollAndJamPass (int unrollJamFactor = -1)
Creates a loop unroll jam pass to unroll jam by the specified factor.
A factor of -1 lets the pass use the default factor or the one on the command line if provided.
Definition at line 77 of file LoopUnrollAndJam.cpp.
References clUnrollJamFactor(), loopUnrollJamByFactor(), and mlir::StandardTypes::None.
createLoopUnrollPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLoopUnrollPass (int unrollFactor = -1, int unrollFull = -1, const std::function< unsigned(AffineForOp)> & getUnrollFactor = nullptr)
Creates a loop unrolling pass with the provided parameters.
'getUnrollFactor' is a function callback for clients to supply a function that computes an unroll factor - the callback takes precedence over unroll factors supplied through other means. If -1 is passed as the unrollFactor and no callback is provided, anything passed from the command-line (if at all) or the default unroll factor is used (LoopUnroll:kDefaultUnrollFactor).
Definition at line 174 of file LoopUnroll.cpp.
References mlir::StandardTypes::None, and pass.
createLowerAffinePass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createLowerAffinePass ()
Lowers affine control flow operations (ForStmt, IfStmt and AffineApplyOp) to equivalent lower-level constructs (flow of basic blocks and arithmetic primitives).
Lowers If and For operations within a function into their lower level CFG equivalent blocks.
Definition at line 574 of file AffineToStandard.cpp.
References pass.
createLowerGpuOpsToNVVMOpsPass()
std::unique_ptr< OpPassBase< gpu::GPUModuleOp > > mlir::createLowerGpuOpsToNVVMOpsPass ()
Creates a pass that lowers GPU dialect operations to NVVM counterparts.
Definition at line 752 of file LowerGpuOpsToNVVMOps.cpp.
References pass.
createLowerGpuOpsToROCDLOpsPass()
std::unique_ptr< OpPassBase< gpu::GPUModuleOp > > mlir::createLowerGpuOpsToROCDLOpsPass ()
Creates a pass that lowers GPU dialect operations to ROCDL counterparts.
Definition at line 76 of file LowerGpuOpsToROCDLOps.cpp.
References pass.
createLowerToCFGPass()
std::unique_ptr< Pass > mlir::createLowerToCFGPass ()
Creates a pass to convert loop.for, loop.if and loop.terminator ops to CFG.
Definition at line 263 of file ConvertLoopToStandard.cpp.
References pass.
createLowerToLLVMPass() [1/3]
std::unique_ptr< OpPassBase< ModuleOp > > mlir::createLowerToLLVMPass (bool useAlloca = false)
Creates a pass to convert the Standard dialect into the LLVMIR dialect.
By default stdlib malloc/free are used for allocating MemRef payloads. Specifying useAlloca-true emits stack allocations instead. In the future this may become an enum when we have concrete uses for other options.
Definition at line 2259 of file ConvertStandardToLLVM.cpp.
createLowerToLLVMPass() [2/3]
std::unique_ptr< OpPassBase< ModuleOp > > mlir::createLowerToLLVMPass (LLVMPatternListFiller patternListFiller, LLVMTypeConverterMaker typeConverterMaker, bool useAlloca = false)
Creates a pass to convert operations to the LLVMIR dialect.
The conversion is defined by a list of patterns and a type converter that will be obtained during the pass using the provided callbacks. By default stdlib malloc/free are used for allocating MemRef payloads. Specifying useAlloca-true emits stack allocations instead. In the future this may become an enum when we have concrete uses for other options.
Definition at line 2264 of file ConvertStandardToLLVM.cpp.
References clUseAlloca(), makeStandardToLLVMTypeConverter(), pass, and populateStdToLLVMConversionPatterns().
createLowerToLLVMPass() [3/3]
template<typename TypeConverter = LLVMTypeConverter> std::unique_ptr<OpPassBase<ModuleOp> > mlir::createLowerToLLVMPass (LLVMPatternListFiller patternListFiller, bool useAlloca = false)
Creates a pass to convert operations to the LLVMIR dialect.
The conversion is defined by a list of patterns obtained during the pass using the provided callback and an optional type conversion class, an instance is created during the pass. By default stdlib malloc/free are used for allocating MemRef payloads. Specifying useAlloca-true emits stack allocations instead. In the future this may become an enum when we have concrete uses for other options.
Definition at line 88 of file ConvertStandardToLLVMPass.h.
References ensureDistinctSuccessors().
createLowerVectorToLLVMPass()
OpPassBase< ModuleOp > * mlir::createLowerVectorToLLVMPass ()
Create a pass to convert vector operations to the LLVMIR dialect.
Definition at line 999 of file ConvertVectorToLLVM.cpp.
References pass.
createLowerVectorToLoopsPass()
OpPassBase<ModuleOp>* mlir::createLowerVectorToLoopsPass ()
Create a pass to convert vector operations to affine loops + std dialect.
createMaterializeVectorsPass()
std::unique_ptr<OpPassBase<FuncOp> > mlir::createMaterializeVectorsPass (ArrayRef< int64_t > vectorSize)
Creates a pass to lower super-vectors to target-dependent HW vectors.
createMemRefBoundCheckPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createMemRefBoundCheckPass ()
Creates a pass to check memref accesses in a Function.
Definition at line 38 of file MemRefBoundCheck.cpp.
References boundCheckLoadOrStoreOp(), and memRefBoundCheck.
createMemRefDataFlowOptPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createMemRefDataFlowOptPass ()
Creates a pass to perform optimizations relying on memref dataflow such as store to load forwarding, elimination of dead stores, and dead allocs.
Definition at line 82 of file MemRefDataFlowOpt.cpp.
References checkMemrefAccessDependence(), mlir::Operation::erase(), mlir::OpState::erase(), mlir::AffineLoadOp::getMemRef(), getNestingDepth(), getNumCommonSurroundingLoops(), mlir::Op< ConcreteType, Traits >::getOperation(), mlir::Value::getUsers(), hasDependence(), pass, mlir::OpTrait::OneResult< ConcreteType >::replaceAllUsesWith(), and mlir::OpState::walk().
createParallelismDetectionTestPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createParallelismDetectionTestPass ()
Creates a pass to test parallelism detection; emits note for parallel loops.
Definition at line 30 of file TestParallelismDetection.cpp.
References isLoopParallel(), pass, and mlir::OpState::walk().
createPipelineDataTransferPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createPipelineDataTransferPass ()
Creates a pass to pipeline explicit movement of data across levels of the memory hierarchy.
Definition at line 43 of file PipelineDataTransfer.cpp.
createPrintCFGGraphPass()
std::unique_ptr< mlir::OpPassBase< mlir::FuncOp > > mlir::createPrintCFGGraphPass (raw_ostream & os = llvm::errs(), bool shortNames = false, const Twine & title = "")
Creates a pass to print CFG graphs.
Definition at line 79 of file ViewRegionGraph.cpp.
References pass.
createPrintOpGraphPass()
std::unique_ptr< OpPassBase< ModuleOp > > mlir::createPrintOpGraphPass (raw_ostream & os = llvm::errs(), bool shortNames = false, const Twine & title = "")
Creates a pass to print op graphs.
Definition at line 160 of file ViewOpGraph.cpp.
References pass.
createSimpleLoopsToGPUPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createSimpleLoopsToGPUPass (unsigned numBlockDims, unsigned numThreadDims)
Create a pass that converts loop nests into GPU kernels.
It considers top-level affine.for and linalg.for operations as roots of loop nests and converts them to the gpu.launch operations if possible.
No check on the size of the block or grid, or on the validity of parallelization is performed, it is under the responsibility of the caller to strip-mine the loops and to perform the dependence analysis before calling the conversion.
Definition at line 121 of file LoopsToGPUPass.cpp.
createSimpleParametricTilingPass()
std::unique_ptr<OpPassBase<FuncOp> > mlir::createSimpleParametricTilingPass (ArrayRef< int64_t > outerLoopSizes)
Creates a pass that performs parametric tiling so that the outermost loops have the given fixed number of iterations.
Assumes outermost loop nests are permutable.
createSimplifyAffineStructuresPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createSimplifyAffineStructuresPass ()
Creates a simplification pass for affine structures (maps and sets).
In addition, this pass also normalizes memrefs to have the trivial (identity) layout map.
Definition at line 80 of file SimplifyAffineStructures.cpp.
References mlir::Operation::getAttrs(), normalizeMemRef(), and pass.
createStripDebugInfoPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createStripDebugInfoPass ()
Creates a pass to strip debug information from a function.
Definition at line 32 of file StripDebugInfo.cpp.
References pass.
createTestLoopFusionPass()
std::unique_ptr<OpPassBase<FuncOp> > mlir::createTestLoopFusionPass ()
Creates a pass which tests loop fusion utilities.
createTestMemRefDependenceCheckPass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createTestMemRefDependenceCheckPass ()
Creates a pass to check memref access dependences in a Function.
Definition at line 40 of file TestMemRefDependenceCheck.cpp.
createVectorizePass()
std::unique_ptr< OpPassBase< FuncOp > > mlir::createVectorizePass (ArrayRef< int64_t > virtualVectorSize)
Creates a pass to vectorize loops, operations and data types using a target-independent, n-D super-vector abstraction.
Definition at line 1285 of file Vectorize.cpp.
References pass.
createVectorizerTestPass()
std::unique_ptr<OpPassBase<FuncOp> > mlir::createVectorizerTestPass ()
Creates a pass to allow independent testing of vectorizer functionality with FileCheck.
debugString()
template<typename T > static std::string mlir::debugString (T & op) static
Definition at line 27 of file DebugStringHelper.h.
defaultFilterFunction()
bool mlir::defaultFilterFunction (Operation &) inline
Definition at line 91 of file NestedMatcher.h.
emitError() [1/2]
InFlightDiagnostic mlir::emitError (Location loc)
Utility method to emit an error message using this location.
Emit an error message using this location.
Definition at line 301 of file Diagnostics.cpp.
Referenced by boundCheckLoadOrStoreOp(), buildHexadecimalFloatLiteral(), buildSequentialConstant(), computeConversionSet(), convertLinkageType(), mlir::LLVM::ModuleTranslation::convertOperation(), deserializeModule(), diag(), mlir::Operation::emitError(), mlir::OpState::erase(), extractSymbolReference(), mlir::quant::fakeQuantAttrsToType(), mlir::MemRefType::getChecked(), getElementPtrType(), getElementType(), mlir::Lexer::getEncodedSourceLocation(), getICmpPredicate(), getInnermostElementType(), getLastStructuredControlFlowOpMergeBlock(), mlir::LLVMTypeConverter::getLLVMContext(), getOrInsertBuiltinVariable(), isFnEntryBlock(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::DialectAsmParser::parseInteger(), mlir::DialectAsmParser::parseKeyword(), mlir::OpAsmParser::parseKeyword(), mlir::DialectAsmParser::parseOptionalInteger(), parseSourceFile(), parseSymbol(), mlir::OpAsmParser::parseSymbolName(), mlir::DialectAsmParser::parseType(), processLinkage(), mlir::OpAsmParser::resolveOperands(), runWithCrashRecovery(), solveUniformType(), translateLLVMIRToModule(), validateTypeConversion(), and verifyRegionAttribute().
emitError() [2/2]
InFlightDiagnostic mlir::emitError (Location loc, const Twine & message)
Definition at line 302 of file Diagnostics.cpp.
References emitDiag(), and Error.
Referenced by emitOptionalError().
emitOptionalError()
template<typename... Args> LogicalResult mlir::emitOptionalError (Optional< Location > loc, Args &&... args)
Overloads of the above emission functions that take an optionally null location.
If the location is null, no diagnostic is emitted and a failure is returned. Given that the provided location may be null, these methods take the diagnostic arguments directly instead of relying on the returned InFlightDiagnostic.
Definition at line 481 of file Diagnostics.h.
References mlir::InFlightDiagnostic::append(), emitError(), and failure().
Referenced by checkTensorElementType(), mlir::MemRefType::getChecked(), mlir::quant::QuantizedType::verifyConstructionInvariants(), mlir::IntegerType::verifyConstructionInvariants(), mlir::ComplexType::verifyConstructionInvariants(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::OpaqueType::verifyConstructionInvariants(), mlir::VectorType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::RankedTensorType::verifyConstructionInvariants(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), mlir::OpaqueAttr::verifyConstructionInvariants(), mlir::UnrankedMemRefType::verifyConstructionInvariants(), and verifyFloatTypeInvariants().
emitOptionalRemark()
template<typename... Args> LogicalResult mlir::emitOptionalRemark (Optional< Location > loc, Args &&... args)
Definition at line 493 of file Diagnostics.h.
References mlir::InFlightDiagnostic::append(), emitRemark(), and failure().
emitOptionalWarning()
template<typename... Args> LogicalResult mlir::emitOptionalWarning (Optional< Location > loc, Args &&... args)
Definition at line 487 of file Diagnostics.h.
References mlir::InFlightDiagnostic::append(), emitWarning(), and failure().
emitRemark() [1/2]
InFlightDiagnostic mlir::emitRemark (Location loc)
Utility method to emit a remark message using this location.
Emit a remark message using this location.
Definition at line 315 of file Diagnostics.cpp.
Referenced by mlir::Operation::emitRemark(), mlir::OpState::erase(), and solveUniformType().
emitRemark() [2/2]
InFlightDiagnostic mlir::emitRemark (Location loc, const Twine & message)
Definition at line 318 of file Diagnostics.cpp.
References emitDiag(), and Remark.
Referenced by emitOptionalRemark().
emitWarning() [1/2]
InFlightDiagnostic mlir::emitWarning (Location loc)
Utility method to emit a warning message using this location.
Emit a warning message using this location.
Definition at line 307 of file Diagnostics.cpp.
Referenced by emitUniformPerLayerDequantize(), mlir::Operation::emitWarning(), mlir::OpState::erase(), and solveUniformType().
emitWarning() [2/2]
InFlightDiagnostic mlir::emitWarning (Location loc, const Twine & message)
Definition at line 310 of file Diagnostics.cpp.
References emitDiag(), and Warning.
Referenced by emitOptionalWarning().
expandAffineExpr()
mlir::Value mlir::expandAffineExpr (OpBuilder & builder, Location loc, AffineExpr expr, ArrayRef< Value > dimValues, ArrayRef< Value > symbolValues)
Emit code that computes the given affine expression using standard arithmetic operations applied to the provided dimension and symbol values.
Definition at line 211 of file AffineToStandard.cpp.
Referenced by expandAffineMap(), and lowerAffineUpperBound().
extractFixedOuterLoops()
TileLoops mlir::extractFixedOuterLoops (loop::ForOp rootFOrOp, ArrayRef< int64_t > sizes)
Tile a nest of standard for loops rooted at rootForOp by finding such parametric tile sizes that the outer loops have a fixed number of iterations as defined in sizes.
Definition at line 923 of file LoopUtils.cpp.
References ceilDivPositive(), mlir::OpBuilder::create(), getPerfectlyNestedLoopsImpl(), tile(), and tryIsolateBands().
extractForInductionVars()
void mlir::extractForInductionVars (ArrayRef< AffineForOp > forInsts, SmallVectorImpl< Value > * ivs)
Extracts the induction variables from a list of AffineForOps and places them in the output argument ivs.
Extracts the induction variables from a list of AffineForOps and returns them.
Definition at line 1582 of file AffineOps.cpp.
Referenced by mlir::MemRefRegion::compute(), getFullMemRefAsRegion(), getIndexSet(), and tileCodeGen().
failed()
bool mlir::failed (LogicalResult result) inline
Utility function that returns true if the provided LogicalResult corresponds to a failure value.
Definition at line 45 of file LogicalResult.h.
References mlir::LogicalResult::Failure, and mlir::LogicalResult::value.
Referenced by mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addInductionVarOrTerminalSymbol(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), addMemRefAccessConstraints(), addMissingLoopIVBounds(), mlir::FlatAffineConstraints::addSliceBounds(), mlir::PassPipelineCLParser::addToPipeline(), adjustToDivisorsOfTripCounts(), affineDataCopyGenerate(), analyzeProfitability(), boundCheckLoadOrStoreOp(), canFuseLoops(), canFuseSrcWhichWritesToLiveOut(), checkLoopOpMappable(), checkMemrefAccessDependence(), compileAndExecuteSingleFloatReturnFunction(), mlir::FlatAffineConstraints::composeMap(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::MemRefRegion::compute(), computeSliceUnion(), mlir::FlatAffineConstraints::constantFoldIdRange(), mlir::TypeConverter::convertBlockSignature(), convertLinalgType(), convertLinkageType(), convertLoopNestToGPULaunch(), convertLoopToGPULaunch(), mlir::LLVM::ModuleTranslation::convertOperation(), mlir::TypeConverter::convertSignatureArg(), mlir::TypeConverter::convertTypes(), mlir::OperationFolder::create(), mlir::PassPipelineOptions< EmptyPipelineOptions >::createFromString(), createLaunchFromOp(), mlir::spirv::deserialize(), doubleBuffer(), emitLoopRanges(), extractSymbolReference(), findMatchingStartFinishInsts(), mlir::FlatAffineConstraints::FlatAffineConstraints(), mlir::AffineApplyOp::fold(), mlir::Operation::fold(), foldLoopBounds(), mlir::ComputationSliceState::getAsConstraints(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::getChecked(), getElementPtr(), getElementPtrType(), mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >::getFromOpaquePointer(), getI64SubArray(), getICmpPredicate(), getIndexSet(), getLastStructuredControlFlowOpMergeBlock(), getMemoryFootprintBytes(), getStridesAndOffset(), getTypeNumBytes(), mlir::detail::inferReturnTensorTypes(), inlineCall(), inlineCallsInSCC(), isFnEntryBlock(), isFusionProfitable(), lowerEntryPointABIAttr(), makeStandardToLLVMTypeConverter(), mlir::ConversionPattern::matchAndRewrite(), normalizeMemRef(), mlir::OperationFolder::notifyRemoval(), mlir::ParseResult::operator bool(), operator<<(), parseAndVerify< uint64_t >(), parseArgumentList(), parseAttributions(), parseBound(), parseFunctionResultList(), parseGlobalOp(), parseGPUFuncOp(), parseLLVMFuncOp(), mlir::DialectAsmParser::parseOptionalInteger(), parsePassPipeline(), parseQuantParams(), parseSourceFile(), parseStorageRange(), parseStorageType(), parseStructMemberDecorations(), parseSymbol(), mlir::OpAsmParser::parseSymbolName(), mlir::quant::QuantizationDialect::parseType(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), performActions(), populateAffineToStdConversionPatterns(), populateLinalgToLLVMConversionPatterns(), populateLoopToStdConversionPatterns(), populateSPIRVLayoutInfoPatterns(), populateVectorToLLVMConversionPatterns(), mlir::detail::PassOptions::print(), mlir::Pass::printAsTextualPipeline(), printMLIROutput(), processLinkage(), replaceAllMemRefUsesWith(), resolveSourceIndices(), roundTripModule(), mlir::OpPassManager::run(), mlir::detail::OpToOpPassAdaptor::runOnOperation(), mlir::detail::OpToOpPassAdaptorParallel::runOnOperation(), serializeModule(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), splitAndProcessBuffer(), topologicalSort(), translateLLVMIRToModule(), mlir::LLVM::ModuleTranslation::translateModule(), mlir::OpBuilder::tryFold(), mlir::OperationFolder::tryToFold(), validateTypeConversion(), vectorizeAffineForOp(), vectorizeLoopsAndLoadsRecursively(), vectorizeRootMatch(), verify(), verifyAttributions(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), verifyFuncArgsGeneric(), verifyGenericOp(), mlir::detail::verifyInferredResultTypes(), mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >::verifyInvariants(), mlir::OpTrait::impl::verifyIsTerminator(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), verifyTerminatorSuccessors(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait(), and visitInPrettyBlockOrder().
failure()
LogicalResult mlir::failure (bool isFailure = true) inline
Utility function to generate a LogicalResult.
If isFailure is true a failure result is generated, otherwise a 'success' result is generated.
Definition at line 32 of file LogicalResult.h.
References mlir::LogicalResult::Failure, and mlir::LogicalResult::Success.
Referenced by mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), addMemRefAccessConstraints(), addMissingLoopIVBounds(), mlir::FlatAffineConstraints::addSliceBounds(), mlir::PassPipelineCLParser::addToPipeline(), analyzeProfitability(), boundCheckLoadOrStoreOp(), buildHexadecimalFloatLiteral(), canonicalizeLoopBounds(), checkLoopOpMappable(), collectValidReferencesFor(), mlir::FlatAffineConstraints::composeMap(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::MemRefRegion::compute(), computeSliceUnion(), mlir::AffineMap::constantFold(), mlir::FlatAffineConstraints::constantFoldId(), convertLoopNestToGPULaunch(), convertLoopToGPULaunch(), mlir::LLVM::ModuleTranslation::convertOperation(), mlir::TypeConverter::convertSignatureArg(), mlir::TypeConverter::convertType(), mlir::TypeConverter::convertTypes(), createLaunchFromOp(), emitOptionalError(), emitOptionalRemark(), emitOptionalWarning(), extractStrides(), extractSymbolReference(), extractValueFromConstOp(), mlir::FoldingHook< AffineDmaWaitOp, llvm::is_one_of< OpTrait::OneResult< AffineDmaWaitOp >, OpTrait::VariadicOperands< AffineDmaWaitOp >... >::value >::fold(), mlir::Operation::fold(), mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::foldHook(), foldLoopBounds(), generateCopy(), mlir::ComputationSliceState::getAsConstraints(), getFlattenedAffineExprs(), mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >::getFromOpaquePointer(), getICmpPredicate(), getIndexSet(), getInterfaceVariables(), getLastStructuredControlFlowOpMergeBlock(), getStridesAndOffset(), hoistOpsBetween(), mlir::detail::inferReturnTensorTypes(), inlineCall(), inlineCallsInSCC(), inlineRegion(), isFnEntryBlock(), loopUnrollByFactor(), loopUnrollFull(), loopUnrollJamByFactor(), lowerEntryPointABIAttr(), mlir::ConversionPattern::matchAndRewrite(), normalizeMemRef(), mlir::OperationFolder::notifyRemoval(), mlir::Diagnostic::operator LogicalResult(), mlir::InFlightDiagnostic::operator LogicalResult(), operator<<(), mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl(), mlir::ModuleOp::parse(), mlir::AffineApplyOp::parse(), mlir::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), mlir::AffineLoadOp::parse(), mlir::AffineStoreOp::parse(), parseAccessChainOp(), parseAddressOfOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineMinOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAllocOp(), parseArgumentList(), parseAtomicBinOp(), parseAtomicCmpXchgOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicOrdering(), parseAtomicRMWOp(), parseAtomicUpdateOp(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), parseAttributions(), parseBitFieldExtractOp(), parseBitFieldInsertOp(), parseBound(), parseBranchConditionalOp(), parseBranchOp(), parseBroadcastOp(), parseBrOp(), parseCallIndirectOp(), parseCallOp(), mlir::impl::parseCastOp(), parseCmpFOp(), parseCmpIOp(), parseCmpOp(), mlir::OpAsmParser::parseColonType(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseCondBranchOp(), parseCondBrOp(), parseConstantMaskOp(), parseConstantOp(), parseContractionOp(), parseControlBarrierOp(), parseCreateMaskOp(), parseDeallocOp(), parseDimAndSymbolList(), parseDimOp(), parseEntryPointOp(), parseEnumAttribute(), parseExecutionModeOp(), parseExtractElementOp(), parseExtractOp(), parseExtractSlicesOp(), parseExtractValueOp(), parseForOp(), mlir::detail::PassOptions::parseFromString(), parseFunctionCallOp(), mlir::impl::parseFunctionLikeOp(), parseFunctionResultList(), mlir::impl::parseFunctionSignature(), parseGenericOp(), parseGEPOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseGroupNonUniformBallotOp(), parseGroupNonUniformElectOp(), parseGroupNonUniformIAddOp(), parseIfOp(), parseInsertElementOp(), parseInsertOp(), parseInsertSlicesOp(), parseInsertStridedSliceOp(), parseInsertValueOp(), mlir::OpAsmParser::parseKeywordType(), parseLaunchOp(), parseLinalgStructuredOp(), parseLLVMFuncOp(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseMemoryAccessAttributes(), parseMemoryBarrierOp(), parseModuleOp(), parseNoIOOp(), parseNullOp(), parseNVVMMmaOp(), parseNVVMShflSyncBflyOp(), parseNVVMSpecialRegisterOp(), parseNVVMVoteBallotOp(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOptionalLinkageKeyword(), parseOuterProductOp(), parseParallelOp(), parsePassPipeline(), parsePrefetchOp(), parsePrintOp(), parseQuantParams(), parseRangeOp(), parseRankOp(), parseReduceOp(), parseReduceReturnOp(), parseReferenceOfOp(), parseReshapeOp(), parseReturnOp(), parseReturnValueOp(), parseROCDLOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSizeAssignment(), parseSliceOp(), parseSpecConstantOp(), parseSplatOp(), parseStorageRange(), parseStoreOp(), parseStridedSliceOp(), parseStructMemberDecorations(), parseSubgroupBallotKHROp(), parseSubViewOp(), parseSymbol(), parseTensorLoadOp(), parseTensorStoreOp(), parseTransferReadOp(), parseTransferWriteOp(), parseTransposeOp(), parseTupleGetOp(), parseTupleOp(), mlir::DialectAsmParser::parseType(), parseUnaryOp(), parseUndefOp(), parseVariableDecorations(), parseVariableOp(), parseViewOp(), parseYieldOp(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration(), performActions(), mlir::linalg::permuteGenericLinalgOpPrecondition(), mlir::detail::PassOptions::print(), print(), mlir::Pass::printAsTextualPipeline(), printMLIROutput(), promoteIfSingleIteration(), mlir::linalg::promoteSubviewsLinalgOpPrecondition(), replaceAllMemRefUsesWith(), replaceAllSymbolUsesImpl(), mlir::OpAsmParser::resolveOperands(), resolveSourceIndices(), roundTripModule(), mlir::OpPassManager::run(), runWithCrashRecovery(), serializeModule(), splitAndProcessBuffer(), mlir::linalg::tileAndFuseLinalgOpAndSetMarker(), tileCodeGen(), mlir::linalg::tileLinalgOpAndSetMarker(), topologicalSort(), translateModuleToLLVMIR(), translateModuleToNVVMIR(), translateModuleToROCDLIR(), mlir::TranslationParser::TranslationParser(), mlir::OpBuilder::tryFold(), tryIsolateBands(), tryRewriteAffineAddEwIsomorphicSigned(), tryRewriteAffineMulEwSigned(), mlir::OperationFolder::tryToFold(), mlir::FlatAffineConstraints::unionBoundingBox(), vectorizeAffineForOp(), mlir::linalg::vectorizeLinalgOpPrecondition(), vectorizeLoopsAndLoadsRecursively(), vectorizeNonTerminals(), vectorizeRootMatch(), mlir::SourceMgrDiagnosticVerifierHandler::verify(), verify(), verifyAttributions(), verifyCompatibleShape(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), verifyDynamicStrides(), verifyGenericOp(), mlir::detail::verifyInferredResultTypes(), mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >::verifyInvariants(), mlir::OpTrait::impl::verifyIsTerminator(), mlir::gpu::GPUDialect::verifyOperationAttribute(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), verifyTerminatorSuccessors(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait(), mlir::OpTrait::IsIsolatedFromAbove< ConcreteType >::verifyTrait(), and visitInPrettyBlockOrder().
floorDiv()
int64_t mlir::floorDiv (int64_t lhs, int64_t rhs) inline
Returns the result of MLIR's floordiv operation on constants.
The RHS is expected to be positive.
Definition at line 31 of file MathExtras.h.
Referenced by createPrivateMemRef(), generateCopy(), mlir::FlatAffineConstraints::getConstantBoundOnDimSize(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::FlatAffineConstraints::isEmptyByGCDTest(), and mlir::AffineExpr::operator!().
fullyComposeAffineMapAndOperands()
void mlir::fullyComposeAffineMapAndOperands (AffineMap * map, SmallVectorImpl< Value > * operands)
Given an affine map map and its input operands, this method composes into map, maps of AffineApplyOps whose results are the values in operands, iteratively until no more of operands are the result of an AffineApplyOp.
When this function returns, map becomes the composed affine map, and each Value in operands is guaranteed to be either a loop IV or a terminal symbol, i.e., a symbol defined at the top level or a block/function argument.
Definition at line 589 of file AffineOps.cpp.
References composeAffineMapAndOperands(), and mlir::Value::getDefiningOp().
Referenced by mlir::FlatAffineConstraints::addLowerOrUpperBound(), createAffineComputationSlice(), mlir::AffineValueMap::difference(), emitOrFoldComposedAffineApply(), generateCopy(), mlir::MemRefAccess::getAccessMap(), getCleanupLoopLowerBound(), mlir::AffineStoreOp::getOperationName(), and replaceAllMemRefUsesWith().
getAffineBinaryOpExpr()
AffineExpr mlir::getAffineBinaryOpExpr (AffineExprKind kind, AffineExpr lhs, AffineExpr rhs)
Definition at line 45 of file AffineExpr.cpp.
References Add, CeilDiv, mlir::AffineExpr::ceilDiv(), FloorDiv, mlir::AffineExpr::floorDiv(), Mod, and Mul.
Referenced by mlir::SDBMExpr::getAsAffineExpr(), operator-(), and mlir::AffineExpr::replaceDimsAndSymbols().
getAffineConstantExpr()
AffineExpr mlir::getAffineConstantExpr (int64_t constant, MLIRContext * context)
Definition at line 277 of file AffineExpr.cpp.
References Constant, mlir::StorageUniquer::get(), and mlir::MLIRContext::getAffineUniquer().
Referenced by canonicalizeMapOrSetAndOperands(), categorizeValueByAffineType(), mlir::AffineExpr::ceilDiv(), detectAsFloorDiv(), mlir::AffineExpr::floorDiv(), generateTransferOpSlices(), mlir::Builder::getAffineConstantExpr(), mlir::SDBMExpr::getAsAffineExpr(), mlir::AffineMap::getConstantMap(), mlir::IntegerSet::getEmptySet(), mlir::FlatAffineConstraints::getSliceBounds(), getStridesAndOffset(), makeCanonicalStridedLayoutExpr(), makePermutationMap(), makeStridedLinearLayoutMap(), mlir::AffineExpr::operator%(), mlir::AffineExpr::operator*(), mlir::AffineExpr::operator+(), mlir::AffineExpr::operator-(), operator-(), mlir::AffineExpr::operator==(), simplifyAdd(), simplifyCeilDiv(), simplifyFloorDiv(), simplifyMod(), simplifyMul(), toAffineExpr(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), and mlir::SimpleAffineExprFlattener::visitModExpr().
getAffineDimExpr()
AffineExpr mlir::getAffineDimExpr (unsigned position, MLIRContext * context)
These free functions allow clients of the API to not use classes in detail.
Definition at line 252 of file AffineExpr.cpp.
References DimId, and getAffineDimOrSymbol().
Referenced by mlir::detail::bindDims(), canonicalizeMapOrSetAndOperands(), canonicalizePromotedSymbols(), categorizeValueByAffineType(), mlir::AffineMap::compose(), mlir::AffineApplyOp::fold(), generateTransferOpSlices(), mlir::Builder::getAffineDimExpr(), mlir::SDBMExpr::getAsAffineExpr(), getDimMap(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::AffineMap::getPermutationMap(), mlir::FlatAffineConstraints::getSliceBounds(), inversePermutation(), mlir::AffineExpr::isFunctionOfDim(), isMatmul(), mlir::linalg::loopToOperandRangesMaps(), makeAffineDimExprs(), makeCanonicalStridedLayoutExpr(), makePermutationMap(), makeStridedLinearLayoutMap(), operator-(), promoteComposedSymbolsAsDims(), and toAffineExpr().
getAffineSymbolExpr()
AffineExpr mlir::getAffineSymbolExpr (unsigned position, MLIRContext * context)
Definition at line 262 of file AffineExpr.cpp.
References getAffineDimOrSymbol(), and SymbolId.
Referenced by canonicalizeMapOrSetAndOperands(), canonicalizePromotedSymbols(), categorizeValueByAffineType(), mlir::AffineMap::compose(), mlir::AffineApplyOp::fold(), mlir::Builder::getAffineSymbolExpr(), mlir::SDBMExpr::getAsAffineExpr(), mlir::FlatAffineConstraints::getSliceBounds(), makeCanonicalStridedLayoutExpr(), makeStridedLinearLayoutMap(), operator-(), promoteComposedSymbolsAsDims(), and toAffineExpr().
getAllIteratorTypeNames()
static ArrayRef<StringRef> mlir::getAllIteratorTypeNames () inline static
Use to encode that a particular iterator type has window semantics.
Definition at line 79 of file StructuredOpsUtils.h.
References getParallelIteratorTypeName(), getReductionIteratorTypeName(), and getWindowIteratorTypeName().
Referenced by getNumIterators().
getArgsInAttrName()
static constexpr StringLiteral mlir::getArgsInAttrName () static
Attribute name for the IntegerAttr which encodes the number of input buffer arguments.
Definition at line 39 of file StructuredOpsUtils.h.
getArgsOutAttrName()
static constexpr StringLiteral mlir::getArgsOutAttrName () static
Attribute name for the IntegerAttr which encodes the number of input buffer arguments.
Definition at line 45 of file StructuredOpsUtils.h.
getBackwardSlice()
void mlir::getBackwardSlice (Operation * op, llvm::SetVector< Operation *> * backwardSlice, TransitiveFilter filter = [](Operation *) { return true;})
Fills backwardSlice with the computed backward slice (i.e.
all the transitive defs of op), without including that operation.
This additionally takes a TransitiveFilter which acts as a frontier: when looking at defs transitively, a operation that does not pass the filter is never propagated through. This allows in particular to carve out the scope within a ForInst or the scope within an IfInst.
The implementation traverses the def chains in postorder traversal for efficiency reasons: if a operation is already in backwardSlice, no need to traverse its definitions again. Since useuse-def chains form a DAG, this terminates.
Upon return to the root call, backwardSlice is filled with a postorder list of defs. This happens to be a topological order, from the point of view of the use-def chains.
Example starting from node 8
1 2 3 4 |_______| |______| | | | | 5 6 |___|_____________| | | 7 8 |_______________| | 9
Assuming all local orders match the numbering order: {1, 2, 5, 3, 4, 6}
Referenced by getBackwardSliceImpl(), and getSlice().
getCleanupLoopLowerBound()
void mlir::getCleanupLoopLowerBound (AffineForOp forOp, unsigned unrollFactor, AffineMap * map, SmallVectorImpl< Value > * operands, OpBuilder & b)
Computes the cleanup loop lower bound of the loop being unrolled with the specified unroll factor; this bound will also be upper bound of the main part of the unrolled loop.
Computes the bound as an AffineMap with its operands or a null map when the trip count can't be expressed as an affine expression.
Definition at line 44 of file LoopUtils.cpp.
References mlir::StandardAttributes::AffineMap, buildTripCountMapAndOperands(), canonicalizeMapAndOperands(), mlir::OpBuilder::create(), fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), and simplifyAffineMap().
Referenced by loopUnrollByFactor(), and loopUnrollJamByFactor().
getComputationSliceState()
void mlir::getComputationSliceState (Operation * depSourceOp, Operation * depSinkOp, FlatAffineConstraints * dependenceConstraints, unsigned loopDepth, bool isBackwardSlice, ComputationSliceState * sliceState)
Computes the computation slice loop bounds for one loop nest as affine maps of the other loop nest's IVs and symbols, using 'dependenceConstraints' computed between 'depSourceAccess' and 'depSinkAccess'.
If 'isBackwardSlice' is true, a backwards slice is computed in which the slice bounds of loop nest surrounding 'depSourceAccess' are computed in terms of loop IVs and symbols of the loop nest surrounding 'depSinkAccess' at 'loopDepth'. If 'isBackwardSlice' is false, a forward slice is computed in which the slice bounds of loop nest surrounding 'depSinkAccess' are computed in terms of loop IVs and symbols of the loop nest surrounding 'depSourceAccess' at 'loopDepth'. The slice loop bounds and associated operands are returned in 'sliceState'.
Definition at line 680 of file Utils.cpp.
References mlir::StandardAttributes::AffineMap, mlir::Operation::getContext(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getIdValues(), getLoopIVs(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), getSequentialLoops(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::ComputationSliceState::insertPoint, mlir::ComputationSliceState::ivs, kSliceFusionBarrierAttrName, mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, mlir::FlatAffineConstraints::projectOut(), mlir::ComputationSliceState::ubOperands, and mlir::ComputationSliceState::ubs.
Referenced by computeSliceUnion().
getComputeCost()
int64_t mlir::getComputeCost (AffineForOp forOp, LoopNestStats & stats)
Computes the total cost of the loop nest rooted at 'forOp' using 'stats'.
Currently, the total cost is computed by counting the total operation instance count (i.e. total number of operations in the loop body * loop trip count) for the entire loop nest.
Definition at line 404 of file LoopFusionUtils.cpp.
References getComputeCostHelper().
Referenced by isFusionProfitable().
getConstantTripCount()
Optional< uint64_t > mlir::getConstantTripCount (AffineForOp forOp)
Returns the trip count of the loop if it's a constant, None otherwise.
This uses affine expression analysis and is able to determine constant trip count in non-trivial cases.
This method uses affine expression analysis (in turn using getTripCount) and is able to determine constant trip count in non-trivial cases.
Definition at line 91 of file LoopAnalysis.cpp.
References buildTripCountMapAndOperands(), mlir::AffineMap::getResults(), mlir::functional::map(), and mlir::StandardTypes::None.
Referenced by adjustToDivisorsOfTripCounts(), buildSliceTripCountMap(), constructTiledIndexSetHyperRect(), findMatchingStartFinishInsts(), getLoopNestStats(), instBodySkew(), loopUnrollByFactor(), loopUnrollFull(), loopUnrollJamByFactor(), loopUnrollJamUpToFactor(), loopUnrollUpToFactor(), and promoteIfSingleIteration().
getDependenceComponents()
void mlir::getDependenceComponents (AffineForOp forOp, unsigned maxLoopDepth, std::vector< SmallVector< DependenceComponent, 2 >> * depCompsVec)
Returns in 'depCompsVec', dependence components for dependences between all load and store ops in loop nest rooted at 'forOp', at loop depths in range [1, maxLoopDepth].
Gathers dependence components for dependences between all ops in loop nest rooted at 'forOp' at loop depths in range [1, maxLoopDepth].
Definition at line 857 of file AffineAnalysis.cpp.
References checkMemrefAccessDependence(), and hasDependence().
Referenced by hasDependence(), isValidLoopInterchangePermutation(), and sinkSequentialLoops().
getDocAttrName()
static constexpr StringLiteral mlir::getDocAttrName () static
Attribute name for the StringAttr which encodes an optional documentation string of the structured op.
Definition at line 51 of file StructuredOpsUtils.h.
getElementTypeOrSelf() [1/3]
Type mlir::getElementTypeOrSelf (Type type)
Return the element type or return the type itself.
Definition at line 21 of file TypeUtilities.cpp.
References mlir::Type::dyn_cast().
Referenced by mlir::OpTrait::util::getBroadcastedType(), getElementTypeOrSelf(), mlir::edsc::makeGenericLinalgOp(), verify(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), and mlir::OpTrait::impl::verifySameOperandsElementType().
getElementTypeOrSelf() [2/3]
Type mlir::getElementTypeOrSelf (Attribute attr)
Return the element type or return the type itself.
Definition at line 31 of file TypeUtilities.cpp.
References getElementTypeOrSelf(), and mlir::Attribute::getType().
getElementTypeOrSelf() [3/3]
Type mlir::getElementTypeOrSelf (Value val)
Definition at line 27 of file TypeUtilities.cpp.
References getElementTypeOrSelf(), and mlir::Value::getType().
getFlattenedAffineExpr() [1/2]
bool mlir::getFlattenedAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols, SmallVectorImpl< int64_t > * flattenedExpr)
Flattens 'expr' into 'flattenedExpr'.
Returns true on success or false if 'expr' could not be flattened (i.e., semi-affine is not yet handled). See documentation for AffineExprFlattener on how mod's and div's are flattened.
Definition at line 889 of file AffineExpr.cpp.
References getFlattenedAffineExprs(), mlir::SimpleAffineExprFlattener::numDims, and mlir::SimpleAffineExprFlattener::numSymbols.
getFlattenedAffineExpr() [2/2]
LogicalResult mlir::getFlattenedAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols, SmallVectorImpl< int64_t > * flattenedExpr, FlatAffineConstraints * cst = nullptr)
Flattens 'expr' into 'flattenedExpr', which contains the coefficients of the dimensions, symbols, and additional variables that represent floor divisions of dimensions, symbols, and in turn other floor divisions.
Returns failure if 'expr' could not be flattened (i.e., semi-affine is not yet handled). 'cst' contains constraints that connect newly introduced local identifiers to existing dimensional and symbolic identifiers. See documentation for AffineExprFlattener on how mod's and div's are flattened.
Definition at line 102 of file AffineStructures.cpp.
References getFlattenedAffineExprs().
Referenced by mlir::AffineExpr::cast(), and mlir::FlatAffineConstraints::setIdValues().
getFlattenedAffineExprs() [1/4]
bool mlir::getFlattenedAffineExprs (AffineMap map, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs)
Flattens the result expressions of the map to their corresponding flattened forms and set in 'flattenedExprs'.
Flattens the expressions in map.
Returns true on success or false if any expression in the map could not be flattened (i.e., semi-affine is not yet handled). For all affine expressions that share the same operands (like those of an affine map), this method should be used instead of repeatedly calling getFlattenedAffineExpr since local variables added to deal with div's and mod's will be reused across expressions.
Returns true on success or false if 'expr' was unable to be flattened (i.e., semi-affine expressions not handled yet).
Definition at line 902 of file AffineExpr.cpp.
References getFlattenedAffineExprs(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
getFlattenedAffineExprs() [2/4]
bool mlir::getFlattenedAffineExprs (IntegerSet set, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs)
Definition at line 911 of file AffineExpr.cpp.
References getFlattenedAffineExprs().
getFlattenedAffineExprs() [3/4]
LogicalResult mlir::getFlattenedAffineExprs (AffineMap map, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs, FlatAffineConstraints * localVarCst = nullptr)
Flattens the result expressions of the map to their corresponding flattened forms and set in 'flattenedExprs'.
Flattens the expressions in map.
Returns failure if any expression in the map could not be flattened (i.e., semi-affine is not yet handled). 'cst' contains constraints that connect newly introduced local identifiers to existing dimensional and / symbolic identifiers. See documentation for AffineExprFlattener on how mod's and div's are flattened. For all affine expressions that share the same operands (like those of an affine map), this method should be used instead of repeatedly calling getFlattenedAffineExpr since local variables added to deal with div's and mod's will be reused across expressions.
Returns failure if 'expr' was unable to be flattened (i.e., semi-affine expressions not handled yet).
Definition at line 115 of file AffineStructures.cpp.
References getFlattenedAffineExprs(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), mlir::FlatAffineConstraints::reset(), and success().
Referenced by mlir::FlatAffineConstraints::addLowerOrUpperBound(), addMemRefAccessConstraints(), mlir::AffineExpr::cast(), mlir::FlatAffineConstraints::composeMap(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::FlatAffineConstraints::FlatAffineConstraints(), getFlattenedAffineExpr(), and mlir::FlatAffineConstraints::setIdValues().
getFlattenedAffineExprs() [4/4]
LogicalResult mlir::getFlattenedAffineExprs (IntegerSet set, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs, FlatAffineConstraints * cst = nullptr)
Definition at line 127 of file AffineStructures.cpp.
References getFlattenedAffineExprs(), mlir::FlatAffineConstraints::reset(), and success().
getFlattenedTypes()
SmallVector< Type, 10 > mlir::getFlattenedTypes (TupleType t)
Get the types within a nested Tuple.
A helper for the class method that handles storage concerns, which is tricky to do in tablegen.
Definition at line 35 of file TypeUtilities.cpp.
References mlir::TupleType::getFlattenedTypes().
Referenced by mlir::TupleType::get().
getForInductionVarOwner()
ForOp mlir::loop::getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
If the provided value is not an induction variable, then return nullptr.
Definition at line 1572 of file AffineOps.cpp.
References mlir::Value::dyn_cast(), mlir::BlockArgument::getOwner(), mlir::Block::getParent(), and mlir::Region::getParentOp().
Referenced by mlir::FlatAffineConstraints::addInductionVarOrTerminalSymbol(), addMissingLoopIVBounds(), buildSliceTripCountMap(), mlir::MemRefRegion::compute(), mlir::FlatAffineConstraints::convertLoopIVSymbolsToDims(), mlir::ComputationSliceState::getAsConstraints(), getBackwardSliceImpl(), getCommonBlock(), getNumCommonLoops(), isForInductionVar(), isOpLoopInvariant(), and mlir::edsc::LoopBuilder::makeAffine().
getForwardSlice()
void mlir::getForwardSlice (Operation * op, llvm::SetVector< Operation *> * forwardSlice, TransitiveFilter filter = [](Operation *) { return true;})
Fills forwardSlice with the computed forward slice (i.e.
all the transitive uses of op), without including that operation.
This additionally takes a TransitiveFilter which acts as a frontier: when looking at uses transitively, a operation that does not pass the filter is never propagated through. This allows in particular to carve out the scope within a ForInst or the scope within an IfInst.
The implementation traverses the use chains in postorder traversal for efficiency reasons: if a operation is already in forwardSlice, no need to traverse its uses again. Since use-def chains form a DAG, this terminates.
Upon return to the root call, forwardSlice is filled with a postorder list of uses (i.e. a reverse topological order). To get a proper topological order, we just just reverse the order in forwardSlice before returning.
Example starting from node 0
          0
___________|___________ 1 2 3 4 |_______| |______| | | | | 5 6 |___|_____________| | | 7 8 |_______________| | 9
Assuming all local orders match the numbering order:
after getting back to the root getForwardSlice, forwardSlice may contain: {9, 7, 8, 5, 1, 2, 6, 3, 4}
reversing the result of 1. gives: {4, 3, 6, 2, 1, 5, 8, 7, 9}
Referenced by getForwardSliceImpl(), getSlice(), hoistOpsBetween(), and vectorizeNonTerminals().
getFunAttrName()
static constexpr StringLiteral mlir::getFunAttrName () static
Attribute name for the StrArrayAttr which encodes the SymbolAttr for the MLIR function that implements the body of the structured op.
Definition at line 55 of file StructuredOpsUtils.h.
Referenced by parseGenericOp().
getFusionComputeCost()
bool mlir::getFusionComputeCost (AffineForOp srcForOp, LoopNestStats & srcStats, AffineForOp dstForOp, LoopNestStats & dstStats, ComputationSliceState * slice, int64_t * computeCost)
Computes and returns in 'computeCost', the total compute cost of fusing the 'slice' of the loop nest rooted at 'srcForOp' into 'dstForOp'.
Currently, the total cost is computed by counting the total operation instance count (i.e. total number of operations in the loop body * loop trip count) for the entire loop nest. Returns true on success, failure otherwise (e.g. non-constant trip counts).
Currently, the total cost is computed by counting the total operation instance count (i.e. total number of operations in the loop body * loop trip count) for the entire loop nest.
Definition at line 415 of file LoopFusionUtils.cpp.
References buildSliceTripCountMap(), getComputeCostHelper(), getLoopIVs(), getSliceIterationCount(), and mlir::ComputationSliceState::insertPoint.
Referenced by isFusionProfitable().
getIndexingMapsAttrName()
static constexpr StringLiteral mlir::getIndexingMapsAttrName () static
Attribute name for the AffineArrayAttr which encodes the relationship between a structured op iterators' and its operands.
Definition at line 27 of file StructuredOpsUtils.h.
Referenced by mlir::vector::getVectorSubscriptAttr(), mlir::linalg::permuteGenericLinalgOp(), and verify().
getIndexSet()
LogicalResult mlir::getIndexSet (MutableArrayRef< AffineForOp > forOps, FlatAffineConstraints * domain)
Builds a system of constraints with dimensional identifiers corresponding to the loop IVs of the forOps appearing in that order.
Bounds of the loop are used to add appropriate inequalities. Any symbols founds in the bound operands are added as symbols in the system. Returns failure for the yet unimplemented cases.
Definition at line 91 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addAffineForOpDomain(), extractForInductionVars(), failed(), failure(), mlir::FlatAffineConstraints::reset(), and success().
Referenced by getInstIndexSet(), and tileCodeGen().
getInvariantAccesses()
DenseSet< Value > mlir::getInvariantAccesses (Value iv, ArrayRef< Value > indices)
Given an induction variable iv of type AffineForOp and indices of type IndexType, returns the set of indices that are independent of iv.
Prerequisites (inherited from isAccessInvariant above):
iv and indices of the proper type;
at most one affine.apply is reachable from each index in indices;
Emits a note if it encounters a chain of affine.apply and conservatively those cases.
Definition at line 191 of file LoopAnalysis.cpp.
References isAccessIndexInvariant().
Referenced by makePermutationMap().
getIteratorTypesAttrName()
static constexpr StringLiteral mlir::getIteratorTypesAttrName () static
Attribute name for the StrArrayAttr which encodes the type of a structured op's iterators.
Definition at line 33 of file StructuredOpsUtils.h.
Referenced by mlir::vector::getVectorSubscriptAttr(), mlir::linalg::permuteGenericLinalgOp(), and verify().
getLargestDivisorOfTripCount()
uint64_t mlir::getLargestDivisorOfTripCount (AffineForOp forOp)
Returns the greatest known integral divisor of the trip count.
Affine expression analysis is used (indirectly through getTripCount), and this method is thus able to determine non-trivial divisors.
Definition at line 117 of file LoopAnalysis.cpp.
References buildTripCountMapAndOperands(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getResults(), and mlir::functional::map().
Referenced by constructTiledIndexSetHyperRect(), loopUnrollByFactor(), and loopUnrollJamByFactor().
getLibraryCallAttrName()
static constexpr StringLiteral mlir::getLibraryCallAttrName () static
Attribute name for the StrArrayAttr which encodes the external library function that implements the structured op.
Definition at line 59 of file StructuredOpsUtils.h.
getLoopIVs()
void mlir::getLoopIVs (Operation & op, SmallVectorImpl< AffineForOp > * loops)
Populates 'loops' with IVs of the loops surrounding 'op' ordered from the outermost 'affine.for' operation to the innermost one.
Definition at line 31 of file Utils.cpp.
References mlir::Operation::getParentOp().
Referenced by mlir::MemRefRegion::compute(), findHighestBlockForPlacement(), getComputationSliceState(), getFullMemRefAsRegion(), getFusionComputeCost(), getInnermostCommonLoopDepth(), getInstIndexSet(), getLastDependentOpInRange(), getNumCommonSurroundingLoops(), insertBackwardComputationSlice(), isFusionProfitable(), isMemRefDereferencingOp(), and isOpLoopInvariant().
getLoopNestStats()
bool mlir::getLoopNestStats (AffineForOp forOpRoot, LoopNestStats * stats)
Collect loop nest statistics (eg.
loop trip count and operation count) in 'stats' for loop nest rooted at 'forOp'. Returns true on success, returns false otherwise.
Definition at line 252 of file LoopFusionUtils.cpp.
References mlir::WalkResult::advance(), getConstantTripCount(), mlir::WalkResult::interrupt(), mlir::LoopNestStats::loopMap, mlir::LoopNestStats::opCountMap, and mlir::LoopNestStats::tripCountMap.
Referenced by isFusionProfitable().
getMemoryFootprintBytes()
Optional< int64_t > mlir::getMemoryFootprintBytes (AffineForOp forOp, int memorySpace = -1)
Gets the memory footprint of all data touched in the specified memory space in bytes; if the memory space is unspecified, considers all memory spaces.
Definition at line 953 of file Utils.cpp.
References getMemoryFootprintBytes().
Referenced by adjustToDivisorsOfTripCounts(), createAffineDataCopyGenerationPass(), and isFusionProfitable().
getMemRefSizeInBytes()
Optional< uint64_t > mlir::getMemRefSizeInBytes (MemRefType memRefType)
Returns the size of memref data in bytes if it's statically shaped, None otherwise.
If the element of the memref has vector type, takes into account size of the vector as well.
Definition at line 356 of file Utils.cpp.
References getMemRefEltSizeInBytes(), and mlir::StandardTypes::None.
Referenced by generateCopy().
getNestingDepth()
unsigned mlir::getNestingDepth (Operation & op)
Returns the nesting depth of this operation, i.e., the number of loops surrounding this operation.
Returns the nesting depth of this statement, i.e., the number of loops surrounding this statement.
Definition at line 864 of file Utils.cpp.
References mlir::Operation::getParentOp().
Referenced by affineDataCopyGenerate(), computeSliceUnion(), createMemRefDataFlowOptPass(), getMemoryFootprintBytes(), isFusionProfitable(), and isLoopParallel().
getNumCommonSurroundingLoops()
unsigned mlir::getNumCommonSurroundingLoops (Operation & A, Operation & B)
Returns the number of surrounding loops common to both A and B.
Returns the number of surrounding loops common to 'loopsA' and 'loopsB', where each lists loops from outer-most to inner-most in loop nest.
Definition at line 894 of file Utils.cpp.
References getLoopIVs().
Referenced by canFuseLoops(), checkDependences(), createMemRefDataFlowOptPass(), and getMaxLoopDepth().
getNumIterators() [1/2]
unsigned mlir::getNumIterators (StringRef name, ArrayAttr iteratorTypes) inline
Returns the iterator of a certain type.
Definition at line 87 of file StructuredOpsUtils.h.
References mlir::Attribute::cast(), and getAllIteratorTypeNames().
Referenced by getNumIterators(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumLoops(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumParallelLoops(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumReductionLoops(), and mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumWindowLoops().
getNumIterators() [2/2]
unsigned mlir::getNumIterators (ArrayAttr iteratorTypes) inline
Definition at line 96 of file StructuredOpsUtils.h.
References getAllIteratorTypeNames(), and getNumIterators().
getParallelIteratorTypeName()
static constexpr StringLiteral mlir::getParallelIteratorTypeName () inline static
Use to encode that a particular iterator type has parallel semantics.
Definition at line 64 of file StructuredOpsUtils.h.
Referenced by getAllIteratorTypeNames(), getDimMap(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumParallelLoops(), and mlir::edsc::toString().
getPerfectlyNestedLoops() [1/2]
void mlir::getPerfectlyNestedLoops (SmallVectorImpl< AffineForOp > & nestedLoops, AffineForOp root)
Get perfectly nested sequence of loops starting at root of loop nest (the first op being another AffineFor, and the second op - a terminator).
A loop is perfectly nested iff: the first op in the loop's body is another AffineForOp, and the second op is a terminator).
Definition at line 373 of file LoopUtils.cpp.
References getPerfectlyNestedLoopsImpl().
Referenced by getTileableBands(), and sinkSequentialLoops().
getPerfectlyNestedLoops() [2/2]
void mlir::getPerfectlyNestedLoops (SmallVectorImpl< loop::ForOp > & nestedLoops, loop::ForOp root)
Definition at line 378 of file LoopUtils.cpp.
References getPerfectlyNestedLoopsImpl().
getReachableAffineApplyOps()
void mlir::getReachableAffineApplyOps (ArrayRef< Value > operands, SmallVectorImpl< Operation *> & affineApplyOps)
Returns in affineApplyOps, the sequence of those AffineApplyOp Operations that are reachable via a search starting from operands and ending at those operands that are not the result of an AffineApplyOp.
Returns the sequence of AffineApplyOp Operations operation in 'affineApplyOps', which are reachable via a search starting from 'operands', and ending at operands which are not defined by AffineApplyOps.
Definition at line 41 of file AffineAnalysis.cpp.
Referenced by createAffineComputationSlice(), findMatchingStartFinishInsts(), and isAccessIndexInvariant().
getReductionIteratorTypeName()
static constexpr StringLiteral mlir::getReductionIteratorTypeName () inline static
Use to encode that a particular iterator type has reduction semantics.
Definition at line 69 of file StructuredOpsUtils.h.
Referenced by getAllIteratorTypeNames(), getDimMap(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumReductionLoops(), and mlir::edsc::toString().
getSequentialLoops()
void mlir::getSequentialLoops (AffineForOp forOp, llvm::SmallDenseSet< Value, 8 > * sequentialLoops)
Returns in 'sequentialLoops' all sequential loops in loop nest rooted at 'forOp'.
Definition at line 963 of file Utils.cpp.
References isLoopParallel().
Referenced by getComputationSliceState().
getSlice()
SetVector< Operation * > mlir::getSlice (Operation * op, TransitiveFilter backwardFilter = [](Operation *) { return true; }, TransitiveFilter forwardFilter = [](Operation *) { return true; })
Iteratively computes backward slices and forward slices until a fixed point is reached.
Returns an llvm::SetVector<Operation *> which includes the original operation.
This allows building a slice (i.e. multi-root DAG where everything that is reachable from an Value in forward and backward direction is contained in the slice). This is the abstraction we need to materialize all the operations for supervectorization without worrying about orderings and Value replacements.
Example starting from any node
1 2 3 4 |_______| |______| | | | | | 5 6___| |___|_____________| | | | | 7 8 | |_______________| | | | 9 10
Return the whole DAG in some topological order.
The implementation works by just filling up a worklist with iterative alternate calls to getBackwardSlice and getForwardSlice.
The following section describes some additional implementation considerations for a potentially more efficient implementation but they are just an intuition without proof, we still use a worklist for now.
Additional implementation considerations
Consider the defs-op-uses hourglass.
\ / defs (in some topological order) \/ op /\ / \ uses (in some topological order) /____\
We want to iteratively apply getSlice to construct the whole list of Operation that are reachable by (use|def)+ from op. We want the resulting slice in topological order. Ideally we would like the ordering to be maintained in-place to avoid copying Operation at each step. Keeping this ordering by construction seems very unclear, so we list invariants in the hope of seeing whether useful properties pop up.
In the following: we use |= for set inclusion; we use << for set topological ordering (i.e. each pair is ordered).
Assumption:
We wish to maintain the following property by a recursive argument: """ defs << {op} <<uses are in topological order. """ The property clearly holds for 0 and 1-sized uses and defs;
Invariants:
defs and uses are in topological order internally, by construction;
for any {x} |= defs, defs(x) |= defs; because all go through op
for any {x} |= uses, defs |= defs(x); because all go through op
for any {x} |= defs, uses |= uses(x); because all go through op
for any {x} |= uses, uses(x) |= uses; because all go through op
Intuitively, we should be able to recurse like: preorder(defs) - op - postorder(uses) and keep things ordered but this is still hand-wavy and not worth the trouble for now: punt to a simple worklist-based solution.
Definition at line 134 of file SliceAnalysis.cpp.
References getBackwardSlice(), getForwardSlice(), and topologicalSort().
getStridesAndOffset() [1/2]
LogicalResult mlir::getStridesAndOffset (MemRefType t, SmallVectorImpl< int64_t > & strides, int64_t & offset)
Returns the strides of the MemRef if the layout map is in strided form.
MemRefs with layout maps in strided form include:
empty or identity layout map, in which case the stride information is the canonical form computed from sizes;
single affine map layout of the form K + k0 * d0 + ... kn * dn, where K and ki's are constants or symbols.
A stride specification is a list of integer values that are either static or dynamic (encoded with getDynamicStrideOrOffset()). Strides encode the distance in the number of elements between successive entries along a particular dimension. For example, memref<42x16xf32, (64 * d0 + d1)> specifies a view into a non-contiguous memory region of 42 by 16 f32 elements in which the distance between two consecutive elements along the outer dimension is 1 and the distance between two consecutive elements along the inner dimension is 64.
If a simple strided form cannot be extracted from the composition of the layout map, returns llvm::None.
The convention is that the strides for dimensions d0, .. dn appear in order to make indexing intuitive into the result.
Definition at line 592 of file StandardTypes.cpp.
References mlir::AffineExpr::dyn_cast(), failed(), failure(), mlir::ShapedType::kDynamicStrideOrOffset, and success().
Referenced by computeReshapeCollapsedType(), convertLinalgType(), getElementPtr(), getI64SubArray(), getTypeNumBytes(), inferSubViewResultType(), isStrided(), operator<<(), print(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), and verify().
getStridesAndOffset() [2/2]
LogicalResult mlir::getStridesAndOffset (MemRefType t, SmallVectorImpl< AffineExpr > & strides, AffineExpr & offset)
In practice, a strided memref must be internally non-aliasing. Test against 0 as a proxy. TODO(ntv) static cases can have more advanced checks. TODO(ntv) dynamic cases would require a way to compare symbolic expressions and would probably need an affine set context propagated everywhere.
Definition at line 523 of file StandardTypes.cpp.
References extractStrides(), failed(), failure(), getAffineConstantExpr(), mlir::MemRefType::getAffineMaps(), mlir::AffineExpr::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), mlir::MemRefType::getShape(), mlir::AffineMap::isIdentity(), makeCanonicalStridedLayoutExpr(), simplifyAffineExpr(), succeeded(), and success().
Referenced by mlir::NoneType::kindof().
getTranslationFromMLIRRegistry()
const llvm::StringMap< TranslateFromMLIRFunction > & mlir::getTranslationFromMLIRRegistry ()
Definition at line 105 of file Translation.cpp.
References getMutableTranslationFromMLIRRegistry().
Referenced by mlir::TranslationParser::TranslationParser().
getTranslationRegistry()
const llvm::StringMap< TranslateFunction > & mlir::getTranslationRegistry ()
Definition at line 109 of file Translation.cpp.
References getMutableTranslationRegistry().
Referenced by mlir::TranslationParser::TranslationParser().
getTranslationToMLIRRegistry()
const llvm::StringMap< TranslateSourceMgrToMLIRFunction > & mlir::getTranslationToMLIRRegistry ()
Get a read-only reference to the translator registry.
Definition at line 100 of file Translation.cpp.
References getMutableTranslationToMLIRRegistry().
Referenced by mlir::TranslationParser::TranslationParser().
getUsedValuesDefinedAbove() [1/2]
void mlir::getUsedValuesDefinedAbove (Region & region, Region & limit, llvm::SetVector< Value > & values)
Fill values with a list of values defined at the ancestors of the limit region and used within region or its descendants.
Definition at line 56 of file RegionUtils.cpp.
References mlir::OpOperand::get(), and visitUsedValuesDefinedAbove().
Referenced by areValuesDefinedAbove(), createLaunchFromOp(), and getUsedValuesDefinedAbove().
getUsedValuesDefinedAbove() [2/2]
void mlir::getUsedValuesDefinedAbove (MutableArrayRef< Region > regions, llvm::SetVector< Value > & values)
Fill values with a list of values used within any of the regions provided but defined in one of the ancestors.
Definition at line 63 of file RegionUtils.cpp.
References getUsedValuesDefinedAbove().
getWindowIteratorTypeName()
static constexpr StringLiteral mlir::getWindowIteratorTypeName () inline static
Use to encode that a particular iterator type has window semantics.
Definition at line 74 of file StructuredOpsUtils.h.
Referenced by getAllIteratorTypeNames(), and mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::getNumWindowLoops().
has_single_element()
template<typename ContainerTy > bool mlir::has_single_element (ContainerTy && c)
Returns true of the given range only contains a single element.
Definition at line 337 of file STLExtras.h.
Referenced by canonicalizeLoopBounds(), hasOneBranchOpTo(), mlir::IRMultiObjectWithUseList< OpOperand >::hasOneUse(), insertCopies(), mlir::SymbolTable::SymbolTable(), mlir::ModuleOp::verify(), verify(), and mlir::OpTrait::impl::verifySymbolTable().
hasDependence()
bool mlir::hasDependence (DependenceResult result) inline
Utility function that returns true if the provided DependenceResult corresponds to a dependence result.
Definition at line 118 of file AffineAnalysis.h.
References getDependenceComponents(), mlir::DependenceResult::HasDependence, and mlir::DependenceResult::value.
Referenced by checkDependences(), createMemRefDataFlowOptPass(), getDependenceComponents(), and getMaxLoopDepth().
hash_value() [1/9]
llvm::hash_code mlir::hash_value (Identifier arg) inline
Definition at line 92 of file Identifier.h.
References mlir::Identifier::strref().
hash_value() [2/9]
inline ::llvm::hash_code mlir::hash_value (IntegerSet arg)
Definition at line 114 of file IntegerSet.h.
hash_value() [3/9]
inline ::llvm::hash_code mlir::hash_value (AffineMap arg)
Definition at line 154 of file AffineMap.h.
References concatAffineMaps(), inversePermutation(), mlir::functional::map(), and simplifyAffineMap().
hash_value() [4/9]
inline ::llvm::hash_code mlir::hash_value (AffineExpr arg)
Make AffineExpr hashable.
Definition at line 195 of file AffineExpr.h.
References mlir::AffineExpr::expr.
Referenced by mlir::Type::classof(), mlir::Location::dump(), mlir::Attribute::getFromOpaquePointer(), mlir::Value::getFromOpaquePointer(), llvm::DenseMapInfo< mlir::IntegerSet >::getHashValue(), llvm::DenseMapInfo< mlir::FuncOp >::getHashValue(), llvm::DenseMapInfo< mlir::AffineMap >::getHashValue(), llvm::DenseMapInfo< mlir::Type >::getHashValue(), llvm::DenseMapInfo< mlir::AffineExpr >::getHashValue(), llvm::DenseMapInfo< mlir::Location >::getHashValue(), llvm::DenseMapInfo< mlir::Value >::getHashValue(), llvm::DenseMapInfo< mlir::BlockArgument >::getHashValue(), llvm::DenseMapInfo< mlir::Attribute >::getHashValue(), mlir::detail::DenseElementsAttributeStorage::getKey(), mlir::detail::DenseElementsAttributeStorage::getKeyForBoolData(), mlir::SDBMExpr::hash_value(), hash_value(), mlir::detail::BoolAttributeStorage::hashKey(), mlir::detail::FloatAttributeStorage::hashKey(), mlir::detail::IntegerAttributeStorage::hashKey(), mlir::AffineExpr::operator!(), mlir::AffineMap::operator!=(), and mlir::IntegerSet::operator==().
hash_value() [5/9]
llvm::hash_code mlir::hash_value (OperationName arg) inline
Definition at line 250 of file OperationSupport.h.
References mlir::OperationName::getAsOpaquePointer().
hash_value() [6/9]
inline ::llvm::hash_code mlir::hash_value (Type arg)
Definition at line 250 of file Types.h.
References mlir::Type::impl.
hash_value() [7/9]
inline ::llvm::hash_code mlir::hash_value (Location arg)
Definition at line 289 of file Location.h.
References hash_value(), and mlir::Location::impl.
hash_value() [8/9]
inline ::llvm::hash_code mlir::hash_value (Value arg)
Make Value hashable.
Definition at line 305 of file Value.h.
References mlir::Value::ownerAndKind.
hash_value() [9/9]
inline ::llvm::hash_code mlir::hash_value (Attribute arg)
Definition at line 1360 of file Attributes.h.
References mlir::Attribute::impl.
initializeLLVMPasses()
void mlir::initializeLLVMPasses ()
Initialize LLVM passes that can be when running MLIR code using ExecutionEngine.
Definition at line 46 of file OptUtils.cpp.
Referenced by compileAndExecuteSingleFloatReturnFunction().
inlineCall()
LogicalResult mlir::inlineCall (InlinerInterface & interface, CallOpInterface call, CallableOpInterface callable, Region * src, bool shouldCloneInlinedRegion = true)
This function inlines a given region, 'src', of a callable operation, 'callable', into the location defined by the given call operation.
This function returns failure if inlining is not possible, success otherwise. On failure, no changes are made to the module. 'shouldCloneInlinedRegion' corresponds to whether the source region should be cloned into the 'call' or spliced directly.
Definition at line 279 of file InliningUtils.cpp.
References mlir::Region::empty(), failed(), failure(), mlir::Region::front(), mlir::Value::getDefiningOp(), mlir::DialectInterfaceCollection< InterfaceType >::getInterfaceFor(), mlir::Value::getType(), mlir::BlockArgument::getType(), inlineRegion(), mlir::BlockAndValueMapping::map(), materializeConversion(), mlir::Value::replaceAllUsesWith(), mlir::Operation::replaceUsesOfWith(), mlir::OpBuilder::setInsertionPointAfter(), and success().
Referenced by inlineCallsInSCC(), and mlir::InlinerInterface::processInlinedBlocks().
inlineRegion() [1/2]
LogicalResult mlir::inlineRegion (InlinerInterface & interface, Region * src, Operation * inlinePoint, BlockAndValueMapping & mapper, ArrayRef< Value > resultsToReplace, Optional< Location > inlineLoc = llvm::None, bool shouldCloneInlinedRegion = true)
This function inlines a region, 'src', into another.
This function returns failure if it is not possible to inline this function. If the function returned failure, then no changes to the module have been made.
The provided 'inlinePoint' must be within a region, and corresponds to the location where the 'src' region should be inlined. 'mapping' contains any remapped operands that are used within the region, and must include remappings for the entry arguments to the region. 'resultsToReplace' corresponds to any results that should be replaced by terminators within the inlined region. 'inlineLoc' is an optional Location that, if provided, will be used to update the inlined operations' location information. 'shouldCloneInlinedRegion' corresponds to whether the source region should be cloned into the 'inlinePoint' or spliced directly.
Handle the terminators for each of the new blocks.
Definition at line 128 of file InliningUtils.cpp.
References mlir::Block::addArgument(), mlir::Region::begin(), mlir::Block::begin(), mlir::Region::cloneInto(), mlir::BlockAndValueMapping::contains(), mlir::Region::empty(), mlir::Region::end(), mlir::Block::end(), mlir::Block::erase(), failure(), mlir::Region::front(), mlir::Operation::getBlock(), mlir::Region::getBlocks(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::InlinerInterface::handleTerminator(), mlir::InlinerInterface::isLegalToInline(), mlir::InlinerInterface::processInlinedBlocks(), remapInlinedLocations(), remapInlinedOperands(), mlir::Block::splitBlock(), and success().
Referenced by inlineCall(), inlineRegion(), and mlir::InlinerInterface::processInlinedBlocks().
inlineRegion() [2/2]
LogicalResult mlir::inlineRegion (InlinerInterface & interface, Region * src, Operation * inlinePoint, ArrayRef< Value > inlinedOperands, ArrayRef< Value > resultsToReplace, Optional< Location > inlineLoc = llvm::None, bool shouldCloneInlinedRegion = true)
This function is an overload of the above 'inlineRegion' that allows for providing the set of operands ('inlinedOperands') that should be used in-favor of the region arguments when inlining.
Definition at line 221 of file InliningUtils.cpp.
References mlir::Region::empty(), failure(), mlir::Region::front(), mlir::BlockArgument::getType(), inlineRegion(), and mlir::BlockAndValueMapping::map().
insertBackwardComputationSlice()
AffineForOp mlir::insertBackwardComputationSlice (Operation * srcOpInst, Operation * dstOpInst, unsigned dstLoopDepth, ComputationSliceState * sliceState)
Creates a clone of the computation contained in the loop nest surrounding 'srcOpInst', slices the iteration space of src loop based on slice bounds in 'sliceState', and inserts the computation slice at the beginning of the operation block of the loop at 'dstLoopDepth' in the loop nest surrounding 'dstOpInst'.
Creates a computation slice of the loop nest surrounding 'srcOpInst', updates the slice loop bounds with any non-null bound maps specified in 'sliceState', and inserts this slice into the loop nest surrounding 'dstOpInst' at loop depth 'dstLoopDepth'.
Returns the top-level loop of the computation slice on success, returns nullptr otherwise.
Definition at line 777 of file Utils.cpp.
References mlir::Operation::emitError(), findInstPosition(), getInstAtPosition(), getLoopIVs(), mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, mlir::ComputationSliceState::ubOperands, and mlir::ComputationSliceState::ubs.
Referenced by isFusionProfitable().
instBodySkew()
LogicalResult mlir::instBodySkew (AffineForOp forOp, ArrayRef< uint64_t > shifts, bool unrollPrologueEpilogue = false)
Skew the operations in the body of a 'affine.for' operation with the specified operation-wise shifts.
The shifts are with respect to the original execution order, and are multiplied by the loop 'step' before being applied.
The shifts are with respect to the original execution order, and are multiplied by the loop 'step' before being applied. A shift of zero for each operation will lead to no change.
Definition at line 229 of file LoopUtils.cpp.
References generateLoop(), getConstantTripCount(), isInstwiseShiftValid(), loopUnrollFull(), and success().
Referenced by findMatchingStartFinishInsts().
interchangeLoops() [1/2]
void mlir::interchangeLoops (AffineForOp forOpA, AffineForOp forOpB)
Performs loop interchange on 'forOpA' and 'forOpB'.
Performs loop interchange on 'forOpA' and 'forOpB', where 'forOpB' is nested within 'forOpA' as the only non-terminator operation in its block.
Requires that 'forOpA' and 'forOpB' are part of a perfectly nested sequence of loops.
Definition at line 499 of file LoopUtils.cpp.
Referenced by sinkLoop(), and sinkSequentialLoops().
interchangeLoops() [2/2]
unsigned mlir::interchangeLoops (ArrayRef< AffineForOp > loops, ArrayRef< unsigned > loopPermMap)
Performs a sequence of loop interchanges on perfectly nested 'loops', as specified by permutation 'loopPermMap' (loop 'i' in 'loops' is mapped to location 'j = 'loopPermMap[i]' after the loop interchange).
Performs a sequence of loop interchanges of loops in perfectly nested sequence of loops in 'loops', as specified by permutation in 'loopPermMap'.
Definition at line 572 of file LoopUtils.cpp.
References sinkLoop().
interleave() [1/4]
template<typename ForwardIterator , typename UnaryFunctor , typename NullaryFunctor , typename = typename std::enable_if< !std::is_constructible<StringRef, UnaryFunctor>::value && !std::is_constructible<StringRef, NullaryFunctor>::value>::type> void mlir::interleave (ForwardIterator begin, ForwardIterator end, UnaryFunctor each_fn, NullaryFunctor between_fn) inline
An STL-style algorithm similar to std::for_each that applies a second functor between every pair of elements.
This provides the control flow logic to, for example, print a comma-separated list:
interleave(names.begin(), names.end(),
           [&](StringRef name) { os << name; },
           [&] { os << ", "; });
Definition at line 43 of file STLExtras.h.
Referenced by appendMangledType(), mlir::Diagnostic::appendRange(), mlir::linalg::generateLibraryCallName(), interleave(), interleaveComma(), mlir::detail::PassOptions::ListOption< DataType >::operator->(), mlir::detail::PassOptions::print(), printUniformQuantizedPerAxisType(), and mlir::AsmState::~AsmState().
interleave() [2/4]
template<typename Container , typename UnaryFunctor , typename NullaryFunctor , typename = typename std::enable_if< !std::is_constructible<StringRef, UnaryFunctor>::value && !std::is_constructible<StringRef, NullaryFunctor>::value>::type> void mlir::interleave (const Container & c, UnaryFunctor each_fn, NullaryFunctor between_fn) inline
Definition at line 59 of file STLExtras.h.
References interleave().
interleave() [3/4]
template<typename Container , typename UnaryFunctor , typename raw_ostream , typename T = detail::ValueOfRange<Container>> void mlir::interleave (const Container & c, raw_ostream & os, UnaryFunctor each_fn, const StringRef & separator) inline
Overload of interleave for the common case of string separator.
Definition at line 67 of file STLExtras.h.
References interleave().
interleave() [4/4]
template<typename Container , typename raw_ostream , typename T = detail::ValueOfRange<Container>> void mlir::interleave (const Container & c, raw_ostream & os, const StringRef & separator) inline
Definition at line 73 of file STLExtras.h.
References interleave().
interleaveComma() [1/2]
template<typename Container , typename UnaryFunctor , typename raw_ostream , typename T = detail::ValueOfRange<Container>> void mlir::interleaveComma (const Container & c, raw_ostream & os, UnaryFunctor each_fn) inline
Definition at line 81 of file STLExtras.h.
References interleave().
Referenced by mlir::detail::OpToOpPassAdaptorBase::getName(), interleaveComma(), mlir::ConversionPattern::matchAndRewrite(), operator<<(), print(), mlir::Pass::printAsTextualPipeline(), mlir::OpPassManager::printAsTextualPipeline(), printAttributions(), printDenseFloatElement(), printElidedElementsAttr(), mlir::OpAsmPrinter::printFunctionalType(), printFunctionResultList(), printLaunchOp(), mlir::OpAsmPrinter::printOptionalArrowTypeList(), mlir::quantizer::CAGUniformMetadata::printSummary(), and mlir::AsmState::~AsmState().
interleaveComma() [2/2]
template<typename Container , typename raw_ostream , typename T = detail::ValueOfRange<Container>> void mlir::interleaveComma (const Container & c, raw_ostream & os) inline
Definition at line 87 of file STLExtras.h.
References interleaveComma().
inversePermutation()
AffineMap mlir::inversePermutation (AffineMap map)
Returns a map of codomain to domain dimensions such that the first codomain dimension for a particular domain dimension is selected.
Returns an empty map if the input map is empty or if map is not invertible (i.e. map does not contain a subset that is a permutation of full domain rank).
Prerequisites:
map has no symbols.
Example 1:
(d0, d1, d2) -> (d1, d1, d0, d2, d1, d2, d1, d0)
                  0       2   3
returns:
(d0, d1, d2, d3, d4, d5, d6, d7) -> (d2, d0, d3)
Example 2:
(d0, d1, d2) -> (d1, d0 + d1, d0, d2, d1, d2, d1, d0)
                  0            2   3
returns:
(d0, d1, d2, d3, d4, d5, d6, d7) -> (d2, d0, d3)
Definition at line 289 of file AffineMap.cpp.
References mlir::StandardAttributes::AffineMap, mlir::AffineExpr::dyn_cast(), mlir::detail::enumerate(), mlir::AffineMap::get(), getAffineDimExpr(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::functional::map().
Referenced by emitLoopRanges(), hash_value(), mlir::linalg::permuteGenericLinalgOp(), mlir::linalg::tileLinalgOp(), and verifyGenericOp().
isForInductionVar()
bool mlir::isForInductionVar (Value val)
Returns if the provided value is the induction variable of a AffineForOp.
Definition at line 1566 of file AffineOps.cpp.
References getForInductionVarOwner().
Referenced by mlir::FlatAffineConstraints::addInductionVarOrTerminalSymbol(), addMemRefAccessConstraints(), addMissingLoopIVBounds(), buildDimAndSymbolPositionMaps(), getNumCommonLoops(), initDependenceConstraints(), and isAccessIndexInvariant().
isInstwiseShiftValid()
bool mlir::isInstwiseShiftValid (AffineForOp forOp, ArrayRef< uint64_t > shifts)
Checks where SSA dominance would be violated if a for op's body operations are shifted by the specified shifts.
Checks whether SSA dominance would be violated if a for op's body operations are shifted by the specified shifts.
This method checks if a 'def' and all its uses have the same shift factor.
Definition at line 355 of file LoopAnalysis.cpp.
References mlir::detail::enumerate(), and mlir::Value::getUsers().
Referenced by findMatchingStartFinishInsts(), and instBodySkew().
isLoopParallel()
bool mlir::isLoopParallel (AffineForOp forOp)
Returns true if `forOp' is a parallel loop.
Returns true if 'forOp' is parallel.
Definition at line 973 of file Utils.cpp.
References mlir::WalkResult::advance(), checkMemrefAccessDependence(), getNestingDepth(), mlir::Operation::hasNoSideEffect(), mlir::WalkResult::interrupt(), mlir::DependenceResult::NoDependence, and mlir::DependenceResult::value.
Referenced by createParallelismDetectionTestPass(), getSequentialLoops(), and vectorizeRootMatch().
isOpaqueTypeWithName()
bool mlir::isOpaqueTypeWithName (Type type, StringRef dialect, StringRef typeData)
Return true if the specified type is an opaque type with the specified dialect and typeData.
Definition at line 43 of file TypeUtilities.cpp.
References mlir::Type::dyn_cast().
isStrided()
bool mlir::isStrided (MemRefType t)
Return true if the layout for t is compatible with strided semantics.
Definition at line 734 of file StandardTypes.cpp.
References getStridesAndOffset(), and succeeded().
Referenced by getMemRefSizes(), mlir::DmaStartOp::getNumElementsPerStride(), mlir::AffineDmaStartOp::getNumElementsPerStride(), mlir::DmaStartOp::getStride(), mlir::AffineDmaStartOp::getStride(), mlir::NoneType::kindof(), mlir::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::DmaStartOp::print(), mlir::AffineDmaStartOp::print(), and toStringRef().
isTopLevelValue()
bool mlir::isTopLevelValue (Value value)
A utility function to check if a value is defined at the top level of a function.
A value of index type defined at the top level is always a valid symbol.
Definition at line 109 of file AffineOps.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::Operation::getParentRegion(), and isFunctionRegion().
Referenced by mlir::FlatAffineConstraints::addInductionVarOrTerminalSymbol(), isDimOpValidSymbol(), isValidDim(), and isValidSymbol().
isValidDim()
bool mlir::isValidDim (Value value)
Returns true if the given Value can be used as a dimension id.
Definition at line 118 of file AffineOps.cpp.
References mlir::Value::cast(), mlir::Value::getDefiningOp(), mlir::Value::getType(), isFunctionRegion(), mlir::Type::isIndex(), and isTopLevelValue().
Referenced by categorizeValueByAffineType(), mlir::AffineApplyOp::getAffineMap(), mlir::AffineStoreOp::getOperationName(), isValidAffineIndexOperand(), mlir::AffineApplyOp::isValidDim(), replaceAllMemRefUsesWith(), and verifyDimAndSymbolIdentifiers().
isValidLoopInterchangePermutation()
bool mlir::isValidLoopInterchangePermutation (ArrayRef< AffineForOp > loops, ArrayRef< unsigned > loopPermMap)
Checks if the loop interchange permutation 'loopPermMap', of the perfectly nested sequence of loops in 'loops', would violate dependences (loop 'i' in 'loops' is mapped to location 'j = 'loopPermMap[i]' in the interchange).
Checks if the loop interchange permutation 'loopPermMap' of the perfectly nested sequence of loops in 'loops' would violate dependences.
Definition at line 559 of file LoopUtils.cpp.
References checkLoopInterchangeDependences(), and getDependenceComponents().
isValidSymbol()
bool mlir::isValidSymbol (Value value)
Returns true if the given Value can be used as a symbol.
Definition at line 179 of file AffineOps.cpp.
References mlir::Value::getDefiningOp(), mlir::Value::getType(), isDimOpValidSymbol(), isFunctionRegion(), mlir::Type::isIndex(), and isTopLevelValue().
Referenced by addMemRefAccessConstraints(), buildDimAndSymbolPositionMaps(), canonicalizePromotedSymbols(), categorizeValueByAffineType(), mlir::MemRefRegion::compute(), mlir::AffineApplyOp::getAffineMap(), mlir::ComputationSliceState::getAsConstraints(), mlir::AffineStoreOp::getOperationName(), initDependenceConstraints(), isMemRefSizeValidSymbol(), isValidAffineIndexOperand(), mlir::AffineApplyOp::isValidSymbol(), promoteComposedSymbolsAsDims(), replaceAllMemRefUsesWith(), and verifyDimAndSymbolIdentifiers().
isVectorizableLoopBody() [1/2]
bool mlir::isVectorizableLoopBody (AffineForOp loop, NestedPattern & vectorTransferMatcher)
Checks whether the loop is structurally vectorizable; i.e.
:
no conditionals are nested under the loop;
all nested load/stores are to scalar MemRefs. TODO(ntv): relax the no-conditionals restriction
Definition at line 345 of file LoopAnalysis.cpp.
References isVectorizableLoopBodyWithOpCond().
Referenced by isVectorizableLoopPtrFactory(), and vectorizeRootMatch().
isVectorizableLoopBody() [2/2]
bool mlir::isVectorizableLoopBody (AffineForOp loop, int * memRefDim, NestedPattern & vectorTransferMatcher)
Checks whether the loop is structurally vectorizable and that all the LoadOp and StoreOp matched have access indexing functions that are are either:
invariant along the loop induction variable created by 'loop';
varying along at most one memory dimension. If such a unique dimension is found, it is written into memRefDim.
Definition at line 334 of file LoopAnalysis.cpp.
References isContiguousAccess(), and isVectorizableLoopBodyWithOpCond().
JitRunnerMain()
int mlir::JitRunnerMain (int argc, char ** argv, llvm::function_ref< LogicalResult(mlir::ModuleOp)> mlirTransformer)
Referenced by compileAndExecuteSingleFloatReturnFunction().
lcm()
int64_t mlir::lcm (int64_t a, int64_t b) inline
Returns the least common multiple of 'a' and 'b'.
Definition at line 47 of file MathExtras.h.
Referenced by eliminateFromConstraint(), and getNewNumDimsSymbols().
loopUnrollByFactor()
LogicalResult mlir::loopUnrollByFactor (AffineForOp forOp, uint64_t unrollFactor)
Unrolls this for operation by the specified unroll factor.
Unrolls this loop by the specified factor.
Returns failure if the loop cannot be unrolled either due to restrictions or due to invalid unroll factors.
Returns success if the loop is successfully unrolled.
Definition at line 410 of file LoopUtils.cpp.
References mlir::OpBuilder::clone(), mlir::OpBuilder::create(), failure(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Operation::getBlock(), getCleanupLoopLowerBound(), getConstantTripCount(), getLargestDivisorOfTripCount(), mlir::BlockAndValueMapping::map(), promoteIfSingleIteration(), and success().
Referenced by loopUnrollFull(), and loopUnrollUpToFactor().
loopUnrollFull()
LogicalResult mlir::loopUnrollFull (AffineForOp forOp)
Unrolls this for operation completely if the trip count is known to be constant.
Unrolls this loop completely.
Returns failure otherwise.
Definition at line 384 of file LoopUtils.cpp.
References failure(), getConstantTripCount(), loopUnrollByFactor(), and promoteIfSingleIteration().
Referenced by instBodySkew().
loopUnrollJamByFactor()
LogicalResult mlir::loopUnrollJamByFactor (AffineForOp forOp, uint64_t unrollJamFactor)
Unrolls and jams this loop by the specified factor.
Returns success if the loop is successfully unroll-jammed.
Definition at line 116 of file LoopUnrollAndJam.cpp.
References mlir::Block::begin(), mlir::Block::end(), failure(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), getCleanupLoopLowerBound(), getConstantTripCount(), getLargestDivisorOfTripCount(), mlir::Operation::getRegions(), mlir::BlockAndValueMapping::map(), pass, promoteIfSingleIteration(), and success().
Referenced by createLoopUnrollAndJamPass(), and loopUnrollJamUpToFactor().
loopUnrollJamUpToFactor()
LogicalResult mlir::loopUnrollJamUpToFactor (AffineForOp forOp, uint64_t unrollJamFactor)
Unrolls and jams this loop by the specified factor or by the trip count (if constant), whichever is lower.
Definition at line 105 of file LoopUnrollAndJam.cpp.
References getConstantTripCount(), and loopUnrollJamByFactor().
loopUnrollUpToFactor()
LogicalResult mlir::loopUnrollUpToFactor (AffineForOp forOp, uint64_t unrollFactor)
Unrolls this loop by the specified unroll factor or its trip count, whichever is lower.
Unrolls and jams this loop by the specified factor or by the trip count (if constant) whichever is lower.
Definition at line 398 of file LoopUtils.cpp.
References getConstantTripCount(), and loopUnrollByFactor().
lowerAffineLowerBound()
Value mlir::lowerAffineLowerBound (AffineForOp op, OpBuilder & builder)
Emit code that computes the lower bound of the given affine loop using standard arithmetic operations.
Definition at line 264 of file AffineToStandard.cpp.
References buildMinMaxReductionSeq(), and expandAffineMap().
Referenced by getOrEmitLowerBound(), and lowerAffineUpperBound().
lowerAffineUpperBound()
Value mlir::lowerAffineUpperBound (AffineForOp op, OpBuilder & builder)
Emit code that computes the upper bound of the given affine loop using standard arithmetic operations.
Definition at line 287 of file AffineToStandard.cpp.
References mlir::PatternRewriter::create(), mlir::PatternRewriter::eraseOp(), expandAffineExpr(), expandAffineMap(), mlir::AffineApplyOp::getAffineMap(), mlir::AffineLoadOp::getAffineMap(), mlir::AffineStoreOp::getAffineMap(), mlir::AffineDmaStartOp::getDstMap(), mlir::DmaStartOp::getDstMemRef(), mlir::AffineDmaStartOp::getDstMemRefOperandIndex(), mlir::OpState::getLoc(), mlir::AffineLoadOp::getMapOperands(), mlir::AffineStoreOp::getMapOperands(), mlir::AffineLoadOp::getMemRef(), mlir::DmaStartOp::getNumElements(), mlir::DmaWaitOp::getNumElements(), mlir::DmaStartOp::getNumElementsPerStride(), mlir::OpTrait::detail::MultiOperandTraitBase< ConcreteType, TraitType >::getOperands(), mlir::AffineDmaStartOp::getSrcMap(), mlir::DmaStartOp::getSrcMemRef(), mlir::AffineDmaStartOp::getSrcMemRefOperandIndex(), mlir::DmaStartOp::getStride(), mlir::AffineDmaWaitOp::getTagIndices(), mlir::AffineDmaStartOp::getTagMap(), mlir::AffineDmaWaitOp::getTagMap(), mlir::DmaStartOp::getTagMemRef(), mlir::DmaWaitOp::getTagMemRef(), mlir::AffineDmaStartOp::getTagMemRefOperandIndex(), mlir::AffineStoreOp::getValueToStore(), mlir::PatternRewriter::inlineRegionBefore(), lowerAffineLowerBound(), lowerAffineMapMin(), mlir::PatternRewriter::replaceOp(), and mlir::PatternRewriter::replaceOpWithNewOp().
Referenced by getOrEmitUpperBound().
m_Constant() [1/2]
detail::constant_op_binder<Attribute> mlir::m_Constant () inline
Matches a constant foldable operation.
Definition at line 205 of file Matchers.h.
Referenced by canonicalizeMapOrSetAndOperands(), foldLoopBounds(), materializeConstant(), mlir::OperationFolder::notifyRemoval(), mlir::OpBuilder::tryFold(), and verify().
m_Constant() [2/2]
template<typename AttrT > detail::constant_op_binder<AttrT> mlir::m_Constant (AttrT * bind_value) inline
Matches a value from a constant foldable operation and writes the value to bind_value.
Definition at line 212 of file Matchers.h.
References mlir::detail::attr_value_binder< AttrClass, ValueType, typename >::bind_value.
m_ConstantInt()
detail::constant_int_op_binder mlir::m_ConstantInt (IntegerAttr::ValueType * bind_value) inline
Matches a constant holding a scalar/vector/tensor integer (splat) and writes the integer value to bind_value.
Definition at line 255 of file Matchers.h.
m_NonZero()
detail::constant_int_not_value_matcher<0> mlir::m_NonZero () inline
Matches a constant scalar / vector splat / tensor splat integer that is any non-zero value.
Definition at line 233 of file Matchers.h.
Referenced by applyCmpPredicate().
m_One()
detail::constant_int_value_matcher<1> mlir::m_One () inline
Matches a constant scalar / vector splat / tensor splat integer one.
Definition at line 217 of file Matchers.h.
Referenced by verify().
m_Op() [1/2]
template<typename OpClass > detail::op_matcher<OpClass> mlir::m_Op () inline
Matches the given OpClass.
Definition at line 222 of file Matchers.h.
m_Op() [2/2]
template<typename OpType , typename... Matchers> auto mlir::m_Op (Matchers... matchers)
Definition at line 260 of file Matchers.h.
m_Zero()
detail::constant_int_value_matcher<0> mlir::m_Zero () inline
Matches a constant scalar / vector splat / tensor splat integer zero.
Definition at line 227 of file Matchers.h.
Referenced by applyCmpPredicate(), foldMemRefCast(), and verify().
make_second_range()
template<typename ContainerTy > auto mlir::make_second_range (ContainerTy && c)
Given a container of pairs, return a range over the second elements.
Definition at line 328 of file STLExtras.h.
Referenced by rebuildAttrAfterRAUW(), and walkSymbolRefs().
makeComposedAffineApply()
AffineApplyOp mlir::makeComposedAffineApply (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > operands)
Returns a composed AffineApplyOp by composing map and operands with other AffineApplyOps supplying those operands.
The operands of the resulting AffineApplyOp do not change the length of AffineApplyOp chains.
Definition at line 598 of file AffineOps.cpp.
References composeAffineMapAndOperands(), mlir::OpBuilder::create(), and mlir::functional::map().
Referenced by mlir::edsc::ValueHandle::createComposedAffineApply(), and mlir::AffineStoreOp::getOperationName().
makeStridedLinearLayoutMap()
AffineMap mlir::makeStridedLinearLayoutMap (ArrayRef< int64_t > strides, int64_t offset, MLIRContext * context)
Given a list of strides (in which MemRefType::getDynamicStrideOrOffset() represents a dynamic value), return the single result AffineMap which represents the linearized strided layout map.
Dimensions correspond to the offset followed by the strides in order. Symbols are inserted for each dynamic dimension in order. A stride cannot take value 0.
Examples:
For offset: 0 strides: ?, ?, 1 return (i, j, k)[M, N]->(M * i + N * j + k)
For offset: 3 strides: 32, ?, 16 return (i, j, k)[M]->(3 + 32 * i + M * j + 16 * k)
For offset: ? strides: ?, ?, ? return (i, j, k)[off, M, N, P]->(off + M * i + N * j + P * k)
Definition at line 666 of file StandardTypes.cpp.
References mlir::detail::enumerate(), mlir::AffineMap::get(), getAffineConstantExpr(), getAffineDimExpr(), getAffineSymbolExpr(), and mlir::MemRefType::getDynamicStrideOrOffset().
Referenced by computeReshapeCollapsedType(), inferSubViewResultType(), mlir::NoneType::kindof(), operator<<(), parseSymbol(), and verify().
mapLoopToProcessorIds()
void mlir::mapLoopToProcessorIds (loop::ForOp forOp, ArrayRef< Value > processorId, ArrayRef< Value > numProcessors)
Maps forOp for execution on a parallel grid of virtual processorIds of size given by numProcessors.
This is achieved by embedding the SSA values corresponding to processorIds and numProcessors into the bounds and step of the forOp. No check is performed on the legality of the rewrite, it is the caller's responsibility to ensure legality.
Requires that processorIds and numProcessors have the same size and that for each idx, processorIds[idx] takes, at runtime, all values between 0 and numProcessors[idx] - 1. This corresponds to traditional use cases for:
GPU (threadIdx, get_local_id(), ...)
MPI (MPI_Comm_rank)
OpenMP (omp_get_thread_num)
Example: Assuming a 2-d grid with processorIds = [blockIdx.x, threadIdx.x] and numProcessors = [gridDim.x, blockDim.x], the loop:
loop.for %i = %lb to %ub step %step {
  ...
}
is rewritten into a version resembling the following pseudo-IR:
loop.for %i = %lb + %step * (threadIdx.x + blockIdx.x * blockDim.x)
   to %ub step %gridDim.x * blockDim.x * %step {
  ...
}
Definition at line 1096 of file LoopUtils.cpp.
References mlir::OpBuilder::create().
Referenced by createGPULaunchLoops(), and insertCopyLoops().
matchPattern() [1/2]
template<typename Pattern > bool mlir::matchPattern (Value value, const Pattern & pattern) inline
Entry point for matching a pattern over a Value.
Definition at line 239 of file Matchers.h.
References mlir::Value::getDefiningOp().
Referenced by applyCmpPredicate(), canonicalizeMapOrSetAndOperands(), foldLoopBounds(), foldMemRefCast(), materializeConstant(), mlir::OperationFolder::notifyRemoval(), operator<<(), mlir::OpBuilder::tryFold(), and verify().
matchPattern() [2/2]
template<typename Pattern > bool mlir::matchPattern (Operation * op, const Pattern & pattern) inline
Entry point for matching a pattern over an Operation.
Definition at line 248 of file Matchers.h.
References mlir::detail::attr_value_binder< AttrClass, ValueType, typename >::match().
MlirOptMain()
LogicalResult mlir::MlirOptMain (llvm::raw_ostream & os, std::unique_ptr< llvm::MemoryBuffer > buffer, const PassPipelineCLParser & passPipeline, bool splitInputFile, bool verifyDiagnostics, bool verifyPasses)
Referenced by processBuffer().
mod()
int64_t mlir::mod (int64_t lhs, int64_t rhs) inline
Returns MLIR's mod operation on constants.
MLIR's mod operation yields the remainder of the Euclidean division of 'lhs' by 'rhs', and is therefore not C's % operator. The RHS is always expected to be positive, and the result is always non-negative.
Definition at line 41 of file MathExtras.h.
Referenced by mlir::quantizer::BasePropagatedFact< ExpandingMinMaxReducer >::assertValue(), and simplifyMod().
normalizeMemRef()
LogicalResult mlir::normalizeMemRef (AllocOp op)
Rewrites the memref defined by this alloc op to have an identity layout map and updates all its indexing uses.
Returns failure if any of its uses escape (while leaving the IR in a valid state).
Definition at line 390 of file Utils.cpp.
References mlir::FlatAffineConstraints::addConstantLowerBound(), mlir::OpBuilder::create(), failed(), failure(), mlir::MemRefType::get(), mlir::MemRefType::getAffineMaps(), mlir::Builder::getMultiDimIdentityMap(), mlir::AffineMap::getNumResults(), mlir::MemRefType::getShape(), replaceAllMemRefUsesWith(), and success().
Referenced by createSimplifyAffineStructuresPass().
openInputFile()
std::unique_ptr<llvm::MemoryBuffer> mlir::openInputFile (llvm::StringRef inputFilename, std::string * errorMessage = nullptr)
Open the file specified by its name for reading.
Write the error message to errorMessage if errors occur and errorMessage is not nullptr.
Referenced by parseMLIRInput().
openOutputFile()
std::unique_ptr<llvm::ToolOutputFile> mlir::openOutputFile (llvm::StringRef outputFilename, std::string * errorMessage = nullptr)
Open the file specified by its name for writing.
Write the error message to errorMessage if errors occur and errorMessage is not nullptr.
Referenced by mlir::SimpleObjectCache::dumpToObjectFile(), and runWithCrashRecovery().
operator!=() [1/6]
bool mlir::operator!= (Identifier lhs, Identifier rhs) inline
Definition at line 82 of file Identifier.h.
References mlir::Identifier::data().
operator!=() [2/6]
bool mlir::operator!= (Identifier lhs, StringRef rhs) inline
Definition at line 87 of file Identifier.h.
References mlir::Identifier::is().
operator!=() [3/6]
bool mlir::operator!= (StringRef lhs, Identifier rhs) inline
Definition at line 89 of file Identifier.h.
References mlir::Identifier::is().
operator!=() [4/6]
bool mlir::operator!= (IntInfty lhs, IntInfty rhs) inline
Definition at line 94 of file SDBM.h.
operator!=() [5/6]
bool mlir::operator!= (OperationName lhs, OperationName rhs) inline
Definition at line 245 of file OperationSupport.h.
References mlir::OperationName::getAsOpaquePointer().
operator!=() [6/6]
bool mlir::operator!= (OpState lhs, OpState rhs) inline
Definition at line 250 of file OpDefinition.h.
References mlir::OpState::getOperation().
operator*()
AffineExpr mlir::operator* (int64_t val, AffineExpr expr) inline
Definition at line 200 of file AffineExpr.h.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getBase(), mlir::ArrayAttr::kindof(), and mlir::AffineExpr::operator!().
operator+() [1/2]
IntInfty mlir::operator+ (IntInfty lhs, IntInfty rhs) inline
Definition at line 57 of file SDBM.h.
References mlir::IntInfty::getValue(), mlir::IntInfty::infty, and mlir::IntInfty::isFinite().
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getBase(), and mlir::AffineExpr::operator!().
operator+() [2/2]
AffineExpr mlir::operator+ (int64_t val, AffineExpr expr) inline
Definition at line 199 of file AffineExpr.h.
operator-()
AffineExpr mlir::operator- (int64_t val, AffineExpr expr) inline
Definition at line 201 of file AffineExpr.h.
References getAffineBinaryOpExpr(), getAffineConstantExpr(), getAffineDimExpr(), getAffineSymbolExpr(), operator<<(), and toAffineExpr().
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getBase(), mlir::AffineExpr::operator!(), mlir::SDBMExpr::operator!(), and mlir::ops_assertions::operator+().
operator<()
bool mlir::operator< (IntInfty lhs, IntInfty rhs) inline
Definition at line 82 of file SDBM.h.
References mlir::IntInfty::getValue().
Referenced by mlir::tblgen::Dialect::Dialect().
operator<<() [1/24]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, Attribute attr) inline
Definition at line 56 of file DialectImplementation.h.
References mlir::DialectAsmPrinter::printAttribute().
operator<<() [2/24]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, const APFloat & value) inline
Definition at line 61 of file DialectImplementation.h.
References mlir::DialectAsmPrinter::printFloat().
operator<<() [3/24]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, float value) inline
Definition at line 66 of file DialectImplementation.h.
operator<<() [4/24]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, double value) inline
Definition at line 69 of file DialectImplementation.h.
operator<<() [5/24]
raw_ostream& mlir::operator<< (raw_ostream & os, Identifier identifier) inline
Definition at line 73 of file Identifier.h.
References mlir::Identifier::print().
operator<<() [6/24]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, Type type) inline
Definition at line 73 of file DialectImplementation.h.
References mlir::DialectAsmPrinter::printType().
operator<<() [7/24]
template<typename T , typename std::enable_if< !std::is_convertible< T &, Attribute &>::value &&!std::is_convertible< T &, Type &>::value &&!std::is_convertible< T &, APFloat &>::value &&!llvm::is_one_of< T, double, float >::value, T >::type * = nullptr> DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, const T & other) inline
Definition at line 87 of file DialectImplementation.h.
References mlir::DialectAsmPrinter::getStream().
operator<<() [8/24]
raw_ostream& mlir::operator<< (raw_ostream & os, const Location & loc) inline
Definition at line 88 of file Location.h.
References mlir::Location::print().
operator<<() [9/24]
raw_ostream& mlir::operator<< (raw_ostream & os, Attribute attr) inline
Definition at line 122 of file Attributes.h.
References mlir::Attribute::print().
operator<<() [10/24]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, Value value) inline
Definition at line 144 of file OpImplementation.h.
References mlir::OpAsmPrinter::printOperand().
operator<<() [11/24]
template<typename T , typename std::enable_if< std::is_convertible< T &, ValueRange >::value &&!std::is_convertible< T &, Value &>::value, T >::type * = nullptr> OpAsmPrinter & mlir::operator<< (OpAsmPrinter & p, const T & values) inline
Definition at line 153 of file OpImplementation.h.
References mlir::OpAsmPrinter::printOperands().
operator<<() [12/24]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, Type type) inline
Definition at line 158 of file OpImplementation.h.
References mlir::OpAsmPrinter::printType().
operator<<() [13/24]
raw_ostream& mlir::operator<< (raw_ostream & os, const DiagnosticArgument & arg) inline
Definition at line 161 of file Diagnostics.h.
References mlir::DiagnosticArgument::print().
operator<<() [14/24]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, Attribute attr) inline
Definition at line 163 of file OpImplementation.h.
References mlir::OpAsmPrinter::getStream(), operator<<(), and mlir::OpAsmPrinter::printAttribute().
operator<<() [15/24]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, bool value) inline
Definition at line 183 of file OpImplementation.h.
operator<<() [16/24]
raw_ostream& mlir::operator<< (raw_ostream & os, Type type) inline
Definition at line 184 of file Types.h.
References mlir::Type::print().
operator<<() [17/24]
template<typename IteratorT > OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, const iterator_range< ValueTypeIterator< IteratorT >> & types) inline
Definition at line 189 of file OpImplementation.h.
References interleaveComma().
operator<<() [18/24]
raw_ostream& mlir::operator<< (raw_ostream & os, Value value) inline
Definition at line 208 of file Value.h.
References mlir::Value::print().
operator<<() [19/24]
raw_ostream& mlir::operator<< (raw_ostream & os, AffineMap map) inline
Definition at line 221 of file AffineMap.h.
References mlir::AffineMap::print().
operator<<() [20/24]
raw_ostream & mlir::operator<< (raw_ostream & os, AffineExpr & expr)
Definition at line 584 of file AffineExpr.cpp.
References mlir::AffineExpr::print().
operator<<() [21/24]
raw_ostream& mlir::operator<< (raw_ostream & os, OperationName identifier) inline
Definition at line 236 of file OperationSupport.h.
References mlir::OperationName::print().
operator<<() [22/24]
raw_ostream& mlir::operator<< (raw_ostream & os, const Diagnostic & diag) inline
Definition at line 308 of file Diagnostics.h.
References mlir::Diagnostic::print().
operator<<() [23/24]
raw_ostream & mlir::operator<< (raw_ostream & os, SubViewOp::Range & range)
Definition at line 2753 of file Ops.cpp.
References mlir::PatternRewriter::create(), mlir::detail::enumerate(), failed(), failure(), mlir::MemRefType::get(), mlir::MemRefType::getAffineMaps(), mlir::Builder::getContext(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefType::getMemorySpace(), mlir::MemRefType::getShape(), getStridesAndOffset(), mlir::OwningRewritePatternList::insert(), m_ConstantIndex(), makeStridedLinearLayoutMap(), matchPattern(), mlir::linalg::Range, mlir::PatternRewriter::replaceOpWithNewOp(), and success().
Referenced by mlir::DmaWaitOp::getNumElements(), operator-(), and operator<<().
operator<<() [24/24]
raw_ostream& mlir::operator<< (raw_ostream & os, Operation & op) inline
Definition at line 661 of file Operation.h.
References mlir::Operation::print().
operator<=()
bool mlir::operator<= (IntInfty lhs, IntInfty rhs) inline
Definition at line 86 of file SDBM.h.
References mlir::IntInfty::getValue().
operator==() [1/6]
bool mlir::operator== (Identifier lhs, Identifier rhs) inline
Definition at line 78 of file Identifier.h.
References mlir::Identifier::data().
operator==() [2/6]
bool mlir::operator== (Identifier lhs, StringRef rhs) inline
Definition at line 86 of file Identifier.h.
References mlir::Identifier::is().
operator==() [3/6]
bool mlir::operator== (StringRef lhs, Identifier rhs) inline
Definition at line 88 of file Identifier.h.
References mlir::Identifier::is().
operator==() [4/6]
bool mlir::operator== (IntInfty lhs, IntInfty rhs) inline
Definition at line 90 of file SDBM.h.
References mlir::IntInfty::getValue().
Referenced by mlir::tblgen::Dialect::Dialect(), and mlir::AffineExpr::operator!=().
operator==() [5/6]
bool mlir::operator== (OperationName lhs, OperationName rhs) inline
Definition at line 241 of file OperationSupport.h.
References mlir::OperationName::getAsOpaquePointer().
operator==() [6/6]
bool mlir::operator== (OpState lhs, OpState rhs) inline
Definition at line 247 of file OpDefinition.h.
References mlir::OpState::getOperation().
parseAttribute() [1/4]
Attribute mlir::parseAttribute (llvm::StringRef attrStr, MLIRContext * context)
This parses a single MLIR attribute to an MLIR context if it was valid.
If not, an error message is emitted through a new SourceMgrDiagnosticHandler constructed from a new SourceMgr with a single a MemoryBuffer wrapping attrStr. If the passed attrStr has additional tokens that were not part of the type, an error is emitted.
Referenced by buildHexadecimalFloatLiteral(), extractSymbolReference(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), mlir::DialectAsmParser::parseKeyword(), and parseSymbol().
parseAttribute() [2/4]
Attribute mlir::parseAttribute (llvm::StringRef attrStr, Type type)
parseAttribute() [3/4]
Attribute mlir::parseAttribute (llvm::StringRef attrStr, MLIRContext * context, size_t & numRead)
This parses a single MLIR attribute to an MLIR context if it was valid.
If not, an error message is emitted through a new SourceMgrDiagnosticHandler constructed from a new SourceMgr with a single a MemoryBuffer wrapping attrStr. The number of characters of attrStr parsed in the process is returned in numRead.
parseAttribute() [4/4]
Attribute mlir::parseAttribute (llvm::StringRef attrStr, Type type, size_t & numRead)
parseDimAndSymbolList()
ParseResult mlir::parseDimAndSymbolList (OpAsmParser & parser, SmallVectorImpl< Value > & operands, unsigned & numDims)
Parses dimension and symbol list and returns true if parsing failed.
Definition at line 177 of file Ops.cpp.
References failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OpAsmParser::OptionalSquare, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperands(), and success().
Referenced by mlir::DmaWaitOp::getNumElements(), mlir::AffineApplyOp::parse(), parseAffineIfOp(), parseAllocOp(), and parseBound().
parsePassPipeline()
LogicalResult mlir::parsePassPipeline (StringRef pipeline, OpPassManager & pm, raw_ostream & errorStream = llvm::errs())
This function parses the textual representation of a pass pipeline, and adds the result to 'pm' on success.
This function returns failure if the given pipeline was invalid. 'errorStream' is the output stream used to emit errors found during parsing.
This function returns failure if the given pipeline was invalid. 'errorStream' is an optional parameter that, if non-null, will be used to emit errors found during parsing.
Definition at line 377 of file PassRegistry.cpp.
References failed(), failure(), options, and success().
Referenced by mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration().
parseSourceFile() [1/3]
OwningModuleRef mlir::parseSourceFile (const llvm::SourceMgr & sourceMgr, MLIRContext * context)
This parses the file specified by the indicated SourceMgr and returns an MLIR module if it was valid.
If not, the error message is emitted through the error handler registered in the context, and a null pointer is returned.
If not, it emits diagnostics and returns null.
Definition at line 4761 of file Parser.cpp.
References mlir::ModuleOp::create(), emitError(), failed(), mlir::FileLineColLoc::get(), mlir::UnknownLoc::get(), parseSourceString(), and verify().
Referenced by parseMLIRInput(), performActions(), roundTripModule(), and mlir::TranslationParser::TranslationParser().
parseSourceFile() [2/3]
OwningModuleRef mlir::parseSourceFile (llvm::StringRef filename, MLIRContext * context)
This parses the file specified by the indicated filename and returns an MLIR module if it was valid.
If not, the error message is emitted through the error handler registered in the context, and a null pointer is returned.
parseSourceFile() [3/3]
OwningModuleRef mlir::parseSourceFile (llvm::StringRef filename, llvm::SourceMgr & sourceMgr, MLIRContext * context)
This parses the file specified by the indicated filename using the provided SourceMgr and returns an MLIR module if it was valid.
If not, the error message is emitted through the error handler registered in the context, and a null pointer is returned.
parseSourceString()
OwningModuleRef mlir::parseSourceString (llvm::StringRef moduleStr, MLIRContext * context)
This parses the module string to a MLIR module if it was valid.
If not, the error message is emitted through the error handler registered in the context, and a null pointer is returned.
Referenced by parseSourceFile().
parseType() [1/2]
Type mlir::parseType (llvm::StringRef typeStr, MLIRContext * context)
This parses a single MLIR type to an MLIR context if it was valid.
If not, an error message is emitted through a new SourceMgrDiagnosticHandler constructed from a new SourceMgr with a single a MemoryBuffer wrapping typeStr. If the passed typeStr has additional tokens that were not part of the type, an error is emitted.
Referenced by buildHexadecimalFloatLiteral(), extractSymbolReference(), mlir::spirv::SPIRVDialect::getDialectNamespace(), mlir::LLVM::LLVMDialect::getDialectNamespace(), mlirParseType(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseRegionArgumentList(), parseSymbol(), mlir::LLVM::LLVMDialect::parseType(), and mlir::DialectAsmParser::parseType().
parseType() [2/2]
Type mlir::parseType (llvm::StringRef typeStr, MLIRContext * context, size_t & numRead)
This parses a single MLIR type to an MLIR context if it was valid.
If not, an error message is emitted through a new SourceMgrDiagnosticHandler constructed from a new SourceMgr with a single a MemoryBuffer wrapping typeStr. The number of characters of typeStr parsed in the process is returned in numRead.
populateAffineToStdConversionPatterns()
void mlir::populateAffineToStdConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Collect a set of patterns to convert from the Affine dialect to the Standard dialect, in particular convert structured affine control flow into CFG branch-based control flow.
Definition at line 542 of file AffineToStandard.cpp.
References mlir::ConversionTarget::addLegalDialect(), applyPartialConversion(), failed(), and mlir::OwningRewritePatternList::insert().
Referenced by populateLinalgToLLVMConversionPatterns().
populateBuiltinFuncToSPIRVPatterns()
void mlir::populateBuiltinFuncToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Appends to a pattern list additional patterns for translating the builtin func op to the SPIR-V dialect.
These patterns do not handle shader interface/ABI; they convert function parameters to be of SPIR-V allowed types.
Definition at line 214 of file SPIRVLowering.cpp.
References mlir::OwningRewritePatternList::insert().
populateFuncOpTypeConversionPattern()
void mlir::populateFuncOpTypeConversionPattern (OwningRewritePatternList & patterns, MLIRContext * ctx, TypeConverter & converter)
Add a pattern to the given pattern list to convert the signature of a FuncOp with the given type converter.
Definition at line 1653 of file DialectConversion.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by mlir::OpConversionPattern< SourceOp >::matchAndRewrite().
populateGpuRewritePatterns()
void mlir::populateGpuRewritePatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Collect a set of patterns to rewrite ops within the GPU dialect.
Definition at line 370 of file AllReduceLowering.cpp.
References mlir::OwningRewritePatternList::insert().
populateGpuToNVVMConversionPatterns()
void mlir::populateGpuToNVVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the GPU dialect to NVVM.
Definition at line 727 of file LowerGpuOpsToNVVMOps.cpp.
References mlir::Dialect::getContext(), mlir::LLVMTypeConverter::getDialect(), and mlir::OwningRewritePatternList::insert().
populateGPUToSPIRVPatterns()
void mlir::populateGPUToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, OwningRewritePatternList & patterns, ArrayRef< int64_t > workGroupSize)
Appends to a pattern list additional patterns for translating GPU Ops to SPIR-V ops.
Needs the workgroup size as input since SPIR-V/Vulkan requires the workgroup size to be statically specified.
Definition at line 397 of file ConvertGPUToSPIRV.cpp.
References mlir::OwningRewritePatternList::insert().
populateLinalgToLLVMConversionPatterns()
void mlir::populateLinalgToLLVMConversionPatterns (LinalgTypeConverter & converter, OwningRewritePatternList & patterns, MLIRContext * ctx)
Populate the given list with patterns that convert from Linalg to LLVM.
Definition at line 559 of file LinalgToLLVM.cpp.
References mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::ConversionTarget::addLegalDialect(), mlir::ConversionTarget::addLegalOp(), applyFullConversion(), failed(), mlir::OwningRewritePatternList::insert(), mlir::TypeConverter::isSignatureLegal(), populateAffineToStdConversionPatterns(), populateLoopToStdConversionPatterns(), populateStdToLLVMConversionPatterns(), and populateVectorToLLVMConversionPatterns().
populateLoopToStdConversionPatterns()
void mlir::populateLoopToStdConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Collect a set of patterns to lower from loop.for, loop.if, and loop.terminator to CFG operations within the Standard dialect, in particular convert structured control flow into CFG branch-based control flow.
Definition at line 249 of file ConvertLoopToStandard.cpp.
References mlir::ConversionTarget::addLegalDialect(), applyPartialConversion(), failed(), and mlir::OwningRewritePatternList::insert().
Referenced by makeStandardToLLVMTypeConverter(), and populateLinalgToLLVMConversionPatterns().
populateStandardToSPIRVPatterns()
void mlir::populateStandardToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Appends to a pattern list additional patterns for translating StandardOps to SPIR-V ops.
Also adds the patterns legalize ops not directly translated to SPIR-V dialect.
Definition at line 392 of file ConvertStandardToSPIRV.cpp.
References mlir::OwningRewritePatternList::insert().
populateStdLegalizationPatternsForSPIRVLowering()
void mlir::populateStdLegalizationPatternsForSPIRVLowering (MLIRContext * context, OwningRewritePatternList & patterns)
Appends to a pattern list patterns to legalize ops that are not directly lowered to SPIR-V.
Definition at line 153 of file LegalizeStandardForSPIRV.cpp.
References applyPatternsGreedily(), and mlir::OwningRewritePatternList::insert().
populateStdToLLVMConversionPatterns()
void mlir::populateStdToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the Standard dialect to LLVM.
Definition at line 2142 of file ConvertStandardToLLVM.cpp.
References populateStdToLLVMMemoryConversionPatters(), and populateStdToLLVMNonMemoryConversionPatterns().
Referenced by createLowerToLLVMPass(), makeStandardToLLVMTypeConverter(), populateLinalgToLLVMConversionPatterns(), and populateVectorToLLVMConversionPatterns().
populateStdToLLVMMemoryConversionPatters()
void mlir::populateStdToLLVMMemoryConversionPatters (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert memory-related operations from the Standard dialect to the LLVM dialect, excluding the memory-related operations.
Definition at line 2124 of file ConvertStandardToLLVM.cpp.
References clUseAlloca(), mlir::LLVMTypeConverter::getDialect(), and mlir::OwningRewritePatternList::insert().
Referenced by populateStdToLLVMConversionPatterns().
populateStdToLLVMNonMemoryConversionPatterns()
void mlir::populateStdToLLVMNonMemoryConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the Standard dialect to the LLVM dialect, excluding the memory-related operations.
Collect a set of patterns to convert from the Standard dialect to LLVM.
Definition at line 2069 of file ConvertStandardToLLVM.cpp.
References mlir::LLVMTypeConverter::getDialect(), and mlir::OwningRewritePatternList::insert().
Referenced by populateStdToLLVMConversionPatterns().
populateVectorToAffineLoopsConversionPatterns()
void mlir::populateVectorToAffineLoopsConversionPatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the Vector dialect to loops + std.
Definition at line 354 of file ConvertVectorToLoops.cpp.
References mlir::OwningRewritePatternList::insert().
populateVectorToLLVMConversionPatterns()
void mlir::populateVectorToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the Vector dialect to LLVM.
Populate the given list with patterns that convert from Vector to LLVM.
Definition at line 955 of file ConvertVectorToLLVM.cpp.
References mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::ConversionTarget::addLegalDialect(), applyPartialConversion(), applyPatternsGreedily(), failed(), mlir::Dialect::getContext(), mlir::LLVMTypeConverter::getDialect(), mlir::OwningRewritePatternList::insert(), mlir::TypeConverter::isSignatureLegal(), populateStdToLLVMConversionPatterns(), and mlir::vector::populateVectorSlicesLoweringPatterns().
Referenced by populateLinalgToLLVMConversionPatterns().
populateVectorToVectorConversionPatterns()
void mlir::populateVectorToVectorConversionPatterns (MLIRContext * context, OwningRewritePatternList & patterns, ArrayRef< int64_t > coarseVectorShape = {}, ArrayRef< int64_t > fineVectorShape = {})
Collect a set of patterns to convert from the Vector dialect to itself.
Should be merged with populateVectorToAffineLoopsConversionPatterns.
printDimAndSymbolList()
void mlir::printDimAndSymbolList (Operation::operand_iterator begin, Operation::operand_iterator end, unsigned numDims, OpAsmPrinter & p)
Prints dimension and symbol list.
Definition at line 165 of file Ops.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), and mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front().
Referenced by mlir::DmaWaitOp::getNumElements(), mlir::AffineApplyOp::print(), print(), and printBound().
promoteIfSingleIteration()
LogicalResult mlir::promoteIfSingleIteration (AffineForOp forOp)
Promotes the loop body of a AffineForOp to its containing block if the AffineForOp was known to have a single iteration.
Promotes the loop body of a forOp to its containing block if the forOp was known to have a single iteration.
Definition at line 110 of file LoopUtils.cpp.
References mlir::OpBuilder::create(), failure(), mlir::Operation::getBlock(), getConstantTripCount(), mlir::Operation::getLoc(), mlir::AffineBound::getMap(), mlir::Block::getOperations(), mlir::Operation::getParentOfType(), mlir::AffineBound::operand_begin(), mlir::AffineBound::operand_end(), and success().
Referenced by createAffineDataCopyGenerationPass(), generateLoop(), isFusionProfitable(), loopUnrollByFactor(), loopUnrollFull(), loopUnrollJamByFactor(), and promoteSingleIterationLoops().
promoteSingleIterationLoops()
void mlir::promoteSingleIterationLoops (FuncOp f)
Promotes all single iteration AffineForOp's in the Function, i.e., moves their body into the containing Block.
Promotes all single iteration for op's in the FuncOp, i.e., moves their body into the containing Block.
Definition at line 154 of file LoopUtils.cpp.
References promoteIfSingleIteration(), and mlir::OpState::walk().
promoteToWorkgroupMemory()
void mlir::promoteToWorkgroupMemory (gpu::GPUFuncOp op, unsigned arg)
Promotes a function argument to workgroup memory in the given function.
The copies will be inserted in the beginning and in the end of the function.
Referenced by insertCopies().
registerAllDialects()
void mlir::registerAllDialects (MLIRContext * context)
Registers all dialects with the specified MLIRContext.
Registers all dialects and their const folding hooks with the specified MLIRContext.
Definition at line 57 of file Dialect.cpp.
References dialectHooksRegistry, and dialectRegistry.
Referenced by mlir::MLIRContext::MLIRContext().
registerDialect()
template<typename ConcreteDialect > void mlir::registerDialect ()
Utility to register a dialect.
Client can register their dialect with the global registry by calling registerDialect<MyDialect>();
Definition at line 295 of file Dialect.h.
References registerDialect(), and registerDialectAllocator().
Referenced by mlir::Dialect::addInterfaces(), and registerDialect().
registerDialectAllocator()
void mlir::registerDialectAllocator (const DialectAllocatorFunction & function)
Registers a specific dialect creation function with the system, typically used through the DialectRegistration template.
Definition at line 39 of file Dialect.cpp.
References dialectRegistry.
Referenced by registerDialect().
registerDialectHooksSetter()
void mlir::registerDialectHooksSetter (const DialectHooksSetter & function)
Registers a function that will set hooks in the registered dialects based on information coming from DialectHooksRegistration.
Registers a function to set specific hooks for a specific dialect, typically used through the DialectHooksRegistration template.
Definition at line 47 of file Dialect.cpp.
References dialectHooksRegistry.
Referenced by mlir::DialectHooksRegistration< ConcreteHooks >::DialectHooksRegistration(), and mlir::DialectHooks::getExtractElementHook().
registerPass()
void mlir::registerPass (StringRef arg, StringRef description, const PassID * passID, const PassAllocatorFunction & function)
Register a specific dialect pass allocator function with the system, typically used through the PassRegistration template.
Definition at line 58 of file PassRegistry.cpp.
References passRegistry.
Referenced by mlir::PassRegistration< ConcretePass >::PassRegistration().
registerPassManagerCLOptions()
void mlir::registerPassManagerCLOptions ()
Register a set of useful command-line options that can be used to configure a pass manager.
The values of these options can be applied via the 'applyPassManagerCLOptions' method below.
Definition at line 147 of file PassManagerOptions.cpp.
Referenced by mlir::PassManager::IRPrinterConfig::shouldPrintAfterOnlyOnChange().
registerPassPipeline()
void mlir::registerPassPipeline (StringRef arg, StringRef description, const PassRegistryFunction & function)
Register a specific dialect pipeline registry function with the system, typically used through the PassPipelineRegistration template.
Definition at line 42 of file PassRegistry.cpp.
References passPipelineRegistry.
Referenced by mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), and mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration().
replaceAllMemRefUsesWith() [1/2]
LogicalResult mlir::replaceAllMemRefUsesWith (Value oldMemRef, Value newMemRef, ArrayRef< Value > extraIndices = {}, AffineMap indexRemap = AffineMap(), ArrayRef< Value > extraOperands = {}, ArrayRef< Value > symbolOperands = {}, Operation * domInstFilter = nullptr, Operation * postDomInstFilter = nullptr)
Replaces all "dereferencing" uses of oldMemRef with newMemRef while optionally remapping the old memref's indices using the supplied affine map, indexRemap.
The new memref could be of a different shape or rank. extraIndices provides any additional access indices to be added to the start.
indexRemap remaps indices of the old memref access to a new set of indices that are used to index the memref. Additional input operands to indexRemap can be optionally provided in extraOperands, and they occupy the start of its input list. indexRemap's dimensional inputs are expected to correspond to memref's indices, and its symbolic inputs if any should be provided in symbolOperands.
domInstFilter, if non-null, restricts the replacement to only those operations that are dominated by the former; similarly, postDomInstFilter restricts replacement to only those operations that are postdominated by it.
Returns true on success and false if the replacement is not possible, whenever a memref is used as an operand in a non-dereferencing context, except for dealloc's on the memref which are left untouched. See comments at function definition for an example.
Definition at line 218 of file Utils.cpp.
References mlir::Type::cast(), failed(), failure(), getElementType(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getParentOfType(), mlir::Value::getType(), mlir::Value::getUsers(), isMemRefDereferencingOp(), and success().
Referenced by createPrivateMemRef(), doubleBuffer(), generateCopy(), and normalizeMemRef().
replaceAllMemRefUsesWith() [2/2]
LogicalResult mlir::replaceAllMemRefUsesWith (Value oldMemRef, Value newMemRef, Operation * op, ArrayRef< Value > extraIndices = {}, AffineMap indexRemap = AffineMap(), ArrayRef< Value > extraOperands = {}, ArrayRef< Value > symbolOperands = {})
Performs the same replacement as the other version above but only for the dereferencing uses of oldMemRef in op.
Definition at line 49 of file Utils.cpp.
References canonicalizeMapAndOperands(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOperation(), mlir::detail::enumerate(), mlir::Operation::erase(), failure(), fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::AffineMapAttr::get(), getAffineMapAttrForMemRef(), mlir::Operation::getAttrs(), getElementType(), mlir::Operation::getLoc(), mlir::Builder::getMultiDimIdentityMap(), mlir::Operation::getName(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::Operation::getNumOperands(), mlir::AffineMap::getNumResults(), mlir::Operation::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getOperands(), mlir::AffineMap::getResults(), mlir::Operation::getResults(), mlir::Value::getType(), mlir::Operation::hasResizableOperandsList(), isMemRefDereferencingOp(), isValidDim(), isValidSymbol(), mlir::Operation::operand_begin(), mlir::Operation::operand_end(), mlir::Operation::replaceAllUsesWith(), mlir::OperationState::setOperandListToResizable(), simplifyAffineMap(), and success().
replaceAllUsesInRegionWith()
void mlir::replaceAllUsesInRegionWith (Value orig, Value replacement, Region & region)
Replace all uses of orig within the given region with replacement.
Definition at line 21 of file RegionUtils.cpp.
References mlir::Value::getUses(), and mlir::Region::isAncestor().
Referenced by areValuesDefinedAbove(), coalesceLoops(), createLaunchFromOp(), and stripmineSink().
shapeRatio() [1/2]
Optional< SmallVector< int64_t, 4 > > mlir::shapeRatio (ArrayRef< int64_t > superShape, ArrayRef< int64_t > subShape)
Computes and returns the multi-dimensional ratio of superShape to subShape.
This is calculated by performing a traversal from minor to major dimensions (i.e. in reverse shape order). If integral division is not possible, returns None. The ArrayRefs are assumed (and enforced) to only contain > 1 values. This constraint comes from the fact that they are meant to be used with VectorTypes, for which the property holds by construction.
Examples:
shapeRatio({3, 4, 5, 8}, {2, 5, 2}) returns {3, 2, 1, 4}
shapeRatio({3, 4, 4, 8}, {2, 5, 2}) returns None
shapeRatio({1, 2, 10, 32}, {2, 5, 2}) returns {1, 1, 2, 16}
Definition at line 33 of file VectorAnalysis.cpp.
References mlir::StandardTypes::None, and mlir::functional::zipApply().
Referenced by generateExtractSlicesOpResultType(), generateTransferOpSlices(), getEnclosingforOps(), initUnrolledVectorState(), shapeRatio(), and unrollSingleResultStructuredOp().
shapeRatio() [2/2]
Optional< SmallVector< int64_t, 4 > > mlir::shapeRatio (VectorType superVectorType, VectorType subVectorType)
Computes and returns the multi-dimensional ratio of the shapes of superVector to subVector.
If integral division is not possible, returns None. Assumes and enforces that the VectorTypes have the same elemental type.
Definition at line 73 of file VectorAnalysis.cpp.
References mlir::VectorType::getShape(), and shapeRatio().
simplifyAffineExpr()
AffineExpr mlir::simplifyAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols)
Simplify an affine expression by flattening and some amount of simple analysis.
Simplify the affine expression by flattening it and reconstructing it.
This has complexity linear in the number of nodes in 'expr'. Returns the simplified expression, which is the same as the input expression if it can't be simplified.
Definition at line 839 of file AffineExpr.cpp.
References mlir::AffineExpr::getContext(), mlir::AffineExpr::isPureAffine(), mlir::SimpleAffineExprFlattener::localExprs, mlir::SimpleAffineExprFlattener::operandExprStack, toAffineExpr(), and mlir::AffineExprVisitor< SubClass, RetTy >::walkPostOrder().
Referenced by canonicalizeStridedLayout(), mlir::AffineExpr::cast(), createPrivateMemRef(), getConstDifference(), mlir::FlatAffineConstraints::getSliceBounds(), getStridesAndOffset(), mlir::edsc::ops::linalg_conv_nhwc(), mlir::edsc::ops::linalg_dilated_conv_nhwc(), makeCanonicalStridedLayoutExpr(), mlir::FlatAffineConstraints::setIdValues(), mlir::MutableAffineMap::simplify(), and simplifyAffineMap().
simplifyAffineMap()
AffineMap mlir::simplifyAffineMap (AffineMap map)
Simplify an affine map by simplifying its underlying AffineExpr results.
Definition at line 280 of file AffineMap.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and simplifyAffineExpr().
Referenced by mlir::FlatAffineConstraints::addLowerOrUpperBound(), mlir::AffineApplyNormalizer::AffineApplyNormalizer(), mlir::AffineValueMap::difference(), mlir::MemRefAccess::getAccessMap(), getCleanupLoopLowerBound(), hash_value(), and replaceAllMemRefUsesWith().
simplifyRegions()
LogicalResult mlir::simplifyRegions (MutableArrayRef< Region > regions)
Run a set of structural simplifications over the given regions.
This includes transformations like unreachable block elimination, dead argument elimination, as well as some other DCE. This function returns success if any of the regions were simplified, failure otherwise.
Definition at line 342 of file RegionUtils.cpp.
References eraseUnreachableBlocks(), runRegionDCE(), succeeded(), and success().
Referenced by areValuesDefinedAbove().
sinkLoop()
void mlir::sinkLoop (AffineForOp forOp, unsigned loopDepth)
Sinks 'forOp' by 'loopDepth' levels by performing a series of loop interchanges.
Performs a series of loop interchanges to sink 'forOp' 'loopDepth' levels deeper in the loop nest.
Requires that 'forOp' is part of a perfect nest with 'loopDepth' AffineForOps consecutively nested under it.
Definition at line 646 of file LoopUtils.cpp.
References interchangeLoops().
Referenced by interchangeLoops().
sinkSequentialLoops()
AffineForOp mlir::sinkSequentialLoops (AffineForOp forOp)
Definition at line 592 of file LoopUtils.cpp.
References checkLoopInterchangeDependences(), getDependenceComponents(), getPerfectlyNestedLoops(), interchangeLoops(), mlir::matcher::isParallelLoop(), mlir::DependenceComponent::lb, and mlir::DependenceComponent::ub.
Referenced by isFusionProfitable(), and sinkSequentialLoops().
splitAndProcessBuffer()
LogicalResult mlir::splitAndProcessBuffer (std::unique_ptr< llvm::MemoryBuffer > originalBuffer, ChunkBufferHandler processChunkBuffer, raw_ostream & os)
Splits the specified buffer on a marker (// -----), processes each chunk independently according to the normal processChunkBuffer logic, and writes all results to os.
This is used to allow a large number of small independent tests to be put into a single file.
Definition at line 21 of file ToolUtilities.cpp.
References failed(), and failure().
Referenced by processBuffer().
succeeded()
bool mlir::succeeded (LogicalResult result) inline
Utility function that returns true if the provided LogicalResult corresponds to a success value.
Definition at line 39 of file LogicalResult.h.
References mlir::LogicalResult::Success, and mlir::LogicalResult::value.
Referenced by affineDataCopyGenerate(), canonicalizeLoopBounds(), mlir::MemRefRegion::compute(), computeReshapeCollapsedType(), mlir::OpBuilder::createOrFold(), createPrivateMemRef(), deleteDeadness(), mlir::detail::DiagnosticEngineImpl::emit(), extractStrides(), mlir::AffineLoadOp::fold(), mlir::Operation::fold(), foldLoopBounds(), generateLoop(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::get(), mlir::ComputationSliceState::getAsConstraints(), getLastStructuredControlFlowOpMergeBlock(), getNewNumDimsSymbols(), getStridesAndOffset(), inferSubViewResultType(), inlineSCC(), isFnEntryBlock(), mlir::TypeConverter::isLegal(), isStrided(), mlir::detail::constant_op_binder< AttrT >::match(), mlir::ConversionPattern::matchAndRewrite(), mlir::detail::ConversionPatternRewriterImpl::notifyRegionWasClonedBefore(), parseAnyType(), parseArgumentList(), parseArrayType(), parseAttributions(), parseBranchConditionalOp(), parseFunctionResultList(), mlir::impl::parseFunctionSignature(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGroupNonUniformIAddOp(), parseOptionalKeywordAlternative(), parseSpecConstantOp(), parseStructMemberDecorations(), parseStructType(), parseUniformType(), parseVariableDecorations(), parseVariableOp(), mlir::linalg::permuteGenericLinalgOp(), print(), mlir::linalg::promoteSubviewsLinalgOp(), runWithCrashRecovery(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), simplifyRegions(), tryIsolateBands(), tryRewriteAffineMulEwSigned(), mlir::linalg::vectorizeLinalgOp(), verify(), and walkSymbolScopes().
success()
LogicalResult mlir::success (bool isSuccess = true) inline
Utility function to generate a LogicalResult.
If isSuccess is true a success result is generated, otherwise a 'failure' result is generated.
Definition at line 25 of file LogicalResult.h.
References mlir::LogicalResult::Failure, and mlir::LogicalResult::Success.
Referenced by mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), addMemRefAccessConstraints(), addMissingLoopIVBounds(), mlir::FlatAffineConstraints::addSliceBounds(), mlir::PassPipelineCLParser::addToPipeline(), mlir::OpAsmParser::addTypesToList(), mlir::OpAsmParser::addTypeToList(), analyzeProfitability(), boundCheckLoadOrStoreOp(), buildHexadecimalFloatLiteral(), canonicalizeLoopBounds(), checkLoopNestMappable(), checkLoopNestMappableImpl(), checkLoopOpMappable(), checkTensorElementType(), collectValidReferencesFor(), compileAndExecute(), compileAndExecuteSingleFloatReturnFunction(), mlir::FlatAffineConstraints::composeMap(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::MemRefRegion::compute(), computeConversionSet(), computeSliceUnion(), mlir::AffineMap::constantFold(), mlir::FlatAffineConstraints::constantFoldId(), mlir::detail::ConversionPatternRewriterImpl::convertBlockSignature(), convertLoopNestToGPULaunch(), mlir::LLVM::ModuleTranslation::convertOperation(), mlir::TypeConverter::convertSignatureArg(), mlir::TypeConverter::convertType(), mlir::TypeConverter::convertTypes(), createAffineDataCopyGenerationPass(), createLaunchBody(), createLaunchFromOp(), deleteDeadness(), emitLoopRanges(), encodeInstructionInto(), mlir::spirv::encodeStringLiteralInto(), eraseUnreachableBlocks(), extractStrides(), extractSymbolReference(), extractValueFromConstOp(), mlir::Operation::fold(), mlir::FoldingHook< ConcreteType, isSingleResult, typename std::enable_if< isSingleResult >::type >::foldHook(), foldLoopBounds(), foldMemRefCast(), generateCopy(), mlir::ComputationSliceState::getAsConstraints(), mlir::DialectAsmParser::getCurrentLocation(), mlir::OpAsmParser::getCurrentLocation(), getFlattenedAffineExprs(), getFlattenedAffineExprs(), mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >::getFromOpaquePointer(), getI64SubArray(), getICmpPredicate(), getIndexSet(), getInterfaceVariables(), getLastStructuredControlFlowOpMergeBlock(), getOrInsertBuiltinVariable(), getStridesAndOffset(), hoistOpsBetween(), mlir::detail::inferReturnTensorTypes(), inlineCall(), inlineCallsInSCC(), inlineRegion(), instBodySkew(), mlir::ExecutionEngine::invoke(), isFnEntryBlock(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), isIntegerArrayAttrSmallerThanShape(), isSumOfIntegerArrayAttrConfinedToShape(), isValidExtractOrInsertSlicesType(), loopUnrollByFactor(), loopUnrollJamByFactor(), lowerEntryPointABIAttr(), mlir::ConversionPattern::matchAndRewrite(), normalizeMemRef(), mlir::OperationFolder::notifyRemoval(), operator<<(), mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl(), mlir::ModuleOp::parse(), mlir::AffineApplyOp::parse(), mlir::DmaStartOp::parse(), mlir::AffineDmaStartOp::parse(), mlir::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAddressOfOp(), parseAffineForOp(), parseAffineIfOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAllocOp(), parseArgumentList(), parseAtomicBinOp(), parseAtomicCmpXchgOp(), parseAtomicOrdering(), parseAtomicRMWOp(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), parseAttributions(), parseBitFieldExtractOp(), parseBitFieldInsertOp(), parseBound(), parseBranchConditionalOp(), parseBranchOp(), parseBrOp(), parseCallOp(), parseCmpFOp(), parseCmpIOp(), parseCmpOp(), mlir::OpAsmParser::parseColonType(), parseCompositeExtractOp(), parseCondBranchOp(), parseCondBrOp(), parseConstantOp(), parseContractionOp(), parseDimAndSymbolList(), parseEntryPointOp(), parseEnumAttribute(), parseExecutionModeOp(), parseExtractElementOp(), parseExtractValueOp(), parseForOp(), mlir::detail::PassOptions::parseFromString(), parseFunctionResultList(), mlir::impl::parseFunctionSignature(), parseGEPOp(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUModuleOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), mlir::DialectAsmParser::parseKeyword(), mlir::OpAsmParser::parseKeyword(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseMemoryAccessAttributes(), parseModuleOp(), parseNoIOOp(), parseNVVMSpecialRegisterOp(), mlir::DialectAsmParser::parseOptionalInteger(), parseOptionalLinkageKeyword(), parseParallelOp(), parsePassPipeline(), parsePrefetchOp(), parseQuantParams(), parseReduceOp(), parseReduceReturnOp(), parseReturnOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSpecConstantOp(), parseStorageRange(), parseStoreOp(), parseStructMemberDecorations(), parseSymbol(), mlir::OpAsmParser::parseSymbolName(), parseTransposeOp(), parseTupleGetOp(), mlir::DialectAsmParser::parseType(), parseUnaryOp(), parseUndefOp(), parseVariableDecorations(), parseVariableOp(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration(), performActions(), mlir::linalg::permuteGenericLinalgOpPrecondition(), populatePassManagers(), mlir::detail::PassOptions::print(), print(), printGPUFuncOp(), printLLVMFuncOp(), printMLIROutput(), promoteIfSingleIteration(), mlir::linalg::promoteSubviewsLinalgOpPrecondition(), mlir::DiagnosticEngine::registerHandler(), replaceAllMemRefUsesWith(), replaceAllSymbolUsesImpl(), mlir::OpAsmParser::resolveOperands(), resolveSourceIndices(), roundTripModule(), mlir::OpPassManager::run(), runWithCrashRecovery(), serializeModule(), mlir::FlatAffineConstraints::setIdValues(), simplifyRegions(), mlir::linalg::tileAndFuseLinalgOpAndSetMarker(), tileCodeGen(), mlir::linalg::tileLinalgOpAndSetMarker(), topologicalSort(), translateModuleToLLVMIR(), translateModuleToNVVMIR(), translateModuleToROCDLIR(), mlir::OpBuilder::tryFold(), tryIsolateBands(), tryRewriteAffineAddEwIsomorphicSigned(), tryRewriteAffineMulEwSigned(), mlir::OperationFolder::tryToFold(), mlir::FlatAffineConstraints::unionBoundingBox(), validateTypeConversion(), vectorizeAffineForOp(), mlir::linalg::vectorizeLinalgOpPrecondition(), vectorizeLoopsAndLoadsRecursively(), vectorizeNonTerminals(), vectorizeOneOperation(), vectorizeRootMatch(), vectorizeRootOrTerminal(), mlir::ModuleOp::verify(), mlir::FuncOp::verify(), mlir::AffineApplyOp::verify(), mlir::OpState::verify(), mlir::DmaStartOp::verify(), mlir::AffineDmaStartOp::verify(), mlir::AffineDmaWaitOp::verify(), mlir::AffineLoadOp::verify(), mlir::AffineStoreOp::verify(), verify(), verifyAllReduce(), mlir::OpTrait::impl::verifyAtLeastNOperands(), mlir::OpTrait::impl::verifyAtLeastNResults(), verifyAtomicUpdateOp(), verifyAttributions(), verifyBitFieldExtractOp(), verifyBlockArgs(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyBody(), verifyCastOp(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), verifyCompatibleShape(), mlir::quant::QuantizedType::verifyConstructionInvariants(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT >::verifyConstructionInvariants(), mlir::IntegerType::verifyConstructionInvariants(), mlir::ComplexType::verifyConstructionInvariants(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::OpaqueType::verifyConstructionInvariants(), mlir::VectorType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), mlir::OpaqueAttr::verifyConstructionInvariants(), mlir::UnrankedMemRefType::verifyConstructionInvariants(), verifyDimAndSymbolIdentifiers(), verifyDynamicStrides(), verifyFloatTypeInvariants(), verifyFuncArgs(), verifyFuncArgsGeneric(), verifyGenericOp(), verifyIndexOp(), mlir::detail::verifyInferredResultTypes(), mlir::OpTrait::impl::verifyIsTerminator(), verifyLoadStorePtrAndValTypes(), verifyMemoryAccessAttribute(), verifyMemorySemantics(), mlir::OpTrait::impl::verifyNOperands(), mlir::OpTrait::impl::verifyNResults(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOneResult(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreIntegerLike(), mlir::spirv::SPIRVDialect::verifyOperationAttribute(), mlir::gpu::GPUDialect::verifyOperationAttribute(), mlir::Dialect::verifyOperationAttribute(), verifyPermutationMap(), mlir::Dialect::verifyRegionArgAttribute(), mlir::LLVM::LLVMDialect::verifyRegionArgAttribute(), verifyRegionAttribute(), mlir::Dialect::verifyRegionResultAttribute(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreIntegerLike(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyShiftOp(), verifyShuffleOp(), verifyStrideOrDilation(), verifySuccessor(), mlir::OpTrait::impl::verifySymbol(), mlir::OpTrait::impl::verifySymbolTable(), verifyTerminatorSuccessors(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait(), mlir::OpTrait::TraitBase< ConcreteType, NResults< N >::Impl >::verifyTrait(), mlir::OpTrait::IsIsolatedFromAbove< ConcreteType >::verifyTrait(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait(), mlir::OpTrait::HasParent< ParentOpType >::Impl< ConcreteType >::verifyTrait(), verifyTransferOp(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyType(), verifyValueSizeAttr(), verifyYield(), mlir::OpTrait::impl::verifyZeroOperands(), mlir::OpTrait::impl::verifyZeroResult(), and visitInPrettyBlockOrder().
tile() [1/4]
SmallVector< SmallVector< AffineForOp, 8 >, 8 > mlir::tile (ArrayRef< AffineForOp > forOps, ArrayRef< uint64_t > sizes, ArrayRef< AffineForOp > targets)
Definition at line 786 of file LoopUtils.cpp.
References tileImpl().
Referenced by extractFixedOuterLoops(), tileImpl(), and tilePerfectlyNested().
tile() [2/4]
SmallVector< Loops, 8 > mlir::tile (ArrayRef< loop::ForOp > forOps, ArrayRef< Value > sizes, ArrayRef< loop::ForOp > targets)
Definition at line 791 of file LoopUtils.cpp.
References tileImpl().
tile() [3/4]
SmallVector< AffineForOp, 8 > mlir::tile (ArrayRef< AffineForOp > forOps, ArrayRef< uint64_t > sizes, AffineForOp target)
Performs tiling (with interchange) by strip-mining the forOps by sizes and sinking them, in their order of occurrence in forOps, under target.
Returns the new AffineForOps, one per forOps, nested immediately under target.
Definition at line 808 of file LoopUtils.cpp.
References tileImpl().
tile() [4/4]
Loops mlir::tile (ArrayRef< loop::ForOp > forOps, ArrayRef< Value > sizes, loop::ForOp target)
Definition at line 814 of file LoopUtils.cpp.
References tileImpl().
tileCodeGen()
LogicalResult mlir::tileCodeGen (MutableArrayRef< AffineForOp > band, ArrayRef< unsigned > tileSizes)
Tiles the specified band of perfectly nested loops creating tile-space loops and intra-tile loops.
A band is a contiguous set of loops.
Definition at line 177 of file LoopTiling.cpp.
References constructTiledIndexSetHyperRect(), mlir::OpBuilder::create(), extractForInductionVars(), failure(), getIndexSet(), moveLoopBody(), and success().
Referenced by adjustToDivisorsOfTripCounts().
tilePerfectlyNested()
Loops mlir::tilePerfectlyNested (loop::ForOp rootForOp, ArrayRef< Value > sizes)
Tile a nest of loop::ForOp loops rooted at rootForOp with the given (parametric) sizes.
Sizes are expected to be strictly positive values at runtime. If more sizes than loops are provided, discard the trailing values in sizes. Assumes the loop nest is permutable. Returns the newly created intra-tile loops.
Definition at line 819 of file LoopUtils.cpp.
References getPerfectlyNestedLoopsImpl(), and tile().
toAffineExpr()
AffineExpr mlir::toAffineExpr (ArrayRef< int64_t > eq, unsigned numDims, unsigned numSymbols, ArrayRef< AffineExpr > localExprs, MLIRContext * context)
Constructs an affine expression from a flat ArrayRef.
If there are local identifiers (neither dimensional nor symbolic) that appear in the sum of products expression, 'localExprs' is expected to have the AffineExpr for it, and is substituted into. The ArrayRef 'eq' is expected to be in the format [dims, symbols, locals, constant term].
Definition at line 594 of file AffineExpr.cpp.
References mlir::AffineExpr::expr, getAffineConstantExpr(), getAffineDimExpr(), and getAffineSymbolExpr().
Referenced by mlir::FlatAffineConstraints::getInequality(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), operator-(), simplifyAffineExpr(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), and mlir::SimpleAffineExprFlattener::visitModExpr().
topologicalSort()
llvm::SetVector<Operation *> mlir::topologicalSort (const llvm::SetVector< Operation *> & toSort)
Multi-root DAG topological sort.
Performs a topological sort of the Operation in the toSort SetVector. Returns a topologically sorted SetVector.
Referenced by DFSPostorder(), getSlice(), topologicalSort(), and vectorizeNonTerminals().
translateLLVMIRToModule()
OwningModuleRef mlir::translateLLVMIRToModule (std::unique_ptr< llvm::Module > llvmModule, MLIRContext * context)
Convert the given LLVM module into MLIR's LLVM dialect.
The LLVM context is extracted from the registered LLVM IR dialect. In case of error, report it to the error handler registered with the MLIR context, if any (obtained from the MLIR module), and return {}.
Definition at line 796 of file ConvertFromLLVMIR.cpp.
References mlir::ModuleOp::create(), failed(), mlir::FileLineColLoc::get(), and mlir::OwningModuleRef::get().
Referenced by translateLLVMIRToModule().
translateModuleToLLVMIR()
std::unique_ptr< llvm::Module > mlir::translateModuleToLLVMIR (ModuleOp m)
Convert the given MLIR module into LLVM IR.
The LLVM context is extracted from the registered LLVM IR dialect. In case of error, report it to the error handler registered with the MLIR context, if any (obtained from the MLIR module), and return nullptr.
Definition at line 24 of file ConvertToLLVMIR.cpp.
References failure(), registration, and success().
Referenced by mlir::ExecutionEngine::create().
translateModuleToNVVMIR()
std::unique_ptr< llvm::Module > mlir::translateModuleToNVVMIR (Operation * m)
Convert the given LLVM-module-like operation into NVVM IR.
This conversion requires the registration of the LLVM IR dialect and will extract the LLVM context from the registered LLVM IR dialect. In case of error, report it to the error handler registered with the MLIR context, if any (obtained from the MLIR module), and return nullptr.
Definition at line 68 of file ConvertToNVVMIR.cpp.
References failure(), mlir::gpu::GPUDialect::isKernel(), registration, and success().
translateModuleToROCDLIR()
std::unique_ptr< llvm::Module > mlir::translateModuleToROCDLIR (Operation * m)
Convert the given LLVM-module-like operation into ROCDL IR.
This conversion requires the registration of the LLVM IR dialect and will extract the LLVM context from the registered LLVM IR dialect. In case of error, report it to the error handler registered with the MLIR context, if any (obtained from the MLIR module), and return nullptr.
Definition at line 77 of file ConvertToROCDLIR.cpp.
References failure(), mlir::gpu::GPUDialect::getKernelFuncAttrName(), registration, and success().
verify()
LogicalResult mlir::verify (Operation * op)
Perform (potentially expensive) checks of invariants, used to detect compiler bugs, on this operation and any nested operations.
Perform (potentially expensive) checks of invariants, used to detect compiler bugs.
On error, this reports the error through the MLIRContext and returns failure.
Definition at line 264 of file Verifier.cpp.
References mlir::Operation::getContext().
Referenced by mlir::AffineApplyOp::getMapOperands(), mlir::DmaStartOp::getOperationName(), mlir::AffineDmaStartOp::getOperationName(), mlir::AffineLoadOp::getOperationName(), mlir::AffineStoreOp::getOperationName(), mlir::AffineDmaWaitOp::getTagMapAttrName(), parseSourceFile(), mlir::Pass::printAsTextualPipeline(), printMLIROutput(), and mlir::Op< AffineLoadOp, OpTrait::OneResult, OpTrait::AtLeastNOperands< 1 >::Impl >::verifyInvariants().
verifyCompatibleShape() [1/2]
LogicalResult mlir::verifyCompatibleShape (ArrayRef< int64_t > shape1, ArrayRef< int64_t > shape2)
Returns success if the given two shapes are compatible.
That is, they have the same size and each pair of the elements are equal or one of them is dynamic.
Definition at line 54 of file TypeUtilities.cpp.
References failure(), mlir::ShapedType::isDynamic(), and success().
Referenced by verify(), verifyCompatibleShape(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), and mlir::OpTrait::impl::verifySameOperandsShape().
verifyCompatibleShape() [2/2]
LogicalResult mlir::verifyCompatibleShape (Type type1, Type type2)
Returns success if the given two types have compatible shape.
That is, they are both scalars (not shaped), or they are both shaped types and at least one is unranked or they have compatible dimensions. Dimensions are compatible if at least one is dynamic or both are equal. The element type does not matter.
Definition at line 73 of file TypeUtilities.cpp.
References mlir::Type::dyn_cast(), failure(), mlir::ShapedType::getShape(), mlir::ShapedType::hasRank(), success(), and verifyCompatibleShape().
viewGraph() [1/2]
void mlir::viewGraph (Block & block, const Twine & name, bool shortNames = false, const Twine & title = "", llvm::GraphProgram::Name program = llvm::GraphProgram::DOT)
Displays the graph in a window.
This is for use from the debugger and depends on Graphviz to generate the graph.
Definition at line 149 of file ViewOpGraph.cpp.
Referenced by mlir::Region::viewGraph().
viewGraph() [2/2]
void mlir::viewGraph (Region & region, const Twine & name, bool shortNames = false, const Twine & title = "", llvm::GraphProgram::Name program = llvm::GraphProgram::DOT)
Displays the CFG in a window.
This is for use from the debugger and depends on Graphviz to generate the graph.
Definition at line 47 of file ViewRegionGraph.cpp.
visitUsedValuesDefinedAbove() [1/2]
void mlir::visitUsedValuesDefinedAbove (Region & region, Region & limit, function_ref< void(OpOperand *)> callback)
Calls callback for each use of a value within region or its descendants that was defined at the ancestors of the limit.
Definition at line 29 of file RegionUtils.cpp.
References mlir::Operation::getOpOperands(), mlir::Region::getParentRegion(), mlir::Region::isAncestor(), reg, and mlir::Region::walk().
Referenced by areValuesDefinedAbove(), getUsedValuesDefinedAbove(), and visitUsedValuesDefinedAbove().
visitUsedValuesDefinedAbove() [2/2]
void mlir::visitUsedValuesDefinedAbove (MutableArrayRef< Region > regions, function_ref< void(OpOperand *)> callback)
Calls callback for each use of a value within any of the regions provided that was defined in one of the ancestors.
Definition at line 50 of file RegionUtils.cpp.
References visitUsedValuesDefinedAbove().
writeGraph() [1/2]
raw_ostream & mlir::writeGraph (raw_ostream & os, Region & region, bool shortNames = false, const Twine & title = "")
Definition at line 52 of file ViewRegionGraph.cpp.
writeGraph() [2/2]
raw_ostream & mlir::writeGraph (raw_ostream & os, Block & block, bool shortNames = false, const Twine & title = "")
Definition at line 154 of file ViewOpGraph.cpp.
Referenced by mlir::Region::viewGraph().
Variable Documentation
makeLLVMPassesTransformer
std::function< llvm::Error(llvm::Module *)> mlir::makeLLVMPassesTransformer
Create a module transformer function for MLIR ExecutionEngine that runs LLVM IR passes explicitly specified, plus an optional optimization level, Any optimization passes, if present, will be inserted before the pass at position optPassesInsertPos.
If not null, targetMachine is used to initialize passes that provide target-specific information to the LLVM optimizer. targetMachine must outlive the returned std::function.
Definition at line 50 of file OptUtils.h.
Referenced by compileAndExecuteSingleFloatReturnFunction(), and populatePassManagers().
makeOptimizingTransformer
std::function< llvm::Error(llvm::Module *)> mlir::makeOptimizingTransformer
Create a module transformer function for MLIR ExecutionEngine that runs LLVM IR passes corresponding to the given speed and size optimization levels (e.g.
-O2 or -Os). If not null, targetMachine is used to initialize passes that provide target-specific information to the LLVM optimizer. targetMachine must outlive the returned std::function.
Definition at line 40 of file OptUtils.h.
Referenced by populatePassManagers().