MLIR: mlir::edsc Namespace Reference
mlir::edsc Namespace Reference
Namespaces
intrinsics
Provides a set of first class intrinsics.
op
ops
Classes
class AffineLoopNestBuilder
Explicit nested LoopBuilder.
class Append
class BlockBuilder
A BlockBuilder is a NestedBuilder for mlir::Block*.
class BlockHandle
A BlockHandle represents a (potentially "delayed") Block abstraction.
class CapturableHandle
Base class for ValueHandle, OperationHandle and BlockHandle.
struct CustomOperation
Simple wrapper to build a generic operation without successor blocks.
class GenericLoopNestRangeBuilder
Helper template class for building loop.for and affine.loop nests from ranges.
struct index_type
struct IndexHandle
An IndexHandle is a simple wrapper around a ValueHandle.
class LoopBuilder
A LoopBuilder is a generic NestedBuilder for loop-like MLIR operations.
class LoopNestBuilder
Helper class to sugar building loop.for loop nests from ranges.
class LoopNestRangeBuilder
Helper class to sugar building loop.for loop nests from ranges.
class LoopRangeBuilder
A LoopRangeBuilder is a generic NestedBuilder for loop.for operations.
class MemRefView
A MemRefView represents the information required to step through a MemRef.
class NestedBuilder
A NestedBuilder is a scoping abstraction to create an idiomatic syntax embedded in C++ that serves the purpose of building nested MLIR.
struct OperationHandle
An OperationHandle can be used in lieu of ValueHandle to capture the operation in cases when one does not care about, or cannot extract, a unique Value from the operation.
class ScopedContext
Helper class to transparently handle builder insertion points by RAII.
struct StructuredIndexed
A StructuredIndexed represents an indexable quantity that is either:
class TemplatedIndexedValue
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
class ValueHandle
ValueHandle implements a (potentially "delayed") typed Value abstraction.
class VectorView
A VectorView represents the information required to step through a Vector accessing each scalar element at a time.
class View
Typedefs
using IndexedValue = TemplatedIndexedValue< intrinsics::affine_load, intrinsics::affine_store >
using StdIndexedValue = TemplatedIndexedValue< intrinsics::std_load, intrinsics::std_store >
Enumerations
enum IterType { IterType::Parallel, IterType::Reduction }
Functions
StringRef toString (IterType t)
void defaultRegionBuilder (ArrayRef< BlockArgument > args)
Operation * makeGenericLinalgOp (ArrayRef< IterType > iteratorTypes, ArrayRef< StructuredIndexed > inputs, ArrayRef< StructuredIndexed > outputs, function_ref< void(ArrayRef< BlockArgument >)> regionBuilder=defaultRegionBuilder, ArrayRef< Value > otherValues={}, ArrayRef< Attribute > otherAttributes={})
Build a linalg.generic op with the specified inputs, outputs and region.
template<typename Container >
SmallVector< ValueHandle, 8 > makeValueHandles (Container values)
Entry point to build multiple ValueHandle from a Container of Value or Type.
SmallVector< IndexHandle, 8 > makeIndexHandles (unsigned rank)
template<typename T >
SmallVector< ValueHandle *, 8 > makeHandlePointers (MutableArrayRef< T > ivs)
Entry point to build multiple ValueHandle* from a mutable list ivs of T.
SmallVector< Value, 8 > extractValues (ArrayRef< IndexHandle > ivs)
Returns a vector of the underlying Value from ivs.
Typedef Documentation
IndexedValue
using mlir::edsc::IndexedValue = typedef TemplatedIndexedValue<intrinsics::affine_load, intrinsics::affine_store>
Definition at line 30 of file Helpers.h.
StdIndexedValue
using mlir::edsc::StdIndexedValue = typedef TemplatedIndexedValue<intrinsics::std_load, intrinsics::std_store>
Definition at line 32 of file Helpers.h.
Enumeration Type Documentation
IterType
enum mlir::edsc::IterType strong
Enumerator
Parallel
Reduction
Definition at line 85 of file Builders.h.
Function Documentation
defaultRegionBuilder()
void mlir::edsc::defaultRegionBuilder (ArrayRef< BlockArgument > args) inline
Definition at line 136 of file Builders.h.
References makeGenericLinalgOp().
extractValues()
SmallVector<Value, 8> mlir::edsc::extractValues (ArrayRef< IndexHandle > ivs) inline
Returns a vector of the underlying Value from ivs.
Definition at line 74 of file Intrinsics.h.
Referenced by emitLoopRanges().
makeGenericLinalgOp()
Operation * mlir::edsc::makeGenericLinalgOp (ArrayRef< IterType > iteratorTypes, ArrayRef< StructuredIndexed > inputs, ArrayRef< StructuredIndexed > outputs, function_ref< void(ArrayRef< BlockArgument >)> regionBuilder = defaultRegionBuilder, ArrayRef< Value > otherValues = {}, ArrayRef< Attribute > otherAttributes = {})
Build a linalg.generic op with the specified inputs, outputs and region.
otherValues and otherAttributes may be passed and will be appended as operands and attributes respectively.
Prerequisites:
inputs may contain StructuredIndexed that capture either buffer or tensor values.
outputs may contain StructuredIndexed that capture either buffer values or tensor types. If both buffer values and tensor types are present, then all buffer values must appear before any tensor type. Without this restriction output tensor results would need to be reordered, which would result in surprising behavior when combined with region definition.
Definition at line 129 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::AffineMap::get(), mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::edsc::ScopedContext::getBuilder(), mlir::getElementTypeOrSelf(), mlir::edsc::ScopedContext::getLocation(), getMaxDimIndex(), makeHandlePointers(), makeValueHandles(), mlir::functional::map(), and toString().
Referenced by defaultRegionBuilder(), mlir::edsc::ops::linalg_conv_nhwc(), mlir::edsc::ops::linalg_dilated_conv_nhwc(), mlir::edsc::ops::linalg_matmul(), and mlir::edsc::ops::linalg_pointwise().
makeHandlePointers()
template<typename T > SmallVector<ValueHandle *, 8> mlir::edsc::makeHandlePointers (MutableArrayRef< T > ivs) inline
Entry point to build multiple ValueHandle* from a mutable list ivs of T.
Definition at line 64 of file Intrinsics.h.
Referenced by clip(), emitLoopRanges(), insertCopyLoops(), makeGenericLinalgOp(), and mlir::linalg::tileLinalgOp().
makeIndexHandles()
SmallVector<IndexHandle, 8> mlir::edsc::makeIndexHandles (unsigned rank) inline
Definition at line 57 of file Intrinsics.h.
Referenced by clip(), and insertCopyLoops().
makeValueHandles()
template<typename Container > SmallVector<ValueHandle, 8> mlir::edsc::makeValueHandles (Container values) inline
Entry point to build multiple ValueHandle from a Container of Value or Type.
Definition at line 541 of file Builders.h.
References mlir::edsc::index_type::v.
Referenced by makeGenericLinalgOp().
toString()
StringRef mlir::edsc::toString (IterType t) inline
Definition at line 87 of file Builders.h.
References mlir::getParallelIteratorTypeName(), mlir::getReductionIteratorTypeName(), Parallel, and Reduction.
Referenced by makeGenericLinalgOp().