MLIR: mlir::loop Namespace Reference
mlir::loop Namespace Reference
Classes
class LoopOpsDialect
Functions
void ensureLoopTerminator (Region &region, Builder &builder, Location loc)
ForOp getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
Function Documentation
ensureLoopTerminator()
void mlir::loop::ensureLoopTerminator (Region & region, Builder & builder, Location loc)
getForInductionVarOwner()
ForOp mlir::loop::getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
If the provided value is not an induction variable, then return nullptr.
Referenced by getBackwardSliceImpl(), mlir::edsc::LoopBuilder::makeLoop(), parseForOp(), and mlir::linalg::tileLinalgOp().