MLIR: mlir::edsc::ops Namespace Reference
mlir::edsc::ops Namespace Reference
Typedefs
using UnaryPointwiseOpBuilder = function_ref< Value(ValueHandle)>
TODO(ntv): In the future we should tie these implementations to something in Tablegen that generates the proper interfaces and the proper sugared named ops.
using BinaryPointwiseOpBuilder = function_ref< Value(ValueHandle, ValueHandle)>
Binary pointwise operation (with broadcast) entry point.
Functions
void macRegionBuilder (ArrayRef< BlockArgument > args)
Build the body of a region to compute a multiply-accumulate, under the current ScopedContext, at the current insert point.
Operation * linalg_pointwise (UnaryPointwiseOpBuilder unaryOp, StructuredIndexed I, StructuredIndexed O)
Operation * linalg_pointwise_tanh (StructuredIndexed I, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = tanh(I).
Operation * linalg_pointwise (BinaryPointwiseOpBuilder binaryOp, StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Binary pointwise operation (with broadcast) entry point.
Operation * linalg_pointwise_add (StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = I1 + I2.
Operation * linalg_pointwise_max (StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = max(I1, I2).
Operation * linalg_matmul (ValueHandle vA, ValueHandle vB, ValueHandle vC)
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes:
(m, n, k) = (par, par, seq)
|
|  C(m, n) += A(m, k) * B(k, n)
.
template<typename Container >
Operation * linalg_matmul (Container values)
Operation * linalg_conv_nhwc (ValueHandle vI, ValueHandle vW, ValueHandle vO, ArrayRef< int > strides={}, ArrayRef< int > dilations={})
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes: ``` (batch, f, [h, w, ...], [kh, kw, ...], c) = | (par, par, [par, par, ...], [red, red, ...], red) | | O(batch, [h, w, ...], f) += | I(batch, | [ | stride[0] * h + dilations[0] * kh, | stride[1] * w + dilations[1] * kw, ...
template<typename Container >
Operation * linalg_conv_nhwc (Container values, ArrayRef< int > strides={}, ArrayRef< int > dilations={})
Operation * linalg_dilated_conv_nhwc (ValueHandle vI, ValueHandle vW, ValueHandle vO, int depth_multiplier=1, ArrayRef< int > strides={}, ArrayRef< int > dilations={})
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes: ``` (batch, dm, c, [h, w, ...], [kh, kw, ...]) = | (par, par, par, [par, par, ...], [red, red, ...]) | | O(batch, [h, w, ...], c * depth_multiplier) += | I(batch, | [ | stride[0] * h + dilations[0] * kh, | stride[1] * w + dilations[1] * kw, ...
template<typename Container >
Operation * linalg_dilated_conv_nhwc (Container values, int depth_multiplier, ArrayRef< int > strides={}, ArrayRef< int > dilations={})
Typedef Documentation
BinaryPointwiseOpBuilder
using mlir::edsc::ops::BinaryPointwiseOpBuilder = typedef function_ref<Value(ValueHandle, ValueHandle)>
Binary pointwise operation (with broadcast) entry point.
Definition at line 206 of file Builders.h.
UnaryPointwiseOpBuilder
using mlir::edsc::ops::UnaryPointwiseOpBuilder = typedef function_ref<Value(ValueHandle)>
TODO(ntv): In the future we should tie these implementations to something in Tablegen that generates the proper interfaces and the proper sugared named ops.
Build a linalg.pointwise, under the current ScopedContext, at the current insert point, that computes:
(i0, ..., in) = (par, ..., par)
|
|  O...(some_subset...(i0, ..., in)) =
|    some_pointwise_func...(I...(some_other_subset...(i0, ..., in)))
This is a very generic entry point that can be configured in many ways to build a perfect loop nest of parallel loops with arbitrarily complex innermost loop code and whatever (explicit) broadcast semantics.
This can be used with both out-of-place and in-place semantics. The client is responsible for ensuring the region operations are compatible with in-place semantics and parallelism. Unary pointwise operation (with broadcast) entry point.
Definition at line 196 of file Builders.h.
Function Documentation
linalg_conv_nhwc() [1/2]
Operation * mlir::edsc::ops::linalg_conv_nhwc (ValueHandle vI, ValueHandle vW, ValueHandle vO, ArrayRef< int > strides = {}, ArrayRef< int > dilations = {})
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes: ``` (batch, f, [h, w, ...], [kh, kw, ...], c) = | (par, par, [par, par, ...], [red, red, ...], red) | | O(batch, [h, w, ...], f) += | I(batch, | [ | stride[0] * h + dilations[0] * kh, | stride[1] * w + dilations[1] * kw, ...
], | c) | * | W([kh, kw, ...], c, f) `` Ifdilationsorstridesare left empty, the default value of1` is used along each relevant dimension.
For now ... must be empty (i.e. only 2-D convolutions are supported).
Definition at line 301 of file Builders.cpp.
References mlir::bindDims(), mlir::AffineExpr::cast(), mlir::edsc::ScopedContext::getContext(), macRegionBuilder(), mlir::edsc::makeGenericLinalgOp(), mlir::edsc::Parallel, mlir::edsc::Reduction, and mlir::simplifyAffineExpr().
linalg_conv_nhwc() [2/2]
template<typename Container > Operation* mlir::edsc::ops::linalg_conv_nhwc (Container values, ArrayRef< int > strides = {}, ArrayRef< int > dilations = {})
Definition at line 266 of file Builders.h.
References linalg_dilated_conv_nhwc().
Referenced by linalg_matmul().
linalg_dilated_conv_nhwc() [1/2]
Operation * mlir::edsc::ops::linalg_dilated_conv_nhwc (ValueHandle vI, ValueHandle vW, ValueHandle vO, int depth_multiplier = 1, ArrayRef< int > strides = {}, ArrayRef< int > dilations = {})
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes: ``` (batch, dm, c, [h, w, ...], [kh, kw, ...]) = | (par, par, par, [par, par, ...], [red, red, ...]) | | O(batch, [h, w, ...], c * depth_multiplier) += | I(batch, | [ | stride[0] * h + dilations[0] * kh, | stride[1] * w + dilations[1] * kw, ...
], | c) | * | W([kh, kw, ...], c, depth_multiplier) `` Ifdilationsorstridesare left empty, the default value of1` is used along each relevant dimension.
For now ... must be empty (i.e. only 2-D convolutions are supported).
Definition at line 335 of file Builders.cpp.
References mlir::bindDims(), mlir::AffineExpr::cast(), mlir::edsc::ScopedContext::getContext(), macRegionBuilder(), mlir::edsc::makeGenericLinalgOp(), mlir::edsc::Parallel, mlir::edsc::Reduction, and mlir::simplifyAffineExpr().
linalg_dilated_conv_nhwc() [2/2]
template<typename Container > Operation* mlir::edsc::ops::linalg_dilated_conv_nhwc (Container values, int depth_multiplier, ArrayRef< int > strides = {}, ArrayRef< int > dilations = {})
Definition at line 300 of file Builders.h.
Referenced by linalg_conv_nhwc().
linalg_matmul() [1/2]
Operation * mlir::edsc::ops::linalg_matmul (ValueHandle vA, ValueHandle vB, ValueHandle vC)
Build a linalg.generic, under the current ScopedContext, at the current insert point, that computes:
(m, n, k) = (par, par, seq)
|
|  C(m, n) += A(m, k) * B(k, n)
.
Definition at line 287 of file Builders.cpp.
References mlir::bindDims(), mlir::edsc::ScopedContext::getContext(), macRegionBuilder(), mlir::edsc::makeGenericLinalgOp(), mlir::edsc::Parallel, and mlir::edsc::Reduction.
linalg_matmul() [2/2]
template<typename Container > Operation* mlir::edsc::ops::linalg_matmul (Container values)
Definition at line 234 of file Builders.h.
References linalg_conv_nhwc().
linalg_pointwise() [1/2]
Operation * mlir::edsc::ops::linalg_pointwise (UnaryPointwiseOpBuilder unaryOp, StructuredIndexed I, StructuredIndexed O)
Definition at line 216 of file Builders.cpp.
References mlir::edsc::StructuredIndexed::getExprs(), mlir::edsc::ValueHandle::getType(), mlir::Type::isa(), mlir::edsc::makeGenericLinalgOp(), and mlir::edsc::Parallel.
Referenced by linalg_pointwise_add(), linalg_pointwise_max(), and linalg_pointwise_tanh().
linalg_pointwise() [2/2]
Operation * mlir::edsc::ops::linalg_pointwise (BinaryPointwiseOpBuilder binaryOp, StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Binary pointwise operation (with broadcast) entry point.
Definition at line 245 of file Builders.cpp.
References mlir::edsc::StructuredIndexed::getExprs(), mlir::edsc::ValueHandle::getType(), mlir::Type::isa(), mlir::edsc::makeGenericLinalgOp(), and mlir::edsc::Parallel.
linalg_pointwise_add()
Operation * mlir::edsc::ops::linalg_pointwise_add (StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = I1 + I2.
The client is responsible for specifying the proper indexings when creating the StructuredIndexed.
Definition at line 267 of file Builders.cpp.
References linalg_pointwise().
linalg_pointwise_max()
Operation * mlir::edsc::ops::linalg_pointwise_max (StructuredIndexed I1, StructuredIndexed I2, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = max(I1, I2).
The client is responsible for specifying the proper indexings when creating the StructuredIndexed.
Definition at line 276 of file Builders.cpp.
References linalg_pointwise().
linalg_pointwise_tanh()
Operation * mlir::edsc::ops::linalg_pointwise_tanh (StructuredIndexed I, StructuredIndexed O)
Build a linalg.pointwise with all parallel iterators and a region that computes O = tanh(I).
The client is responsible for specifying the proper indexings when creating the StructuredIndexed.
Definition at line 237 of file Builders.cpp.
References linalg_pointwise().
macRegionBuilder()
void mlir::edsc::ops::macRegionBuilder (ArrayRef< BlockArgument > args)
Build the body of a region to compute a multiply-accumulate, under the current ScopedContext, at the current insert point.
Definition at line 208 of file Builders.cpp.
Referenced by linalg_conv_nhwc(), linalg_dilated_conv_nhwc(), and linalg_matmul().