MLIR: mlir::LLVM Namespace Reference
mlir::LLVM Namespace Reference
Namespaces
detail
Classes
class LLVMDialect
class LLVMType
class ModuleTranslation
Functions
void ensureDistinctSuccessors (ModuleOp m)
Make argument-taking successors of each block distinct.
Value createGlobalString (Location loc, OpBuilder &builder, StringRef name, StringRef value, LLVM::Linkage linkage, LLVM::LLVMDialect *llvmDialect)
Create an LLVM global containing the string "value" at the module containing surrounding the insertion point of builder.
bool satisfiesLLVMModule (Operation *op)
LLVM requires some operations to be inside of a Module operation.
Function Documentation
createGlobalString()
Value mlir::LLVM::createGlobalString (Location loc, OpBuilder & builder, StringRef name, StringRef value, LLVM::Linkage linkage, LLVM::LLVMDialect * llvmDialect)
Create an LLVM global containing the string "value" at the module containing surrounding the insertion point of builder.
Obtain the address of that global and use it to compute the address of the first character in the string (operations inserted at the builder insertion point).
Definition at line 1842 of file LLVMDialect.cpp.
References mlir::OpBuilder::create(), mlir::LLVM::LLVMType::getArrayTy(), mlir::Builder::getIndexType(), mlir::OpBuilder::getInsertionBlock(), mlir::LLVM::LLVMType::getInt64Ty(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::LLVM::LLVMType::getInt8Ty(), mlir::Builder::getIntegerAttr(), mlir::Operation::getParentOfType(), mlir::Block::getParentOp(), and mlir::Builder::getStringAttr().
Referenced by mlir::LLVM::LLVMDialect::getDialectNamespace().
ensureDistinctSuccessors()
void mlir::LLVM::ensureDistinctSuccessors (ModuleOp m)
Make argument-taking successors of each block distinct.
PHI nodes in LLVM IR use the predecessor ID to identify which value to take. They do not support different values coming from the same predecessor. If a block has another block as a successor more than once with different values, insert a new dummy block for LLVM PHI nodes to tell the sources apart.
Definition at line 2060 of file ConvertStandardToLLVM.cpp.
References ensureDistinctSuccessors(), and mlir::ModuleOp::getOps().
Referenced by makeStandardToLLVMTypeConverter().
satisfiesLLVMModule()
bool mlir::LLVM::satisfiesLLVMModule (Operation * op)
LLVM requires some operations to be inside of a Module operation.
This function confirms that the Operation has the desired properties.
Definition at line 1871 of file LLVMDialect.cpp.
References mlir::Operation::hasTrait().
Referenced by mlir::LLVM::LLVMDialect::getDialectNamespace(), mlir::LLVM::ModuleTranslation::ModuleTranslation(), parseUndefOp(), mlir::LLVM::ModuleTranslation::translateModule(), and verify().