MLIR: mlir::vector Namespace Reference
mlir::vector Namespace Reference
Classes
class VectorOpsDialect
Dialect for Ops on higher-dimensional vector types.
Functions
void populateVectorToVectorCanonicalizationPatterns (OwningRewritePatternList &patterns, MLIRContext *context)
Collect a set of vector-to-vector canonicalization patterns.
void populateVectorToVectorTransformationPatterns (OwningRewritePatternList &patterns, MLIRContext *context)
Collect a set of vector-to-vector transformation patterns.
void populateVectorSlicesLoweringPatterns (OwningRewritePatternList &patterns, MLIRContext *context)
Collect a set of vector slices transformation patterns: ExtractSlicesOpLowering, InsertSlicesOpLowering Useful for clients that want to express all vector "slices" ops in terms of more elementary vector "slice" ops.
IntegerType getVectorSubscriptType (Builder &builder)
Returns the integer type required for subscripts in the vector dialect.
ArrayAttr getVectorSubscriptAttr (Builder &b, ArrayRef< int64_t > values)
Returns an integer array attribute containing the given values using the integer type required for subscripts in the vector dialect.
SmallVector< Value, 1 > unrollSingleResultOpMatchingType (PatternRewriter &builder, Operation *op, ArrayRef< int64_t > targetShape)
Function Documentation
getVectorSubscriptAttr()
ArrayAttr mlir::vector::getVectorSubscriptAttr (Builder & b, ArrayRef< int64_t > values)
Returns an integer array attribute containing the given values using the integer type required for subscripts in the vector dialect.
Definition at line 56 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Builder::getI64ArrayAttr(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), and mlir::Value::getType().
Referenced by mlir::vector::VectorOpsDialect::getDialectNamespace(), inferExtractOpResultType(), inferStridedSliceOpResultType(), parseBroadcastOp(), print(), and verify().
getVectorSubscriptType()
IntegerType mlir::vector::getVectorSubscriptType (Builder & builder)
Returns the integer type required for subscripts in the vector dialect.
Definition at line 52 of file VectorOps.cpp.
References mlir::Builder::getIntegerType().
Referenced by mlir::vector::VectorOpsDialect::getDialectNamespace().
populateVectorSlicesLoweringPatterns()
void mlir::vector::populateVectorSlicesLoweringPatterns (OwningRewritePatternList & patterns, MLIRContext * context)
Collect a set of vector slices transformation patterns: ExtractSlicesOpLowering, InsertSlicesOpLowering Useful for clients that want to express all vector "slices" ops in terms of more elementary vector "slice" ops.
If all "produced" tuple values are "consumed" (the most common use for "slices" ops), this lowering removes all tuple related operations as well (through DCE and folding). If tuple values "leak" coming in, however, some tuple related ops will remain.
Definition at line 797 of file VectorTransforms.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by mlir::vector::VectorOpsDialect::getDialectNamespace(), and mlir::populateVectorToLLVMConversionPatterns().
populateVectorToVectorCanonicalizationPatterns()
void mlir::vector::populateVectorToVectorCanonicalizationPatterns (OwningRewritePatternList & patterns, MLIRContext * context)
Collect a set of vector-to-vector canonicalization patterns.
Definition at line 1827 of file VectorOps.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by mlir::vector::VectorOpsDialect::getDialectNamespace().
populateVectorToVectorTransformationPatterns()
void mlir::vector::populateVectorToVectorTransformationPatterns (OwningRewritePatternList & patterns, MLIRContext * context)
Collect a set of vector-to-vector transformation patterns.
Definition at line 791 of file VectorTransforms.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by mlir::vector::VectorOpsDialect::getDialectNamespace().
unrollSingleResultOpMatchingType()
SmallVector< Value, 1 > mlir::vector::unrollSingleResultOpMatchingType (PatternRewriter & builder, Operation * op, ArrayRef< int64_t > targetShape)
Definition at line 466 of file VectorTransforms.cpp.
References mlir::Operation::getNumResults(), getVectorContractionOpUnrollState(), getVectorElementwiseOpUnrollState(), and unrollSingleResultStructuredOp().