MLIR: mlir::linalg Namespace Reference
mlir::linalg Namespace Reference
Namespaces
detail
Classes
class Aliases
A very primitive alias analysis which just records for each view, either:
struct FusionInfo
class LinalgDependenceGraph
Data structure for holding a dependence graph that operates on LinalgOp and views as SSA values.
class LinalgDialect
struct LinalgTransforms
struct PromotionInfo
class RangeType
A RangeType represents a minimal range abstraction (min, max, step).
struct TiledLinalgOp
Enumerations
enum LinalgTypes { Range = Type::FIRST_LINALG_TYPE, LAST_USED_LINALG_TYPE = Range }
Functions
std::string generateLibraryCallName (Operation *op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
SmallVector< AffineMap, 4 > loopToOperandRangesMaps (Operation *op)
Returns the list of maps that map loops to operands of a Linalg op.
template<typename OpTy >
bool isProducedByOpOfType (Operation *consumerOp, Value consumedView)
LogicalResult tileLinalgOpAndSetMarker (PatternRewriter &rewriter, Operation *op, ArrayRef< int64_t > sizes, StringRef linalgMarker, ArrayRef< unsigned > permutation)
Tiles op by sizes permuting the loops according to permutation and sets the attribute kLinalgTransformMarker to linalgMarker.
LogicalResult tileAndFuseLinalgOpAndSetMarker (PatternRewriter &rewriter, Operation *op, ArrayRef< int64_t > sizes, ArrayRef< int64_t > operandIndicesToFuse, StringRef linalgMarker)
Tiles op by sizes, fuses the producers of operandIndicesToFuse and sets the attribute kLinalgTransformMarker to linalgMarker.
template<typename ConcreteOp >
LogicalResult linalgOpToLoops (PatternRewriter &rewriter, Operation *op)
Emits a loop nest of loop.for with the proper body for op.
template<typename ConcreteOp >
LogicalResult linalgOpToAffineLoops (PatternRewriter &rewriter, Operation *op)
Emits a loop nest of affine.for with the proper body for op.
LogicalResult vectorizeLinalgOpPrecondition (Operation *op)
Rewrite a linalg.generic into a suitable vector.contraction op.
SmallVector< Value, 0 > vectorizeLinalgOp (PatternRewriter &rewriter, Operation *op)
LogicalResult permuteGenericLinalgOpPrecondition (Operation *op, ArrayRef< unsigned > permutation)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
SmallVector< Value, 0 > permuteGenericLinalgOp (PatternRewriter &rewriter, Operation *op, ArrayRef< unsigned > permutation, StringRef linalgMarker)
LogicalResult promoteSubviewsLinalgOpPrecondition (Operation *op)
Promote std.subviews feeding linalg operations.
SmallVector< Value, 0 > promoteSubviewsLinalgOp (PatternRewriter &rewriter, Operation *op)
bool isProducerLastWriteOfView (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
bool isFusableInto (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
Optional< FusionInfo > fuseProducerOf (OpBuilder &b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph &graph, OperationFolder *folder=nullptr)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
template<typename ConcreteOp >
SmallVector< Value, 8 > getViewSizes (OpBuilder &builder, ConcreteOp linalgOp)
Returns the linearized list of all view dimensions in a linalgOp.
SmallVector< Value, 4 > applyMapToValues (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > values, OperationFolder *folder=nullptr)
Returns the values obtained by applying map to the list of values.
Optional< TiledLinalgOp > tileLinalgOp (OpBuilder &b, LinalgOp op, ArrayRef< Value > tileSizes, ArrayRef< unsigned > permutation={}, OperationFolder *folder=nullptr)
Performs standalone tiling of a single LinalgOp by tileSizes.
Optional< TiledLinalgOp > tileLinalgOp (OpBuilder &b, LinalgOp op, ArrayRef< int64_t > tileSizes, ArrayRef< unsigned > permutation={}, OperationFolder *folder=nullptr)
Performs standalone tiling of a single LinalgOp by constant tileSizes.
template<typename... Args>
Optional< TiledLinalgOp > tileLinalgOperation (OpBuilder &b, Operation *op, Args... args)
SmallVector< PromotionInfo, 8 > promoteSubViews (OpBuilder &b, Location loc, ArrayRef< Value > subViews, bool dynamicBuffers=false, OperationFolder *folder=nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
SmallVector< Value, 4 > getAssumedNonViewOperands (LinalgOp linalgOp)
Returns all the operands of linalgOp that are not views.
template<typename T , unsigned N>
void applyPermutationToVector (SmallVector< T, N > &inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
LinalgOp promoteSubViewOperands (OpBuilder &b, LinalgOp op, llvm::SetVector< Value > subViews, bool dynamicBuffers=false, OperationFolder *folder=nullptr)
Prepares the SubView promotion later performed by promoteSubViews (where most of the transformation happens).
Enumeration Type Documentation
LinalgTypes
enum mlir::linalg::LinalgTypes
Enumerator
Range
LAST_USED_LINALG_TYPE
Definition at line 19 of file LinalgTypes.h.
Function Documentation
applyMapToValues()
SmallVector< Value, 4 > mlir::linalg::applyMapToValues (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > values, OperationFolder * folder = nullptr)
Returns the values obtained by applying map to the list of values.
When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 43 of file Utils.cpp.
References emitOrFoldComposedAffineApply(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResults().
Referenced by emitLoopRanges(), getViewSizes(), makeTiledLoopRanges(), makeTiledViews(), permuteIvs(), and tileLinalgOp().
applyPermutationToVector()
template<typename T , unsigned N> void mlir::linalg::applyPermutationToVector (SmallVector< T, N > & inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
Element i in inVec is mapped to location j = permutation[i]. E.g.: for an input vector `inVec = ['a', 'b', 'c']and a permutation vector permutation = [2, 0, 1], this function leavesinVec = ['c', 'a', 'b']`.
Definition at line 159 of file Utils.h.
References promoteSubViewOperands().
Referenced by permuteGenericLinalgOp(), and tileLinalgOp().
fuseProducerOf()
Optional< FusionInfo > mlir::linalg::fuseProducerOf (OpBuilder & b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph & graph, OperationFolder * folder = nullptr)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 268 of file Fusion.cpp.
References fuse(), mlir::linalg::LinalgDependenceGraph::getDependencesInto(), isFusableInto(), mlir::StandardTypes::None, and mlir::OpBuilder::setInsertionPoint().
Referenced by fuseLinalgOpsGreedily(), and tileAndFuseLinalgOpAndSetMarker().
generateLibraryCallName()
std::string mlir::linalg::generateLibraryCallName (Operation * op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
The name mangling scheme is basic and uses MLIR type names:
form a string which is the concatenation of the linalg op name with all the operand type names, separate by underscores;
drop the linalg. prefix, and the <, >, ? symbols from the type. Assumes op is a LinalgOp.
Examples:
linalg.fill(A, f) : memref<f32>, f32 name mangles into linalg_fill_viewf32_f32_impl
linalg.dot(A, B, C) : memref<?xf32, stride_specification>, memref<?xf32, stride_specification>, memref<f32> name mangles into linalg_dot_viewxf32_viewxf32_viewf32_impl
linalg.matmul(...) : memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification> name mangles into linalg_matmul_viewxxf32_viewxxf32_viewxxf32_impl
Definition at line 1040 of file LinalgOps.cpp.
References appendMangledType(), mlir::Operation::getName(), mlir::Operation::getOperandTypes(), mlir::OperationName::getStringRef(), and mlir::interleave().
getAssumedNonViewOperands()
SmallVector< Value, 4 > mlir::linalg::getAssumedNonViewOperands (LinalgOp linalgOp)
Returns all the operands of linalgOp that are not views.
Asserts that these operands are value types to allow transformations like tiling to just use the values when cloning linalgOp.
Definition at line 64 of file Utils.cpp.
Referenced by cloneWithLoopRanges(), promoteSubViews(), and tileLinalgOp().
getViewSizes()
template<typename ConcreteOp > SmallVector<Value, 8> mlir::linalg::getViewSizes (OpBuilder & builder, ConcreteOp linalgOp)
Returns the linearized list of all view dimensions in a linalgOp.
Applying the inverse, concatenated loopToOperandRangeMaps to this list allows the derivation of loop ranges for any linalgOp.
Definition at line 58 of file Utils.h.
References applyMapToValues(), mlir::OpBuilder::create(), and mlir::functional::map().
Referenced by emitLoopRanges(), and tileLinalgOp().
isFusableInto()
bool mlir::linalg::isFusableInto (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
This checks producer is the last write of consumedView and that no interleaved dependence would be violated (RAW, WAR or WAW).
Definition at line 248 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringDependences(), and isProducerLastWriteOfView().
Referenced by fuseProducerOf().
isProducedByOpOfType()
template<typename OpTy > bool mlir::linalg::isProducedByOpOfType (Operation * consumerOp, Value consumedView)
Definition at line 40 of file LinalgTransforms.h.
References mlir::linalg::detail::isProducedByOpOfTypeImpl(), linalgOpToAffineLoops(), linalgOpToLoops(), permuteGenericLinalgOp(), permuteGenericLinalgOpPrecondition(), promoteSubviewsLinalgOp(), promoteSubviewsLinalgOpPrecondition(), tileAndFuseLinalgOpAndSetMarker(), tileLinalgOpAndSetMarker(), vectorizeLinalgOp(), and vectorizeLinalgOpPrecondition().
isProducerLastWriteOfView()
bool mlir::linalg::isProducerLastWriteOfView (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
This checks structural dominance, that the dependence is a RAW without any interleaved write to any piece of consumedView.
Definition at line 224 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringWrites(), and isStructurallyFusableProducer().
Referenced by isFusableInto(), and mlir::linalg::detail::isProducedByOpOfTypeImpl().
linalgOpToAffineLoops()
template<typename ConcreteOp > LogicalResult mlir::linalg::linalgOpToAffineLoops (PatternRewriter & rewriter, Operation * op)
Emits a loop nest of affine.for with the proper body for op.
Definition at line 587 of file LinalgToLoops.cpp.
Referenced by isProducedByOpOfType().
linalgOpToLoops()
template<typename ConcreteOp > LogicalResult mlir::linalg::linalgOpToLoops (PatternRewriter & rewriter, Operation * op)
Emits a loop nest of loop.for with the proper body for op.
Definition at line 579 of file LinalgToLoops.cpp.
Referenced by isProducedByOpOfType().
loopToOperandRangesMaps()
SmallVector< AffineMap, 4 > mlir::linalg::loopToOperandRangesMaps (Operation * op)
Returns the list of maps that map loops to operands of a Linalg op.
The i-th affine map identifies loop indices to subscripts that are used when accessing the i-th operand. For instance, a matmul that can be written in index notation as: A(i, k) * B(k, j) -> C(i, j) will have the following, ordered, list of affine maps:
(
  (i, j, k) -> (i, k),
  (i, j, k) -> (k, j),
  (i, j, k) -> (i, j)
)
Only permutation maps are currently supported.
Definition at line 929 of file LinalgOps.cpp.
References mlir::StandardAttributes::AffineMap, concat(), extractOrIdentityMap(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Operation::getContext(), makeAffineDimExprs(), mlir::StandardTypes::None, and weightedConvInputIndex().
Referenced by cloneWithLoopRanges(), emitLoopRanges(), fuse(), getIndexingMaps(), getViewDefiningLoopRange(), makeTiledViews(), and tileLinalgOp().
permuteGenericLinalgOp()
SmallVector< Value, 0 > mlir::linalg::permuteGenericLinalgOp (PatternRewriter & rewriter, Operation * op, ArrayRef< unsigned > permutation, StringRef linalgMarker)
Definition at line 235 of file LinalgTransforms.cpp.
References applyPermutationToVector(), DEBUG_TYPE, mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getArrayAttr(), mlir::Builder::getContext(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), mlir::Operation::getOperands(), mlir::AffineMap::getPermutationMap(), mlir::Builder::getStringAttr(), mlir::inversePermutation(), permuteGenericLinalgOpPrecondition(), mlir::Operation::setAttr(), and mlir::succeeded().
Referenced by isProducedByOpOfType().
permuteGenericLinalgOpPrecondition()
LogicalResult mlir::linalg::permuteGenericLinalgOpPrecondition (Operation * op, ArrayRef< unsigned > permutation)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
Definition at line 220 of file LinalgTransforms.cpp.
References mlir::failure(), and mlir::success().
Referenced by isProducedByOpOfType(), and permuteGenericLinalgOp().
promoteSubViewOperands()
LinalgOp mlir::linalg::promoteSubViewOperands (OpBuilder & b, LinalgOp op, llvm::SetVector< Value > subViews, bool dynamicBuffers = false, OperationFolder * folder = nullptr)
Prepares the SubView promotion later performed by promoteSubViews (where most of the transformation happens).
It arranges the new operands for LinalgOp op and deallocates the new buffer(s) It is the entry point for declarative transformation Returns the cloned LinalgOp with the new operands
Referenced by applyPermutationToVector(), promoteSubViews(), promoteSubViews(), and promoteSubviewsLinalgOp().
promoteSubViews()
SmallVector< PromotionInfo, 8 > mlir::linalg::promoteSubViews (OpBuilder & b, Location loc, ArrayRef< Value > subViews, bool dynamicBuffers = false, OperationFolder * folder = nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
For now, promotion occurs in 3 steps:
Create a new buffer for a full tile (i.e. not clipped at the boundary).
Take a full view on the buffer and linalg.fill it with zeros (use float zero for now).
Take a partial slice of the full view in step 2. and copy into it. Infers statically sized buffers from subViews unless dynamicBuffers is true.
Returns a list of PromotionInfo which hold the promoted buffer and the full and partial views indexing into the buffer.
Definition at line 108 of file Promotion.cpp.
References getAssumedNonViewOperands(), promoteFullTileBuffer(), promoteSubViewOperands(), and promoteSubViews().
promoteSubviewsLinalgOp()
SmallVector< Value, 0 > mlir::linalg::promoteSubviewsLinalgOp (PatternRewriter & rewriter, Operation * op)
Definition at line 284 of file LinalgTransforms.cpp.
References DEBUG_TYPE, promoteSubViewOperands(), promoteSubviewsLinalgOpPrecondition(), and mlir::succeeded().
Referenced by isProducedByOpOfType().
promoteSubviewsLinalgOpPrecondition()
LogicalResult mlir::linalg::promoteSubviewsLinalgOpPrecondition (Operation * op)
Promote std.subviews feeding linalg operations.
Definition at line 271 of file LinalgTransforms.cpp.
References mlir::failure(), and mlir::success().
Referenced by isProducedByOpOfType(), and promoteSubviewsLinalgOp().
tileAndFuseLinalgOpAndSetMarker()
LogicalResult mlir::linalg::tileAndFuseLinalgOpAndSetMarker (PatternRewriter & rewriter, Operation * op, ArrayRef< int64_t > sizes, ArrayRef< int64_t > operandIndicesToFuse, StringRef linalgMarker)
Tiles op by sizes, fuses the producers of operandIndicesToFuse and sets the attribute kLinalgTransformMarker to linalgMarker.
Definition at line 53 of file LinalgTransforms.cpp.
References mlir::PatternRewriter::eraseOp(), mlir::failure(), fuseProducerOf(), mlir::Operation::getParentOfType(), mlir::Builder::getStringAttr(), mlir::success(), and tileLinalgOperation().
Referenced by isProducedByOpOfType().
tileLinalgOp() [1/2]
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOp (OpBuilder & b, LinalgOp op, ArrayRef< Value > tileSizes, ArrayRef< unsigned > permutation = {}, OperationFolder * folder = nullptr)
Performs standalone tiling of a single LinalgOp by tileSizes.
and permute the loop nest according to permutation The permutation is expressed as a list of integers that specify the new ordering of the loop nest. The length of permutation must be equal to the length of tileSizes. E.g. the permutation (i,j,k) -> (j,k,i) will be expressed with permutation = [1,2,0]. All values in permutation must be integers, in the range 0..tileSizes.size() without duplications (i.e. [1,1,2] is an invalid permutation). An empty list states for the identity permutation. Returns a struct containing the tiled loops in the specified order and the cloned op if successful, llvm::None otherwise. When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 311 of file Tiling.cpp.
References applyMapToValues(), applyPermutationToVector(), mlir::concatAffineMaps(), getAssumedNonViewOperands(), mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getContext(), mlir::loop::getForInductionVarOwner(), mlir::edsc::ScopedContext::getLocation(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::AffineMap::getPermutationMap(), getViewSizes(), mlir::inversePermutation(), loopToOperandRangesMaps(), mlir::edsc::makeHandlePointers(), makeTiledLoopRanges(), makeTiledViews(), mlir::OpBuilder::setInsertionPoint(), and transformIndexedGenericOpIndices().
Referenced by tileLinalgOp(), tileLinalgOperation(), and tileLinalgOps().
tileLinalgOp() [2/2]
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOp (OpBuilder & b, LinalgOp op, ArrayRef< int64_t > tileSizes, ArrayRef< unsigned > permutation = {}, OperationFolder * folder = nullptr)
Performs standalone tiling of a single LinalgOp by constant tileSizes.
and permute the loop nest according to permutation The permutation is expressed as a list of integers that specify the new ordering of the loop nest. The length of permutation must be equal to the length of tileSizes. E.g. the permutation (i,j,k) -> (j,k,i) will be expressed with permutation = [1,2,0]. All values in permutation must be integers, in the range 0..tileSizes.size() without duplications (i.e. [1,1,2] is an invalid permutation). An empty list states for the identity permutation. Returns a struct containing the tiled loops in the specified order and the cloned op if successful, llvm::None otherwise. When non-null, the optional pointer folder is used to call into the createAndFold builder method. If folder is null, the regular create method is called.
Definition at line 386 of file Tiling.cpp.
References mlir::StandardTypes::None, mlir::OpBuilder::setInsertionPoint(), and tileLinalgOp().
tileLinalgOpAndSetMarker()
LogicalResult mlir::linalg::tileLinalgOpAndSetMarker (PatternRewriter & rewriter, Operation * op, ArrayRef< int64_t > sizes, StringRef linalgMarker, ArrayRef< unsigned > permutation)
Tiles op by sizes permuting the loops according to permutation and sets the attribute kLinalgTransformMarker to linalgMarker.
The permutation is expressed as a list of integers that specify the new ordering of the loop nest. The length of permutation must be equal to the length of tileSizes. E.g. the permutation (i,j,k) -> (j,k,i) will be expressed with permutation = [1,2,0]. All values in permutation must be integers, in the range 0..tileSizes.size() without duplications (i.e. [1,1,2] is an invalid permutation). An empty list states for the identity permutation.
Definition at line 41 of file LinalgTransforms.cpp.
References mlir::failure(), mlir::Builder::getStringAttr(), mlir::success(), and tileLinalgOperation().
Referenced by isProducedByOpOfType().
tileLinalgOperation()
template<typename... Args> Optional<TiledLinalgOp> mlir::linalg::tileLinalgOperation (OpBuilder & b, Operation * op, Args... args)
Definition at line 123 of file Utils.h.
References tileLinalgOp().
Referenced by tileAndFuseLinalgOpAndSetMarker(), and tileLinalgOpAndSetMarker().
vectorizeLinalgOp()
SmallVector< Value, 0 > mlir::linalg::vectorizeLinalgOp (PatternRewriter & rewriter, Operation * op)
Definition at line 190 of file LinalgTransforms.cpp.
References DEBUG_TYPE, mlir::Operation::getLoc(), mlir::succeeded(), and vectorizeLinalgOpPrecondition().
Referenced by isProducedByOpOfType().
vectorizeLinalgOpPrecondition()
LogicalResult mlir::linalg::vectorizeLinalgOpPrecondition (Operation * op)
Rewrite a linalg.generic into a suitable vector.contraction op.
Definition at line 161 of file LinalgTransforms.cpp.
References mlir::failure(), mlir::ShapedType::hasStaticShape(), isMatmul(), and mlir::success().
Referenced by isProducedByOpOfType(), and vectorizeLinalgOp().