MLIR: mlir::ops_assertions Namespace Reference
mlir::ops_assertions Namespace Reference
Overloaded arithmetic operators for SDBM expressions asserting that their arguments have the proper SDBM expression subtype.
Functions
SDBMExpr operator+ (SDBMExpr lhs, SDBMExpr rhs)
Add two SDBM expressions.
SDBMExpr operator+ (SDBMExpr lhs, int64_t rhs)
SDBMExpr operator+ (int64_t lhs, SDBMExpr rhs)
SDBMExpr operator- (SDBMExpr lhs, SDBMExpr rhs)
Subtract an SDBM expression from another SDBM expression.
SDBMExpr operator- (SDBMExpr lhs, int64_t rhs)
SDBMExpr operator- (int64_t lhs, SDBMExpr rhs)
SDBMExpr stripe (SDBMExpr expr, SDBMExpr factor)
Construct a stripe expression from a positive expression and a positive constant stripe factor.
SDBMExpr stripe (SDBMExpr expr, int64_t factor)
Detailed Description
Overloaded arithmetic operators for SDBM expressions asserting that their arguments have the proper SDBM expression subtype.
Perform canonicalization and constant folding on these expressions.
Function Documentation
operator+() [1/3]
SDBMExpr mlir::ops_assertions::operator+ (SDBMExpr lhs, SDBMExpr rhs)
Add two SDBM expressions.
At least one of the expressions must be a constant or a negation, but both expressions cannot be negations simultaneously.
Definition at line 666 of file SDBMExpr.cpp.
References addConstant(), mlir::SDBMExpr::cast(), mlir::SDBMExpr::dyn_cast(), foldSumDiff(), mlir::SDBMConstantExpr::get(), mlir::SDBMExpr::getDialect(), mlir::SDBMDiffExpr::getLHS(), mlir::SDBMDiffExpr::getRHS(), mlir::SDBMConstantExpr::getValue(), and mlir::SDBMExpr::isa().
operator+() [2/3]
SDBMExpr mlir::ops_assertions::operator+ (SDBMExpr lhs, int64_t rhs) inline
Definition at line 471 of file SDBMExpr.h.
References mlir::SDBMConstantExpr::get(), and mlir::SDBMExpr::getDialect().
operator+() [3/3]
SDBMExpr mlir::ops_assertions::operator+ (int64_t lhs, SDBMExpr rhs) inline
Definition at line 474 of file SDBMExpr.h.
References mlir::SDBMConstantExpr::get(), mlir::SDBMExpr::getDialect(), and mlir::operator-().
operator-() [1/3]
SDBMExpr mlir::ops_assertions::operator- (SDBMExpr lhs, SDBMExpr rhs)
Subtract an SDBM expression from another SDBM expression.
Both expressions must not be difference expressions.
Definition at line 699 of file SDBMExpr.cpp.
References buildDiffExpr(), mlir::SDBMExpr::cast(), mlir::SDBMExpr::dyn_cast(), mlir::SDBMConstantExpr::get(), mlir::SDBMExpr::getDialect(), and mlir::SDBMConstantExpr::getValue().
operator-() [2/3]
SDBMExpr mlir::ops_assertions::operator- (SDBMExpr lhs, int64_t rhs) inline
Definition at line 481 of file SDBMExpr.h.
References mlir::SDBMConstantExpr::get(), and mlir::SDBMExpr::getDialect().
operator-() [3/3]
SDBMExpr mlir::ops_assertions::operator- (int64_t lhs, SDBMExpr rhs) inline
Definition at line 484 of file SDBMExpr.h.
References mlir::SDBMConstantExpr::get(), mlir::SDBMExpr::getDialect(), and stripe().
stripe() [1/2]
SDBMExpr mlir::ops_assertions::stripe (SDBMExpr expr, SDBMExpr factor)
Construct a stripe expression from a positive expression and a positive constant stripe factor.
Definition at line 726 of file SDBMExpr.cpp.
References mlir::SDBMExpr::cast(), and mlir::SDBMStripeExpr::get().
Referenced by mlir::SDBM::get().
stripe() [2/2]
SDBMExpr mlir::ops_assertions::stripe (SDBMExpr expr, int64_t factor) inline
Definition at line 491 of file SDBMExpr.h.
References mlir::SDBMConstantExpr::get(), and mlir::SDBMExpr::getDialect().
Referenced by operator-().