MLIR: mlir::fxpmath::detail Namespace Reference
mlir::fxpmath::detail Namespace Reference
Classes
struct QuantizedMultiplierSmallerThanOneExp
Derives a quantized multiplier and shift from a real valued multiplier less than 1.
struct UniformBinaryOpInfo
Helper class for operating on binary operations where all operands and the result are a UniformQuantizedType.
Functions
quant::UniformQuantizedType getUniformElementType (Type t)
bool hasStorageBitWidth (quant::QuantizedType t, ArrayRef< unsigned > checkWidths)
template<typename F >
bool integralLog2 (F x, int &log2Result)
Computes the log2(x), rounded to an integral value.
Type castElementType (Type t, Type newElementType)
Casts an integer or floating point based shaped type to a new element type.
Attribute broadcastScalarConstIntValue (Type t, int64_t value)
Creates an IntegerAttr with a type that matches the shape of 't' (which can be a scalar primitive or a shaped type).
APFloat convertFloatToType (FloatType ft, APFloat value)
Given an APFloat, converts it to the float semantics that matches the given FloatType, silently ignoring inexact conversions.
Attribute broadcastScalarConstFloatValue (Type t, APFloat value)
Creates a FloatAttr with a type that matches the shape of 't' (which can be a scalar primitive or a shaped type).
Function Documentation
broadcastScalarConstFloatValue()
Attribute mlir::fxpmath::detail::broadcastScalarConstFloatValue (Type t, APFloat value) inline
Creates a FloatAttr with a type that matches the shape of 't' (which can be a scalar primitive or a shaped type).
Definition at line 207 of file UniformKernelUtils.h.
References convertFloatToType(), mlir::Type::dyn_cast(), mlir::FloatAttr::get(), and mlir::DenseElementsAttr::get().
Referenced by emitUniformPerLayerDequantize().
broadcastScalarConstIntValue()
Attribute mlir::fxpmath::detail::broadcastScalarConstIntValue (Type t, int64_t value) inline
Creates an IntegerAttr with a type that matches the shape of 't' (which can be a scalar primitive or a shaped type).
Definition at line 181 of file UniformKernelUtils.h.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::IntegerAttr::get(), mlir::DenseElementsAttr::get(), and mlir::Type::isa().
Referenced by emitUniformPerLayerDequantize(), tryRewriteAffineAddEwIsomorphicSigned(), and tryRewriteAffineMulEwSigned().
castElementType()
Type mlir::fxpmath::detail::castElementType (Type t, Type newElementType) inline
Casts an integer or floating point based shaped type to a new element type.
Definition at line 161 of file UniformKernelUtils.h.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), mlir::MemRefType::get(), getAffineMaps(), mlir::Type::isIntOrFloat(), mlir::StandardTypes::MemRef, mlir::StandardTypes::RankedTensor, mlir::StandardTypes::UnrankedTensor, and mlir::StandardTypes::Vector.
Referenced by emitUniformPerLayerDequantize(), tryRewriteAffineAddEwIsomorphicSigned(), and tryRewriteAffineMulEwSigned().
convertFloatToType()
APFloat mlir::fxpmath::detail::convertFloatToType (FloatType ft, APFloat value) inline
Given an APFloat, converts it to the float semantics that matches the given FloatType, silently ignoring inexact conversions.
Definition at line 195 of file UniformKernelUtils.h.
References mlir::FloatType::getFloatSemantics().
Referenced by broadcastScalarConstFloatValue().
getUniformElementType()
quant::UniformQuantizedType mlir::fxpmath::detail::getUniformElementType (Type t) inline
Definition at line 23 of file UniformKernelUtils.h.
References mlir::Type::dyn_cast_or_null(), and mlir::quant::QuantizedType::getQuantizedElementType().
hasStorageBitWidth()
bool mlir::fxpmath::detail::hasStorageBitWidth (quant::QuantizedType t, ArrayRef< unsigned > checkWidths) inline
Definition at line 28 of file UniformKernelUtils.h.
References mlir::Type::getIntOrFloatBitWidth(), and mlir::quant::QuantizedType::getStorageType().
integralLog2()
template<typename F > bool mlir::fxpmath::detail::integralLog2 (F x, int & log2Result)
Computes the log2(x), rounded to an integral value.
Returns whether 'x' can be considered an exact integral value.
Definition at line 40 of file UniformKernelUtils.h.
Referenced by mlir::fxpmath::detail::UniformBinaryOpInfo::isFixedPointPOT().