MLIR: mlir::edsc::intrinsics Namespace Reference
mlir::edsc::intrinsics Namespace Reference
Provides a set of first class intrinsics.
Namespaces
detail
Classes
struct OperationBuilder
struct ValueBuilder
Helper variadic abstraction to allow extending to any MLIR op without boilerplate or Tablegen.
Typedefs
using linalg_copy = OperationBuilder< linalg::CopyOp >
using linalg_fill = OperationBuilder< linalg::FillOp >
using linalg_range = ValueBuilder< linalg::RangeOp >
using linalg_reshape = ValueBuilder< linalg::ReshapeOp >
using linalg_slice = ValueBuilder< linalg::SliceOp >
using linalg_yield = OperationBuilder< linalg::YieldOp >
using addf = ValueBuilder< AddFOp >
using affine_apply = ValueBuilder< AffineApplyOp >
using affine_if = OperationBuilder< AffineIfOp >
using affine_load = ValueBuilder< AffineLoadOp >
using affine_store = OperationBuilder< AffineStoreOp >
using alloc = ValueBuilder< AllocOp >
using call = OperationBuilder< mlir::CallOp >
using constant_float = ValueBuilder< ConstantFloatOp >
using constant_index = ValueBuilder< ConstantIndexOp >
using constant_int = ValueBuilder< ConstantIntOp >
using dealloc = OperationBuilder< DeallocOp >
using dim = ValueBuilder< DimOp >
using muli = ValueBuilder< MulIOp >
using mulf = ValueBuilder< MulFOp >
using memref_cast = ValueBuilder< MemRefCastOp >
using ret = OperationBuilder< ReturnOp >
using select = ValueBuilder< SelectOp >
using std_load = ValueBuilder< LoadOp >
using std_store = OperationBuilder< StoreOp >
using subi = ValueBuilder< SubIOp >
using tanh = ValueBuilder< TanhOp >
using view = ValueBuilder< ViewOp >
using zero_extendi = ValueBuilder< ZeroExtendIOp >
using sign_extendi = ValueBuilder< SignExtendIOp >
Functions
OperationHandle br (BlockHandle bh, ArrayRef< ValueHandle > operands)
Branches into the mlir::Block* captured by BlockHandle b with operands.
OperationHandle br (BlockHandle *bh, ArrayRef< ValueHandle *> captures, ArrayRef< ValueHandle > operands)
Creates a new mlir::Block* and branches to it from the current block.
OperationHandle cond_br (ValueHandle cond, BlockHandle trueBranch, ArrayRef< ValueHandle > trueOperands, BlockHandle falseBranch, ArrayRef< ValueHandle > falseOperands)
Branches into the mlir::Block* captured by BlockHandle trueBranch with trueOperands if cond evaluates to true (resp.
OperationHandle cond_br (ValueHandle cond, BlockHandle *trueBranch, ArrayRef< ValueHandle *> trueCaptures, ArrayRef< ValueHandle > trueOperands, BlockHandle *falseBranch, ArrayRef< ValueHandle *> falseCaptures, ArrayRef< ValueHandle > falseOperands)
Eagerly creates new mlir::Block* with argument types specified by trueOperands/falseOperands.
Detailed Description
Provides a set of first class intrinsics.
In the future, most of intrinsics related to Operation that don't contain other operations should be Tablegen'd.
Typedef Documentation
addf
using mlir::edsc::intrinsics::addf = typedef ValueBuilder<AddFOp>
Definition at line 194 of file Intrinsics.h.
affine_apply
using mlir::edsc::intrinsics::affine_apply = typedef ValueBuilder<AffineApplyOp>
Definition at line 195 of file Intrinsics.h.
affine_if
using mlir::edsc::intrinsics::affine_if = typedef OperationBuilder<AffineIfOp>
Definition at line 196 of file Intrinsics.h.
affine_load
using mlir::edsc::intrinsics::affine_load = typedef ValueBuilder<AffineLoadOp>
Definition at line 197 of file Intrinsics.h.
affine_store
using mlir::edsc::intrinsics::affine_store = typedef OperationBuilder<AffineStoreOp>
Definition at line 198 of file Intrinsics.h.
alloc
using mlir::edsc::intrinsics::alloc = typedef ValueBuilder<AllocOp>
Definition at line 199 of file Intrinsics.h.
call
using mlir::edsc::intrinsics::call = typedef OperationBuilder<mlir::CallOp>
Definition at line 200 of file Intrinsics.h.
constant_float
using mlir::edsc::intrinsics::constant_float = typedef ValueBuilder<ConstantFloatOp>
Definition at line 201 of file Intrinsics.h.
constant_index
using mlir::edsc::intrinsics::constant_index = typedef ValueBuilder<ConstantIndexOp>
Definition at line 202 of file Intrinsics.h.
constant_int
using mlir::edsc::intrinsics::constant_int = typedef ValueBuilder<ConstantIntOp>
Definition at line 203 of file Intrinsics.h.
dealloc
using mlir::edsc::intrinsics::dealloc = typedef OperationBuilder<DeallocOp>
Definition at line 204 of file Intrinsics.h.
dim
using mlir::edsc::intrinsics::dim = typedef ValueBuilder<DimOp>
Definition at line 205 of file Intrinsics.h.
linalg_copy
using mlir::edsc::intrinsics::linalg_copy = typedef OperationBuilder<linalg::CopyOp>
Definition at line 19 of file Intrinsics.h.
linalg_fill
using mlir::edsc::intrinsics::linalg_fill = typedef OperationBuilder<linalg::FillOp>
Definition at line 20 of file Intrinsics.h.
linalg_range
using mlir::edsc::intrinsics::linalg_range = typedef ValueBuilder<linalg::RangeOp>
Definition at line 21 of file Intrinsics.h.
linalg_reshape
using mlir::edsc::intrinsics::linalg_reshape = typedef ValueBuilder<linalg::ReshapeOp>
Definition at line 22 of file Intrinsics.h.
linalg_slice
using mlir::edsc::intrinsics::linalg_slice = typedef ValueBuilder<linalg::SliceOp>
Definition at line 23 of file Intrinsics.h.
linalg_yield
using mlir::edsc::intrinsics::linalg_yield = typedef OperationBuilder<linalg::YieldOp>
Definition at line 24 of file Intrinsics.h.
memref_cast
using mlir::edsc::intrinsics::memref_cast = typedef ValueBuilder<MemRefCastOp>
Definition at line 208 of file Intrinsics.h.
mulf
using mlir::edsc::intrinsics::mulf = typedef ValueBuilder<MulFOp>
Definition at line 207 of file Intrinsics.h.
muli
using mlir::edsc::intrinsics::muli = typedef ValueBuilder<MulIOp>
Definition at line 206 of file Intrinsics.h.
ret
using mlir::edsc::intrinsics::ret = typedef OperationBuilder<ReturnOp>
Definition at line 209 of file Intrinsics.h.
select
using mlir::edsc::intrinsics::select = typedef ValueBuilder<SelectOp>
Definition at line 210 of file Intrinsics.h.
sign_extendi
using mlir::edsc::intrinsics::sign_extendi = typedef ValueBuilder<SignExtendIOp>
Definition at line 217 of file Intrinsics.h.
std_load
using mlir::edsc::intrinsics::std_load = typedef ValueBuilder<LoadOp>
Definition at line 211 of file Intrinsics.h.
std_store
using mlir::edsc::intrinsics::std_store = typedef OperationBuilder<StoreOp>
Definition at line 212 of file Intrinsics.h.
subi
using mlir::edsc::intrinsics::subi = typedef ValueBuilder<SubIOp>
Definition at line 213 of file Intrinsics.h.
tanh
using mlir::edsc::intrinsics::tanh = typedef ValueBuilder<TanhOp>
Definition at line 214 of file Intrinsics.h.
view
using mlir::edsc::intrinsics::view = typedef ValueBuilder<ViewOp>
Definition at line 215 of file Intrinsics.h.
zero_extendi
using mlir::edsc::intrinsics::zero_extendi = typedef ValueBuilder<ZeroExtendIOp>
Definition at line 216 of file Intrinsics.h.
Function Documentation
br() [1/2]
OperationHandle mlir::edsc::intrinsics::br (BlockHandle bh, ArrayRef< ValueHandle > operands)
Branches into the mlir::Block* captured by BlockHandle b with operands.
Prerequisites: All Handles have already captured previously constructed IR objects.
Definition at line 16 of file Intrinsics.cpp.
References mlir::edsc::BlockHandle::getBlock().
Referenced by diag(), and getICmpPredicate().
br() [2/2]
OperationHandle mlir::edsc::intrinsics::br (BlockHandle * bh, ArrayRef< ValueHandle *> captures, ArrayRef< ValueHandle > operands)
Creates a new mlir::Block* and branches to it from the current block.
Argument types are specified by operands. Captures the new block in bh and the actual operands in captures. To insert the new mlir::Block*, a local ScopedContext is constructed and released to the current block. The branch operation is then added to the new block.
Prerequisites: b has not yet captured an mlir::Block*. No captures have captured any mlir::Value. All operands have already captured an mlir::Value captures.size() == operands.size() captures and operands are pairwise of the same type.
Definition at line 40 of file Intrinsics.cpp.
References enforceEmptyCapturesMatchOperands(), and mlir::edsc::BlockHandle::getBlock().
cond_br() [1/2]
OperationHandle mlir::edsc::intrinsics::cond_br (ValueHandle cond, BlockHandle trueBranch, ArrayRef< ValueHandle > trueOperands, BlockHandle falseBranch, ArrayRef< ValueHandle > falseOperands)
Branches into the mlir::Block* captured by BlockHandle trueBranch with trueOperands if cond evaluates to true (resp.
falseBranch and falseOperand if cond evaluates to false).
Prerequisites: All Handles have captured previously constructed IR objects.
Definition at line 51 of file Intrinsics.cpp.
References mlir::edsc::BlockHandle::getBlock().
cond_br() [2/2]
OperationHandle mlir::edsc::intrinsics::cond_br (ValueHandle cond, BlockHandle * trueBranch, ArrayRef< ValueHandle *> trueCaptures, ArrayRef< ValueHandle > trueOperands, BlockHandle * falseBranch, ArrayRef< ValueHandle *> falseCaptures, ArrayRef< ValueHandle > falseOperands)
Eagerly creates new mlir::Block* with argument types specified by trueOperands/falseOperands.
Captures the new blocks in trueBranch/falseBranch and the arguments in trueCaptures/falseCaptures. To insert the new mlir::Block*, a local ScopedContext is constructed and released. The branch operation is then added in the original location and targeting the eagerly constructed blocks.
Prerequisites: trueBranch/falseBranch has not yet captured an mlir::Block*. No trueCaptures/falseCaptures have captured any mlir::Value. All trueOperands/trueOperands have already captured an mlir::Value trueCaptures.size() == trueOperands.size() falseCaptures.size() == falseOperands.size() trueCaptures and trueOperands are pairwise of the same type falseCaptures and falseOperands are pairwise of the same type.
Definition at line 61 of file Intrinsics.cpp.
References enforceEmptyCapturesMatchOperands(), and mlir::edsc::BlockHandle::getBlock().