MLIR: mlir::functional Namespace Reference
mlir::functional Namespace Reference
Classes
struct ScopeGuard
Simple ScopeGuard.
Functions
template<typename Fn , typename IterType >
auto map (Fn fun, IterType begin, IterType end) -> SmallVector< typename std::result_of< Fn(decltype(*begin))>::type, 8 >
Map with iterators.
template<typename Fn , typename ContainerType >
auto map (Fn fun, ContainerType input) -> decltype(map(fun, std::begin(input), std::end(input)))
Map with templated container.
template<typename Fn , typename ContainerType1 , typename ContainerType2 >
auto zipMap (Fn fun, ContainerType1 input1, ContainerType2 input2) -> SmallVector< typename std::result_of< Fn(decltype(*input1.begin()), decltype(*input2.begin()))>::type, 8 >
Zip map with 2 templated container, iterates to the min of the sizes of the 2 containers.
template<typename Fn , typename IterType >
void apply (Fn fun, IterType begin, IterType end)
Apply with iterators.
template<typename Fn , typename ContainerType >
void apply (Fn fun, ContainerType input)
Apply with templated container.
template<typename Fn , typename ContainerType1 , typename ContainerType2 >
void zipApply (Fn fun, ContainerType1 input1, ContainerType2 input2)
Zip apply with 2 templated container, iterates to the min of the sizes of the 2 containers.
template<typename T , typename ToType = T>
std::function< ToType *(T *)> makePtrDynCaster ()
Unwraps a pointer type to another type (possibly the same).
Function Documentation
apply() [1/2]
template<typename Fn , typename IterType > void mlir::functional::apply (Fn fun, IterType begin, IterType end)
Apply with iterators.
Definition at line 67 of file Functional.h.
Referenced by apply(), and mlir::canonicalizeSetAndOperands().
apply() [2/2]
template<typename Fn , typename ContainerType > void mlir::functional::apply (Fn fun, ContainerType input)
Apply with templated container.
Definition at line 77 of file Functional.h.
References apply().
makePtrDynCaster()
template<typename T , typename ToType = T> std::function<ToType *(T *)> mlir::functional::makePtrDynCaster () inline
Unwraps a pointer type to another type (possibly the same).
Used in particular to allow easier compositions of Operation::operand_range types.
Definition at line 96 of file Functional.h.
Referenced by makePermutationMap().
map() [1/2]
template<typename Fn , typename IterType > auto mlir::functional::map (Fn fun, IterType begin, IterType end) -> SmallVector<typename std::result_of<Fn(decltype(*begin))>::type, 8>
Map with iterators.
Definition at line 28 of file Functional.h.
Referenced by addDomainConstraints(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), mlir::AffineApplyNormalizer::AffineApplyNormalizer(), mlir::AffineValueMap::AffineValueMap(), canonicalizeLoopBounds(), mlir::canonicalizeMapAndOperands(), mlir::canonicalizeSetAndOperands(), canRegisterAlias(), mlir::AffineExpr::cast(), cloneWithLoopRanges(), computeConversionSet(), createBinaryIndexHandle(), emitLoopRanges(), emitOrFoldComposedAffineApply(), expandAffineMap(), extractSymbolReference(), mlir::FlatAffineConstraints::FlatAffineConstraints(), mlir::AffineApplyOp::fold(), generateCopy(), generateTransferOpSlices(), mlir::MemRefAccess::getAccessMap(), mlir::Builder::getAffineMapArrayAttr(), getAffineMaps(), mlir::MemRefType::getChecked(), mlir::getConstantTripCount(), mlir::AffineMap::getContext(), getDimMap(), mlir::Builder::getF32ArrayAttr(), mlir::Builder::getF64ArrayAttr(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexArrayAttr(), getIndexingMaps(), mlir::getLargestDivisorOfTripCount(), mlir::AffineBound::getMap(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineValueMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineBound::getOperands(), mlir::AffineStoreOp::getOperationName(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), mlir::Builder::getStrArrayAttr(), mlir::Builder::getType(), getViewDefiningLoopRange(), mlir::linalg::getViewSizes(), mlir::hash_value(), inlineBeneficiaryOps(), mlir::detail::NestedAnalysisMap::invalidate(), mlir::inversePermutation(), mlir::makeComposedAffineApply(), mlir::edsc::makeGenericLinalgOp(), makeI64ArrayAttr(), makePermutationMap(), makeTiledViews(), map(), mlir::MutableAffineMap::MutableAffineMap(), mlir::AffineMap::operator bool(), mlir::edsc::ValueHandle::operator bool(), mlir::AffineExpr::operator!(), mlir::AffineMap::operator!=(), mlir::AffineMap::operator==(), mlir::AffineApplyOp::parse(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), parseBound(), permuteIvs(), printBound(), printDenseFloatElement(), promoteComposedSymbolsAsDims(), mlir::FlatAffineConstraints::setIdValues(), mlir::UnrankedMemRefDescriptor::setMemRefDescPtr(), mlir::AffineApplyOp::verify(), verify(), verifyDimMap(), and mlir::AsmState::~AsmState().
map() [2/2]
template<typename Fn , typename ContainerType > auto mlir::functional::map (Fn fun, ContainerType input) -> decltype(map(fun, std::begin(input), std::end(input)))
Map with templated container.
Definition at line 42 of file Functional.h.
References map().
zipApply()
template<typename Fn , typename ContainerType1 , typename ContainerType2 > void mlir::functional::zipApply (Fn fun, ContainerType1 input1, ContainerType2 input2)
Zip apply with 2 templated container, iterates to the min of the sizes of the 2 containers.
TODO(ntv): make variadic when needed.
Definition at line 85 of file Functional.h.
Referenced by mlir::shapeRatio().
zipMap()
template<typename Fn , typename ContainerType1 , typename ContainerType2 > auto mlir::functional::zipMap (Fn fun, ContainerType1 input1, ContainerType2 input2) -> SmallVector<typename std::result_of<Fn(decltype(*input1.begin()), decltype(*input2.begin()))>::type, 8>
Zip map with 2 templated container, iterates to the min of the sizes of the 2 containers.
TODO(ntv): make variadic when needed.
Definition at line 51 of file Functional.h.
Referenced by generateExtractSlicesOpResultType(), generateTransferOpSlices(), isValidExtractOrInsertSlicesType(), and unrollSingleResultStructuredOp().