MLIR: lib/Dialect/LLVMIR/IR/NVVMDialect.cpp File Reference
NVVMDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/NVVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/NVVMOps.cpp.inc"
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::NVVM
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void printNVVMIntrinsicOp (OpAsmPrinter &p, Operation *op)
static LLVM::LLVMDialect * getLlvmDialect (OpAsmParser &parser)
static ParseResult parseNVVMShflSyncBflyOp (OpAsmParser &parser, OperationState &result)
static ParseResult parseNVVMVoteBallotOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (MmaOp op)
Variables
static DialectRegistration< NVVMDialect > nvvmDialect
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 157 of file NVVMDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getLlvmDialect()
static LLVM::LLVMDialect* getLlvmDialect (OpAsmParser & parser) static
Definition at line 44 of file NVVMDialect.cpp.
References mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), and mlir::MLIRContext::getRegisteredDialect().
Referenced by parseNVVMShflSyncBflyOp(), and parseNVVMVoteBallotOp().
parseNVVMShflSyncBflyOp()
static ParseResult parseNVVMShflSyncBflyOp (OpAsmParser & parser, OperationState & result) static
Definition at line 53 of file NVVMDialect.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::LLVM::LLVMType::getInt32Ty(), getLlvmDialect(), mlir::OpAsmParser::getNameLoc(), mlir::LLVM::LLVMType::getStructElementType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseNVVMVoteBallotOp()
static ParseResult parseNVVMVoteBallotOp (OpAsmParser & parser, OperationState & result) static
Definition at line 78 of file NVVMDialect.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt32Ty(), getLlvmDialect(), mlir::OpAsmParser::getNameLoc(), llvmDialect, mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
printNVVMIntrinsicOp()
static void printNVVMIntrinsicOp (OpAsmPrinter & p, Operation * op) static
Definition at line 38 of file NVVMDialect.cpp.
References mlir::Operation::getName(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), and mlir::Operation::getResultTypes().
verify()
static LogicalResult verify (MmaOp op) static
Definition at line 94 of file NVVMDialect.cpp.
References mlir::LLVM::LLVMType::getFloatTy(), mlir::LLVM::LLVMType::getHalfTy(), mlir::LLVM::LLVMType::getStructTy(), mlir::StringAttr::getValue(), mlir::LLVM::LLVMType::getVectorTy(), and mlir::success().
Variable Documentation
nvvmDialect
DialectRegistration<NVVMDialect> nvvmDialect static
Definition at line 162 of file NVVMDialect.cpp.