MLIR: lib/IR/Operation.cpp File Reference
Operation.cpp File Reference
#include "mlir/IR/Operation.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/Support/CommandLine.h"
#include <numeric>
Functions
static llvm::cl::opt< bool > printOpOnDiagnostic ("mlir-print-op-on-diagnostic", llvm::cl::desc("When a diagnostic is emitted on an operation, also print " "the operation as an attached note"))
static Type getTensorOrVectorElementType (Type type)
If this is a vector type, or a tensor type, return the scalar element type that it is built around, otherwise return the type unmodified.
static LogicalResult verifySuccessor (Operation *op, unsigned succNo)
static LogicalResult verifyTerminatorSuccessors (Operation *op)
static LogicalResult verifyValueSizeAttr (Operation *op, StringRef attrName, bool isOperand)
Function Documentation
getTensorOrVectorElementType()
static Type getTensorOrVectorElementType (Type type) static
If this is a vector type, or a tensor type, return the scalar element type that it is built around, otherwise return the type unmodified.
Definition at line 785 of file Operation.cpp.
References mlir::Type::dyn_cast().
Referenced by mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreIntegerLike(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), and mlir::OpTrait::impl::verifyResultsAreIntegerLike().
printOpOnDiagnostic()
static llvm::cl::opt<bool> printOpOnDiagnostic ("mlir-print-op-on-diagnostic" , llvm::cl::desc("When a diagnostic is emitted on an operation, also print " "the operation as an attached note")) static
Referenced by mlir::Operation::emitError(), mlir::Operation::emitRemark(), and mlir::Operation::emitWarning().
verifySuccessor()
static LogicalResult verifySuccessor (Operation * op, unsigned succNo) static
Definition at line 944 of file Operation.cpp.
References mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), mlir::Operation::emitError(), mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::Operation::getNumSuccessorOperands(), mlir::Operation::getSuccessor(), mlir::Operation::getSuccessorOperands(), mlir::BlockArgument::getType(), and mlir::success().
Referenced by verifyTerminatorSuccessors().
verifyTerminatorSuccessors()
static LogicalResult verifyTerminatorSuccessors (Operation * op) static
Definition at line 964 of file Operation.cpp.
References mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getNumSuccessors(), mlir::Operation::getParentRegion(), mlir::Operation::getSuccessor(), mlir::success(), and verifySuccessor().
Referenced by mlir::OpTrait::impl::verifyIsTerminator().
verifyValueSizeAttr()
static LogicalResult verifyValueSizeAttr (Operation * op, StringRef attrName, bool isOperand) static
Definition at line 1016 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getAttrOfType(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::OpTrait::impl::verifyOperandSizeAttr(), and mlir::OpTrait::impl::verifyResultSizeAttr().