MLIR: lib/Dialect/StandardOps/Ops.cpp File Reference
Ops.cpp File Reference
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Support/STLExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/StandardOps/OpsEnums.cpp.inc"
#include "mlir/Dialect/StandardOps/Ops.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void printStandardUnaryOp (Operation *op, OpAsmPrinter &p)
A custom unary operation printer that omits the "std." prefix from the operation names.
static void printStandardBinaryOp (Operation *op, OpAsmPrinter &p)
A custom binary operation printer that omits the "std." prefix from the operation names.
static void printStandardCastOp (Operation *op, OpAsmPrinter &p)
A custom cast operation printer that omits the "std." prefix from the operation names.
template<typename T >
static LogicalResult verifyCastOp (T op)
A custom cast operation verifier.
static detail::op_matcher< ConstantIndexOp > m_ConstantIndex ()
Matches a ConstantIndexOp.
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
static void print (OpAsmPrinter &p, AllocOp op)
static ParseResult parseAllocOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (AllocOp op)
static ParseResult parseBranchOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, BranchOp op)
static LogicalResult verify (CallOp op)
static ParseResult parseCallIndirectOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, CallIndirectOp op)
static LogicalResult verify (CallIndirectOp op)
static Type getCheckedI1SameShape (Builder *build, Type type)
static Type getI1SameShape (Builder *build, Type type)
static void buildCmpIOp (Builder *build, OperationState &result, CmpIPredicate predicate, Value lhs, Value rhs)
static ParseResult parseCmpIOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, CmpIOp op)
static bool applyCmpPredicate (CmpIPredicate predicate, const APInt &lhs, const APInt &rhs)
static const char *const * getCmpFPredicateNames ()
static void buildCmpFOp (Builder *build, OperationState &result, CmpFPredicate predicate, Value lhs, Value rhs)
static ParseResult parseCmpFOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, CmpFOp op)
static LogicalResult verify (CmpFOp op)
static bool applyCmpPredicate (CmpFPredicate predicate, const APFloat &lhs, const APFloat &rhs)
static ParseResult parseCondBranchOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, CondBranchOp op)
static void print (OpAsmPrinter &p, ConstantOp &op)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ConstantOp &op)
The constant op requires an attribute, and furthermore requires that it matches the return type.
static LogicalResult verify (DeallocOp op)
static void print (OpAsmPrinter &p, DimOp op)
static ParseResult parseDimOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (DimOp op)
static void print (OpAsmPrinter &p, ExtractElementOp op)
static ParseResult parseExtractElementOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ExtractElementOp op)
static void print (OpAsmPrinter &p, LoadOp op)
static ParseResult parseLoadOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (LoadOp op)
static void print (OpAsmPrinter &p, PrefetchOp op)
static ParseResult parsePrefetchOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (PrefetchOp op)
static ParseResult parseReturnOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReturnOp op)
static LogicalResult verify (ReturnOp op)
static ParseResult parseSelectOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, SelectOp op)
static LogicalResult verify (SelectOp op)
static LogicalResult verify (SignExtendIOp op)
static void print (OpAsmPrinter &p, SplatOp op)
static ParseResult parseSplatOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (SplatOp op)
static void print (OpAsmPrinter &p, StoreOp op)
static ParseResult parseStoreOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (StoreOp op)
static Type getTensorTypeFromMemRefType (Builder &b, Type type)
static void print (OpAsmPrinter &p, TensorLoadOp op)
static ParseResult parseTensorLoadOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, TensorStoreOp op)
static ParseResult parseTensorStoreOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (TruncateIOp op)
static ParseResult parseViewOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ViewOp op)
static LogicalResult verifyDynamicStrides (MemRefType memrefType, ArrayRef< int64_t > strides)
static LogicalResult verify (ViewOp op)
static Type inferSubViewResultType (MemRefType memRefType)
static ParseResult parseSubViewOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, SubViewOp op)
static LogicalResult verify (SubViewOp op)
static LogicalResult verify (ZeroExtendIOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2943 of file Ops.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
applyCmpPredicate() [1/2]
static bool applyCmpPredicate (CmpIPredicate predicate, const APInt & lhs, const APInt & rhs) static
Definition at line 648 of file Ops.cpp.
References mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::Dialect::getContext(), and mlir::IntegerAttr::getValue().
Referenced by applyCmpPredicate().
applyCmpPredicate() [2/2]
static bool applyCmpPredicate (CmpFPredicate predicate, const APFloat & lhs, const APFloat & rhs) static
Definition at line 817 of file Ops.cpp.
References mlir::AlwaysFalse, mlir::AlwaysTrue, applyCmpPredicate(), mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::Dialect::getContext(), mlir::FloatAttr::getValue(), mlir::m_NonZero(), mlir::m_Zero(), mlir::matchPattern(), mlir::OEQ, mlir::OGE, mlir::OGT, mlir::OLE, mlir::OLT, mlir::ONE, mlir::ORD, mlir::PatternRewriter::replaceOpWithNewOp(), mlir::UEQ, mlir::UGE, mlir::UGT, mlir::ULE, mlir::ULT, mlir::UNE, and mlir::UNO.
buildCmpFOp()
static void buildCmpFOp (Builder * build, OperationState & result, CmpFPredicate predicate, Value lhs, Value rhs) static
Definition at line 741 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
buildCmpIOp()
static void buildCmpIOp (Builder * build, OperationState & result, CmpIPredicate predicate, Value lhs, Value rhs) static
Definition at line 588 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
It folds the source of any memref_cast into the root operation directly.
Definition at line 209 of file Ops.cpp.
References mlir::Operation::getOpOperands(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
Referenced by mlir::DmaStartOp::fold(), mlir::DmaWaitOp::fold(), and verify().
getCheckedI1SameShape()
static Type getCheckedI1SameShape (Builder * build, Type type) static
Definition at line 565 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), mlir::Builder::getI1Type(), mlir::Type::isa(), mlir::Type::isIntOrIndexOrFloat(), and mlir::StandardAttributes::Type.
Referenced by getI1SameShape(), parseCmpFOp(), parseCmpIOp(), and parseSelectOp().
getCmpFPredicateNames()
static const char* const* getCmpFPredicateNames () inline static
Definition at line 693 of file Ops.cpp.
References mlir::AlwaysFalse, mlir::AlwaysTrue, mlir::NumPredicates, mlir::OEQ, mlir::OGE, mlir::OGT, mlir::OLE, mlir::OLT, mlir::ONE, mlir::ORD, mlir::UEQ, mlir::UGE, mlir::UGT, mlir::ULE, mlir::ULT, mlir::UNE, and mlir::UNO.
Referenced by print().
getI1SameShape()
static Type getI1SameShape (Builder * build, Type type) static
Definition at line 578 of file Ops.cpp.
References getCheckedI1SameShape().
Referenced by buildCmpFOp(), and buildCmpIOp().
getTensorTypeFromMemRefType()
static Type getTensorTypeFromMemRefType (Builder & b, Type type) static
Definition at line 2186 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::RankedTensorType::get(), and mlir::Builder::getNoneType().
Referenced by parseTensorLoadOp(), and parseTensorStoreOp().
inferSubViewResultType()
static Type inferSubViewResultType (MemRefType memRefType) static
Definition at line 2507 of file Ops.cpp.
References mlir::OperationState::addAttributes(), mlir::Type::cast(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::Builder::getI32VectorAttr(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::ShapedType::kDynamicSize, mlir::makeStridedLinearLayoutMap(), mlir::MemRefType::Builder::setAffineMaps(), mlir::MemRefType::Builder::setShape(), mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), and mlir::succeeded().
m_ConstantIndex()
static detail::op_matcher<ConstantIndexOp> m_ConstantIndex () static
Matches a ConstantIndexOp.
TODO: This should probably just be a general matcher that uses m_Constant and checks the operation for an index type.
Definition at line 198 of file Ops.cpp.
Referenced by mlir::operator<<(), and verify().
parseAllocOp()
static ParseResult parseAllocOp (OpAsmParser & parser, OperationState & result) static
Definition at line 258 of file Ops.cpp.
References mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::parseDimAndSymbolList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::success(), and mlir::OperationState::types.
parseBranchOp()
static ParseResult parseBranchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 417 of file Ops.cpp.
References mlir::OperationState::addSuccessor(), mlir::failure(), mlir::OpAsmParser::parseSuccessorAndUseList(), and mlir::success().
parseCallIndirectOp()
static ParseResult parseCallIndirectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 508 of file Ops.cpp.
References mlir::OpAsmParser::addTypesToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::FunctionType::getInputs(), mlir::FunctionType::getResults(), mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseCmpFOp()
static ParseResult parseCmpFOp (OpAsmParser & parser, OperationState & result) static
Definition at line 750 of file Ops.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Attribute::cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), getCheckedI1SameShape(), mlir::OpAsmParser::getNameLoc(), mlir::Attribute::isa(), mlir::NumPredicates, mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseCmpIOp()
static ParseResult parseCmpIOp (OpAsmParser & parser, OperationState & result) static
Definition at line 597 of file Ops.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Attribute::cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), getCheckedI1SameShape(), mlir::OpAsmParser::getNameLoc(), mlir::Attribute::isa(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseCondBranchOp()
static ParseResult parseCondBranchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 909 of file Ops.cpp.
References mlir::OperationState::addSuccessor(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI1Type(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseSuccessorAndUseList(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 967 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OperationState::types.
parseDimOp()
static ParseResult parseDimOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1190 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseExtractElementOp()
static ParseResult parseExtractElementOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1519 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::ShapedType::getElementType(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
parseLoadOp()
static ParseResult parseLoadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1599 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
parsePrefetchOp()
static ParseResult parsePrefetchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1752 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseGreater(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::success().
parseReturnOp()
static ParseResult parseReturnOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1874 of file Ops.cpp.
References mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), and mlir::OpAsmParser::resolveOperands().
parseSelectOp()
static ParseResult parseSelectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1922 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), getCheckedI1SameShape(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
parseSplatOp()
static ParseResult parseSplatOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2005 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::ShapedType::getElementType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseStoreOp()
static ParseResult parseStoreOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2055 of file Ops.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::OpAsmParser::Square.
parseSubViewOp()
static ParseResult parseSubViewOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2549 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
parseTensorLoadOp()
static ParseResult parseTensorLoadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2202 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), getTensorTypeFromMemRefType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseTensorStoreOp()
static ParseResult parseTensorStoreOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2225 of file Ops.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), getTensorTypeFromMemRefType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OpAsmParser::resolveOperands().
parseViewOp()
static ParseResult parseViewOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2264 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
print() [1/19]
static void print (OpAsmPrinter & p, AllocOp op) static
Definition at line 247 of file Ops.cpp.
References mlir::printDimAndSymbolList(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [2/19]
static void print (OpAsmPrinter & p, BranchOp op) static
Definition at line 426 of file Ops.cpp.
References mlir::OwningRewritePatternList::insert(), and mlir::OpAsmPrinter::printSuccessorAndUseList().
print() [3/19]
static void print (OpAsmPrinter & p, CallIndirectOp op) static
Definition at line 525 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [4/19]
static void print (OpAsmPrinter & p, CmpIOp op) static
Definition at line 633 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [5/19]
static void print (OpAsmPrinter & p, CmpFOp op) static
Definition at line 787 of file Ops.cpp.
References mlir::FirstValidValue, getCmpFPredicateNames(), mlir::NumPredicates, and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [6/19]
static void print (OpAsmPrinter & p, CondBranchOp op) static
Definition at line 938 of file Ops.cpp.
References mlir::OwningRewritePatternList::insert(), and mlir::OpAsmPrinter::printSuccessorAndUseList().
print() [7/19]
static void print (OpAsmPrinter & p, ConstantOp & op) static
Definition at line 954 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [8/19]
static void print (OpAsmPrinter & p, DimOp op) static
Definition at line 1184 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [9/19]
static void print (OpAsmPrinter & p, ExtractElementOp op) static
Definition at line 1512 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [10/19]
static void print (OpAsmPrinter & p, LoadOp op) static
Definition at line 1593 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [11/19]
static void print (OpAsmPrinter & p, PrefetchOp op) static
Definition at line 1740 of file Ops.cpp.
References mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [12/19]
static void print (OpAsmPrinter & p, ReturnOp op) static
Definition at line 1883 of file Ops.cpp.
print() [13/19]
static void print (OpAsmPrinter & p, SelectOp op) static
Definition at line 1942 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [14/19]
static void print (OpAsmPrinter & p, SplatOp op) static
Definition at line 1999 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [15/19]
static void print (OpAsmPrinter & p, StoreOp op) static
Definition at line 2048 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [16/19]
static void print (OpAsmPrinter & p, TensorLoadOp op) static
Definition at line 2196 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [17/19]
static void print (OpAsmPrinter & p, TensorStoreOp op) static
Definition at line 2219 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [18/19]
static void print (OpAsmPrinter & p, ViewOp op) static
Definition at line 2289 of file Ops.cpp.
References mlir::MemRefType::getDynamicStrideOrOffset(), mlir::getStridesAndOffset(), mlir::OpAsmPrinter::printOperand(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::succeeded().
print() [19/19]
static void print (OpAsmPrinter & p, SubViewOp op) static
Definition at line 2581 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printStandardBinaryOp()
static void printStandardBinaryOp (Operation * op, OpAsmPrinter & p) static
A custom binary operation printer that omits the "std." prefix from the operation names.
Definition at line 106 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::StandardOpsDialect::getDialectNamespace(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), mlir::Value::getType(), mlir::OpAsmPrinter::printGenericOp(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printStandardCastOp()
static void printStandardCastOp (Operation * op, OpAsmPrinter & p) static
A custom cast operation printer that omits the "std." prefix from the operation names.
Definition at line 130 of file Ops.cpp.
References mlir::StandardOpsDialect::getDialectNamespace(), mlir::Operation::getName(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), and mlir::Value::getType().
printStandardUnaryOp()
static void printStandardUnaryOp (Operation * op, OpAsmPrinter & p) static
A custom unary operation printer that omits the "std." prefix from the operation names.
Definition at line 93 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::StandardOpsDialect::getDialectNamespace(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::OperationName::getStringRef(), mlir::Value::getType(), and mlir::OpAsmPrinter::printOptionalAttrDict().
verify() [1/19]
static LogicalResult verify (AllocOp op) static
Definition at line 283 of file Ops.cpp.
References mlir::PatternRewriter::create(), mlir::PatternRewriter::eraseOp(), mlir::AffineMap::getNumSymbols(), mlir::Block::getPredecessors(), mlir::has_single_element(), mlir::OwningRewritePatternList::insert(), m_ConstantIndex(), mlir::matchPattern(), mlir::PatternRewriter::mergeBlocks(), mlir::PatternRewriter::replaceOp(), mlir::MemRefType::Builder::setShape(), and mlir::success().
verify() [2/19]
static LogicalResult verify (CallOp op) static
Definition at line 448 of file Ops.cpp.
References mlir::OpState::emitOpError(), mlir::FunctionType::get(), mlir::Dialect::getContext(), mlir::m_Constant(), mlir::matchPattern(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
verify() [3/19]
static LogicalResult verify (CallIndirectOp op) static
Definition at line 531 of file Ops.cpp.
References mlir::OwningRewritePatternList::insert(), and mlir::success().
verify() [4/19]
static LogicalResult verify (CmpFOp op) static
Definition at line 802 of file Ops.cpp.
References mlir::FirstValidValue, mlir::IntegerAttr::getInt(), mlir::NumPredicates, and mlir::success().
verify() [5/19]
static LogicalResult verify (ConstantOp & op) static
The constant op requires an attribute, and furthermore requires that it matches the return type.
Definition at line 987 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::Attribute::getType(), mlir::IntegerType::getWidth(), mlir::Attribute::isa(), mlir::Type::isa(), and mlir::success().
verify() [6/19]
static LogicalResult verify (DeallocOp op) static
Definition at line 1163 of file Ops.cpp.
References foldMemRefCast(), mlir::OwningRewritePatternList::insert(), and mlir::success().
verify() [7/19]
static LogicalResult verify (DimOp op) static
Definition at line 1205 of file Ops.cpp.
References mlir::Type::dyn_cast(), foldMemRefCast(), mlir::IndexType::get(), mlir::IntegerAttr::get(), mlir::Dialect::getContext(), mlir::IntegerAttr::getValue(), mlir::Type::isa(), mlir::ShapedType::isDynamic(), mlir::succeeded(), and mlir::success().
verify() [8/19]
static LogicalResult verify (ExtractElementOp op) static
Definition at line 1536 of file Ops.cpp.
References mlir::IntegerAttr::getInt(), mlir::ElementsAttr::getValue(), mlir::Type::isa(), mlir::Type::isIndex(), and mlir::success().
verify() [9/19]
static LogicalResult verify (LoadOp op) static
Definition at line 1615 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), mlir::impl::foldCastOp(), foldMemRefCast(), mlir::MemRefType::getAffineMaps(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefType::getMemorySpace(), mlir::UnrankedMemRefType::getMemorySpace(), mlir::getStridesAndOffset(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), mlir::succeeded(), and mlir::success().
verify() [10/19]
static LogicalResult verify (PrefetchOp op) static
Definition at line 1793 of file Ops.cpp.
References mlir::Type::dyn_cast(), foldMemRefCast(), mlir::IndexType::get(), mlir::IntegerAttr::get(), mlir::Dialect::getContext(), mlir::IntegerAttr::getValue(), and mlir::success().
verify() [11/19]
static LogicalResult verify (ReturnOp op) static
Definition at line 1889 of file Ops.cpp.
References mlir::Type::isa(), and mlir::success().
verify() [12/19]
static LogicalResult verify (SelectOp op) static
Definition at line 1947 of file Ops.cpp.
References mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verify() [13/19]
static LogicalResult verify (SignExtendIOp op) static
Definition at line 1975 of file Ops.cpp.
References mlir::getElementTypeOrSelf(), mlir::IntegerType::getWidth(), and mlir::success().
verify() [14/19]
static LogicalResult verify (SplatOp op) static
Definition at line 2018 of file Ops.cpp.
References mlir::DenseElementsAttr::get(), getElementType(), and mlir::success().
verify() [15/19]
static LogicalResult verify (StoreOp op) static
Definition at line 2074 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::impl::foldCastOp(), foldMemRefCast(), mlir::Dialect::getContext(), mlir::ShapedType::getElementType(), mlir::Builder::getZeroAttr(), mlir::m_Zero(), mlir::matchPattern(), mlir::succeeded(), mlir::success(), and mlir::verifyCompatibleShape().
verify() [16/19]
static LogicalResult verify (TruncateIOp op) static
Definition at line 2243 of file Ops.cpp.
References mlir::getElementTypeOrSelf(), mlir::IntegerType::getWidth(), and mlir::success().
verify() [17/19]
static LogicalResult verify (ViewOp op) static
Definition at line 2327 of file Ops.cpp.
References mlir::PatternRewriter::create(), mlir::failed(), mlir::Builder::getContext(), mlir::Value::getDefiningOp(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefType::getMemorySpace(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::getStridesAndOffset(), mlir::OwningRewritePatternList::insert(), mlir::ShapedType::isDynamic(), m_ConstantIndex(), mlir::makeStridedLinearLayoutMap(), mlir::functional::map(), mlir::matchPattern(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::MemRefType::Builder::setAffineMaps(), mlir::MemRefType::Builder::setShape(), mlir::success(), and verifyDynamicStrides().
verify() [18/19]
static LogicalResult verify (SubViewOp op) static
Definition at line 2591 of file Ops.cpp.
References mlir::detail::enumerate(), mlir::failed(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefType::getMemorySpace(), mlir::getStridesAndOffset(), mlir::ShapedType::kDynamicSize, and mlir::success().
verify() [19/19]
static LogicalResult verify (ZeroExtendIOp op) static
Definition at line 2900 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::getElementTypeOrSelf(), mlir::IntegerType::getWidth(), and mlir::success().
verifyCastOp()
template<typename T > static LogicalResult verifyCastOp (T op) static
A custom cast operation verifier.
Definition at line 138 of file Ops.cpp.
References mlir::success().
verifyDynamicStrides()
static LogicalResult verifyDynamicStrides (MemRefType memrefType, ArrayRef< int64_t > strides) static
Definition at line 2310 of file Ops.cpp.
References mlir::failure(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefType::getShape(), mlir::ShapedType::isDynamic(), and mlir::success().
Referenced by verify().