MLIR: lib/Analysis/OpStats.cpp File Reference
OpStats.cpp File Reference
#include "mlir/IR/Module.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/Pass/Pass.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
Variables
static PassRegistration< PrintOpStatsPass > pass ("print-op-stats", "Print statistics of operations")
Variable Documentation
pass
PassRegistration<PrintOpStatsPass> pass("print-op-stats", "Print statistics of operations") static
Referenced by buildDefaultRegistryFn(), mlir::detail::OpPassManagerImpl::coalesceAdjacentAdaptorPasses(), mlir::detail::OpToOpPassAdaptorParallel::getParallelPassManagers(), mlir::detail::isAdaptorPass(), isHiddenPass(), mlir::detail::OpPassManagerImpl::mergeInto(), mlir::OpPassManager::mergeStatisticsInto(), mlir::OpPassManager::nest(), mlir::OpPassManager::operator=(), populatePassManagers(), prepareStatistics(), mlir::OpPassManager::printAsTextualPipeline(), printIR(), printResultsAsList(), printResultsAsPipeline(), and mlir::OpPassManager::run().