MLIR: lib/Pass/Pass.cpp File Reference
Pass.cpp File Reference
#include "mlir/Pass/Pass.h"
#include "PassDetail.h"
#include "mlir/Analysis/Verifier.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Module.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/CrashRecoveryContext.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/ToolOutputFile.h"
Classes
struct mlir::detail::OpPassManagerImpl
struct mlir::detail::PassInstrumentorImpl
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::detail
Utilities for detecting if a given trait holds for some set of arguments 'Args'.
Functions
static LogicalResult runPipeline (OpPassManager &pm, Operation *op, AnalysisManager am)
Utility to run the given operation and analysis manager on a provided op pass manager.
static OpPassManager * findPassManagerFor (MutableArrayRef< OpPassManager > mgrs, const OperationName &name)
Find an operation pass manager that can operate on an operation of the given type, or nullptr if one does not exist.
static bool hasSizeMismatch (ArrayRef< OpPassManager > lhs, ArrayRef< OpPassManager > rhs)
Utility functor that checks if the two ranges of pass managers have a size mismatch.
static LogicalResult runWithCrashRecovery (OpPassManager &pm, ModuleAnalysisManager &am, ModuleOp module, StringRef crashReproducerFileName)
Safely run the pass manager over the given module, creating a reproducible on failure or crash.
Function Documentation
findPassManagerFor()
static OpPassManager* findPassManagerFor (MutableArrayRef< OpPassManager > mgrs, const OperationName & name) static
Find an operation pass manager that can operate on an operation of the given type, or nullptr if one does not exist.
Definition at line 321 of file Pass.cpp.
References mlir::OpPassManager::getOpName().
Referenced by mlir::detail::OpToOpPassAdaptorBase::mergeInto(), mlir::detail::OpToOpPassAdaptor::runOnOperation(), and mlir::detail::OpToOpPassAdaptorParallel::runOnOperation().
hasSizeMismatch()
static bool hasSizeMismatch (ArrayRef< OpPassManager > lhs, ArrayRef< OpPassManager > rhs) static
Utility functor that checks if the two ranges of pass managers have a size mismatch.
Definition at line 400 of file Pass.cpp.
Referenced by mlir::detail::OpToOpPassAdaptorParallel::runOnOperation().
runPipeline()
static LogicalResult runPipeline (OpPassManager & pm, Operation * op, AnalysisManager am) static
Utility to run the given operation and analysis manager on a provided op pass manager.
Definition at line 306 of file Pass.cpp.
References mlir::AnalysisManager::clear(), and mlir::OpPassManager::run().
Referenced by mlir::detail::OpToOpPassAdaptor::runOnOperation(), and mlir::detail::OpToOpPassAdaptorParallel::runOnOperation().
runWithCrashRecovery()
static LogicalResult runWithCrashRecovery (OpPassManager & pm, ModuleAnalysisManager & am, ModuleOp module, StringRef crashReproducerFileName) static
Safely run the pass manager over the given module, creating a reproducible on failure or crash.
Enable crash recovery.
Disable crash recovery.
Definition at line 504 of file Pass.cpp.
References mlir::Op< ConcreteType, Traits >::clone(), mlir::detail::OpPassManagerImpl::disableThreads, mlir::OpState::emitError(), mlir::emitError(), mlir::failure(), mlir::UnknownLoc::get(), mlir::OpPassManager::getContext(), mlir::OpPassManager::getImpl(), mlir::openOutputFile(), mlir::ModuleOp::print(), mlir::OpPassManager::printAsTextualPipeline(), mlir::OpPassManager::run(), mlir::succeeded(), mlir::success(), and mlir::detail::OpPassManagerImpl::verifyPasses.
Referenced by mlir::PassManager::run().