MLIR: lib/Transforms/PipelineDataTransfer.cpp File Reference
PipelineDataTransfer.cpp File Reference
#include "mlir/Transforms/Passes.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/LoopUtils.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "affine-pipeline-data-transfer"
Functions
static unsigned getTagMemRefPos (Operation &dmaInst)
static bool doubleBuffer (Value oldMemRef, AffineForOp forOp)
Doubles the buffer of the supplied memref on the specified 'affine.for' operation by adding a leading dimension of size two to the memref.
static bool checkTagMatch (AffineDmaStartOp startOp, AffineDmaWaitOp waitOp)
static void findMatchingStartFinishInsts (AffineForOp forOp, SmallVectorImpl< std::pair< Operation *, Operation *>> &startWaitPairs)
Variables
static PassRegistration< PipelineDataTransfer > pass ("affine-pipeline-data-transfer", "Pipeline non-blocking data transfers between explicitly managed levels of " "the memory hierarchy")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-pipeline-data-transfer"
Definition at line 26 of file PipelineDataTransfer.cpp.
Function Documentation
checkTagMatch()
static bool checkTagMatch (AffineDmaStartOp startOp, AffineDmaWaitOp waitOp) static
Definition at line 143 of file PipelineDataTransfer.cpp.
References mlir::AffineDmaStartOp::getTagIndices(), mlir::AffineDmaWaitOp::getTagIndices(), mlir::AffineDmaStartOp::getTagMemRef(), and mlir::AffineDmaWaitOp::getTagMemRef().
Referenced by findMatchingStartFinishInsts().
doubleBuffer()
static bool doubleBuffer (Value oldMemRef, AffineForOp forOp) static
Doubles the buffer of the supplied memref on the specified 'affine.for' operation by adding a leading dimension of size two to the memref.
Replaces all uses of the old memref by the new one while indexing the newly added dimension by the loop IV of the specified 'affine.for' operation modulo 2. Returns false if such a replacement cannot be performed.
Definition at line 64 of file PipelineDataTransfer.cpp.
References mlir::StandardAttributes::AffineMap, mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpState::erase(), mlir::failed(), mlir::AffineMap::get(), mlir::MemRefType::get(), mlir::Value::getType(), mlir::replaceAllMemRefUsesWith(), and mlir::OpBuilder::setInsertionPointAfter().
Referenced by findMatchingStartFinishInsts().
findMatchingStartFinishInsts()
static void findMatchingStartFinishInsts (AffineForOp forOp, SmallVectorImpl< std::pair< Operation *, Operation *>> & startWaitPairs) static
Definition at line 166 of file PipelineDataTransfer.cpp.
References checkTagMatch(), mlir::createAffineComputationSlice(), doubleBuffer(), mlir::failed(), mlir::getConstantTripCount(), mlir::Value::getDefiningOp(), mlir::Builder::getI64IntegerAttr(), mlir::getReachableAffineApplyOps(), getTagMemRefPos(), mlir::Value::hasOneUse(), mlir::instBodySkew(), mlir::isInstwiseShiftValid(), pass, mlir::Value::use_empty(), and mlir::Value::user_begin().
getTagMemRefPos()
static unsigned getTagMemRefPos (Operation & dmaInst) static
Definition at line 50 of file PipelineDataTransfer.cpp.
Referenced by findMatchingStartFinishInsts().
Variable Documentation
pass
PassRegistration<PipelineDataTransfer> pass("affine-pipeline-data-transfer", "Pipeline non-blocking data transfers between explicitly managed levels of " "the memory hierarchy") static
Referenced by findMatchingStartFinishInsts().