MLIR: lib/TableGen/Predicate.cpp File Reference
Predicate.cpp File Reference
#include "mlir/TableGen/Predicate.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
Enumerations
enum PredCombinerKind
Functions
static PredCombinerKind getPredCombinerKind (const tblgen::Pred &pred)
static PredNode * buildPredicateTree (const tblgen::Pred &root, llvm::BumpPtrAllocator &allocator, ArrayRef< Subst > substitutions)
static PredNode * propagateGroundTruth (PredNode *node, const llvm::SmallPtrSetImpl< tblgen::Pred *> &knownTruePreds, const llvm::SmallPtrSetImpl< tblgen::Pred *> &knownFalsePreds)
static std::string combineBinary (ArrayRef< std::string > children, std::string combiner, std::string init)
static std::string combineNot (ArrayRef< std::string > children)
static std::string getCombinedCondition (const PredNode &root)
Enumeration Type Documentation
PredCombinerKind
enum PredCombinerKind strong
Definition at line 89 of file Predicate.cpp.
Function Documentation
buildPredicateTree()
static PredNode* buildPredicateTree (const tblgen::Pred & root, llvm::BumpPtrAllocator & allocator, ArrayRef< Subst > substitutions) static
Definition at line 139 of file Predicate.cpp.
References mlir::tblgen::Pred::getCondition(), getPredCombinerKind(), mlir::tblgen::ConcatPred::getPrefix(), and mlir::tblgen::Pred::isCombined().
Referenced by mlir::tblgen::CombinedPred::getConditionImpl().
combineBinary()
static std::string combineBinary (ArrayRef< std::string > children, std::string combiner, std::string init) static
Definition at line 276 of file Predicate.cpp.
Referenced by getCombinedCondition().
combineNot()
static std::string combineNot (ArrayRef< std::string > children) static
Definition at line 295 of file Predicate.cpp.
Referenced by getCombinedCondition().
getCombinedCondition()
static std::string getCombinedCondition (const PredNode & root) static
Definition at line 302 of file Predicate.cpp.
References combineBinary(), and combineNot().
Referenced by mlir::tblgen::CombinedPred::getConditionImpl().
getPredCombinerKind()
static PredCombinerKind getPredCombinerKind (const tblgen::Pred & pred) static
Definition at line 116 of file Predicate.cpp.
References mlir::tblgen::Pred::isCombined().
Referenced by buildPredicateTree().
propagateGroundTruth()
static PredNode* propagateGroundTruth (PredNode * node, const llvm::SmallPtrSetImpl< tblgen::Pred *> & knownTruePreds, const llvm::SmallPtrSetImpl< tblgen::Pred *> & knownFalsePreds) static
Definition at line 193 of file Predicate.cpp.
Referenced by mlir::tblgen::CombinedPred::getConditionImpl().