MLIR: lib/Dialect/Linalg/Transforms/Promotion.cpp File Reference
Promotion.cpp File Reference
#include "mlir/Dialect/Linalg/EDSC/Intrinsics.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/EDSC/Helpers.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/STLExtras.h"
#include "mlir/Transforms/FoldUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "linalg-promotion"
Functions
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options")
static llvm::cl::opt< bool > clPromoteDynamic ("test-linalg-promote-dynamic", llvm::cl::desc("Test generation of dynamic promoted buffers"), llvm::cl::cat(clOptionsCategory), llvm::cl::init(false))
static Value allocBuffer (Type elementType, Value size, bool dynamicBuffers)
static PromotionInfo promoteFullTileBuffer (OpBuilder &b, Location loc, SubViewOp subView, bool dynamicBuffers, OperationFolder *folder)
static void promoteSubViews (FuncOp f, bool dynamicBuffers)
Variables
static PassRegistration< LinalgPromotionPass > pass ("linalg-promote-subviews", "promote subview ops to local buffers", [] { return std::make_unique< LinalgPromotionPass >(clPromoteDynamic);})
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-promotion"
Definition at line 40 of file Promotion.cpp.
Function Documentation
allocBuffer()
static Value allocBuffer (Type elementType, Value size, bool dynamicBuffers) static
Definition at line 48 of file Promotion.cpp.
References mlir::IntegerType::get(), mlir::MemRefType::get(), mlir::Value::getContext(), mlir::Value::getDefiningOp(), and mlir::Type::getIntOrFloatBitWidth().
Referenced by promoteFullTileBuffer().
clOptionsCategory()
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options") static
clPromoteDynamic()
static llvm::cl::opt<bool> clPromoteDynamic ("test-linalg-promote-dynamic" , llvm::cl::desc("Test generation of dynamic promoted buffers") , llvm::cl::cat(clOptionsCategory) , llvm::cl::init(false)) static
Referenced by mlir::createLinalgPromotionPass().
promoteFullTileBuffer()
static PromotionInfo promoteFullTileBuffer (OpBuilder & b, Location loc, SubViewOp subView, bool dynamicBuffers, OperationFolder * folder) static
Definition at line 76 of file Promotion.cpp.
References allocBuffer(), mlir::detail::enumerate(), and mlir::MemRefType::get().
Referenced by mlir::linalg::promoteSubViews().
promoteSubViews()
static void promoteSubViews (FuncOp f, bool dynamicBuffers) static
Definition at line 206 of file Promotion.cpp.
References mlir::OpState::getContext(), mlir::linalg::promoteSubViewOperands(), and mlir::OpState::walk().
Referenced by mlir::linalg::promoteSubViews().
Variable Documentation
pass
PassRegistration<LinalgPromotionPass> pass("linalg-promote-subviews", "promote subview ops to local buffers", [] { return std::make_unique< LinalgPromotionPass >(clPromoteDynamic);}) static
Referenced by mlir::createLinalgPromotionPass().