MLIR: lib/Dialect/QuantOps/Utils/QuantizeUtils.cpp File Reference
QuantizeUtils.cpp File Reference
#include "mlir/Dialect/QuantOps/QuantizeUtils.h"
#include "mlir/Dialect/QuantOps/UniformSupport.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/StandardTypes.h"
Functions
static Attribute convertPrimitiveValueAttr (Attribute origRealValue, QuantizedType quantizedElementType, const UniformQuantizedValueConverter &converter, Type &outConvertedType)
Converts a possible primitive, real expressed value attribute to a corresponding storage attribute (typically FloatAttr -> IntegerAttr).
static DenseElementsAttr convertDenseFPElementsAttr (DenseFPElementsAttr realFPElementsAttr, QuantizedType quantizedElementType, const UniformQuantizedValueConverter &converter)
Converts a real expressed DenseFPElementsAttr to a corresponding DenseElementsAttr (typically DenseIntElementsAttr) containing quantized storage values assuming the given quantizedElementType and converter.
static SparseElementsAttr convertSparseElementsAttr (SparseElementsAttr realSparseAttr, QuantizedType quantizedElementType, const UniformQuantizedValueConverter &converter)
Converts a real expressed SplatElementsAttr to a corresponding SplatElementsAttr containing quantized storage values assuming the given quantizedElementType and converter.
Function Documentation
convertDenseFPElementsAttr()
static DenseElementsAttr convertDenseFPElementsAttr (DenseFPElementsAttr realFPElementsAttr, QuantizedType quantizedElementType, const UniformQuantizedValueConverter & converter) static
Converts a real expressed DenseFPElementsAttr to a corresponding DenseElementsAttr (typically DenseIntElementsAttr) containing quantized storage values assuming the given quantizedElementType and converter.
Definition at line 39 of file QuantizeUtils.cpp.
References mlir::DenseFPElementsAttr::begin(), mlir::quant::QuantizedType::castExpressedToStorageType(), mlir::DenseIntElementsAttr::get(), mlir::DenseElementsAttr::isSplat(), and mlir::quant::UniformQuantizedValueConverter::quantizeFloatToInt().
Referenced by convertSparseElementsAttr(), and mlir::quant::quantizeAttrUniform().
convertPrimitiveValueAttr()
static Attribute convertPrimitiveValueAttr (Attribute origRealValue, QuantizedType quantizedElementType, const UniformQuantizedValueConverter & converter, Type & outConvertedType) static
Converts a possible primitive, real expressed value attribute to a corresponding storage attribute (typically FloatAttr -> IntegerAttr).
quantizedElementType is the QuantizedType that describes the expressed origValue. Returns a converter Attribute or nullptr if conversion is not possible.
Definition at line 22 of file QuantizeUtils.cpp.
References mlir::Attribute::cast(), mlir::IntegerAttr::get(), mlir::quant::QuantizedType::getStorageType(), mlir::FloatAttr::getValue(), mlir::Attribute::isa(), and mlir::quant::UniformQuantizedValueConverter::quantizeFloatToInt().
Referenced by mlir::quant::quantizeAttrUniform().
convertSparseElementsAttr()
static SparseElementsAttr convertSparseElementsAttr (SparseElementsAttr realSparseAttr, QuantizedType quantizedElementType, const UniformQuantizedValueConverter & converter) static
Converts a real expressed SplatElementsAttr to a corresponding SplatElementsAttr containing quantized storage values assuming the given quantizedElementType and converter.
Definition at line 70 of file QuantizeUtils.cpp.
References mlir::quant::QuantizedType::castExpressedToStorageType(), convertDenseFPElementsAttr(), mlir::SparseElementsAttr::get(), mlir::SparseElementsAttr::getIndices(), and mlir::SparseElementsAttr::getValues().
Referenced by mlir::quant::quantizeAttrUniform().