MLIR: lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp File Reference
ROCDLDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/SourceMgr.h"
#include "mlir/Dialect/LLVMIR/ROCDLOps.cpp.inc"
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::ROCDL
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static void printROCDLOp (OpAsmPrinter &p, Operation *op)
static ParseResult parseROCDLOp (OpAsmParser &parser, OperationState &result)
Variables
static DialectRegistration< ROCDLDialect > rocdlDialect
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 68 of file ROCDLDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseROCDLOp()
static ParseResult parseROCDLOp (OpAsmParser & parser, OperationState & result) static
Definition at line 44 of file ROCDLDialect.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OperationState::types.
printROCDLOp()
static void printROCDLOp (OpAsmPrinter & p, Operation * op) static
Definition at line 37 of file ROCDLDialect.cpp.
References mlir::Operation::getName(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), and mlir::Operation::getResultTypes().
Variable Documentation
rocdlDialect
DialectRegistration<ROCDLDialect> rocdlDialect static
Definition at line 73 of file ROCDLDialect.cpp.