MLIR: lib/Dialect/SDBM/SDBMExpr.cpp File Reference
SDBMExpr.cpp File Reference
#include "mlir/Dialect/SDBM/SDBMExpr.h"
#include "SDBMExprDetail.h"
#include "mlir/Dialect/SDBM/SDBMDialect.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "llvm/Support/raw_ostream.h"
Functions
template<typename Result >
static Result addConstantAndSink (SDBMDirectExpr expr, int64_t constant, bool negated, function_ref< Result(SDBMDirectExpr)> builder)
static SDBMExpr addConstant (SDBMVaryingExpr lhs, int64_t constant)
static SDBMExpr buildDiffExpr (SDBMDirectExpr lhs, SDBMNegExpr rhs)
static SDBMExpr foldSumDiff (SDBMExpr lhs, SDBMExpr rhs)
Function Documentation
addConstant()
static SDBMExpr addConstant (SDBMVaryingExpr lhs, int64_t constant) static
Definition at line 332 of file SDBMExpr.cpp.
References mlir::SDBMExpr::cast(), mlir::SDBMExpr::dyn_cast(), mlir::SDBMConstantExpr::get(), mlir::SDBMSumExpr::get(), mlir::SDBMDiffExpr::get(), mlir::SDBMNegExpr::get(), and mlir::SDBMExpr::getDialect().
Referenced by foldSumDiff(), mlir::ops_assertions::operator+(), and mlir::SDBMExpr::tryConvertAffineExpr().
addConstantAndSink()
template<typename Result > static Result addConstantAndSink (SDBMDirectExpr expr, int64_t constant, bool negated, function_ref< Result(SDBMDirectExpr)> builder) static
Definition at line 304 of file SDBMExpr.cpp.
References mlir::SDBMExpr::cast(), mlir::SDBMExpr::dyn_cast(), mlir::SDBMConstantExpr::get(), mlir::SDBMSumExpr::get(), and mlir::SDBMExpr::getDialect().
buildDiffExpr()
static SDBMExpr buildDiffExpr (SDBMDirectExpr lhs, SDBMNegExpr rhs) static
Definition at line 354 of file SDBMExpr.cpp.
References mlir::SDBMConstantExpr::get(), mlir::SDBMDiffExpr::get(), mlir::SDBMDirectExpr::getConstant(), mlir::SDBMExpr::getDialect(), mlir::SDBMDirectExpr::getTerm(), and mlir::SDBMNegExpr::getVar().
Referenced by foldSumDiff(), and mlir::ops_assertions::operator-().
foldSumDiff()
static SDBMExpr foldSumDiff (SDBMExpr lhs, SDBMExpr rhs) static
Definition at line 369 of file SDBMExpr.cpp.
References addConstant(), buildDiffExpr(), mlir::SDBMExpr::dyn_cast(), mlir::SDBMNegExpr::get(), mlir::SDBMDirectExpr::getConstant(), mlir::SDBMDiffExpr::getLHS(), mlir::SDBMDiffExpr::getRHS(), mlir::SDBMDirectExpr::getTerm(), and mlir::SDBMNegExpr::getVar().
Referenced by mlir::ops_assertions::operator+(), and mlir::SDBMExpr::tryConvertAffineExpr().