MLIR: lib/Analysis/SliceAnalysis.cpp File Reference
SliceAnalysis.cpp File Reference
#include "mlir/Analysis/SliceAnalysis.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/Functional.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/ADT/SetVector.h"
Functions
static void getForwardSliceImpl (Operation *op, SetVector< Operation *> *forwardSlice, TransitiveFilter filter)
static void getBackwardSliceImpl (Operation *op, SetVector< Operation *> *backwardSlice, TransitiveFilter filter)
static void DFSPostorder (Operation *current, DFSState *state)
Function Documentation
DFSPostorder()
static void DFSPostorder (Operation * current, DFSState * state) static
Definition at line 173 of file SliceAnalysis.cpp.
References mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Value::getUses(), and mlir::topologicalSort().
getBackwardSliceImpl()
static void getBackwardSliceImpl (Operation * op, SetVector< Operation *> * backwardSlice, TransitiveFilter filter) static
Definition at line 80 of file SliceAnalysis.cpp.
References mlir::Operation::emitError(), mlir::detail::enumerate(), mlir::getBackwardSlice(), mlir::loop::getForInductionVarOwner(), mlir::getForInductionVarOwner(), mlir::Operation::getNumRegions(), mlir::Operation::getOperands(), and mlir::Operation::getParentOfType().
getForwardSliceImpl()
static void getForwardSliceImpl (Operation * op, SetVector< Operation *> * forwardSlice, TransitiveFilter filter) static
Definition at line 31 of file SliceAnalysis.cpp.
References mlir::getForwardSlice(), mlir::Operation::getNumRegions(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), and mlir::Value::getUsers().