MLIR: lib/Dialect/SPIRV/SPIRVDialect.cpp File Reference
SPIRVDialect.cpp File Reference
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
#include "mlir/Dialect/SPIRV/TargetAndABI.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/StandardTypes.h"
#include "mlir/Parser.h"
#include "mlir/Support/StringExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/SPIRV/SPIRVOpUtils.inc"
#include "mlir/Dialect/SPIRV/SPIRVOps.cpp.inc"
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::spirv
Macros
#define GET_OP_LIST
Functions
static bool containsReturn (Region &region)
Returns true if the given region contains spv.Return or spv.ReturnValue ops.
template<typename ValTy >
static Optional< ValTy > parseAndVerify (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<>
Optional< Type > parseAndVerify< Type > (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<>
Optional< uint64_t > parseAndVerify< uint64_t > (SPIRVDialect const &dialect, DialectAsmParser &parser)
static bool isValidSPIRVIntType (IntegerType type)
static bool isValidSPIRVVectorType (VectorType type)
static Type parseAndVerifyType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseArrayType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parsePointerType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseRuntimeArrayType (SPIRVDialect const &dialect, DialectAsmParser &parser)
template<typename IntTy >
static Optional< IntTy > parseAndVerifyInteger (SPIRVDialect const &dialect, DialectAsmParser &parser)
static Type parseImageType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static ParseResult parseStructMemberDecorations (SPIRVDialect const &dialect, DialectAsmParser &parser, ArrayRef< Type > memberTypes, SmallVectorImpl< StructType::LayoutInfo > &layoutInfo, SmallVectorImpl< StructType::MemberDecorationInfo > &memberDecorationInfo)
static Type parseStructType (SPIRVDialect const &dialect, DialectAsmParser &parser)
static void print (ArrayType type, DialectAsmPrinter &os)
static void print (RuntimeArrayType type, DialectAsmPrinter &os)
static void print (PointerType type, DialectAsmPrinter &os)
static void print (ImageType type, DialectAsmPrinter &os)
static void print (StructType type, DialectAsmPrinter &os)
static LogicalResult verifyRegionAttribute (Location loc, NamedAttribute attribute, bool forArg)
Macro Definition Documentation
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
containsReturn()
static bool containsReturn (Region & region) inline static
Returns true if the given region contains spv.Return or spv.ReturnValue ops.
Definition at line 45 of file SPIRVDialect.cpp.
References mlir::OpBuilder::create(), mlir::DialectInlinerInterface::DialectInlinerInterface(), mlir::Operation::erase(), mlir::Operation::getLoc(), mlir::Region::getParentOp(), mlir::Operation::getRegion(), mlir::Block::getTerminator(), and isLegalToInline().
isValidSPIRVIntType()
static bool isValidSPIRVIntType (IntegerType type) static
Definition at line 152 of file SPIRVDialect.cpp.
References mlir::IntegerType::getWidth().
Referenced by mlir::spirv::SPIRVDialect::isValidScalarType(), and parseAndVerifyType().
isValidSPIRVVectorType()
static bool isValidSPIRVVectorType (VectorType type) static
Definition at line 167 of file SPIRVDialect.cpp.
References mlir::spirv::SPIRVDialect::isValidScalarType().
Referenced by mlir::spirv::SPIRVDialect::isValidType().
parseAndVerify()
template<typename ValTy > static Optional< ValTy > parseAndVerify (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 339 of file SPIRVDialect.cpp.
References mlir::DialectAsmParser::emitError(), mlir::DialectAsmParser::getCurrentLocation(), mlir::StandardTypes::None, and mlir::DialectAsmParser::parseKeyword().
Referenced by mlir::spirv::SPIRVDialect::getAttributeName().
parseAndVerify< Type >()
template<> Optional< Type > parseAndVerify< Type > (SPIRVDialect const & dialect, DialectAsmParser & parser)
Definition at line 354 of file SPIRVDialect.cpp.
References mlir::StandardTypes::None, and parseAndVerifyType().
Referenced by mlir::spirv::SPIRVDialect::getAttributeName().
parseAndVerify< uint64_t >()
template<> Optional< uint64_t > parseAndVerify< uint64_t > (SPIRVDialect const & dialect, DialectAsmParser & parser)
Definition at line 373 of file SPIRVDialect.cpp.
References mlir::failed(), mlir::StandardTypes::None, and mlir::DialectAsmParser::parseComma().
Referenced by mlir::spirv::SPIRVDialect::getAttributeName().
parseAndVerifyInteger()
template<typename IntTy > static Optional<IntTy> parseAndVerifyInteger (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 364 of file SPIRVDialect.cpp.
References mlir::StandardTypes::None, and mlir::DialectAsmParser::parseInteger().
parseAndVerifyType()
static Type parseAndVerifyType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 188 of file SPIRVDialect.cpp.
References mlir::Type::dyn_cast(), mlir::DialectAsmParser::emitError(), mlir::DialectAsmParser::getCurrentLocation(), mlir::Type::getDialect(), mlir::Type::isBF16(), isValidSPIRVIntType(), mlir::DialectAsmParser::parseType(), and mlir::StandardAttributes::Type.
Referenced by parseAndVerify< Type >(), parseArrayType(), parsePointerType(), and parseRuntimeArrayType().
parseArrayType()
static Type parseArrayType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 239 of file SPIRVDialect.cpp.
References mlir::DialectAsmParser::emitError(), mlir::spirv::ArrayType::get(), mlir::DialectAsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::DialectAsmParser::parseDimensionList(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseLess(), mlir::DialectAsmParser::parseOptionalLSquare(), mlir::DialectAsmParser::parseRSquare(), mlir::succeeded(), and mlir::StandardAttributes::Type.
Referenced by mlir::spirv::SPIRVDialect::parseType().
parseImageType()
static Type parseImageType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 428 of file SPIRVDialect.cpp.
References mlir::spirv::ImageType::get(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseLess(), and mlir::StandardAttributes::Type.
Referenced by mlir::spirv::SPIRVDialect::parseType().
parsePointerType()
static Type parsePointerType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 296 of file SPIRVDialect.cpp.
References mlir::DialectAsmParser::emitError(), mlir::spirv::PointerType::get(), mlir::DialectAsmParser::getCurrentLocation(), parseAndVerifyType(), mlir::DialectAsmParser::parseComma(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseKeyword(), mlir::DialectAsmParser::parseLess(), and mlir::StandardAttributes::Type.
Referenced by mlir::spirv::SPIRVDialect::parseType().
parseRuntimeArrayType()
static Type parseRuntimeArrayType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 322 of file SPIRVDialect.cpp.
References mlir::spirv::RuntimeArrayType::get(), parseAndVerifyType(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseLess(), and mlir::StandardAttributes::Type.
Referenced by mlir::spirv::SPIRVDialect::parseType().
parseStructMemberDecorations()
static ParseResult parseStructMemberDecorations (SPIRVDialect const & dialect, DialectAsmParser & parser, ArrayRef< Type > memberTypes, SmallVectorImpl< StructType::LayoutInfo > & layoutInfo, SmallVectorImpl< StructType::MemberDecorationInfo > & memberDecorationInfo) static
Definition at line 446 of file SPIRVDialect.cpp.
References mlir::DialectAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::DialectAsmParser::getCurrentLocation(), mlir::OptionalParseResult::hasValue(), mlir::DialectAsmParser::parseComma(), mlir::DialectAsmParser::parseOptionalComma(), mlir::DialectAsmParser::parseOptionalInteger(), mlir::DialectAsmParser::parseOptionalRSquare(), mlir::DialectAsmParser::parseRSquare(), mlir::succeeded(), and mlir::success().
Referenced by parseStructType().
parseStructType()
static Type parseStructType (SPIRVDialect const & dialect, DialectAsmParser & parser) static
Definition at line 492 of file SPIRVDialect.cpp.
References mlir::DialectAsmParser::emitError(), mlir::spirv::StructType::get(), mlir::Dialect::getContext(), mlir::spirv::StructType::getEmpty(), mlir::DialectAsmParser::getNameLoc(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseLess(), mlir::DialectAsmParser::parseOptionalComma(), mlir::DialectAsmParser::parseOptionalGreater(), mlir::DialectAsmParser::parseOptionalLSquare(), parseStructMemberDecorations(), mlir::DialectAsmParser::parseType(), mlir::succeeded(), and mlir::StandardAttributes::Type.
Referenced by mlir::spirv::SPIRVDialect::parseType().
print() [1/5]
static void print (ArrayType type, DialectAsmPrinter & os) static
Definition at line 558 of file SPIRVDialect.cpp.
References mlir::spirv::ArrayType::getArrayStride(), mlir::spirv::ArrayType::getElementType(), mlir::spirv::ArrayType::getNumElements(), and mlir::spirv::ArrayType::hasLayout().
Referenced by mlir::spirv::SPIRVDialect::printType().
print() [2/5]
static void print (RuntimeArrayType type, DialectAsmPrinter & os) static
Definition at line 566 of file SPIRVDialect.cpp.
References mlir::spirv::RuntimeArrayType::getElementType().
print() [3/5]
static void print (PointerType type, DialectAsmPrinter & os) static
Definition at line 570 of file SPIRVDialect.cpp.
References mlir::spirv::PointerType::getPointeeType(), and mlir::spirv::PointerType::getStorageClass().
print() [4/5]
static void print (ImageType type, DialectAsmPrinter & os) static
Definition at line 575 of file SPIRVDialect.cpp.
References mlir::spirv::ImageType::getArrayedInfo(), mlir::spirv::ImageType::getDepthInfo(), mlir::spirv::ImageType::getDim(), mlir::spirv::ImageType::getElementType(), mlir::spirv::ImageType::getImageFormat(), mlir::spirv::ImageType::getSamplerUseInfo(), and mlir::spirv::ImageType::getSamplingInfo().
print() [5/5]
static void print (StructType type, DialectAsmPrinter & os) static
Definition at line 584 of file SPIRVDialect.cpp.
References mlir::spirv::StructType::getElementType(), mlir::spirv::StructType::getMemberDecorations(), mlir::spirv::StructType::getNumElements(), mlir::spirv::StructType::getOffset(), mlir::spirv::StructType::hasLayout(), and mlir::interleaveComma().
verifyRegionAttribute()
static LogicalResult verifyRegionAttribute (Location loc, NamedAttribute attribute, bool forArg) static
Definition at line 680 of file SPIRVDialect.cpp.
References mlir::emitError(), mlir::spirv::getInterfaceVarABIAttrName(), mlir::Attribute::isa(), and mlir::success().
Referenced by mlir::spirv::SPIRVDialect::verifyRegionArgAttribute(), and mlir::spirv::SPIRVDialect::verifyRegionResultAttribute().