MLIR: lib/Dialect/SPIRV/SPIRVLowering.cpp File Reference
SPIRVLowering.cpp File Reference
#include "mlir/Dialect/SPIRV/SPIRVLowering.h"
#include "mlir/Dialect/SPIRV/LayoutUtils.h"
#include "mlir/Dialect/SPIRV/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/Support/Debug.h"
#include <functional>
Macros
#define DEBUG_TYPE "mlir-spirv-lowering"
Functions
static Optional< int64_t > getTypeNumBytes (Type t)
static Type convertStdType (Type type)
static spirv::GlobalVariableOp getBuiltinVariable (Block &body, spirv::BuiltIn builtin)
static std::string getBuiltinVarName (spirv::BuiltIn builtin)
Gets name of global variable for a builtin.
static spirv::GlobalVariableOp getOrInsertBuiltinVariable (Block &body, Location loc, spirv::BuiltIn builtin, OpBuilder &builder)
Gets or inserts a global variable for a builtin within body block.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-spirv-lowering"
Definition at line 22 of file SPIRVLowering.cpp.
Function Documentation
convertStdType()
static Type convertStdType (Type type) static
Definition at line 101 of file SPIRVLowering.cpp.
References mlir::Type::dyn_cast(), mlir::spirv::ArrayType::get(), mlir::spirv::PointerType::get(), mlir::spirv::StructType::get(), mlir::Type::getContext(), mlir::SPIRVTypeConverter::getIndexType(), getTypeNumBytes(), mlir::spirv::SPIRVDialect::isValidType(), and mlir::StandardAttributes::Type.
Referenced by mlir::SPIRVTypeConverter::convertType().
getBuiltinVariable()
static spirv::GlobalVariableOp getBuiltinVariable (Block & body, spirv::BuiltIn builtin) static
Definition at line 224 of file SPIRVLowering.cpp.
References mlir::spirv::SPIRVDialect::getAttributeName(), and mlir::Block::getOps().
Referenced by getOrInsertBuiltinVariable().
getBuiltinVarName()
static std::string getBuiltinVarName (spirv::BuiltIn builtin) static
Gets name of global variable for a builtin.
Definition at line 242 of file SPIRVLowering.cpp.
Referenced by getOrInsertBuiltinVariable().
getOrInsertBuiltinVariable()
static spirv::GlobalVariableOp getOrInsertBuiltinVariable (Block & body, Location loc, spirv::BuiltIn builtin, OpBuilder & builder) static
Gets or inserts a global variable for a builtin within body block.
Definition at line 248 of file SPIRVLowering.cpp.
References mlir::Region::begin(), mlir::OpBuilder::create(), mlir::emitError(), mlir::Operation::emitError(), mlir::spirv::PointerType::get(), mlir::VectorType::get(), getBuiltinVariable(), mlir::spirv::getBuiltinVariableValue(), getBuiltinVarName(), mlir::Builder::getIntegerType(), mlir::Operation::getLoc(), mlir::SymbolTable::getNearestSymbolTable(), mlir::Operation::getParentOp(), mlir::Operation::getRegion(), and mlir::OpBuilder::setInsertionPointToStart().
getTypeNumBytes()
static Optional<int64_t> getTypeNumBytes (Type t) static
Definition at line 43 of file SPIRVLowering.cpp.
References mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::Type::getIntOrFloatBitWidth(), mlir::getStridesAndOffset(), mlir::spirv::SPIRVDialect::isValidScalarType(), mlir::ShapedType::kDynamicSize, and mlir::StandardTypes::None.
Referenced by convertStdType().