MLIR: lib/IR/StandardTypes.cpp File Reference
StandardTypes.cpp File Reference
#include "mlir/IR/StandardTypes.h"
#include "TypeDetail.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/Twine.h"
Functions
static LogicalResult checkTensorElementType (Optional< Location > location, MLIRContext *context, Type elementType)
static AffineExpr makeCanonicalStridedLayoutExpr (ArrayRef< int64_t > sizes, MLIRContext *context)
Given MemRef sizes that are either static or dynamic, returns the canonical "contiguous" strides AffineExpr.
static void extractStridesFromTerm (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr &offset)
static LogicalResult extractStrides (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr &offset)
Takes a single AffineExpr e and populates the strides array with the strides expressions for each dim position.
Function Documentation
checkTensorElementType()
static LogicalResult checkTensorElementType (Optional< Location > location, MLIRContext * context, Type elementType) inline static
Definition at line 236 of file StandardTypes.cpp.
References mlir::emitOptionalError(), mlir::TensorType::isValidElementType(), and mlir::success().
Referenced by mlir::RankedTensorType::verifyConstructionInvariants(), and mlir::UnrankedTensorType::verifyConstructionInvariants().
extractStrides()
static LogicalResult extractStrides (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr & offset) static
Takes a single AffineExpr e and populates the strides array with the strides expressions for each dim position.
The convention is that the strides for dimensions d0, .. dn appear in order to make indexing intuitive into the result.
Definition at line 479 of file StandardTypes.cpp.
References mlir::Add, mlir::CeilDiv, mlir::AffineExpr::dyn_cast(), extractStridesFromTerm(), mlir::failure(), mlir::FloorDiv, mlir::Mod, mlir::Mul, mlir::succeeded(), and mlir::success().
Referenced by mlir::getStridesAndOffset().
extractStridesFromTerm()
static void extractStridesFromTerm (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr & offset) static
Definition at line 464 of file StandardTypes.cpp.
References mlir::AffineExpr::dyn_cast().
Referenced by extractStrides().
makeCanonicalStridedLayoutExpr()
static AffineExpr makeCanonicalStridedLayoutExpr (ArrayRef< int64_t > sizes, MLIRContext * context) static
Given MemRef sizes that are either static or dynamic, returns the canonical "contiguous" strides AffineExpr.
Strides are multiplicative and once a dynamic dimension is encountered, all canonical strides become dynamic and need to be encoded with a different symbol. For canonical strides expressions, the offset is always 0 and and fastest varying stride is always 1.
Examples:
memref<3x4x5xf32> has canonical stride expression 20*d0 + 5*d1 + d2.
memref<3x?x5xf32> has canonical stride expression s0*d0 + 5*d1 + d2.
memref<3x4x?xf32> has canonical stride expression s1*d0 + s0*d1 + d2.
Definition at line 430 of file StandardTypes.cpp.
References mlir::detail::enumerate(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), and mlir::simplifyAffineExpr().
Referenced by mlir::canonicalizeStridedLayout(), and mlir::getStridesAndOffset().