MLIR: lib/Quantizer/Support/Statistics.cpp File Reference
Statistics.cpp File Reference
#include "mlir/Quantizer/Support/Statistics.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/StandardTypes.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void collectElementsStatisticsDim (ElementsAttr attr, unsigned numElements, ArrayRef< int64_t > shape, SmallVectorImpl< uint64_t > &indices, uint64_t dim, TensorAxisStatistics &statistics)
static bool getElementsStatistics (ElementsAttr attr, TensorAxisStatistics &statistics)
Function Documentation
collectElementsStatisticsDim()
static void collectElementsStatisticsDim (ElementsAttr attr, unsigned numElements, ArrayRef< int64_t > shape, SmallVectorImpl< uint64_t > & indices, uint64_t dim, TensorAxisStatistics & statistics) static
Definition at line 22 of file Statistics.cpp.
References mlir::ElementsAttr::getValue(), mlir::quantizer::TensorAxisStatistics::maxValue, mlir::quantizer::TensorAxisStatistics::mean, and mlir::quantizer::TensorAxisStatistics::minValue.
Referenced by getElementsStatistics().
getElementsStatistics()
static bool getElementsStatistics (ElementsAttr attr, TensorAxisStatistics & statistics) static
Definition at line 53 of file Statistics.cpp.
References mlir::quantizer::TensorAxisStatistics::clear(), collectElementsStatisticsDim(), mlir::ShapedType::getElementType(), mlir::ShapedType::getNumElements(), mlir::ShapedType::getRank(), mlir::ShapedType::getShape(), mlir::ElementsAttr::getType(), mlir::ShapedType::hasStaticShape(), mlir::Type::isa(), mlir::quantizer::TensorAxisStatistics::maxValue, mlir::quantizer::TensorAxisStatistics::minValue, and mlir::quantizer::TensorAxisStatistics::sampleSize.
Referenced by mlir::quantizer::AttributeTensorStatistics::get().