MLIR: llvm::DOTGraphTraits< const CAGSlice * > Struct Template Reference
llvm::DOTGraphTraits< const CAGSlice * > Struct Template Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const CAGNode *node, const CAGSlice *graph)
std::string getNodeAttributes (const CAGNode *node, const CAGSlice *graph)
Static Public Member Functions
static std::string getGraphProperties (const CAGSlice *)
static bool isNodeHidden (const CAGNode *node)
Detailed Description
template<>
struct llvm::DOTGraphTraits< const CAGSlice * >
Definition at line 35 of file InferQuantizedTypesPass.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< const CAGSlice * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 37 of file InferQuantizedTypesPass.cpp.
Member Function Documentation
getGraphProperties()
static std::string llvm::DOTGraphTraits< const CAGSlice * >::getGraphProperties (const CAGSlice *) inline static
Definition at line 47 of file InferQuantizedTypesPass.cpp.
getNodeAttributes()
std::string llvm::DOTGraphTraits< const CAGSlice * >::getNodeAttributes (const CAGNode * node, const CAGSlice * graph) inline
Definition at line 57 of file InferQuantizedTypesPass.cpp.
References mlir::quantizer::CAGNode::Constraint, mlir::quantizer::CAGNode::getKind(), mlir::quantizer::CAGNode::OperandAnchor, and mlir::quantizer::CAGNode::ResultAnchor.
getNodeLabel()
std::string llvm::DOTGraphTraits< const CAGSlice * >::getNodeLabel (const CAGNode * node, const CAGSlice * graph) inline
Definition at line 40 of file InferQuantizedTypesPass.cpp.
References mlir::quantizer::CAGNode::printLabel().
isNodeHidden()
static bool llvm::DOTGraphTraits< const CAGSlice * >::isNodeHidden (const CAGNode * node) inline static
Definition at line 51 of file InferQuantizedTypesPass.cpp.
References mlir::quantizer::CAGNode::isOrphan().
The documentation for this struct was generated from the following file:
lib/Quantizer/Transforms/InferQuantizedTypesPass.cpp