MLIR: mlir::quant::ExpressedToQuantizedConverter Struct Reference
mlir::quant::ExpressedToQuantizedConverter Struct Reference
Performs type conversion from an arbitrary input type to a type that is expressed by a QuantizedType.
#include "mlir/Dialect/QuantOps/UniformSupport.h"
Public Member Functions
Type convert (QuantizedType elementalType) const
Converts the inputType to be based on the given elemental type, returning the new type (or nullptr and emit an error on failure).
operator bool () const
Whether the conversion is legal.
Static Public Member Functions
static const ExpressedToQuantizedConverter forInputType (Type inputType)
Creates a converter for the given input type.
Public Attributes
const Type inputType
The input type that is being converted from.
const Type expressedType
Supported, elemental expressed type (i.e.
Detailed Description
Performs type conversion from an arbitrary input type to a type that is expressed by a QuantizedType.
This handles cases where the inputType is a supported primitive type (i.e. f32, bf16, etc) or a vector/tensor type based on a supported elemental type.
Since conversion often involves introspecting some attributes of the input type in order to determine how to represent it, this is a two step process.
Definition at line 32 of file UniformSupport.h.
Member Function Documentation
convert()
Type ExpressedToQuantizedConverter::convert (QuantizedType elementalType) const
Converts the inputType to be based on the given elemental type, returning the new type (or nullptr and emit an error on failure).
Definition at line 44 of file UniformSupport.cpp.
References mlir::Type::cast(), expressedType, mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), mlir::Type::getKind(), mlir::VectorType::getShape(), mlir::RankedTensorType::getShape(), inputType, isQuantizablePrimitiveType(), mlir::StandardTypes::RankedTensor, mlir::StandardTypes::UnrankedTensor, and mlir::StandardTypes::Vector.
Referenced by mlir::quant::UniformQuantizedPerAxisValueConverter::convert(), and mlir::quant::UniformQuantizedPerAxisValueConverter::UniformQuantizedPerAxisValueConverter().
forInputType()
const ExpressedToQuantizedConverter ExpressedToQuantizedConverter::forInputType (Type inputType) static
Creates a converter for the given input type.
Definition at line 21 of file UniformSupport.cpp.
References mlir::Type::cast(), getElementType(), mlir::Type::getKind(), inputType, isQuantizablePrimitiveType(), mlir::StandardTypes::RankedTensor, mlir::StandardTypes::UnrankedTensor, and mlir::StandardTypes::Vector.
operator bool()
mlir::quant::ExpressedToQuantizedConverter::operator bool () const inline explicit
Whether the conversion is legal.
Definition at line 41 of file UniformSupport.h.
References expressedType.
Member Data Documentation
expressedType
const Type mlir::quant::ExpressedToQuantizedConverter::expressedType
Supported, elemental expressed type (i.e.
f32). Will be nullptr if conversion is not supported.
Definition at line 49 of file UniformSupport.h.
Referenced by convert(), and operator bool().
inputType
const Type mlir::quant::ExpressedToQuantizedConverter::inputType
The input type that is being converted from.
This may be an elemental or composite type.
Definition at line 45 of file UniformSupport.h.
Referenced by convert(), and forInputType().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/QuantOps/UniformSupport.h
lib/Dialect/QuantOps/Utils/UniformSupport.cpp