MLIR: mlir::detail::OpaqueElementsAttributeStorage Struct Reference
mlir::detail::OpaqueElementsAttributeStorage Struct Reference
An attribute representing a reference to a tensor constant with opaque content.
#include "IR/AttributeDetail.h"
Public Types
using KeyTy = std::tuple< Type, Dialect *, StringRef >
Public Member Functions
OpaqueElementsAttributeStorage (Type type, Dialect *dialect, StringRef bytes)
bool operator== (const KeyTy &key) const
Key equality and hash functions.
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static unsigned hashKey (const KeyTy &key)
static OpaqueElementsAttributeStorage * construct (AttributeStorageAllocator &allocator, KeyTy key)
Construct a new storage instance.
Public Attributes
Dialect * dialect
StringRef bytes
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
An attribute representing a reference to a tensor constant with opaque content.
Definition at line 535 of file AttributeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::OpaqueElementsAttributeStorage::KeyTy = std::tuple<Type, Dialect *, StringRef>
Definition at line 536 of file AttributeDetail.h.
Constructor & Destructor Documentation
OpaqueElementsAttributeStorage()
mlir::detail::OpaqueElementsAttributeStorage::OpaqueElementsAttributeStorage (Type type, Dialect * dialect, StringRef bytes) inline
Definition at line 538 of file AttributeDetail.h.
Member Function Documentation
construct()
static OpaqueElementsAttributeStorage* mlir::detail::OpaqueElementsAttributeStorage::construct (AttributeStorageAllocator & allocator, KeyTy key) inline static
Construct a new storage instance.
Definition at line 552 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and mlir::StorageUniquer::StorageAllocator::copyInto().
hashKey()
static unsigned mlir::detail::OpaqueElementsAttributeStorage::hashKey (const KeyTy & key) inline static
Definition at line 545 of file AttributeDetail.h.
operator==()
bool mlir::detail::OpaqueElementsAttributeStorage::operator== (const KeyTy & key) const inline
Key equality and hash functions.
Definition at line 542 of file AttributeDetail.h.
References mlir::AttributeStorage::getType().
Member Data Documentation
bytes
StringRef mlir::detail::OpaqueElementsAttributeStorage::bytes
Definition at line 561 of file AttributeDetail.h.
dialect
Dialect* mlir::detail::OpaqueElementsAttributeStorage::dialect
Definition at line 560 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h