MLIR: llvm::DenseMapInfo< mlir::Identifier > Struct Template Reference
llvm::DenseMapInfo< mlir::Identifier > Struct Template Reference
#include "mlir/IR/Identifier.h"
Static Public Member Functions
static mlir::Identifier getEmptyKey ()
static mlir::Identifier getTombstoneKey ()
static unsigned getHashValue (mlir::Identifier Val)
static bool isEqual (mlir::Identifier LHS, mlir::Identifier RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< mlir::Identifier >
Definition at line 101 of file Identifier.h.
Member Function Documentation
getEmptyKey()
static mlir::Identifier llvm::DenseMapInfo< mlir::Identifier >::getEmptyKey () inline static
Definition at line 102 of file Identifier.h.
References mlir::Identifier::getFromOpaquePointer().
getHashValue()
static unsigned llvm::DenseMapInfo< mlir::Identifier >::getHashValue (mlir::Identifier Val) inline static
Definition at line 110 of file Identifier.h.
References mlir::Identifier::data().
getTombstoneKey()
static mlir::Identifier llvm::DenseMapInfo< mlir::Identifier >::getTombstoneKey () inline static
Definition at line 106 of file Identifier.h.
References mlir::Identifier::getFromOpaquePointer().
isEqual()
static bool llvm::DenseMapInfo< mlir::Identifier >::isEqual (mlir::Identifier LHS, mlir::Identifier RHS) inline static
Definition at line 113 of file Identifier.h.
The documentation for this struct was generated from the following file:
include/mlir/IR/Identifier.h