MLIR: mlir::detail::CallSiteLocationStorage Struct Reference
mlir::detail::CallSiteLocationStorage Struct Reference
#include "IR/LocationDetail.h"
Public Types
using KeyTy = std::pair< Location, Location >
The hash key used for uniquing.
Public Member Functions
CallSiteLocationStorage (Location callee, Location caller)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static CallSiteLocationStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Construct a new storage instance.
Public Attributes
Location callee
Location caller
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Definition at line 25 of file LocationDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::CallSiteLocationStorage::KeyTy = std::pair<Location, Location>
The hash key used for uniquing.
Definition at line 30 of file LocationDetail.h.
Constructor & Destructor Documentation
CallSiteLocationStorage()
mlir::detail::CallSiteLocationStorage::CallSiteLocationStorage (Location callee, Location caller) inline
Definition at line 26 of file LocationDetail.h.
Referenced by construct().
Member Function Documentation
construct()
static CallSiteLocationStorage* mlir::detail::CallSiteLocationStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Construct a new storage instance.
Definition at line 37 of file LocationDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and CallSiteLocationStorage().
operator==()
bool mlir::detail::CallSiteLocationStorage::operator== (const KeyTy & key) const inline
Definition at line 31 of file LocationDetail.h.
References callee, and caller.
Member Data Documentation
callee
Location mlir::detail::CallSiteLocationStorage::callee
Definition at line 42 of file LocationDetail.h.
Referenced by operator==().
caller
Location mlir::detail::CallSiteLocationStorage::caller
Definition at line 42 of file LocationDetail.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
lib/IR/LocationDetail.h