MLIR: mlir::detail::RankedTensorTypeStorage Struct Reference
mlir::detail::RankedTensorTypeStorage Struct Reference
#include "IR/TypeDetail.h"
Public Types
using KeyTy = std::pair< ArrayRef< int64_t >, Type >
The hash key used for uniquing.
Public Types inherited from mlir::detail::ShapedTypeStorage
using KeyTy = Type
The hash key used for uniquing.
Public Member Functions
RankedTensorTypeStorage (unsigned shapeSize, Type elementTy, const int64_t *shapeElements)
bool operator== (const KeyTy &key) const
ArrayRef< int64_t > getShape () const
Public Member Functions inherited from mlir::detail::ShapedTypeStorage
ShapedTypeStorage (Type elementTy, unsigned subclassData=0)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::TypeStorage
Dialect & getDialect ()
Get the dialect that this type is registered to.
unsigned getSubclassData () const
Get the subclass data.
void setSubclassData (unsigned val)
Set the subclass data.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static RankedTensorTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Construction.
Public Attributes
const int64_t * shapeElements
Public Attributes inherited from mlir::detail::ShapedTypeStorage
Type elementType
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage (unsigned subclassData=0)
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Definition at line 153 of file TypeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::RankedTensorTypeStorage::KeyTy = std::pair<ArrayRef<int64_t>, Type>
The hash key used for uniquing.
Definition at line 159 of file TypeDetail.h.
Constructor & Destructor Documentation
RankedTensorTypeStorage()
mlir::detail::RankedTensorTypeStorage::RankedTensorTypeStorage (unsigned shapeSize, Type elementTy, const int64_t * shapeElements) inline
Definition at line 154 of file TypeDetail.h.
Member Function Documentation
construct()
static RankedTensorTypeStorage* mlir::detail::RankedTensorTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Construction.
Definition at line 165 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and mlir::StorageUniquer::StorageAllocator::copyInto().
getShape()
ArrayRef<int64_t> mlir::detail::RankedTensorTypeStorage::getShape () const inline
Definition at line 175 of file TypeDetail.h.
References mlir::TypeStorage::getSubclassData().
operator==()
bool mlir::detail::RankedTensorTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 160 of file TypeDetail.h.
References getShape().
Member Data Documentation
shapeElements
const int64_t* mlir::detail::RankedTensorTypeStorage::shapeElements
Definition at line 179 of file TypeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/TypeDetail.h