MLIR: mlir::detail::DenseElementsAttributeStorage Struct Reference
mlir::detail::DenseElementsAttributeStorage Struct Reference
An attribute representing a reference to a dense vector or tensor object.
#include "IR/AttributeDetail.h"
Classes
struct KeyTy
Public Member Functions
DenseElementsAttributeStorage (ShapedType ty, ArrayRef< char > data, bool isSplat=false)
bool operator== (const KeyTy &key) const
Compare this storage instance with the provided key.
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static KeyTy getKey (ShapedType ty, ArrayRef< char > data, bool isKnownSplat)
Construct a key from a shaped type, raw data buffer, and a flag that signals if the data is already known to be a splat.
static KeyTy getKeyForBoolData (ShapedType ty, ArrayRef< char > data, size_t numElements)
Construct a key with a set of boolean data.
static llvm::hash_code hashKey (const KeyTy &key)
Hash the key for the storage.
static DenseElementsAttributeStorage * construct (AttributeStorageAllocator &allocator, KeyTy key)
Construct a new storage instance.
Public Attributes
ArrayRef< char > data
bool isSplat
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
An attribute representing a reference to a dense vector or tensor object.
Definition at line 376 of file AttributeDetail.h.
Constructor & Destructor Documentation
DenseElementsAttributeStorage()
mlir::detail::DenseElementsAttributeStorage::DenseElementsAttributeStorage (ShapedType ty, ArrayRef< char > data, bool isSplat = false) inline
Definition at line 395 of file AttributeDetail.h.
Member Function Documentation
construct()
static DenseElementsAttributeStorage* mlir::detail::DenseElementsAttributeStorage::construct (AttributeStorageAllocator & allocator, KeyTy key) inline static
Construct a new storage instance.
Definition at line 510 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), mlir::detail::DenseElementsAttributeStorage::KeyTy::data, mlir::ShapedType::getElementTypeBitWidth(), mlir::detail::DenseElementsAttributeStorage::KeyTy::isSplat, and mlir::detail::DenseElementsAttributeStorage::KeyTy::type.
getKey()
static KeyTy mlir::detail::DenseElementsAttributeStorage::getKey (ShapedType ty, ArrayRef< char > data, bool isKnownSplat) inline static
Construct a key from a shaped type, raw data buffer, and a flag that signals if the data is already known to be a splat.
Callers to this function are expected to tag preknown splat values when possible, e.g. one element shapes.
Definition at line 423 of file AttributeDetail.h.
References mlir::ShapedType::getElementType(), mlir::ShapedType::getElementTypeBitWidth(), mlir::ShapedType::getNumElements(), mlir::hash_value(), and mlir::Type::isBF16().
getKeyForBoolData()
static KeyTy mlir::detail::DenseElementsAttributeStorage::getKeyForBoolData (ShapedType ty, ArrayRef< char > data, size_t numElements) inline static
Construct a key with a set of boolean data.
Definition at line 469 of file AttributeDetail.h.
References mlir::hash_value().
hashKey()
static llvm::hash_code mlir::detail::DenseElementsAttributeStorage::hashKey (const KeyTy & key) inline static
Hash the key for the storage.
Definition at line 504 of file AttributeDetail.h.
References mlir::detail::DenseElementsAttributeStorage::KeyTy::hashCode, and mlir::detail::DenseElementsAttributeStorage::KeyTy::type.
operator==()
bool mlir::detail::DenseElementsAttributeStorage::operator== (const KeyTy & key) const inline
Compare this storage instance with the provided key.
Definition at line 400 of file AttributeDetail.h.
References mlir::detail::DenseElementsAttributeStorage::KeyTy::data, mlir::ShapedType::getElementTypeBitWidth(), mlir::AttributeStorage::getType(), mlir::detail::DenseElementsAttributeStorage::KeyTy::isSplat, and mlir::detail::DenseElementsAttributeStorage::KeyTy::type.
Member Data Documentation
data
ArrayRef<char> mlir::detail::DenseElementsAttributeStorage::data
Definition at line 529 of file AttributeDetail.h.
isSplat
bool mlir::detail::DenseElementsAttributeStorage::isSplat
Definition at line 530 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h