MLIR: mlir::detail::ConversionPatternRewriterImpl Struct Reference
mlir::detail::ConversionPatternRewriterImpl Struct Reference
Classes
struct BlockAction
The storage class for an undoable block action (one of BlockActionKind), contains the information necessary to undo this action.
struct BlockPosition
Original position of the given block in its parent region.
struct OpReplacement
This class represents one requested operation replacement via 'replaceOp'.
Public Types
enum BlockActionKind { BlockActionKind::Create, BlockActionKind::Move, BlockActionKind::Split, BlockActionKind::TypeConversion }
The kind of the block action performed during the rewrite.
Public Member Functions
ConversionPatternRewriterImpl (PatternRewriter &rewriter, TypeConverter *converter)
RewriterState getCurrentState ()
Return the current state of the rewriter.
void resetState (RewriterState state)
Reset the state of the rewriter to a previously saved point.
void undoBlockActions (unsigned numActionsToKeep=0)
Undo the block actions (motions, splits) one by one in reverse order until "numActionsToKeep" actions remains.
void discardRewrites ()
Cleanup and destroy any generated rewrite operations.
void applyRewrites ()
Apply all requested operation rewrites.
LogicalResult convertBlockSignature (Block *block)
Convert the signature of the given block.
Block * applySignatureConversion (Region *region, TypeConverter::SignatureConversion &conversion)
Apply a signature conversion on the given region.
void replaceOp (Operation *op, ValueRange newValues)
PatternRewriter hook for replacing the results of an operation.
void notifySplitBlock (Block *block, Block *continuation)
Notifies that a block was split.
void notifyRegionIsBeingInlinedBefore (Region &region, Region &parent, Region::iterator before)
Notifies that the blocks of a region are about to be moved.
void notifyRegionWasClonedBefore (iterator_range< Region::iterator > &blocks, Location origRegionLoc)
Notifies that the blocks of a region were cloned into another.
void remapValues (Operation::operand_range operands, SmallVectorImpl< Value > &remapped)
Remap the given operands to those with potentially different types.
bool isOpIgnored (Operation *op) const
Returns true if the given operation is ignored, and does not need to be converted.
void markNestedOpsIgnored (Operation *op)
Recursively marks the nested operations under 'op' as ignored.
Public Attributes
ConversionValueMapping mapping
ArgConverter argConverter
Utility used to convert block arguments.
std::vector< Operation * > createdOps
Ordered vector of all of the newly created operations during conversion.
SmallVector< OpReplacement, 4 > replacements
Ordered vector of any requested operation replacements.
SmallVector< BlockAction, 4 > blockActions
Ordered list of block operations (creations, splits, motions).
llvm::SetVector< Operation * > ignoredOps
A set of operations that have been erased/replaced/etc that should no longer be considered for legalization.
SmallVector< OperationTransactionState, 4 > rootUpdates
A transaction state for each of operations that were updated in-place.
SmallPtrSet< Operation *, 1 > pendingRootUpdates
A set of operations that have pending updates.
Detailed Description
Definition at line 468 of file DialectConversion.cpp.
Member Enumeration Documentation
BlockActionKind
enum mlir::detail::ConversionPatternRewriterImpl::BlockActionKind strong
The kind of the block action performed during the rewrite.
Actions can be undone if the conversion fails.
Enumerator
Create
Move
Split
TypeConversion
Definition at line 481 of file DialectConversion.cpp.
Constructor & Destructor Documentation
ConversionPatternRewriterImpl()
mlir::detail::ConversionPatternRewriterImpl::ConversionPatternRewriterImpl (PatternRewriter & rewriter, TypeConverter * converter) inline
Definition at line 526 of file DialectConversion.cpp.
Member Function Documentation
applyRewrites()
void ConversionPatternRewriterImpl::applyRewrites ()
Apply all requested operation rewrites.
This method is invoked when the conversion process succeeds.
Definition at line 706 of file DialectConversion.cpp.
applySignatureConversion()
Block * ConversionPatternRewriterImpl::applySignatureConversion (Region * region, TypeConverter::SignatureConversion & conversion)
Apply a signature conversion on the given region.
Definition at line 747 of file DialectConversion.cpp.
References mlir::Region::empty(), mlir::Region::front(), and mlir::Block::push_back().
convertBlockSignature()
LogicalResult ConversionPatternRewriterImpl::convertBlockSignature (Block * block)
Convert the signature of the given block.
Definition at line 731 of file DialectConversion.cpp.
References mlir::Block::getParent(), mlir::Block::isEntryBlock(), mlir::Block::push_back(), and mlir::success().
discardRewrites()
void ConversionPatternRewriterImpl::discardRewrites ()
Cleanup and destroy any generated rewrite operations.
This method is invoked when the conversion process fails.
Definition at line 694 of file DialectConversion.cpp.
References mlir::Operation::erase().
getCurrentState()
RewriterState ConversionPatternRewriterImpl::getCurrentState ()
Return the current state of the rewriter.
Definition at line 620 of file DialectConversion.cpp.
Referenced by mlir::ConversionPattern::matchAndRewrite().
isOpIgnored()
bool ConversionPatternRewriterImpl::isOpIgnored (Operation * op) const
Returns true if the given operation is ignored, and does not need to be converted.
Definition at line 810 of file DialectConversion.cpp.
References mlir::Operation::getParentOp().
Referenced by mlir::ConversionPattern::matchAndRewrite().
markNestedOpsIgnored()
void ConversionPatternRewriterImpl::markNestedOpsIgnored (Operation * op)
Recursively marks the nested operations under 'op' as ignored.
This removes them from being considered for legalization.
Definition at line 815 of file DialectConversion.cpp.
References mlir::Operation::getNumRegions(), mlir::Operation::getRegions(), and mlir::Operation::walk().
Referenced by mlir::ConversionPattern::matchAndRewrite().
notifyRegionIsBeingInlinedBefore()
void ConversionPatternRewriterImpl::notifyRegionIsBeingInlinedBefore (Region & region, Region & parent, Region::iterator before)
Notifies that the blocks of a region are about to be moved.
Definition at line 780 of file DialectConversion.cpp.
References mlir::detail::enumerate(), and mlir::Block::push_back().
notifyRegionWasClonedBefore()
void ConversionPatternRewriterImpl::notifyRegionWasClonedBefore (iterator_range< Region::iterator > & blocks, Location origRegionLoc)
Notifies that the blocks of a region were cloned into another.
Definition at line 789 of file DialectConversion.cpp.
References computeConversionSet(), and mlir::succeeded().
notifySplitBlock()
void ConversionPatternRewriterImpl::notifySplitBlock (Block * block, Block * continuation)
Notifies that a block was split.
Definition at line 775 of file DialectConversion.cpp.
remapValues()
void ConversionPatternRewriterImpl::remapValues (Operation::operand_range operands, SmallVectorImpl< Value > & remapped)
Remap the given operands to those with potentially different types.
Definition at line 803 of file DialectConversion.cpp.
Referenced by mlir::ConversionPattern::matchAndRewrite().
replaceOp()
void ConversionPatternRewriterImpl::replaceOp (Operation * op, ValueRange newValues)
PatternRewriter hook for replacing the results of an operation.
Mark this operation as recursively ignored so that we don't need to convert any nested operations.
Definition at line 758 of file DialectConversion.cpp.
References mlir::Operation::getNumResults(), mlir::Operation::getResult(), and mlir::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
resetState()
void ConversionPatternRewriterImpl::resetState (RewriterState state)
Reset the state of the rewriter to a previously saved point.
Definition at line 626 of file DialectConversion.cpp.
undoBlockActions()
void ConversionPatternRewriterImpl::undoBlockActions (unsigned numActionsToKeep = 0)
Undo the block actions (motions, splits) one by one in reverse order until "numActionsToKeep" actions remains.
Definition at line 652 of file DialectConversion.cpp.
References mlir::Region::begin(), and mlir::Region::getBlocks().
Member Data Documentation
argConverter
ArgConverter mlir::detail::ConversionPatternRewriterImpl::argConverter
Utility used to convert block arguments.
Definition at line 587 of file DialectConversion.cpp.
blockActions
SmallVector<BlockAction, 4> mlir::detail::ConversionPatternRewriterImpl::blockActions
Ordered list of block operations (creations, splits, motions).
Definition at line 596 of file DialectConversion.cpp.
createdOps
std::vector<Operation *> mlir::detail::ConversionPatternRewriterImpl::createdOps
Ordered vector of all of the newly created operations during conversion.
Definition at line 590 of file DialectConversion.cpp.
ignoredOps
llvm::SetVector<Operation *> mlir::detail::ConversionPatternRewriterImpl::ignoredOps
A set of operations that have been erased/replaced/etc that should no longer be considered for legalization.
This is not meant to be an exhaustive list of all operations, but the minimal set that can be used to detect if a given operation should be ignored. For example, we may add the operations that define non-empty regions to the set, but not any of the others. This simplifies the amount of memory needed as we can query if the parent operation was ignored.
Definition at line 605 of file DialectConversion.cpp.
mapping
ConversionValueMapping mlir::detail::ConversionPatternRewriterImpl::mapping
Definition at line 584 of file DialectConversion.cpp.
pendingRootUpdates
SmallPtrSet<Operation *, 1> mlir::detail::ConversionPatternRewriterImpl::pendingRootUpdates
A set of operations that have pending updates.
This tracking isn't strictly necessary, and is thus only active during debug builds for extra verification.
Definition at line 614 of file DialectConversion.cpp.
replacements
SmallVector<OpReplacement, 4> mlir::detail::ConversionPatternRewriterImpl::replacements
Ordered vector of any requested operation replacements.
Definition at line 593 of file DialectConversion.cpp.
rootUpdates
SmallVector<OperationTransactionState, 4> mlir::detail::ConversionPatternRewriterImpl::rootUpdates
A transaction state for each of operations that were updated in-place.
Definition at line 608 of file DialectConversion.cpp.
The documentation for this struct was generated from the following file:
lib/Transforms/DialectConversion.cpp