MLIR: mlir::detail::OpaqueAttributeStorage Struct Reference
mlir::detail::OpaqueAttributeStorage Struct Reference
Opaque Attribute Storage and Uniquing.
#include "IR/AttributeDetail.h"
Public Types
using KeyTy = std::tuple< Identifier, StringRef, Type >
The hash key used for uniquing.
Public Member Functions
OpaqueAttributeStorage (Identifier dialectNamespace, StringRef attrData, Type type)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static OpaqueAttributeStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
Identifier dialectNamespace
StringRef attrData
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Opaque Attribute Storage and Uniquing.
Definition at line 266 of file AttributeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::OpaqueAttributeStorage::KeyTy = std::tuple<Identifier, StringRef, Type>
The hash key used for uniquing.
Definition at line 273 of file AttributeDetail.h.
Constructor & Destructor Documentation
OpaqueAttributeStorage()
mlir::detail::OpaqueAttributeStorage::OpaqueAttributeStorage (Identifier dialectNamespace, StringRef attrData, Type type) inline
Definition at line 267 of file AttributeDetail.h.
Member Function Documentation
construct()
static OpaqueAttributeStorage* mlir::detail::OpaqueAttributeStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 278 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and mlir::StorageUniquer::StorageAllocator::copyInto().
operator==()
bool mlir::detail::OpaqueAttributeStorage::operator== (const KeyTy & key) const inline
Definition at line 274 of file AttributeDetail.h.
References mlir::AttributeStorage::getType().
Member Data Documentation
attrData
StringRef mlir::detail::OpaqueAttributeStorage::attrData
Definition at line 290 of file AttributeDetail.h.
dialectNamespace
Identifier mlir::detail::OpaqueAttributeStorage::dialectNamespace
Definition at line 287 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h