MLIR: mlir::detail::FunctionTypeStorage Struct Reference
mlir::detail::FunctionTypeStorage Struct Reference
Function Type Storage and Uniquing.
#include "IR/TypeDetail.h"
Public Types
using KeyTy = std::pair< ArrayRef< Type >, ArrayRef< Type > >
The hash key used for uniquing.
Public Member Functions
FunctionTypeStorage (unsigned numInputs, unsigned numResults, Type const *inputsAndResults)
bool operator== (const KeyTy &key) const
ArrayRef< Type > getInputs () const
ArrayRef< Type > getResults () const
Public Member Functions inherited from mlir::TypeStorage
Dialect & getDialect ()
Get the dialect that this type is registered to.
unsigned getSubclassData () const
Get the subclass data.
void setSubclassData (unsigned val)
Set the subclass data.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static FunctionTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Construction.
Public Attributes
unsigned numResults
Type const * inputsAndResults
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage (unsigned subclassData=0)
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Function Type Storage and Uniquing.
Definition at line 71 of file TypeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::FunctionTypeStorage::KeyTy = std::pair<ArrayRef<Type>, ArrayRef<Type> >
The hash key used for uniquing.
Definition at line 78 of file TypeDetail.h.
Constructor & Destructor Documentation
FunctionTypeStorage()
mlir::detail::FunctionTypeStorage::FunctionTypeStorage (unsigned numInputs, unsigned numResults, Type const * inputsAndResults) inline
Definition at line 72 of file TypeDetail.h.
Member Function Documentation
construct()
static FunctionTypeStorage* mlir::detail::FunctionTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Construction.
Definition at line 84 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and mlir::StorageUniquer::StorageAllocator::copyInto().
getInputs()
ArrayRef<Type> mlir::detail::FunctionTypeStorage::getInputs () const inline
Definition at line 100 of file TypeDetail.h.
References mlir::TypeStorage::getSubclassData().
getResults()
ArrayRef<Type> mlir::detail::FunctionTypeStorage::getResults () const inline
Definition at line 103 of file TypeDetail.h.
References mlir::TypeStorage::getSubclassData().
operator==()
bool mlir::detail::FunctionTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 79 of file TypeDetail.h.
Member Data Documentation
inputsAndResults
Type const* mlir::detail::FunctionTypeStorage::inputsAndResults
Definition at line 108 of file TypeDetail.h.
numResults
unsigned mlir::detail::FunctionTypeStorage::numResults
Definition at line 107 of file TypeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/TypeDetail.h