MLIR: mlir::tblgen::NamedTypeConstraint Struct Reference
mlir::tblgen::NamedTypeConstraint Struct Reference
#include "mlir/TableGen/Argument.h"
Public Member Functions
bool hasPredicate () const
bool isVariadic () const
Public Attributes
llvm::StringRef name
TypeConstraint constraint
Detailed Description
Definition at line 43 of file Argument.h.
Member Function Documentation
hasPredicate()
bool tblgen::NamedTypeConstraint::hasPredicate () const
Definition at line 14 of file Argument.cpp.
References constraint, mlir::tblgen::Constraint::getPredicate(), and mlir::tblgen::Pred::isNull().
isVariadic()
bool tblgen::NamedTypeConstraint::isVariadic () const
Definition at line 18 of file Argument.cpp.
References constraint, and mlir::tblgen::TypeConstraint::isVariadic().
Referenced by mlir::tblgen::SymbolInfoMap::SymbolInfo::getVarDecl().
Member Data Documentation
constraint
TypeConstraint mlir::tblgen::NamedTypeConstraint::constraint
Definition at line 50 of file Argument.h.
Referenced by hasPredicate(), and isVariadic().
name
llvm::StringRef mlir::tblgen::NamedTypeConstraint::name
Definition at line 49 of file Argument.h.
The documentation for this struct was generated from the following files:
include/mlir/TableGen/Argument.h
lib/TableGen/Argument.cpp