MLIR: mlir::detail::MemRefTypeStorage Struct Reference
mlir::detail::MemRefTypeStorage Struct Reference
#include "IR/TypeDetail.h"
Public Types
using KeyTy = std::tuple< ArrayRef< int64_t >, Type, ArrayRef< AffineMap >, unsigned >
The hash key used for uniquing.
Public Types inherited from mlir::detail::ShapedTypeStorage
using KeyTy = Type
The hash key used for uniquing.
Public Member Functions
MemRefTypeStorage (unsigned shapeSize, Type elementType, const int64_t *shapeElements, const unsigned numAffineMaps, AffineMap const *affineMapList, const unsigned memorySpace)
bool operator== (const KeyTy &key) const
ArrayRef< int64_t > getShape () const
ArrayRef< AffineMap > getAffineMaps () const
Public Member Functions inherited from mlir::detail::ShapedTypeStorage
ShapedTypeStorage (Type elementTy, unsigned subclassData=0)
bool operator== (const KeyTy &key) const
Public Member Functions inherited from mlir::TypeStorage
Dialect & getDialect ()
Get the dialect that this type is registered to.
unsigned getSubclassData () const
Get the subclass data.
void setSubclassData (unsigned val)
Set the subclass data.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static MemRefTypeStorage * construct (TypeStorageAllocator &allocator, const KeyTy &key)
Construction.
Public Attributes
const int64_t * shapeElements
An array of integers which stores the shape dimension sizes.
const unsigned numAffineMaps
The number of affine maps in the 'affineMapList' array.
AffineMap const * affineMapList
List of affine maps in the memref's layout/index map composition.
const unsigned memorySpace
Memory space in which data referenced by memref resides.
Public Attributes inherited from mlir::detail::ShapedTypeStorage
Type elementType
Additional Inherited Members
Protected Member Functions inherited from mlir::TypeStorage
TypeStorage (unsigned subclassData=0)
This constructor is used by derived classes as part of the TypeUniquer.
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
Definition at line 194 of file TypeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::MemRefTypeStorage::KeyTy = std::tuple<ArrayRef<int64_t>, Type, ArrayRef<AffineMap>, unsigned>
The hash key used for uniquing.
Definition at line 206 of file TypeDetail.h.
Constructor & Destructor Documentation
MemRefTypeStorage()
mlir::detail::MemRefTypeStorage::MemRefTypeStorage (unsigned shapeSize, Type elementType, const int64_t * shapeElements, const unsigned numAffineMaps, AffineMap const * affineMapList, const unsigned memorySpace) inline
Definition at line 195 of file TypeDetail.h.
Member Function Documentation
construct()
static MemRefTypeStorage* mlir::detail::MemRefTypeStorage::construct (TypeStorageAllocator & allocator, const KeyTy & key) inline static
Construction.
Definition at line 212 of file TypeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and mlir::StorageUniquer::StorageAllocator::copyInto().
getAffineMaps()
ArrayRef<AffineMap> mlir::detail::MemRefTypeStorage::getAffineMaps () const inline
Definition at line 232 of file TypeDetail.h.
getShape()
ArrayRef<int64_t> mlir::detail::MemRefTypeStorage::getShape () const inline
Definition at line 228 of file TypeDetail.h.
References mlir::TypeStorage::getSubclassData().
operator==()
bool mlir::detail::MemRefTypeStorage::operator== (const KeyTy & key) const inline
Definition at line 207 of file TypeDetail.h.
References getAffineMaps(), and getShape().
Member Data Documentation
affineMapList
AffineMap const* mlir::detail::MemRefTypeStorage::affineMapList
List of affine maps in the memref's layout/index map composition.
Definition at line 241 of file TypeDetail.h.
memorySpace
const unsigned mlir::detail::MemRefTypeStorage::memorySpace
Memory space in which data referenced by memref resides.
Definition at line 243 of file TypeDetail.h.
numAffineMaps
const unsigned mlir::detail::MemRefTypeStorage::numAffineMaps
The number of affine maps in the 'affineMapList' array.
Definition at line 239 of file TypeDetail.h.
shapeElements
const int64_t* mlir::detail::MemRefTypeStorage::shapeElements
An array of integers which stores the shape dimension sizes.
Definition at line 237 of file TypeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/TypeDetail.h