MLIR: mlir::edsc::IndexHandle Struct Reference
mlir::edsc::IndexHandle Struct Reference
An IndexHandle is a simple wrapper around a ValueHandle.
#include "mlir/EDSC/Intrinsics.h"
Public Member Functions
IndexHandle ()
IndexHandle (index_type v)
IndexHandle (Value v)
IndexHandle (ValueHandle v)
IndexHandle & operator= (const ValueHandle &v)
Public Member Functions inherited from mlir::edsc::ValueHandle
ValueHandle (Type t)
A ValueHandle that is constructed from a Type represents a typed "delayed" Value.
ValueHandle (Value v)
A ValueHandle that is constructed from an mlir::Value is an "eager" Value.
ValueHandle (index_type cst)
Builds a ConstantIndexOp of value cst.
ValueHandle (const ValueHandle &other)=default
ValueHandle is a value type, use the default copy constructor.
ValueHandle & operator= (const ValueHandle &other)
ValueHandle is a value type, the assignment operator typechecks before assigning.
void swap (ValueHandle &other)
Provide a swap operator.
operator Value () const
Implicit conversion useful for automatic conversion to Container<Value>.
operator Type () const
operator bool () const
bool hasValue () const
Value getValue () const
bool hasType () const
Type getType () const
Operation * getOperation () const
Additional Inherited Members
Static Public Member Functions inherited from mlir::edsc::ValueHandle
static ValueHandle null ()
A ValueHandle in a null state can never be captured;.
template<typename Op , typename... Args>
static ValueHandle create (Args... args)
Generic mlir::Op create.
template<typename Op , typename... Args>
static ValueHandle create (OperationFolder *folder, Args... args)
Generic mlir::Op create.
static ValueHandle createComposedAffineApply (AffineMap map, ArrayRef< Value > operands)
Special case to build composed AffineApply operations.
static ValueHandle create (StringRef name, ArrayRef< ValueHandle > operands, ArrayRef< Type > resultTypes, ArrayRef< NamedAttribute > attributes={})
Generic create for a named operation producing a single value.
Protected Member Functions inherited from mlir::edsc::ValueHandle
ValueHandle ()
Protected Member Functions inherited from mlir::edsc::CapturableHandle
CapturableHandle ()=default
Protected Attributes inherited from mlir::edsc::ValueHandle
Type t
Value v
Detailed Description
An IndexHandle is a simple wrapper around a ValueHandle.
IndexHandles are ubiquitous enough to justify a new type to allow simple declarations without boilerplate such as:
{c++}
   IndexHandle i, j, k;
Definition at line 34 of file Intrinsics.h.
Constructor & Destructor Documentation
IndexHandle() [1/4]
mlir::edsc::IndexHandle::IndexHandle () inline explicit
Definition at line 35 of file Intrinsics.h.
IndexHandle() [2/4]
mlir::edsc::IndexHandle::IndexHandle (index_type v) inline explicit
Definition at line 37 of file Intrinsics.h.
IndexHandle() [3/4]
mlir::edsc::IndexHandle::IndexHandle (Value v) inline explicit
Definition at line 38 of file Intrinsics.h.
References mlir::edsc::ScopedContext::getBuilder(), mlir::Builder::getIndexType(), and mlir::Value::getType().
IndexHandle() [4/4]
mlir::edsc::IndexHandle::IndexHandle (ValueHandle v) inline explicit
Definition at line 42 of file Intrinsics.h.
References mlir::edsc::ScopedContext::getBuilder(), mlir::Builder::getIndexType(), and mlir::edsc::ValueHandle::getType().
Member Function Documentation
operator=()
IndexHandle& mlir::edsc::IndexHandle::operator= (const ValueHandle & v) inline
Creating a new IndexHandle(v) and then std::swap rightly complains the binding has already occurred and that we should use another name.
Definition at line 46 of file Intrinsics.h.
References mlir::edsc::ScopedContext::getBuilder(), mlir::Builder::getIndexType(), mlir::edsc::ValueHandle::getType(), mlir::edsc::ValueHandle::getValue(), and mlir::edsc::ValueHandle::t.
The documentation for this struct was generated from the following file:
include/mlir/EDSC/Intrinsics.h