MLIR: llvm::PointerLikeTypeTraits< mlir::BlockArgument > Struct Template Reference
llvm::PointerLikeTypeTraits< mlir::BlockArgument > Struct Template Reference
Allow stealing the low bits of a value.
#include "mlir/IR/Value.h"
Public Types
enum { NumLowBitsAvailable }
Static Public Member Functions
static void * getAsVoidPointer (mlir::Value I)
static mlir::BlockArgument getFromVoidPointer (void *P)
Detailed Description
template<>
struct llvm::PointerLikeTypeTraits< mlir::BlockArgument >
Allow stealing the low bits of a value.
Definition at line 363 of file Value.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NumLowBitsAvailable
Definition at line 371 of file Value.h.
Member Function Documentation
getAsVoidPointer()
static void* llvm::PointerLikeTypeTraits< mlir::BlockArgument >::getAsVoidPointer (mlir::Value I) inline static
Definition at line 365 of file Value.h.
References mlir::Value::getAsOpaquePointer().
getFromVoidPointer()
static mlir::BlockArgument llvm::PointerLikeTypeTraits< mlir::BlockArgument >::getFromVoidPointer (void * P) inline static
Definition at line 368 of file Value.h.
References mlir::Value::cast(), and mlir::Value::getFromOpaquePointer().
The documentation for this struct was generated from the following file:
include/mlir/IR/Value.h