MLIR: mlir::detail::IntegerAttributeStorage Struct Reference
mlir::detail::IntegerAttributeStorage Struct Reference final
An attribute representing a integral value.
#include "IR/AttributeDetail.h"
Public Types
using KeyTy = std::pair< Type, APInt >
Public Member Functions
IntegerAttributeStorage (Type type, size_t numObjects)
bool operator== (const KeyTy &key) const
Key equality and hash functions.
APInt getValue () const
Returns an APInt representing the stored value.
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static unsigned hashKey (const KeyTy &key)
static IntegerAttributeStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Construct a new storage instance.
Public Attributes
size_t numObjects
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
An attribute representing a integral value.
Definition at line 200 of file AttributeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::IntegerAttributeStorage::KeyTy = std::pair<Type, APInt>
Definition at line 203 of file AttributeDetail.h.
Constructor & Destructor Documentation
IntegerAttributeStorage()
mlir::detail::IntegerAttributeStorage::IntegerAttributeStorage (Type type, size_t numObjects) inline
Definition at line 205 of file AttributeDetail.h.
References mlir::Type::isa(), and mlir::Type::isIndex().
Member Function Documentation
construct()
static IntegerAttributeStorage* mlir::detail::IntegerAttributeStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Construct a new storage instance.
Definition at line 220 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and mlir::detail::AffineMapAttributeStorage::value.
getValue()
APInt mlir::detail::IntegerAttributeStorage::getValue () const inline
Returns an APInt representing the stored value.
Definition at line 236 of file AttributeDetail.h.
References mlir::AttributeStorage::getType().
hashKey()
static unsigned mlir::detail::IntegerAttributeStorage::hashKey (const KeyTy & key) inline static
Definition at line 214 of file AttributeDetail.h.
References mlir::hash_value().
operator==()
bool mlir::detail::IntegerAttributeStorage::operator== (const KeyTy & key) const inline
Key equality and hash functions.
Definition at line 211 of file AttributeDetail.h.
References mlir::AttributeStorage::getType().
Member Data Documentation
numObjects
size_t mlir::detail::IntegerAttributeStorage::numObjects
Definition at line 243 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h