MLIR: mlir::edsc::StructuredIndexed Struct Reference
mlir::edsc::StructuredIndexed Struct Reference
A StructuredIndexed represents an indexable quantity that is either:
#include "mlir/Dialect/Linalg/EDSC/Builders.h"
Public Member Functions
StructuredIndexed (Type type)
StructuredIndexed (Value value)
StructuredIndexed (ValueHandle valueHandle)
StructuredIndexed operator() (ArrayRef< AffineExpr > indexings)
ArrayRef< AffineExpr > getExprs ()
Public Member Functions inherited from mlir::edsc::ValueHandle
ValueHandle (Type t)
A ValueHandle that is constructed from a Type represents a typed "delayed" Value.
ValueHandle (Value v)
A ValueHandle that is constructed from an mlir::Value is an "eager" Value.
ValueHandle (index_type cst)
Builds a ConstantIndexOp of value cst.
ValueHandle (const ValueHandle &other)=default
ValueHandle is a value type, use the default copy constructor.
ValueHandle & operator= (const ValueHandle &other)
ValueHandle is a value type, the assignment operator typechecks before assigning.
void swap (ValueHandle &other)
Provide a swap operator.
operator Value () const
Implicit conversion useful for automatic conversion to Container<Value>.
operator Type () const
operator bool () const
bool hasValue () const
Value getValue () const
bool hasType () const
Type getType () const
Operation * getOperation () const
Additional Inherited Members
Static Public Member Functions inherited from mlir::edsc::ValueHandle
static ValueHandle null ()
A ValueHandle in a null state can never be captured;.
template<typename Op , typename... Args>
static ValueHandle create (Args... args)
Generic mlir::Op create.
template<typename Op , typename... Args>
static ValueHandle create (OperationFolder *folder, Args... args)
Generic mlir::Op create.
static ValueHandle createComposedAffineApply (AffineMap map, ArrayRef< Value > operands)
Special case to build composed AffineApply operations.
static ValueHandle create (StringRef name, ArrayRef< ValueHandle > operands, ArrayRef< Type > resultTypes, ArrayRef< NamedAttribute > attributes={})
Generic create for a named operation producing a single value.
Protected Member Functions inherited from mlir::edsc::ValueHandle
ValueHandle ()
Protected Member Functions inherited from mlir::edsc::CapturableHandle
CapturableHandle ()=default
Protected Attributes inherited from mlir::edsc::ValueHandle
Type t
Value v
Detailed Description
A StructuredIndexed represents an indexable quantity that is either:
a captured value, which is suitable for buffer and tensor operands, or;
a captured type, which is suitable for tensor return values.
A StructuredIndexed itself is indexed and passed to makeGenericLinalgOp. It enable an idiomatic syntax for index expressions such as:
StructuredIndexed A(buffer_or_tensor_value), B(buffer_or_tensor_value),
  C(buffer_value_or_tensor_type);
makeGenericLinalgOp({A({m, n}), B({k, n})}, {C({m, n})}, ...);
Definition at line 109 of file Builders.h.
Constructor & Destructor Documentation
StructuredIndexed() [1/3]
mlir::edsc::StructuredIndexed::StructuredIndexed (Type type) inline
Definition at line 110 of file Builders.h.
StructuredIndexed() [2/3]
mlir::edsc::StructuredIndexed::StructuredIndexed (Value value) inline
Definition at line 111 of file Builders.h.
StructuredIndexed() [3/3]
mlir::edsc::StructuredIndexed::StructuredIndexed (ValueHandle valueHandle) inline
Definition at line 112 of file Builders.h.
Member Function Documentation
getExprs()
ArrayRef<AffineExpr> mlir::edsc::StructuredIndexed::getExprs () inline
Definition at line 117 of file Builders.h.
References mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::edsc::ops::linalg_pointwise().
operator()()
StructuredIndexed mlir::edsc::StructuredIndexed::operator() (ArrayRef< AffineExpr > indexings) inline
Definition at line 113 of file Builders.h.
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/EDSC/Builders.h