MLIR: llvm::DenseMapInfo< mlir::FuncOp > Struct Template Reference
llvm::DenseMapInfo< mlir::FuncOp > Struct Template Reference
#include "mlir/IR/Function.h"
Static Public Member Functions
static mlir::FuncOp getEmptyKey ()
static mlir::FuncOp getTombstoneKey ()
static unsigned getHashValue (mlir::FuncOp val)
static bool isEqual (mlir::FuncOp LHS, mlir::FuncOp RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< mlir::FuncOp >
Definition at line 159 of file Function.h.
Member Function Documentation
getEmptyKey()
static mlir::FuncOp llvm::DenseMapInfo< mlir::FuncOp >::getEmptyKey () inline static
Definition at line 160 of file Function.h.
References mlir::Op< FuncOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::Symbol, OpTrait::FunctionLike, CallableOpInterface::Trait >::getFromOpaquePointer().
getHashValue()
static unsigned llvm::DenseMapInfo< mlir::FuncOp >::getHashValue (mlir::FuncOp val) inline static
Definition at line 168 of file Function.h.
References mlir::Op< ConcreteType, Traits >::getAsOpaquePointer(), and mlir::hash_value().
getTombstoneKey()
static mlir::FuncOp llvm::DenseMapInfo< mlir::FuncOp >::getTombstoneKey () inline static
Definition at line 164 of file Function.h.
References mlir::Op< FuncOp, OpTrait::ZeroOperands, OpTrait::ZeroResult, OpTrait::IsIsolatedFromAbove, OpTrait::Symbol, OpTrait::FunctionLike, CallableOpInterface::Trait >::getFromOpaquePointer().
isEqual()
static bool llvm::DenseMapInfo< mlir::FuncOp >::isEqual (mlir::FuncOp LHS, mlir::FuncOp RHS) inline static
Definition at line 171 of file Function.h.
The documentation for this struct was generated from the following file:
include/mlir/IR/Function.h