MLIR: mlir::edsc::OperationHandle Struct Reference
mlir::edsc::OperationHandle Struct Reference
An OperationHandle can be used in lieu of ValueHandle to capture the operation in cases when one does not care about, or cannot extract, a unique Value from the operation.
#include "mlir/EDSC/Builders.h"
Public Member Functions
OperationHandle ()
OperationHandle (Operation *op)
OperationHandle (const OperationHandle &)=default
OperationHandle & operator= (const OperationHandle &)=default
operator Operation * ()
Operation * getOperation () const
Static Public Member Functions
template<typename Op , typename... Args>
static OperationHandle create (Args... args)
Generic mlir::Op create.
template<typename Op , typename... Args>
static Op createOp (Args... args)
static OperationHandle create (StringRef name, ArrayRef< ValueHandle > operands, ArrayRef< Type > resultTypes, ArrayRef< NamedAttribute > attributes={})
Generic create for a named operation.
Additional Inherited Members
Protected Member Functions inherited from mlir::edsc::CapturableHandle
CapturableHandle ()=default
Detailed Description
An OperationHandle can be used in lieu of ValueHandle to capture the operation in cases when one does not care about, or cannot extract, a unique Value from the operation.
This can be used for capturing zero result operations as well as multi-result operations that are not supported by ValueHandle. We do not distinguish further between zero and multi-result operations at this time.
Definition at line 396 of file Builders.h.
Constructor & Destructor Documentation
OperationHandle() [1/3]
mlir::edsc::OperationHandle::OperationHandle () inline
Definition at line 397 of file Builders.h.
OperationHandle() [2/3]
mlir::edsc::OperationHandle::OperationHandle (Operation * op) inline
Definition at line 398 of file Builders.h.
References mlir::matcher::Op().
OperationHandle() [3/3]
mlir::edsc::OperationHandle::OperationHandle (const OperationHandle &) default
Member Function Documentation
create() [1/2]
template<typename Op , typename... Args> OperationHandle mlir::edsc::OperationHandle::create (Args... args) static
Generic mlir::Op create.
This is the key to being extensible to the whole of MLIR without duplicating the type system or the op definitions.
Definition at line 476 of file Builders.h.
References mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getLocation(), and mlir::matcher::Op().
Referenced by mlir::edsc::ValueHandle::create().
create() [2/2]
OperationHandle OperationHandle::create (StringRef name, ArrayRef< ValueHandle > operands, ArrayRef< Type > resultTypes, ArrayRef< NamedAttribute > attributes = {}) static
Generic create for a named operation.
Definition at line 107 of file Builders.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::edsc::ScopedContext::getBuilder(), and mlir::edsc::ScopedContext::getLocation().
createOp()
template<typename Op , typename... Args> Op mlir::edsc::OperationHandle::createOp (Args... args) static
Definition at line 483 of file Builders.h.
References mlir::edsc::ScopedContext::getBuilder(), mlir::edsc::ScopedContext::getLocation(), and mlir::matcher::Op().
getOperation()
Operation* mlir::edsc::OperationHandle::getOperation () const inline
Definition at line 415 of file Builders.h.
operator Operation *()
mlir::edsc::OperationHandle::operator Operation * () inline
Definition at line 414 of file Builders.h.
operator=()
OperationHandle& mlir::edsc::OperationHandle::operator= (const OperationHandle &) default
The documentation for this struct was generated from the following files:
include/mlir/EDSC/Builders.h
lib/EDSC/Builders.cpp