MLIR: mlir::detail::StringAttributeStorage Struct Reference
mlir::detail::StringAttributeStorage Struct Reference
An attribute representing a string value.
#include "IR/AttributeDetail.h"
Public Types
using KeyTy = std::pair< StringRef, Type >
Public Member Functions
StringAttributeStorage (StringRef value, Type type)
bool operator== (const KeyTy &key) const
Key equality function.
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static StringAttributeStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Construct a new storage instance.
Public Attributes
StringRef value
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
An attribute representing a string value.
Definition at line 294 of file AttributeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::StringAttributeStorage::KeyTy = std::pair<StringRef, Type>
Definition at line 295 of file AttributeDetail.h.
Constructor & Destructor Documentation
StringAttributeStorage()
mlir::detail::StringAttributeStorage::StringAttributeStorage (StringRef value, Type type) inline
Definition at line 297 of file AttributeDetail.h.
Member Function Documentation
construct()
static StringAttributeStorage* mlir::detail::StringAttributeStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Construct a new storage instance.
Definition at line 306 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and mlir::StorageUniquer::StorageAllocator::copyInto().
operator==()
bool mlir::detail::StringAttributeStorage::operator== (const KeyTy & key) const inline
Key equality function.
Definition at line 301 of file AttributeDetail.h.
References mlir::AttributeStorage::getType(), and mlir::detail::AffineMapAttributeStorage::value.
Member Data Documentation
value
StringRef mlir::detail::StringAttributeStorage::value
Definition at line 312 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h