MLIR: mlir::detail::FloatAttributeStorage Struct Reference
mlir::detail::FloatAttributeStorage Struct Reference final
An attribute representing a floating point value.
#include "IR/AttributeDetail.h"
Public Types
using KeyTy = std::pair< Type, APFloat >
Public Member Functions
FloatAttributeStorage (const llvm::fltSemantics &semantics, Type type, size_t numObjects)
bool operator== (const KeyTy &key) const
Key equality and hash functions.
APFloat getValue () const
Returns an APFloat representing the stored value.
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static unsigned hashKey (const KeyTy &key)
static KeyTy getKey (Type type, double value)
Construct a key with a type and double.
static FloatAttributeStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Construct a new storage instance.
Public Attributes
const llvm::fltSemantics & semantics
size_t numObjects
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
An attribute representing a floating point value.
Definition at line 138 of file AttributeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::FloatAttributeStorage::KeyTy = std::pair<Type, APFloat>
Definition at line 141 of file AttributeDetail.h.
Constructor & Destructor Documentation
FloatAttributeStorage()
mlir::detail::FloatAttributeStorage::FloatAttributeStorage (const llvm::fltSemantics & semantics, Type type, size_t numObjects) inline
Definition at line 143 of file AttributeDetail.h.
Member Function Documentation
construct()
static FloatAttributeStorage* mlir::detail::FloatAttributeStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Construct a new storage instance.
Definition at line 171 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate().
getKey()
static KeyTy mlir::detail::FloatAttributeStorage::getKey (Type type, double value) inline static
Construct a key with a type and double.
Definition at line 156 of file AttributeDetail.h.
References mlir::Type::cast(), mlir::FloatType::getFloatSemantics(), mlir::Type::isBF16(), and mlir::Type::isF64().
getValue()
APFloat mlir::detail::FloatAttributeStorage::getValue () const inline
Returns an APFloat representing the stored value.
Definition at line 189 of file AttributeDetail.h.
hashKey()
static unsigned mlir::detail::FloatAttributeStorage::hashKey (const KeyTy & key) inline static
Definition at line 151 of file AttributeDetail.h.
References mlir::hash_value().
operator==()
bool mlir::detail::FloatAttributeStorage::operator== (const KeyTy & key) const inline
Key equality and hash functions.
Definition at line 148 of file AttributeDetail.h.
References mlir::AttributeStorage::getType().
Member Data Documentation
numObjects
size_t mlir::detail::FloatAttributeStorage::numObjects
Definition at line 196 of file AttributeDetail.h.
semantics
const llvm::fltSemantics& mlir::detail::FloatAttributeStorage::semantics
Definition at line 195 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h