MLIR: mlir::detail::BoolAttributeStorage Struct Reference
mlir::detail::BoolAttributeStorage Struct Reference
An attribute representing a boolean value.
#include "IR/AttributeDetail.h"
Public Types
using KeyTy = std::pair< MLIRContext *, bool >
Public Member Functions
BoolAttributeStorage (Type type, bool value)
bool operator== (const KeyTy &key) const
We only check equality for and hash with the boolean key parameter.
Public Member Functions inherited from mlir::AttributeStorage
Type getType () const
Get the type of this attribute.
Dialect & getDialect () const
Get the dialect of this attribute.
Public Member Functions inherited from mlir::StorageUniquer::BaseStorage
unsigned getKind () const
Get the kind classification of this storage.
Static Public Member Functions
static unsigned hashKey (const KeyTy &key)
static BoolAttributeStorage * construct (AttributeStorageAllocator &allocator, const KeyTy &key)
Public Attributes
bool value
Additional Inherited Members
Protected Member Functions inherited from mlir::AttributeStorage
AttributeStorage (Type type)
Construct a new attribute storage instance with the given type.
AttributeStorage ()
void setType (Type type)
Set the type of this attribute.
void initializeDialect (Dialect &newDialect)
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()
Detailed Description
An attribute representing a boolean value.
Definition at line 69 of file AttributeDetail.h.
Member Typedef Documentation
KeyTy
using mlir::detail::BoolAttributeStorage::KeyTy = std::pair<MLIRContext *, bool>
Definition at line 70 of file AttributeDetail.h.
Constructor & Destructor Documentation
BoolAttributeStorage()
mlir::detail::BoolAttributeStorage::BoolAttributeStorage (Type type, bool value) inline
Definition at line 72 of file AttributeDetail.h.
Member Function Documentation
construct()
static BoolAttributeStorage* mlir::detail::BoolAttributeStorage::construct (AttributeStorageAllocator & allocator, const KeyTy & key) inline static
Definition at line 81 of file AttributeDetail.h.
References mlir::StorageUniquer::StorageAllocator::allocate(), and mlir::IntegerType::get().
hashKey()
static unsigned mlir::detail::BoolAttributeStorage::hashKey (const KeyTy & key) inline static
Definition at line 77 of file AttributeDetail.h.
References mlir::hash_value().
operator==()
bool mlir::detail::BoolAttributeStorage::operator== (const KeyTy & key) const inline
We only check equality for and hash with the boolean key parameter.
Definition at line 76 of file AttributeDetail.h.
References mlir::detail::AffineMapAttributeStorage::value.
Member Data Documentation
value
bool mlir::detail::BoolAttributeStorage::value
Definition at line 87 of file AttributeDetail.h.
The documentation for this struct was generated from the following file:
lib/IR/AttributeDetail.h