MLIR: lib/Analysis/TestMemRefDependenceCheck.cpp File Reference
TestMemRefDependenceCheck.cpp File Reference
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/Passes.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/IR/Builders.h"
#include "mlir/Pass/Pass.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "test-memref-dependence-check"
Functions
static std::string getDirectionVectorStr (bool ret, unsigned numCommonLoops, unsigned loopNestDepth, ArrayRef< DependenceComponent > dependenceComponents)
static void checkDependences (ArrayRef< Operation *> loadsAndStores)
Variables
static PassRegistration< TestMemRefDependenceCheck > pass ("test-memref-dependence-check", "Checks dependences between all pairs of memref accesses.")
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "test-memref-dependence-check"
Definition at line 23 of file TestMemRefDependenceCheck.cpp.
Function Documentation
checkDependences()
static void checkDependences (ArrayRef< Operation *> loadsAndStores) static
Definition at line 76 of file TestMemRefDependenceCheck.cpp.
References mlir::checkMemrefAccessDependence(), mlir::DependenceResult::Failure, getDirectionVectorStr(), mlir::getNumCommonSurroundingLoops(), mlir::hasDependence(), pass, and mlir::DependenceResult::value.
getDirectionVectorStr()
static std::string getDirectionVectorStr (bool ret, unsigned numCommonLoops, unsigned loopNestDepth, ArrayRef< DependenceComponent > dependenceComponents) static
Definition at line 47 of file TestMemRefDependenceCheck.cpp.
Referenced by checkDependences().
Variable Documentation
pass
PassRegistration<TestMemRefDependenceCheck> pass("test-memref-dependence-check", "Checks dependences between all pairs of memref accesses.") static
Referenced by checkDependences().