MLIR: lib/Dialect/Linalg/Transforms/Tiling.cpp File Reference
Tiling.cpp File Reference
#include "mlir/Dialect/Linalg/EDSC/Builders.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/LoopOps/LoopOps.h"
#include "mlir/EDSC/Helpers.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineExprVisitor.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/STLExtras.h"
#include "mlir/Transforms/FoldUtils.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "linalg-tiling"
Typedefs
using LoopIndexToRangeIndexMap = DenseMap< int, int >
Functions
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options")
static llvm::cl::list< unsigned > clTileSizes ("linalg-tile-sizes", llvm::cl::desc("Tile sizes by which to tile linalg operations"), llvm::cl::ZeroOrMore, llvm::cl::MiscFlags::CommaSeparated, llvm::cl::cat(clOptionsCategory))
static bool isZero (Value v)
static std::tuple< SmallVector< SubViewOp::Range, 4 >, LoopIndexToRangeIndexMap > makeTiledLoopRanges (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > allViewSizes, ArrayRef< Value > allTileSizes, OperationFolder *folder)
static void transformIndexedGenericOpIndices (OpBuilder &b, LinalgOp op, ArrayRef< ValueHandle *> pivs, const LoopIndexToRangeIndexMap &loopIndexToRangeIndex)
static bool isTiled (AffineExpr expr, ArrayRef< Value > tileSizes)
static bool isTiled (AffineMap map, ArrayRef< Value > tileSizes)
static SmallVector< Value, 4 > makeTiledViews (OpBuilder &b, Location loc, LinalgOp linalgOp, ArrayRef< Value > ivs, ArrayRef< Value > tileSizes, ArrayRef< Value > viewSizes, OperationFolder *folder)
static void tileLinalgOps (FuncOp f, ArrayRef< int64_t > tileSizes)
Variables
static PassRegistration< LinalgTilingPass > pass ("linalg-tile", "Tile operations in the linalg dialect", [] { auto pass=std::make_unique< LinalgTilingPass >();pass->tileSizes.assign(clTileSizes.begin(), clTileSizes.end());return pass;})
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-tiling"
Definition at line 37 of file Tiling.cpp.
Typedef Documentation
LoopIndexToRangeIndexMap
using LoopIndexToRangeIndexMap = DenseMap<int, int>
Definition at line 51 of file Tiling.cpp.
Function Documentation
clOptionsCategory()
static llvm::cl::OptionCategory clOptionsCategory (DEBUG_TYPE " options") static
clTileSizes()
static llvm::cl::list<unsigned> clTileSizes ("linalg-tile-sizes" , llvm::cl::desc("Tile sizes by which to tile linalg operations") , llvm::cl::ZeroOrMore , llvm::cl::MiscFlags::CommaSeparated , llvm::cl::cat(clOptionsCategory)) static
Referenced by mlir::createLinalgTilingPass().
isTiled() [1/2]
static bool isTiled (AffineExpr expr, ArrayRef< Value > tileSizes) static
Definition at line 212 of file Tiling.cpp.
Referenced by isTiled(), makeTiledLoopRanges(), and makeTiledViews().
isTiled() [2/2]
static bool isTiled (AffineMap map, ArrayRef< Value > tileSizes) static
Definition at line 222 of file Tiling.cpp.
References mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), and isTiled().
isZero()
static bool isZero (Value v) static
Definition at line 46 of file Tiling.cpp.
References mlir::Value::getDefiningOp().
Referenced by makeTiledLoopRanges(), and makeTiledViews().
makeTiledLoopRanges()
static std::tuple<SmallVector<SubViewOp::Range, 4>, LoopIndexToRangeIndexMap> makeTiledLoopRanges (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > allViewSizes, ArrayRef< Value > allTileSizes, OperationFolder * folder) static
Definition at line 63 of file Tiling.cpp.
References mlir::linalg::applyMapToValues(), mlir::AffineExpr::cast(), mlir::AffineExpr::getKind(), mlir::AffineBinaryOpExpr::getLHS(), mlir::AffineMap::getNumResults(), mlir::AffineDimExpr::getPosition(), mlir::AffineBinaryOpExpr::getRHS(), isTiled(), isZero(), mlir::Mul, and mlir::linalg::Range.
Referenced by mlir::linalg::tileLinalgOp().
makeTiledViews()
static SmallVector<Value, 4> makeTiledViews (OpBuilder & b, Location loc, LinalgOp linalgOp, ArrayRef< Value > ivs, ArrayRef< Value > tileSizes, ArrayRef< Value > viewSizes, OperationFolder * folder) static
Definition at line 232 of file Tiling.cpp.
References mlir::linalg::applyMapToValues(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Operation::erase(), mlir::Value::getDefiningOp(), mlir::Value::getType(), isTiled(), isZero(), mlir::linalg::loopToOperandRangesMaps(), mlir::functional::map(), and mlir::Value::use_empty().
Referenced by mlir::linalg::tileLinalgOp().
tileLinalgOps()
static void tileLinalgOps (FuncOp f, ArrayRef< int64_t > tileSizes) static
Definition at line 422 of file Tiling.cpp.
References mlir::OpState::getContext(), mlir::linalg::tileLinalgOp(), and mlir::OpState::walk().
transformIndexedGenericOpIndices()
static void transformIndexedGenericOpIndices (OpBuilder & b, LinalgOp op, ArrayRef< ValueHandle *> pivs, const LoopIndexToRangeIndexMap & loopIndexToRangeIndex) static
Definition at line 172 of file Tiling.cpp.
References mlir::OpBuilder::create(), mlir::Value::getDefiningOp(), mlir::Value::getUses(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::linalg::tileLinalgOp().
Variable Documentation
pass
PassRegistration<LinalgTilingPass> pass("linalg-tile", "Tile operations in the linalg dialect", [] { auto pass=std::make_unique< LinalgTilingPass >();pass->tileSizes.assign(clTileSizes.begin(), clTileSizes.end());return pass;}) static
Referenced by mlir::createLinalgTilingPass().