MLIR: lib/Translation/Translation.cpp File Reference
Translation.cpp File Reference
#include "mlir/Translation.h"
#include "mlir/IR/Module.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/LogicalResult.h"
#include "llvm/Support/SourceMgr.h"
Functions
static llvm::StringMap< TranslateSourceMgrToMLIRFunction > & getMutableTranslationToMLIRRegistry ()
static llvm::StringMap< TranslateFromMLIRFunction > & getMutableTranslationFromMLIRRegistry ()
static llvm::StringMap< TranslateFunction > & getMutableTranslationRegistry ()
static void registerTranslateToMLIRFunction (StringRef name, const TranslateSourceMgrToMLIRFunction &function)
Function Documentation
getMutableTranslationFromMLIRRegistry()
static llvm::StringMap<TranslateFromMLIRFunction>& getMutableTranslationFromMLIRRegistry () static
Definition at line 32 of file Translation.cpp.
Referenced by mlir::getTranslationFromMLIRRegistry(), and mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration().
getMutableTranslationRegistry()
static llvm::StringMap<TranslateFunction>& getMutableTranslationRegistry () static
Definition at line 39 of file Translation.cpp.
Referenced by mlir::getTranslationRegistry(), and mlir::TranslateRegistration::TranslateRegistration().
getMutableTranslationToMLIRRegistry()
static llvm::StringMap<TranslateSourceMgrToMLIRFunction>& getMutableTranslationToMLIRRegistry () static
Definition at line 24 of file Translation.cpp.
Referenced by mlir::getTranslationToMLIRRegistry(), and registerTranslateToMLIRFunction().
registerTranslateToMLIRFunction()
static void registerTranslateToMLIRFunction (StringRef name, const TranslateSourceMgrToMLIRFunction & function) static
Definition at line 46 of file Translation.cpp.
References getMutableTranslationToMLIRRegistry(), and mlir::TranslateToMLIRRegistration::TranslateToMLIRRegistration().