MLIR: lib/Dialect/SPIRV/Serialization/TranslateRegistration.cpp File Reference
TranslateRegistration.cpp File Reference
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/Serialization.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Module.h"
#include "mlir/Parser.h"
#include "mlir/Support/FileUtilities.h"
#include "mlir/Translation.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
Functions
static OwningModuleRef deserializeModule (const llvm::MemoryBuffer *input, MLIRContext *context)
static LogicalResult serializeModule (ModuleOp module, raw_ostream &output)
static LogicalResult roundTripModule (llvm::SourceMgr &sourceMgr, raw_ostream &output, MLIRContext *context)
Variables
static TranslateToMLIRRegistration fromBinary ("deserialize-spirv", [](llvm::SourceMgr &sourceMgr, MLIRContext *context) { assert(sourceMgr.getNumBuffers()==1 &&"expected one buffer");return deserializeModule(sourceMgr.getMemoryBuffer(sourceMgr.getMainFileID()), context);})
static TranslateFromMLIRRegistration toBinary ("serialize-spirv", [](ModuleOp module, raw_ostream &output) { return serializeModule(module, output);})
static TranslateRegistration roundtrip ("test-spirv-roundtrip", [](llvm::SourceMgr &sourceMgr, raw_ostream &output, MLIRContext *context) { return roundTripModule(sourceMgr, output, context);})
Function Documentation
deserializeModule()
static OwningModuleRef deserializeModule (const llvm::MemoryBuffer * input, MLIRContext * context) static
Definition at line 36 of file TranslateRegistration.cpp.
References mlir::ModuleOp::create(), mlir::spirv::deserialize(), mlir::emitError(), fromBinary, mlir::FileLineColLoc::get(), mlir::UnknownLoc::get(), mlir::ModuleOp::getBody(), and mlir::Block::push_front().
roundTripModule()
static LogicalResult roundTripModule (llvm::SourceMgr & sourceMgr, raw_ostream & output, MLIRContext * context) static
Definition at line 107 of file TranslateRegistration.cpp.
References mlir::ModuleOp::create(), mlir::spirv::deserialize(), mlir::failed(), mlir::failure(), mlir::FileLineColLoc::get(), mlir::ModuleOp::getBody(), mlir::parseSourceFile(), mlir::ModuleOp::print(), mlir::Block::push_front(), roundtrip, mlir::spirv::serialize(), and mlir::success().
serializeModule()
static LogicalResult serializeModule (ModuleOp module, raw_ostream & output) static
Definition at line 74 of file TranslateRegistration.cpp.
References mlir::OpState::emitError(), mlir::failed(), mlir::failure(), mlir::spirv::serialize(), mlir::success(), toBinary, and mlir::OpState::walk().
Variable Documentation
fromBinary
TranslateToMLIRRegistration fromBinary("deserialize-spirv", [](llvm::SourceMgr &sourceMgr, MLIRContext *context) { assert(sourceMgr.getNumBuffers()==1 &&"expected one buffer");return deserializeModule(sourceMgr.getMemoryBuffer(sourceMgr.getMainFileID()), context);}) static
Referenced by deserializeModule().
roundtrip
TranslateRegistration roundtrip("test-spirv-roundtrip", [](llvm::SourceMgr &sourceMgr, raw_ostream &output, MLIRContext *context) { return roundTripModule(sourceMgr, output, context);}) static
Referenced by roundTripModule().
toBinary
TranslateFromMLIRRegistration toBinary("serialize-spirv", [](ModuleOp module, raw_ostream &output) { return serializeModule(module, output);}) static
Referenced by serializeModule().