MLIR: lib/Support/TranslateClParser.cpp File Reference
TranslateClParser.cpp File Reference
#include "mlir/Support/TranslateClParser.h"
#include "mlir/Analysis/Verifier.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Module.h"
#include "mlir/Parser.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Translation.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileUtilities.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
Functions
static LogicalResult printMLIROutput (ModuleOp module, raw_ostream &os)
Variables
static SmallVector< TranslateFunction, 16 > wrapperStorage
Function Documentation
printMLIROutput()
static LogicalResult printMLIROutput (ModuleOp module, raw_ostream & os) static
Definition at line 31 of file TranslateClParser.cpp.
References mlir::failed(), mlir::failure(), mlir::ModuleOp::print(), mlir::success(), and mlir::verify().
Referenced by mlir::TranslationParser::TranslationParser().
Variable Documentation
wrapperStorage
SmallVector<TranslateFunction, 16> wrapperStorage static
Definition at line 29 of file TranslateClParser.cpp.