MLIR: lib/Quantizer/Support/UniformConstraints.cpp File Reference
UniformConstraints.cpp File Reference
#include "mlir/Quantizer/Support/UniformConstraints.h"
#include "mlir/Dialect/QuantOps/QuantTypes.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Quantizer/Support/Configuration.h"
#include "mlir/Quantizer/Support/ConstraintAnalysisGraph.h"
#include "mlir/Quantizer/Support/Metadata.h"
#include "mlir/Quantizer/Support/Rules.h"
#include "mlir/Quantizer/Support/TypeUtils.h"
#include "mlir/Quantizer/Support/UniformSolvers.h"
#include "llvm/Support/raw_ostream.h"
Functions
static QuantizedType solveUniformType (SolverContext &solverContext, const ClusteredFacts &clusteredFacts, const CandidateQuantizedType &ct, Type originalElementType, Location loc)
Function Documentation
solveUniformType()
static QuantizedType solveUniformType (SolverContext & solverContext, const ClusteredFacts & clusteredFacts, const CandidateQuantizedType & ct, Type originalElementType, Location loc) static
Definition at line 36 of file UniformConstraints.cpp.
References mlir::quantizer::BasePropagatedFact< BinaryReducer >::assertValue(), mlir::emitError(), mlir::emitRemark(), mlir::emitWarning(), mlir::UnknownLoc::get(), mlir::quantizer::TargetConfiguration::getAllCandidateTypesMask(), mlir::quantizer::TargetConfiguration::getCandidateTypes(), mlir::quantizer::getElementOrPrimitiveType(), mlir::quantizer::CAGNode::getKind(), mlir::quantizer::SolverContext::getMlirContext(), mlir::quantizer::BasePropagatedFact< BinaryReducer >::hasValue(), mlir::quantizer::modified(), mlir::quantizer::CandidateQuantizedType::quantizedType, mlir::quantizer::CAGUniformMetadata::SalienceRequired, mlir::quantizer::CandidateQuantizedType::scheme, mlir::quantizer::CandidateQuantizedType::UniformExplicitFixedPointScale, and mlir::quantizer::CandidateQuantizedType::UniformPerLayer.