MLIR: lib/Dialect/VectorOps/VectorTransforms.cpp File Reference
VectorTransforms.cpp File Reference
#include <type_traits>
#include "mlir/Dialect/AffineOps/AffineOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/Dialect/VectorOps/VectorOps.h"
#include "mlir/Dialect/VectorOps/VectorTransforms.h"
#include "mlir/Dialect/VectorOps/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Function.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/Module.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
#include "mlir/Support/Functional.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct UnrolledVectorState
struct VectorState
Macros
#define DEBUG_TYPE "vector-to-vector"
Functions
static SmallVector< int64_t, 8 > computeStrides (ArrayRef< int64_t > shape)
Given a shape with sizes greater than 0 along all dimensions, returns the distance, in number of elements, between a slice in a dimension and the next slice in the same dimension.
static int64_t computeMaxLinearIndex (ArrayRef< int64_t > basis)
static int64_t linearize (ArrayRef< int64_t > offsets, ArrayRef< int64_t > basis)
Computes and returns the linearized index of 'offsets' w.r.t. 'basis'.
static SmallVector< int64_t, 8 > delinearize (int64_t linearIndex, ArrayRef< int64_t > basis)
Given a shape with sizes greater than 0 along all dimensions, returns the delinearized components of linearIndex along shape.
static Operation * cloneOpWithOperandsAndTypes (PatternRewriter &builder, Location loc, Operation *op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes)
static void getMappedElements (const DenseMap< int64_t, int64_t > &indexMap, ArrayRef< int64_t > inputElements, SmallVectorImpl< int64_t > &resultElements)
static TupleType generateExtractSlicesOpResultType (VectorType vectorType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, PatternRewriter &builder)
static void initUnrolledVectorState (VectorType vectorType, Value initValue, const DenseMap< int64_t, int64_t > &indexMap, ArrayRef< int64_t > targetShape, UnrolledVectorState &state, PatternRewriter &builder)
static int64_t getUnrolledVectorLinearIndex (UnrolledVectorState &state, ArrayRef< int64_t > vectorOffsets, DenseMap< int64_t, int64_t > &indexMap)
static Value getOrCreateUnrolledVectorSlice (Location loc, UnrolledVectorState &state, ArrayRef< int64_t > vectorOffsets, ArrayRef< int64_t > offsets, DenseMap< int64_t, int64_t > &indexMap, Value initValue, SmallVectorImpl< Value > &cache, PatternRewriter &builder)
static Value unrollSingleResultStructuredOp (Operation *op, ArrayRef< int64_t > iterationBounds, std::vector< VectorState > &vectors, unsigned resultIndex, ArrayRef< int64_t > targetShape, PatternRewriter &builder)
static void getVectorContractionOpUnrollState (vector::ContractionOp contractionOp, ArrayRef< int64_t > targetShape, SmallVectorImpl< int64_t > &iterationBounds, std::vector< VectorState > &vectors, unsigned &resultIndex)
static void getVectorElementwiseOpUnrollState (Operation *op, ArrayRef< int64_t > targetShape, SmallVectorImpl< int64_t > &iterationBounds, std::vector< VectorState > &vectors, unsigned &resultIndex)
static void generateTransferOpSlices (VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, ArrayRef< Value > indices, PatternRewriter &rewriter, function_ref< void(unsigned, ArrayRef< Value >)> fn)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vector-to-vector"
Definition at line 39 of file VectorTransforms.cpp.
Function Documentation
cloneOpWithOperandsAndTypes()
static Operation* cloneOpWithOperandsAndTypes (PatternRewriter & builder, Location loc, Operation * op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes) static
Definition at line 99 of file VectorTransforms.cpp.
References mlir::OpBuilder::createOperation(), mlir::Operation::getAttrs(), mlir::Operation::getName(), and mlir::OperationName::getStringRef().
Referenced by unrollSingleResultStructuredOp().
computeMaxLinearIndex()
static int64_t computeMaxLinearIndex (ArrayRef< int64_t > basis) static
Definition at line 63 of file VectorTransforms.cpp.
Referenced by generateExtractSlicesOpResultType(), initUnrolledVectorState(), and unrollSingleResultStructuredOp().
computeStrides()
static SmallVector<int64_t, 8> computeStrides (ArrayRef< int64_t > shape) static
Given a shape with sizes greater than 0 along all dimensions, returns the distance, in number of elements, between a slice in a dimension and the next slice in the same dimension.
e.g. shape[3, 4, 5] -> linearization_basis[20, 5, 1]
Definition at line 49 of file VectorTransforms.cpp.
Referenced by generateExtractSlicesOpResultType(), generateTransferOpSlices(), initUnrolledVectorState(), and unrollSingleResultStructuredOp().
delinearize()
static SmallVector<int64_t, 8> delinearize (int64_t linearIndex, ArrayRef< int64_t > basis) static
Given a shape with sizes greater than 0 along all dimensions, returns the delinearized components of linearIndex along shape.
Definition at line 83 of file VectorTransforms.cpp.
Referenced by generateExtractSlicesOpResultType(), generateTransferOpSlices(), and unrollSingleResultStructuredOp().
generateExtractSlicesOpResultType()
static TupleType generateExtractSlicesOpResultType (VectorType vectorType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, PatternRewriter & builder) static
Definition at line 126 of file VectorTransforms.cpp.
References computeMaxLinearIndex(), computeStrides(), delinearize(), mlir::VectorType::get(), mlir::TupleType::get(), mlir::Builder::getContext(), mlir::VectorType::getShape(), mlir::shapeRatio(), and mlir::functional::zipMap().
Referenced by initUnrolledVectorState().
generateTransferOpSlices()
static void generateTransferOpSlices (VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, ArrayRef< Value > indices, PatternRewriter & rewriter, function_ref< void(unsigned, ArrayRef< Value >)> fn) static
Definition at line 493 of file VectorTransforms.cpp.
References mlir::ceilDiv(), computeStrides(), mlir::PatternRewriter::create(), delinearize(), mlir::detail::enumerate(), mlir::PatternRewriter::eraseOp(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::Builder::getI64IntegerAttr(), mlir::VectorType::getShape(), mlir::TupleType::getType(), mlir::Value::getUsers(), mlir::Builder::getZeroAttr(), mlir::Value::hasOneUse(), mlir::functional::map(), mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::shapeRatio(), mlir::TupleType::size(), and mlir::functional::zipMap().
getMappedElements()
static void getMappedElements (const DenseMap< int64_t, int64_t > & indexMap, ArrayRef< int64_t > inputElements, SmallVectorImpl< int64_t > & resultElements) static
Definition at line 110 of file VectorTransforms.cpp.
Referenced by getOrCreateUnrolledVectorSlice(), getUnrolledVectorLinearIndex(), and initUnrolledVectorState().
getOrCreateUnrolledVectorSlice()
static Value getOrCreateUnrolledVectorSlice (Location loc, UnrolledVectorState & state, ArrayRef< int64_t > vectorOffsets, ArrayRef< int64_t > offsets, DenseMap< int64_t, int64_t > & indexMap, Value initValue, SmallVectorImpl< Value > & cache, PatternRewriter & builder) static
Definition at line 219 of file VectorTransforms.cpp.
References mlir::Type::cast(), mlir::PatternRewriter::create(), mlir::VectorType::get(), mlir::Builder::getI64IntegerAttr(), getMappedElements(), mlir::Value::getType(), getUnrolledVectorLinearIndex(), UnrolledVectorState::slicesTuple, and UnrolledVectorState::unrolledShape.
Referenced by unrollSingleResultStructuredOp().
getUnrolledVectorLinearIndex()
static int64_t getUnrolledVectorLinearIndex (UnrolledVectorState & state, ArrayRef< int64_t > vectorOffsets, DenseMap< int64_t, int64_t > & indexMap) static
Definition at line 206 of file VectorTransforms.cpp.
References UnrolledVectorState::basis, getMappedElements(), linearize(), and UnrolledVectorState::unrolledShape.
Referenced by getOrCreateUnrolledVectorSlice(), and unrollSingleResultStructuredOp().
getVectorContractionOpUnrollState()
static void getVectorContractionOpUnrollState (vector::ContractionOp contractionOp, ArrayRef< int64_t > targetShape, SmallVectorImpl< int64_t > & iterationBounds, std::vector< VectorState > & vectors, unsigned & resultIndex) static
Definition at line 401 of file VectorTransforms.cpp.
Referenced by mlir::vector::unrollSingleResultOpMatchingType().
getVectorElementwiseOpUnrollState()
static void getVectorElementwiseOpUnrollState (Operation * op, ArrayRef< int64_t > targetShape, SmallVectorImpl< int64_t > & iterationBounds, std::vector< VectorState > & vectors, unsigned & resultIndex) static
Definition at line 436 of file VectorTransforms.cpp.
References mlir::Type::dyn_cast_or_null(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::Operation::getResult(), and mlir::Value::getType().
Referenced by mlir::vector::unrollSingleResultOpMatchingType().
initUnrolledVectorState()
static void initUnrolledVectorState (VectorType vectorType, Value initValue, const DenseMap< int64_t, int64_t > & indexMap, ArrayRef< int64_t > targetShape, UnrolledVectorState & state, PatternRewriter & builder) static
Definition at line 175 of file VectorTransforms.cpp.
References UnrolledVectorState::basis, computeMaxLinearIndex(), computeStrides(), mlir::PatternRewriter::create(), generateExtractSlicesOpResultType(), mlir::Value::getLoc(), getMappedElements(), mlir::VectorType::getShape(), UnrolledVectorState::numInstances, mlir::shapeRatio(), UnrolledVectorState::slicesTuple, UnrolledVectorState::unrolledShape, and UnrolledVectorState::unrollFactors.
Referenced by unrollSingleResultStructuredOp().
linearize()
static int64_t linearize (ArrayRef< int64_t > offsets, ArrayRef< int64_t > basis) static
Computes and returns the linearized index of 'offsets' w.r.t. 'basis'.
Definition at line 73 of file VectorTransforms.cpp.
Referenced by getUnrolledVectorLinearIndex().
unrollSingleResultStructuredOp()
static Value unrollSingleResultStructuredOp (Operation * op, ArrayRef< int64_t > iterationBounds, std::vector< VectorState > & vectors, unsigned resultIndex, ArrayRef< int64_t > targetShape, PatternRewriter & builder) static
Definition at line 309 of file VectorTransforms.cpp.
References mlir::Type::cast(), cloneOpWithOperandsAndTypes(), computeMaxLinearIndex(), computeStrides(), mlir::PatternRewriter::create(), delinearize(), mlir::Type::dyn_cast_or_null(), mlir::VectorType::get(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), getOrCreateUnrolledVectorSlice(), mlir::Operation::getResult(), mlir::Builder::getTupleType(), mlir::Value::getType(), getUnrolledVectorLinearIndex(), initUnrolledVectorState(), mlir::shapeRatio(), and mlir::functional::zipMap().
Referenced by mlir::vector::unrollSingleResultOpMatchingType().