MLIR: lib/Dialect/VectorOps/VectorOps.cpp File Reference
VectorOps.cpp File Reference
#include "mlir/Dialect/VectorOps/VectorOps.h"
#include "mlir/Dialect/StandardOps/Ops.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/VectorOps/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Support/Functional.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Support/STLExtras.h"
#include "llvm/ADT/StringSet.h"
#include "mlir/Dialect/VectorOps/VectorOps.cpp.inc"
Namespaces
mlir
This file provides some simple template functional-style sugar to operate on value types.
mlir::vector
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static ParseResult parseContractionOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ContractionOp op)
static bool verifyDimMap (VectorType lhsType, VectorType rhsType, const std::vector< std::pair< int64_t, int64_t >> &map)
static bool verifyOutputShape (VectorType lhsType, VectorType rhsType, VectorType accType, VectorType resType, const std::vector< std::pair< int64_t, int64_t >> &contractingDimMap, const std::vector< std::pair< int64_t, int64_t >> &batchDimMap)
static LogicalResult verify (ContractionOp op)
static int64_t getResultIndex (AffineMap map, AffineExpr targetExpr)
static std::vector< std::pair< int64_t, int64_t > > getDimMap (ArrayRef< AffineMap > indexingMaps, ArrayAttr iteratorTypes, StringRef targetIteratorTypeName, MLIRContext *context)
static void print (OpAsmPrinter &p, vector::ExtractElementOp op)
static ParseResult parseExtractElementOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (vector::ExtractElementOp op)
static Type inferExtractOpResultType (VectorType vectorType, ArrayAttr position)
static void print (OpAsmPrinter &p, vector::ExtractOp op)
static ParseResult parseExtractOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (vector::ExtractOp op)
static LogicalResult isValidExtractOrInsertSlicesType (Operation *op, VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides)
static LogicalResult verify (ExtractSlicesOp op)
static void populateFromInt64AttrArray (ArrayAttr arrayAttr, SmallVectorImpl< int64_t > &results)
static LogicalResult verify (BroadcastOp op)
static void print (OpAsmPrinter &p, ShuffleOp op)
static LogicalResult verify (ShuffleOp op)
static ParseResult parseShuffleOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, InsertElementOp op)
static ParseResult parseInsertElementOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (InsertElementOp op)
static void print (OpAsmPrinter &p, InsertOp op)
static ParseResult parseInsertOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (InsertOp op)
static LogicalResult verify (InsertSlicesOp op)
static void print (OpAsmPrinter &p, InsertStridedSliceOp op)
static ParseResult parseInsertStridedSliceOp (OpAsmParser &parser, OperationState &result)
template<typename OpType >
static LogicalResult isIntegerArrayAttrSmallerThanShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName)
template<typename OpType >
static LogicalResult isIntegerArrayAttrConfinedToRange (OpType op, ArrayAttr arrayAttr, int64_t min, int64_t max, StringRef attrName, bool halfOpen=true)
template<typename OpType >
static LogicalResult isIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName, bool halfOpen=true, int64_t min=0)
template<typename OpType >
static LogicalResult isSumOfIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr1, ArrayAttr arrayAttr2, ArrayRef< int64_t > shape, StringRef attrName1, StringRef attrName2, bool halfOpen=true, int64_t min=1)
static ArrayAttr makeI64ArrayAttr (ArrayRef< int64_t > values, MLIRContext *context)
static LogicalResult verify (InsertStridedSliceOp op)
static void print (OpAsmPrinter &p, OuterProductOp op)
static ParseResult parseOuterProductOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (OuterProductOp op)
static void print (OpAsmPrinter &p, ReshapeOp op)
static ParseResult parseReshapeOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ReshapeOp op)
static Type inferStridedSliceOpResultType (VectorType vectorType, ArrayAttr offsets, ArrayAttr sizes, ArrayAttr strides)
static LogicalResult verify (StridedSliceOp op)
template<typename EmitFun >
static LogicalResult verifyPermutationMap (AffineMap permutationMap, EmitFun emitOpError)
static LogicalResult verifyTransferOp (Operation *op, MemRefType memrefType, VectorType vectorType, AffineMap permutationMap)
static void print (OpAsmPrinter &p, TransferReadOp op)
static ParseResult parseTransferReadOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (TransferReadOp op)
static LogicalResult verify (TransferWriteOp op)
static MemRefType inferVectorTypeCastResultType (MemRefType t)
static void print (OpAsmPrinter &p, TypeCastOp op)
static LogicalResult verify (TypeCastOp op)
static ParseResult parseTupleOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, TupleOp op)
static LogicalResult verify (TupleOp op)
static ParseResult parseTupleGetOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, TupleGetOp op)
static LogicalResult verify (TupleGetOp op)
static LogicalResult verify (ConstantMaskOp &op)
static LogicalResult verify (CreateMaskOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1632 of file VectorOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
getDimMap()
static std::vector<std::pair<int64_t, int64_t> > getDimMap (ArrayRef< AffineMap > indexingMaps, ArrayAttr iteratorTypes, StringRef targetIteratorTypeName, MLIRContext * context) static
Definition at line 274 of file VectorOps.cpp.
References mlir::AffineExpr::cast(), mlir::detail::enumerate(), mlir::getAffineDimExpr(), mlir::Dialect::getContext(), getIndexingMaps(), mlir::getParallelIteratorTypeName(), mlir::getReductionIteratorTypeName(), getResultIndex(), mlir::AffineMapAttr::getValue(), and mlir::functional::map().
getResultIndex()
static int64_t getResultIndex (AffineMap map, AffineExpr targetExpr) static
Definition at line 266 of file VectorOps.cpp.
References mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResult().
Referenced by getDimMap().
inferExtractOpResultType()
static Type inferExtractOpResultType (VectorType vectorType, ArrayAttr position) static
Definition at line 390 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::VectorType::get(), mlir::VectorType::getShape(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), and mlir::ArrayAttr::size().
Referenced by parseExtractOp().
inferStridedSliceOpResultType()
static Type inferStridedSliceOpResultType (VectorType vectorType, ArrayAttr offsets, ArrayAttr sizes, ArrayAttr strides) static
Definition at line 1123 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::VectorType::get(), mlir::VectorType::getShape(), mlir::Value::getType(), mlir::ArrayAttr::getValue(), mlir::vector::getVectorSubscriptAttr(), and mlir::ArrayAttr::size().
Referenced by verify().
inferVectorTypeCastResultType()
static MemRefType inferVectorTypeCastResultType (MemRefType t) static
Definition at line 1442 of file VectorOps.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::VectorType::get(), mlir::MemRefType::get(), mlir::MemRefType::getShape(), and mlir::Value::getType().
Referenced by print(), and verify().
isIntegerArrayAttrConfinedToRange()
template<typename OpType > static LogicalResult isIntegerArrayAttrConfinedToRange (OpType op, ArrayAttr arrayAttr, int64_t min, int64_t max, StringRef attrName, bool halfOpen = true) static
Definition at line 834 of file VectorOps.cpp.
References mlir::success().
Referenced by verify().
isIntegerArrayAttrConfinedToShape()
template<typename OpType > static LogicalResult isIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName, bool halfOpen = true, int64_t min = 0) static
Definition at line 854 of file VectorOps.cpp.
References mlir::ArrayAttr::size(), and mlir::success().
Referenced by verify().
isIntegerArrayAttrSmallerThanShape()
template<typename OpType > static LogicalResult isIntegerArrayAttrSmallerThanShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName) static
Definition at line 819 of file VectorOps.cpp.
References mlir::ArrayAttr::size(), and mlir::success().
Referenced by verify().
isSumOfIntegerArrayAttrConfinedToShape()
template<typename OpType > static LogicalResult isSumOfIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr1, ArrayAttr arrayAttr2, ArrayRef< int64_t > shape, StringRef attrName1, StringRef attrName2, bool halfOpen = true, int64_t min = 1) static
Definition at line 877 of file VectorOps.cpp.
References mlir::ArrayAttr::size(), and mlir::success().
Referenced by verify().
isValidExtractOrInsertSlicesType()
static LogicalResult isValidExtractOrInsertSlicesType (Operation * op, VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides) static
Definition at line 478 of file VectorOps.cpp.
References mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeSliceSizes(), mlir::computeStrides(), mlir::delinearize(), mlir::Operation::emitError(), mlir::VectorType::get(), mlir::VectorType::getShape(), mlir::TupleType::getType(), mlir::TupleType::getTypes(), mlir::TupleType::size(), and mlir::success().
Referenced by verify().
makeI64ArrayAttr()
static ArrayAttr makeI64ArrayAttr (ArrayRef< int64_t > values, MLIRContext * context) static
Definition at line 899 of file VectorOps.cpp.
References mlir::IntegerType::get(), mlir::ArrayAttr::get(), mlir::IntegerAttr::get(), and mlir::functional::map().
Referenced by verify().
parseContractionOp()
static ParseResult parseContractionOp (OpAsmParser & parser, OperationState & result) static
Definition at line 76 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::VectorType::get(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI1Type(), mlir::OpAsmParser::getNameLoc(), mlir::VectorType::getShape(), mlir::DictionaryAttr::getValue(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseTrailingOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
parseExtractElementOp()
static ParseResult parseExtractElementOp (OpAsmParser & parser, OperationState & result) static
Definition at line 361 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseExtractOp()
static ParseResult parseExtractOp (OpAsmParser & parser, OperationState & result) static
Definition at line 413 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), inferExtractOpResultType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseInsertElementOp()
static ParseResult parseInsertElementOp (OpAsmParser & parser, OperationState & result) static
Definition at line 664 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseInsertOp()
static ParseResult parseInsertOp (OpAsmParser & parser, OperationState & result) static
Definition at line 710 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseInsertStridedSliceOp()
static ParseResult parseInsertStridedSliceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 802 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseOuterProductOp()
static ParseResult parseOuterProductOp (OpAsmParser & parser, OperationState & result) static
Definition at line 956 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::VectorType::get(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseReshapeOp()
static ParseResult parseReshapeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1020 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
parseShuffleOp()
static ParseResult parseShuffleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 620 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::VectorType::get(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseTransferReadOp()
static ParseResult parseTransferReadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1351 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
parseTupleGetOp()
static ParseResult parseTupleGetOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1496 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::IntegerAttr::getInt(), mlir::TupleType::getType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::TupleType::size(), mlir::success(), and mlir::OperationState::types.
parseTupleOp()
static ParseResult parseTupleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1469 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::TupleType::get(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
populateFromInt64AttrArray()
static void populateFromInt64AttrArray (ArrayAttr arrayAttr, SmallVectorImpl< int64_t > & results) static
Definition at line 525 of file VectorOps.cpp.
References mlir::IntegerAttr::getInt().
Referenced by verify().
print() [1/13]
static void print (OpAsmPrinter & p, ContractionOp op) static
Definition at line 118 of file VectorOps.cpp.
References mlir::DictionaryAttr::get(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [2/13]
static void print (OpAsmPrinter & p, vector::ExtractElementOp op) static
Definition at line 354 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [3/13]
static void print (OpAsmPrinter & p, vector::ExtractOp op) static
Definition at line 407 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [4/13]
static void print (OpAsmPrinter & p, ShuffleOp op) static
Definition at line 579 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [5/13]
static void print (OpAsmPrinter & p, InsertElementOp op) static
Definition at line 657 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [6/13]
static void print (OpAsmPrinter & p, InsertOp op) static
Definition at line 703 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [7/13]
static void print (OpAsmPrinter & p, InsertStridedSliceOp op) static
Definition at line 796 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [8/13]
static void print (OpAsmPrinter & p, OuterProductOp op) static
Definition at line 949 of file VectorOps.cpp.
print() [9/13]
static void print (OpAsmPrinter & p, ReshapeOp op) static
Definition at line 1003 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [10/13]
static void print (OpAsmPrinter & p, TransferReadOp op) static
Definition at line 1344 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [11/13]
static void print (OpAsmPrinter & p, TypeCastOp op) static
Definition at line 1452 of file VectorOps.cpp.
References inferVectorTypeCastResultType().
print() [12/13]
static void print (OpAsmPrinter & p, TupleOp op) static
Definition at line 1482 of file VectorOps.cpp.
References mlir::interleaveComma(), mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [13/13]
static void print (OpAsmPrinter & p, TupleGetOp op) static
Definition at line 1517 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
verify() [1/20]
static LogicalResult verify (ContractionOp op) static
Definition at line 192 of file VectorOps.cpp.
References mlir::detail::enumerate(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), mlir::VectorType::getShape(), mlir::functional::map(), mlir::success(), verifyDimMap(), and verifyOutputShape().
verify() [2/20]
static LogicalResult verify (vector::ExtractElementOp op) static
Definition at line 379 of file VectorOps.cpp.
References mlir::success().
verify() [3/20]
static LogicalResult verify (vector::ExtractOp op) static
Definition at line 442 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::detail::enumerate(), mlir::vector::getVectorSubscriptAttr(), mlir::success(), and mlir::LogicalResult::value.
verify() [4/20]
static LogicalResult verify (ExtractSlicesOp op) static
Definition at line 515 of file VectorOps.cpp.
References isValidExtractOrInsertSlicesType().
verify() [5/20]
static LogicalResult verify (BroadcastOp op) static
Definition at line 543 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), and mlir::success().
verify() [6/20]
static LogicalResult verify (ShuffleOp op) static
Definition at line 586 of file VectorOps.cpp.
References mlir::detail::enumerate(), and mlir::success().
verify() [7/20]
static LogicalResult verify (InsertElementOp op) static
Definition at line 684 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), and mlir::success().
verify() [8/20]
static LogicalResult verify (InsertOp op) static
Definition at line 728 of file VectorOps.cpp.
References mlir::detail::enumerate(), and mlir::success().
verify() [9/20]
static LogicalResult verify (InsertSlicesOp op) static
Definition at line 762 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), isValidExtractOrInsertSlicesType(), and populateFromInt64AttrArray().
verify() [10/20]
static LogicalResult verify (InsertStridedSliceOp op) static
Definition at line 909 of file VectorOps.cpp.
References mlir::failed(), mlir::failure(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), isSumOfIntegerArrayAttrConfinedToShape(), makeI64ArrayAttr(), and mlir::success().
verify() [11/20]
static LogicalResult verify (OuterProductOp op) static
Definition at line 980 of file VectorOps.cpp.
References mlir::success().
verify() [12/20]
static LogicalResult verify (ReshapeOp op) static
Definition at line 1055 of file VectorOps.cpp.
References populateFromInt64AttrArray(), and mlir::success().
verify() [13/20]
static LogicalResult verify (StridedSliceOp op) static
Definition at line 1153 of file VectorOps.cpp.
References mlir::failed(), mlir::failure(), mlir::vector::getVectorSubscriptAttr(), inferStridedSliceOpResultType(), mlir::OwningRewritePatternList::insert(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), isIntegerArrayAttrSmallerThanShape(), isSumOfIntegerArrayAttrConfinedToShape(), populateFromInt64AttrArray(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
verify() [14/20]
static LogicalResult verify (TransferReadOp op) static
Definition at line 1380 of file VectorOps.cpp.
References mlir::failed(), mlir::failure(), mlir::VectorType::isValidElementType(), verifyPermutationMap(), and verifyTransferOp().
verify() [15/20]
static LogicalResult verify (TransferWriteOp op) static
Definition at line 1421 of file VectorOps.cpp.
References mlir::failed(), mlir::failure(), verifyPermutationMap(), and verifyTransferOp().
verify() [16/20]
static LogicalResult verify (TypeCastOp op) static
Definition at line 1458 of file VectorOps.cpp.
References inferVectorTypeCastResultType(), and mlir::success().
verify() [17/20]
static LogicalResult verify (TupleOp op) static
Definition at line 1490 of file VectorOps.cpp.
References mlir::success().
verify() [18/20]
static LogicalResult verify (TupleGetOp op) static
Definition at line 1524 of file VectorOps.cpp.
References mlir::Type::cast(), mlir::TupleType::getType(), mlir::TupleType::size(), and mlir::success().
verify() [19/20]
static LogicalResult verify (ConstantMaskOp & op) static
Definition at line 1548 of file VectorOps.cpp.
References mlir::detail::enumerate(), mlir::VectorType::getShape(), and mlir::success().
verify() [20/20]
static LogicalResult verify (CreateMaskOp op) static
Definition at line 1579 of file VectorOps.cpp.
References mlir::vector::getVectorSubscriptAttr(), mlir::OwningRewritePatternList::insert(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
verifyDimMap()
static bool verifyDimMap (VectorType lhsType, VectorType rhsType, const std::vector< std::pair< int64_t, int64_t >> & map) static
Definition at line 139 of file VectorOps.cpp.
References mlir::functional::map().
Referenced by verify().
verifyOutputShape()
static bool verifyOutputShape (VectorType lhsType, VectorType rhsType, VectorType accType, VectorType resType, const std::vector< std::pair< int64_t, int64_t >> & contractingDimMap, const std::vector< std::pair< int64_t, int64_t >> & batchDimMap) static
Definition at line 150 of file VectorOps.cpp.
References mlir::VectorType::getShape().
Referenced by verify().
verifyPermutationMap()
template<typename EmitFun > static LogicalResult verifyPermutationMap (AffineMap permutationMap, EmitFun emitOpError) static
Definition at line 1263 of file VectorOps.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getResults(), and mlir::success().
Referenced by verify().
verifyTransferOp()
static LogicalResult verifyTransferOp (Operation * op, MemRefType memrefType, VectorType vectorType, AffineMap permutationMap) static
Definition at line 1291 of file VectorOps.cpp.
References mlir::Operation::emitOpError(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::VectorType::getShape(), and mlir::success().
Referenced by verify().